redhat-cop/agnosticd

- ansible/configs/ansible-tower/env_vars.yml
Add configuration `ansible_tower_additional_packages` to add packages to the base package list for the ansible tower hosts.
Also adds python3 to the list of base common packages.
Config ansible-tower
> Add config ansible-tower ansible_tower_additional_packages

- ansible/roles_ocp_workloads/ocp4_workload_jenkins/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/agent_buildconfig.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/agent_imagestream.yaml.j2
Added capability to create a custom Jenkins agent image as part of the workload deploy.
ocp4_workload_jenkins
> Enable custom agent pod for Jenkins role.

- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/files/blackduck-hosts.json
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/files/insecure-bank-deployment.yml
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/files/insecure-bank-route.yml
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/files/insecure-bank-service.yml
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_synopsys_blackduck/templates/project.j2
(Opening as a DRAFT PR) This role deploys the Synopsys Black Duck integration and a demo application on an OpenShift Workshop. This is part of an effort to add RHPDS Catalog entries for our Partners, and provide the ability to perform demos and workshops. 
ocp4_workload_synopsys_blackduck
The workshop guide for users will be published on demo.openshift.com
I ran yamllint and here are the results:
```defaults/main.yml
files/insecure-bank-deployment.yml
files/insecure-bank-route.yml
files/insecure-bank-service.yml
tasks/main.yml
tasks/post_workload.yml
tasks/pre_workload.yml
tasks/remove_workload.yml
tasks/workload.yml
tasks/workload.yml
13:17     warning  truthy value should be one of [false, true]  (truthy)
```
```paste below
ansible 2.9.11
config file = None …
```
> Add role ocp4_workload_synopsys_blackduck

- ansible/roles-infra/infra-osp-template-create/.yamllint
- ansible/roles-infra/infra-osp-template-create/defaults/main.yml
- ansible/roles-infra/infra-osp-template-create/tasks/create_osp_template.yml
- ansible/roles-infra/infra-osp-template-create/tasks/get_stack_hot_outputs.yml
- ansible/roles-infra/infra-osp-template-create/tasks/main.yml
- ansible/roles-infra/infra-osp-template-create/vars/main.yml
Add retry for OpenStack template creation. On failure the stack will be deleted and recreated.
Role infra-osp-template-create
> Add role infra-osp-template-create stack retry

- ansible/configs/ansible-tower-pntae/post_software.yml
Minor edit to change the urls from https to http in message displayed for user in opentlc
```paste below
```
> change splunk and elk_stack url from https to http

- ansible/configs/rhel-security/pre_software.yml
- ansible/configs/rhel-security/software.yml
Add student user creation to all nodes deployed by this config.
rhel-security
> Create student in all nodes.

- ansible/configs/ansible-gitOps-integration/files/repos_template.j2
Baseurl changed for according to rhtr  in repos_template.j2
> baseurl changed config: ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/files/repos_template.j2
- ansible/configs/ansible-gitOps-integration/rh_event.yml
Added user, project and job template tasks in rh_event.yml
> Added user,project and job template task ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
Typo fixed in sample_vars
ansible-gitOps-integration
> Typo fixed  ansible-gitOps-integration

- ansible/configs/ocp4-workshop/software.yml
- ansible/roles/host-ocp4-installer/tasks/install_installer.yml
> Add retries to OpenShift installer download

- ansible/configs/ansible-multitier-infra/post_software.yml
- ansible/configs/ansible-multitier-infra/pre_software.yml
- ansible/configs/ansible-multitier-infra/sample_vars_osp.yml
User.info and pre_Software fixed.
> vscode role fixed

- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
> fixed vscode SG

- ansible/configs/ansible-multitier-infra/default_vars_osp.yml
Open port 80/443 on bastion for letsencrypt and done some cleanup 
config ansible-multitier-infra
> Fixed security group ansible-multitier-infra

- ansible/configs/ansible-multitier-infra/default_vars_osp.yml
fixed HostSG which had some leftovers
config: ansible-multitier-infra
> Bugfix in SG ansible-multitier-infra

- ansible/configs/smart-management/post_software.yml
- ansible/configs/smart-management/sample_vars_osp.yml
Resolving lab provisioning errors due to variable naming
Error on lab deployment
```paste below
```
> Update smart-management to fix variable errors

- ansible/configs/ansible-gitOps-integration/requirements.yml
> FLT requirement added

- ansible/configs/ansible-gitOps-integration/files/site.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
> site.yml added

- ansible/configs/smart-management/configure_satellite.yml
- ansible/configs/smart-management/post_software.yml
- ansible/configs/smart-management/sample_vars_osp.yml
> Smart management updating satellite configuration

- ansible/configs/smart-management/post_software.yml
> smart-management, adding workloads for satellite installation

- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-multitier-infra/default_vars_osp.yml
User's access details added in post_software.yml
> User access details added ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-multitier-infra/default_vars_osp.yml
Added bastions group in hosts_template.j2 for FTL
> Updated hosts_template.j2 ansible-gitOps-integration

- ansible/configs/smart-management/post_software.yml
> smart-management remove basiton variables

- ansible/configs/pntae-vilt-bastion/default_vars.yml
pntae-vilt-bastion add student_user
```paste below
```
> pntae-vilt-bastion add student_user entry

- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/tasks/remove_workload.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/tasks/workload.yaml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/create_user.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/migrate_repos.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines/defaults/main.yaml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines/templates/buildconfig-jenkins.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/create_gitea_repo.yaml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/create_gitea_user.yaml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/delete_gitea_repo.yaml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/delete_gitea_user.yaml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/templates/limitrange.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/templates/rolebinding.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/post_workload.yml
Fixes and enhancement for ocp workloads.
> Fixes and enhancements

- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/.travis.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/templates/amq-streams.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/templates/datagrid.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/templates/directive-consumer.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/templates/directive-producer.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/templates/infinispan-cluster.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/templates/kafka-cluster.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/templates/landing-page.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/templates/slack-producer.yml.j2
Fixes #2522
ocp4_workload_rhte19_shadowman
```paste below
```
> Shadowman Sprint Support for OCP4

- ansible/configs/pntae-vilt-bastion/default_vars.yml
pntae-vilt-bastion set student_password
```paste below
```
> pntae-vilt-bastion set student_password

- ansible/configs/pntae-vilt-bastion/post_software.yml
pntae-vilt-bastion agnosticd_user_info
```paste below
```
> pntae-vilt-bastion agnosticd_user_info

- ansible/roles/ocp-workload-3scale-demo/tasks/post_workload.yml
Replace the text of the email to point to the new OCP 4 console.
```paste below
```
> message rewrite

- ansible/configs/ansible-gitOps-integration/post_software.yml
> Bookbag role included

- ansible/configs/ansible-gitOps-integration/post_software.yml
> bookbag added go bastion

- ansible/configs/ansible-gitOps-integration/post_software.yml
> Bookbag ocp

- ansible/configs/ansible-tower-pntae/post_software.yml
ansible-tower-pntae: use tower license
```paste below
```
> ansible-tower-pntae use tower license

- ansible/roles-infra/infra-ec2-template-generate/tasks/locate_availability_zones_tasks.yml
Read-only command task should have `changed_when: false`
> Add changed_when to command task

- ansible/configs/ansible-workshops/vars/tower_advanced_users_workshop_vars.yml
> adding tower advanced users workshop var file

- ansible/configs/ansible-workshops/vars/tower_advanced_users_workshop_vars.yml
Adding vars with {{ RHPDS input }} value
```paste below
```
> Adv tower wks

- ansible/roles/ocp4-workload-ccnrd/tasks/install-username-distribution.yaml
Update username-distribution to 1.4 version in CCN Dev Track along with:
Support account request via POST - https://github.com/RedHat-Middleware-Workshops/username-distribution/pull/6
Fixed persistent data issue - https://github.com/RedHat-Middleware-Workshops/username-distribution/pull/4
```paste below
```
> Update username-distribution to 1.4 version in CCN Dev Track

- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/tasks/workload.yml
For the specified role:
- added a yamllint file
- made code changes to ensure correct formatting
ocp4_workload_argocd_operator
> added yamllint for ocp4_workload_argocd_operator

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml
Update username-distribution to 1.4 version in Quarkus workshop along with:
Support account request via POST - RedHat-Middleware-Workshops/username-distribution#6
Fixed persistent data issue - RedHat-Middleware-Workshops/username-distribution#4
```paste below
```
> Update username-distribution to 1.4 version in Quarkus workshop

- ansible/roles/ocp4-workload-jdg-workshop/tasks/install-username-distribution.yaml
Update username-distribution to 1.4 version in DG workshop along with:
Support account request via POST - RedHat-Middleware-Workshops/username-distribution#6
Fixed persistent data issue - RedHat-Middleware-Workshops/username-distribution#4
```paste below
```
> Update username-distribution to 1.4 version in DG workshop

- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/tasks/workload.yaml
Add user.info to bookbag user role if oauth is enabled
> Add message for login with oauth to user info.

- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/create_gitea_repo.yaml
> Fix gitea repo creation

- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/templates/buildconfig-jenkins.yaml.j2
Add logic to pipeline in buildconfig
Up the quota
> Updates to buildconfig and quota for pipelines lab

- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/.yamllint
For the specified role:
- Modified yamllint files to remove two space requirement before comments
ocp4_workload_bookbag_setup
ocp4_workload_lbookbag_user
> yamllint modified in ocp4_workload_bookbag* roles

- ansible/roles/agnosticd_dynamic/.yamllint
- ansible/roles/agnosticd_dynamic/tasks/install-galaxy-source-to-cache.yaml
- ansible/roles/agnosticd_dynamic/tasks/install-galaxy-sources-to-dynamic-roles-dir.yaml
> yamllint formatting cleanup for role agnosticd_dynamic

- ansible/roles/bookbag/.yamllint
- Modified yamllint file to enforce formatting rules
bookbag
> updated yamllint file in role bookbag

- ansible/cloud_providers/azure_infrastructure_deployment.yml
- ansible/cloud_providers/gcp_infrastructure_deployment.yml
- ansible/configs/ocp4-cluster/default_vars_azure.yml
- ansible/configs/ocp4-cluster/files/cloud_providers/azure_cloud_template.j2
- ansible/configs/ocp4-cluster/post_infra.yml
- ansible/roles-infra/infra-azure-ssh-key/a
- ansible/roles-infra/infra-azure-ssh-key/defaults/main.yml
- ansible/roles-infra/infra-azure-ssh-key/tasks/main.yml
- ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml
Updating a use of keyvault to improve concurrency and removing a few deprecated functions
cloud_providers/azure
cloud_providers/gcp
roles-infra/infra-azure-ssh-key
N/A
> Update config/ocp4-cluster on Azure to improve performance

- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_codeready_workspaces/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_codeready_workspaces/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_codeready_workspaces/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_codeready_workspaces/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_codeready_workspaces/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_codeready_workspaces/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_dm7_foundations_elt/.yamllint
For the specified role:
- added yamllint file to ocp4_workload_codeready_workspaces role
- cleaned code up as per formatting requirements
- tightened formatting warnings into errors for the future in the codeready_workspaces roles, the bookbag_setup role, and the dm7_foundations_elt role
ocp4_workload_codeready_workspaces
> Cleanup formatting in ocp4_workload_codeready_workspaces role

- ansible/roles/a_simple_webserver/.travis.yml
- ansible/roles/a_simple_webserver/.yamllint
- ansible/roles/a_simple_webserver/tasks/install.yml
- ansible/roles/a_simple_webserver/tasks/main.yml
- ansible/roles/a_simple_webserver/tasks/pre_install.yml
- ansible/roles/a_simple_webserver/tasks/smoketest.yml
> yamllint formatting cleanup for role a_simple_webserver

- ansible/roles/git-copy-files/.yamllint
- ansible/roles/git-copy-files/files/apache-setup.yml
- ansible/roles/git-copy-files/tasks/main.yml
> yamllint formatting cleanup for role git-copy-files

- ansible/roles/ocp4-workload-homeroomlab-starter-guides/defaults/main.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/php-is.yml
Update Starter Guide for Homeroom to 4.5
* Updated `lab_repo` to latest branch available from https://github.com/openshift-labs/starter-guides
* Update PHP custom ImageStream to 7.3 pointing to quay.io/osevg/php-s2i
> Change role ocp4-workload-homeroomlab-starter-guides default lab image

- ansible/roles/eap7-dev/.yamllint
- ansible/roles/eap7-dev/defaults/main.yml
- ansible/roles/eap7-dev/tasks/packages.yml
> yamllint formatting cleanup for role eap7-dev

- ansible/configs/kni-osp/default_vars.yml
Remove Google's `dns_nameserver` from `appnet` network
kni-osp
> Fix dns nameserver

- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/doc-svc.j2
Small fix: Updated the Documentation service definition to include the right `namespace` name.
Documentation Service Template
> Updated service template to include the svc name

- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/workload.yml
Fixed an issue with the route checking.
`k8s_info`
The route created sucessfully, but the `k8s_info` was checking the wrong field. This PR fixes this issue.
> updated route check task

- ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/route.yaml.j2
Bugfix. Had wrong apiVersion in the jenkins remove workload
> Fix apiversion in jenkins remove

- ansible/roles/ocp4-workload-kube-federation/.yamllint
- ansible/roles/ocp4-workload-kube-federation/defaults/main.yml
- ansible/roles/ocp4-workload-kube-federation/tasks/post_workload.yml
- ansible/roles/ocp4-workload-kube-federation/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-kube-federation/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-kube-federation/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-kube-federation

- ansible/roles/ocp4-workload-istio-tutorial-student/.yamllint
- ansible/roles/ocp4-workload-istio-tutorial-student/defaults/main.yml
- ansible/roles/ocp4-workload-istio-tutorial-student/tasks/deployment_wait.yml
- ansible/roles/ocp4-workload-istio-tutorial-student/tasks/post_workload.yml
- ansible/roles/ocp4-workload-istio-tutorial-student/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-istio-tutorial-student/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-istio-tutorial-student/tasks/workload.yml
ocp4-workload-istio-tutorial-student
> yamllint formatting cleanup for role ocp4-workload-istio-tutorial-student

- ansible/roles/ocp4-workload-build-your-own-operator/.yamllint
- ansible/roles/ocp4-workload-build-your-own-operator/defaults/main.yml
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/pre_remove_workload.yml
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/workload.yml
ocp4-workload-build-your-own-operator
> yamllint formatting cleanup for role ocp4-workload-build-your-own-operator

- ansible/roles/ocp4-workload-er-demo/.yamllint
- ansible/roles/ocp4-workload-er-demo/defaults/main.yml
- ansible/roles/ocp4-workload-er-demo/tasks/main.yml
- ansible/roles/ocp4-workload-er-demo/tasks/post_workload.yml
- ansible/roles/ocp4-workload-er-demo/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-er-demo/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-er-demo/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-er-demo

- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/.yamllint
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/defaults/main.yml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/files/deploy_certs.yml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/files/router-with-certs.yaml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/files/router-without-certs.yaml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/tasks/post_workload.yml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/tasks/workload.yml
ocp4-workload-enable-lets-encrypt-certificates
> yamllint formatting cleanup for role ocp4-workload-enable-lets-encrypt-certificates

- ansible/roles/gitlab-config/.yamllint
- ansible/roles/gitlab-config/defaults/main.yml
- ansible/roles/gitlab-config/tasks/create-group.yml
- ansible/roles/gitlab-config/tasks/create-project.yml
- ansible/roles/gitlab-config/tasks/create-user.yml
> yamllint formatting cleanup for role gitlab-config

- ansible/roles/ocp4-workload-cnvlab/.yamllint
- ansible/roles/ocp4-workload-cnvlab/defaults/main.yml
- ansible/roles/ocp4-workload-cnvlab/files/cnv-admin.yaml
- ansible/roles/ocp4-workload-cnvlab/files/project.yaml
- ansible/roles/ocp4-workload-cnvlab/tasks/post_workload.yml
- ansible/roles/ocp4-workload-cnvlab/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-cnvlab/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-cnvlab/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-cnvlab

- ansible/roles/ocp4-workload-enable-service-broker/.yamllint
- ansible/roles/ocp4-workload-enable-service-broker/defaults/main.yml
- ansible/roles/ocp4-workload-enable-service-broker/files/service_catalog_api_server.yaml
- ansible/roles/ocp4-workload-enable-service-broker/files/service_catalog_controller_manager.yaml
- ansible/roles/ocp4-workload-enable-service-broker/tasks/post_workload.yml
- ansible/roles/ocp4-workload-enable-service-broker/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-enable-service-broker/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-enable-service-broker/tasks/workload.yml
ocp4-workload-enable-service-broker
> yamllint formatting cleanup for role ocp4-workload-enable-service-broker

- ansible/roles/ocp4-workload-ceph/.yamllint
- ansible/roles/ocp4-workload-ceph/defaults/main.yml
- ansible/roles/ocp4-workload-ceph/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-ceph

- ansible/roles/ocp4-workload-infra-nodes/.yamllint
- ansible/roles/ocp4-workload-infra-nodes/defaults/main.yml
- ansible/roles/ocp4-workload-infra-nodes/files/cluster-monitoring-config.yml
- ansible/roles/ocp4-workload-infra-nodes/tasks/post_workload.yml
- ansible/roles/ocp4-workload-infra-nodes/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-infra-nodes/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-infra-nodes/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-infra-nodes

- ansible/roles/host-ocp-installer/.yamllint
- ansible/roles/host-ocp-installer/tasks/main.yml
> yamllint formatting cleanup for role host-ocp-installer

- ansible/roles/host-ocp-node/.yamllint
- ansible/roles/host-ocp-node/tasks/install_crio_for_openshift.yml
- ansible/roles/host-ocp-node/tasks/install_docker_for_openshift.yml
- ansible/roles/host-ocp-node/tasks/main.yml
- ansible/roles/host-ocp-node/tasks/packages.yml
- ansible/roles/host-ocp-node/tasks/post_docker.yml
- ansible/roles/host-ocp-node/tasks/sysctl.yml
> yamllint formatting cleanup for role host-ocp-node

- ansible/roles/ocp4-workload-cost-uploader/.yamllint
- ansible/roles/ocp4-workload-cost-uploader/defaults/main.yml
- ansible/roles/ocp4-workload-cost-uploader/tasks/post_workload.yml
- ansible/roles/ocp4-workload-cost-uploader/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-cost-uploader/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-cost-uploader/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-cost-uploader

- ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/defaults/main.yml
Add a new intro of lab guides
```paste below
```
> Update role ocp4_workload_quarkus_workshop_user to set m3 path

- ansible/roles/ocp4-workload-machinesets/.yamllint
- ansible/roles/ocp4-workload-machinesets/defaults/main.yml
- ansible/roles/ocp4-workload-machinesets/files/cluster-monitoring-config.yml
- ansible/roles/ocp4-workload-machinesets/tasks/post_workload.yml
- ansible/roles/ocp4-workload-machinesets/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-machinesets/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-machinesets/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-machinesets

- ansible/roles/ocp4-workload-project-request-template/.yamllint
- ansible/roles/ocp4-workload-project-request-template/defaults/main.yml
- ansible/roles/ocp4-workload-project-request-template/files/openshift-ingress-namespace.yaml
- ansible/roles/ocp4-workload-project-request-template/tasks/post_workload.yml
- ansible/roles/ocp4-workload-project-request-template/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-project-request-template/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-project-request-template/tasks/workload.yml
ocp4-workload-project-request-template
> yamllint formatting cleanup for role ocp4-workload-project-request-template

- ansible/roles/ocp4-workload-istio-workshop-homeroom/.yamllint
- ansible/roles/ocp4-workload-istio-workshop-homeroom/defaults/main.yml
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/post_workload.yml
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/workload.yml
ocp4-workload-istio-workshop-homeroom
> yamllint formatting cleanup for role ocp4-workload-istio-workshop-homeroom

- ansible/roles/ocp4-workload-istio-controlplane-student/.yamllint
- ansible/roles/ocp4-workload-istio-controlplane-student/defaults/main.yml
- ansible/roles/ocp4-workload-istio-controlplane-student/tasks/post_workload.yml
- ansible/roles/ocp4-workload-istio-controlplane-student/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-istio-controlplane-student/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-istio-controlplane-student/tasks/workload.yml
ocp4-workload-istio-controlplane-student
> yamllint formatting cleanup for role ocp4-workload-istio-controlplane-student

- ansible/roles/ocp4-workload-cluster-autoscale/.yamllint
- ansible/roles/ocp4-workload-cluster-autoscale/defaults/main.yml
- ansible/roles/ocp4-workload-cluster-autoscale/tasks/post_workload.yml
- ansible/roles/ocp4-workload-cluster-autoscale/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-cluster-autoscale/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-cluster-autoscale/tasks/workload.yml
ocp4-workload-cluster-autoscale
> yamllint formatting cleanup for role ocp4-workload-cluster-autoscale

- ansible/roles/vscode-server/tasks/vscode-server.yml
Minor fix  done for downloaded vscode extension list task to make role idempotent.
> minor fix role:vscode-server

- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/workload.yml
Add a bigger limitrange to pipelines project.
ocp4_workload_rhtr_pipelines
> Added LimitRange for pipelines project

- ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/post_workload.yml
Remove unnecessary information in the final email notification.
```paste below
```
> Update post_workload.yml to remove unnecessary information in the final email notification 

- ansible/roles/ocp-workload-bxms-pam-foundations/.yamllint
- ansible/roles/ocp-workload-bxms-pam-foundations/defaults/main.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/tasks/post_workload.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/tasks/pre_workload.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/tasks/remove_workload.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/tasks/workload.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/templates/rhpam-dev-businesscentral.yaml
- ansible/roles/ocp-workload-bxms-pam-foundations/templates/rhpam-dev-kieserver.yaml
> yamllint formatting cleanup for ocp-workload-bxms-pam-foundations

- ansible/configs/sap-hana/files/cloud_providers/osp_cloud_template_master.j2
This commit is in the same vein as #2789
Add missing dependencies in resources in the Heat Template
> Change sapa-hana, Fix dependencies of resources in sap-hana HOT

- ansible/roles/ocp-infra-enable-custom-catalog/.yamllint
- ansible/roles/ocp-infra-enable-custom-catalog/tasks/main.yml
ocp-infra-enable-custom-catalog
> yamllint formatting cleanup for ocp-infra-enable-custom-catalog

- ansible/roles/ocp4-workload-template-service-broker/.yamllint
- ansible/roles/ocp4-workload-template-service-broker/defaults/main.yml
- ansible/roles/ocp4-workload-template-service-broker/files/service_catalog_api_server.yaml
- ansible/roles/ocp4-workload-template-service-broker/files/service_catalog_controller_manager.yaml
- ansible/roles/ocp4-workload-template-service-broker/tasks/post_workload.yml
- ansible/roles/ocp4-workload-template-service-broker/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-template-service-broker/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-template-service-broker/tasks/test.yaml
- ansible/roles/ocp4-workload-template-service-broker/tasks/workload.yml
ocp4-workload-template-service-broker
> yamllint formatting cleanup for role ocp4-workload-template-service-broker

- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/deployment.yaml.j2
Fix for crashing bookbag on oc apply.
> Update requests/limits for bookbag

- ansible/roles/ocp-workload-bxms-pam/.yamllint
- ansible/roles/ocp-workload-bxms-pam/defaults/main.yml
- ansible/roles/ocp-workload-bxms-pam/tasks/configure_repository.yml
- ansible/roles/ocp-workload-bxms-pam/tasks/post_workload.yml
- ansible/roles/ocp-workload-bxms-pam/tasks/pre_workload.yml
- ansible/roles/ocp-workload-bxms-pam/tasks/remove_workload.yml
- ansible/roles/ocp-workload-bxms-pam/tasks/workload.yml
- ansible/roles/ocp-workload-bxms-pam/templates/nexus3-persistent-template.yaml
- ansible/roles/ocp-workload-bxms-pam/templates/rhpam-dev-businesscentral.yaml
- ansible/roles/ocp-workload-bxms-pam/templates/rhpam-dev-kieserver.yaml
> yamllint formatting cleanup for ocp-workload-bxms-pam

- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/deployment.yaml.j2
Add startup/liveness/readiness probes to bookbag deployment.
> Add Health Checks to bookbag

- ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/tasks/workload_amq_streams.yml
- ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/tasks/workload_amq_streams_operator.yml
- ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/tasks/workload_gitea.yml
For the specifed role:
- Created yamllint file
- Shortened some lines in workload_amq_stream.yml, workload_amq_streams_operator.yml and workload_gitea.yml
- Fixed indentation in workload_amq_streams_operator.yml
- Code Cleanup 
ocp4_workload_amq_streams_dev_exp
> cleanup ocp4_workload_amq_streams_dev_exp role yamllint warnings

- ansible/roles_ocp_workloads/ocp4_workload_authentication/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_authentication/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_authentication/files/oauth-htpasswd.yaml
- ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/workload.yml
For the specified role:
- added yamllint file to ocp4_workload_authentication role
- cleaned code up as per formatting requirements
- tightened formatting warnings into errors for the future
> Cleanup ocp4_workload-authentication role formatting

- ansible/roles/ocp-workload-example/.yamllint
- ansible/roles/ocp-workload-example/defaults/main.yml
- ansible/roles/ocp-workload-example/tasks/post_workload.yml
- ansible/roles/ocp-workload-example/tasks/pre_workload.yml
- ansible/roles/ocp-workload-example/tasks/remove_workload.yml
- ansible/roles/ocp-workload-example/tasks/workload.yml
> yamllint formatting cleanup for ocp-workload-example

- ansible/roles_ocp_workloads/ocp4_workload_le_certificates/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_le_certificates/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_le_certificates/files/deploy_certs.yaml
- ansible/roles_ocp_workloads/ocp4_workload_le_certificates/files/router-without-certs.yaml
- ansible/roles_ocp_workloads/ocp4_workload_le_certificates/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_le_certificates/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_le_certificates/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_le_certificates/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_logging/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_logging/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_logging/files/eo_namespace.yaml
- ansible/roles_ocp_workloads/ocp4_workload_logging/files/eo_operatorgroup.yaml
- ansible/roles_ocp_workloads/ocp4_workload_logging/files/eo_role.yaml
- ansible/roles_ocp_workloads/ocp4_workload_logging/files/eo_rolebinding.yaml
- ansible/roles_ocp_workloads/ocp4_workload_logging/files/logging_curator_configmap.yaml
- ansible/roles_ocp_workloads/ocp4_workload_logging/files/logging_namespace.yaml
- ansible/roles_ocp_workloads/ocp4_workload_logging/files/logging_operatorgroup.yaml
- ansible/roles_ocp_workloads/ocp4_workload_logging/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_logging/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_logging/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_logging/tasks/workload.yml
ocp4_workload_le_certificates
ocp4_workload_logging
> Cleanup ocp4_workload_le_certificates and ocp4_workload_logging roles

- ansible/roles/ocp-workload-openshift-applier/.yamllint
- ansible/roles/ocp-workload-openshift-applier/tasks/post_workload.yml
- ansible/roles/ocp-workload-openshift-applier/tasks/pre_workload.yml
- ansible/roles/ocp-workload-openshift-applier/tasks/remove_workload.yml
- ansible/roles/ocp-workload-openshift-applier/tasks/workload.yml
ocp-workload-openshift-applier
> yamllint formatting cleanup for ocp-workload-openshift-applier

- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/deployment.yaml.j2
Remove Probes - caused more issues than benefits...
> Remove probes from bookbag pods

- ansible/roles/ocp-infra-osp-fip/.yamllint
- ansible/roles/ocp-infra-osp-fip/tasks/main.yml
> yamllint formatting cleanup for ocp-infra-osp-fip

- ansible/roles_studentvm/studentvm_amq_foundations/.yamllint
- ansible/roles_studentvm/studentvm_amq_foundations/meta/main.yml
- ansible/roles_studentvm/studentvm_amq_foundations/tasks/main.yml
- ansible/roles_studentvm/studentvm_bash_prompt/.yamllint
- ansible/roles_studentvm/studentvm_bash_prompt/meta/main.yml
- ansible/roles_studentvm/studentvm_bash_prompt/tasks/main.yml
- ansible/roles_studentvm/studentvm_java_development/.yamllint
- ansible/roles_studentvm/studentvm_java_development/meta/main.yml
- ansible/roles_studentvm/studentvm_java_development/tasks/main.yml
- ansible/roles_studentvm/studentvm_ocp4/.yamllint
- ansible/roles_studentvm/studentvm_ocp4/meta/main.yml
- ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
- ansible/roles_studentvm/studentvm_user/.yamllint
- ansible/roles_studentvm/studentvm_user/meta/main.yml
- ansible/roles_studentvm/studentvm_user/tasks/main.yml
studentvm_amq_foundations 
studentvm_bash_prompt 
studentvm_java_development
studentvm_ocp4
studentvm_user
> yamllint formatting cleanup for studentvm_* roles

- ansible/roles/ocp4-workload-projectreaper-operator/.yamllint
- ansible/roles/ocp4-workload-projectreaper-operator/defaults/main.yml
- ansible/roles/ocp4-workload-projectreaper-operator/tasks/post_workload.yml
- ansible/roles/ocp4-workload-projectreaper-operator/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-projectreaper-operator/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-projectreaper-operator/tasks/workload.yml
ocp4-workload-projectreaper-operator
> yamllint formatting cleanup for role ocp4-workload-projectreaper-operator

- ansible/roles/ocp-workload-terminal/.yamllint
- ansible/roles/ocp-workload-terminal/defaults/main.yml
- ansible/roles/ocp-workload-terminal/tasks/post_workload.yml
- ansible/roles/ocp-workload-terminal/tasks/pre_workload.yml
- ansible/roles/ocp-workload-terminal/tasks/remove_workload.yml
- ansible/roles/ocp-workload-terminal/tasks/workload.yml
> yamllint formatting cleanup for ocp-workload-terminal

- ansible/roles/ocp-workload-rhte19-shadowman/.yamllint
- ansible/roles/ocp-workload-rhte19-shadowman/tasks/idle_workload.yml
- ansible/roles/ocp-workload-rhte19-shadowman/tasks/post_workload.yml
- ansible/roles/ocp-workload-rhte19-shadowman/tasks/pre_workload.yml
- ansible/roles/ocp-workload-rhte19-shadowman/tasks/remove_workload.yml
- ansible/roles/ocp-workload-rhte19-shadowman/tasks/workload.yml
> yamllint formatting cleanup for ocp-workload-rhte19-shadowman

- ansible/roles/ocp_workload_shared_cluster_access/.yamllint
- ansible/roles/ocp_workload_shared_cluster_access/defaults/main.yml
- ansible/roles/ocp_workload_shared_cluster_access/tasks/post_workload.yml
ocp_workload_shared_cluster_access
> yamllint formatting cleanup for ocp_workload_shared_cluster_access

- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/.yamllint
- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/defaults/main.yml
- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/files/codeready-workspaces-operator-installer/custom-resource.yaml
- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/tasks/post_workload.yml
- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/tasks/pre_workload.yml
- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/tasks/remove_workload.yml
- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/tasks/wait_for_build.yml
- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/tasks/wait_for_deploy.yml
- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/tasks/workload.yml
ocp-workload-rhte19-optaplanner-101-lab-infra
> yamllint formatting cleanup for ocp-workload-rhte19-optaplanner-101-lab-infra

- ansible/roles/ocp-workload-rhte-mw-msa-orchestration/.yamllint
- ansible/roles/ocp-workload-rhte-mw-msa-orchestration/defaults/main.yml
- ansible/roles/ocp-workload-rhte-mw-msa-orchestration/tasks/pre_workload.yml
- ansible/roles/ocp-workload-rhte-mw-msa-orchestration/tasks/remove_workload.yml
- ansible/roles/ocp-workload-rhte-mw-msa-orchestration/tasks/wait_for_build.yml
- ansible/roles/ocp-workload-rhte-mw-msa-orchestration/tasks/wait_for_deploy.yml
- ansible/roles/ocp-workload-rhte-mw-msa-orchestration/tasks/workload.yml
ocp-workload-rhte-mw-msa-orchestration
> yamllint formatting cleanup for ocp-workload-rhte-mw-msa-orchestration

- ansible/roles/ocp-workload-rhte-mw-msa-mesh/.yamllint
- ansible/roles/ocp-workload-rhte-mw-msa-mesh/defaults/main.yml
- ansible/roles/ocp-workload-rhte-mw-msa-mesh/tasks/pre_workload.yml
- ansible/roles/ocp-workload-rhte-mw-msa-mesh/tasks/remove_workload.yml
- ansible/roles/ocp-workload-rhte-mw-msa-mesh/tasks/wait_for_dc.yml
- ansible/roles/ocp-workload-rhte-mw-msa-mesh/tasks/wait_for_deploy.yml
- ansible/roles/ocp-workload-rhte-mw-msa-mesh/tasks/workload.yml
- ansible/roles/ocp-workload-rhte-mw-msa-mesh/templates/app-config.yaml
- ansible/roles/ocp-workload-rhte-mw-msa-mesh/templates/coolstore-catalog-mongodb-persistent.yaml
- ansible/roles/ocp-workload-rhte-mw-msa-mesh/templates/coolstore-gateway.yaml
> yamllint formatting cleanup for ocp-workload-rhte-mw-msa-mesh

- ansible/roles/ocp-workload-rhte-mw-bfield-migration/.yamllint
- ansible/roles/ocp-workload-rhte-mw-bfield-migration/defaults/main.yml
- ansible/roles/ocp-workload-rhte-mw-bfield-migration/tasks/pre_workload.yml
- ansible/roles/ocp-workload-rhte-mw-bfield-migration/tasks/remove_workload.yml
- ansible/roles/ocp-workload-rhte-mw-bfield-migration/tasks/workload.yml
ocp-workload-rhte-mw-bfield-migration
> yamllint formatting cleanup for ocp-workload-rhte-mw-bfield-migration

- ansible/roles/ocp-workload-rhte-mw-api-mesh/.yamllint
- ansible/roles/ocp-workload-rhte-mw-api-mesh/tasks/pre_workload.yml
- ansible/roles/ocp-workload-rhte-mw-api-mesh/tasks/remove_workload.yml
- ansible/roles/ocp-workload-rhte-mw-api-mesh/tasks/wait_for_build.yml
- ansible/roles/ocp-workload-rhte-mw-api-mesh/tasks/wait_for_dc.yml
- ansible/roles/ocp-workload-rhte-mw-api-mesh/tasks/wait_for_deploy.yml
- ansible/roles/ocp-workload-rhte-mw-api-mesh/tasks/workload.yml
- ansible/roles/ocp-workload-rhte-mw-api-mesh/templates/app-config.yaml
- ansible/roles/ocp-workload-rhte-mw-api-mesh/templates/coolstore-catalog-mongodb-persistent.yaml
> yamllint formatting cleanup for ocp-workload-rhte-mw-api-mesh

- ansible/roles/ocp-workload-rhte-mw-api-biz/.yamllint
- ansible/roles/ocp-workload-rhte-mw-api-biz/defaults/main.yml
- ansible/roles/ocp-workload-rhte-mw-api-biz/tasks/main.yml
- ansible/roles/ocp-workload-rhte-mw-api-biz/tasks/pre_workload.yml
- ansible/roles/ocp-workload-rhte-mw-api-biz/tasks/remove_workload.yml
- ansible/roles/ocp-workload-rhte-mw-api-biz/tasks/wait_for_build.yml
- ansible/roles/ocp-workload-rhte-mw-api-biz/tasks/wait_for_deploy.yml
- ansible/roles/ocp-workload-rhte-mw-api-biz/tasks/workload.yml
> yamllint formatting cleanup for ocp-workload-rhte-mw-api-biz

- ansible/roles/ocp-workload-reactive-pipelines/.yamllint
- ansible/roles/ocp-workload-reactive-pipelines/defaults/main.yml
- ansible/roles/ocp-workload-reactive-pipelines/tasks/main.yml
- ansible/roles/ocp-workload-reactive-pipelines/tasks/post_workload.yml
- ansible/roles/ocp-workload-reactive-pipelines/tasks/pre_workload.yml
- ansible/roles/ocp-workload-reactive-pipelines/tasks/remove_workload.yml
- ansible/roles/ocp-workload-reactive-pipelines/tasks/workload.yml
ocp-workload-reactive-pipelines
> yamllint formatting cleanup for ocp-workload-reactive-pipelines

- ansible/roles/ocp-workload-integreatly/.yamllint
- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/post_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/pre_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/remove_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
> yamllint formatting cleanup for ocp-workload-integreatly

- ansible/roles/ocp-workload-fuse-on-ocp/.yamllint
- ansible/roles/ocp-workload-fuse-on-ocp/defaults/main.yml
- ansible/roles/ocp-workload-fuse-on-ocp/tasks/pre_workload.yml
- ansible/roles/ocp-workload-fuse-on-ocp/tasks/remove_workload.yml
- ansible/roles/ocp-workload-fuse-on-ocp/tasks/wait_for_build.yml
- ansible/roles/ocp-workload-fuse-on-ocp/tasks/wait_for_deploy.yml
- ansible/roles/ocp-workload-fuse-on-ocp/tasks/workload.yml
> yamllint formatting cleanup for ocp-workload-fuse-on-ocp

- ansible/roles/ocp-workload-fsi-cc-dispute-demo/.yamllint
- ansible/roles/ocp-workload-fsi-cc-dispute-demo/defaults/main.yml
- ansible/roles/ocp-workload-fsi-cc-dispute-demo/tasks/post_workload.yml
- ansible/roles/ocp-workload-fsi-cc-dispute-demo/tasks/pre_workload.yml
- ansible/roles/ocp-workload-fsi-cc-dispute-demo/tasks/remove_workload.yml
- ansible/roles/ocp-workload-fsi-cc-dispute-demo/tasks/wait_for_build.yml
- ansible/roles/ocp-workload-fsi-cc-dispute-demo/tasks/wait_for_deploy.yml
- ansible/roles/ocp-workload-fsi-cc-dispute-demo/tasks/workload.yml
ocp-workload-fsi-cc-dispute-demo
> yamllint formatting cleanup for ocp-workload-fsi-cc-dispute-demo

- ansible/roles_ocp_workloads/ocp4_workload_authentication/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_authentication/templates/cluster_role_binding.j2
- ansible/roles_ocp_workloads/ocp4_workload_authentication/templates/htpasswd.j2
Add support for creating multiple admin users with ocp4_workload_authentication
> Add ocp4_workload_authentication support for multiple admin users

- ansible/roles/ocp4-workload-quay-operator/.yamllint
- ansible/roles/ocp4-workload-quay-operator/defaults/main.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/post_workload.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-quay-operator

- ansible/roles/ocp4-workload-openbanking-sandbox/tasks/pre_workload.yml
> corrected the lxml version in virtualenv

- ansible/roles/ocp4-workload-openbanking-sandbox/tasks/pre_workload.yml
> Fsi bank - fixed perms adding become:true to task

- ansible/configs/kni-osp/files/named.conf.j2
- ansible/configs/kni-osp/files/ocp-install.sh.j2
- ansible/configs/kni-osp/post_software.yml
- ansible/configs/kni-osp/software.yml
DNS Forwarder IP was wrong and ironic client will need to be installed for the rhtr kni lab
> [kni-osp] DNS Forwarder Changes and adding a required package for the lab

- ansible/roles/ocp4-workload-debezium-demo/defaults/main.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/post_workload.yml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_e2e_demo.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_registry.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_streams.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_webapp.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/workload.yml
- ansible/roles/ocp4-workload-debezium-demo/templates/elasticsearch.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/extra-services.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connect.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connector-elastic.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-demo.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-topic.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/registry-operatorgroup.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/registry-subscription.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/registry.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/webapp.yaml.j2
- Update the versions to reflect 2020 Q3 release
- Add the service registry as a component available for debezium use
change data capture with debezium
```paste below
```
> update to q3, add registry

- ansible/roles/ocp4-workload-authentication/.yamllint
- ansible/roles/ocp4-workload-authentication/defaults/main.yml
- ansible/roles/ocp4-workload-authentication/files/oauth-htpasswd.yaml
- ansible/roles/ocp4-workload-authentication/tasks/post_workload.yml
- ansible/roles/ocp4-workload-authentication/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-authentication/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-authentication/tasks/workload.yml
> yamllint formatting cleanup for roles/ocp4-workload-authentication

- ansible/roles/ocp-workload-rhte-mw-op-intel/.yamllint
- ansible/roles/ocp-workload-rhte-mw-op-intel/defaults/main.yml
- ansible/roles/ocp-workload-rhte-mw-op-intel/tasks/pre_workload.yml
- ansible/roles/ocp-workload-rhte-mw-op-intel/tasks/remove_workload.yml
- ansible/roles/ocp-workload-rhte-mw-op-intel/tasks/spark_workload.yml
- ansible/roles/ocp-workload-rhte-mw-op-intel/tasks/strimzi_workload.yml
- ansible/roles/ocp-workload-rhte-mw-op-intel/tasks/wait_for_build.yml
- ansible/roles/ocp-workload-rhte-mw-op-intel/tasks/wait_for_deploy.yml
> yamllint formatting cleanup for ocp-workload-rhte-mw-op-intel

- ansible/roles/ocp-workload-fsi-client-onboarding-demo/.yamllint
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/defaults/main.yml
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/files/client-onboarding-process.yaml
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/files/secrets-and-accounts.yaml
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/tasks/post_workload.yml
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/tasks/pre_workload.yml
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/tasks/remove_workload.yml
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/tasks/wait_for_build.yml
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/tasks/wait_for_deploy.yml
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/tasks/workload.yml
ocp-workload-fsi-client-onboarding-demo
> yamllint formatting cleanup for ocp-workload-fsi-client-onboarding-demo

- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/tasks/open_data_hub.yml
- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/templates/open-data-hub/jupyterhub-single-user-profile-user.configmap.yml.j2
removed lable on single user profile
> updated jupyter pre-load configs

- ansible/roles/ocp-workload-parksmap-demo/.yamllint
- ansible/roles/ocp-workload-parksmap-demo/defaults/main.yml
- ansible/roles/ocp-workload-parksmap-demo/files/workshop-mlbparks.yaml
- ansible/roles/ocp-workload-parksmap-demo/files/workshop-nationalparks.yaml
- ansible/roles/ocp-workload-parksmap-demo/files/workshop-parksmap.yaml
- ansible/roles/ocp-workload-parksmap-demo/files/workshopper-template.yaml
- ansible/roles/ocp-workload-parksmap-demo/tasks/post_workload.yml
- ansible/roles/ocp-workload-parksmap-demo/tasks/pre_workload.yml
- ansible/roles/ocp-workload-parksmap-demo/tasks/remove_workload.yml
- ansible/roles/ocp-workload-parksmap-demo/tasks/workload.yml
> yamllint formatting cleanup for ocp-workload-parksmap-demo

- ansible/configs/ocp4-workshop/.yamllint
- ansible/configs/ocp4-workshop/destroy_cluster.yml
- ansible/configs/ocp4-workshop/destroy_env.yml
- ansible/configs/ocp4-workshop/env_vars.yml
- ansible/configs/ocp4-workshop/files/kubelet-bootstrap-cred-manager-ds.yaml
- ansible/configs/ocp4-workshop/lifecycle.yml
- ansible/configs/ocp4-workshop/mgr_users.yml
- ansible/configs/ocp4-workshop/ocp_workloads.yml
- ansible/configs/ocp4-workshop/post_infra.yml
- ansible/configs/ocp4-workshop/post_software.yml
- ansible/configs/ocp4-workshop/pre_infra.yml
- ansible/configs/ocp4-workshop/software.yml
> yamllint formatting cleanup for role ocp4-workshop

- ansible/configs/hacluster-pntae/.yamllint
- ansible/configs/hacluster-pntae/default_vars.yml
- ansible/configs/hacluster-pntae/default_vars_osp.yml
- ansible/configs/hacluster-pntae/post_infra.yml
- ansible/configs/hacluster-pntae/post_software.yml
- ansible/configs/hacluster-pntae/pre_infra.yml
- ansible/configs/hacluster-pntae/pre_software.yml
- ansible/configs/hacluster-pntae/sample_vars/private-dns-osp.yml
- ansible/configs/hacluster-pntae/sample_vars_ec2.yml
- ansible/configs/hacluster-pntae/sample_vars_osp.yml
- ansible/configs/hacluster-pntae/setup_lab_user.yml
- ansible/configs/hacluster-pntae/software.yml
- ansible/configs/hacluster-pntae/start.yml
- ansible/configs/hacluster-pntae/stop.yml
> yamllint formatting cleanup for role hacluster-pntae

- ansible/configs/ocp4-ha-lab/.yamllint
- ansible/configs/ocp4-ha-lab/default_vars.yml
- ansible/configs/ocp4-ha-lab/destroy_cluster.yml
- ansible/configs/ocp4-ha-lab/destroy_env.yml
- ansible/configs/ocp4-ha-lab/files/oauth-htpasswd.yaml
- ansible/configs/ocp4-ha-lab/files/oauth-opentlc-ldap.yaml
- ansible/configs/ocp4-ha-lab/mgr_users.yml
- ansible/configs/ocp4-ha-lab/ocp_workloads.yml
- ansible/configs/ocp4-ha-lab/post_infra.yml
- ansible/configs/ocp4-ha-lab/post_software.yml
- ansible/configs/ocp4-ha-lab/pre_infra.yml
- ansible/configs/ocp4-ha-lab/pre_software.yml
- ansible/configs/ocp4-ha-lab/sample_vars.yaml
- ansible/configs/ocp4-ha-lab/software.yml
> yamllint formatting cleanup for role ocp4-ha-lab

- ansible/configs/ocp4-disconnected-osp-lab/.yamllint
- ansible/configs/ocp4-disconnected-osp-lab/default_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/files/pvc-registry.yaml
- ansible/configs/ocp4-disconnected-osp-lab/post_infra.yml
- ansible/configs/ocp4-disconnected-osp-lab/post_software.yml
- ansible/configs/ocp4-disconnected-osp-lab/pre_infra.yml
- ansible/configs/ocp4-disconnected-osp-lab/pre_software.yml
- ansible/configs/ocp4-disconnected-osp-lab/sample_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
> yamllint formatting cleanup for role ocp4-disconnected-osp-lab

- ansible/configs/ocp-workshop/.yamllint
- ansible/configs/ocp-workshop/destroy_env.yml
- ansible/configs/ocp-workshop/env_tests.yml
- ansible/configs/ocp-workshop/env_vars.yml
- ansible/configs/ocp-workshop/files/prometheus_alerts_rules.yml
- ansible/configs/ocp-workshop/mgr_users.yml
- ansible/configs/ocp-workshop/ocp_workloads.yml
- ansible/configs/ocp-workshop/post_infra.yml
- ansible/configs/ocp-workshop/post_software.yml
- ansible/configs/ocp-workshop/pre_infra.yml
- ansible/configs/ocp-workshop/pre_software.yml
- ansible/configs/ocp-workshop/scaleup.yml
- ansible/configs/ocp-workshop/software.yml
> yamllint formatting cleanup for config role ocp-workshop

- ansible/configs/ocp-storage-cns/.yamllint
- ansible/configs/ocp-storage-cns/destroy_env.yml
- ansible/configs/ocp-storage-cns/env_vars.yml
- ansible/configs/ocp-storage-cns/post_infra.yml
- ansible/configs/ocp-storage-cns/post_ocp_nfs_config.yml
- ansible/configs/ocp-storage-cns/post_software.yml
- ansible/configs/ocp-storage-cns/pre_infra.yml
- ansible/configs/ocp-storage-cns/pre_software.yml
- ansible/configs/ocp-storage-cns/software.yml
> yamllint formatting cleanup for config role ocp-storage-cns

- ansible/configs/ocp-workshop-with-clientvms/.yamllint
- ansible/configs/ocp-workshop-with-clientvms/destroy_env.yml
- ansible/configs/ocp-workshop-with-clientvms/env_tests.yml
- ansible/configs/ocp-workshop-with-clientvms/env_vars.yml
- ansible/configs/ocp-workshop-with-clientvms/files/prometheus_alerts_rules.yml
- ansible/configs/ocp-workshop-with-clientvms/mgr_users.yml
- ansible/configs/ocp-workshop-with-clientvms/ocp_workloads.yml
- ansible/configs/ocp-workshop-with-clientvms/post_infra.yml
- ansible/configs/ocp-workshop-with-clientvms/post_software.yml
- ansible/configs/ocp-workshop-with-clientvms/pre_infra.yml
- ansible/configs/ocp-workshop-with-clientvms/pre_software.yml
- ansible/configs/ocp-workshop-with-clientvms/scaleup.yml
- ansible/configs/ocp-workshop-with-clientvms/software.yml
> yamllint formatting cleanup for config role ocp-workshop-with-client-vms

- ansible/configs/ocp4-workshop/software.yml
Fix for error during yamllint formatting where a `_` became a `-`.
config ocp4-workshop
> Fix config ocp4-workshop ocp4_installer_version var

- ansible/roles/ocp4-workload-debezium-demo/defaults/main.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_e2e_demo.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_mysql_demo.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_pgsql_demo.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_registry.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_webapp.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-debezium-demo/tasks/workload.yml
- ansible/roles/ocp4-workload-debezium-demo/templates/configmap-e2e-init-sql.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/configmap-pgsql-init-sql.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/elasticsearch-ss-patch.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/elasticsearch.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connect.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connector-camel-elastic.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connector-camel-sql.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-demo.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-topic.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/oauthclient.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/postgresql.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/registry.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/webapp.yaml.j2
- Update variables with `proper names` 
- Add postgresql as a replication target for the complete scenario
ocp4-workload-debezium-demo
```paste below
```
> Fix role ocp4-workload-debezium-demo to use proper var names

- ansible/configs/ocp-storage-cns/.yamllint
- ansible/configs/ocp-storage-cns/destroy_env.yml
- ansible/configs/ocp-storage-cns/env_vars.yml
- ansible/configs/ocp-storage-cns/post_infra.yml
- ansible/configs/ocp-storage-cns/post_ocp_nfs_config.yml
- ansible/configs/ocp-storage-cns/post_software.yml
- ansible/configs/ocp-storage-cns/pre_infra.yml
- ansible/configs/ocp-storage-cns/pre_software.yml
- ansible/configs/ocp-storage-cns/software.yml
Style cleanup for ocp-storage-cns for yamllint
- Cleanup Pull Request
config ocp-storage-cns
> Cleanup config ocp-storage-cns for yamllint

- ansible/configs/ocp-ha-disconnected-lab/.yamllint
- ansible/configs/ocp-ha-disconnected-lab/aws_test.yml
- ansible/configs/ocp-ha-disconnected-lab/destroy_env.yml
- ansible/configs/ocp-ha-disconnected-lab/env_vars.yml
- ansible/configs/ocp-ha-disconnected-lab/files/prometheus_alerts_rules.yml
- ansible/configs/ocp-ha-disconnected-lab/post_infra.yml
- ansible/configs/ocp-ha-disconnected-lab/post_ocp_nfs_config.yml
- ansible/configs/ocp-ha-disconnected-lab/post_software.yml
- ansible/configs/ocp-ha-disconnected-lab/pre_infra.yml
- ansible/configs/ocp-ha-disconnected-lab/pre_software.yml
- ansible/configs/ocp-ha-disconnected-lab/software.yml
> yamllint formatting cleanup for config role ocp-ha-disconnected-lab

- ansible/configs/three-tier-app/.yamllint
- ansible/configs/three-tier-app/default_vars.yml
- ansible/configs/three-tier-app/default_vars_osp.yml
- ansible/configs/three-tier-app/post_infra.yml
- ansible/configs/three-tier-app/post_software.yml
- ansible/configs/three-tier-app/pre_infra.yml
- ansible/configs/three-tier-app/pre_software.yml
- ansible/configs/three-tier-app/sample_vars/private-dns-osp.yml
- ansible/configs/three-tier-app/sample_vars_ec2.yml
- ansible/configs/three-tier-app/sample_vars_osp.yml
- ansible/configs/three-tier-app/setup_lab_user.yml
- ansible/configs/three-tier-app/software.yml
- ansible/configs/three-tier-app/start.yml
- ansible/configs/three-tier-app/stop.yml
> yamllint formatting cleanup for config role three-tier-app

- ansible/configs/osp-satellite-vm/.yamllint
- ansible/configs/osp-satellite-vm/env_vars.yml
- ansible/configs/osp-satellite-vm/infra.yml
- ansible/configs/osp-satellite-vm/instance_loop.yml
- ansible/configs/osp-satellite-vm/post_infra.yml
- ansible/configs/osp-satellite-vm/pre_infra.yml
- ansible/configs/osp-satellite-vm/pull_repo.yml
> yamllint formatting cleanup for role osp-satellite-vm

- ansible/configs/osp-sandbox/.yamllint
- ansible/configs/osp-sandbox/default_vars.yml
- ansible/configs/osp-sandbox/post_infra.yml
- ansible/configs/osp-sandbox/post_software.yml
- ansible/configs/osp-sandbox/pre_infra.yml
- ansible/configs/osp-sandbox/pre_software.yml
- ansible/configs/osp-sandbox/sample_vars.yml
- ansible/configs/osp-sandbox/software.yml
> yamllint formatting cleanup for role osp-sandbox

- ansible/configs/osp-migration/.yamllint
- ansible/configs/osp-migration/env_vars.yml
- ansible/configs/osp-migration/infra.yml
- ansible/configs/osp-migration/instance_loop.yml
- ansible/configs/osp-migration/post_infra.yml
- ansible/configs/osp-migration/pre_infra.yml
- ansible/configs/osp-migration/pull_repo.yml
> yamllint formatting cleanup for role osp-migrations

- ansible/configs/openshift-demos/.yamllint
- ansible/configs/openshift-demos/create_oc_config.yml
- ansible/configs/openshift-demos/env_vars.yml
- ansible/configs/openshift-demos/imagebuild-pipeline.yml
- ansible/configs/openshift-demos/msa-cicd-eap-full.yml
- ansible/configs/openshift-demos/msa-cicd-eap-min.yml
- ansible/configs/openshift-demos/undeploy.yml
- ansible/configs/openshift-demos/unidle.yml
- ansible/configs/openshift-demos/verify_all.yml
- ansible/configs/openshift-demos/verify_tasks.yml
> yamllint formatting cleanup for role openshift-demos

- ansible/configs/studentvm/.yamllint
- ansible/configs/studentvm/default_vars.yml
- ansible/configs/studentvm/default_vars_ec2.yml
- ansible/configs/studentvm/default_vars_osp.yml
- ansible/configs/studentvm/post_infra.yml
- ansible/configs/studentvm/post_software.yml
- ansible/configs/studentvm/pre_software.yml
- ansible/configs/studentvm/sample_vars/studentvm_aws_bare_bones.yml
- ansible/configs/studentvm/sample_vars/studentvm_aws_ocp4.yml
- ansible/configs/studentvm/sample_vars/studentvm_aws_with_student_user.yml
- ansible/configs/studentvm/sample_vars/studentvm_osp_bare_bones.yml
- ansible/configs/studentvm/sample_vars/studentvm_osp_ocp4.yml
- ansible/configs/studentvm/sample_vars/studentvm_osp_with_student_user.yml
- ansible/configs/studentvm/software.yml
- ansible/configs/studentvm/studentvm-role.yml
> yamllint formatting cleanup to config role studentvm

- ansible/configs/amq-messaging-foundations/.yamllint
- ansible/configs/amq-messaging-foundations/default_vars.yml
- ansible/configs/amq-messaging-foundations/default_vars_ec2.yml
- ansible/configs/amq-messaging-foundations/default_vars_osp.yml
- ansible/configs/amq-messaging-foundations/post_infra.yml
- ansible/configs/amq-messaging-foundations/post_software.yml
- ansible/configs/amq-messaging-foundations/pre_software.yml
- ansible/configs/amq-messaging-foundations/requirements-ruby.yml
- ansible/configs/amq-messaging-foundations/software.yml
> yamllint formatting cleanup for role amq-messaging-foundations

- ansible/configs/simple-example/.yamllint
- ansible/configs/simple-example/destroy_env.yml
- ansible/configs/simple-example/env_vars.yml
- ansible/configs/simple-example/post_infra.yml
- ansible/configs/simple-example/post_software.yml
- ansible/configs/simple-example/pre_infra.yml
- ansible/configs/simple-example/pre_software.yml
- ansible/configs/simple-example/sample_vars.yml
- ansible/configs/simple-example/software.yml
> yamllint formatting cleanup for role simple-example

- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/satellite-infrastructure/requirements.yml
Windows image updated in files/cloud_providers
config: ansible-windows
> updated windows images

- ansible/configs/ocp4-workshop/env_vars.yml
- ansible/configs/ocp4-workshop/post_software.yml
- ansible/configs/ocp4-workshop/software.yml
Add vars to ocp4-workshop config to select which user info messages to show.
Config ocp4-workshop
> Add config ocp4-workshop user info vars

- ansible/configs/ocp4-cluster/default_vars.yml
- ansible/configs/ocp4-cluster/post_infra.yml
- ansible/configs/ocp4-cluster/post_software.yml
Add variables to ocp4-cluster config to select which user info messages to report. This will be used to prune email content sent to RHTR lab participants.
> Add config ocp4-cluster user info vars

- .github/workflows/lfs.yml
Disabled LFS check earlier due to failures, but it is working again now.
> Enable LFS GitHub check

- ansible/configs/satellite-vm/.yamllint
- ansible/configs/satellite-vm/default_vars.yml
- ansible/configs/satellite-vm/default_vars_ec2.yml
- ansible/configs/satellite-vm/default_vars_osp.yml
- ansible/configs/satellite-vm/destroy_env.yml
- ansible/configs/satellite-vm/post_infra.yml
- ansible/configs/satellite-vm/post_software.yml
- ansible/configs/satellite-vm/pre_infra.yml
- ansible/configs/satellite-vm/pre_software.yml
- ansible/configs/satellite-vm/sample_vars_ec2.yml
- ansible/configs/satellite-vm/sample_vars_osp.yml
- ansible/configs/satellite-vm/software.yml
- ansible/configs/satellite-vm/start.yml
- ansible/configs/satellite-vm/stop.yml
> yamllint formatting cleanup for role satellite-vm

- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/ansible-windows/post_software.yml
- ansible/configs/satellite-infrastructure/requirements.yml
user.info added to config
config: ansible-windows
> user.info updated 

- ansible/configs/ocp4-cluster/default_vars.yml
- ansible/configs/ocp4-cluster/default_vars_osp.yml
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Add more support for OCP 4.6 for ocp4-cluster on OSP.
ocp4-cluster
> Enable cluster ocp46

- ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/post_workload.yml
Current text includes "for <USER NAME>", which reads a bit weird because it will only ever be a message for that one user. This also addresses a long line in the source.
role ocp4_workload_quarkus_workshop_user
> Change role ocp4_workload_quarkus_workshop_user module user info

- ansible/configs/satellite-multi-region/.yamllint
- ansible/configs/satellite-multi-region/deploy_stack.yml
- ansible/configs/satellite-multi-region/destroy_env.yml
- ansible/configs/satellite-multi-region/env_vars.yml
- ansible/configs/satellite-multi-region/post_infra.yml
- ansible/configs/satellite-multi-region/post_software.yml
- ansible/configs/satellite-multi-region/pre_infra.yml
- ansible/configs/satellite-multi-region/pre_software.yml
- ansible/configs/satellite-multi-region/sample_vars.yml
- ansible/configs/satellite-multi-region/software.yml
> yamllint formatting cleanup for role satellite-multi-region

- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/create_gitea_repo.yaml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/create_gitea_user.yaml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/delete_gitea_repo.yaml
- ansible/roles_ocp_workloads/ocp4_workload_rhtr_pipelines_user/tasks/delete_gitea_user.yaml
Bug fix: add retries to the 4 Gitea methods (create/delete user/repository).
ocp4_workload_rhtr_pipelines
> Add retries to Gitea methods for ocp4_pipelines lab

- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/tasks/open_data_hub.yml
- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/tasks/per_user_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/tasks/postgresql.yml
- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/tasks/single_user_pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/tasks/user_project.yml
- ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/tasks/workload.yml
Fix role ocp4_workload_ml_workflows_user remove workload. There was a bug in how `user_namespace` was set. While fixing this also switched to using best practice variable naming, starting with the role name: `ocp4_workload_ml_workflows_user_namespace`.
Also add `.yamllint`.
Role ocp4_workload_ml_workflows_user
> Fix role ocp4_workload_ml_workflows_user remove workload

- ansible/configs/ocp4-workshop/software.yml
> Add retry to tasks using mirror.openshift.com

- ansible/configs/ansible-multitier-infra/default_vars.yml
- ansible/configs/ansible-multitier-infra/default_vars_ec2.yml
- ansible/configs/ansible-multitier-infra/files/hosts_template.j2
- ansible/configs/ansible-multitier-infra/post_software.yml
- ansible/configs/ansible-multitier-infra/pre_software.yml
config ansible-multitier-infra needed extending to enable visual-studio-code in production
Recent changes also had lost the devops user's ssh config breaking the labs. Restored
(This should be added in the future to the control users role)
> Fix config ansible multitier infra

- ansible/configs/ansible-multitier-infra/files/repos_template.j2
> EPEL error fixed

- ansible/roles/ocp4-workload-ccnrd/files/stack.Dockerfile
- ansible/roles/ocp4-workload-ccnrd/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
Upgrade Red Hat Build Of Quarkus 1.7 and relavant CRW base image, Kn, Tkn, GraalVM versions
```paste below
```
> Upgrade Red Hat Build Of Quarkus 1.7

- ansible/configs/ans-tower-lab-ng/post_software.yml
tower-credential role added in config
config: ansible-tower-lab-ng
> Credential role added ansible-tower-lab-ng

- ansible/configs/selinux-policy/.yamllint
- ansible/configs/selinux-policy/destroy_env.yml
- ansible/configs/selinux-policy/env_vars.yml
- ansible/configs/selinux-policy/post_infra.yml
- ansible/configs/selinux-policy/post_software.yml
- ansible/configs/selinux-policy/pre_infra.yml
- ansible/configs/selinux-policy/pre_software.yml
- ansible/configs/selinux-policy/sample_vars.yml
- ansible/configs/selinux-policy/software.yml
> yamllint formatting cleanup for role selinux-policy

- ansible/configs/ans-tower-lab-ng/post_software.yml
> replaced role with task ans-tower-lab-ng

- ansible/configs/satellite-infrastructure/.yamllint
- ansible/configs/satellite-infrastructure/default_vars.yml
- ansible/configs/satellite-infrastructure/default_vars_ec2.yml
- ansible/configs/satellite-infrastructure/default_vars_osp.yml
- ansible/configs/satellite-infrastructure/destroy_env.yml
- ansible/configs/satellite-infrastructure/post_infra.yml
- ansible/configs/satellite-infrastructure/post_software.yml
- ansible/configs/satellite-infrastructure/pre_infra.yml
- ansible/configs/satellite-infrastructure/pre_software.yml
- ansible/configs/satellite-infrastructure/sample_vars_ec2.yml
- ansible/configs/satellite-infrastructure/sample_vars_osp.yml
- ansible/configs/satellite-infrastructure/satellite_workloads.yml
- ansible/configs/satellite-infrastructure/software.yml
- ansible/configs/satellite-infrastructure/start.yml
- ansible/configs/satellite-infrastructure/stop.yml
> yamllint formatting cleanup for role satellite-infrastructure

- ansible/configs/ocp4-cluster/destroy_env_osp.yml
Fix wrong indentation of image destroy tasks.
ocp4-cluster
> Fix ocp4-cluster destroy

- ansible/roles/ocp-workload-dm7-realtime-event-decisioning/tasks/workload.yml
Hotfix (terrible....) to remove LimitRange from DM7 project to ensure the pods redeploy. Developer will need to figure out how to add proper requests/limits for CPU and Memory for all pods...
ocp-workload-dm7-realtime-event-decisioning
> Hotfix to make DM7 Demo work

- ansible/configs/ans-tower-lab-ng/default_vars_osp.yml
- ansible/configs/ans-tower-lab-ng/post_software.yml
- ansible/configs/ans-tower-lab-ng/pre_software.yml
- ansible/configs/ans-tower-lab-ng/sample_vars/osp_vars.yml
modified:   configs/ans-tower-lab-ng/default_vars_osp.yml
modified:   configs/ans-tower-lab-ng/post_software.yml
modified:   configs/ans-tower-lab-ng/pre_software.yml
modified:   configs/ans-tower-lab-ng/sample_vars/osp_vars.yml
Tested config on pink cluster.
Components Installed:
1. Ansible Tower Lab with VScode on control node.
2. Ansible Tower software delpoyed
> Tested on Pink cluster with and without Ansible tower installed

- ansible/configs/ocp4-cluster/default_vars.yml
- ansible/configs/ocp4-cluster/files/fio-test-job.yaml.j2
- ansible/configs/ocp4-cluster/files/fio-test.sh
- ansible/configs/ocp4-cluster/files/fio.Dockerfile
- ansible/configs/ocp4-cluster/post_software.yml
- ansible/configs/ocp4-cluster/workloads.yml
This PR has changes that updates the `ocp4-cluster` config with some additional functionality around fio performance testing. Specifically, it will allow for infinite or finite running of the test when deploying a cluster.
ocp4-cluster
> Update ocp4-cluster config for fio performance test

- ansible/configs/ans-tower-lab-ng/files/clouds.yaml.j2
> clouds.yaml added

- ansible/configs/ocp4-cluster/default_vars_gcp.yml
> comment out gcp_region as default

- ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile
- ansible/roles/ocp4-workload-quarkus-workshop/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/templates/devfile.json.j2
Update ocp4-workload-quarkus-workshop to upgrade RHBQ 1.7
```paste below
```
> Update ocp4-workload-quarkus-workshop to upgrade RHBQ 1.7

- ansible/configs/ans-tower-lab-ng/post_software.yml
- ansible/configs/ans-tower-lab-ng/sample_vars/homework_ec2_vars.yml
user.info fixed
post_software.yaml
> user info fixed

- ansible/configs/ans-tower-lab-ng/default_vars_osp.yml
bastion name changed to control
```paste below
```
> bastion name changed to control

- ansible/configs/ansible-multitier-infra/post_software.yml
> User info upadted

- ansible/configs/ocp4-cluster/default_vars.yml
- ansible/configs/ocp4-workshop/env_vars.yml
- ansible/configs/ocp4-workshop/software.yml
- ansible/roles/host-ocp4-installer/tasks/install_installer.yml
- ansible/roles_ocp_workloads/ocp4_workload_pipelines/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
- ansible/roles_studentvm/studentvm_ocp4/defaults/main.yml
- ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
Added support for variable `ocp4_installer_root_url` which by default is set to the CloudFront mirror.
ocp4-cluster
ocp4-workshop
studentvm_ocp4
> Added support for ocp4_installer_root_url where necessary. 

- ansible/configs/ansible-multitier-infra/files/clouds.yaml.j2
- ansible/configs/ansible-multitier-infra/post_software.yml
> added bookbag stuff

- ansible/configs/ansible-multitier-infra/post_software.yml
tower license injector task added in post_software.yml
config: ansible-multitier-infra
> tower license added to ansible-multitier-infra

- ansible/configs/cloud-credentials/post_infra.yml
Cosmetic fix for the `user.info` to change to a more generic base DNS domain instead of sandbox zone.
cloud-credentials
> Update config cloud-credentials

- ansible/configs/ansible-multitier-infra/post_software.yml
> userinfo updated

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/post_workload.yml
The `agnosticd_user_info` data vars were missing. This adds them.
> Update role ocp4_workload_rhacm

- ansible/roles_studentvm/studentvm_user/tasks/main.yml
Line length was too long for yamllint. Fixes.
ocp4_studentvm_user
> Update role ocp4_studentvm_user line length

- ansible/configs/three-tier-app/post_software.yml
- ansible/configs/three-tier-app/pre_software.yml
Updated pre and post software to run on Novello
1: Done some cleanup
2: Control-user role added to pre_software.yml
3: User info updated in post_software.yml
config: three-tier-app
> control-user and user.info updated

- ansible/configs/smart-management/post_software.yml
> Added bookbag

- ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml
Add additional retries and checks to downloading the kn cli
> Add more checks (and retries) to kn download

- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/README.adoc
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/tasks/remove_workload_dm.yml
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/tasks/workload_dm.yml
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/clusterresourcequota.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/dm/dm-bc-dc.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/dm/dm-bc-route.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/dm/dm-bc-service-ping.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/dm/dm-bc-service.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/dm/dm-ks-dc.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/dm/dm-ks-route.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/dm/dm-ks-service-ping.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/dm/dm-ks-service.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/dm/dm-sa-rolebinding.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/dm/dm-service-account.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/image-pull-secret.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/imagestream.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/limitrange.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/namespace-admin-rb.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/namespace.j2
- ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/pvc.j2
Role for the GPTE Decision Manager 7 Experienced course
The current DM7 Experienced ELABs run on OpenShift 3.11 on Novello. This new role moves the workload to a shared OCP 4.x cluster.
role name: ocp4_workload_dm7_exp_elt
Role for the GPTE Decision Manager 7 Experienced ELT courses
Targets shared OCP 4.4 cluster
Deploys the following components:
* DM Business central v 7.8
* DM KIE Server v7.8
All components are verified to be up and running by verifying the number of readyReplicas in the deployment status.
> Add role for the GPTE Decision Manager 7 Experienced courses

- ansible/configs/smart-management/post_software.yml
Updating user info for bookbag use.
```paste below
```
> smart-management updating user info for RHTR bookbag

- .gitignore
- ansible/roles/ocp4-workload-ccnrd/files/ccn-community-operators.yaml
- ansible/roles/ocp4-workload-ccnrd/files/ccn-redhat-operators-cs.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
Fix ocp4-workload-ccnrd to create CCN CatalogResource
```paste below
```
> Fix ocp4-workload-ccnrd to create CCN CatalogResource

- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
Update ocp4-workload-ccnrd to fix CCN catalog sources in a loop
```paste below
```
> Update ocp4-workload-ccnrd to fix CCN catalog sources in a loop

- ansible/configs/smart-management/post_software.yml
learners were having issues with the devops user, defaulting to admin user
```paste below
```
> Hotfix for RHTR Remediation Lab, updating tower login credentials

- ansible/configs/smart-management/post_software.yml
{"msg": "'tower_admin_password' is undefined"}
> tower admin password issue fixed

- ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/files/console_operator.yaml
> Fix Travis

- ansible/configs/smart-management-foundations/default_vars.yml
- ansible/configs/smart-management-foundations/destroy_env.yml
- ansible/configs/smart-management-foundations/pre_software.yml
> smart-management-foundations update for install_student_user role

- ansible/roles/ocp4-workload-ccnrd/files/amqstreams_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/codeready_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/elasticsearch_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/jaeger_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/kafka_knative_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/kiali_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/pipelines_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/serverless_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
Update ocp4-workload-ccnrd to remove snapshot images
```paste below
```
> Update ocp4-workload-ccnrd to remove snapshot images

- ansible/roles/bastion-student-user/.yamllint
- ansible/roles/bastion-student-user/defaults/main.yml
- ansible/roles/bastion-student-user/tasks/main.yml
> yamllint formatting cleanup for role bastion-student-user

- ansible/roles/satellite-public-hostname/.yamllint
- ansible/roles/satellite-public-hostname/tasks/main.yml
> yamllint formatting cleanup for role satellite-public-hostname

- ansible/roles/tower-user-create/.yamllint
- ansible/roles/tower-user-create/tasks/main.yml
> yamllint formatting cleanup for role tower-user-create

- ansible/roles/satellite-manage-repositories/.yamllint
- ansible/roles/satellite-manage-repositories/tasks/version_6.x.yml
> yamllint formatting cleanup for role satellite-manage-repositories

- ansible/roles/satellite-manage-manifest/.yamllint
- ansible/roles/satellite-manage-manifest/tasks/version_6.x.yml
> yamllint formatting cleanup for role satellite-manage-manifest

- ansible/roles/tower-pip-packages/.yamllint
- ansible/roles/tower-pip-packages/tasks/main.yml
> yamllint formatting cleanup for role tower-pip-packages

- ansible/configs/ocp4-workshop/files/status.j2
- ansible/configs/ocp4-workshop/lifecycle.yml
- ansible/configs/ocp4-workshop/templates/status.j2
- ansible/lifecycle_ec2.yml
- ansible/lifecycle_osp.yml
Add user info output for status so that it can be run through Ansible tower with Babylon.
Status playbooks and ocp4-workshop config
> Add status output user info

- ansible/configs/ocp4-disconnected-osp-lab/software.yml
Once again @ritesh97-rh YAMLLINT updates broke one of our environments.
> Fix Cert request for OCP 4 HA Lab

- ansible/configs/rhte-oc-cluster-vms/.yamllint
- ansible/configs/rhte-oc-cluster-vms/destroy_env.yml
- ansible/configs/rhte-oc-cluster-vms/env_vars.yml
- ansible/configs/rhte-oc-cluster-vms/mgr_users.yml
- ansible/configs/rhte-oc-cluster-vms/post_infra.yml
- ansible/configs/rhte-oc-cluster-vms/post_software.yml
- ansible/configs/rhte-oc-cluster-vms/pre_infra.yml
- ansible/configs/rhte-oc-cluster-vms/pre_software.yml
- ansible/configs/rhte-oc-cluster-vms/software.yml
> yamllint formatting cleanup for role rhte-oc-cluster-vms

- ansible/configs/rhel-container-security/.yamllint
- ansible/configs/rhel-container-security/destroy_env.yml
- ansible/configs/rhel-container-security/env_vars.yml
- ansible/configs/rhel-container-security/post_infra.yml
- ansible/configs/rhel-container-security/post_software.yml
- ansible/configs/rhel-container-security/pre_infra.yml
- ansible/configs/rhel-container-security/pre_software.yml
- ansible/configs/rhel-container-security/sample_vars.yml
- ansible/configs/rhel-container-security/software.yml
> yamllint formatting cleanup for role rhel-container-security

- ansible/roles/gitlab-server/.yamllint
- ansible/roles/gitlab-server/defaults/main.yml
- ansible/roles/gitlab-server/tasks/install-gitlab-server.yml
> yamllint formatting cleanup for role gitlab-server

- ansible/roles/host-ocp-nfs/.yamllint
- ansible/roles/host-ocp-nfs/tasks/config_nfs_mount_storage.yml
- ansible/roles/host-ocp-nfs/tasks/main.yml
- ansible/roles/host-ocp-nfs/tasks/nfs_exports.yml
- ansible/roles/host-ocp-nfs/tasks/packages.yml
> yamllint formatting cleanup for role host-ocp-nfs

- ansible/roles/host-httpd-reverse-proxy/.yamllint
- ansible/roles/host-httpd-reverse-proxy/tasks/main.yml
> yamllint formatting cleanup for role host-httpd-reverse-proxy

- ansible/roles/geerlingguy.java/.yamllint
- ansible/roles/geerlingguy.java/meta/main.yml
> yamllint formatting cleanup for role geerlingguy.java

- ansible/roles/ocp4-workload-camelk-lab/.yamllint
- ansible/roles/ocp4-workload-camelk-lab/defaults/main.yml
- ansible/roles/ocp4-workload-camelk-lab/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-camelk-lab/tasks/workload.yml
- ansible/roles/ocp4-workload-camelk-lab/templates/amqstreams-subscription.yml
- ansible/roles/ocp4-workload-camelk-lab/templates/camelk-subscription.yml
- ansible/roles/ocp4-workload-camelk-lab/templates/installed-community-openshift-operators.yml
- ansible/roles/ocp4-workload-camelk-lab/templates/installed-redhat-openshift-operators.yml
> yamllint formatting cleanup for role ocp4-workload-camelk-lab

- ansible/roles/ocp4-workload-istio-controlplane-infra/.yamllint
- ansible/roles/ocp4-workload-istio-controlplane-infra/defaults/main.yml
- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/post_workload.yml
- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/workload.yml
ocp4-workload-istio-controlplane-infra
> yamllint formatting cleanup for role ocp4-workload-istio-controlplane-infra

- ansible/roles/ocp4-workload-automation-broker/.yamllint
- ansible/roles/ocp4-workload-automation-broker/defaults/main.yml
- ansible/roles/ocp4-workload-automation-broker/files/service_catalog_api_server.yaml
- ansible/roles/ocp4-workload-automation-broker/files/service_catalog_controller_manager.yaml
- ansible/roles/ocp4-workload-automation-broker/tasks/workload.yml
ocp4-workload-automation-broker
> yamllint formatting cleanup for roles/ocp4-workload-automation-broker

- ansible/roles/ocp4-workload-aws-jumpbox/.yamllint
- ansible/roles/ocp4-workload-aws-jumpbox/defaults/main.yml
- ansible/roles/ocp4-workload-aws-jumpbox/tasks/post_workload.yml
- ansible/roles/ocp4-workload-aws-jumpbox/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-aws-jumpbox/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-aws-jumpbox/tasks/workload.yml
- ansible/roles/ocp4-workload-aws-jumpbox/templates/aws_inventory.yml
- ansible/roles/ocp4-workload-aws-jumpbox/templates/create_jumpbox.yml
- ansible/roles/ocp4-workload-aws-jumpbox/templates/delete_jumpbox.yml
> yamllint formatting cleanup for role ocp4-workload-aws-jumpbox

- ansible/roles/ocp4-workload-app-deploy-homework/.yamllint
- ansible/roles/ocp4-workload-app-deploy-homework/defaults/main.yml
ocp4-workload-app-deploy-homework
> yamllint formatting cleanup for role ocp4-workload-app-deploy-homework

- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/.yamllint
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/defaults/main.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/pre_remove_workload.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/workload.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tests/test-local.yml
ocp4-workload-build-an-operator-homeroomlab
> yamllint formatting cleanup for role ocp4-workload-build-an-operator-homeroomlab

- ansible/roles/mysql/.yamllint
- ansible/roles/mysql/tasks/main.yml
> yamllint formatting cleanup for role mysql

- ansible/roles/idm-server/.yamllint
- ansible/roles/idm-server/defaults/main.yml
- ansible/roles/idm-server/handlers/main.yml
- ansible/roles/idm-server/tasks/prep.yml
> yamllint formatting cleanup for role idm-server

- ansible/roles/molecule/.yamllint
- ansible/roles/molecule/defaults/main.yml
> yamllint formatting cleanup for role molecule

- ansible/roles/host-ocp4-provisioner/.yamllint
- ansible/roles/host-ocp4-provisioner/tasks/azure_prereqs.yml
- ansible/roles/host-ocp4-provisioner/tasks/ec2_prereqs.yml
- ansible/roles/host-ocp4-provisioner/tasks/gcp_prereqs.yml
- ansible/roles/host-ocp4-provisioner/tasks/main.yml
- ansible/roles/host-ocp4-provisioner/tasks/osp_prereqs.yml
> yamllint formatting cleanup for role host-ocp4-provisioner

- ansible/roles/host-ocp4-destroy/.yamllint
- Updated yamllint file to enforce formatting rules
host-ocp4-destroy
> updated yamllint for role host-ocp4-destroy

- ansible/roles/host-ocp4-nfs/.yamllint
- ansible/roles/host-ocp4-nfs/tasks/main.yaml
> yamllint formatting cleanup for role host-ocp4-nfs

- ansible/roles/host-ocp-provisioner/.yamllint
> added yamllint config file for host-ocp-provisioner role

- ansible/roles/host-virtualenv/.yamllint
- ansible/roles/host-virtualenv/defaults/main.yml
> yamllint formatting cleanup for role host-virtualenv

- ansible/roles/host-gogs-server/.yamllint
- ansible/roles/host-gogs-server/defaults/main.yml
- ansible/roles/host-gogs-server/tasks/main.yml
> yamllint formatting cleanup for role host-gogs-server

- ansible/roles/ocp4-workload-metering/.yamllint
- ansible/roles/ocp4-workload-metering/defaults/main.yml
- ansible/roles/ocp4-workload-metering/tasks/post_workload.yml
- ansible/roles/ocp4-workload-metering/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-metering/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-metering/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-metering

- ansible/roles/dev-workstation/.yamllint
- ansible/roles/dev-workstation/tasks/install_docker.yml
- ansible/roles/dev-workstation/tasks/main.yml
- ansible/roles/dev-workstation/tasks/packages.yml
> yamllint formatting for role dev-workstation

- ansible/roles/ocp4-workload-sleep/.yamllint
- ansible/roles/ocp4-workload-sleep/defaults/main.yml
- ansible/roles/ocp4-workload-sleep/tasks/post_workload.yml
- ansible/roles/ocp4-workload-sleep/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-sleep/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-sleep/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-sleep

- ansible/roles/ocp4-workload-rhte-a0009/.yamllint
- ansible/roles/ocp4-workload-rhte-a0009/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-a0009/tasks/post_workload.yml
- ansible/roles/ocp4-workload-rhte-a0009/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-rhte-a0009/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-rhte-a0009/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-rhte-a0009

- ansible/roles/ocp4-workload-rhte-a0007-shared/.yamllint
- ansible/roles/ocp4-workload-rhte-a0007-shared/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-a0007-shared/tasks/post_workload.yml
- ansible/roles/ocp4-workload-rhte-a0007-shared/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-rhte-a0007-shared/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-rhte-a0007-shared/tasks/workload.yml
ocp4-workload-rhte-a0007-shared
> yamllint formatting cleanup for role ocp4-workload-rhte-a0007-shared

- ansible/roles/opentlc-integration/.yamllint
- ansible/roles/opentlc-integration/tasks/at.yml
- ansible/roles/opentlc-integration/tasks/git_repos.yml
- ansible/roles/opentlc-integration/tasks/main.yml
- ansible/roles/opentlc-integration/tasks/smtp.yml
> yamllint formatting cleanup for role opentlc-integration

- ansible/roles/ocp4-workload-open-data-hub-student/.yamllint
- ansible/roles/ocp4-workload-open-data-hub-student/defaults/main.yml
- ansible/roles/ocp4-workload-open-data-hub-student/files/deploy_role.yaml
- ansible/roles/ocp4-workload-open-data-hub-student/files/deploy_role_binding.yaml
- ansible/roles/ocp4-workload-open-data-hub-student/files/deploy_service_account.yaml
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/post_workload.yml
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/workload.yml
ocp4-workload-open-data-hub-student
> yamllint formatting cleanup for role ocp4-workload-open-data-hub-student

- ansible/roles/ocp-workload-dekorate-component-operator/.yamllint
- ansible/roles/ocp-workload-dekorate-component-operator/defaults/main.yml
- ansible/roles/ocp-workload-dekorate-component-operator/files/capability.yml
- ansible/roles/ocp-workload-dekorate-component-operator/files/component.yml
- ansible/roles/ocp-workload-dekorate-component-operator/files/link.yml
- ansible/roles/ocp-workload-dekorate-component-operator/files/sa.yml
- ansible/roles/ocp-workload-dekorate-component-operator/files/user-rbac.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/helm.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/kubedb.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/operator.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/post_workload.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/pre_workload.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/remove_workload.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/tekton.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/workload.yml
> yamllint formatting cleanup for ocp-workload-dekorate-component-operator

- ansible/roles/ocp4-workload-openshift-ansible/.yamllint
- ansible/roles/ocp4-workload-openshift-ansible/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-openshift-ansible/tasks/workload.yml
ocp4-workload-openshift-ansible
> yamllint formatting cleanup for role ocp4-workload-openshift-ansible

- ansible/roles/geerlingguy.git/.yamllint
- ansible/roles/geerlingguy.git/meta/main.yml
- ansible/roles/geerlingguy.git/tasks/install-from-source.yml
- ansible/roles/geerlingguy.git/vars/Debian.yml
- ansible/roles/geerlingguy.git/vars/Fedora.yml
- ansible/roles/geerlingguy.git/vars/RedHat.yml
- ansible/roles/geerlingguy.git/vars/main.yml
> yamllint formatting cleanup for role geerlingguy.git

- ansible/roles/ocp4-workload-mysql/.yamllint
- ansible/roles/ocp4-workload-mysql/defaults/main.yml
- ansible/roles/ocp4-workload-mysql/tasks/post_workload.yml
- ansible/roles/ocp4-workload-mysql/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-mysql/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-mysql/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-mysql

- ansible/roles/bastion-3scale/.yamllint
- ansible/roles/bastion-3scale/tasks/main.yml
> yamllint formatting cleanup in role bastion-3scale

- ansible/roles/ocp-infra-maistra/.yamllint
- ansible/roles/ocp-infra-maistra/defaults/main.yml
- ansible/roles/ocp-infra-maistra/meta/main.yml
- ansible/roles/ocp-infra-maistra/tasks/main.yml
- ansible/roles/ocp-infra-maistra/tests/test.yml
> yamllint formatting cleanup for ocp-infra-maistra

- ansible/roles/satellite-capsule-rex/.yamllint
> created yamllint config file in role satellite-capsule-rex

- ansible/roles/rhn-subscription-manager/.yamllint
- ansible/roles/rhn-subscription-manager/tasks/main.yml
> yamllint formatting cleanup for role rhn-subscription-manager

- ansible/roles/sandbox-creds-copy/.yamllint
- ansible/roles/sandbox-creds-copy/tasks/main.yml
> yamllint formatting cleanup for role sandbox-creds-copy

- ansible/roles/satellite-installation/.yamllint
- ansible/roles/satellite-installation/defaults/main.yml
- ansible/roles/satellite-installation/tasks/enable_rex_access.yml
- ansible/roles/satellite-installation/tasks/firewalld.yml
- ansible/roles/satellite-installation/tasks/remove_epel_repos.yml
- ansible/roles/satellite-installation/tasks/version_6.7.yml
> yamllint formatting cleanup for role satellite-installation

- ansible/roles/ocp-infra-openwhisk/.yamllint
- ansible/roles/ocp-infra-openwhisk/tasks/main.yml
> yamllint formatting cleanup for ocp-infra-openwhisk

- ansible/roles/satellite-libvirt/.yamllint
- ansible/roles/satellite-libvirt/defaults/main.yml
- ansible/roles/satellite-libvirt/tasks/libvirt.yml
- ansible/roles/satellite-libvirt/tasks/proxy_libvirt.yml
> yamllint formatting cleanup for role satellite-libvirt

- ansible/roles/ocp4-workload-workshopper/.yamllint
- ansible/roles/ocp4-workload-workshopper/defaults/main.yml
- ansible/roles/ocp4-workload-workshopper/tasks/post_workload.yml
- ansible/roles/ocp4-workload-workshopper/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-workshopper/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-workshopper/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-workshopper

- ansible/roles/ocp4-workload-workshop-admin-storage/.yamllint
- ansible/roles/ocp4-workload-workshop-admin-storage/defaults/main.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/post_workload.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-workshop-admin-storage

- ansible/roles/satellite-insights/.yamllint
- ansible/roles/satellite-insights/tasks/version_6.7.yml
> yamllint formatting cleanup for role satellite-insights

- ansible/roles/rhel-graphical/.yamllint
- ansible/roles/rhel-graphical/meta/main.yml
- ansible/roles/rhel-graphical/tasks/main.yml
> yamllint formatting cleanup for role rhel-graphical

- ansible/roles/ocp4-workload-userquota-operator/.yamllint
- ansible/roles/ocp4-workload-userquota-operator/defaults/main.yml
- ansible/roles/ocp4-workload-userquota-operator/tasks/post_workload.yml
- ansible/roles/ocp4-workload-userquota-operator/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-userquota-operator/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-userquota-operator/tasks/workload.yml
ocp4-workload-userquota-operator
> yamllint formatting cleanup for role ocp4-workload-userquota-operator

- ansible/roles/ocp4-workload-dil-streaming/tasks/provision_shared.yaml
The previous merge of this file was messed up...these are the changes required that were missing.
ocp4-workload-dil-streaming
> Update role ocp4-workload-dil-streaming to fix merge issue

- ansible/roles/satellite-manage-compute-profile/.yamllint
- ansible/roles/satellite-manage-compute-profile/tasks/main.yml
satellite-manage-compute-profile
> yamllint formatting cleanup for role satellite-manage-compute-profile

- ansible/roles/rhel-security-verification/.yamllint
- ansible/roles/rhel-security-verification/tasks/aide-verify.yml
- ansible/roles/rhel-security-verification/tasks/audit-verify.yml
- ansible/roles/rhel-security-verification/tasks/crypto-verify.yml
- ansible/roles/rhel-security-verification/tasks/firewalld-verify.yml
- ansible/roles/rhel-security-verification/tasks/gpg-verify.yml
- ansible/roles/rhel-security-verification/tasks/idm-verify.yml
- ansible/roles/rhel-security-verification/tasks/ipsec-verify.yml
- ansible/roles/rhel-security-verification/tasks/openscap-verify.yml
- ansible/roles/rhel-security-verification/tasks/sessionrecording-verify.yml
> yamllint formatting cleanup for role rhel-security-verification

- ansible/roles/tower-custom-venv/.yamllint
> yamllint formatting cleanup for role tower-custom-venv

- ansible/roles/tower-inventory-create/.yamllint
- ansible/roles/tower-inventory-create/tasks/main.yml
> yamllint formatting cleanup for role tower-inventory-create

- ansible/roles/openshift-ansible-broker/.yamllint
> added yamllint config file to role openshift-ansible-broker

- ansible/configs/aro/.yamllint
- ansible/configs/aro/destroy_env.yml
- ansible/configs/aro/mgr_users.yml
- ansible/configs/aro/post_software.yml
- ansible/configs/aro/pre_software.yml
> yamllint formatting cleanup for role aro

- ansible/configs/ansible-advanced/.yamllint
- ansible/configs/ansible-advanced/default_vars.yml
- ansible/configs/ansible-advanced/default_vars_ec2.yml
- ansible/configs/ansible-advanced/default_vars_osp.yml
- ansible/configs/ansible-advanced/destroy_env.yml
- ansible/configs/ansible-advanced/post_infra.yml
- ansible/configs/ansible-advanced/post_software.yml
- ansible/configs/ansible-advanced/pre_infra.yml
- ansible/configs/ansible-advanced/pre_software.yml
- ansible/configs/ansible-advanced/requirements.yml
- ansible/configs/ansible-advanced/sample_vars_ec2.yml
- ansible/configs/ansible-advanced/software.yml
> yamllint formatting cleanup for role ansible-advanced

- ansible/roles/satellite-verification/.yamllint
> created yamllint config file in role satellite_verification

- ansible/roles/satellite-provisioning/.yamllint
> created yamllint config file in role satellite_provisioning

- ansible/roles/tower-credential-create/.yamllint
- ansible/roles/tower-credential-create/tasks/main.yml
> yamllint formatting cleanup for role tower-credential-create

- ansible/roles/satellite-manage-setting/.yamllint
- ansible/roles/satellite-manage-setting/tasks/main.yml
> yamllint formatting cleanup for role satellite-manage-setting

- ansible/roles/satellite-manage-location/.yamllint
- ansible/roles/satellite-manage-location/tasks/main.yml
> yamllint formatting cleanup for role satellite-manage-location

- ansible/roles/satellite-manage-userroles/.yamllint
- ansible/roles/satellite-manage-userroles/tasks/role.yml
- ansible/roles/satellite-manage-userroles/tasks/user.yml
> yamllint formatting cleanup for role satellite-manage-userroles

- ansible/roles/satellite-manage-lifecycle/.yamllint
- ansible/roles/satellite-manage-lifecycle/tasks/version_6.x.yml
> yamllint formatting cleanup for role satellite-manage-lifecycle

- ansible/roles/satellite-manage-host/.yamllint
- ansible/roles/satellite-manage-host/tasks/version_6.x.yml
> yamllint formatting cleanup for role satellite-manage-host

- ansible/roles/satellite-register-host/.yamllint
- ansible/roles/satellite-register-host/tasks/katello_agent.yml
- ansible/roles/satellite-register-host/tasks/register.yml
- ansible/roles/satellite-register-host/tasks/remote_execution.yml
> yamllint formatting cleanup for role satellite-register-host

- ansible/roles/set_env_authorized_key/.yamllint
- ansible/roles/set_env_authorized_key/tasks/main.yml
> yamllint formatting cleanup for role set_env_authorized_key

- ansible/roles/satellite-manage-hostgroup/.yamllint
- ansible/roles/satellite-manage-hostgroup/tasks/main.yml
> yamllint formatting cleanup for role satellite-manage-hostgroup

- ansible/roles/satellite-manage-capsule-certificate/.yamllint
- ansible/roles/satellite-manage-capsule-certificate/tasks/main.yml
- ansible/roles/satellite-manage-capsule-certificate/tasks/version_6.4.yml
satellite-manage-capsule-certificate
> yamllint formatting cleanup for role satellite-manage-capsule-certificate

- ansible/roles/satellite-manage-activationkey/.yamllint
- ansible/roles/satellite-manage-activationkey/tasks/version_6.x.yml
satellite-manage-activationkey
> yamllint formatting cleanup for role satellite-manage-activationkey

- ansible/roles/satellite-capsule-configuration/.yamllint
- ansible/roles/satellite-capsule-configuration/tasks/version_6.4.yml
satellite-capsule-configuration
> yamllint formatting cleanup for role satellite-capsule-configuration

- ansible/roles/satellite-manage-organization/.yamllint
- ansible/roles/satellite-manage-organization/tasks/main.yml
> yamllint formatting cleanup for role satellite-manage-organization

- ansible/roles/rhel-custom-security-content-verification/.yamllint
- ansible/roles/rhel-custom-security-content-verification/tasks/main.yml
rhel-custom-security-content-verification
> yamllint formatting cleanup for role rhel-custom-security-content-verification

- ansible/configs/multi-network-app-pntae/.yamllint
- ansible/configs/multi-network-app-pntae/default_vars.yml
- ansible/configs/multi-network-app-pntae/default_vars_osp.yml
- ansible/configs/multi-network-app-pntae/post_infra.yml
- ansible/configs/multi-network-app-pntae/post_software.yml
- ansible/configs/multi-network-app-pntae/pre_infra.yml
- ansible/configs/multi-network-app-pntae/pre_software.yml
- ansible/configs/multi-network-app-pntae/sample_vars/private-dns-osp.yml
- ansible/configs/multi-network-app-pntae/sample_vars_ec2.yml
- ansible/configs/multi-network-app-pntae/sample_vars_osp.yml
- ansible/configs/multi-network-app-pntae/setup_lab_user.yml
- ansible/configs/multi-network-app-pntae/software.yml
- ansible/configs/multi-network-app-pntae/start.yml
- ansible/configs/multi-network-app-pntae/stop.yml
> yamllint formatting cleanup for role multi-network-app-pntae

- ansible/configs/ocp-clientvm/.yamllint
- ansible/configs/ocp-clientvm/default_vars.yml
- ansible/configs/ocp-clientvm/default_vars_ec2.yml
- ansible/configs/ocp-clientvm/default_vars_osp.yml
- ansible/configs/ocp-clientvm/post_infra.yml
- ansible/configs/ocp-clientvm/post_software.yml
- ansible/configs/ocp-clientvm/pre_software.yml
- ansible/configs/ocp-clientvm/requirements-ruby.yml
- ansible/configs/ocp-clientvm/software.yml
> yamllint formatting cleanup for config  role ocp-clientvm

- ansible/configs/multi-region-tower/.yamllint
- ansible/configs/multi-region-tower/deploy_stack.yml
- ansible/configs/multi-region-tower/destroy_env.yml
- ansible/configs/multi-region-tower/env_vars.yml
- ansible/configs/multi-region-tower/post_infra.yml
- ansible/configs/multi-region-tower/post_software.yml
- ansible/configs/multi-region-tower/pre_infra.yml
- ansible/configs/multi-region-tower/pre_software.yml
- ansible/configs/multi-region-tower/sample_vars.yml
- ansible/configs/multi-region-tower/sample_vars_babylon.yml
- ansible/configs/multi-region-tower/software.yml
- ansible/configs/multi-region-tower/tower_workloads.yml
> yamllint formatting cleanup for role multi-region-tower

- ansible/configs/multi-region-example/.yamllint
- ansible/configs/multi-region-example/deploy_stack.yml
- ansible/configs/multi-region-example/destroy_env.yml
- ansible/configs/multi-region-example/env_vars.yml
- ansible/configs/multi-region-example/post_infra.yml
- ansible/configs/multi-region-example/post_software.yml
- ansible/configs/multi-region-example/pre_infra.yml
- ansible/configs/multi-region-example/pre_software.yml
- ansible/configs/multi-region-example/sample_vars.yml
- ansible/configs/multi-region-example/software.yml
> yamllint formatting cleanup for role multi-region-example

- ansible/configs/ansible-tower-advanced/.yamllint
- ansible/configs/ansible-tower-advanced/destroy_env.yml
- ansible/configs/ansible-tower-advanced/env_vars.yml
- ansible/configs/ansible-tower-advanced/post_infra.yml
- ansible/configs/ansible-tower-advanced/post_software.yml
- ansible/configs/ansible-tower-advanced/pre_infra.yml
- ansible/configs/ansible-tower-advanced/pre_software.yml
- ansible/configs/ansible-tower-advanced/sample_vars.yml
- ansible/configs/ansible-tower-advanced/sample_vars_babylon.yml
- ansible/configs/ansible-tower-advanced/software.yml
- ansible/configs/ansible-tower-advanced/tower_workloads.yml
> yamllint formatting cleanup for role ansible-tower-advanced

- ansible/configs/just-a-bunch-of-nodes/.yamllint
- ansible/configs/just-a-bunch-of-nodes/default_vars.yml
- ansible/configs/just-a-bunch-of-nodes/post_infra.yml
- ansible/configs/just-a-bunch-of-nodes/post_software.yml
- ansible/configs/just-a-bunch-of-nodes/pre_infra.yml
- ansible/configs/just-a-bunch-of-nodes/pre_software.yml
- ansible/configs/just-a-bunch-of-nodes/software.yml
> yamllint formatting cleanup for role just-a-bunch-of-nodes

- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/winc-deploy.j2
Adding an "ssh" container, as the "bastion" container breaks Windows Containers
SSH Container Deployment
There was an issue with using the "bastion ssh" container. This PR deploys a known working ssh contianer.
> updated to use ssh container

- ansible/configs/ansible-windows/.yamllint
- ansible/configs/ansible-windows/destroy_env.yml
- ansible/configs/ansible-windows/env_vars.yml
- ansible/configs/ansible-windows/post_infra.yml
- ansible/configs/ansible-windows/post_software.yml
- ansible/configs/ansible-windows/pre_infra.yml
- ansible/configs/ansible-windows/pre_software.yml
- ansible/configs/ansible-windows/software.yml
> yamllint formatting cleanup for role ansible-windows

- ansible/configs/ansible-tower/.yamllint
- ansible/configs/ansible-tower/destroy_env.yml
- ansible/configs/ansible-tower/post_infra.yml
- ansible/configs/ansible-tower/post_software.yml
- ansible/configs/ansible-tower/pre_infra.yml
- ansible/configs/ansible-tower/pre_software.yml
- ansible/configs/ansible-tower/sample_vars.yml
- ansible/configs/ansible-tower/sample_vars_babylon.yml
- ansible/configs/ansible-tower/software.yml
- ansible/configs/ansible-tower/tower_workloads.yml
> yamllint formatting cleanup for role ansible-tower

- ansible/configs/ansible-tower-pntae/.yamllint
- ansible/configs/ansible-tower-pntae/default_vars.yml
- ansible/configs/ansible-tower-pntae/default_vars_osp.yml
- ansible/configs/ansible-tower-pntae/post_infra.yml
- ansible/configs/ansible-tower-pntae/post_software.yml
- ansible/configs/ansible-tower-pntae/pre_software.yml
- ansible/configs/ansible-tower-pntae/sample_vars/ansimp_osp_with_student_user.yml
- ansible/configs/ansible-tower-pntae/sample_vars/osp_vars.yml
- ansible/configs/ansible-tower-pntae/setup_lab_user.yml
- ansible/configs/ansible-tower-pntae/software.yml
> yamllint formatting cleanup for role ansible-tower-pntae

- ansible/configs/ansible-provisioner/.yamllint
- ansible/configs/ansible-provisioner/env_vars.yml
- ansible/configs/ansible-provisioner/mgr_users.yml
- ansible/configs/ansible-provisioner/post_infra.yml
- ansible/configs/ansible-provisioner/post_software.yml
- ansible/configs/ansible-provisioner/pre_infra.yml
- ansible/configs/ansible-provisioner/pre_software.yml
- ansible/configs/ansible-provisioner/software.yml
> yamllint formatting cleanup for role ansible-provisioner

- ansible/configs/a-base-config/.yamllint
- ansible/configs/a-base-config/default_vars.yml
- ansible/configs/a-base-config/post_infra.yml
- ansible/configs/a-base-config/post_software.yml
- ansible/configs/a-base-config/pre_infra.yml
- ansible/configs/a-base-config/pre_software.yml
- ansible/configs/a-base-config/sample_variables/rhel8_server_on_ec2.yml
- ansible/configs/a-base-config/sample_variables/rhel8_server_on_osp.yml
- ansible/configs/a-base-config/sample_variables/secrets_example_all.yml
- ansible/configs/a-base-config/sample_variables/secrets_example_ec2.yml
- ansible/configs/a-base-config/sample_variables/secrets_example_osp.yml
- ansible/configs/a-base-config/software.yml
> yamllint formatting cleanup for role a-base-config

- ansible/configs/ans-network-lab/.yamllint
- ansible/configs/ans-network-lab/destroy_env.yml
- ansible/configs/ans-network-lab/env_vars.yml
- ansible/configs/ans-network-lab/post_infra.yml
- ansible/configs/ans-network-lab/post_software.yml
- ansible/configs/ans-network-lab/pre_infra.yml
- ansible/configs/ans-network-lab/pre_software.yml
- ansible/configs/ans-network-lab/software.yml
> yamllint formatting cleanup for role ans-network-lab

- ansible/configs/ans-tower-lab/.yamllint
- ansible/configs/ans-tower-lab/default_vars.yml
- ansible/configs/ans-tower-lab/default_vars_ec2.yml
- ansible/configs/ans-tower-lab/default_vars_osp.yml
- ansible/configs/ans-tower-lab/destroy_env.yml
- ansible/configs/ans-tower-lab/post_infra.yml
- ansible/configs/ans-tower-lab/post_software.yml
- ansible/configs/ans-tower-lab/pre_infra.yml
- ansible/configs/ans-tower-lab/pre_software.yml
- ansible/configs/ans-tower-lab/sample_vars/ec2_vars.yml
- ansible/configs/ans-tower-lab/sample_vars/homework_ec2_vars.yml
- ansible/configs/ans-tower-lab/sample_vars/osp_vars.yml
- ansible/configs/ans-tower-lab/setup_lab_user.yml
- ansible/configs/ans-tower-lab/software.yml
> yamllint formatting cleanup for role ans-tower-lab

- ansible/configs/ans-tower-ops-demo/.yamllint
- ansible/configs/ans-tower-ops-demo/destroy_env.yml
- ansible/configs/ans-tower-ops-demo/env_vars.yml
- ansible/configs/ans-tower-ops-demo/post_infra.yml
- ansible/configs/ans-tower-ops-demo/post_software.yml
- ansible/configs/ans-tower-ops-demo/pre_infra.yml
- ansible/configs/ans-tower-ops-demo/pre_software.yml
- ansible/configs/ans-tower-ops-demo/software.yml
> yamllint formatting cleanup for role ans-tower-ops-demo

- ansible/configs/ansible-cicd-lab/.yamllint
- ansible/configs/ansible-cicd-lab/create_host.yml
- ansible/configs/ansible-cicd-lab/destroy_env.yml
- ansible/configs/ansible-cicd-lab/docker_setup.yml
- ansible/configs/ansible-cicd-lab/env_vars.yml
- ansible/configs/ansible-cicd-lab/jenkins_ssh_setup.yml
- ansible/configs/ansible-cicd-lab/post_infra.yml
- ansible/configs/ansible-cicd-lab/post_software.yml
- ansible/configs/ansible-cicd-lab/pre_infra.yml
- ansible/configs/ansible-cicd-lab/pre_software.yml
- ansible/configs/ansible-cicd-lab/requirements.yml
- ansible/configs/ansible-cicd-lab/software.yml
- ansible/configs/ansible-cicd-lab/tower_setup.yml
> yamllint formatting cleanup for role ansible-cicd-lab

- ansible/configs/ansible-integrations/.yamllint
- ansible/configs/ansible-integrations/destroy_env.yml
- ansible/configs/ansible-integrations/env_vars.yml
- ansible/configs/ansible-integrations/post_infra.yml
- ansible/configs/ansible-integrations/post_software.yml
- ansible/configs/ansible-integrations/pre_infra.yml
- ansible/configs/ansible-integrations/pre_software.yml
- ansible/configs/ansible-integrations/software.yml
> yamllint formatting cleanup for role ansible-integrations

- ansible/roles/windows-common/.yamllint
> yamllint formatting cleanup for role windows-common

- ansible/roles/windows-ad/.yamllint
- ansible/roles/windows-ad/tasks/main.yml
> yamllint formatting cleanup for role windows-ad

- ansible/roles/tower-virtual-environment/.yamllint
- ansible/roles/tower-virtual-environment/tasks/main.yml
> yamllint formatting cleanup for role tower-virtual-environment

- ansible/roles/tower_validate/.travis.yml
- ansible/roles/tower_validate/.yamllint
- ansible/roles/tower_validate/meta/main.yml
- ansible/roles/tower_validate/tasks/main.yml
> yamllint formatting cleanup for role tower-validate

- ansible/roles/tower-project-create/.yamllint
- ansible/roles/tower-project-create/tasks/main.yml
> yamllint formatting cleanup for role tower-project-create

- ansible/roles/tower-license-injector/.yamllint
- ansible/roles/tower-license-injector/tasks/main.yml
> yamllint formatting cleanup for role tower-license-injector

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/.yamllint
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/files/opendatahub_v1alpha1_opendatahub_cr.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/files/operator.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/files/role.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/files/role_binding.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/files/service_account.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/per_user_operator_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/per_user_post_operator_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/per_user_pre_operator_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/per_user_remove_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/remove_workload.yml
ocp4-workload-rhte-analytics-data-ocp-workshop-s2020
> yamllint formatting cleanup for role ocp4-workload-rhte-analytics-data-ocp-workshop-s2020

- ansible/roles/ocp4-workload-ml-workflows-workshop/.yamllint
- Update yamllint file to enforce formatting rules
ocp4-workload-ml-workflows-workshop
> updated yamllint for ocp4-workload-ml-workflows-workshop

- ansible/roles/ocp4-workload-upgrade-cluster/.yamllint
- ansible/roles/ocp4-workload-upgrade-cluster/defaults/main.yml
- ansible/roles/ocp4-workload-upgrade-cluster/tasks/post_workload.yml
- ansible/roles/ocp4-workload-upgrade-cluster/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-upgrade-cluster/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-upgrade-cluster/tasks/workload.yml
> yamllint formatting cleanup for role ocp4-workload-upgrade-cluster

- ansible/roles/git-server-ssh/.yamllint
- ansible/roles/git-server-ssh/defaults/main.yml
- ansible/roles/git-server-ssh/tasks/main.yml
> yamllint formatting cleanup for role git-server-ssh

- ansible/roles/bastion-opentlc-ipa/.yamllint
- ansible/roles/bastion-opentlc-ipa/tasks/main.yml
> yamllint formatting cleanup for role bastion-opentlc-ipa

- ansible/roles/tower-org-create/.yamllint
- ansible/roles/tower-org-create/tasks/main.yml
> yamllint formatting cleanup for role tower-org-create

- ansible/roles/tower-copy-ssh/.yamllint
- ansible/roles/tower-copy-ssh/tasks/main.yml
> yamllint formatting cleanup for role tower-copy-ssh

- ansible/roles/tower-auth-integration/.yamllint
- ansible/roles/tower-auth-integration/tasks/ldap_auth.yml
- ansible/roles/tower-auth-integration/tasks/main.yml
> yamllint formatting cleanup for role tower-auth-integration

- ansible/roles/tower-babylon-job-runner/.yamllint
- ansible/roles/tower-babylon-job-runner/tasks/main.yml
> yamllint formatting cleanup for role tower-babylon-job-runner

- ansible/roles/ocp-workload-appmod-migration/.yamllint
- ansible/roles/ocp-workload-appmod-migration/defaults/main.yml
- ansible/roles/ocp-workload-appmod-migration/tasks/pre_workload.yml
- ansible/roles/ocp-workload-appmod-migration/tasks/remove_workload.yml
- ansible/roles/ocp-workload-appmod-migration/tasks/workload.yml
- ansible/roles/ocp-workload-appmod-migration/templates/constraints_limitrange.yaml
- ansible/roles/ocp-workload-appmod-migration/templates/limitrange.yaml
> yamllint formatting cleanup for ocp-workload-appmod-migration

- ansible/roles/tower-license-copy/.yamllint
- ansible/roles/tower-license-copy/tasks/main.yml
> yamllint formatting cleanup for role tower-license-copy

- ansible/roles/cleanup-tower-default/.yamllint
- ansible/roles/cleanup-tower-default/tasks/main.yml
> yamllint formatting cleanup for role cleanup_tower_default

- ansible/roles/ocp-workload-developer-environment/.yamllint
- ansible/roles/ocp-workload-developer-environment/defaults/main.yml
- ansible/roles/ocp-workload-developer-environment/tasks/idle_workload.yml
- ansible/roles/ocp-workload-developer-environment/tasks/post_workload.yml
- ansible/roles/ocp-workload-developer-environment/tasks/pre_workload.yml
- ansible/roles/ocp-workload-developer-environment/tasks/remove_workload.yml
ocp-workload-developer-environment
> yamllint formatting cleanup for ocp-workload-developer-environment

- ansible/roles/geerlingguy.gogs/.yamllint
- ansible/roles/geerlingguy.gogs/meta/main.yml
- ansible/roles/geerlingguy.gogs/tasks/init-setup.yml
- ansible/roles/geerlingguy.gogs/tasks/main.yml
- ansible/roles/geerlingguy.gogs/tests/test.yml
> yamllint formatting cleanup for role geerlingguy.gogs

- ansible/roles/tower-job-template-create/.yamllint
> created yamllint config file in role tower-job-template-create

- ansible/roles/ocp-infra-azure-service-broker/.yamllint
- ansible/roles/ocp-infra-azure-service-broker/tasks/main.yml
ocp4-infra-azure-service-broker
> yamllint formatting cleanup for ocp-infra-azure-service-broker

- ansible/roles/bastion/.yamllint
- ansible/roles/bastion/tasks/main.yml
> yamllint formatting cleanup for role bastion

- ansible/roles/ocp-infra-aws-service-broker/.yamllint
> added a yamllint config file to role ocp-infra-aws-service-broker

- ansible/roles/ocp-workload-amq-streams/.yamllint
- ansible/roles/ocp-workload-amq-streams/defaults/main.yml
- ansible/roles/ocp-workload-amq-streams/tasks/pre_workload.yml
- ansible/roles/ocp-workload-amq-streams/tasks/remove_workload.yml
> yamllint formatting cleanup for ocp-workload-amq-streams

- ansible/roles/ocp-infra-nexus/.yamllint
- ansible/roles/ocp-infra-nexus/files/nexus3-persistent-template.yaml
- ansible/roles/ocp-infra-nexus/tasks/main.yml
> yamllint formatting cleanup for ocp-infra-nexus

- ansible/roles/bastion-lite/.yamllint
- ansible/roles/bastion-lite/tasks/main.yml
> yamllint formatting cleanup for role bastion-lite

- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin-student/.yamllint
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin-student/defaults/main.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin-student/tasks/clean-environment.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin-student/tasks/post_workload.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin-student/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin-student/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin-student/tasks/workload.yml
ocp4-workload-workshop-dashboard-cluster-student-admin
> yamllint formatting cleanup for role ocp4-workload-workshop-dashboard-clutser-student-admin

- ansible/roles/ocp4-workload-osevg-workshop-tracker/.yamllint
- ansible/roles/ocp4-workload-osevg-workshop-tracker/defaults/main.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tasks/post_workload.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tasks/workload.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tests/test-local.yml
ocp4-workload-osevg-workshop-tracker
> yamllint formatting cleanup for role ocp4-workload-osevg-workshop-tracker

- ansible/roles/ocp4-workload-opentlc-production/.yamllint
- ansible/roles/ocp4-workload-opentlc-production/defaults/main.yml
- ansible/roles/ocp4-workload-opentlc-production/files/image_registry.yaml
- ansible/roles/ocp4-workload-opentlc-production/tasks/post_workload.yml
- ansible/roles/ocp4-workload-opentlc-production/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-opentlc-production/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-opentlc-production/tasks/workload.yml
- ansible/roles/ocp4-workload-opentlc-production/templates/build_defaults.yaml
ocp4-workload-opentlc-production
> yamllint formatting cleanup for role ocp4-workload-opentlc-production

- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/pre_workload.yml
Updated the getting route info to use k8s_info and to use the right api version for 4.6
k8s_info
Quick fix to get the 4.6 lab working.
> Updated route info to use k8s_info

- ansible/configs/sap-hana/default_vars.yml
- ansible/configs/sap-hana/post_software.yml
Add multiple Tower Workflows so the user can choose between deploying an HA or non-HA environment
sap-hana
> Add multiple Tower Workflows

- training/03_Infrastructure/02_Advanced/Adding_Versions_RHEL.adoc
02_Advanced 
```paste below
```
> updating training doc

- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/pre_workload.yml
Fix indent issue in ocp4-workload-workshop-admin-storage that is failing yamllint.
role ocp4-workload-workshop-admin-storage
> Fix yamllint indent issue in ocp4-workload-workshop-admin-storage

- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/subscription.j2
Update subscription to allow windows containers to deploy
subscription template
The startingCSV is no longer needed
> Update subscription for Windows Conatiners

- ansible/configs/osp-satellite-vm/instance_loop.yml
- ansible/configs/osp-satellite-vm/post_infra.yml
- ansible/configs/osp-satellite-vm/post_software.yml
> remove evil - in dns names

- training/03_Infrastructure/02_Advanced/Adding_Users.adoc
Users creation instructions doc for agD adv training
Adding_Users.adoc
> Users creation instructions doc for agD adv training

- ansible/configs/ansible-tower-implementation/files/repos_template.j2
> repos fixed

- ansible/configs/test-empty-config/.yamllint
- ansible/configs/test-empty-config/destroy_env.yml
- ansible/configs/test-empty-config/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/test-empty-config/files/cloud_providers/ec2_cloud_template_json.j2
- ansible/configs/test-empty-config/post_infra.yml
- ansible/configs/test-empty-config/post_software.yml
- ansible/configs/test-empty-config/pre_infra.yml
- ansible/configs/test-empty-config/pre_software.yml
- ansible/configs/test-empty-config/requirements.yml
- ansible/configs/test-empty-config/sample_vars.yml
- ansible/configs/test-empty-config/sample_vars_osp.yml
- ansible/configs/test-empty-config/software.yml
Add yamllint to test-empty-tonfig and resolve issues.
- Cleanup
> Cleanup config test-empty-config for yamllint

- ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
Reverts redhat-cop/agnosticd#3224
> Revert "Take the GUID subdomain out of OSP hostnames"

- ansible/configs/osp-satellite-vm/instance_loop.yml
Add new DNS entry format `{{host}}.{{guid}}`
`config/osp-satellite-vm`
> Add DNS entry

- ansible/configs/osp-satellite-vm/instance_loop.yml
Add new hostname format to `hostname-{{guid}}.{{guid}}.domain`
`config/osp-satellite-vm`
> Add new hostname format

- ansible/roles/ocp4-workload-quarkus-workshop/files/amqstreams_subscription.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/codeready_subscription.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/community-operators-index.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/jaeger_subscription.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/redhat-operators-index.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile
- ansible/roles/ocp4-workload-quarkus-workshop/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/templates/devfile.json.j2
Update ocp4-workload-quarkus-workshop to upgrade OCP 4.6.4
```paste below
```
> Update ocp4-workload-quarkus-workshop to upgrade OCP 4.6.4

- ansible/roles_ocp_workloads/ocp4_workload_workload_monitoring/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_workload_monitoring/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_workload_monitoring/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_workload_monitoring/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_workload_monitoring/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_workload_monitoring/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_workload_monitoring/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_workload_monitoring/tasks/workload.yml
Adds a role to enable user workload monitoring per https://docs.openshift.com/container-platform/4.6/monitoring/enabling-monitoring-for-user-defined-projects.html
> adds role for enabling user workload monitoring

- ansible/configs/osp-satellite-vm/post_infra.yml
Fix satellite hostname for osp-satellite-vm
`config/osp-satellite-vm`
> Fix satellite hostname

- ansible/roles/ocp4-workload-debezium-demo/.yamllint
- ansible/roles/ocp4-workload-debezium-demo/defaults/main.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/post_workload.yml
- ansible/roles/ocp4-workload-debezium-demo/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_e2e_demo.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_mysql_demo.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_pgsql_demo.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_registry.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_streams.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_webapp.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/remove_workload.yml
Style formatting changes to ocp4-workload-debezium-demo
Replaces previous yamllint PR closed due to conflict.
- Cleanup Pull Request
role ocp4-workload-debezium-demo
> Cleanup role ocp4-workload-debezium-demo for yamllint

- ansible/roles/tower_agnosticd_virtualenvs/tasks/custom-venv-paths.yml
- ansible/roles/tower_agnosticd_virtualenvs/tasks/main.yml
Add feature to role tower_agnosticd_virtualenvs to have it add paths to Ansible tower CUSTOM_VENV_PATHS.
Role tower_agnosticd_virtualenvs
> Change role tower_agnosticd_virtualenvs to manage CUSTOM_VENV_PATHS

- tools/virtualenvs/aws-ansible-2.9.txt
- tools/virtualenvs/azure-ansible-2.9.txt
- tools/virtualenvs/openstack-ansible-2.9.12.txt
- tools/virtualenvs/openstack-ansible-2.9.txt
Add psutil to all ansible virtual environments so that they may function in Ansible Tower.
Agnosticd tools/virtualenvs
> Add psutil to all ansible virtualenvs

- ansible/configs/sandbox/files/repos_template.j2
> re-added repos.j2

- ansible/configs/sandbox/files/repos_template.j2
- ansible/configs/sandbox/pre_software.yml
> Rut31337 sb2

- ansible/configs/sandbox/default_vars.yml
Set set_env_authorized_key to false by default
sandbox config
> Update sandbox config

- ansible/configs/sandbox/software.yml
Update sandbox with unzip install and cleanup
Sandbox config
> Update sandbox with unzip install and cleanup

- ansible/configs/amq-messaging-foundations/requirements.yml
- ansible/configs/ans-tower-lab-ng/requirements.yml
- ansible/configs/ans-tower-lab/requirements.yml
- ansible/configs/ansible-advanced/requirements.yml
- ansible/configs/ansible-gitOps-integration/requirements.yml
- ansible/configs/ansible-platform-foundations/requirements.yml
- ansible/configs/ansible-tower-advanced/requirements.yml
- ansible/configs/ansible-tower-implementation/requirements.yml
- ansible/configs/ansible-tower-pntae/requirements.yml
- ansible/configs/ansible-tower/requirements.yml
- ansible/configs/ansible-windows-elt/requirements.yml
- ansible/configs/ansible-windows/requirements.yml
- ansible/configs/hacluster-breakfix1-pntae/requirements.yml
- ansible/configs/hacluster-pntae/requirements.yml
- ansible/configs/multi-network-app-pntae/requirements.yml
- ansible/configs/ocp-clientvm/requirements.yml
- ansible/configs/ocp-ha-disconnected-lab/requirements.yml
- ansible/configs/ocp-workshop/requirements.yml
- ansible/configs/ocp4-cluster/requirements.yml
- ansible/configs/ocp4-disconnected-osp-lab/requirements.yml
- ansible/configs/ocp4-ha-lab/requirements.yml
- ansible/configs/ocp4-workshop/requirements.yml
- ansible/configs/ocs4-external-implementation/requirements.yml
- ansible/configs/rhel8lab/requirements.yml
- ansible/configs/rhte-ans-tower/requirements.yml
- ansible/configs/sap-integration/requirements.yml
- ansible/configs/studentvm/requirements.yml
- ansible/configs/test-empty-config/requirements.yml
- ansible/configs/three-tier-app/requirements.yml
Update ftl-injector to v0.17 to address python requirements issue.
ftl-injector
> Set ftl-injector to v0.17

- ansible/configs/sandbox/.yamllint
- ansible/configs/sandbox/post_infra.yml
- ansible/configs/sandbox/software.yml
Fix config sandbox where it is failing yamllint.
Config sandbox
> Fix config sandbox yamllint

- ansible/configs/sap-integration/files/requirements_k8s.txt
after troubleshooting on the bastion server directly, that's a requirement.txt that should work.
> Fix pip dependencies in sap-integration

- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Windows AMIs updated for ansible for windows CI
config: ansible-windows
> Windows AMIs update

- ansible/configs/osp-migration/post_infra.yml
Using **debug** module for user.info, even the task is skipped it will be sent in the mail to the users.
> Update config osp-migration to use agnosticd_user_info instead debug

- ansible/roles/ocp4-workload-dil-streaming/tasks/workload.yml
JDG was installed in only one namespace because of hardcoded testing
> [Bugfix]  DIL only ONE JDG is installed, adding the loop

- tests/static/syntax-check.sh
> Fix yamllint relative includes in static checks

- ansible/roles-infra/infra_osp_bastion_on_openshift_network/meta/main.yml
- ansible/roles-infra/infra_osp_bastion_on_openshift_network/tasks/add-bastion-to-openstack-network.yml
- ansible/roles-infra/infra_osp_bastion_on_openshift_network/tasks/main.yml
- ansible/roles-infra/infra_osp_bastion_on_openshift_network/vars/main.yml
Fix OpenStack auth in role infra_osp_bastion_on_openshift_network.
role infra_osp_bastion_on_openshift_network
> Fix role infra_osp_bastion_on_openshift_network OpenStack auth

- ansible/roles_ocp_workloads/ocp4_workload_pntae/files/tech-breakfix-shift-004
New catalog entry for openshift breakfix tech-breakfix-shift-004 based on old catalog cee-cf-111
```paste below
```
> tech-breakfix-shift-004 script (text)

- ansible/configs/sap-integration/default_vars_ec2.yml
- ansible/configs/sap-integration/sap_software.yml
Fix device name while creating the storage pool
`configs/sap-integration`
> Fix device name for SAP storage pool

- ansible/roles/ocp4-workload-debezium-demo/templates/streams-subscription.yaml.j2
Fixes the provisioning of debezium demo
ocp4-workload-debezium-demo
```paste below
```
> pin channel version to 1.5.x

- ansible/roles_ocp_workloads/ocp4_workload_windows_node/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/operatorgroup.j2
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/subscription.j2
This updates this demo to use the Windows Containers GA bits.
Windows Containers Operator
> Updating Windows Containers Demo to use GA bits

- ansible/configs/sap-integration/default_vars.yml
- ansible/configs/sap-integration/default_vars_osp.yml
Add missing bastion instance and update to new OCP installer
> Add bastion instance back to OSP and update OCP installer version

- ansible/roles-infra/sandbox-ibm/tasks/configure_access.yml
This will update the variables set to identify the sandbox name and ID according to cloud_provider.
sandbox_name > ibm_sandbox_name
sandbox_account > ibm_sandbox_account
sandbox config
> Update sandbox config to identify cloud provider in variable

- ansible/configs/sap-integration/default_vars_osp.yml
Rollback default image to RHEL 8.1
> Rollback to RHEL 8.1

- ansible/configs/sap-integration/default_vars_osp.yml
Add a suggested variable by GPTE team to solve the existing issue for OCP on OSP.
> Add suggested workaround by GPTE team

- ansible/configs/sap-integration/files/k8s/3scale_operatorgroup.j2
- ansible/configs/sap-integration/files/k8s/3scale_subscription.j2
- ansible/configs/sap-integration/files/k8s/fuse_operatorgroup.j2
- ansible/configs/sap-integration/files/k8s/fuse_subscription.j2
- ansible/configs/sap-integration/files/k8s/fuse_syndesis.j2
- ansible/configs/sap-integration/files/k8s/ocs_operatorgroup.j2
- ansible/configs/sap-integration/files/k8s/ocs_subscription.j2
Update deployed workloads to match new OCP version and available Operator versions
> Update Fuse Online, 3scale and OCS workloads

- ansible/configs/sap-integration/custom_workloads.yml
Ignore the jaeger CSV results while checking other CSVs
> Ommit jaeger CSV while checking others

- ansible/roles_ocp_workloads/ocp4_workload_quay_operator/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/quay.j2
Add support for two new variables to specify the image tag for Quay and Clair to the Quay Workload.
> Add support to specify image tags for Quay/Clair for the Quay Workload

- ansible/roles/ocp-workload-gogs-load-repository/defaults/main.yml
- ansible/roles/ocp-workload-gogs-load-repository/tasks/clone_repo.yml
- ansible/roles/ocp-workload-gogs/tasks/workload.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/defaults/main.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/workload.yml
* Updating the workload to OCP 4.6 Workshop base
* Fix ocp-workload-gogs-load-repository
* Fix ocp-workload-gogs
```paste below
```
> Change workload ocp4-workload-homeroomlab-starter-guides update to 4.6 

- ansible/configs/sap-smart/default_vars.yml
- ansible/configs/sap-smart/software.yml
> Fix device name for SAP Smart Management

- ansible/roles/host_virtualenv/tasks/main.yml
Add retries to host_virtualenv role for pip requirements install.
Role host_virtualenv
> Change role host_virtualenv to add pip retries

- ansible/configs/sap-smart/sat_workload.yml
- ansible/configs/sap-smart/software.yml
Fix issue to deploy Satellite when using OSP 16, we have to add the internal hostname and IP address to /etc/hosts file
sap-smart
> Fix Satellite DNS resolution

- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/.travis.yml
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/templates/catalog-source.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/templates/erdemo-cr.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/templates/operator-group.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_emergency_response/templates/subscription.yml.j2
Add role for Emergency Response Demo
ocp4_workload_emergency_response
> Add push-button deployment for Emergency Response Demo

- ansible/configs/sap-smart/default_vars.yml
Workaround the not domain behavior caused by sap-preconfigure
sap-smart
> Overrride ansible domain

- ansible/configs/sap-smart/software.yml
Solve dict issue for host in hostgroups
sap-smart
> Change how hosts in groups are discovered

- ansible/configs/sap-smart/software.yml
Change group scope to all hosts
sap-smart
> Change group scope

- ansible/configs/sap-hana/software.yml
Iterate over SAP hosts only (HANA and S4HANA) to avoid issues while getting facts
sap-hana
> Iterate over SAP hosts only

- ansible/roles/ocp4-workload-ccnrd/files/stack.Dockerfile
- ansible/roles/ocp4-workload-ccnrd/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
Update ocp4-workload-ccnrd to rebuild Spring Boot 2.3.4
```paste below
```
> Update ocp4-workload-ccnrd to rebuild Spring Boot 2.3.4

- ansible/configs/ocp4-cluster/default_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/default_vars.yml
Update documentation and variable name for FTL for ocp4-cluster and ocp4-disconnected-osp-lab
ocp4-cluster
> Update FTL variables and docs

- ansible/roles/ocp4-workload-quarkus-workshop/files/quarkus-realm.json
This is a workaround before the following issues are fixed:
[1] https://github.com/quarkusio/quarkus/issues/14318
[2] https://issues.redhat.com/browse/QUARKUS-695
[3] https://issues.redhat.com/browse/KEYCLOAK-16837
```paste below
```
> Update ocp4-workload-quarkus-workshop fix the keycloak NPE issue

- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_master.j2
- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_nested.j2
!!!!! NEEDS REVIEW !!!! 
```paste below
```
> Updating Floating IP resources to include subnet id

- ansible/configs/sap-hana/files/cloud_providers/osp_cloud_template_master.j2
This PR is a complement of PR #3381  for sap-hana config 
config/sap-hana
> Updating Floating IP resources to include subnet id complement of #3381

- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Hard coded AMIs for ansible-windows needed extended for us-east-2
config/ansible/windows
> Added windows AMI for us-east-2

- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Fix typo in ami mapping
Fix typo in ami mapping
```paste below
```
> Fix typo in ansible windows ec2_cloud_template.j2

- ansible/configs/kni-osp/files/cloud_providers/osp_cloud_template_master.j2
> Testing FIP allocations

- ansible/configs/ocp4-disconnected-osp-lab/files/general-ms.yaml.j2
Update yaml manifest j2 template to support ocp4.6
> increment OCP version in templates

- ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile
Update ocp4-workload-quarkus-workshop to update RHBQ 1.7.6
```paste below
```
> Update ocp4-workload-quarkus-workshop to update RHBQ 1.7.6

- training/03_Infrastructure/02_Advanced/Adding_Versions_RHEL.adoc
> add Satellite config to secrets.yaml file explanation

- training/02_Getting_Started/06_deploying_a_base_config_osp.adoc
- training/03_Infrastructure/02_Advanced/Adding_Versions_RHEL.adoc
fix link # typo 
- 
02_Getting_Started/06_deploying_a_base_config_osp.adoc
03_Infrastructure/02_Advanced/Adding_Versions_RHEL.adoc
> fix link # typo - agD training doc

- ansible/configs/smart-management-foundations/pre_infra.yml
> Add default value to output_dir

- ansible/configs/smart-management-foundations/pre_infra.yml
Fixing broken ceph_cluster variable
```paste below
```
> smart-management-foundations updating ceph_cluster variable

- ansible/configs/ansible-multitier-rhel8/README.adoc
- ansible/configs/ansible-multitier-rhel8/default_vars.yml
- ansible/configs/ansible-multitier-rhel8/default_vars_ec2.yml
- ansible/configs/ansible-multitier-rhel8/default_vars_osp.yml
- ansible/configs/ansible-multitier-rhel8/destroy_env.yml
- ansible/configs/ansible-multitier-rhel8/files/cloud_providers/azure_cloud_template.j2
- ansible/configs/ansible-multitier-rhel8/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/ansible-multitier-rhel8/files/cloud_providers/terraform_ec2_cloud_template.tf.j2
- ansible/configs/ansible-multitier-rhel8/files/cloud_providers/terraform_ec2_cloud_template.tfvars.j2
- ansible/configs/ansible-multitier-rhel8/files/clouds.yaml.j2
- ansible/configs/ansible-multitier-rhel8/files/hosts_template.j2
- ansible/configs/ansible-multitier-rhel8/files/repos_template.j2
- ansible/configs/ansible-multitier-rhel8/files/ssh_config.j2
- ansible/configs/ansible-multitier-rhel8/files/tower_cli.j2
- ansible/configs/ansible-multitier-rhel8/post_infra.yml
- ansible/configs/ansible-multitier-rhel8/post_software.yml
- ansible/configs/ansible-multitier-rhel8/pre_infra.yml
- ansible/configs/ansible-multitier-rhel8/pre_software.yml
- ansible/configs/ansible-multitier-rhel8/software.yml
- ansible/configs/ansible-multitier-rhel8/start.yml
- ansible/configs/ansible-multitier-rhel8/stop.yml
add new ansible-multitier-rhel8 config to deploy 4 rhel8 hosts
```paste below
```
> Jdisrael add multi tier config

- ansible/configs/ansible-multitier-rhel8/pre_software.yml
> fix repo name

- ansible/configs/ansible-multitier-rhel8/default_vars_ec2.yml
Update RHEL 8 Definitive host definitions
ansible-multitier-rhel8
```paste below
```
> Update RHEL 8 Definitive host definitions

- ansible/configs/a-base-config/sample_variables/rhel8_server_on_ec2.yml
- ansible/configs/ans-tower-lab-ng/default_vars_ec2.yml
- ansible/configs/ans-tower-lab/default_vars_ec2.yml
- ansible/configs/ansible-multitier-rhel8/default_vars_ec2.yml
- ansible/configs/ansible-windows-elt/default_vars_ec2.yml
- ansible/configs/multi-cloud-capsule/default_vars_ec2.yml
- ansible/configs/ocp-workshop/README.adoc
- ansible/configs/ocp4-workshop/env_vars.yml
- ansible/configs/rhel-container-security/env_vars.yml
- ansible/configs/satellite-infrastructure/default_vars_ec2.yml
- ansible/configs/satellite-multi-region/env_vars.yml
- ansible/configs/satellite-vm/default_vars_ec2.yml
- ansible/configs/selinux-policy/env_vars.yml
- ansible/roles/ocp4-workload-infra-nodes/defaults/main.yml
- ansible/roles/ocp4_machineset_config/README.adoc
- ansible/roles/ocp4_machineset_config/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_example_dedicated_cluster/readme.adoc
- training/02_Getting_Started/07_deploying_a_base_config_aws.adoc
> aws: switch to AMD instances (10% cheaper)

- ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/quay.yml
Tack Quay channel for DSO workshop
> Specify Quay Channel for DSO workshop

- ansible/roles/ocp-workload-migration/templates/operator.yml.j2
Fixes the issue with operator.yml.j2 template 
Fixes #3438 
role: ocp-workload-migration
> Fix a bug in operator.yml template

- ansible/roles_ocp_workloads/ocp4_workload_open_data_hub_olm/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_open_data_hub_olm/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_open_data_hub_olm/templates/catalogsource.j2
- ansible/roles_ocp_workloads/ocp4_workload_open_data_hub_olm/templates/installplan.j2
- ansible/roles_ocp_workloads/ocp4_workload_open_data_hub_olm/templates/subscription.yaml.j2
> adds catalog snapshot support to odh operator role

- ansible/configs/rhel-custom-security-content/destroy_env.yml
add remove bookbag to destroy play for implementing custom security config in RHPDS
```paste below
```
> add remove bookbag to destroy play

- ansible/roles/gitlab-server/tasks/install-gitlab-server.yml
Variable added  called gitlab_package_name with default value. This variable helps to install gitlab server of particular version instead of latest.
Role: gitlab-server
> Variable added for package name

- ansible/configs/ansible-multitier-infra/Makefile
- ansible/configs/ansible-multitier-infra/pre_software.yml
Added a play for configuring podman service on an optional utility group in pre_software.yml
> Multitier podman support for ansible-multitier-infra

- ansible/configs/ocp4-cluster/lifecycle_hook_post_start.yml
- ansible/roles/ocp_cleanup_failed_pods/.yamllint
- ansible/roles/ocp_cleanup_failed_pods/README.adoc
- ansible/roles/ocp_cleanup_failed_pods/meta/main.yaml
- ansible/roles/ocp_cleanup_failed_pods/tasks/main.yaml
Add cleanup of failed pods for ocp4-cluster config with role ocp_cleanup_failed_pods
Role ocp_cleanup_failed_pods
> Add failed pod cleanup for ocp4-cluster

- ansible/configs/ocp-workloads/env_vars.yml
- ansible/configs/ocp-workloads/post_software.yml
Add ability to pass `infra_workloads` and `student_workloads` to ocp-workloads config for compatibility with ocp4-cluster config.
Config ocp-workloads
> Add infra and student workloads to ocp-workloads config

- ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/quay.yml
Fixed issue with Quay and DSO workshop
> Fixed issue with DSO workshop and Quay

- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
Fix infra-osp-template-generate yaml issue in additional floating ips functionality.
Role infra-osp-template-generate
> Fix additional fips for role infra-osp-template-generate

- ansible/roles-infra/infra-osp-project-create/tasks/main.yml
> Explicitly setting publicch  subnet to use

- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_master.j2
- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_nested.j2
> Updating OSP templates for explicit public subnet

- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_master.j2
> Remove needless depends_on

- ansible/roles/osp-image-packer/.yamllint
- ansible/roles/osp-image-packer/tasks/main.yml
New role added named `osp-image-packer` which creates image/images from instances. E.g satellite image. 
Role: osp-image-packer
> New Role: osp-image-packer

- ansible/roles/osp-image-packer/.yamllint
- ansible/roles/osp-image-packer/README.adoc
- ansible/roles/osp-image-packer/tasks/main.yml
Readme file added to role
role: osp-image-packer
> Image packer v1

- ansible/configs/ansible-advanced-v2/README.adoc
- ansible/configs/ansible-advanced-v2/default_vars.yml
- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/destroy_env.yml
- ansible/configs/ansible-advanced-v2/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/ansible-advanced-v2/files/clouds.yaml.j2
- ansible/configs/ansible-advanced-v2/files/hosts_template.j2
- ansible/configs/ansible-advanced-v2/files/playbook.yml
- ansible/configs/ansible-advanced-v2/files/repos_template.j2
- ansible/configs/ansible-advanced-v2/files/ssh_config.j2
- ansible/configs/ansible-advanced-v2/files/subenv_default_vars.yml.j2
- ansible/configs/ansible-advanced-v2/files/subenv_heat_template.j2
- ansible/configs/ansible-advanced-v2/post_infra.yml
- ansible/configs/ansible-advanced-v2/post_software.yml
- ansible/configs/ansible-advanced-v2/pre_infra.yml
- ansible/configs/ansible-advanced-v2/pre_software.yml
- ansible/configs/ansible-advanced-v2/requirements.yml
- ansible/configs/ansible-advanced-v2/sample_vars/osp_vars.yml
- ansible/configs/ansible-advanced-v2/satellite_clean_up.yml
- ansible/configs/ansible-advanced-v2/software.yml
new config for Advance Ansible version 2
config: ansible-advanced-v2
> new config ansible-advanced-v2

- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_master.j2
> Fixed jinja template syntax

- ansible/roles/ocp4-workload-ccnrd/files/cheplugin-meta.yaml
- ansible/roles/ocp4-workload-ccnrd/files/community-operators-index.yaml
- ansible/roles/ocp4-workload-ccnrd/files/pipelines_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/redhat-operators-index.yaml
- ansible/roles/ocp4-workload-ccnrd/files/serverless_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/stack.Dockerfile
- ansible/roles/ocp4-workload-ccnrd/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-guides.yaml
- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
update-ocp4-workload-ccnrd to upgrade OCP 4.7 features
```paste below
```
> update-ocp4-workload-ccnrd to upgrade OCP 4.7 features

- ansible/roles_ocp_workloads/ocp4_workload_pipelines/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
Latest pipeline operator changed the name of the CSV. So the logic needed updating.
Also set the latest defaults in the defaults file.
> Update Pipelines Workload for latest pipeline operator code

- ansible/roles/ocp4-workload-ccnrd/tasks/install-codeready.yaml
- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
Fix oc4-workload-ccnrd to update interactive OpenShift login as well as removing unused tools.
```paste below
```
> Fix oc4-workload-ccnrd to update interactive OpenShift login

- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
Update ocp4-workload-ccnrd to remove unused tools
```paste below
```
> Update ocp4-workload-ccnrd to remove unused tools

- ansible/roles/ocp4-workload-ccnrd/files/elasticsearch_subscription.yaml
Update ocp4-workload-ccnrd for updating elasticsearch-operator version
```paste below
```
> Update ocp4-workload-ccnrd for updating elasticsearch-operator version

- ansible/configs/satellite-hackfest/README.adoc
- ansible/configs/satellite-hackfest/default_vars.yml
- ansible/configs/satellite-hackfest/default_vars_osp.yml
- ansible/configs/satellite-hackfest/destroy_env.yml
- ansible/configs/satellite-hackfest/files/hosts_template.j2
- ansible/configs/satellite-hackfest/files/repos_template.j2
- ansible/configs/satellite-hackfest/files/ssh_config.j2
- ansible/configs/satellite-hackfest/post_infra.yml
- ansible/configs/satellite-hackfest/post_software.yml
- ansible/configs/satellite-hackfest/pre_infra.yml
- ansible/configs/satellite-hackfest/pre_software.yml
- ansible/configs/satellite-hackfest/requirements.yml
- ansible/configs/satellite-hackfest/sample_vars_osp.yml
- ansible/configs/satellite-hackfest/satellite_clean_up.yml
- ansible/configs/satellite-hackfest/setup_lab_user.yml
- ansible/configs/satellite-hackfest/software.yml
This config is similar to smart-management-foundations, but mixes RHEL 7 and 8 hosts for testing the new version of satellite.
```paste below
```
> new config for satellite 6.9 hackfest

- ansible/roles/ocp4-workload-ccnrd/files/stack.Dockerfile
Update ocp4-workload-ccnrd to update CLI tools version
```paste below
```
> Update ocp4-workload-ccnrd to update CLI tools version

- ansible/configs/ocp-workloads/requirements.yml
- ansible/configs/ocp4-cluster/requirements.yml
Add collection kubernetes.core to requirements for ocp-workloads and ocp4-cluster.
Confings ocp-workloads and ocp4-cluster
> Add kubernetes.core to requirements for ocp-workloads and ocp4-cluster.

- ansible/configs/ansible-advanced-v2/post_software.yml
Gitlab URL changed
post_software.yml
> Fixed Gitlab URL

- ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
- ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
Fix pipelines workload as well.
> Fix studentvm tekton

- ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
TASK [studentvm_ocp4 : Run restore context to reload selinux] ******************
Friday 12 March 2021  02:30:40 +0000 (0:00:05.018)       0:08:16.335 ********** 
fatal: [studentvm.g9s2j.internal]: FAILED! => {"changed": true, "cmd": "restorecon -R -v \\"/usr/local/bin/tkn /usr/local/bin/tkn-linux-amd64\\"", "delta": "0:00:00.006723", "end": "2021-03-12 02:30:42.312838", "msg": "non-zero return code", "rc": 255, "start": "2021-03-12 02:30:42.306115", "stderr": "restorecon: SELinux: Could not get canonical path for /usr/local/bin/tkn /usr/local/bin/tkn-linux-amd64 restorecon: No such file or directory.", "stderr_lines": ["restorecon: SELinux: Could not get canonical path for /usr/local/bin/tkn /usr/local/bin/tkn-linux-amd64 restorecon: No such file or directory."], "stdout": "", …
> Jaii tkn ocp4 studentvm selinux

- ansible/configs/sap-integration/custom_workloads.yml
- ansible/configs/sap-integration/default_vars.yml
- ansible/configs/sap-integration/files/k8s/camelk_subscription.j2
- ansible/configs/sap-integration/files/k8s/channel_ordercheck.j2
- ansible/configs/sap-integration/files/k8s/channel_returntxt.j2
- ansible/configs/sap-integration/files/k8s/gitops_cluster_role.j2
- ansible/configs/sap-integration/files/k8s/gitops_subscription.j2
- ansible/configs/sap-integration/files/k8s/integration_sap_odata.j2
- ansible/configs/sap-integration/files/k8s/integration_sap_sales_slack.j2
- ansible/configs/sap-integration/files/k8s/kamelet_bind_slack.j2
- ansible/configs/sap-integration/files/k8s/ns_sapserverless.j2
- ansible/configs/sap-integration/files/k8s/ns_serverless.j2
- ansible/configs/sap-integration/files/k8s/pipelines_subscription.j2
- ansible/configs/sap-integration/files/k8s/serverless_knativeeventing.j2
- ansible/configs/sap-integration/files/k8s/serverless_knativeserving.j2
- ansible/configs/sap-integration/files/k8s/serverless_operatorgroup.j2
- ansible/configs/sap-integration/files/k8s/serverless_subscription.j2
Extend SAP side-by-side lab with additional capabilities for Pipelines, GitOps and Serverless
> Extend side-by-side lab with additional features

- ansible/configs/sap-integration/custom_workloads.yml
- ansible/configs/sap-integration/default_vars.yml
Minor changes to fix a typo issue and default variables
> Fix file name typo and add default variables for slack

- ansible/configs/sap-integration/custom_workloads.yml
- ansible/configs/sap-integration/files/k8s/kamelet_slack_source.j2
- ansible/configs/sap-integration/files/k8s/serverless_knativeserving.j2
Remove indent for jinja raw and add remaining objects
> Fix raw indent and add final objects

- ansible/configs/sap-integration/files/k8s/channel_ordercheck.j2
- ansible/configs/sap-integration/files/k8s/channel_returntxt.j2
Add channel type to InMemoryChannel
> Move channels to memory channels

- ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/post_workload.yml
Add links to `user.info` for Lab Instructor README and DEMO video to be sent via final email.
> Add links to Lab Instructor README and DEMO video

- ansible/configs/sap-integration/files/k8s/kamelet_slack_source.j2
Add raw block to ignore not required variable during deployment
> Solve not required variable process

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/pre_software.yml
1. Satellite server image name updated
2. Packages installed using yum/dnf instead of pip3
ansible-advanced-v2
pre_software.yml
COnfig deployed and tested from laptop
> Satellite server image and packages updated

- ansible/roles/ocp4-workload-dil-streaming/tasks/user_projects.yaml
Fixes https://github.com/RedHat-Middleware-Workshops/dayinthelife-streaming/issues/80 
Change the validation to integer instead of string
DIL streaming
```paste below
```
> fix integer validation

- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
Fix ocp4-workload-ccnrd to fix debug issue in CRW
```paste below
```
> Fix ocp4-workload-ccnrd to fix debug issue

- ansible/roles/ocp4-workload-dil-streaming/tasks/provision_crw.yaml
- ansible/roles/ocp4-workload-dil-streaming/tasks/provision_fuse.yaml
- ansible/roles/ocp4-workload-dil-streaming/tasks/single_user.yaml
- ansible/roles/ocp4-workload-dil-streaming/tasks/workload.yml
- ansible/roles/ocp4-workload-dil-streaming/templates/crw-subscription.yaml.j2
- ansible/roles/ocp4-workload-dil-streaming/templates/fuse-subscriptionyaml.j2
…al for Fuse Online & same for CRW, async check for CRW
Fixes Related issue [https://github.com/RedHat-Middleware-Workshops/dayinthelife-streaming/issues/82]
1. Takes too long to provision for large clusters, moving all the snapshot catalog to openshift market place
2. Install operator without manual approval
> [Bug Fix] For ticket RITM0865429 (RHPDS DIL Streaming workshop failed) 

- ansible/roles_ocp_workloads/ocp4_workload_cyberark_dap/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_open_data_hub_olm/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_stackrox_central/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_stackrox_central/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_stackrox_sensor/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_stackrox_sensor/tasks/workload.yml
Multiple errors in yamllint. Fixed all of them.
ocp4_workload_cyberark_dap
ocp4_workload_stackrox_central
ocp4_workload_stackrox_sensor
ocp4_workload_open_data_hub_olm
> Fix YAMLLINT errors

- ansible/roles/ocp4_workload_stackrox_demo_apps/tasks/check_deployment.yml
This set of tasks was missing a retry and was defaulting to 3. Adding specific delays and retries.
ocp4_workload_stackrox_demo_app
> Update stackrox demo app role with retries

- ansible/configs/ocp4-ha-lab/requirements.yml
Bump ftl-injector version in a kinda out-dated config that now runs the Adv Deploy OSP ILT
config/ocp4-ha-lab
Not taking the chance of this never having been implemented in agnosticv.
> ftl-injector version bump

- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/cheplugin-meta.yaml
Update ocp4-workload-ccnrd-cuttingedge to update MTA 5.1.3
```paste below
```
> Update ocp4-workload-ccnrd-cuttingedge to update MTA 5.1.3

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
satellite image name modified and using new image
config: ansible-advanced-v2
> Modified image name 

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/pre_software.yml
replaced .bashrc with .bash_profile 
config: ansible-advanced-v2
> replaced .bashrc

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/pre_software.yml
- ansible/configs/ansible-advanced-v2/satellite_clean_up.yml
Removed rhn repo subscription task from satellite clean up task file
config: ansible-advanced-v2
> removed rhn task 

- ansible/roles/ocp4-workload-dil-agile-integration/defaults/main.yaml
- ansible/roles/ocp4-workload-dil-agile-integration/tasks/provision_backend.yaml
- ansible/roles/ocp4-workload-dil-agile-integration/tasks/provision_camelk.yaml
- ansible/roles/ocp4-workload-dil-agile-integration/tasks/provision_gogs.yaml
- ansible/roles/ocp4-workload-dil-agile-integration/tasks/provision_snapshotoperator.yaml
- ansible/roles/ocp4-workload-dil-agile-integration/tasks/provision_streams.yaml
- ansible/roles/ocp4-workload-dil-agile-integration/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-dil-agile-integration/tasks/workload.yml
- ansible/roles/ocp4-workload-dil-agile-integration/templates/apicurito-subscription.yaml.j2
- ansible/roles/ocp4-workload-dil-agile-integration/templates/camelk-subscription.yaml.j2
- ansible/roles/ocp4-workload-dil-agile-integration/templates/che-csc.yaml.j2
- ansible/roles/ocp4-workload-dil-agile-integration/templates/che-subscriptionyaml.j2
- ansible/roles/ocp4-workload-dil-agile-integration/templates/fuse-subscriptionyaml.j2
- ansible/roles/ocp4-workload-dil-agile-integration/templates/microcks-subscription.yaml.j2
- ansible/roles/ocp4-workload-dil-agile-integration/templates/snapshot-catalogsource.yaml.j2
- ansible/roles/ocp4-workload-dil-agile-integration/templates/sso-subscription.yaml.j2
- ansible/roles/ocp4-workload-dil-agile-integration/templates/streams-subscription.yaml.j2
- ansible/roles/ocp4-workload-dil-agile-integration/templates/threescale-subscription.yaml.j2
Fixes problem with SSO version by using the operatorhub snapshot
DIL Agile Integration 
```paste below
```
> Use operatorhub snapshot

- ansible/configs/sap-smart/sat_workload.yml
Solve an existing issue where Sat manifest won't refresh
sap-smart
> Fix Satellite manifest refresh issue

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/post_workload.yml
The ACM RHPDS demo needs credentials to enable the 2.2 reporting functionality. Grafana requires an S3 bucket to work. This will expose those in the provisioning note.
> Update ACM role to add credentials

- ansible/configs/osp-sandbox/.yamllint
- ansible/configs/osp-sandbox/post_software.yml
Change osp-sandbox config to use agnosticd_user_info
Config osp-sandbox
> Change config osp-sandbox to use agnosticd_user_info

- ansible/configs/sap-integration/post_software.yml
Use agnosticd_user_info in sap-integration config.
Config sap-integration
> Change sap-integration config to use agnosticd_user_info

- ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/post_workload.yml
Use agnosticd_user_info in ocp4_workload_dso
Role ocp4_workload_dso.
> Change role ocp4_workload_dso to use agnosticd_user_info

- ansible/roles_studentvm/studentvm_java_development/defaults/main.yml
- ansible/roles_studentvm/studentvm_java_development/tasks/main.yml
Added Symlink to fix Mandrel Native Builds. Renamed some variables for consistency.
studentvm_java_development
> Fix Mandrel deployment, updated variables

- ansible/roles_studentvm/studentvm_ocp4/defaults/main.yml
- ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
Made installation of various CLI tools customizable
studentvm_ocp4
> Added some logic to studentvm ocp4 role

- ansible/roles_studentvm/studentvm_ocp4/defaults/main.yml
- ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
Optionally add the `kubeseal` binary to a Student VM
studentvm_ocp4
> Optionally add kubeseal to studentvm

- ansible/roles/ocp4-workload-migration/defaults/main.yml
- ansible/roles/ocp4-workload-migration/tasks/post_workload.yml
Adding two new tasks in post_workload to download a couple of setup scripts in OCP4 environment for ocp4-workload-migration. 
Modifying location for content download. This is a first step in consolidating the download location within the konveyor repo. 
role ocp4-workload-migration
> Make deployment pull preparation script

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/aws_credentials.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/post_workload.yml
This is a fix for #3602 which missed setting the facts that were being used to gather the data to be included in the email. It will now set the facts properly. The tasks have also been moved into a separate task list.
> Update RHACM role with proper email info

- ansible/configs/ocp-workshop/post_software.yml
- ansible/roles/ocp4-workload-migration/tasks/post_workload.yml
Added Ansible populated var for GUID instead of determining by scripting. 
role: ocp4-workload-migration, task post_workload.yml
> Update GUID var for prepare_station.sh

- ansible/configs/sap-integration/files/k8s/kamelet_slack_source.j2
Slack source was using Telegram info. This will change the source to point to the correct one
> Change slack source to point to the correct config

- ansible/roles-infra/infra-ec2-template-generate/templates/cloud_template.j2
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'sandbox_student_user' is undefined"}
```
```paste below
```
> Fix AnsibleUndefinedVariable  in default cloudformation template

- ansible/roles-infra/infra-ec2-template-generate/templates/cloud_template.j2
Fixes:
`FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'owner' is undefined"}`
> Update EC2 default template

- ansible/configs/sap-smart/default_vars.yml
Update Satellite to 6.8
sap-smart
> WIP - Update Satellite version to 6.8

- ansible/configs/sap-smart/default_vars.yml
Revert changes for not required merge
sap-smart
> Revert changes for a non required change

- ansible/configs/ocp-workshop/.yamllint
- ansible/configs/ocp4-workshop/.yamllint
- ansible/configs/ocp4-workshop/software.yml
- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-migration/tasks/post_workload.yml
Some bastion names were still hard-coded. Replaced with variables.
role, ocp4_workload_migration
> Adding bastion names as vars

- ansible/configs/ansible-infoblox/tower_configure.yml
increase retry and delay counts
```paste below
```
> increase retry and delay counts

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/aws_credentials.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/post_workload.yml
The current version of this role is trying to grab cloudformation_out_final on the bastion, but it needs to come from localhost.
> Update ACM workload with proper localhost var

- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/cheplugin-meta.yaml
Fix ocp4-workload-cccnrd-cuttingedge to update MTA version
```paste below
```
> Fix ocp4-workload-cccnrd-cuttingedge to update MTA version

- ansible/roles_studentvm/studentvm_ocp4/defaults/main.yml
- ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
Updated some tools for studentvm.
Added optional install of kam, argocd(-util) and kustomize.
studentvm_ocp4
> Update available tools in studentvm

- ansible/roles_studentvm/studentvm_ansible/.yamllint
- ansible/roles_studentvm/studentvm_ansible/defaults/main.yml
- ansible/roles_studentvm/studentvm_ansible/meta/main.yml
- ansible/roles_studentvm/studentvm_ansible/tasks/main.yml
Add a new studentvm role to deploy Ansible.
> Added role studentvm_ansible

- ansible/configs/sap-integration/custom_workloads.yml
- ansible/configs/sap-integration/files/k8s/camelk_catalosource.j2
- ansible/configs/sap-integration/files/k8s/camelk_subscription.j2
Use a custom snapshoft of the Camel-K catalog
> Use custom Camel-K snapshot to stick to version v1.3.1

- ansible/configs/sap-integration/files/k8s/kamelet_slack_source.j2
Remove no longer required parameters from the Kamelet
> Remove kamelet not required parameters

- ansible/configs/ocp4-cluster/post_software.yml
Changed a @bastion. hard-coded name into an ansible variable
ocp4-cluster post_software.yml
> Changed hard-coded bastion to variable

- ansible/configs/sap-integration/files/admin_host_requirements.txt
- ansible/configs/sap-integration/files/macos_requirements.txt
- ansible/configs/sap-integration/files/requirements_k8s.txt
Reverts redhat-cop/agnosticd#3585
> Revert "Bump pyyaml from 5.3 to 5.4 in /ansible/configs/sap-integration/files"

- ansible/roles/ocp-workload-migration/templates/operator.yml.j2
Updating OCP3 version of MTC in the migration workshop. 
role, ocp3-workload-migration
> Ocp3 update

- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/files/clusterrole-sealed-secrets-user.yaml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/files/sealed-secrets-controller.yaml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/workload.yml
Added workload to deploy (and configure) Sealed Secrets via the Sealed Secrets Operator.
> Added workload to deploy sealed secrets operator

- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/workload.yml
Had implemented a suggestion on how to create YAML k8s files. Didn't work. Reverting back to the proven way.
> Fix sealed secret controller role (revert back to definition from src)

- ansible/roles/install_operator/defaults/main.yml
- ansible/roles/install_operator/tasks/install.yml
- ansible/roles/install_operator/templates/catalogsource.yaml.j2
- ansible/roles/install_operator/templates/subscription.yaml.j2
Fixed channel calculation. Somehow the channel was empty outside the block.
> Fix channel calculation

- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/files/sealed-secrets-controller.yaml
> Fix sealed secrets controller name

- ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/files/helm_chart_repository.yaml
- ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/tasks/workload.yml
Added a role to deploy the one remaining customization for the OpenShift Advanced App Deploy ILT (2021 version).
ocp4_workload_adv_app_deploy_ilt
> Add Adv App App Deploy Role

- ansible/configs/ansible-tower/requirements.yml
- tests/static/syntax-check.sh
- Tests Pull Request
```paste below
```
> Fix CI tests

- ansible/roles/ocp4-workload-migration/defaults/main.yml
- ansible/roles/ocp4-workload-migration/tasks/post_workload.yml
Add variable to ocp4-workload-migration role to control setup of bookbag. Default to retain current behavior.
Role ocp4-workload-migration
> Add ocp4_workload_migration_deploy_bookbag for ocp4-workload-migration

- ansible/roles/ocp-workload-migration/tasks/post_workload.yml
- ansible/roles/ocp4-workload-migration/tasks/post_workload.yml
> mtc: add bastions

- ansible/roles/ocp4-workload-rhsso-foundations/tasks/pre_workload.yml
Fixed workload to handle user names with underscores. Previously user name "john_doe" failed. This fix resolves the issue.
The fix was recommended by Chandra Bose and Guillaume.
ocp4-workload-rhsso-foundations
> Fix workload: ocp4-workload-rhsso-foundation: user name fix - handle for underscores in username

- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack.Dockerfile
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/templates/devfile.json.j2
Update ocpr-workload-ccnrd-cuttingedge to update RHBQ 1.11
```paste below
```
> Update ocpr-workload-ccnrd-cuttingedge to update RHBQ 1.11

- ansible/roles/ocp4-workload-migration/defaults/main.yml
Fix default admin user list to match ocp4_workload_authentication role.
Role ocp4-workload-migration.
> Fix default admin users for ocp4-workload-migration

- ansible/roles/ocp4-workload-ccnrd/files/stack.Dockerfile
- ansible/roles/ocp4-workload-ccnrd/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
update-ocp4-workload-ccnrd to update RHBQ 1.11
```paste below
```
> update-ocp4-workload-ccnrd to update RHBQ 1.11

- ansible/configs/sandbox/pre_infra_ec2.yml
Add punctuation to AWS Sandbox rando password.
sandbox
Required to match AWS IAM password requirements.
> Add punctuation to AWS Sandbox rando password

- ansible/roles/ocp4-workload-ccnrd/files/cheplugin-meta.yaml
Fix to ocp4-workload-ccnrd for MTA issue on CRW 2.8
```paste below
```
> Fix to ocp4-workload-ccnrd for MTA issue on CRW 2.8

- docs/.gitignore
- docs/First_OSP_Env_walkthrough.adoc
- use IP address instead of DNS name of DNS server
- GitHub doesn't follow properly symlinks hence not using it
- linking docs to two issues created
- ignoring files generated by asciidoctor(-pdf)
- hint to replace more secret variables
docs/First_OSP_Env_walkthrough.adoc
See discussion in GChat...
> Finish walkthrough of introductory instructions for OSP

- ansible/configs/ibm-rhoic/destroy_env.yml
- ansible/configs/ibm-rhoic/infra.yml
- ansible/configs/ibm-rhoic/software.yml
Updating the order I used for naming resources from guid-type to type-guid, IBM Cloud does not like numbers as the first character in some resource types and our guid's can start with numbers.
config/ibm-rhoic
Also updated the body in the uri tasks to use native Ansible formatting instead of hand crafted JSON as it is much easier to maintain.
> Update config ibm-rhoic

- ansible/configs/sandbox/pre_infra_ec2.yml
> add more bad characters to AWS IAM password

- ansible/configs/sap-hana/README.adoc
- ansible/configs/sap-integration/README.adoc
- ansible/configs/sap-rhvh/README.adoc
- ansible/configs/sap-smart/README.adoc
Ricardo Garcis is taking over my role as TMM for Portfolio Architecture and he will be looking after the SAP initiative and SAP related labs. I'm not removing my name for now as we will be working in a transition period until he takes full ownership.
many
> Add Ricardo Garcia as new owner for SAP related configs

- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
Change role ocp-workload-integreatly to use agnosticd_user_info
Role ocp-workload-integreatly
> Change role ocp-workload-integreatly to use agnosticd_user_info

- ansible/roles_ocp_workloads/ocp4_workload_monitoring_grafana/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_grafana/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_grafana/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_grafana/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_grafana/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_grafana/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_grafana/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_grafana/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_prometheus/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_prometheus/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_prometheus/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_prometheus/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_prometheus/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_prometheus/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_prometheus/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_monitoring_prometheus/tasks/workload.yml
SUMMARY:
This is a workload to install Promethues and Grafana community operators at namespace level per each student. The namespace is variable. For now it'll be used in the Adv. CND VILT, but can be used by any catalog.
ISSUE TYPE
New config Pull Request
COMPONENT NAME
> Adding Prometheus and Grafana Community Operator to user namespace.

- ansible/roles_ocp_workloads/ocp4_workload_amq_streams/tasks/workload.yml
SUMMARY:
Fixing the operator name for AMQ Streams - new configuration. Issue found when testing the catalog.
ISSUE TYPE
COMPONENT NAME
> fixing operator name

- ansible/cloud_providers/ec2_infrastructure_deployment.yml
> ODCR condition: be compatible with ansible 2.7.9

- ansible/roles_ocp_workloads/ocp4_workload_cnd_apicurio_registry_operator/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_grafana/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_grafana/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_grafana/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_prometheus/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_prometheus/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_prometheus/tasks/workload.yml
Added support to Prometheus and Grafana workloads for CND to deploy into multiple namespaces
ocp_workload_cnd_monitoring_prometheus 
ocp_workload_cnd_monitoring_grafana
> Update cnd workloads

- ansible/configs/sap-integration/files/k8s/gitops_cluster_role.j2
- ansible/configs/sap-integration/files/k8s/gitops_subscription.j2
- ansible/configs/sap-integration/files/k8s/pipelines_subscription.j2
Move GitOps Operator and Pipelines Operator to stable releases
> Move GitOps and Pipelines to GA subscription

- ansible/roles/ocp4-workload-dil-streaming/defaults/main.yaml
- ansible/roles/ocp4-workload-dil-streaming/tasks/provision_webapp.yaml
- ansible/roles/ocp4-workload-dil-streaming/templates/instructions-deployment.yaml.j2
- ansible/roles/ocp4-workload-dil-streaming/templates/instructions-group.yaml.j2
Update the application of the instructions to v0.0.63 and use the custom operator
Fixes https://github.com/RedHat-Middleware-Workshops/dayinthelife-streaming/issues/40 
ocp4-workload-dil-streaming
```paste below
```
> use custom operator

- docs/First_OSP_Env_walkthrough.adoc
The link was wrong, the sandbox is in rhpds not in labs...
> Just change the labs.opentlc link to correct rhpds.redhat for OSP sandbox

- ansible/configs/sap-smart/default_vars.yml
- ansible/configs/sap-smart/sat_workload.yml
Instead of using a custom manifest for the lab, we are moving to GPTE provided one
sap-smart
> Use Sat manifest from GPTE so new variables are required

- ansible/roles_ocp_workloads/ocp4_workload_cnd_apicurio_registry_operator/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_apicurio_registry_operator/templates/namespace-admin-rb.j2
- ansible/roles_ocp_workloads/ocp4_workload_cnd_tracing_jaeger/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_tracing_jaeger/templates/namespace-admin-rb.j2
SUMMARY:
Adding user admin access to the new created projects: schema-registry and tracing.
ISSUE TYPE
COMPONENT NAME
> Adding user admin access to the new projects.

- ansible/configs/sap-smart/default_vars.yml
- ansible/configs/sap-smart/post_software.yml
- ansible/configs/sap-smart/sat_workload.yml
We would like to use Satellite 6.9 instead of 6.7 for this lab, in order to do that I have added the necessary repos and added more options to the Satellite installer command following the Satellite 6.9 documentation
Added repos and installation variables for Satellite 6.9
```paste below
```
> Added repos and config for Satellite 6.9

- ansible/configs/studentvm/default_vars.yml
- ansible/configs/studentvm/requirements.yml
- ansible/configs/studentvm/software.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/gitea.yaml.j2
Remove logic to install FTL if `ftl_injector_tag` is set. Unify to install only if `install_ftl=true` like other configs. FTL Injector version comes from requirements.yml.
studentvm
> Update install_ftl handling for StudentVM

- ansible/roles/install_operator/tasks/remove.yml
Remove extra debug statement in install_operator role
> Remove debug statement

- ansible/roles/set-repositories/tasks/satellite-repos.yml
Add HA support for satellite subscription
set-repositories-satellite
```paste below
```
> Add HA support for satellite subscription

- training/02_Getting_Started/01_Introduction.adoc
> removed my name from subtitle

- training/02_Getting_Started/06_deploying_a_base_config_osp.adoc
> fixed config issues (member vars)

- training/02_Getting_Started/06_deploying_a_base_config_osp.adoc
> added jq installation command

- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/files/sealed-secrets-controller.yaml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/workload.yml
The Sealed Secret Community operator is crap... So replacing the Operator with the Helm Chart - which is also better maintained.
Need to use the helm binary because AgnosticD doesn't support using the k8s collection.
> Convert sealed secrets from Operator to Helm Chart

- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/workload.yml
/usr/local/bin is not writeable as ansible-user. Needs become.
> Fix sealed secrets path

- training/02_Getting_Started/06_deploying_a_base_config_osp.adoc
> fixing bugs

- training/03_Infrastructure/01_Foundational/04_Modify_a_base_config_Lab.adoc
> added bastions to AnsibleGroup, to avoid pb failure

- ansible/configs/sap-smart/post_software.yml
> Add Satellite Tools repo for Satellite 6.9

- ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml
Fixing trailing spaces on PR #3851
> Fix trailing spaces error

- training/03_Infrastructure/01_Foundational/04_Modify_a_base_config_Lab.adoc
> fixed rhel_image error for node instance

- ansible/roles/set-repositories/tasks/satellite-repos.yml
Fix bug in satellite HA
```paste below
```
> Fix bug in satellite HA

- ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/approve_installplan.yml
- ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/workload.yml
- ansible/roles/ocp-workload-aiedge-computing-blueprint/templates/installplan.yaml.j2
Add updated ACM objects for new features in the demo
Feature Pull Request
Role: ocp-workload-aiedge-computing-blueprint
Safe to merge upon approval
> Add ACM objects for AI Edge cluster

- tools/virtualenvs/ansible2.10-python3.6-2021-06-14.txt
Add pywinrm and requests-credssp to virtualenv ansible2.10-python3.6-2021-06-14
Virtual environment ansbile2.10-python3.6-2021-06-14
Technically this is cheating and we should not update virtualenvs but rather create new ones.
> Update ansible2.10-python3.6-2021-06-14 venv for pywinrm, requests-credssp

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
Change `debug` to `agnosticd_user_info`.
Role ocp4-workload-quarkus-workshop
> Change ocp4-workload-quarkus-workshop to use agnosticd_user_info

- ansible/configs/rhel-container-security/env_vars.yml
Changing AMI to RHEL8.4
env_vars.yml
Keeping up with latest RHEL AMI
> using latest RHEL

- ansible/configs/rhel-custom-security-content/destroy_env.yml
Fix rhel-custom-security-content bookbag destruction by executing on localhost for virtualenv.
Config rhel-custom-security-content
> Fix config rhel-custom-security-content bookbag destroy

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
Update ocp4-workload-quarkus-workshop to rebase user info
- 
```paste below
```
> Update ocp4-workload-quarkus-workshop to rebase user info

- ansible/configs/rhel-security/destroy_env.yml
Add task to destroy bookbag environment in RHEL Security config.
rhel-security
Similar to https://github.com/redhat-cop/agnosticd/pull/3874
> Add task to destroy bookbag environment in RHEL Security config.

- ansible/roles_ocp_workloads/ocp4_workload_amq_streams/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_amq_streams/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_apicurio_registry_operator/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_apicurio_registry_operator/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_grafana/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_grafana/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_prometheus/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_prometheus/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_tracing_jaeger/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_cnd_tracing_jaeger/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_nexus_operator/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_nexus_operator/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml
install_operator role changed some of the parameters (and some of the logic) to be more flexible.
This PR updates all consumers of that role to use the new variable names.
Multiple workloads
> Update "install_operator" consumers for latest changes

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
Fix indentation issue in `agnosticd_user_info` in role `ocp4-workload-quarkus-workshop`.
Role ocp4-workload-quarkus-workshop
> Fix indentation in ocp4-workload-quarkus-workshop

- ansible/configs/ansible-tower-advanced/README.adoc
- ansible/configs/ansible-tower-advanced/env_vars.yml
- ansible/configs/ansible-tower-advanced/requirements.yml
- ansible/configs/ansible-tower-advanced/sample_vars.yml
- bump Tower version to 3.8.3-1
- bump RHEL version to RHEL 8.4
- connect to Satellite
- use awx.awx collection 19.1.0
- improve instructions in readme and sample_vars
- Update config Pull Request
ansible-tower-advanced
Was dependent on PRs #3881, #3882 and #3883 (already merged)
> adapt ansible-tower-advanced to Tower 3.8 and RHEL 8

- ansible/configs/satellite-vm/README.adoc
- ansible/configs/satellite-vm/default_vars.yml
- ansible/configs/satellite-vm/default_vars_osp.yml
- ansible/configs/satellite-vm/files/repos_template.j2
- ansible/configs/satellite-vm/pre_software.yml
- ansible/configs/satellite-vm/requirements.yml
- ansible/configs/satellite-vm/sample_vars_ec2.yml
- ansible/configs/satellite-vm/sample_vars_osp.yml
- ansible/roles/satellite-insights/tasks/version_6.7.yml
- ansible/roles/satellite-installation/tasks/main.yml
- ansible/roles/satellite-installation/tasks/version_6.9.yml
- ansible/roles/satellite-manage-activationkey/tasks/version_6.x.yml
- ansible/roles/satellite-manage-compute-profile/tasks/main.yml
- ansible/roles/satellite-manage-host/tasks/version_6.x.yml
- ansible/roles/satellite-manage-hostgroup/tasks/main.yml
- ansible/roles/satellite-manage-setting/tasks/main.yml
- ansible/roles/satellite-manage-userroles/tasks/role.yml
- ansible/roles/satellite-manage-userroles/tasks/user.yml
- ansible/roles/satellite-provisioning/tasks/provisioning_resources.yml
- ansible/roles/satellite-publish-content-views/tasks/version_6.x.yml
- ansible/roles/satellite-verification/tasks/main.yml
> Satellite 6.9 updates

- ansible/roles_ocp_workloads/ocp4_workload_data_grid/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_data_grid/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_data_grid/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_data_grid/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_data_grid/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_data_grid/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_data_grid/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_data_grid/tasks/workload.yml
SUMMARY:
This is a workload to install Data Grid operator at cluster level. For now it'll be used in the Adv. CND VILT, but can be used by any catalog.
ISSUE TYPE
New config Pull Request
COMPONENT NAME
> datagrid operator.

- ansible/roles/host-ocp4-installer/defaults/main.yml
- ansible/roles/host-ocp4-installer/tasks/print_cluster_info.yml
Add user data and facts for cluster access in host-ocp4-installer role.
Role host-ocp4-installer.
> Set user data and facts in host-ocp4-installer role

- ansible/configs/ansible-multi-node/post_software.yml
- ansible/configs/ansible-multi-node/software.yml
user_info output had wrong boolean, fixes output of automationcontroller user_info (URL etc)
config `ansible-multi-node`
> Tidy up to config ansible-multi-node and fix for user-info output

- ansible/action_plugins/agnosticd_odcr.py
> On-Demand Capacity Reservations: do not create reservation when count == 0

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/defaults/main.yml
Fix validation check for prometheus StatefulSet
ocp4-workload-rhte-analytics_data_ocp_workshop
> ODH Data Engineering: Fix validation check for prometheus statefulset

- ansible/completion_callback.yml
Add messages for email body to completion callback.
Completion callback playbook.
> Add user message body to completion callback

- ansible/setup_runtime.yml
> Add missing cloud providers to pre-check

- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_grafana/tasks/workload.yml
SUMMARY:
Fixing the Grafana Operator. 
ISSUE TYPE
COMPONENT NAME
> fixing operator grafana.

- ansible/roles/host-ocp4-installer/tasks/install_installer.yml
We were checking for 3 parts (2 dots) - which fails for 4.8.0-rc.3. Need to check for >=3
> Fix check for number of periods in installer version

- ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_grafana/tasks/remove_workload.yml
SUMMARY:
Updating the Grafana Operator, remove section based on PR 3938.
ISSUE TYPE
COMPONENT NAME
```
> updating the remove section with the namespace

- ansible/configs/ansible-automation-platform/env_vars.yml
- ansible/configs/ansible-automation-platform/software.yml
Updating the code to download the manifest locally with a secret password and username.
```paste below
```
> Update ansible-automation-platform for manifest

- ansible/configs/ansible-automation-platform/software.yml
Variable naming scheme of dictionary was incorrect.
```paste below
```
> Ansible Automation Playform fix variable name

- ansible/configs/ansible-infoblox/post_software.yml
- ansible/configs/ansible-infoblox/requirements.yml
- ansible/configs/ansible-infoblox/sample_vars/sample_infoblox_lab.yml
- ansible/configs/ansible-infoblox/tower_configure.yml
* Changed sate;lite_manifest to tower_manifest to better describe what it is for
* Added dtc (DNS Traffic Controll ) to nios temp licenses.  Allows DTC based labs.
* Separated lab output strings into multiple tasks to resolve issues with lab documentation being generated out of order.   
ansible-infoblox
```
> updates to ansible infoblox lab.  

- ansible/roles_ocp_workloads/ocp4_workload_open_data_hub_olm/defaults/main.yml
might fix AIML and data engineering labs
> updates olm catalog snapshot tag

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
Added haproxy pod variables in default_osp_vars.yml
config: ansible advanced v2
> Added variables for pod

- ansible/configs/ansible-multi-node/sample_vars/automationcontroller_cluster.yml
- ansible/roles/deploy_automationcontroller/README.md
- ansible/roles/deploy_automationcontroller/defaults/main.yml
- ansible/roles/deploy_automationcontroller/tasks/main.yml
- ansible/roles/deploy_automationcontroller/templates/automationcontroller_inventory.j2
Added functionality to the deploy_automationcontroller role to allow more flexible scenarios for deployments:
- all-in-one
- controller + external database
- cluster 
Added functionality to allow local or remote manifests to be used, to assist both production and local (laptop) deploys
Improved documentation and updated with new vars
Refactored and added greater consistency in task and variable naming
Note. The role is not in production use yet so changes should not impact existing CIs or configs
role/deploy_automationcontroller
> Enhance role deploy_automationcontroller

- ansible/configs/ansible-infoblox/default_vars.yml
- ansible/configs/ansible-infoblox/post_software.yml
- ansible/configs/ansible-infoblox/requirements.yml
- ansible/configs/ansible-infoblox/sample_vars/sample_infoblox_lab.yml
- ansible/configs/ansible-infoblox/tower_configure.yml
Add nios_temp_license: nios IB-V825 dns dhcp enterprise dtc  to default_vars.yml in ansible-infoblox config.
```
> Add nios_temp_license: nios IB-V825 dns dhcp enterprise dtc  to default_vars.yml in ansible-infoblox config.

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/satellite_clean_up.yml
Added a task to refresh satellite (build from image) subscription.
Ansible Advanced v2 config
> Subscription refresh task

- ansible/configs/ansible-advanced-v2/default_vars.yml
- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/satellite_clean_up.yml
Added RHEL8 packages list in variables file.
Ansible Advanced V2 config
> Added rhel8 packages list

- ansible/configs/ansible-advanced-v2/default_vars.yml
- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/pre_software.yml
- ansible/configs/ansible-advanced-v2/satellite_clean_up.yml
Removed installation duplicate task from pre_software.yml
Ansible Advanced v2 config
> Removed duplicate task

- ansible/configs/ansible-advanced-v2/default_vars.yml
- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/files/pods/haproxy/haproxy.cfg.j2
- ansible/configs/ansible-advanced-v2/pre_software.yml
- ansible/configs/ansible-advanced-v2/satellite_clean_up.yml
Added haproxy final lab backend entry in haproxy.cfg.j2 template
Ansible Advanced v2
> Added Final Lab in Haproxy

- ansible/configs/sap-smart/files/cloud_providers/osp_cloud_template_master.j2
Added if logic to jinja templates for osp_public_subnet
> Added if logic for osp_public_subnet for sap smart mgmt

- ansible/roles/control-user/tasks/create-user.yml
- ansible/roles/control-user/tasks/ssh-config.yml
Fix control-user logic error
control-user
> Fix omit error in create-user ssh setup

- ansible/configs/ansible-multi-node/post_software.yml
- ansible/configs/ansible-multi-node/setup-hands-on-aap2.yml
Add no_log to remove a htpasswd output
Improved jinja boolean conditional to use `sameas true`
config ansible-multi-node
> Minor fixes to hona lab for security and user.info config ansible-multi-node

- ansible/configs/ansible-multi-node/post_software.yml
- ansible/configs/ansible-multi-node/sample_vars/hands_on_aap2.yml
Cleans up trailing \n output
Sets correctly ssh user
config ansible-multi-node
> Improve user_info and add control_user to ssh cmd

- ansible/configs/sap-integration/lifecycle_hook_post_start.yml
When the cloud provider is different than ec2, the inventory is not built, and the CSR are not approved resulting in a broken cluster.
This change, if applied, add includes to build the inventory for OSP and Azure so the certificates are all approved there too.
```paste below
```
> Sap integration

- ansible/configs/ans-tower-lab-ng/post_software.yml
- ansible/configs/ans-tower-lab-ng/pre_software.yml
ans-tower-lab-ng 
Python2 was borked
```paste below
```
> ans-tower-lab-ng updates for broken lab

- ansible/configs/ans-tower-lab-ng/post_software.yml
- ansible/configs/ans-tower-lab-ng/pre_software.yml
ansible-tower-lab-ng
Lab needs to use python3 as an interpreter for ansible commands
```paste below
```
> ans-tower-lab-ng fix homework deployment

- ansible/roles/bookbag/.yamllint
- ansible/roles/bookbag/tasks/deploy-bookbag.yaml
- ansible/roles/bookbag/tasks/workload.yaml
Add support for multi-user deployment of bookbag to the bookbag role. If data for multiple users is found in the user info this will cause the bookbag role to now deploy an instance for each user.
bookbag role
> Add bookbag role multi-user support

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
Added lab_mgr_dir  variable for lab_manager path.
Ansible Advanced v2
> Added lab manager path variable

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/post_software.yml
- ansible/configs/ansible-advanced-v2/pre_software.yml
Added lab_mgr_dir variable in access_details.
Ansible Advanced V2
> added var in access_details

- ansible/roles/ocp4-workload-jdg-workshop/templates/devfile.json.j2
fix the codeready devfile to remove the embedded commands
> remove embedded from menu

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/post_software.yml
- ansible/configs/ansible-advanced-v2/pre_software.yml
Fixed lab-manager path to save access-details.
Ansible Advanced v2
> fixed access details path

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/post_software.yml
- ansible/configs/ansible-advanced-v2/pre_software.yml
Fixed type in lab_mgr_dir variable name.
Ansible Advanced V2
> Fixed type 

- ansible/roles/install_operator/tasks/install.yml
Increasing the timeout delay for troubleshooting
> Increasing Timeout

- ansible/configs/ansible-advanced-v2/pre_software.yml
Added releases to Lab Manager repository hence updating task to use release instead main branch. 
Ansible Advanced v2
> Added Lab Manager release

- ansible/roles_ocp_workloads/ocp4_workload_dso/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/quay.yml
Resolved issue with DSO lab where Quay was not deploying
> Fixed Quay DSO CSV issue

- ansible/configs/osp-migration/infra.yml
- ansible/roles-infra/infra-osp-project-create/tasks/main.yml
Add setting guid and uuid tags for openstack environments.
Config osp-migration
Role infra-osp-project-create
> Add set guid, uuid tags for OpenStack environments

- ansible/roles/ocp4-workload-homeroomlab-odo/defaults/main.yml
Update the repo to point to the official one here: https://github.com/openshift-labs/lab-developing-with-odo
ocp4-workload-homeroomlab-odo
> Change workload ocp4-workload-homeroomlab-odo update repo

- ansible/configs/test-empty-config/infra.yml
- ansible/configs/test-empty-config/sample_vars_equinix_metal.yml
- ansible/roles-infra/infra-equinix-metal-dry-run/defaults/main.yaml
- ansible/roles-infra/infra-equinix-metal-dry-run/tasks/main.yaml
> Add equinix metal dry-run role for testing

- ansible/roles/ocp4-workload-workshop-admin-storage/files/production-cluster-admin.json
Updating to use quay.io/openshift/origin-console:latest
> Updating web console image

- ansible/roles/host-lets-encrypt-certs-certbot/templates/run-certbot.j2
Total copy/paste fail on my part that I would have caught if I tested with OSP on top of AWS and Azure
roles/host-lets-encrypt-certs-certbot
@stencell found this error
> CHANGE: host-lets-encrypt-certs-certbot

- ansible/configs/ibm-rhoic/infra.yml
- ansible/configs/ibm-rhoic/software.yml
Updating retries on "Applying the plan" as per comment from GPTE during auto testing
configs/ibm-rhoic
RITM0959756
> CHANGE config ibm-rhoic

- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/workload.yml
Add controls for agnosticd_user_info for ocp4_workload_shared_cluster_access
Also add `agnosticd_user_info` data reporting for ocp4_workload_shared_cluster_access.
Config ocp4_workload_shared_cluster_access
> Add controls for agnosticd_user_info for ocp4_workload_shared_cluster_access

- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/README.adoc
- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/templates/operatorgroup.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_tigera_calico/templates/subscription.yml.j2
Adding a workload to add Tigera Calico operator and client configuration to an OCP 4 cluster.
roles_ocp_workloads/ocp4_workload_tigera_calico
Tested on OpenShift 4.7.15+
> ADD roles_ocp_workloads/ocp4_workload_tigera_calico

- ansible/roles_studentvm/studentvm_user/defaults/main.yml
- ansible/roles_studentvm/studentvm_user/tasks/main.yml
* Remove use of `user` with `agnosticd_user_info` as this is only for use with multi-user environments.
* Add controls for `agnosticd_user_info`
* Switch from `debug` to `agnosticd_user_info` for messages.
* Add additional user data items
Role studentvm_user
> Fix user data for studentvm_user role

- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Microsoft AMI issues resolved with hard coded AMI updates
config ansible-windows
> Windows ami updated

- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/ccn-sso74-template.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/cheplugin-meta.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/community-operators-index.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/coolstore-monolith-binary-build-template.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/coolstore-monolith-pipeline-build-template.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/eap74-openjdk11-image-stream.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/elasticsearch_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/redhat-operators-index.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack.Dockerfile
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/install-guides.yaml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/workload.yml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/templates/devfile.json.j2
Update ocp4-workload-ccnrd-cuttingedge based OCP 4.8
Please be sure to restore the cutting-edge category item based OCP 4.8 in RHPDS
```paste below
```
> Update ocp4-workload-ccnrd-cuttingedge based OCP 4.8

- tools/virtualenvs/equinix_metal-ansible2.9-python3.6-2021-07-02.txt
The venv doesn't work on tower.
> Add psutil to equinix venv

- tools/virtualenvs/equinix_metal-ansible2.9-python3.6-2021-07-02.txt
> Add selinux to equinix venv

- ansible/roles/ocp-client-vm/defaults/main.yml
- ansible/roles/ocp-client-vm/tasks/main.yml
Path changed for oc CLI binaries.
ocp-client-vm
> Updated OC Client Locations for ClientVMs (and add mirror support)

- ansible/configs/insights-technical-sales/README.adoc
- ansible/configs/insights-technical-sales/default_vars.yml
- ansible/configs/insights-technical-sales/default_vars_osp.yml
- ansible/configs/insights-technical-sales/destroy_env.yml
- ansible/configs/insights-technical-sales/files/hosts_template.j2
- ansible/configs/insights-technical-sales/files/repos_template.j2
- ansible/configs/insights-technical-sales/files/ssh_config.j2
- ansible/configs/insights-technical-sales/post_infra.yml
- ansible/configs/insights-technical-sales/post_software.yml
- ansible/configs/insights-technical-sales/pre_infra.yml
- ansible/configs/insights-technical-sales/pre_software.yml
- ansible/configs/insights-technical-sales/sample_vars_osp.yml
- ansible/configs/insights-technical-sales/setup_lab_user.yml
- ansible/configs/insights-technical-sales/software.yml
Creating a new config for the Insights for Technical Sales course releasing soon
insights-technical-sales
Within the config the value of "update_packages:" has been purposefully set to false to ensure insights can detect issues on the "node" system. There is separate logic in the "pre_software.yml" to update the control system separately.
```paste below
```
> New config for Insights course

- ansible/roles_ocp_workloads/ocp4_workload_authentication/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/workload.yml
Add controls for `agnosticd_user_info` reporting for `ocp4_workload_authentication` role.
Role ocp4_workload_authentication.
> Add agnosticd_user_info controls for ocp4_workload_authentication

- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/.travis.yml
- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/templates/cache_v1alpha1_himss2021.yaml
- ansible/roles_ocp_workloads/ocp4_workload_sepsis_detection/templates/sepsisdetection-operator-all-configs.yml
This new agnosticD role deploys a full instance of the [HIMSS 2021 Sepsis Detection demo](https://github.com/redhat-naps-da/himss_interoperability_showcase_2021/blob/master/README.adoc).
This is a new demo to be made in RHPDS  in  Catalogs -> Multi-Product Demo.
The demo is to deploy in a OCP 4.8 _training_ cluster.
> HIMMS 2021 Sepsis Detection Demo

- ansible/roles-infra/infra-aws-open-environment/tasks/print_user_info.yaml
> Fix OpenEnv, use the 'sandbox_account' variable

- ansible/roles-infra/infra-aws-sandbox/README.adoc
> infra-aws-sandbox: move to redhat-gpe/aws-sandbox

- ansible/roles/host-ocp4-destroy/tasks/main.yml
> Add poll to async task

- ansible/configs/ibm-rhoic/default_vars.yml
- ansible/configs/ibm-rhoic/software.yml
Making the name match similar variables and settings a default so it doesn't fail if not set.
configs/ibm-rhoic
N/A
> CHANGE: config/ibm-rhoic

- ansible/configs/rosa/software.yml
Change location of ocm file because RH Eng changed location in rosa script
rosa
```paste below
```
> Change location of ocm file because RH Eng changed location in rosa script

- ansible/configs/rosa/software.yml
Create missing config dir on rosa homedir
```paste below
```
> fix rosa deployment

- ansible/roles/ocp4-workload-ccnrd-cuttingedge/defaults/main.yml
- ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/create_che_workspace.yaml
Update ocp4-workload-ccn-cuttingedge to fix the CRW issue
```paste below
```
> Update ocp4-workload-ccn-cuttingedge to fix the CRW issue

- ansible/roles/ocp4-workload-ccnrd-cuttingedge/templates/devfile.json.j2
Fix ocp4-workload-ccn-cuttingedge to fix the devfile issue
```paste below
```
> Fix ocp4-workload-ccn-cuttingedge to fix the devfile issue

- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/templates/cloudformation.yaml.j2
New Workload for the Advanced OpenShift Day 2 Operations ILT.
- Retrieves two FIPs from OpenStack
- Creates Route53 entries for the FIPs.
ocp4_workload_adv_day2_ops_ilt
> Add adv ops ilt workload

- ansible/lifecycle_osp.yml
> Fix OSP lifecycle, do not fail if servers are already being shelved

- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/workload.yml
Add reporting openshift_username to ocp4_workload_shared_cluster_access.
Role ocp4_workload_shared_cluster_access
> Add reporting username to ocp4_workload_shared_cluster_access

- ansible/roles/ocp4_approve_certificate_signing_requests/tasks/approve-certificate-signing-requests.yml
> While the instances are starting, retry get CSRs

- ansible/roles/ocp4-workload-quarkus-workshop/files/codeready_cr.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/community-operators-index.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/redhat-operators-index.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/rhsso-template.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile
- ansible/roles/ocp4-workload-quarkus-workshop/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/create_che_workspace.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhsso.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/templates/devfile.json.j2
Update ocp4-workload-quarkus-workshop to update OCP 4.8
```paste below
```
> Update ocp4-workload-quarkus-workshop to update OCP 4.8

- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/tasks/workload.yml
Bugfix: CloudFormation stacks must start with a letter.
ocp4_workload_adv_day2_ops_ilt
> Change Route53 Stack Name

- ansible/configs/aap2-ansible-workshops/README.adoc
- ansible/configs/aap2-ansible-workshops/ansible.cfg
- ansible/configs/aap2-ansible-workshops/destroy_env.yml
- ansible/configs/aap2-ansible-workshops/env_vars.yml
- ansible/configs/aap2-ansible-workshops/post_infra.yml
- ansible/configs/aap2-ansible-workshops/post_software.yml
- ansible/configs/aap2-ansible-workshops/pre_infra.yml
- ansible/configs/aap2-ansible-workshops/pre_software.yml
- ansible/configs/aap2-ansible-workshops/sample_vars.yml
- ansible/configs/aap2-ansible-workshops/software.yml
- ansible/configs/aap2-ansible-workshops/vars/README.adoc
- ansible/configs/aap2-ansible-workshops/vars/advanced_tower_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/common_all_ansible_workshop_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/f5_tower_workshop_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/networking_arista_tower_workshop_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/networking_cisco_tower_workshop_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/networking_juniper_tower_workshop_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/networking_multivendor_tower_workshop_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/rhel_90_tower_workshop_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/rhel_tower_workshop_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/security_tower_workshop_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/tower_advanced_users_workshop_vars.yml
- ansible/configs/aap2-ansible-workshops/vars/windows_tower_workshop_vars.yml
- tests/static/syntax-check.sh
New config to allow AAP2 Ansible Workshops to be deployed without impacting existing 1.2 workshops
config aap2-ansible-workshops
> Create new config aap2-ansible-workshops

- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/defaults/main.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/post_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/pre_workload.yml
Update content to OCP 4.8 and Pipelines Operator 1.5.x
- Update homeroom lab tag
- Use agnosticd_user_info
ocp4-workload-homeroomlab-tekton-pipelines
> Change workload ocp4-workload-homeroomlab-tekton-pipelines: Update to 4.8

- ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/tasks/workload.yml
Add `agnosticd_user_info` for users in ocp4_workload_rhods_olm workload.
Role ocp4_workload_rhods_olm
> Add user info reporting for ocp4_workload_rhods_olm

- ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/tasks/workload.yml
* adds user data for workshops
* add default user count and switch variable
* user details for workshop mode for RHODS
* Reformat workshop message and other tweaks
* Alter workshop output
Co-authored-by: Erik M Jacobs <erikmjacobs@gmail.com>
```paste below
```
> Add user info reporting for ocp4_workload_rhods_olm (#4134)

- ansible/configs/aap2-ansible-workshops/requirements.yml
- ansible/configs/ansible-workshops/requirements.yml
Encapsulates the collections required for the AAP 1 **and** AAP2 workshops
config ansible-workshops
config aap2-ansible-workshops
<
> Collections captured from admin-dev for AAP2 and AAP1 workshops

- ansible/configs/osp-migration/pre_infra.yml
Set virtualenv for osp-migration import host
> Add ansible_playbook_python for osp-migration import host

- ansible/roles/ocp-workload-migration/meta/main.yml
- ansible/roles/ocp4-workload-migration/meta/main.yml
Changing contact name and details for main.yaml of ocp migration workloads. 
> Changing author/contact from Pranav to Nenad

- ansible/roles/ocp4-workload-ocs-poc/tasks/remove_workload.yml
Enhance remove_workload.yml by removing finalizers
ocp4-workload-ocs-poc
```paste below
```
> Remove finalizers for ocp4-workload-ocs-poc remove_workload.yml

- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/workload.yml
Add Flag to Sealed Secrets Controller to report status (and therefore enable ArgoCD to monitor sealed secrets properly).
> Fix Sealed Secrets not reporting status

- ansible.cfg
> Add collections_path to ansible.cfg

- ansible/configs/ocp4-equinix-aio/requirements.yml
> Add community.general to requirements in config

- ansible.cfg
Reverts redhat-cop/agnosticd#4212
> Revert "Add collections_path to ansible.cfg"

- ansible/configs/ansible-advanced-v2/default_vars_osp.yml
- ansible/configs/ansible-advanced-v2/post_software.yml
- ansible/configs/ansible-advanced-v2/pre_software.yml
- ansible/configs/ansible-advanced-v2/software.yml
Modification were made to use new version of lab-manager which has course prep.
Advanced ansible - v2
> Modification done to use new version of lab-manager

- ansible/configs/ansible-advanced-v2/post_software.yml
- ansible/configs/ansible-advanced-v2/pre_software.yml
- ansible/configs/ansible-advanced-v2/satellite_clean_up.yml
Modify repository configuration task to run on all nodes. 
Ansible advanced v2
> Modify satellite  tasks

- ansible/configs/ibm-rhoic/default_vars.yml
- ansible/configs/ibm-rhoic/software.yml
Adding support to adjust the number of worker nodes on each deployment
configs/ibm-rhoic
N/A
> CHANGE: configs/ibm-rhoic

- ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/templates/argocd_argocd.yaml.j2
Updated ArgoCD image version to latest in v2.0.x stream. Fixes a few issues with homework.
> Update ArgoCD version

- ansible/configs/ocp4-cluster/requirements.yml
Add community.general 4.0.2 collection to ocp4-cluster
ocp4-cluster
> Add community.general collection

- ansible/roles/ocp4-workload-dil-streaming/templates/webapp.yaml.j2
day in the life - streaming workshop
```paste below
```
> fix codeready service url

- ansible/roles/host-ocp4-installer/tasks/main.yml
Oops. Changing /root requires become: True
> Fix permission error

- ansible/roles_ocp_workloads/ocp4_workload_industrial_edge/tasks/workload.yml
Syntax error in super fancy split logic... Fixed.
ocp4_workload_industrial_edge
> Fix logic in split

- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/templates/kustomization.yaml.j2
Updated Sealed Secrets Workload to:
- Use kubernetes.core.helm to install/remove Sealed Secrets Helm Chart
- Alternatively deploy a kustomized sealed secrets controller to allow deployment on OCP 4.9
> Update sealed secrets

- ansible/roles/ocp4-workload-oadp/.yamllint
- ansible/roles/ocp4-workload-oadp/README.adoc
- ansible/roles/ocp4-workload-oadp/defaults/main.yml
- ansible/roles/ocp4-workload-oadp/meta/main.yml
- ansible/roles/ocp4-workload-oadp/tasks/main.yml
- ansible/roles/ocp4-workload-oadp/tasks/post_workload.yml
- ansible/roles/ocp4-workload-oadp/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-oadp/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-oadp/tasks/workload.yml
- ansible/roles/ocp4-workload-oadp/templates/cloud-credentials.yml.j2
- ansible/roles/ocp4-workload-oadp/templates/oadp-operator-operatorgroup.yml.j2
- ansible/roles/ocp4-workload-oadp/templates/oadp-operator-subscription.yml.j2
- ansible/roles/ocp4-workload-oadp/templates/velero.yml.j2
This is a PR which enables a new role for a workload on top of OCP4. 
It is connected to a CI OCP4_OADP
It was tested and it deploys successfully in test clusters outside of AgD and it deploys in AgD DEV environment without errors. 
role name: ocp4-workload-oadp
Thank you :)
> Create a new role ocp4-workload-oadp for a new CI

- tools/virtualenvs/README.adoc
Update README for virtualenvs to document kubernetes library issue.
Virtualenv docs
> Update virtualenvs README

- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/pre_workload.yml
This section was expanded to not use a loop and one of the paths, was mistyped.
```paste below
```
> correcting path

- ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/infrastructure.yml
Increasing retry delays
```paste below
```
> ocp4_workload_dso - Jenkins Retry Delay

- ansible/roles_ocp_workloads/ocp4-workload-fsi-risk-analytics/files/management-ui.yaml
- ansible/roles_ocp_workloads/ocp4-workload-fsi-risk-analytics/files/risk-officer-ui.yaml
Fixed deployment yaml - added image reference
ocp4-workload-fsi-risk-analytics
> Fixed deployment yaml - added image reference

- ansible/configs/ansible-windows/Makefile
- ansible/configs/ansible-windows/env_vars.yml
- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Fix broken ansible-windows config with new, hard coded, AMI values (due to be retired shortly)
config ansible-windows
> Fix ansible-windows AMI issue and enhance Makefile

- ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/workload.yml
missed a var in the last push
ocp4_workloads_rhel_worker
```paste below
```
> [WiP] rhel worker bastion key

- ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/workload.yml
rework to simplify
add ansible-user: ec2-user to hopefully clue in tower
```paste below
```
> WiP - rhel worker - admin key, again
