redhat-cop/agnosticd

ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/README.adoc, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/add-codeready-user.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/add_che_user.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/confirm_che_workspace.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/create_che_workspace.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/create_project.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/remove-codeready-user.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/remove_che_user.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/remove_che_workspace.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/verify-workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/verify_che_workspace.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/templates/devfile.json.j2
Adds a new workload to deploy (and remove) the per-user quarkus workshop components for a single user, after the cluster is prepared with the shared cluster workload (`ocp4-workload-quarkus-workshop`). 
`ocp4_workload_quarkus_workshop_user`
cc @jkupferer @danieloh30 @wkulhanek for RHTR. @danieloh30  later we will need to separately add the guides/code to the workshop repos, then modify the agnosticV variables to only install the spring->quarkus stuff (`m3`) for RHTR.
=> Add single user workload for Quarkus Workshop on a shared cluster

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
Fix role `ocp4_workload_gitea_operator` in task `Print the user details if users are created` when attempting to use pass a str when using format `user%d`
You can test by running the role with variables
```
ocp4_workload_gitea_operator_create_users: true
```
=> Fix role ocp4_workload_gitea_operator to convert str -> int when using jinja2 format filter

ansible/roles-infra/infra-osp-resources-destroy/.yamllint, ansible/roles-infra/infra-osp-resources-destroy/tasks/detect_project.yml, ansible/roles-infra/infra-osp-resources-destroy/tasks/heat.yml, ansible/roles-infra/infra-osp-resources-destroy/tasks/keypairs.yml, ansible/roles-infra/infra-osp-resources-destroy/tasks/main.yml, ansible/roles-infra/infra-osp-resources-destroy/tasks/project.yml, ansible/roles-infra/infra-osp-resources-destroy/tasks/project_resources.yml, ansible/roles-infra/infra-osp-resources-destroy/vars/main.yml
Clean-up for infra-osp-resources-destroy role.
* Update to Ansible 2.9, replacing facts modules with info modules
* add `.yamllint`
* move environment settings to the role vars rather than repeating in several places
- Clean-up Pull Request
infra-osp-resources-destroy
=> Clean-up role infra-osp-resources-destroy

ansible/roles_ocp_workloads/ocp4_workload_rhacm/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/templates/catalogSource.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm/templates/installplan.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm/templates/subscription.j2
This will allow the RHACM workload to use a catalog snapshot. To use the snapshot, the `ocp4_workload_rhacm_use_catalog_snapshot` must be set to true. 
=> Update RHACM workload to use catalog source

ansible/roles/ocp-workload-migration/templates/operator.yml.j2
=> Update workload ocp-workload-migration to use latest image SHAs

ansible/configs/kni-osp/files/fix-overlay.sh, ansible/configs/kni-osp/files/ocp-install.sh.j2, ansible/configs/kni-osp/software.yml
The baremetal installer relies on library-go to build the
openshift-install binary. Unfortunately this relies on an
unstable URL. This bumps the version to something a lot newer
and is referenced in commit 077cc86cafd75bb95023434deb93b110ea2ae106
kni-osp
=> Remove the automated openshift-installer build and add some checks for deploy success (overlayfs)

ansible/roles/ocp4-workload-quarkus-workshop/defaults/main.yml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-codeready.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/verify-workload.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/install-guides.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/verify-workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/workload.yml
When using the `ocp4-workload-quarkus-workshop` workload to lay down infra when `num_users` is 0, we don't need to install the username-distribution or guides, so skip them with a `when:` clause.
For the per-user workload `ocp4-workload-quarkus-workshop-user`, deploy per-user guides that provide support for using the per-user unique `guid` variable for creating OCP project/namespaces, and then output the proper URL in the resulting `user.info` for the final email which gives a direct link to the per-user guide.
Also, add the definition for module 3 (`m3`).
`ocp4-quarkus-workshop` and `ocp4-quarkus-workshop-user`
cc @danieloh30 @jkupferer
=> create per-user guides; skip some infra steps when num_users <= 0

ansible/roles_ocp_workloads/ocp4_workload_quay_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/catalogsource.j2, ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/installplan.j2, ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/operatorgroup.j2, ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/quay.j2, ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/subscription.j2
Quay Operator
- Add Support for Catalog Snapshots
- Cleanup all around
- Remove workarounds for previous bugs
- Remove settings to set images for Quay and Clair, those should come from the operator based on CSV
- Test that latest operator works (and cleans up after itself)
=> Added support for catalog snapshots, cleanup all around

ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/remove_workload.yml
There was a bug in the Windows Node playbook that, due to a missing variable, it didn't remove the workload. This PR fixes that issue.
ocp4_workload_windows_node
=> Updated removal playbook with the proper variables

ansible/roles_ocp_workloads/ocp4_workload_authentication/defaults/main.yml
The ocp4_workload_authentication_ldap_bind_password is currently set to `<FROM SECRET>` in defaults, which prevents the `fail` task in the workload from reporting that this variable has not been set.
ocp4_workload_authentication role
=> Change role ocp4_workload_authentication to not set bind password

ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml
Several times already my deployment has failed because the Serverless CSV is not ready in a timely manner.
Proposed change is to increase retries from 15 to 30.
=> Serverless: increase timeout for CSV waiting

ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/tasks/workload.yaml
Fix yamllint warnings on role ocp4_workload_bookbag_user.
- Fixed two long line length warnings
- Tightened yamllint rules to treat line length as error
- Code Clean-Up Pull Request
role ocp4_workload_bookbag_user
=> Fix role ocp4_workload_bookbag_user yamllint warnings

ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/deployment.yaml.j2
The AUTH_USERNAME and AUTH_PASSWORD environment variables for openshift-homeroom (aka bookbag) configure authentication options. This PR adds `ocp4_workload_bookbag_user_auth_username` and 
`ocp4_workload_bookbag_user_auth_password` variables to control these environment variables.
role ocp4_workload_bookbag_user
=> Add role ocp4_workload_bookbag_user AUTH_USERNAME and AUTH_PASSWORD

docs/Contributing.adoc
Add standard `.yamllint` configuration example to docs.
Rationale: We need a standard `.yamllint` configuration documented so that we can converge our configuration and code standards to this configuration.
Contributing documentation.
=> Add doc for .yamllint

ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml
Bugfix. Ignore insecure connection when downloading kn binary from the cluster if run before certificates have been added.
Workload: ocp4_serverless
=> Add insecure tolerance to kn download

ansible/roles/ocp4-workload-homeroomlab-starter-guides/defaults/main.yml
Fix typo for repo git url: https://github.com/openshift-labs/starter-guides
`defaults/main.yml`
RHPDS fails at **checkSoftwareDeploy**
Logs:
```
TASK [ocp4-workload-homeroomlab-starter-guides : Create homeroom resources] ****
Friday 02 October 2020  05:54:28 -0400 (0:00:00.051)       1:19:42.907 ********
changed: [bastion.723f.internal]
TASK [ocp4-workload-homeroomlab-starter-guides : Wait for the homeroom to deploy] ***
Friday 02 October 2020  05:54:32 -0400 (0:00:04.569)       1:19:47.476 ********
changed: [bastion.723f.internal]
TASK [ocp4-workload-homeroomlab-starter-guides : Git clone the repo if it doesn't exist] ***
Friday 02 October 2020  05:55:05 -0400 (0:00:32.285)       1:20:19.762 ********
=================================================================== …
```
=> Fix role ocp4-workload-homeroomlab-starter-guides update git repo url

ansible/configs/ansible-gitOps-integration/files/repos_template.j2, ansible/configs/ansible-tower-implementation/files/repos_template.j2, ansible/configs/three-tier-app/files/repos_template.j2
Fix epel repo base url in ansible configs.
Configs:
- ansible-gitOps-integration
- ansible-tower-intergation
- three-tier-app
=> Fix ansible config epel repo url

ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
This commit, if applied, adds dependencies between the following
resources in the default HOT template:
- servers require ports
- ports require security groups
- subnet requires network
It tries to fix the network issues we're having on Green.
=> Change osp-template-generate, Fix dependencies of resources in heat template

ansible/configs/sap-hana/find_snapshot.yml, ansible/configs/sap-hana/pre_infra.yml
This commit fixes the following error:
```
TASK [Find out SnapShot ID for SAP Software] ***********************************
Tuesday 06 October 2020  03:02:38 -0400 (0:00:00.178)       0:00:05.462 ******* 
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'aws_secret_access_key' is undefined\n\nThe error appears to be in '/tmp/openstack-SAP_E2E_AUTOMATION-prod-9dcc-2818/agnosticd/ansible/configs/sap-hana/pre_infra.yml': line 32, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Find out SnapShot ID for SAP Software\n      ^ here\n"}
```
config sap-hana
=> Fix sap-hana: don't lookup EC2 snapshots when cloud is osp

ansible/configs/kni-osp/files/clouds.yaml.j2
This commit, if applied, fixes the following error:
```
TASK [Create clouds.yaml file] *************************************************
Tuesday 06 October 2020  03:59:03 +0000 (0:00:01.900)       0:10:58.291 *******
fatal: [provision]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'osp_auth_username_member' is undefined"}
```
=> kno-osp: Fix facts in clouds.yaml.j2 template

ansible/configs/kni-osp/files/clouds.yaml.j2
The variable isn't defined by default, fallback to use the fact osp_project_info.
=> Change KNI config, fix osp_project_id in clouds.yml.j2 template

ansible/configs/kni-osp/default_vars.yml
This commit, if applied, fixes the following error:
```
TASK [Resolving install-config] ************************************************
Tuesday 06 October 2020  13:09:28 +0000 (0:00:03.089)       0:11:16.083 *******
fatal: [provision]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ocp4' is undefined"}
```
=> Change KNI lab, Fix typo in variable name

ansible/configs/ocp4-disconnected-osp-lab/default_vars.yml
Change config ocp4-disconnected-osp-lab to use `ocp4_pull_secret` as default value for `test_deploy_pull_secret`. This standardizes the variable name to match `ocp4-cluster` config.
config ocp4-disconnected-osp-lab
=> Change config ocp4-disconnected-osp-lab to use ocp4_pull_secret

ansible/configs/smart-management/pre_infra.yml, ansible/configs/smart-management/pre_software.yml
Issue with ssh keys in group testing for the RHTR remediation lab. I believe this is being caused by this role accidentally being called more than once.
```paste below
```
=> smart-management removing redundant key generation

ansible/roles/set-repositories/tasks/satellite-repos.yml
Update set-repositories role to pass consumer_name for satellite registration. For some reason, setting `network.fqdn` in `/etc/rhsm/facts/katello.facts` was not sufficient.
Role set-repositories
=> Update set-repositories role to pass consumer_name for registration

ansible/configs/sap-hana/default_vars.yml, ansible/configs/sap-hana/pre_software.yml
Trying to fix:
```
TASK [install common packages for RHEL 8] **************************************
Wednesday 07 October 2020  10:24:48 -0400 (0:00:00.066)       0:03:52.774 ***** 
fatal: [hana-testing-2d84]: FAILED! => {"attempts": 1, "changed": false, "msg": "Failed to download metadata for repo 'rhel-8-for-x86_64-appstream-e4s-rpms'", "rc": 1, "results": []}
fatal: [bastion-testing-2d84]: FAILED! => {"attempts": 1, "changed": false, "msg": "Failed to download metadata for repo 'rhel-8-for-x86_64-highavailability-e4s-rpms'", "rc": 1, "results": []}
fatal: [s4hana-testing-2d84]: FAILED! => {"attempts": 1, "changed": false, "msg": "Failed to download metadata for repo 'rhel-8-for-x86_64-appstream-e4s-rpms'", "rc": 1, "results": []}
fatal: [tower-testing-2d84]: FAILED! => {"attempts": 1, …
```
=> Rollback #2655 and add retries to the command

ansible/configs/ocp4-cluster/default_vars.yml, ansible/roles/host-ocp4-installer/tasks/main.yml
Introduce a new variable, *ocp4_network_ovn_install_workaround*, for the ocp4-cluster config.
This is necessary to install a workaround during the installation of OCP 4.6+ with OVN Networking. Since this workaround is *only* necessary for Windows nodes set to false by default.
Previous logic would have applied the workaround regardless of need if OVN was selected.
ocp4-cluster
=> Introduce ocp4-cluster variable ocp4_network_ovn_install_workaround

ansible/roles-infra/infra-osp-resources-destroy/tasks/detect_project.yml
Because this role currently sets the environment variable OS_PROJECT_NAME to be the ansible variable `osp_project_name` we are seeing auth failures on the initial project detection.
This PR forces the detect project to use OS_PROJECT_NAME `admin` for this task.
Role infra-osp-resources-destroy
=> Fix role infra-osp-resources-destroy to detect project from admin

ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/job-image-pull.j2
Adding task that "prepulls" the Windows base image. This helps by speeding up application deployment since the image is 5GB in size.
This is done by creating a Job that does an `ssh` connection to the Windows node and runs a `docker pull` of the image. This job is run in the same namespace as the operator, so that it may use the same secret needed to ssh into the Windows node.
Right now this is a "best effort" and I only check if the job gets created. The playbook should still succeed even if the job fails. I've accounted for this in my documentation to the student.
- Adding a `job` task.
=> Updating playbook to prepull image for student

.github/workflows/lfs.yml
LFS check jobs are all showing canceled with no other information. Disabling for now.
- Issue workaround
LFS check GitHub action
=> Disable lfs check

ansible/roles_ocp_workloads/ocp4_workload_windows_node/defaults/main.yml
The Windows Machine Operator [has changed the namespace it deploys to](https://github.com/openshift/windows-machine-config-operator/blob/master/deploy/namespace.yaml#L4) to be in-line with other OpenShift components.
Windows Machine Config Operator
=> updating the windows machine operator namespace

ansible/roles/ocp4-workload-openbanking-sandbox/tasks/3amp-deploy-full-api.yml
Fixes #3033 in order to pass the provisioning test in the DEV SHARED environment.
The resolution is about using the `template` module instead of defining a property with `lookup('template',  <absolute-path>)`.
ROLE: ocp4-workload-openbanking-sandbox
See #3033
=> Open Banking Sandbox CI DEV - use 'template' module as a mid step to process downloaded J2 file

ansible/roles_ocp_workloads/ocp4_workload_rhtr_xraylab_user/tasks/workload.yaml
Remove agnosticd_user_info for ocp4_workload_rhtr_xraylab_user to remove redundant information from user info that will be available in the lab instructions.
Role ocp4_workload_rhtr_xraylab_user
=> Remove role ocp4_workload_rhtr_xraylab_user extra user info

ansible/roles_ocp_workloads/ocp4_workload_rhtr_xraylab_user/tasks/grafana-operator.yaml
Under load, the Grafana operator may take time to produce a status. The check was failing because the Phase entry was non existent, so could not even be checked if Succeeded.
Patched sets a default value for the check to happen.
=> Modify check for Grafana operator status

ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/main.yml
Append a condition('destroy') to execute the pre_workload task.
```paste below
```
=> Update role ocp4_workload_quarkus_workshop_user to fix destroy issue

ansible/roles_ocp_workloads/ocp4_workload_rhtr_xraylab/templates/storage/rgw_objectstore.yaml.j2
Initially the RGW in OCS is set up to handle http traffic only. This is problematic when the Lab is used with browsers with restrictions in mixed traffic (http/https). This is a small patch on the route to allow both traffics on the same Route.
=> XRay Lab - Allow both secure and insecure traffic on the RGW

ansible/roles/ocp-workload-migration/templates/operator.yml.j2, ansible/roles/ocp4-workload-migration/tasks/workload.yml, ansible/roles/ocp4-workload-migration/templates/mig-operator-subscription-downstream.yml.j2
This PR:
- Updates OCP3 migration workload to use latest MTC 1.3.0 release
- Pins down version of OCP4 migration workloads to MTC 1.3.0 using Manual install plan
```paste below
```
=> Update MTC (formerly CAM) workloads to MTC 1.3

ansible/configs/ansible-gitOps-integration/default_vars.yml, ansible/configs/ansible-gitOps-integration/post_software.yml
Add option to suppress user info messages for lab, making it easier for the user to find the link. All access information should be embedded in lab instructions.
Config ansible-gitOps-integration
=> Add config ansible-gitOps-integration var to suppress user info messages

ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/post_workload.yml
Add comma(,) to fix Print module info in ocp4_workload_quarkus_workshop_user workload 
```paste below
```
=> Update ocp4_workload_quarkus_workshop_user workload to fix Print module info

ansible/configs/ocp4-cluster/destroy_env_osp.yml
@marcosmamorim noticed that ocp4-cluster configs left qcow2 images in the OpenStack cluster after deletion.
This PR cleans this up.
ocp4-cluster
=> Delete RHCos image if it exists on OpenStack

ansible/roles/host-ocp4-installer/tasks/main.yml
Bug fix: ocp4_network_ovn_install_workaround didn't have a default where checked to prevent configs other than ocp4-cluster from failing.
host_ocp4_installer
=> Fix missing default on ovn_workaround

ansible/roles_ocp_workloads/ocp4_workload_dso/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/infrastructure.yml
Minor fix-up for ocp4_workload_dso registry route detection. This adds a failure condition to the step when getting the route to make failure more obvious.
Also remove step to expose the registry as this task will have failed here if the registry were not already exposed.
=> Fix role ocp4_workload_dso registry route detection

ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/infrastructure.yml, ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/pre_workload.yml
The  variable ocp4_dso_ocp_registry_route is referenced in the pre_workload.yml and so needs to be set before use there.
=> Fix role ocp4_workload_dso to set ocp4_dso_ocp_registry_route in pre_workload

ansible/roles/host-ocp4-provisioner/tasks/osp_prereqs.yml
OCP 4 Provisioner would always create a directory /home/{{ ansible_user }}/resources on the bastion. This is not necessary. Remove the creation of this directory (the ocp4_disconnected_lab is the only config that needs this and creates the directory anyway).
host_ocp4_provisioner
=> Don't create resources directory on bastion by default

ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml
In OpenShift Serverless 1.10 the kn-cli-download route does no longer seem to be created.
Therefore add a test  to only try to download the kn cli if the route exists.
=> Add test to kn download if it doesn't exist.

ansible/roles/ocp-workload-migration/templates/operator.yml.j2, ansible/roles/ocp4-workload-migration/tasks/workload.yml, ansible/roles/ocp4-workload-migration/templates/mig-operator-subscription-downstream.yml.j2
Updates migration workloads from MTC 1.3.0 to 1.3.1
```paste below
```
=> Update migration workloads to MTC 1.3.1

ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/install-codeready.yaml
The import of the quarkus-stack image in the `ocp_workload_dso` role can result in an intermittent failure. Error log output included at the end of this description. This appears to be a timing issue between the creation of the image stream and import of the images. The import has been updated with retries and a ten second delay to mitigate potential concurrency issues.
ocp_workload_dso role
Error log output
```
TASK [ocp4_workload_dso : import stack image] **********************************
Wednesday 21 October 2020  15:06:29 -0400 (0:00:01.163)       1:27:51.867 *****
fatal: [bastion.7e01.internal]: FAILED! => {"changed": true, "cmd": "oc import-image --all quarkus-stack -n openshift\n", "delta":
"0:00:00.142603", "end": "2020-10-21 19:06:29.498440", "msg": …
```
=> Fix intermittent failure of oc import

ansible/roles/vscode-server/tasks/vscode-server.yml
vscoder-server role pulls in the extensions into the vscode user homedir as root, extensions are 700 root and this can create issues installing them as another user e.g. devops
role vscode-server
=> Fix permissions issues with vscode extensions belonging to root

tests/jenkins/downstream/poll_email.py
This change fixes the following error in jenkins:
```+ ./tests/jenkins/downstream/poll_email.py --server imap.gmail.com --guid 18f2 --timeout 40 --filter 'has completed'
Traceback (most recent call last):
File "./tests/jenkins/downstream/poll_email.py", line 120, in <module>
args.timeout))
File "./tests/jenkins/downstream/poll_email.py", line 78, in wait_email
M.select('INBOX')
File "/usr/lib64/python2.7/imaplib.py", line 662, in select
typ, dat = self._simple_command(name, mailbox)
File "/usr/lib64/python2.7/imaplib.py", line 1083, in _simple_command
return self._command_complete(name, self._command(name, *args))
File "/usr/lib64/python2.7/imaplib.py", line 910, in _command_complete
typ, data = self._get_tagged_response(tag)
File "/usr/lib64/python2.7/imaplib.py", line 1012, in …
```
=> poll_email.py: Deal with Socket errors

ansible/configs/amq-messaging-foundations/software.yml
SUMMARY
When try to provisioning the environment the agnosticv is expecting amq-messaging-foundations role. Since the role it's not matching the environment is not being provisioned.
ISSUE TYPE
COMPONENT NAME
amq-messaging-foundations
=> fixing role name.

ansible/roles/ocp4-workload-migration/defaults/main.yml, ansible/roles/ocp4-workload-migration/tasks/workload.yml, ansible/roles/ocp4-workload-migration/templates/mig_storage.yml.j2
Recently, we observed in one of our lab environments that the AWS ELB DNS names took longer time to propagate than expected which caused our workload to break since it relied on using load balancer service URL to connect to MCG storage. This PR uses the default Route exported by MCG for the same Service eliminating the need to rely on AWS DNS names to propagate. 
```paste below
```
=> Change workload ocp4-workload-migration to use default MCG Route instead of Service endpoint

ansible/configs/amq-messaging-foundations/software.yml
SUMMARY
When try to provisioning the environment the agnosticv is expecting an existing role. Since the role it's not matching the environment is not being provisioned.
ISSUE TYPE
COMPONENT NAME
amq-messaging-foundations
=> updating the role to ocp-client-vm

ansible/roles_ocp_workloads/ocp4_workload_serverless/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml
OpenShift Serverless 1.10+ does no longer create a Route to download the kn CLI tool. It uses the "ConsoleCLIDownload" custom resource instead. This PR checks if this CR exists and if so uses it. Otherwise it looks for the route. And if that doesn't exist either the kn tool is not installed.
=> Updates for Serverless 1.10+ (and ConsoleCLIDownload CRs)

ansible/roles_studentvm/studentvm_user/tasks/main.yml
Reformatting by @ritesh97-rh broke the logic.
TASK [studentvm_user : Generate user password if not defined] ******************
Wednesday 28 October 2020  16:00:59 -0400 (0:00:00.187)       0:07:34.887 *****
fatal: [studentvm.6bc2.internal]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'password'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unrecognized value after key=value parameters given to password lookup"}
studentvm_user
=> Fix syntax error introduced by reformatting

ansible/configs/ocp4-cluster/default_vars_osp.yml
The use_dynamic_dns variable was set in every AgnosticV config. But it wasn't defined in ocp4-cluster. This fixes that so that the AgnosticV configs can be cleaned up.
ocp4-cluster
=> Add variable in defaults rather than every AgnosticV config

ansible/roles/ocp4-workload-openbanking-sandbox/tasks/3amp-deploy-full-api.yml
Fixes #3147.
Role: ocp4-workload-openbanking-sandbox
After some search I found this issue #3147 might be related to a characteristic behaviour of some builtin modules when Split_Lines=True by default. In this case, found no option to disable this mode on `slurp` ansible module.
I've tested this update on full role execution against a regular OCP 4.5 workshop (small) cluster from RHPDS.
```paste below
$ ansible --version
ansible 2.9.14
config file = /home/rmarins/Workspaces/agnosticd/ansible.cfg
configured module search path = ['/home/rmarins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.8/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.8.6 (default, Sep 25 2020, …
```
=> Fixes #3147 processing content read on remote host fails - OCP4 Open Banking role 

ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/files/console_operator.yaml, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/files/oauth_cluster.yaml, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/files/providers.html, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/templates/config_map_console_custom_logo.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/templates/console_link.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/templates/login.html.j2, ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/templates/secret_login_page.yaml.j2, login.html
As part of the OpenShift Web Console customization contest I wrote this workload to change the login page, logo and any Console Links in the OpenShift Web Console.
Defaults make it look like the labs.opentlc.com provisioning portal, add help links for partners and Red Hatters.
More docs here: https://github.com/wkulhanek/openshift-web-console-customizations
ocp4_workload_opentlc_webconsole
=> Add workload to customize the OpenShift Web Console

ansible/cloud_providers/azure_infrastructure_deployment.yml, ansible/cloud_providers/gcp_infrastructure_deployment.yml, ansible/configs/aro/pre_software.yml, ansible/configs/ocp4-cluster/default_vars_azure.yml, ansible/configs/ocp4-cluster/files/cloud_providers/azure_cloud_template.j2, ansible/configs/ocp4-cluster/post_infra.yml, ansible/roles-infra/infra-azure-ssh-key/a, ansible/roles-infra/infra-azure-ssh-key/defaults/main.yml, ansible/roles-infra/infra-azure-ssh-key/tasks/main.yml, ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml
Included:
- Azure CLI no longer needs to add an extension for ARO. The extension was phased out when it went from Beta to GA.
- Fixing up some Ansible depreciated code in the same playbooks
- Cleaning up how keyvaults are used to remove a bottleneck
- Updating ocp4-cluster to allow zero windows VMs or up to 4. There is no reason to allow more for demo purposes.
config/ocp4-cluster (keyvault changes + roles-infra/azure*ssh*)
cloud-provider/gcp (ansible depreciation)
cloud-provider/azure (ansible + aro extension fix + allowing zero windows VMs with a limit of 4)
Just about two months worth of little edits that need to get tested and tagged
=> Update: Accumulated Azure bugs

ansible/roles/ocp-workload-migration/defaults/main.yml, ansible/roles/ocp-workload-migration/tasks/download-content.yml, ansible/roles/ocp-workload-migration/tasks/pre_workload.yml, ansible/roles/ocp4-workload-migration/defaults/main.yml, ansible/roles/ocp4-workload-migration/tasks/download-content.yml, ansible/roles/ocp4-workload-migration/tasks/workload.yml
This PR adds ability to download lab content on the bastion hosts. The content is hosted in official repo maintained by migration engineering. The content includes a bunch of YML files and bash scripts. Size of the content is a few megabytes.
```paste below
```
=> Update migration workloads to add ability to download lab content on the bastion hosts

ansible/roles-infra/infra-ec2-template-generate/defaults/main.yml, ansible/roles-infra/infra-ec2-template-generate/templates/cloud_template.j2
This PR implements functionality for `ocp4-cluster` to match the `ocp4-workshop` flag `use_root_zone`. This is a feature we need for GPTE infrastructure clusters in order to shorten the DNS domain names.
This also makes some whitespace formatting changes to the jinja2 template to make control flow statements easier to see and visually match by moving the opening bracket `{%` to the beginning of the line.
Role infra-ec2-template-generate
Test deploys with ocp4-cluster performed both with and without this flag to confirm new functionality and that this feature does not break anything.
=> Change role infra-ec2-template-generate to add aws_dns_create_public_zone

ansible/roles/ocp-workload-migration/tasks/workload.yml, ansible/roles/ocp-workload-migration/templates/cr.yml.j2, ansible/roles/ocp-workload-migration/templates/crd.yml.j2, ansible/roles/ocp4-workload-migration/tasks/workload.yml, ansible/roles/ocp4-workload-migration/templates/crd.yml.j2
This PR updates migration workloads to prepare for a demo migration scenario of CRDs.
```paste below
```
=> Update migration workloads to create demo CRDs

ansible/roles/ocp-workload-migration/tasks/workload.yml
Fixes a small syntax error introduced by another PR. 
```paste below
```
=> Fix ocp-workload-migration syntax error

ansible/roles/ocp4-workload-ccnrd/tasks/pre_workload.yml
Update ocp-worksload-ccnrd to fix a wrong console url
```paste below
```
=> Update ocp-worksload-ccnrd to fix a wrong console url

ansible/roles/ocp4-workload-ccnrd/files/elasticsearch_subscription.yaml, ansible/roles/ocp4-workload-ccnrd/files/osm_subscription.yaml
Update ocp4-workload-ccnrd to fix openshift-operators-redhat namespace and servicemesh operator
```paste below
```
=> Update ocp4-workload-ccnrd to fix openshift-operators-redhat namespace

ansible/roles/ocp4-workload-ccnrd/files/elasticsearch_subscription.yaml
Update ocp4-workload-ccnrd to update the elasticsearch operator version 4.6. It's working with 4.5 in naked OCP 4.6 but it doesn't in ccnrd cluster based on ocp 4.6 so I updated to 4.6 by default.
```paste below
```
=> Update ocp4-workload-ccnrd to update the elasticsearch operator version

docs/Contributing.adoc
All destroy playbooks must be idem-potent.
OPS should be able to run a destroy playbook several times, until it succeeds.
=> Update Contributing.adoc: add idem-potent rule

ansible/roles_ocp_workloads/ocp4_workload_dso/files/sonarqube-persistent-template.yml, ansible/roles_ocp_workloads/ocp4_workload_dso/files/sonarqube-template.yml, ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/sonarqube.yml
The ocp4_workload_dso role was pulling in a template to install sonarqube from github. The template was updated recently resulting in  a deployment failure of sonarqube (see the error log).  Updated the role so that the templates are included in the role, decoupling them from the upstream templates.
Error log:
```
ASK [ocp4_workload_dso : set sonardb cpu and mem] *****************************
Friday 06 November 2020  13:07:05 -0500 (0:00:00.046)       1:21:23.713 *******
fatal: [bastion.89c0.internal]: FAILED! => {"changed": true, "cmd": "oc --config=/root/.kube/config --server=https://api.cluster-
89c0.89c0.example.opentlc.com:6443 --insecure-skip-tls-verify=true set resources dc/sonardb --limits=cpu=400m,memory=1Gi - …
```
=> Fix sonarqube deployment in OCP4 security lab

ansible/roles/ocp4-workload-ausgeben-infra/.yamllint, ansible/roles/ocp4-workload-ausgeben-infra/defaults/main.yml, ansible/roles/ocp4-workload-ausgeben-infra/tasks/workload.yml
=> yamllint formatting cleanup for role ocp4-workload-ausgeben-infra

ansible/roles/ocp4-workload-debugging-workshop/tasks/post_workload.yml
=> Increase the number of retries while waiting for 'istio-sidecar-injector' service to be ready

ansible/configs/ansible-windows/.yamllint, ansible/configs/ansible-windows/post_software.yml
Fix ansible-windows config yamllint failures. This config is currently failing and causing problems with other items in checks.
Extend yamllint line length to 200 characters.
config ansible-windows
=> Fix config ansible-windows for yamllint

ansible/configs/sap-hana/default_vars.yml
S/4HANA host is coming twice due to an issue with a missing variable
sap-hana
=> Fix s4hana duplicate host for OSP deployments

ansible/action_plugins/agnosticd_user_info.py, ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/workload.yml
Added support for Shared Cluster CodeReady Workspaces access to shared cluster access workload.
This only prints out the URL of the CRW installation in the cluster.
Also fix agnosticd_user_info's body function.
agnosticd_user_info.py
ocp4_workload_shared_cluster_access
=> Add crw to shared env

ansible/roles/ocp-workload-aiedge-computing-blueprint/.yamllint, ansible/roles/ocp-workload-aiedge-computing-blueprint/defaults/main.yml, ansible/roles/ocp-workload-aiedge-computing-blueprint/readme.adoc, ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/main.yml, ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/post_workload.yml, ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/pre_workload.yml, ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/remove_workload.yml, ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/workload.yml, ansible/roles/ocp-workload-aiedge-computing-blueprint/templates/github-push.task.yaml.j2
DEV Role to deploy the Red Hat Edge Computing blueprint
https://github.com/redhat-edge-computing
Add an agnosticd role to deploy the [Red Hat Edge Computing](https://github.com/redhat-edge-computing) blueprint. This is the last role that will be applied in a OCP4 workload after the deployment of Red Hat Advanced Cluster Management and Gitea
ocp-workload-aiedge-computing-blueprint
This will be called in the agnosticv config OCP4_ACM_AIEDGE_COMPUTING and is the initial PR to start DEV testing of this agnosticv config before submitting it for final PROD testing
=> Add Red Hat Edge Computing role

ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
This change takes the GUID subdomain out of OSP hostnames.  From my understanding dynamic DNS no longer creates a GUID subdomain.  Hostnames should be host-GUID.dynamic.opentlc.com NOT host-GUID.GUID.dynamic.opentlc.com.
infra-osp-create-inventory
=> Take the GUID subdomain out of OSP hostnames

ansible/configs/ocp4-disconnected-osp-lab/default_vars.yml, ansible/configs/ocp4-disconnected-osp-lab/software.yml
The OpenStack HA Config needed an update to run on the Orange (and Pink etc.) OpenStack clusters.
I also took the opportunity to update the bastion and utilityvms to RHEL 8.2 and Satellite.
Nameservers had to be set to override the ones coming from OpenStack to get acceptable performance.
Validated that the solver still works (except for registry PVC at the end which is no longer necessary).
=> Update OCP 4 HA Lab Config for RHEL 8.2 and dynamic dns

ansible/roles/set-repositories/tasks/pre_checks_rhn.yml, ansible/roles/set-repositories/tasks/rhn-repos.yml
When registering a system to rhn directly we could not specify which systems were RHEL 7 or RHEL 8. This change preserves the original function of the role, but adds the option to exclusively define rhel_repos_el7 or rhel_repos_el8 in the case that a developer requires two systems running different major versions of RHEL.
role, set-repositories
Example use:
rhel_repos:
- not defined, is exclusive to _el7 and _el8, preserving original functionality
rhel_repos_el7:
- rhel-7-server-rpms
- rhel-7-server-rh-common-rpms
- rhel-7-server-extras-rpms
rhel_repos_el8:                           
- rhel-8-for-x86_64-baseos-rpms
- rhel-8-for-x86_64-appstream-rpms
```paste below
```
=> set-repositories role update

ansible/configs/satellite-vm/default_vars_osp.yml
Remove variables `osp_cluster_dns_zone` and `osp_cluster_dns_server` from `default_vars_osp.yaml`
config/satellite-vm
=> Fix default OSP variables

ansible/configs/ansible-tower/tower_workloads.yml
Use become `true` for processing `ansible_tower_node_workloads` in ansible-tower config.
Config ansible-tower
=> Change config ansible-tower to use become for node workloads

ansible/configs/osp-satellite-vm/post_infra.yml
* Fix domain name
* Import role `infra-osp-wait_for_linux_hosts` for satellite servers
`config/osp-satellite-vm`
=> Fix osp-satellite-vm user info

ansible/roles/tower-settings-update/tasks/main.yml
Fix role tower-settings-update to function when `tower_setting_params` has only one key in the dictionary.
The `dict` lookup by default does not return a list when the dictionary has only one entry. The `dict2items` filter is a cleaner approach and does not have this issue.
Role tower-settings-update
=> Fix role tower-settings-update to handle dict with one key

ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/pre_workload.yml
Expose internal registry for core cluster.
Without this patch the `Retrieve registry route` task on line 43 fails because the registry route is not exposed by default.
Fixes merged [PR 3071](https://github.com/redhat-cop/agnosticd/pull/3071/files)
=> Expose internal registry for core cluster

tools/bump_version.sh
Apparently it happens that users using this script pass the 'prod'
twice.
Add a check to prevent that.
=> bump_version: Add a check to prevent double 'prod'

ansible/action_plugins/agnosticd_user_info.py
When testing ocp_workloads independently (like on an existing OCP cluster, from localhost), the user_info script will fail if the output_dir does not exist.
This PR adds basic directory check and creation to the script. This does not change behaviour in a full deployment when the directory has already been created, but prevents failing on workload test.
Added line example:
`os.makedirs(os.path.dirname(os.path.join(output_dir, 'user-info.yaml')), exist_ok=True)`
=> Change action_plugin user_info: create output_dir if not existent

ansible/action_plugins/agnosticd_user_info.py
Fix output_dir creation in agnosticd_user_info for python2. The recent merge to create output dir used the `exist_ok` flag which only works in Python3.
agnosticd_user_info
=> Fix agnosticd_user_info make output_dir for python2

ansible/roles/ocp-workload-migration/templates/operator.yml.j2, ansible/roles/ocp4-workload-migration/templates/mig-operator-subscription-downstream.yml.j2
This PR updates the SHAs for MTC operator deployment in OpenShift 3 migration workload to use v1.3.2
Also updates the subscription of MTC operator in OpenShift 4 workload and pins down to v1.3.2 
```paste below
```
=> Update migration workloads to use MTC v1.3.2

ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/infrastructure.yml
The role `ocp4_workload_dso` uses the `oc patch` command to update the cluster image config, but sometimes the cluster image config API may be unavailable due to components restarting. This PR add retries to this task to make it more robust.
=> Change role ocp4_workload_dso to add retries to cluster image config

ansible/configs/kni-osp/files/requirements_k8s.txt, ansible/configs/ocp4-cluster/files/requirements_k8s.txt, ansible/configs/ocp4-workshop/files/requirements_k8s.txt, ansible/configs/ocs4-external-implementation/files/requirements_k8s.txt, ansible/configs/sap-integration/files/requirements_k8s.txt, ansible/roles/ocp-workload-migration/files/requirements.txt
Remove reference to k8s python module in requirements which are causing virtualenvs to fail pip.
Config kni-osp
Config ocp4-workshop
Config ocs4-external-implementation
Config sap-integration
Role ocp-workload-migration
=> Remove k8s library from python requirements

ansible/roles/bastion-lite/tasks/main.yml, ansible/roles/bastion/tasks/main.yml
The condition to run FTL is currently too loose.
Fix it and use only the boolean `install_ftl`
=> Fix FTL condition that is too loose

ansible/roles/ocp4-workload-dil-streaming/tasks/pre_workload.yml, ansible/roles/ocp4-workload-dil-streaming/tasks/provision_che.yaml, ansible/roles/ocp4-workload-dil-streaming/tasks/provision_crw.yaml, ansible/roles/ocp4-workload-dil-streaming/tasks/single_cluster.yaml
Fix setting rout_subdomain in ocp4-workload-dil-streaming.
The role did not specify `api_version` when attempting to fetch the ingress configuration, resulting in getting a result from the wrong api group.
Role ocp4-workload-dil-streaming
=> Fix role ocp4-workload-dil-streaming route_subdomain var

ansible/roles/ocp4-workload-camelk-crw/tasks/pre_workload.yml, ansible/roles/ocp4-workload-debezium-demo/tasks/pre_workload.yml, ansible/roles/ocp4-workload-debugging-workshop/tasks/pre_workload.yml, ansible/roles/ocp4-workload-iot-managed/tasks/provision_che.yaml, ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/workload.yml, ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin-student/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_workshop_user/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/workload.yml
Fix multiple roles where the OpenShift cluster ingress config was fetched without specifying `api_group`, resulting in unpredictable behavior.
Across multiple roles this PR will:
- Add `api_version` if missing
- Add `name: cluster` if missing
- Switch from `k8s_facts` to `k8s_info`
- Add `failed_when` condition to fail on fetching the the resource rather than fail on the subsequent `set_fact` task.
Roles:
- ocp4-workload-camelk-crw
- ocp4-workload-debezium-demo
- ocp4-workload-debugging-workshop
- ocp4-workload-iot-managed
- ocp4-workload-rhte-analytics_data_ocp_workshop
- ocp4-workload-workshop-dashboard-cluster-admin-student
- ocp4_workload_dso
- ocp4_workload_quarkus_workshop_user
- ocp4_workload_quarkus_workshop_user
=> Fix multiple roles fetching Ingress without api_group

ansible/roles-infra/infra_osp_bastion_on_openshift_network/.yamllint, ansible/roles-infra/infra_osp_bastion_on_openshift_network/README.adoc, ansible/roles-infra/infra_osp_bastion_on_openshift_network/defaults/main.yaml, ansible/roles-infra/infra_osp_bastion_on_openshift_network/meta/main.yml, ansible/roles-infra/infra_osp_bastion_on_openshift_network/tasks/add-bastion-to-openstack-network.yml, ansible/roles-infra/infra_osp_bastion_on_openshift_network/tasks/main.yml, ansible/roles-infra/infra_osp_bastion_on_openshift_network/vars/main.yml
Add role infra_osp_bastion_on_openshift_network to add bastion to OpenShift node network.
Role infra_osp_bastion_on_openshift_network
=> Add role infra_osp_bastion_on_openshift_network

ansible/roles/host-lets-encrypt-certs-certbot/defaults/main.yml, ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml
Fix role hosts-lets-encrypt-certs-certbot virtualenv setup to use `pip` module with `python -m venv` command so that it functions without the dependence on /usr/local/bin/virtualenv
Role hosts-lets-encrypt-certs-certbot
=> Fix role host-lets-encrypt-certs-certbot virtualenv setup

ansible/roles/host_virtualenv/tasks/main.yml
Add installation on `virtualenv` python library system-wide to the `host_virtualenv` module for backwards compatibility.
Role host_virtualenv.
=> Add host_virtualenv install virtualenv system-wide

ansible/configs/three-tier-app/default_vars_ec2.yml
Existing labs expect external ssh access to nodes app1, app2, appdb1
Ansible Advanced Homework lab is breaking on this issue
Re-attaches the correct Security Group to allow this
=> Fixes three-tier-app to externally expose ssh TCP/22 on app and appdb

ansible/configs/sap-integration/default_vars_ec2.yml, ansible/configs/sap-integration/default_vars_osp.yml, ansible/configs/sap-integration/sap_software.yml
Add variable used to mount extra device, OpenStack 13 and AWS use device `/dev/xvX` and in OpenStack 16 use `/dev/sdX`
config/sap-integration
=> Add variable extra_device - sap-integration

ansible/configs/sap-rhvh/default_vars.yml, ansible/configs/sap-rhvh/pre_software.yml
Add variable used to mount extra device, OpenStack 13 and AWS use device `/dev/xvX` and in OpenStack 16 use `/dev/sdX`
Default values
`rhvm_data_device: vdc`
`rhvm_image_device: vdb`
`bastion_extra_device: vdb`
config/sap-integration
=> Update device names sap-rhvh

ansible/roles/ocp4-workload-debezium-demo/templates/scc-anyuid.yaml.j2
- Create a new scc for each project to handle independently
- Add `sys_chroot` as it was removed in OCP 4.6 for community containers (Elasticsearch)
ocp4-workload-debezium-demo
aka Change Data Capture with debezium
```paste below
```
=> create scc for each project and add sys_chroot

ansible/roles-infra/infra-ec2-template-generate/defaults/main.yml
Add support for AWS Region Bahrain (me-south-1)
- infra-ec2-template-generate
We are looking to add support for the me-south-1 region. Note that the `RHEL81NBDE` image doesn't appear to be available and returned `None` so I left that one out. Other than that one AMI, I was able to get the rest of the images using `tools/find_ami.sh`
Also, I added a DNS mapping for `me-south-1.compute.internal`
=> Add support for AWS region me-south-1

ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/files/deploy_certs.sh, ansible/roles/ocp4-workload-idm/files/deploy_certs.sh, ansible/roles_ocp_workloads/ocp4_workload_le_certificates/templates/deploy_certs.sh.j2
Without the "login" shell flag, `-l` bash does not initialize the shell environment which causes problems for ansible execution from cron. This PR adds this flag to the shebang `#!` line of teh deploy_certs.sh in the three roles in which it is used.
Roles:
- ocp4-workload-enable-lets-encrypt-certificates
- ocp4-workload-idm
- ocp4_workload_le_certificates
=> Add bash shell init flag to deploy_certs.sh

ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/defaults/main.yml
This lab was broken since long time, we aligned it to latest content from [learn.openshift.com](https://learn.openshift.com/middleware/pipelines) and update it to OCP 4.6 and Pipelines 1.2.x
ocp4-workload-homeroomlab-tekton-pipelines
**ATTENTION**
Before merging it, we need to fix a permission issue from RHPDS side:
https://github.com/openshift-labs/lab-tekton-pipelines/pull/79#issuecomment-749681286
```paste below
```
=> Fix role ocp4-workload-homeroomlab-tekton-pipelines: update lab to OCP 4.6 and Pipelines 1.2.x

ansible/action_plugins/agnosticd_user_info.py
Change agnosticd_user_info to print data to log as currently occurs for `msg` and `body`.
agnosticd_user_info
Example output:
```
TASK [agnosticd_user_info] *******************************************************************************************************************************************************************************************************************
Thursday 07 January 2021  11:19:32 -0600 (0:00:00.041)       0:00:00.041 ****** 
ok: [localhost] => {
"changed": false,
"data": {
"testkey": "val"
}
}
```
=> Change agnosticd_user_info to always print data to log

ansible/configs/sandbox/default_vars.yml, ansible/configs/sandbox/pre_infra.yml
Small change to fix an incorrect default var. `student_name` is provided by CloudForms and this was incorrectly expecting `user`.
sandbox config
=> Update sandbox config with student_name

ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/per_user.yml
Change workload ocp4-workload-homeroomlab-starter-guides remove cluster-monitoring-view for users
ocp4-workload-homeroomlab-starter-guides 
```paste below
```
=> Change workload ocp4-workload-homeroomlab-starter-guides remove cluster-monitoring-view for users

ansible/roles/host-ocp4-installer/.yamllint, ansible/roles/host-ocp4-installer/create-manifests.yml, ansible/roles/host-ocp4-installer/tasks/install_installer.yml, ansible/roles/host-ocp4-installer/tasks/main.yml, ansible/roles/host-ocp4-installer/tasks/osp_pre.yml, ansible/roles/host-ocp4-installer/tasks/print_cluster_info.yml
- Add retry OpenShift install on failed waiting for Kubernetes API.
- Also add yamllint and cleanup.
- Remove non-functional OpenStack host restart.
- Remove retry wait for bootstrap complete as I could find no evidence of this succeeding in the logs after initial failure, but many cases where it simply made the failure take longer to be reported.
Role host-ocp4-install
=> Change role host-ocp4-install to implement retry

docs/Operator_Catalog_Snapshots.adoc
In OCP 4.6 the way OpenShift Operator Snapshot images need to be created changed. This PR adds documentation for 4.6 an later.
=> Added instructions for Operator Index snapshots for 4.6+

ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/defaults/main.yml, ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/per_user.yml, ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/pre_workload.yml, ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/workload.yml
ocp4-workload-homeroomlab-tekton-pipelines
```paste below
```
=> Fix workload ocp4-workload-homeroomlab-tekton-pipelines remove serviceaccount and use ocp users

ansible/roles_ocp_workloads/ocp4_workload_nexus_operator/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_nexus_operator/tasks/workload.yml
Add retries to k8s tasks for ocp4_workload_nexus_operator to make the workload more robust for intermittent api connectivity issues.
Also remove unnecessary `./templates/` prefix for template lookup.
Role ocp4_workload_nexus_operator
=> Add retries for k8s tasks to ocp4_workload_nexus_operator

ansible/configs/sap-hana/software.yml
The last changes in OSP have caused SAP software not to deploy due to DNS issues. This will manually add every host address entry on HANA and S4HANA servers
sap-hana
=> Add entries on both HANA and S4HANA hosts to workaround OSP DNS issues

ansible/configs/ans-tower-ops-demo/env_vars.yml, ansible/configs/ans-tower-ops-demo/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/ansible-integrations/env_vars.yml, ansible/configs/ansible-integrations/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/ansible-windows/env_vars.yml, ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
All Windows based configs appeared to break and non AgnosticD teams saw the same.
Windows AMIs use cloud-init/userdata to pull in a github based winrm activation powershell script.
This fix updates the Windows AMIs, and forces the powershell script download to use TLS 1.2
- Bug Fix Pull Request
./configs/ansible-integrations/env_vars.yml
./configs/ansible-windows/env_vars.yml
./configs/ans-tower-ops-demo/env_vars.yml
=> Fix windows powershell remoting issue caused, we think, by github TLS 1.2

ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/README.adoc, ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/templates/operatorgroup.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_couchbase_cluster/templates/subscription.yml.j2
This role deploys the Couchbase cluster operator on an OpenShift Workshop. This is part of an effort to add RHPDS Catalog entries for our Partners, and provide the ability to perform demos and workshops.
ocp4_workload_couchbase_cluster
The workshop guide for users will be published on demo.openshift.com.
After running yamllint I received these results:
```
defaults/main.yml
meta/main.yml
tasks/main.yml
tasks/post_workload.yml
tasks/pre_workload.yml
tasks/remove_workload.yml
tasks/workload.yml
templates/operatorgroup.yml.j2
templates/subscription.yml.j2
```
```
ansible 2.10.4
config file = None
configured module search path = ['/Users/philliplamb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = …
```
=> Add role ocp4_workload_couchbase_cluster

ansible/roles/host-ocp4-installer/tasks/main.yml, ansible/roles/host-ocp4-installer/tasks/osp_pre.yml
Add loop_control label to tasks in host-ocp4-installer to make the logs easier to read...
Currently it is puking stuff like this to the logs:
```
TASK [host-ocp4-installer : Add additional metadata to instances] **************
Thursday 14 January 2021  14:01:05 -0500 (0:00:27.251)       0:41:47.090 ******
skipping: [bastion] => (item={u'vm_state': u'active', u'OS-EXT-STS:task_state': None, u'addresses': {u'cluster-02ce-8t5j5-openshift': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:3b:c9:da', u'version': 4, u'addr': u'10.0.1.75', u'OS-EXT-IPS:type': u'fixed'}]}, u'image': {u'id': u'f136604f-a1a8-4a51-ab2f-e9c45fb99547'}, u'OS-EXT-SRV-ATTR:user_data': None, u'OS-EXT-SRV-ATTR:root_device_name': None, u'OS-SRV-USG:launched_at': u'2021-01-14T18:43:39.000000', u'flavor': {u'vcpus': 4, u'disk': 30, …
```
=> Add loop labels in host-ocp4-installer

ansible/roles/ocp-workload-3scale-demo/tasks/config.yml, ansible/roles/ocp-workload-3scale-demo/tasks/post_workload.yml, ansible/roles/ocp-workload-3scale-demo/tasks/workload.yml
Update to use RH SSO operator instead of the template, fixes the problem with the live and readiness probes.
3scale security demo with OIDC
```paste below
```
=> Update ocp-workload-3scale-demo to use rh-sso operator

ansible/roles_ocp_workloads/ocp4_workload_cyberark_dap/tasks/workload.yml
Stray `>-` introduced in earlier commit.
Role ocp4_workload_cyberark_dap
=> Fix ocp4_workload_cyberark_dap command with stray yaml quote marker

ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/workload.yml
Fixes issue where creation of tekton PipelineRun fails due to the openshift-pipeline operator still initializing the required endpoints. This adds a simple retry for each PipelineRun creation
ocp-workload-aiedge-computing-blueprint
Fix is in response to this failure
```
Internal error occurred: failed calling webhook \"webhook.pipeline.tekton.dev\": Post https://tekton-pipelines-webhook.openshift-pipelines.svc:443/defaulting?timeout=30s: no endpoints available for service \"tekton-pipelines-webhook\""
```
=> Fix AI Edge workshop failure when creating PipelineRun

ansible/configs/rhel-custom-security-content/data/Dockerfiles/test_suite-rhel8
We have to use a specific version of UBI because we use the repo configured in the HOST to install new packages into the built UBI image. in this case the repo configured is RHEL8.1, otherwise it there is package conflicts.
```paste below
```
=> Use fixed version (8.1) of UBI image so it's compatible with RHEL8.1 repo

ansible/roles/ocp4-workload-dil-streaming/templates/datagrid-operatorgroup.yaml.j2, ansible/roles/ocp4-workload-dil-streaming/templates/datagrid-subscription.yaml.j2
Fix role ocp4-workload-dil-streaming use of `item` variable in favor of `__user`.
Role ocp4-workload-dil-streaming
=> Fix role ocp4-workload-dil-streaming loop var usage

ansible/configs/sap-smart/default_vars.yml, ansible/configs/sap-smart/sat_workload.yml
The sap-smart config has been relying on a satellite manifest file being present on the host from which it is depolyed. This PR changes this logic to instead download a vault protected file from a public url.
=> Change sap-smart config to use download with vault for satellite manifest

ansible/configs/sap-smart/software.yml
The https://github.com/redhat-cop/infra-ansible.git role fails when setting up EPEL access because of GPG signature validation failure. This adds the key to the host's RPM config so this will not fail.
config sap-smart
=> Add install RPM-GPG-KEY-EPEL-7 to sap-smart config

ansible/configs/sap-smart/software.yml
Change sap-smart config RPM-GPG-KEY-EPEL-7 to RPM-GPG-KEY-EPEL-8. It was the RHEL8 key that is needed, not RHEL7.
config sap-smart
=> Change sap-smart RPM-GPG-KEY-EPEL-7 to RPM-GPG-KEY-EPEL-8

ansible/roles/host-ocp4-installer/defaults/main.yml, ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2, tests/static/syntax-check.sh
There is sometimes a need to deploy an OpenShift cluster in FIPS mode. This change will allow that to happen by setting the `ocp4_fips_enable` variable to true.
=> Update ocp4-installer to allow FIPS mode

ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
The `ocp4_fips_enable` template was not using the ansible `| bool` filter which is likely to cause the string `"true"` or `"false"` to be set in the generated yaml when values are passed by command line.
Compare:
```
$ ansible localhost -e ocp4_fips_enable=false -m debug -a "msg='fips: {{ ocp4_fips_enable | to_json }}'"
Friday 05 February 2021  20:56:11 -0600 (0:00:00.059)       0:00:00.059 ******* 
localhost | SUCCESS => {
"msg": "fips: \"false\""
}
```
To
```
$ ansible localhost -e ocp4_fips_enable=false -m debug -a "msg='fips: {{ ocp4_fips_enable | bool | to_json }}'"
Friday 05 February 2021  20:57:53 -0600 (0:00:00.058)       0:00:00.058 ******* 
localhost | SUCCESS => {
"msg": "fips: false"
}
```
Role host-ocp4-installer
=> Fix role host-ocp4-installer to use bool filter for ocp4_fips_enable

ansible/configs/ansible-windows/Makefile, ansible/configs/ansible-windows/env_vars.yml
Config ansible-windows had wide open UDP security group and a deployment was subject to an attack on UDP/LDAP
This PR cleans up the config and tightens up the SGs to reduce the attack surface including the port in question 389/udp
config ansible-windows
=> Tighten up security groups for ansible-windows after UDP LDAP attack

ansible/roles_studentvm/studentvm_java_development/.yamllint, ansible/roles_studentvm/studentvm_java_development/defaults/main.yml, ansible/roles_studentvm/studentvm_java_development/tasks/main.yml
Add capability to install the Mandrel (GraalVM) distribution (required for updated App Deploy ILT).
Also made installing the JDK optional.
studentvm_roles / studentvm_java_development
=> Update Java StudentVM workload to optionally install Mandrel

ansible/configs/ocp4-cluster/default_vars_ec2.yml
- change to c5d (better perf)
- the sizing depends on number of workers. xlarge is generally enough,
but can be a problem if the number of workers is high.
=> ocp4-cluster Improve instance type of master

ansible/configs/smart-management-foundations/default_vars_osp.yml
Update the satellite image name for ibm-cloud naming
```paste below
```
=> Update smart-management-foundations satellite image

ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/workload.yml
Update the role `ocp-workload-aiedge-computing-blueprint` to use the ACM PlacementRule & Subscription that selects clusters based on assigned label and not ManagedClusterConditionAvailable state.  This resolves an issue where ACM subscription objects would trigger a delete action when the ACM Hub and Managed clusters were woken up out of order OR experienced a break/delay in communication.
ocp-workload-aiedge-computing-blueprint
=> Update role ocp-workload-aiedge-computing-blueprint ACM PlacementRule and Subscription

training/02_Getting_Started/06_deploying_a_base_config_osp.adoc, training/03_Infrastructure/02_Advanced/Adding_Versions_RHEL.adoc
add information to use and configure own AK when no Sat server is available
06_deploying_a_base_config_osp.adoc
```
=> add information to use and configure own AK when no Sat server is available - agd training

training/02_Getting_Started/06_deploying_a_base_config_osp.adoc, training/03_Infrastructure/02_Advanced/Adding_Versions_RHEL.adoc
add information to use and configure own AK when no Sat server is available
training/03_Infrastructure/02_Advanced/Adding_Versions_RHEL.adoc
=> add information to use and configure own AK when no Sat server is available

ansible/configs/ocp4-cluster/default_vars_ec2.yml, ansible/roles/host-ocp4-installer/defaults/main.yml, ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Allow user to specify the desired IOPS for master storage.
In case of large clusters the master instance should have provisioned
IOPS for the etcd database to work properly.
This change, if applied, automatically sets the
`controlPlane.platform.aws.rootVolume.type` to `io1` if the number of
workers is greater than 10.
In that case, the IOPS value is also calculated:
* minimum of 2000 IOPS,
* if number of wokers > 20, then it's 100 IOPS per node
* maximum of 32000 IOPS
That IOPS value can be overridden by the user with the `master_storage_iops` variable, directly in the config or agnosticv.
According to OpenShift documentation
https://docs.openshift.com/container-platform/4.6/installing/installing_aws/installing-aws-customizations.html
* type = io1 / 2000 IOPS  is a good setting for large …
=> ocp4-cluster config: IOPS setting for master storage

ansible/configs/smart-management-foundations/pre_infra.yml, ansible/configs/smart-management-foundations/pre_software.yml
1: Renamed ceph_cluster_color to ceph_cluster - For better synchronization with osp-migration config and to get updated.
2: Moved infra-local-create-ssh_key role to pre_software.yml as it was always been there. It also helps in troubleshoot if all configs are prepared in same way.
Config: smart-management-foundation
=> updated variables and tasks

ansible/configs/ansible-multitier-rhel8/post_software.yml
Due to invalid entry book bag is not working
Definitive RHEL 8 on AWS
=> Fix for Bookbag

ansible/roles/ocp-workload-migration/templates/operator.yml.j2, ansible/roles/ocp4-workload-migration/templates/mig-operator-subscription-downstream.yml.j2
This PR is pulling in the updates to the MTC versions for the workshop roles. 
Fixes #3429  .
- Update role template Pull Request
Updating the required templates within the following roles:
- ocp-workload-migration
- ocp4-workload-migration
=> Bumping up the versions of MTC in OCP Migration workshop to 1.4

ansible/roles/ocp4_workload_ai_ml_workflows_demo/templates/workshop-singleuser-profile.yml.j2
Increased Pod Sizing for JupyterHub. 
This means users can run the lab or demo without shutting down notebooks.
=> updated jh pod sizing

ansible/configs/ocp4-cluster/lifecycle_hook_post_start.yml, ansible/roles/ocp4_approve_certificate_signing_requests/README.adoc, ansible/roles/ocp4_approve_certificate_signing_requests/defaults/main.yml, ansible/roles/ocp4_approve_certificate_signing_requests/meta/main.yaml, ansible/roles/ocp4_approve_certificate_signing_requests/tasks/approve-certificate-signing-requests.yml, ansible/roles/ocp4_approve_certificate_signing_requests/tasks/main.yml
Add role ocp4_approve_certificate_signing_requests to implement retry loop to wait for CertificateSigningRequests and approve them. Use new role in ocp4-cluster start lifecycle hook.
Role ocp4_approve_certificate_signing_requests
=> Add role ocp4_approve_certificate_signing_requests

ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
Fix router name determination in additional fip logic.
Role infra-osp-template-generate
=> Fix role infra-osp-template-generate router name determination

ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
Fix `depends_on` clause in heat template to use name of first network with a router.
Role nfra-osp-template-generate
=> Fix role infra-osp-template-generate additional fip depends_on clause

ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/job-image-pull.j2
There was an issue where the image used to pull the Windows containers was failing.
```
$ oc get pods -n openshift-windows-machine-config-operator
NAME                                               READY   STATUS    RESTARTS   AGE
winc-ssh-6ddf8c6cbb-gd87n                          1/1     Running   0          179m
windows-image-pull-9bp5g                           0/1     Error     0          179m
windows-image-pull-dpb5b                           0/1     Error     0          176m
windows-image-pull-hmlwt                           0/1     Error     0          178m
windows-image-pull-jc9lj                           0/1     Error     0          178m
windows-image-pull-ljkkt                           0/1     Error     0          178m
windows-image-pull-shtlk                           0/1 …
```
=> Updated image used for pulling image

ansible/roles/host-ocp4-destroy/defaults/main.yml, ansible/roles/host-ocp4-destroy/tasks/main.yml, ansible/roles/host-ocp4-destroy/tasks/remove-osp-external-network.yml, ansible/roles/host-ocp4-installer/defaults/main.yml, ansible/roles/host-ocp4-installer/tasks/configure-osp-external-network-for-install.yml, ansible/roles/host-ocp4-installer/tasks/main.yml, ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Add feature to use Ansible to manage the external network setup for the host-ocp4-installer role. This allows avoiding using a floating IP address for the bootstrap node and so provides a work-around for our current issues with OpenStack floating ips assigned to separate subnets.
Roles host-ocp4-installer & host-ocp4-destroy
=> Add ocp4_ansible_managed_osp_external_network to host-ocp4-installer

ansible/roles/host-ocp4-destroy/tasks/main.yml, ansible/roles/host-ocp4-installer/defaults/main.yml, ansible/roles/host-ocp4-installer/tasks/main.yml
This new feature was supposed to default to disabled. Fix default value in host-ocp4-installer
Role host-ocp4-installer
=> Set default ocp4_ansible_managed_osp_external_network to false

ansible/roles/ocp-workload-3scale-demo/tasks/config.yml
add more retries for sso pod to start
the SSO Pod showing not enough time to start so the deployment fails. Upped the retries from 15 to 30x
```paste below
```
=> add more retries for sso pod to start

ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/windows-ms.j2
Updated size of Windows Node to be the same as the Linux node: m5a.4xlarge
This is to support the .NET application sample that will be coming in the next few weeks. The current size is too small for the application being deployed.
Windows machine set
This PR just updates the size of the machineset used.
=> Updated size on Windows node

ansible/roles_ocp_workloads/ocp4_workload_cyberark_dap/defaults/main.yml
The version for ocp4_workload_cyberark_dap was mismatched between 1.0.6 and 1.0.7 in two variables. This consolidates the version to one variable.
Role ocp4_workload_cyberark_dap
=> Fix version mismatch in role ocp4_workload_cyberark_dap

ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
StudentVM kept failing because the binary in the Tekton archive changed from `tkn` to `tkn-linux-amd64`. Fixed by creating a link from `tkn-linux-amd64` to `tkn`.
studentvm_ocp4
=> Fix failing tkn bash completion by createing a link

ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
add become: true for link tkn task
Deployments was failing with this:
TASK [ocp4_workload_pipelines : Link tkn-linux-amd64 to tkn] *******************
Wednesday 10 March 2021  13:01:58 -0500 (0:00:05.409)       0:51:26.828 *******
fatal: [bastion.raleigh-5d3e.internal]: FAILED! => {"changed": false, "msg": "Error while linking: [Errno 13] Permission denied: b'/usr/bin/tkn-linux-amd64' -> b'/usr/bin/tkn'", "path": "/usr/bin/tkn"}
add become: true for link tkn task
```paste below
```
=> add become: true for link tkn task

ansible/roles-infra/infra-osp-project-create/tasks/main.yml
fixing the bug on OSP sanboxes where it was not generating the OSP public subnet variable due to the when conditional set to look for a newly created project.
roles-infra/infra-osp-project-create/tasks/main.yml
=> Fixe glitch on sandboxes - CI AgD training

ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml, ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
tkn executable changed back to just `tkn`... removing the link step again.
studentvm_ocp4
=> Revert / fix tkn executable name

ansible/configs/sap-integration/custom_workloads.yml
Deployment is failing while creating Channels as the CRD does not exist. Adding retry option to the play to give it enough option for the CRD to be created.
=> Retry channels set up while serverless is coming ready

ansible/configs/aro/.yamllint, ansible/configs/aro/post_software.yml
OpenShift 4.6 removed the mongodb-persistent template from the OpenShift namespace, this breaks a widely used lab called ARO Workshop which is used in both the Red Hat and Microsoft fields.
This fix readds that template to hold us over until ARO Workshop can be updated to use more modern practices like operators.
post_software.yaml in aro config
Also updates the OpenShift client used from from 4.3 to version 4.6.
=> Update ansible / configs / aro

ansible/roles/ocp4-workload-dil-streaming/tasks/approves_installplan.yaml
Fixes a timeout problem with large clusters where creating an Install Plan takes too long.
DIL streaming
```paste below
```
=> change installplan timeout

ansible/roles_studentvm/studentvm_ocp4/defaults/main.yml, ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
The role studentvm_ocp4 current fails if the user name is not set. A reasonable default is to use `student_name` if available and otherwise fall back to `ansible_user`.
Role studentvm_ocp4
=> Add reasonable default for studentvm_ocp4_user_name

ansible/roles_ocp_workloads/ocp4_workload_dm7_foundations_elt/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_dm7_foundations_elt/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_dm7_foundations_elt/templates/clusterresourcequota.j2
role: roles_ocp_workloads/ocp4_workload_dm7_foundations_elt
clusterresourcequota deployment fails when ocp_user has underscore in its name.
Fix: replace '_' with '-' in clusterresourcequota name.
```paste below
```
=> ocp4_workload_dm7_foundations_elt: clusterresourcequota name cannot contain underscore

ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_dm7_exp_elt/templates/clusterresourcequota.j2
role:roles_ocp_workloads/ocp4_workload_dm7_exp_elt
clusterresourcequota deployment fails when ocp_user has underscore in its value.
Fix: replace '_' with '-' in clusterresourcequota name.
=> ocp4_workload_dm7_exp_elt: clusterresourcequota name cannot contain underscore

ansible/roles/set-repositories/tasks/satellite-repos.yml
I am using ansible-multitier-infra as the basis for a new config.  When `repo_method: satellite` and `use_content_view: false`, the role `set-repositories` runs `satellite-repos.yml`.  The  task `Enable repos for RHEL` only verifies that repos that are not in the `rhel_repos` variable are enabled.  The EPEL 8 repo is still enabled, even though it's not my `rhel_repos` and causes issues with dependencies on several packages
Adding a task to `satellite-repos.yml` to purge all repos before applying the `rhel_repos` list resolves this as only defined repos will be used.
satellite-repos.yml
variables used: 
```
__image: rhel-server-7.8
use_content_view: false
rhel_repos:
- rhel-7-server-rpms
- rhel-7-server-rh-common-rpms
- rhel-7-server-extras-rpms
- …
```
=> Fix role set-repositories not removing existing repos before enabling repos from rhel_repos variable

ansible/roles_ocp_workloads/ocp4_workload_stackrox_central/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_stackrox_sensor/tasks/workload.yml
Increasing the retries to wait for ready replicas. Should not be a problem, but this just adds some more buffer since we ran into a few issues.
ocp4_workload_stackrox_central
ocp4_workload_stackrox_sensor
=> Update roles stackrox for increase retries

ansible/roles/bastion/tasks/main.yml, ansible/roles/bastion/templates/bash_profile.j2
Replace "hostname" logic in .bashrc with just a {{ guid }}. Fixes issue #3548 
FYI: @prakhar1985 (OpenShift environments have mostly switched to bastion-lite instead of bastion - guess that's why nobody noticed until now.
Role: bastion
=> Fix missing GUID. Closes #3548

ansible/configs/ansible-advanced-v2/files/bind9-Dockerfile
Docker ubi-init image version locked.
bind9-Dockerfile
=> Docker Image version locked

ansible/action_plugins/agnosticd_user_info.py
Update agnosticd_user_info to accept a list for `msg` to match usage of `debug`. Ex:
```
- name: output workshop info guides
agnosticd_user_info:
msg:
- ""
- "URL for attendees to get a username assigned to them and links to labs:"
- "http://get-a-username-labs-infra.{{ route_subdomain }}"
- "You should share this URL (or a shortlink for it) -- It is all they will need to get started!"
- ""
- "get-a-username's admin page is https://get-a-username-labs-infra.{{ route_subdomain }}/admin"
- "Admin login with admin/{{workshop_openshift_user_password}}"```
```
agnosticd_user_info
=> Accept list msg for agnosticd_user_info

ansible/roles/ocp4-workload-ccnrd-cuttingedge/templates/devfile.json.j2
…ccnrd-cuttingedge role
Fix ocp4-workload-ccnrd-cuttingedge to update links for ccnrd-cuttingedge role
```paste below
```
=> Fix ocp4-workload-ccnrd-cuttingedge to update links

ansible/configs/sap-smart/sat_workload.yml
Use katello-service to restart Satellite services
sap-smart
=> Fix Satellite services restart

ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/workload.yml
Trying to install helm as `ec2-user` caused issues. The deployer now just installs `helm` in the `ec2-user`'s local directory
helm
=> updated helm install to local directory

ansible/action_plugins/agnosticd_odcr.py, ansible/action_plugins/test_agnosticd_odcr.py, ansible/cloud_providers/ec2_destroy_env.yml, ansible/cloud_providers/ec2_infrastructure_deployment.yml, ansible/configs/just-a-bunch-of-nodes/default_vars_ec2.yml, ansible/configs/just-a-bunch-of-nodes/sample_vars.yml, ansible/roles-infra/infra-aws-capacity-reservation/defaults/main.yaml, ansible/roles-infra/infra-aws-capacity-reservation/lookup_plugins/agnosticd_aws_create_capacity_reservations.py, ansible/roles-infra/infra-aws-capacity-reservation/readme.adoc, ansible/roles-infra/infra-aws-capacity-reservation/tasks/create.yaml, ansible/roles-infra/infra-aws-capacity-reservation/tasks/destroy.yaml, ansible/roles-infra/infra-aws-capacity-reservation/tasks/main.yaml, ansible/roles-infra/infra-aws-capacity-reservation/tasks/pre_checks.yaml, ansible/roles-infra/infra-ec2-template-destroy/tasks/ec2_detect_region_tasks.yml, tools/builds/Dockerfile-aws
Implement on-demand capacity reservations in agnosticd.
A certain % of our provisions are failing because of *InstanceInsufficientCapacity* error in AWS.
This change implements the creation of capacity reservations as described here:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-capacity-reservations.html
In a nutshell, if ODCR is wanted and supported by the config:
1. role  determines the AZs with matching instance-type offerings
2. role creates the capacity reservations
3. if it fails, move to next AZ
4. if it fails again, move to next region
Input vars and output Vars are described in the readme of the role.
- ansible/action_plugins/agnosticd_odcr.py 
- ansible/roles-infra/infra-aws-capacity-reservation
To heavily test that feature the following setting …
=> implement AWS on-demand capacity reservation (ODCR)

ansible/configs/ocp4-disconnected-osp-lab/default_vars.yml
remove ftl from ocp4-disconnected-osp-lab due to python module conflicts
```paste below
```
=> remove ftl due to python module conflicts

ansible/configs/sap-integration/files/k8s/serverless_knativeeventing.j2
Camel-K Operator 1.3.2 is introducing behaviour that is causing an issue on the SAP serverless integration. This will solve the issue.
=> Fix issue caused by 1.3.2 Camel K operator

ansible/roles-infra/infra-ec2-template-generate/templates/cloud_template.j2
This adds the option to enable a new set of credentials to the default CFN template. This can be used when there is a need for an environment provisioned in a sandbox account to interact directly with an AWS service.
infra-ec2-template-generate
=> Add student user option to default CFN template

ansible/roles/ocp4-workload-migration/tasks/post_workload.yml
Created files in the user directory are owned by root, and not the lab user. 
That makes it difficult to work with. 
Added student user ownership at copy time
role, ocp4_workload_migration, post workload scritps.
=> Adding ownership change on file copy to student

ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/aws_credentials.yml
`loop` did not get indented properly when the tasks were copied to the new file.
=> Update ACM Workload with format fix

ansible/configs/sap-integration/files/k8s/kamelet_slack_source.j2
Slack is complaining about API rate limits when running multiple instances of the lab. This will prevent that
=> Add parameters for Slack binding to avoid rate limits

ansible/roles/ocp4-workload-migration/tasks/post_workload.yml
The variables were relying on old vars from ocp4-workshop.
We moved to ocp4-cluster, and the variables are different. 
ocp4-workload-migration role
=> Updating vars to reflect new ones in ocp4-cluster

ansible/roles/ocp4-workload-migration/tasks/workload.yml, ansible/roles/ocp4-workload-migration/templates/mig-operator-subscription-downstream.yml.j2
Updated MTC to 1.4.2
In the  new MTC  we are trying to approve the plan but the OLM is also adding some status fields to the same install plan and changing the observedGeneration of the object. 
We need to try and retry.
role: ocp4-workload-migration
=> Mtc version bump and approval check

ansible/roles/ocp4-workload-migration/tasks/workload.yml
The loop has to go over the whole block, repeating just the last task was a mistake
role, ocp4-workload-migration
=> Move the loop to block, not the Approve task

ansible/configs/ocp4-cluster/lifecycle_hook_post_start.yml
When the cloud provider is different than ec2, the inventory is not built, and the CSR are not approved resulting in a broken cluster.
This change, if applied, add includes to build the inventory for OSP and Azure so the certificates are all approved there too.
- ocp4-cluster config
=> Fix config ocp4-cluster, lifecycle start hook: add all missing cloud providers

ansible/roles/install_operator/defaults/main.yml, ansible/roles/install_operator/meta/main.yml, ansible/roles/install_operator/tasks/install.yml, ansible/roles/install_operator/tasks/main.yml, ansible/roles/install_operator/tasks/remove.yml, ansible/roles/install_operator/templates/catalogsource.j2, ansible/roles/install_operator/templates/installplan.j2, ansible/roles/install_operator/templates/subscription.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml
Added a generic role, *install_operator* that installs an Operator into an OpenShift Cluster. It supports all the usual features like manual approval or using a catalog source.
Also added a workload, *ocp4_workload_openshift_gitops* using that generic role as a first example. Workloads will be updated to use the generic role as they are being updated periodically.
@thoraxe FYI.
```paste below
```
=> Add generic operator install role

ansible/roles/ocp-workload-migration/files/requirements.txt
Something has changed with google authenticator package which is getting included in venv.
It now requires a lower version of rsa to be able to install venv properly, compared to what we had in requirements.txt. 
role, ocp4-workload-migration
=> Fixing pip requirements for venv.

ansible/roles-infra/sandbox-ibm/tasks/create_roks_access_groups.yml, ansible/roles-infra/sandbox-ibm/tasks/create_roks_policies.yml
To enable RHOIC (formerly ROKS), there was a missing access policy. This change will create that additional policy. It will be deleted as part of the cleanup.
sanbox-ibm
=> Update IBM sandbox workload with new access policies

ansible/roles/ocp4-workload-migration/tasks/download-content.yml
the new env_type does not have a package installed by default (sshpass)
role: ocp4-workload-migration
=> Add sshpass

ansible/configs/pntae-vilt-bastion/default_vars.yml, ansible/configs/pntae-vilt-bastion/default_vars_osp.yml
config pntae-vilt-bastion needs port 443 access on bastion
```paste below
```
=> pntae-vilt-bastion: new security group to enable https port 443

ansible/roles-infra/infra-aws-sandbox/tasks/main.yml
When cleaning up the sandbox, also recreated the keypair if needed.
=> aws sandbox: Make sure keypair is always created

ansible/configs/ocp4-workshop/files/requirements_k8s.txt
Fix k8s virtualenv definition for ocp4-workshop by bumping version of google-auth module.
Config ocp4-workshop
=> Bump google-auth in k8s virtualenv for ocp4-workshop

ansible/configs/sandbox/default_vars_ec2.yml, ansible/configs/sandbox/ec2_destroy_env.yml, ansible/configs/sandbox/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/sandbox/post_infra.yml, ansible/configs/sandbox/post_infra_ec2.yml, ansible/configs/sandbox/post_software.yml, ansible/configs/sandbox/post_software_ec2.yml, ansible/configs/sandbox/post_software_ibm.yml, ansible/configs/sandbox/pre_infra.yml, ansible/configs/sandbox/pre_infra_ec2.yml, ansible/configs/sandbox/pre_infra_ibm.yml, ansible/configs/sandbox/pre_software.yml
This commit, if applied, adds a new feature to the 'sandbox' config to
enable access to the AWS Web console to students.
- introduce new boolean variable sandbox_enable_console_access (default: true)
- Remove useless tasks in ec2_destroy_env.yml
- Enable LoginProfile for the student user in the cloudformation template
- use include_tasks to dynamically load either ibm  or ec2 tasks:
when provisioning for ec2, we don't want to display IBM tasks and vice versa.
- Display access in user.info
- sandbox config
=> Update config sandbox: enable web console access for AWS sandbox

ansible/configs/ibm-rhoic/destroy_env.yml
Occasionally the token we are using times out before the final API call is made, this gets a new token immediately before calling that API so that timeout will never happen.
configs/ibm-rhoic
If IBM Cloud is slow on removing its OpenShift cluster then the token doesn't get used before its timeout.
=> Update config ibm-rhoic

ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
Replace `command:` with `shell:` to set up completion for `tkn` in pipelines workload. Somehow command doesn't pass the parameters correctly in that instance.
=> Fix tkn completion setup

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
Gitea 1.14 changed the way admin users are created. Added logic to support both Gitea 1.13 and 1.14.
Also disallowing `latest` tag.
Fixed a few issues when using a name for the Gitea instance that's not "gitea".
=> Some fixes for Gitea 1.14 (and giteas not named 'gitea')

ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
Recent changes in ocp4-cluster post_software require the `shortname` to be set on the bastion server. OSP did not have that set. This PR fixes that.
infra-osp-create-inventory
=> Add 'shortname' to OSP inventory

ansible/roles/ocp4-workload-migration/defaults/main.yml, ansible/roles/ocp4-workload-migration/files/cluster-admins-group.clusterrolebinding.yaml, ansible/roles/ocp4-workload-migration/tasks/workload.yml, ansible/roles/ocp4-workload-migration/templates/cluster-admins.group.yaml.j2
Add cluster-admins group setup fro ocp4-workload-migration role.
The cluster-admins group is required for RHOCS:
https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.5/html/managing_openshift_container_storage/multicloud-object-gateway_rhocs
Role ocp4-workload-migration
=> Add cluster-admins group for ocp4-workload-migration

docs/First_OSP_Env_walkthrough.adoc
- service to use has changed
- the format was borked within the instructions to install Python modules
- few more cosmetic changes
docs/First_OSP_Env_walkthrough.adoc
n/a
=> Fix some glitches in the first OSP walkthrough documentation

ansible/roles-infra/sandbox-ibm/tasks/create_access.yml, ansible/roles-infra/sandbox-ibm/tasks/create_roks_access_groups.yml, ansible/roles-infra/sandbox-ibm/tasks/create_roks_policies.yml, ansible/roles-infra/sandbox-ibm/tasks/create_roks_ui_access.yml, ansible/roles-infra/sandbox-ibm/tasks/remove_access.yml, ansible/roles-infra/sandbox-ibm/tasks/remove_roks_access.yml, ansible/roles-infra/sandbox-ibm/tasks/remove_roks_access_groups.yml, ansible/roles-infra/sandbox-ibm/tasks/remove_roks_ui_access_groups.yml, ansible/roles-infra/sandbox-ibm/tasks/remove_ui_access.yml
The IBM Cloud APIs timeout more than we can tolerate. This adds retries to all of the API calls to avoid failures due to brief failures of the API.
sandbox-ibm
=> Update sanbox-ibm role with timeout retries

ansible/configs/sandbox/pre_infra_ec2.yml
remove double quotes from AWS IAM password
sandbox
```paste below
```
=> remove double quotes from AWS IAM password

ansible/roles/ocp-workload-aiedge-computing-blueprint/defaults/main.yml, ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/workload.yml
Fix role `ocp-workload-aiedge-computing-blueprint` to approve operator installs that require manual approval & use ACM cluster labels to manage the install of ArgoCD operator and application on managed clusters
* Add check for any operator installs that require manual approval
* Use ACM cluster labels to control the install of ArgoCD on specific clusters
* Use ACM subscriptions to managed the creation of MANUela factory+line
ArgoCD applications
* Add manuela-factory-subs/channel to the list of replaced git repo
* Use placeholder test for the edge cluster domain
ROLE: `ocp-workload-aiedge-computing-blueprint`
N/A
=> Fix role ocp-workload-aiedge-computing-blueprint

ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/workload.yml
Fix incorrect role var reference in role ocp-workload-aiedge-computing-blueprint. 
Role: ocp-workload-aiedge-computing-blueprint
Please merge when approved
=> Fix AIEdge blueprint role var reference

ansible/configs/ibm-rhoic/destroy_env.yml, ansible/configs/ibm-rhoic/destroy_rhoic_cluster.yml, ansible/configs/ibm-rhoic/infra.yml, ansible/configs/ibm-rhoic/software.yml
The current destroy process is failing when a RHOIC cluster doesn't actually exist. This will change the process to pull a whole list of existing RHOIC clusters and delete it if it exists. The current process looks for a specific cluster and fails when it doesn't find it.
Also, line spacing.
ibm-rhoic
=> Update IBM RHOIC config destroy process

ansible/action_plugins/agnosticd_odcr.py
fix the following error:
```
TASK [infra-aws-capacity-reservation : Create on-demand capacity reservations and save result] ***
Monday 10 May 2021  04:36:44 -0400 (0:00:00.109)       0:00:12.494 ************
[ERROR]: ClientError(u'An error occurred (InvalidParameterValue) when calling
the CreateCapacityReservation operation: The specified EndDate has already
passed. Specify an EndDate in the future.',)
fatal: [localhost]: FAILED! => {"changed": false, "error": "Client Error while creating reservation."}
```
- agnosticd_odcr.py
tested with python2 and python3
=> ODCR: fix EndDate TZ, use UTC

ansible/configs/ocp4-cluster/files/requirements_k8s.txt
Add lxml to k8s virtualenv required by 3scale demo workload, which uses the `xml` ansible module.
=> Add lxml python lib to ocp4-cluster k8s virtualenv

ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/tasks/gitea_setup_repo.yml
Playbook tried to set owner/group as root:root - which is a) not allowed and b) should not be necessary. Removing.
=> Remove root owner from script

ansible/configs/kni-osp/post_infra.yml, ansible/configs/ocp4-cluster/destroy_env_osp.yml, ansible/configs/ocp4-disconnected-osp-lab/destroy_env.yml, ansible/configs/ocs4-external-implementation/destroy_env_osp.yml, ansible/configs/osp-migration/dns_loop.yml, ansible/configs/osp-satellite-vm/dns_loop.yml, ansible/configs/sap-integration/destroy_env_osp.yml, ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml, ansible/roles/ocp-infra-osp-fip/tasks/main.yml
This change, if applied, fixes all 'nsupdate' invocations and makes sure the IP
address is used, not the dns name.
This change fixes the following error that happens with some recent versions of ansible:
> dns.exception.SyntaxError: Text input is malformed.
Co-authored-by: Eric L <ericzolf@users.noreply.github.com>
I tested the following playbook with:
```yaml
- hosts: localhost
gather_facts: false
tasks:
- debug:
msg: "{{ myvar | ipaddr | ternary(myvar, lookup('dig', myvar)) }}"
vars:
myvar: ddns01.opentlc.com
- debug:
msg: "{{ myvar | ipaddr | ternary(myvar, lookup('dig', myvar)) }}"
vars:
myvar: 169.45.246.132
```
* ansible 2.11
* ansible 2.9
* ansible 2.7
* openstack-ansible-2.9 virtualenv
* ansible system on admin host
* aws-ansible-2.9 virtualenv
=> Fix nsupdate 'server' param, always pass IP

ansible/configs/sandbox/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/sandbox/pre_infra_ec2.yml
Use ansible default chars for the generation of passwords:
> By default generated passwords contain a random mix of upper and lowercase ASCII letters, the numbers 0-9 and punctuation (". , : - _").
Plus adds a number at the end to pass AWS password policy:
> Password should meet 1 more of the following requirements: Password should have at least one number, Password should have at least one symbol
=> Fix password generation in sandbox open env

ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
Remove broken task which attempts to setup bash completion for istioctl. The logic in the task is not how istioctl bash completion functions and produces the error:
```
$ ./istioctl completion bash
Error: unknown command "completion" for "istioctl"
Run 'istioctl --help' for usage.
```
A future feature PR could implement bash completion for istioctl following documentation here:
https://istio.io/latest/docs/ops/diagnostic-tools/istioctl/#enabling-auto-completion
Role studentvm_ocp4
=> Remove broken bash completion task for istioctl in role studentvm_ocp4

ansible/configs/rhel-custom-security-content/default_vars.yml
The instance property `flavor` needs to be a dict rather than a simple string.
Config rhel-custom-security-content
=> Fix default vars for rhel-custom-security-content

ansible/cloud_providers/.yamllint, ansible/cloud_providers/ec2_destroy_env.yml, ansible/cloud_providers/ibm_infrastructure_deployment.yml, ansible/cloud_providers/osp_destroy_env.yml, ansible/cloud_providers/test_infrastructure_deployment.yml
We had a situation with a previous commit where someone updated a file in cloud_providers which broke the syntax and caused other things in DEV to fail. This change will ensure that at least the syntax is correct in cloud_providers before merging is allowed.
ansible/cloud_providers
This is the change that happened to azure_infrastructure which I want to avoid in the future
https://github.com/redhat-cop/agnosticd/commit/b91cd0f571b31093061d83570528f4af013eb448#diff-e68e040cbbe52d399e9f255a9e8896dd3d73c745b3a54285f3c88287837717b1
=> Adding yamllint to ansible/cloud_providers

ansible/configs/sandbox/post_software_ec2.yml
Add warning to not check AWS credentials into GIT
sandbox
```paste below
```
=> Add warning to not check AWS credentials into GIT

ansible/roles/set-repositories/tasks/satellite-repos.yml
Remove cert bootstrap for Satellite HA
```paste below
```
=> Remove cert bootstrap for Satellite HA

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/files/workaround_clusterrole.yaml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/templates/workaround_clusterrolebinding.yaml.j2
Red Hat GitOps Operator has a bug preventing regular users from using ArgoCD. This PR installs the workaround as outlined in  https://access.redhat.com/solutions/6012601
=> Workaround for GitOps Operator bug

ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/homeroom.yaml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/install_elasticsearch_operator.yaml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/install_jaeger_operator.yaml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/install_kiali_operator.yaml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/install_servicemesh_operator.yaml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/per_user_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/catalogsource.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/elasticsearch_installplan.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/elasticsearch_subscription.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/jaeger_installplan.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/jaeger_subscription.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/kiali_installplan.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/kiali_subscription.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/netpol.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/rbac.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/rhsso_installplan.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/rhsso_operator.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/servicemesh_controlplane.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/servicemesh_installplan.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/servicemesh_memberroll.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/servicemesh_subscription.j2
Adds an agnosticd OCP4 workload role that deploys the RedHatGov OpenShift Service Mesh Workshop
This is agnosticd OCP4 workload role that deploys RedHatGov's OSM workshop.  The workshop content is delivered via homeroom (https://github.com/RedHatGov/service-mesh-workshop-dashboard), and the code used by the workshop participants is here (https://github.com/RedHatGov/service-mesh-workshop-code).  After adding this role, we will file a ticket to add this workshop to RHPDS.
The `ocp4_workload_servicemesh_workshop` role was tested on an RHPDS OpenShift 4.7 Cluster.
=> Add role ocp4_workload_servicemesh_workshop

ansible/roles/ocp4-workload-dil-streaming/tasks/post_workload.yml, ansible/roles/ocp4-workload-dil-streaming/tasks/provision_user_registration.yaml, ansible/roles/ocp4-workload-dil-streaming/templates/user_registration.yaml.j2
Add randomly generated password for registration and app and add the information to the final email sent.
fixes https://github.com/RedHat-Middleware-Workshops/dayinthelife-streaming/issues/84
ocp4-workload-dil-streaming
```paste below
```
=> create a random pass for reg and add to mail

ansible/roles_ocp_workloads/ocp4_workload_fuse_online/tasks/workload.yml
Noelia mentioned there is an intermittent error with catalog item _Fuse Foundations Part 1 - Fuse Online_. The error occurs during deployment of AMQ broker.
I added more retries during the broker deployment process.
ocp4_workload_fuse_online
=> Update - Fuse Foundations Part 1 - Fuse Online - Provisioning Failure Data

ansible/roles_ocp_workloads/ocp4_workload_fuse_online/templates/image-pull-secret.j2
The `ocp4_pull_secret` was found to contain a dictionary rather than the
expected json string of the pull secret. This cause encoding problems.
Role ocp4_workload_fuse_online
=> Change role ocp4_workload_fuse_online to use ocp4_token

ansible/roles/set-repositories/tasks/satellite-repos.yml
Enable RHSM to manage repositories
RHEL 8.4 in AWS seems to have manage repositories disabled in RHSM config.  This will help make sure subscription manager has repo management enabled.
=> Enable RHSM to manage repositories

ansible/roles-infra/infra-osp-project-create/defaults/main.yaml, ansible/roles-infra/infra-osp-project-create/tasks/main.yml, ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2, ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_master.j2, ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_nested.j2
When deploying to OpenStack, the router external IP address floating IP addresses are created on the provider network specified by the user via `provider_network`. If the provider network has more than one subnet, the logic is to pick the one with the least used IP addresses. This is done with `openstack ip availability` but it lookups a hard coded `external` network. This pull request replaces it with the `provider_network`.
And some clusters have a policy that forbids to specify the subnet when creating a router or floating IP. The pull request adds a boolean variable named `osp_find_public_subnet` that will enable lookup when set to true. Its default value is `true` to be backward compatible with the current behavior.
roles-infra/infra-osp-project-create …
=> Add ability to not lookup public subnet for OpenStack provider

ansible/roles/ocp4_workload_stackrox_demo_pipeline/templates/config/2-rox-deployment-check-task.yml.j2, ansible/roles/ocp4_workload_stackrox_demo_pipeline/templates/config/2-rox-image-check-task.yml.j2, ansible/roles/ocp4_workload_stackrox_demo_pipeline/templates/config/2-rox-image-scan-task.yml.j2
This fixes two display issues with the Pipelines output in the OCP4/ACS demo.
roles/ocp4_workload_stackrox_demo_pipeline
The changes here are only in the templates used to create ClusterTasks in Pipelines.  There's no change in the Ansible role itself.  Tested functionality against a "OpenShift 4.7 Workshop (Training)" RHPDS cluster.
=> Fix role ocp4_workload_stackrox_demo_pipeline resolve display issues in Pipelines output

ansible/roles/tower-license-injector/README.md, ansible/roles/tower-license-injector/defaults/main.yml, ansible/roles/tower-license-injector/tasks/license.yml, ansible/roles/tower-license-injector/tasks/main.yml, ansible/roles/tower-license-injector/tasks/man_content.yml, ansible/roles/tower-license-injector/tasks/man_file.yml, ansible/roles/tower-license-injector/tasks/man_url.yml, ansible/roles/tower-license-injector/tasks/manifest.yml, ansible/roles/tower-license-injector/vars/main.yml
Manifest can be loaded as URL, file or base64-variable
roles/tower-license-injector
The code works with Tower 3.8 and the collection awx.awx version 19.2.0
=> Add manifest feature to the tower-license-injector role

ansible/cloud_providers/ec2_pre_checks.yml, ansible/roles-infra/infra-ec2-template-generate/tasks/locate_availability_zones.yml, ansible/roles-infra/infra-ec2-template-generate/tasks/locate_availability_zones_tasks.yml
I added a few `check_mode: false` to some command tasks checking for information, allowing the provisioning to work a bit longer in check mode without modifying anything in the environment.
cloud_providers
roles-infra/infra-ec2-template-generate
The main.yml playbook still can't run fully in check mode and will probably never run through, but it helps to check quickly if some configuration is completely awry.
=> Add a few check_mode:false to allow for the --check mode a bit longer

ansible/roles/set-repositories/defaults/main.yaml, ansible/roles/set-repositories/tasks/main.yml, ansible/roles/set-repositories/tasks/satellite-repos.yml
Two changes:
1. replace 3 include/when statements with one include <variable> statement, it removes a few useless skips and keeps the code simpler
2. add a pool option to the role to allow for custom product registration (in case the AK doesn't make it)
roles/set-repositories
n/a
=> Simplify include code and add Satellite pool to set-repositories

ansible/roles/ocp-workload-migration/templates/operator.yml.j2, ansible/roles/ocp4-workload-migration/templates/mig-operator-subscription-downstream.yml.j2
Updating the OCP3 and OCP4 versions of MTC tooling to the newest GA. 
=> Update OCP4 MTC to 1.4.5

ansible/configs/osp-migration/pull_repo.yml
Added debug task to display the private repo and tag used in the osp-migration config
=> Display private repo and tag for osp-migration configs

ansible/configs/osp-migration/pull_repo.yml
This is related to https://github.com/redhat-cop/agnosticd/pull/3894. With this commit deployment always expecting a tag whereas all DEV developments don’t have a tag as it always use master branch of novello-template repo. This PR is intened to fix that. It will display what tag is selected. IF no tag is selected by default it will select master in next TASK namely **Download the templates from the private repository**. So I added same condition here
- 
All Novello deployment affected.
=> Deployment should go good with novello tag on DEV config.

ansible/configs/aro/post_software.yml
We introduced this task to add the template in ARO 4.6 to ease the transition as OpenShift dropped it in 4.6. Now that OpenShift 4.8 is about to be released and ARO is now on 4.7, it doesn't work anymore and causes the deploy to fail on the last step.
config/aro
N/A
=> UPDATE: config/aro

ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/templates/data-engineering-kfdef.yaml.j2
Updates `ocp4-workload-rhte-analytics_data_ocp_workshop` KfDef to pull kustomize components from ODH manifests v1.0.10.
`ocp4-workload-rhte-analytics_data_ocp_workshop`
=> ocp4-workload-rhte-analytics_data_ocp_workshop: Set kfdef to use ODH manifests v1.0.10

ansible/roles/deploy_automationcontroller/README.md
Simple, but important, doc fix as group names had the wrong prefix in role `deploy_automationcontroller`
role `deploy_automationcontroller`
=> Minor typo fix for group names in role deploy_automationcontroller

ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/workload.yml
Fix an incorrect route in the get-a-username task that would send the user to a bad jupyter notebook route
ocp4-workload-rhte-analytics_data_ocp_workshop
=> ODH Data Engineering: Fix url for get-a-username notebook route

ansible/roles_ocp_workloads/ocp4_workload_open_data_hub_olm/defaults/main.yml
FIX: Update ODH OLM role to use catalog snapshot v4.7_2021_07_01 since older snapshots are referencing image hashes that no longer exist
roles_ocp_workloads/ocp4_workload_open_data_hub_olm
=> ODH Data Engineering: Update catalog snapshot for ODH OLM role

ansible/roles/host-ocp4-installer/tasks/install_installer.yml, ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
This PR adds support to the host-ocp4-installer role to support the latest stable release for an OpenShift major version.
ocp4_installer_version=4.7 -> Install latest stable 4.7 release (4.7.18 right now)
ocp4_installer_version=4.7.16 -> Install specific release 4.7.16
@fridim @jkupferer @klewis0928 @NonyNo3lle  FYI.
=> Add support for latest stable OCP release

ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_prometheus/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_prometheus/tasks/workload.yml
SUMMARY:
Fixing the Prometheus Operator. The operator doesn't finish the installation in several occasions. It does happens from time to time (around 3-4 users). 
Cause:
It's preventing the Adv. CND catalog to be created. 
Tested multiple times in a local environment and same issue. At some point it fails in early stages of users setup.
Making the catalog source name fixed is avoiding this issue and have all the namespaces per 20 users with the operators created.
ISSUE TYPE
COMPONENT NAME
=> Operator is not finishing the installation - changing the catalog source name.

ansible/roles-infra/infra-aws-sandbox/tasks/manual_cleanup.yml
Until https://github.com/rebuy-de/aws-nuke/issues/660  is fixed upstream
in aws-nuke, manually cleanup all the S3 Access Points
=> AWS Sandbox cleanup of S3 Access points

ansible/cloud_providers/ec2_destroy_env.yml, ansible/cloud_providers/ec2_infrastructure_deployment.yml, ansible/configs/ocp4-ha-lab/default_vars.yml, ansible/configs/ocp4-ha-lab/destroy_env.yml, ansible/roles-infra/infra-aws-open-environment/defaults/main.yaml, ansible/roles-infra/infra-aws-open-environment/tasks/create_resources.yaml, ansible/roles-infra/infra-aws-open-environment/tasks/destroy_resources.yaml, ansible/roles-infra/infra-aws-open-environment/tasks/main.yaml, ansible/roles-infra/infra-aws-open-environment/tasks/print_user_info.yaml, ansible/roles-infra/infra-aws-open-environment/templates/open-environment.yaml.j2, ansible/roles-infra/infra-cloud-tags/defaults/main.yaml, ansible/roles-infra/infra-cloud-tags/tasks/main.yaml, ansible/roles-infra/infra-ec2-template-create/tasks/main.yml
This change, if applied, adds a new role to AgnosticD to
enable or disable Open Environment full access for any catalog item.
The variable is the boolean `agnosticd_open_environment`.
If `true`, the role `infra-aws-open-environment` is executed during the infra step.
It creates an admin user with programmatic and Web Console access.
It then prints the credentials to the user as user.info.
Also:
- create an infra-cloud-tags role to define in one place the
default cloud tags and reuse them in several other roles or configs.
- infra-aws-open-environment role
- ec2 cloud-provider
=> Implement Open Environment checkbox feature (AWS)

ansible/roles_ocp_workloads/ocp4_workload_cnd_monitoring_prometheus/tasks/workload.yml
SUMMARY:
Fixing the Prometheus Operator. The operator doesn't finish the installation in several occasions. It does happens from time to time (around 8 users).
Cause:
It's preventing the Adv. CND catalog to be created.
Tested multiple times in a local environment and same issue. At some point it fails in early stages of users setup.
Removing the label once create for the namespace +  removing the prefix for the catalog source, since we don't need it.
ISSUE TYPE
COMPONENT NAME
=> removing labels and prefix- Prometheus Operator

ansible/roles_ocp_workloads/ocp4_workload_cyberark_dap/tasks/workload.yml
Extremely rare network timeouts happen when getting file to unarchive, this will work around them.
roles_ocp_workloads/ocp4_workload_cyberark_dap
N/A
=> UPDATE:  roles_ocp_workloads/ocp4_workload_cyberark_dap

ansible/configs/ocp4-workshop/software.yml
Few of the CI's were affected due to this python 2.7 end of support. Hence updating this awscli bundle to pickup the available one.
Example error we are receiving:
```
TASK [Install awscli] **********************************************************
Friday 16 July 2021  03:58:13 -0400 (0:00:03.152)       0:08:32.655 *********** 
fatal: [clientvm.tst-55d4.internal]: FAILED! => {"changed": true, "cmd": ["/tmp/awscli-bundle/install", "-i", "/usr/local/aws", "-b", "/bin/aws"], "delta": "0:00:00.040229", "end": "2021-07-16 07:58:15.331303", "msg": "non-zero return code", "rc": 1, "start": "2021-07-16 07:58:15.291074", "stderr": "Unsupported Python version detected: Python 2.7\nTo continue using this installer you must use Python 3.6 or later.\nFor more information see the following blog post: …
```
=> AWS has ended support for python 2.7 client.

ansible/roles_ocp_workloads/ocp4_workload_vertical_pod_autoscaler/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_vertical_pod_autoscaler/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_vertical_pod_autoscaler/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_vertical_pod_autoscaler/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_vertical_pod_autoscaler/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vertical_pod_autoscaler/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vertical_pod_autoscaler/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vertical_pod_autoscaler/tasks/workload.yml
owner: jmaltin
The Vertical Pod Autoscaler (VPA) made its debut in OCP4.6.  In OCP4.8 it is now GA.
VPA is deployed via Operator, available in the redhat operator hub channels.
This implementation defaults to subscription channel '4.8'
Deploys, configures, and removes the VPA
Depends on nothing but OCP >= 4.8
roles_ocp4_workloads/ocp4_workload_vertical_pod_autoscaler
=> Add workload ocp4_workload_vertical_pod_autoscaler

ansible/configs/rhel-security/post_infra.yml
Removes a broken unnecessary task from the rhel-security config
`
fatal: [bastion.blv8z.internal]: FAILED! => {"changed": false, "msg": "Could not find or access '~/.ssh/id_rsa' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
`
rhel-security
=> Remove broken task from rhel-security config.

ansible/export_inventory.yml, ansible/main.yml, ansible/roles/agnosticd_inventory_exporter/defaults/main.yaml, ansible/roles/agnosticd_inventory_exporter/tasks/main.yaml, ansible/roles/agnosticd_inventory_exporter/templates/inventory.yaml.j2
Role to export the in-memory inventory after infra and after
post_software.
The inventory file can then be used as a regular ansible inventory file
to execute ad-hoc ansible commands:
```
ansible -i /tmp/output_dir/inventory_post_infra.yaml all -m ping
```
The feature is disabled by default and can be enabled by changing the value of `agnosticd_inventory_exporter_enable` to `true`.
=> Export in-memory ansible inventory

ansible/roles/ocp4-workload-migration/tasks/download-content.yml
The change of virtualenv to python3 in download-content.yaml causes some tests to fail on RHEL7.
Since this virtual environment has to be enabled for RHEL8, a check is added before the virtualenv change/restore.
ocp4-workload-migration, download-content.yaml file
=> Adding RHEL7 test for virtualenv change in ocp4-workload-migration

ansible/roles/control-user/tasks/create-user.yml, ansible/roles/control-user/tasks/ssh-config.yml
Simply allows the control node user to directly ssh to control (aka bastion) via a randomly generated password
Can be **optionally** activated to avoid the pattern `ssh student@bastion...; sudo su - devops`
role: control-user
=> Enahnce control-user to allow ssh via random generated passwd

ansible/configs/ansible-multi-node/post_software.yml
CF's ruby script doesn't acknowledge \n from Jinja templates
Reverted to calling agnostic_user_info via loop to clean up the user email
config ansible-multi-node
=> config ansible-multi-node user_info enhancement

ansible/roles/ocp4-workload-jdg-workshop/templates/devfile.json.j2
To enable login OpenShift via CRW Terminal in OCP 4.7+
```paste below
```
=> Update ocp4-workload-jdg-workshop for enabling CRW login

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/gitea.yaml.j2
Fixes an issue where gitea would fail to the create the gitea CR due to
null values when the default value ('') for the ansible vars below was used
* ocp4_workload_gitea_operator_gitea_volume_storage_class
* ocp4_workload_gitea_operator_gitea_volume_size
* ocp4_workload_gitea_operator_admin_password
`roles_ocp_workloads/ocp4_workload_gitea_operator`
Ansible output error is 
`"msg": "Failed to create object: b'{"kind":"Status","apiVersion":"v1","metadata": },"status":"Failure","message":"Gitea.gpte.opentlc.com "gitea" is invalid:`
with failures for `XXXX: Invalid value:  null: XXXX in body must be of type string`
for each all of the Gitea CR entries below
```
spec.giteaAdminPassword
spec.giteaVolumeStorageClass …
```
=> FIX: gitea operator -- Set gitea CR string defaults to non-null

ansible/configs/test-empty-config/default_vars.yml, ansible/configs/test-empty-config/post_software.yml
Add control for bookbag deploy to test-empty-config. This allows a default value for the bookbag_repo without triggering deploys by having the default defined in AgnosticV.
=> Add bookbag_deploy control to test-empty-config

ansible/configs/osp-migration/infra.yml, ansible/roles-infra/infra-osp-project-create/tasks/main.yml
Use `agnosticd_user_info` to save the OpenStack API as well as project id and name that was used for the provision. This is useful for automation to locate the project later to implement features such as console access.
Role infra-osp-project-create
Config osp-migration
=> Add save OpenStack project info as user data

ansible/roles-infra/infra-azure-ssh-key/tasks/main.yml
Occasional errors with key vaults and names containing multiple dashes in a row, this is the easiest way to fix that.
roles-infra/infra-azure-ssh-key/tasks/main.yml
There could be more elegant ways to do this, but this will work.
=> CHANGE: roles-infra/infra-azure-ssh-key

ansible/configs/osp-migration/pre_infra.yml
The osp-migration config migration host group `add_host` command requires `output_dir` to be set.
Config osp-migration
=> Set output_dir for migration host in osp-migration

ansible/configs/osp-migration/env_vars.yml, ansible/configs/osp-migration/infra.yml, ansible/configs/osp-migration/post_software.yml, ansible/roles-infra/infra-osp-project-create/defaults/main.yaml, ansible/roles-infra/infra-osp-project-create/tasks/main.yml
Change reporting of OpenStack user data to set `openstack_` prefix rather than `osp_`. This data will be visible to the end user in the new catalog user interface so we should avoid use of abbreviations that make it less obvious for the user.
This PR also introduces `osp_report_project_credentials` to allow configuration of whether project credentials should be reported to the end user.
Config osp-migration
Role infra-osp-project-create
=> Change reporting of OpenStack user data

ansible/roles_ocp_workloads/ocp4_workload_rhacm/defaults/main.yml
Update defaults of ACM workshop role to 2.3.1
Updated vars, `acm-release` `acm-csv` `catalog_source_image` `source_tag`
ACM 2.3.1 is now GA, this change defaults acm role to 2.3.1
=> Update RHACM workload defaults to 2.3

ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/sonarqube.yml
The SonarQube memory limit was increased to 4GB. During testing, SonarQube was observed to consistently crash. When the pod restarted it was using ~ 95%  of its allocated memory. After updating the memory limit, memory usage has been consistent (~50%) without any crashes after executing multiple pipeline runs. 
ocp4_workload_dso (DevSecOps lab)
=> Increase SonarQube Memory Limits

ansible/roles_ocp_workloads/ocp4_workload_hands_on_openshift_48/files/dev_coffeeshop_scrt.yaml, ansible/roles_ocp_workloads/ocp4_workload_hands_on_openshift_48/files/dev_database_scrt.yaml, ansible/roles_ocp_workloads/ocp4_workload_hands_on_openshift_48/files/prod_database_scrt.yaml, ansible/roles_ocp_workloads/ocp4_workload_hands_on_openshift_48/tasks/workload.yml
AgnosticD global `.gitignore` file selects to ignore `*secret.yaml`, which interferes with OpenShift kind: Secret yaml manifests.
Rename my `*secret.yaml` files to `*scrt.yaml`
roles_ocp_workloads/ocp4_workload_hands_on_openshift_48
```paste below
```
=> rename *secret.yaml to *scrt.yaml to avoid gitignore issue

ansible/configs/ocp-workloads/post_infra.yml
Fix bug in ocp-workloads config that inconsistently references both `ansible_host` and `ansible_ssh_host` keys in `target_host` variable.
Config ocp-workloads
=> Fix ocp-workloads config to use ansible_host in target_host

ansible/configs/ocp4-cluster/default_vars.yml, ansible/roles/host-ocp4-installer/create-manifests.yml, ansible/roles/host-ocp4-installer/templates/calico-01-cr-installation.yaml.j2, ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Adding support for Calico as a networking provider during ocp4-cluster provisioning
roles/host-ocp4-installer -- added support for Calico being added to the manifests
configs/ocp4-cluster -- Only default_vars.yaml
This is tested on OpenShift 4.7.15+, not earlier versions
=> UPDATE roles/host-ocp4-installer -- adding Tigera Calico support

ansible/configs/ocp4-workshop/files/cloud_providers/ec2_cloud_template.j2
fixing the following error:
```
TASK [infra-ec2-template-generate : AWS Generate CloudFormation Template] ******
Monday 23 August 2021  11:38:12 +0000 (0:00:00.020)       0:00:12.205 *********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'owner' is undefined"}
```
=> Following up on 7a9ecaee9f2bf2ffcc9cdfc160c8cd27c54695dc

CODEOWNERS
Adding the configs and roles which GPST maintains for partner demos and workshops
Reference team -- https://github.com/orgs/redhat-gpst/teams/agnosticd-maintainers
CODEOWNERS
This will hopefully streamline the PR process
=> CHANGE CODEOWNERS

ansible/roles/ocp-client-vm/tasks/main.yml
Error in deployer causing duplicate /pub/pub to show up in deployer and fail
roles/ocp-client-vm/tasks/main.yaml
**Error message received using AgnosticD**
```
fatal: [clientvm.57cc.internal]: FAILED! => {"changed": false, "msg": "Failure downloading http://d3s3zqyaz8cp2d.cloudfront.net/pub/pub/openshift-v3/clients/3.11.154/linux/oc.tar.gz, HTTP Error 404: Not Found"}
```
=> Fix duplicate /pub in url

ansible/roles/ocp-client-vm/tasks/main.yml
Update main.yml file to remove x86_64 entry as this directory doesn't exist in the repository.
This is to resolve following fatal error.
fatal: [clientvm.0b0e.internal]: FAILED! => {"changed": false, "msg": "Failure downloading http://d3s3zqyaz8cp2d.cloudfront.net/pub/openshift-v4/x86_64/clients/ocp/4.6.0/openshift-client-linux.tar.gz, HTTP Error 404: Not Found"}
=> Update main.yml file

ansible/configs/ocp4-workshop/files/install-config.yaml.j2, ansible/roles/host-ocp4-installer/tasks/main.yml, ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Following up on #3930, which:
* introduced a dedicated role for tags
* removed the variable cf_tags_final in favor of cloud_tags_final.
=> Use name `cloud_tags_final` and not cf_tags_final

ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/create_che_workspace.yaml
Update ocp4-workload-ccn-cuttingedge to remove an unnecessary task
```paste below
```
=> Update ocp4-workload-ccn-cuttingedge to remove an unnecessary task

ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/create_che_workspace.yaml
Add a task to check if CRW API is up
```paste below
```
=> Update ocp4-workload-ccn-cuttingedge to Add a task to check if CRW API is up

ansible/lookup_plugins/unvault_string.py
Add unvault_string lookup plugin. This allows for code like:
```
- name: Set user_password
set_fact:
user_password: "{{ lookup('unvault_string', password) }}
```
If `password` is not vaulted then it is passed straight through.
Just this lookup plugin. Other roles and configs may then use it.
=> Add unvault_string lookup plugin

ansible/configs/ansible-automation-platform/env_vars.yml, ansible/roles/bastion-student-user/defaults/main.yml, ansible/roles/bastion-student-user/tasks/main.yml, ansible/roles/bastion/defaults/main.yml, ansible/roles/bastion/tasks/main.yml, ansible/roles/bastion/tasks/prepuser.yml
By default, only the root user can easily use Ansible throughout the environment,
this is definitely not best practice, and having the student user being able to do it is better.
The solution chosen is a bit complex but avoids duplicating code.
Add possibility to define a group different from user name,
because the student user is created with the "users" group
Add flag to allow the student user to use Ansible or not,
variable is false by default to be backward compatible
* bastion
* bastion-student-user
Really the main driver for this is that it's hard to explain to students that they shouldn't use Ansible as root while we do it in our labs.
=> Add the possibility to use Ansible as student user

ansible/configs/ocp4-cluster/destroy_env_osp.yml, ansible/configs/ocp4-cluster/requirements.yml, ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/tasks/workload.yml
3 Changes:
- Add OpenStack and AWS collections to ocp4-cluster. This should enable developers to use the collections in workloads etc but not affect any existing workloads
- Add support for workload removal during destroy on an OCP 4 Cluster on OpenStack. This is necessary to cleanup things that are not part of the OpenStack environment. For example Route53 entries for the GitOps ILT 
- Fix ILT workload to use proper localhost variables to access OpenStack.
- ocp4-cluster
- ocp4_workload_adv_day2_ops_ilt
=> Add collections to cluster

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/create_user.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/migrate_repos.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
This PR adds support to set up just one (regular) user in Gitea (e.g. lab-user). The capability to set up multiple users remains.
=> Add support for single users for Gitea workload

ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack.Dockerfile
Update ocp4-workload-ccn-cuttingedge to update serverless 1.17.0
```paste below
```
=> Update ocp4-workload-ccn-cuttingedge to update serverless 1.17.0

ansible/roles/deploy_automationcontroller_cfg/tasks/main.yml
Minor change to remove container registry credentials inserted at runtime into the installer inventory file.
Which ends up on the bastion after installation.
=> remove container registry creds from installer inventory

tools/virtualenvs/ansible2.9-python3.6-2021-09-02.txt
fix issue:
```
file://output_dir/ocp-workshop.91a0.ec2_cloud_template
Traceback (most recent call last):
File "/home/opentlc-mgr/virtualenvs/ansible2.9-python3.6-2021-09-02/bin/aws", line 5, in <module>
from aws.main import main
File "/home/opentlc-mgr/virtualenvs/ansible2.9-python3.6-2021-09-02/lib64/python3.6/site-packages/aws/main.py", line 23
print '%(name)s: %(endpoint)s' % {
```
We can update that venv as it's not used anywhere yet
=> Update awscli and botocore

ansible/configs/ansible-automation-platform/software.yml
In order to not use EPEL software, we install ansible beforehand from RHEL while disabling EPEL
config ansible-automation-platform
only the config is impacted, nothing else.
=> Install ansible with disabled EPEL

ansible/roles/ocp-workload-migration/templates/operator.yml.j2, ansible/roles/ocp4-workload-migration/defaults/main.yml, ansible/roles/ocp4-workload-migration/templates/mig-operator-subscription-downstream.yml.j2
This PR updates the required versions for the lab to be updated to the newest 1.5.1 version
roles:
=> Bumping MTC version to 1.5.1 for OCP3/4 labs

ansible/cloud_providers/equinix_metal_infrastructure_deployment.yml
Fix warning in tower:
```
[WARNING]: The specified collections path
/tmp/awx_8023_mfue6yvv/project/ansible/collections' is not part of the
configured Ansible collections paths '/tmp/awx_8023_mfue6yvv/requirements_collections:/var/lib/awx/.ansible/collections:/usr/share/ansible/collections'. The
minstalled collection won't be picked up in an Ansible run   
```
=> Equinix metal: add chdir to anisble-galaxy command

ansible/configs/ocp4-cluster/destroy_env_ec2.yml, ansible/configs/ocp4-ha-lab/destroy_env.yml, ansible/configs/ocp4-workshop/destroy_env.yml, ansible/configs/rosa/destroy_env.yml, ansible/configs/sap-integration/destroy_env_ec2.yml
ocp4-cluster currently does not destroy correctly on some hosts. This PR ensure that creation_time if not defined uses CreationTime instead.
ocp4-cluster and related configs
```paste below
```
=> Use CreationTime when creation_time is not defined

ansible/roles/set-repositories/defaults/main.yaml, ansible/roles/set-repositories/tasks/satellite-repos.yml
set-repositories role:
-  added var and logic to control force registration of subscription
- default:  set_repositories_satellite_force_register: false
- can now set set_repositories_subscription_hostname from outside role
- added test to see if was set before computing set_repositories_subscription_hostname
- removed a duplicate `when:` syntax error
role: set-repositories
I was using this role from a `delegate_to:` and ran into some hostnaming issues.
Also, who doesn't love a good `force`?
```paste below
```
=> set-repositories role: add logic

ansible/export_inventory.yml, ansible/main.yml, ansible/roles/agnosticd_inventory_exporter/tasks/main.yaml
Fix the loop causing the error:
```
Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ stage }}'.
```
=> Fix inventory exporter loop

ansible/roles/host-ocp4-installer/tasks/main.yml
Permissions were wrong for /root/.kube and /home/{{ ansible_user }}/.kube and .kube/config files resulting in warnings when using helm.
Also changed all `/home/xxx` to `~xxx` notation.
=> Fix kube config permissions

ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/defaults/main.yml
Updates the homeroom version in the workshop to V2.2.  This addresses a bug that prevents participants from completing the authorization RH-SSO lab in the workshop (https://github.com/RedHatGov/service-mesh-workshop-dashboard/issues/12).
=> Change workload ocp4_workload_servicemesh_workshop, update homeroom version

ansible/configs/smart-management/pre_software.yml
This fix is in respond to failures of the tower-install role with python2. Pip is installed natively at version 8.1 which fails to install the packages. version 20.3 works and is available. 
smart-management config
```paste below
```
=> smart_management, updating pip to resolve ansible-tower-cli install error

ansible/roles_ocp_workloads/ocp4_workload_le_certificates/files/deploy_certs.yaml
Fix deploy_certs.yaml playbook for letsencrypt certbot. Use `~` for home directory. `ansible_user` is undefined when executing with local connection.
Role ocp4_workload_le_certificates
=> Fix ocp4_workload_le_certificates home path in deploy_certs.yaml

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
The Gitea Workload had wrong variable names to import repositories.
Fixed the variable names - and added logic to still allow old variable names while printing a warning message to avoid breaking existing configs.
=> Fix gitea workload variable names

ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/templates/kustomization.yaml.j2
Bugfix. Sealed Secrets Controller 0.16 did not deploy the --update-status flag.
Also added parameters to turn that feature on or off (when or if 0.17 ships...)
=> Fixed sealed secrets yaml deployment

ansible/roles/set_env_authorized_key/tasks/main.yml
For reasons unknown, using `local_action` here causes `~{{ ansible_user }}` to evaluate incorrectly on subsequent tasks when executed on tower. Switching to `delegate_to` resolves it somehow.
role set_env_authorized_key
=> Remove use of local_action in set_env_authorized_key

ansible/roles/bastion-lite/tasks/main.yml, ansible/roles/bastion/tasks/main.yml, ansible/roles/host-ocp4-installer/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_industrial_edge/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_paloalto_prismacloud/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/remove_workload.yml
Remove use of `ansible_user` in loops. When executed in tower with Ansible 2.9 `ansible_user` does not consistently evaluate to the correct user, instead evaluating to `root` when used in loops.
Ex: https://tower.dark-tower-prod.infra.open.redhat.com/#/jobs/playbook/298923
Various components
=> Remove use of ansible_user in loops

ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/workload.yml
Add retries on task to remove htpasswd secret.
=> Add retries to first k8s task in ocp4_workload_authentication

tools/virtualenvs/README.adoc
=> Add known issue for pyvenv

ansible/lifecycle_ec2.yml
Change to use `ec2` module to start and stop instances rather than `ec2_instance`. The `ec2` module is idempotent and does not produce an error when all instances are found to already be started or stopped.
ec2 cloud provider
=> Switch to use ec2 module to start/stop instances

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_pipelines/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
Pipelines Operator changed names in the latest release.
Adding variables to specify the CSV prefix. Default is the old name for compatibility.
=> Update Gitops and Pipelines operators to support changed names

ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/files/ec2-role-access-policy.json, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/files/ec2-role-trust-policy.json, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/workload.yml
This new ocp4_workload role is (I hope) useful with any OCP4 cluster config (or BYO cluster).
It deploys any number of RHEL8 instances to be used as worker nodes.   It does not run the playbooks to install OpenShift on the RHEL nodes, or automate their joining the cluster.  That's for the student to do.  Samples code of the steps necessary to setup OpenShift on the RHEL nodes and have them join the cluster are in the workload.yml comments.
It deploys the RHEL instances into the VPC of the existing cluster in the sandbox.
It sets up all AWS permissions necessary for the new RHEL nodes to join the cluster.
It updates the bastion host with a checkout of the openshift-ansible project and a list of RHEL_workers.txt to be added to an ansible inventory.
The user must run the openshift-ansible …
=> ocp4_workload_rhel_worker: new workload

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
Deployment of the Gitea Operator with default variables failed because the logic assumed an admin password to be set.
=> Fix deployment with default variables

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
needed a second registered variable and to change ordering so ansible could find `r_gitea.resources[0]` OK.
```paste below
```
=> add second registered var to avoid conflicts

ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/defaults/main.yml
Use the SSH key generated for OCP install, not the backdoor key.
Use the backdoor key when developing from laptop.
```paste below
```
=> set false to use unique ssh key, not backdoor

ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/workload.yml
more WiP:
* revert use of custom key
* use backdoor key
* asserted become: false in wait_for_connection play 
* * ansible was connection to bastion as ec2-user, and then connecting to worker as root. BAD
```paste below
```
=> [WiP] Judd rhel worker bastion key

ansible/roles-infra/infra-ec2-template-generate/defaults/main.yml
This PR re-enables the me-south-1 AMI mappings that were originally submitted by PR https://github.com/redhat-cop/agnosticd/pull/3332, but accidentally backed out by PR https://github.com/redhat-cop/agnosticd/pull/3697
Note that this PR leaves the `GOLD` images out for the `me-south-1` region since I don't have access to the correct account to obtain these AMI values. If someone have these handy for the `me-south-1` region, I'd be happy to include them in this PR - if not, perhaps a follow-up PR can be submitted in the future with these values. 
```paste below
```
=> re-enabling me-south-1 AMI mappings

ansible/configs/aap2-ansible-workshops/vars/automate_smart_mgmt_vars.yml
aap2-ansible-workshops config vars addition for Ansible "Automated Smart Management" workshop
automate_smart_mgmt_vars.yml vars file for deploying Automated Smart Management workshop
Entire `ec2_xtra` stanza will need to defined in order to point workshop provisioner to location of Satellite AMI, intentionally left commented out in order to provide the complete example of what will need to be defined, hidden from view here in a public repo
=> "Automated Smart Management" config vars definition for AAP2-based workshop

ansible/roles-infra/infra-ec2-template-generate/defaults/main.yml
During the process of the worshop deployment the installer was stuck on istio-system. The service mesh operator was not installed due to the version used to the previous main.yml file. I updated several operator version to allow to deploy the Workshop.
```paste below
```
=> version of operators changed into the Debugging workshop 

ansible/roles-infra/infra-equinix-metal-resources/defaults/main.yaml, ansible/roles-infra/infra-equinix-metal-resources/tasks/delete_instances.yaml
Fix error:
```
TASK [infra-equinix-metal-resources : Delete all devices] **********************
Friday 10 December 2021  18:59:04 +0000 (0:00:01.011)       0:00:47.201 *******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: packet.baseapi.ResponseError: Error 422: Cannot delete a device while it is provisioning
fatal: [localhost]: FAILED! => {"changed": false, "msg": "failed to set device state absent, error: Error 422: Cannot delete a device while it is provisioning"}
```
=> Equinix: Harden deletion of resources

ansible/roles-infra/infra-equinix-metal-create-inventory/tasks/main.yaml
```
TASK [infra-equinix-metal-create-inventory : Create inventory (add_host)] ******
Friday 10 December 2021  17:38:11 +0000 (0:00:00.038)       0:07:40.638 ******* 
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'public_ipv6'\n\nThe error appears to be in '/tmp/awx_314755_1nw664eu/project/ansible/roles-infra/infra-equinix-metal-create-inventory/tasks/main.yaml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create inventory (add_host)\n  ^ here\n"}
```
=> Equinix: Omit ipv6 when not present

ansible/roles_ocp_workloads/ocp4_workload_industrial_edge/tasks/workload.yml
Ansible Tower bug. Remove loops everywhere {{ ansible_user }} is used (otherwise ansible user gets set to root)
ocp4_workload_industrial_edge
=> Remove loops where {{ ansible_user }} is used.

ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/acs.yml
Due to a race condition detected in the DSO Lab 4 during the installation of the Security Lab rhpds environment, a delay until the ACS Operator is ready is needed.
=> ocp4_workload_4 - fix the race condition for ACS Central installation

ansible/configs/ansible-multi-node/pre_software.yml, ansible/configs/ansible-multi-node/setup_hands_on_aap2.yml
Simplifies and extends the config ansible-multi-node
- move to `bastion-lite` as it is simpler and cleaner than `bastion`
- Add git repo resource injection
- Refactor some paths e.g replace `/home/devops` with more versatile/robust `~devops/` etc
- Eliminate some repo making code in favor of curated Satellite HA Content view
config ansible-multi-node
=> Simplify and enhance config ansible-multi-node for HONA

ansible/roles/codeready_containers_hacks/tasks/configure-oc-cli.yml
Updating the OC link to download the package, file not found however path has extra / in the link.
```paste below
```
=> Updating the OC link to download the package

ansible/configs/aap2-ansible-workshops/vars/automate_smart_mgmt_vars.yml
Uncommenting the ec2_xtra vars section and updating with the prod AWS Account ID and updated filter.
```paste below
```
=> Adding RHPDS Prod AWS Account Details

ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/templates/kustomization.yaml.j2
Sealed Secrets finally released 0.17.1. And Helm Chart 2.0.0. Updated workload to support those versions (and only those versions at a minimum).
=> Update Sealed Secrets workload for 0.17.1 (and Helm Chart 2.0.0)

ansible/roles-infra/infra-dns/defaults/main.yml, ansible/roles-infra/infra-dns/readme.adoc, ansible/roles-infra/infra-dns/tasks/instance_loop.yml, ansible/roles-infra/infra-dns/tasks/nested_loop.yml, ansible/roles-infra/infra-osp-dns/defaults/main.yml, ansible/roles-infra/infra-osp-dns/tasks/instance_loop.yml, ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml
instances[].dns_records   list of alt names for instances.
```
- name: node
count: 3
public_dns: true
dns_records:
- machine
- server
```
Will create:
- node{1,2,3}.guid A records, using the public IP of each node
- machine{1,2,3}.guid CNAME records pointing to the corresponding A records
- server{1,2,3}.guid CNAME records pointing to the corresponding A records
=> Add alternative DNS names for instances

ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt/tasks/workload.yml
The ILT Needs an operator to be able to create ArgoCD managed namespaces. Somehow I had missed to commit that before.
Here it is.
ocp4_workload_adv_app_deploy_ilt
=> Re-added argocd namespace operator to ILT workload

ansible/roles-infra/infra-azure-ssh-key/tasks/main.yml
Add another error handler for azure keyvault check - this failure is breaking destroys when the ssh key is not in the vault.
ocp4-cluster
```paste below
```
=> Add another error handler for azure keyvault check

ansible/roles/ocp4_approve_certificate_signing_requests/defaults/main.yml
Change initial wait time for CSR update to 5 min.  Give the cluster a little more time to show pending CSR requests.
roles/ocp4_approve_certificate_signing_requests
```paste below
```
=> Change wait time for CSR update to 5 min

ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/workload.yml
Fix wrong variable name in install operator.
=> Fix variable name in Quay Operator workload

ansible/cloud_providers/azure_infrastructure_deployment.yml, ansible/configs/ocp4-cluster/requirements.yml
add azure collections to ocp4-cluster
ocp4-cluster
```paste below
```
=> add azure collections to ocp4-cluster

ansible/configs/sap-hana/files/cloud_providers/osp_cloud_template_master.j2
This Change removes the forced external subnet of the floating ip and
instead implements a variable check to define, using the 
"find_osp_public_subnet" boolean in the generic OSP cloud provider.
This particular forced tag is the reason for all of the failed sap-hana
config deployments.
Config: sap-hana, OSP cloud template j2
None
=> Removing forced external subnet definition

ansible/roles/open-env-azure-invite-user/tasks/main.yml
open-env-azure-invite-user - Changing to jenkins.sfo01@gmail.com
```paste below
```
=>  open-env-azure-invite-user

ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/workload.yml
Default volume size was 10G.  Lab failed with such a small volume.  Increase volume size to 120G.
```paste below
```
=> ocp4_workload_rhel_worker: add volume to RHEL worker

ansible/install_galaxy_roles.yml, ansible/roles/ocp4_approve_certificate_signing_requests/defaults/main.yml, ansible/roles/ocp4_approve_certificate_signing_requests/tasks/approve-certificate-signing-requests.yml
Add logic to the ocp4_approve_certificate_signing_requests role to check the node status to confirm that all nodes report Ready status with a recent lastHeartbeatTime before completing. This gives nodes time to request CSRs rather than relying on an arbitrary wait time.
Role ocp4_approve_certificate_signing_requests
=> Add wait for nodes to be ready to ocp4_approve_certificate_signing_requests

ansible/configs/osp-migration/env_vars.yml, ansible/configs/osp-migration/post_software.yml
Labconsole was on https://dynamic-labconsole.apps.shared-na4.na4.openshift.opentlc.com/ (shared ocp4) and idea is to use the babylon environment (https://console.apps.open.redhat.com/)
=> Update config osp-migration to use new labconsole url

ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
fix workload output for storage
roles/ocp4-workload-workshop-admin-storage
workshop output was using debug not agnosticd_user_info module which does not populate babylon
```paste below
```
=> fix workload output for storage

ansible/roles/open-env-azure-delete-open-env/tasks/main.yml
fix azure open env delete by forcing deletion of resource group
azure open environment
```paste below
```
=> fix azure open env delete

ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml
This PR migrated from `k8s` and `k8s_info` to `kubernetes.core`.
Also includes a validation for rhacm resources.
Deployments on overloaded regions can result in an ocp race condition resulting an error on a `lenght` validation, this PR ensures the variable `rhacm_csv.resources` is defined before moving on.
Tested on Ansible 2.9.20
```
ansible==2.9.20
appdirs==1.4.4
attrs==21.4.0
autopage==0.5.0
Babel==2.9.1
boto3==1.20.46
botocore==1.23.46
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.11
cliff==3.10.0
cmd2==2.3.3
cryptography==36.0.1
debtcollector==2.4.0
decorator==5.1.1
distro==1.6.0
dnspython==2.2.0
dogpile.cache==1.1.5
idna==3.3
iso8601==1.0.2
Jinja2==3.0.3
jmespath==0.10.0
jsonpatch==1.32
jsonpointer==2.2 …
```
=> Migrated to kubernetes.core packages and add validation to rhacm_csv.resources

ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/post_workload.yml
Fix ocp4-workload-ccn-cuttingedge to replace user.info module
```paste below
```
=> Fix ocp4-workload-ccn-cuttingedge to replace user.info module

ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/post_workload.yml
Fix ocp4-workload-ccn-cuttingedge to fix 'm1' yaml error
```paste below
```
=> Fix ocp4-workload-ccn-cuttingedge to fix 'm1' yaml error

ansible/roles/ocp4-workload-ccnrd-stable/tasks/post_workload.yml
Fix ocp4-workload-ccn-stable to replace user.info module
```paste below
```
=> Fix ocp4-workload-ccn-stable to replace user.info module

ansible/lookup_plugins/bitwarden.py
Add `bitwarden` lookup plugin.
This lookup can be used either with a pre-unlocked Bitwarden CLI or passing client credentials and master password:
```
- name: Set api_access from Bitwarden when CLI is already unlocked
set_fact:
api_access: "{{ lookup('bitwarden', 'api-access-credentials') }}.login"
- name: Set api_access from Bitwarden including Bitwarden login and unlock
set_fact:
api_access: >-
{{
lookup(
'bitwarden', 'api-access-credentials',
client_id = bitwarden_client_id,
client_secret = bitwarden_client_secret,
master_password = bitwarden_master_password
).login
}}
```
New lookup plugin `bitwarden`
=> Add Bitwarden lookup plugin

ansible/configs/test-empty-config/update.yml, ansible/lifecycle_hook.yml, ansible/lookup_plugins/agnosticd_user_data.py, ansible/roles/agnosticd_restore_output_dir/tasks/main.yml, ansible/roles/agnosticd_restore_output_dir/tasks/restore-from-s3.yml, ansible/setup_runtime.yml, ansible/update.yml, ansible/update_placeholder.yml
The update entry point playbook allows for updating existing
deployments. The update functionality must be implemented within the
config. An example for test-empty-config is provided.
Update functionality includes the new `agnosticd_user_data` lookup
plugin and `agnosticd_restore_output_dir` role so that updates can
fetch data items set during the initial provision.
- Core update.yml entry-point playbook
- Config test-empty-config
- `agnosticd_user_data` lookup plugin
- `agnosticd_restore_output_dir` role
=> Add update entry point playbook

ansible/roles/ocp4-workload-debugging-workshop/tasks/post_workload.yml
during the argo-cd checking the process failed because 2 pod were not ready.  argocd-dex-server, argocd-server, argocd-repo-server  were in progressing state. Only the argocd-redis were up. By changing the code with 50 iterations maximum for each pod status it will validate the deployment of argocd.
fixing this issue 
failed: [clientvm.78fjk.internal] (item={'observedGeneration': 1, 'replicas': 1, 'updatedReplicas': 1, 'unavailableReplicas': 1, 'conditions': [{'type': 'Available', 'status': 'False', 'lastUpdateTime': '2022-02-21T09:59:25Z', 'lastTransitionTime': '2022-02-21T09:59:25Z', 'reason': 'MinimumReplicasUnavailable', 'message': 'Deployment does not have minimum availability.'}, {'type': 'Progressing', 'status': 'True', 'lastUpdateTime': '2022-02-21T09:59:26Z', …
=> change the argocd deployment checking.

ansible/roles/ocp4-workload-authentication/defaults/main.yml, ansible/roles/ocp4-workload-authentication/tasks/workload.yml, ansible/roles/ocp4-workload-authentication/templates/oauth-htpasswd.j2
This will allow for the default `htpasswd` identity provider to be customized with a name other than the default `htpasswd_provider`. At times when there are multiple identity providers configured, the default name isn't descriptive enough and hence this change to allow for a custom name at deploy time. 
ocp4-workload-authentication
Example for default value override:
```
ocp4_workload_authentication_vars:
htpasswd_oauth_name: admin_identity_provider
```
=> Allowing for htpasswd_oauth provider to have customizable name

ansible/action_plugins/agnosticd_user_info.py
Add `user` key to result from `agnosticd_user_info` action plugin to support parsing per-user data and messages from ansible logs. This is required for full compatibility with picking up per-user data and messages from the ansible job logs when the callback is not processed or the job check occurs after job completion but before the callback in processed.
`agnosticd_user_info` action plugin
=> Add user key in agnosticd_user_info result

ansible/configs/ocp4-equinix-aio/default_vars_equinix_metal.yml, ansible/configs/ocp4-equinix-aio/pre_software.yml, ansible/configs/ocp4-equinix-aio/requirements.yml, ansible/configs/ocp4-equinix-aio/sample_vars_equinix_metal.yml
As equinix metal doesn't support centos streams and centos 8 is not supported/doesn't have repos anymore, this change makes the aio work with the closest alternative on equinix metal : Rocky Linux
=> Ocp4 equinix aio

ansible/configs/aap2-ansible-workshops/infra.yml
The AAP2 Workshops already use Ansible 2.12 to deploy and even with `--skip-tags` Ansible tries to validate the ec2 cloud provider modules leading to failures as they are now distributed across 2 collections. For example despite skipping ec2_instance_facts deploys fail as they attempt to locate the module. (There appear to be some bugs in how 2.12 and collections redirect references to modules as by design 2.12 **should** be able to correctly locate the module without its FQCN)
To be clear the Workshop make **zero** use of AgnosticD Cloud Provider code still preferring their own so this PR brings no loss of functionality.
(As an aside all cloud "facts" modules are depreciated and 1) need to move to the `*_info` versions and 2) the register structure changes so loops and conditionals etc …
=> Added empty infra.yml to AAP2 config to avoid ec2 cloud provider checks

ansible/configs/aap2-ansible-workshops/post_infra.yml
Bugs in 2.12 and changes in the **2** AWS Collections are breaking AgnosticD's ability to locate the correct module. This PR adds the 2 collections via the `collections` keyword
Config: aap2-ansible-workshops
=> Added collections keyword to AAP2 post_infra as 2.12 workaround

ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml
Defaulting install plan approve to false of rhacm workload
ansible 2.9.20
config file = /Users/singularity/src/agnosticd/ansible.cfg
configured module search path = ['/Users/singularity/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /Users/singularity/.virtualenvs/deployer/lib/python3.10/site-packages/ansible
executable location = /Users/singularity/.virtualenvs/deployer/bin/ansible
python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
```
ansible==2.9.20
appdirs==1.4.4
attrs==21.4.0
autopage==0.5.0
Babel==2.9.1
boto3==1.20.46
botocore==1.23.46
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.11
cliff==3.10.0
cmd2==2.3.3
cryptography==36.0.1 …
```
=> Disable rhacm subscription auto-approve

ansible/configs/aro/software.yml
Make aro installer get token from file
aro
```paste below
```
=> fix where token comes from in aro

ansible/roles_ocp_workloads/ocp4_workload_authentication/defaults/main.yml
Set default user count for ocp4_workload_authentication to use well known variables `user_count` and `num_users` as defaults.
=> Default ocp4_workload_authentication to use user_count and num_users

ansible/roles/ocp4-workload-debezium-demo/tasks/provision_streams.yaml
Increasing retires from 10 - 15 to attempt to fix demo
---
--
  | - name: Evaluate Streams Subscription
  | k8s:
  | state: present
  | resource_definition: "{{ lookup('template', 'streams-subscription.yaml.j2') }}"
  |  
  | - name: Wait for Streams operator to install
  | k8s_info:
  | api_version: apiextensions.k8s.io/v1beta1
  | kind: CustomResourceDefinition
  | name: kafkas.kafka.strimzi.io
  | register: crd_streams
  | until: crd_streams.resources \| list \| length == 1
  | retries: 10 >>>>>>>>  15 
  | delay: 30
---
- name: Evaluate Streams Subscription
k8s:
state: present
resource_definition: "{{ lookup('template', 'streams-subscription.yaml.j2') }}"
- name: Wait for Streams operator to install
k8s_info:
api_version: [apiextensions.k8s.io/v1beta1](http://apiextensions.k8s.io/v1bet …
=>  ocp4-workload-debezium-demo - provision streams retires increase

ansible/configs/aap2-ansible-workshops/post_infra.yml
Ansible Workshops is on the latest amazon.aws collection and ec_instance_facts becomes ec2_instance_info
This PR fixes that
Config aap2-ansible-workshops
=> Fix AAP2 using ec2_instance_facts to _info

ansible/configs/sap-hana/software.yml
<!--- Describe the change below, including rationale and design decisions.
make a fix to ensure successful deployment of sap-hana configuration, although there is a missing variable.
In case the variable is missing the post installation step is skipped
as per request of Ahsen Shah in the chat
=> config/sap-hana: Only deploy AAP software if offline_token is defined

ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml
Sometimes when cleaning up, DNS zones dont exist so it should move on.
```paste below
```
=> Sometimes the DNS zones dont exist, just move on

ansible/configs/three-tier-app/default_vars.yml, ansible/configs/three-tier-app/default_vars_ec2.yml, ansible/configs/three-tier-app/default_vars_osp.yml, ansible/configs/three-tier-app/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/three-tier-app/post_infra.yml, ansible/configs/three-tier-app/pre_infra.yml, ansible/configs/three-tier-app/pre_software.yml, ansible/configs/three-tier-app/sample_vars/private-dns-osp.yml, ansible/configs/three-tier-app/sample_vars_ec2.yml
Following up on https://github.com/redhat-cop/agnosticd/pull/4521
- update ssh access in three-tier-app, use common workflow
- use satellite as repo_method in example
- remove key_name (use generated provision ssh key)
- remove unecessary HostedZoneId (subdomain is enough)
- use RHEL8-default for image (infra-images role)
* three-tier-app config on aws.
=> Update three-tier-app, SSH, images, repos

ansible/configs/test-empty-config/default_vars.yml, ansible/configs/test-empty-config/post_software.yml
Add `test_empty_config_user_count` for test-empty-config. Previously this was hard-coded to 10 users.
=> Add user count for test-empty-config

ansible/configs/test-empty-config/post_software.yml
Fix bug with `test_empty_config_user_count` requiring `int` filter.
=> Fix test-empty-config test_empty_config_user_count bug

ansible/cloud_providers/ec2_infrastructure_deployment.yml, ansible/cloud_providers/osp_infrastructure_deployment.yml, ansible/roles/bastion-student-user/defaults/main.yml, ansible/roles/bastion-student-user/tasks/main.yml, ansible/roles/bastion/tasks/prepuser.yml, ansible/roles/control-user/defaults/main.yml, ansible/roles/control-user/tasks/ssh-config.yml, ansible/roles/locate_env_authorized_key/readme.adoc, ansible/roles/locate_env_authorized_key/tasks/main.yaml, ansible/roles/set_env_authorized_key/defaults/main.yaml, ansible/roles/set_env_authorized_key/tasks/main.yml
This change, if applied, add a new role to detect the env_authorized_key
to use, see its readme.
- use those facts instead of role defaults in diverse places
- run 'locate_env_authorized_key' role at the beginning of infra, after
key creation
=> New role to detect env_authorized_key path

ansible/configs/ocp4-cluster/requirements.yml
ocp4-cluster was missing the ansible.posix collection (needed for authorized keys)
ocp4-cluster
=> Added posix collection

ansible/configs/aap2-ansible-workshops/pre_infra.yml
As discussed in the chat, it would be helpful to have more information (esp the admin password) in the RHPDS notification email.
The way it is right now a facilitator has to assign him/herself an environment first to get the password, then go to the admin page (/list.php) to login with the password to control environments. And free up the env assigned to self...
From what I know the information used in the email message comes from the user.info data so I changed these lines, not knowing completely how the  agnosticd_user_info handles line breaks.
The admin_password var is available to the provision_lab.yml Playbook.
@tonykay @IPvSean 
```paste below
```
=> Get mor info from pre_infra.yml for email 

ansible/configs/ibm-rhoic/pre_infra.yml, ansible/configs/ibm-rhoic/software.yml
Add reference to `requester_username` and `requester_email` to facilitate transition for ibm-rhoic config to use these vars.
Config ibm-rhoic
=> Add requester vars for ibm-rhoic config

ansible/configs/sap-smart/files/cloud_providers/osp_cloud_template_master.j2
Adding config_drive: True to the osp template.
This should help with metadata configuration during provisions. A disk will be mounted with the metadata and it will reduce the risk of errors
sap-smart config
=> Adding config_drive to sap-smart osp template

ansible/roles-infra/infra-ec2-template-generate/templates/cloud_template.j2
Add support for hyphens in instance names using our ec2 cloudformation template.
Resource names in CloudFormation do not support hyphens even though instance names and dns names do support it. This PR strips any hyphens out of CloudFormation resource names.
Also adds ability to place host DNS in separate DNS zone.
ec2 cloud provider
=> Add support for hyphens in ec2 instances names

ansible/configs/open-environment-gcp/default_vars.yml
fix requester_name in gcp open env
open-environment-gcp
```paste below
```
=> fix requester_name

ansible/configs/ocp4-cluster/pre_infra.yml, ansible/roles-infra/infra-aws-capacity-reservation/readme.adoc, ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
This change, if applied, allows more ways to arrange the clusters in different zones.
By default:
* 2 zones for workers
* 1 zone for masters
* 1 zone for bastion
Supported names for logical zones:
* workers1, workers2
* masters
* az1 for bastion
We can force zones to be distinct with `agnosticd_aws_capacity_reservation_distinct: true`.
It's possible to force everything into a single zone (costs effective, less HA) with `agnosticd_aws_capacity_reservation_single_zone: true`.
No flexibility to change the number of zone as the configs expects `masters` `workers1` and `workers2` logical zones.
It's always possible to change the layout by also changing the variables to specify how to use the new layout:
```yaml
openshift_controlplane_aws_zones_odcr
openshift_machineset_aws_zones_odcr …
```
=> ocp4-cluster config, support multiple zone-layout for ODCR

ansible/configs/open-environment-gcp/default_vars.yml
Remove email domain from username if it exists.  This breaks GCP as project names cannot have an @ in them.
open-environment-gcp
```paste below
```
=> Remove domain from username

ansible/cloud_providers/ec2_infrastructure_deployment.yml
The ec2 cloud provider should not generate an SSH config when the cloud formation template does not create any bastion hosts. This is required for the sandbox config.
=> Do not generate ssh config when no bastions are deployed

ansible/roles/open-env-gcp-add-user-to-project/README.md, ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml, ansible/roles/open-env-gcp-remove-project/tasks/main.yml
Add admin group to gcp sandboxes
open-env-gcp
```paste below
```
=> Add admin group to gcp sandboxes

ansible/roles_ocp_workloads/ocp4_workload_sealed_secrets/defaults/main.yml
Sealed Secrets moved the image from Quay to DockerHub. This PR fixes that by updating to the latest release.
=> Fix sealed secrets controller

ansible/configs/open-environment-azure-subscription/post_software.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/homeroom.yaml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/per_user_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/jaeger_subscription.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/kiali_subscription.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/rhsso_installplan.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/rhsso_operator.j2, ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/templates/servicemesh_subscription.j2
Updating Service Mesh Workshop to run on OpenShift 4.10. Add missing imagestreams and fix operator installations to avoid k8s API deprecation problems.
=> Update ocp4_workload_servicemesh_workshop to run on OCP 4.10

ansible/roles/host-ocp4-installer/create-manifests.yml
rhjcd-patch-change urls to upgrade calico on ocp4
```paste below
```
=> change urls to upgrade calico on ocp4

ansible/configs/open-environment-azure-subscription/default_vars.yml, ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
add the ability to specify a pool to the pool manager API in azure
./open-env-azure-add-user-to-subscription/tasks/main.yml
./open-env-azure-remove-user-from-subscription/tasks/main.yml
./open-env-azure-remove-user-from-subscription/tasks/main.yml
```paste below
```
=> add multi pools to azure subscription

ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/workload.yml
Demo instructions need the name of the VM in RHEV. Adding to the agnosticd_info output.
ocp4_workload_ama_rhev_vm
=> Add VM name to output of workload

ansible/configs/ocp-workloads/requirements.yml
An error is thrown when running a removal workload of a LPE_INTEGRATION DEV lab:
`FAILED! => {"reason": "couldn't resolve module/action 'kubernetes.core.k8s_json_patch'. This often indicates a misspelling, missing collection, or incorrect module path.\\n\\nThe error appears to be in '/tmp/awx_482900_wxz_7ck2/project/ansible/roles_ocp_workloads/ocp4_workload_lpe_fuse/tasks/remove_workload.yml': line 13, column 3,`
Upgrading kubernetes.core should resolve this
The LPE_INTEGRATION DEV lab was introduced in https://github.com/redhat-cop/agnosticd/pull/4698
New config Pull Request
ocp-workloads
=> Upgrade kubernetes core for ocp-workloads

ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/tasks/remove_workload.yml
The removal of lpe_amq_streams was not working due to the wrong vars assignment.
This PR assigns the correct vars to the remove_workload.yml ansible tasks.
ocp4_workload_lpe_amq_streams
=> Fix lpe amq streams default vars

ansible/install_galaxy_roles.yml
Sometimes, a catalog item needs additional ansible collection, depending
on the workloads it installs.
This change, if applied, adds the ability to define the entire content
of requirements.yml file that is usually in the config directory.
Code is taken from https://github.com/redhat-cop/agnosticd/pull/3054
agnosticd core
=> Feature: dynamically define galaxy requirements

ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/templates/code-server-config.yaml.j2
Let's Encrypt certificates are only implemented for AWS (Route53). Add variable to make requesting certificates optional (e.g. for OSP deployments).
=> Made requesting certificates optional for VSCode

ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml
fix issue where dns zone names are very touchy in GCP
open-env-gcp
```paste below
```
=> fix goofy issue with dns zone name

ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/files/user_settings.json
Disable trust prompt for workspaces in VSCode.
=> trust default workspace

ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml, ansible/roles/open-env-gcp-remove-project/tasks/main.yml
fix bug in delete and add google api enablement
open-env-gcp
```paste below
```
=> fix bug in delete and add google api enablement

ansible/roles/host-ocp4-provisioner/defaults/main.yml
As of today, AWS has deprecated python 3.6 in awscli-latest.tar by
moving to 1.25.0 which removes 3.6 support.
As a quick fix, we are forcing all OCP deploys to use a python 3.6
supported version of awscli until a longer term fix can be implemented.
ocp4-installer
(https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/)
Deploys are now failing with 
```
fatal: [bastion.internal]: FAILED! => {"changed": true, "cmd": ["/tmp/awscli-bundle/install", "-i", "/usr/local/aws", "-b", "/bin/aws"], "delta": "0:00:00.054218", "end": "2022-05-31 22:38:55.021126", "msg": "non-zero return code", "rc": 1, "start": "2022-05-31 22:38:54.966908", "stderr": "Unsupported Python version detected: Python 3.6\nTo continue using this installer you must …
```
=> Force AWS CLI version to 1.18.200

ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/tasks/workload.yml
Fixes the deployment of the service mesh by adding time pauses to wait for the operator fully install.
ocp4_workload_lpe_servicemesh
=> Add pause task to fix svc mesh installation

ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/workload.yml
Feature: allow installation of extensions into VSCode Server.
Extension files *must* be hosted in the same location - e.g. the GPTE S3 Bucket.
=> Allow installation of extensions

ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/workload.yml
Increase retry for RGW deployment to fix issue
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "WARNING: key_name is DEPRECATED and should not be defined when using new create_ssh_provision_key role."}
...ignoring
FAILED - RETRYING: Wait for the RGW deployment (1 retries left).
fatal: [bastion.67f65.internal]: FAILED! => {"attempts": 18, "changed": false, "resources": []}
FAIL sandboxes-gpte-OCP4_WORKSHOP_DATA_ENGINEERING-prod-eb8d run_babylon provision
FAIL tower status: failed
```
ocp4-workload-rhte-analytics_data_ocp_workshop role
=> Increase retry for RGW deployment to fix issue

ansible/roles/ocp4-workload-ocs-poc/tasks/workload.yml
Increase retry to access bucket to fix below issue:
```
TASK [ocp4-workload-ocs-poc : Wait for Bucket to have status] ******************
FAILED - RETRYING: Wait for Bucket to have status (30 retries left).
.............
.............
FAILED - RETRYING: Wait for Bucket to have status (2 retries left).
FAILED - RETRYING: Wait for Bucket to have status (1 retries left).
fatal: [bastion.2mfqt.internal]: FAILED! => {"attempts": 30, "changed": false, "resources": [{"apiVersion": 
..................................................................
..................................................................
```
Full log: https://tower.dark-tower-prod.infra.open.redhat.com/#/jobs/playbook/537465
ocp4-workload-ocs-poc
=> Increase retry to access bucket

ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/create_user_workloads.yml
Add retry to address race condition in ServiceMeshControlPlane creation
=> Add retry to control plane creation on service mesh workshop role

ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/create_user_workloads.yml
must add `until` for `retries` to be regarded
@dudash
=> Add until clause to smcp creation

ansible/roles/ocp4_workload_stackrox_demo_apps/templates/openshift_policy_fix/policy.json.j2
Red Hat ACS 3.70 deprecated some API fields in the /v1/policies endpoint
https://docs.openshift.com/acs/3.70/release_notes/370-release-notes.html#deprecation-notices-370
The ansible playbook for updating policies expects these values to be present, and the failure results from these being missing. Since the two fields aren't required for any functionality, I just removed them. 
ocp4_workload_stackrox_demo_apps
```paste below
```
=> ACS removed some fields in policy API in 3.70

ansible/configs/sap-hana/software.yml
Instead of calling the role since some of its tasks have conflicts with sap-hana config
```paste below
```
=> Added tasks to deploy Ansible Tower  for sap-hana config

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/files/gitconfig, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/setup-gitops.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/vm-tomcat-install-and-configure.yml, ansible/roles_ocp_workloads/ocp4_workload_big_demo/files/gitconfig, ansible/roles_ocp_workloads/ocp4_workload_big_demo/tasks/workload.yml
Allow insecure connections to the Gitea repository. This is necessary to be able to move the Let's Encrypt and Authentication workloads towards the end of provisioning to prevent API and authentication pods from rotating while the deployment continues...
ocp4_workload_big_demo
=> Allow for insecure Gitea connections

ansible/roles_ocp_workloads/ocp4_workload_authentication/defaults/main.yml
Do not report per-user messages for ocp4_workload_authentication unless multiple users are configured.
=> Do not report per-user messages for ocp4_workload_authentication if user count is one

ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/workload.yml
Add pause for node to come up in ocp windows node role
ocp4_workload_windows_node
```paste below
```
=> Add pause for node to come up in ocp windows node role

ansible/roles_ocp_workloads/ocp4_workload_mta_tackle/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle/templates/seed-tackle.sh.j2
In case the mta_tackle workload runs before certificates exist the seeing of tackle fails.
Added -k to all curl commands in the seed script to ignore.
ocp4_workload_mta_tackle
=> Make curl commands insecure in tackle workload

ansible/configs/ocp4-equinix-aio/default_vars_equinix_metal.yml
SUMMARY
As per Alberto's request changing to use da6 to help resolve 
Error 503: The facility am6 has no provisionable s3.xlarge.x86 servers matching your criteria 
default_vars_equinix_metal.ym
=> default_vars_equinix_metal.yml - changing to da6 from am6

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/vm-oracledb-install-and-configure.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/vm-tomcat-install-and-configure.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/workload.yml
Apache removed the Tomcat download URL and replaced with a newer version. Update download URL to newer version and use the default download from the GPTE S3 Bucket instead.
Add two flags to use pre-installed VM templates instead of installing Oracle and Tomcat from scratch. This speeds up deployment of this workload by at least 30 minutes.
=> Fix tomcat download URL, enable use of pre-installed VM templates

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/remove_workload.yml
Bugfix: when destroying an AMA environment this workload deletes the RHV VMs and then tries to clean up OpenShift. The OCP cleanup can fail if the cluster node(s) had not been running upon deletion because the cluster may not be ready yet.
Add variable (defaults to false) to not destroy OpenShift resources - which is usually fine because the cluster gets deleted anyway.
=> Add variable to omit delete of namespaces upon workload destroy

ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/post_workload.yml
Fix loop_var in ocp4-workload-homeroomlab-starter-guides.
Role ocp4-workload-homeroomlab-starter-guides
=> Fix loop_var in ocp4-workload-homeroomlab-starter-guides

ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/approve_installplan.yml
deploy fail due to timeout with - TASK [install_operator : advanced-cluster-management - Wait until InstallPlan is created]
deploy fail due to timeout with - TASK [install_operator : advanced-cluster-management - Wait until InstallPlan is created]
=> increase in rety acm install plan

ansible/configs/sap-smart/post_software.yml
Logic in sap-smart config for creating infra-ansible symlink must match AgnosticD logic to select the role install path.
=> Fix sap-smart infra-ansible symlink to reflect agnosticd install path logic

ansible/configs/sap-smart/post_software.yml
Last attempt duplicated `configs/sap-smart`.
=> Fix sap-smart usage of playbook_dir when determining roles path

ansible/configs/sap-smart/post_software.yml
Symlink must be created locally, not on the towers.
=> Fix roles symlink creation for sap-smart to create locally

ansible/roles/ocp4-workload-ccnrd-stable/templates/devfile.json.j2
Fix ocp4-workload_ccnrd-stable to fix the image tag
```paste below
```
=> Fix ocp4-workload_ccnrd-stable to fix the image tag

ansible/configs/ocp4-cluster/default_vars.yml, ansible/configs/ocp4-cluster/post_software.yml, ansible/roles/openshift_cluster_admin_service_account/.yamllint, ansible/roles/openshift_cluster_admin_service_account/README.adoc, ansible/roles/openshift_cluster_admin_service_account/defaults/main.yml, ansible/roles/openshift_cluster_admin_service_account/tasks/main.yml
Add ability to create a service account with cluster-admin privileges to ocp4-cluster config. By default this feature is disabled but may be enabled by setting `openshift_cluster_admin_service_account_create` to `true`.
- Config ocp4-cluster
- New role openshift_cluster_admin_service_account
```paste below
```
=> Add openshift_cluster_admin_service_account for ocp4-cluster config

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/gitea.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/defaults/main.yml
Make sure the user number is passed as an integer to Gitea. Also fix ODF CSV default prefix.
ocp4_workload_openshift_data_foundation
=> Add int to gitea

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/gitea.yaml.j2
The workload was missing a variable to pass the postgresql image to the operator. Fixed.
=> Add option to set Postgresql image

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/templates/kubevirt/datavolume.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/templates/kubevirt/vm.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/defaults/main.yml
StorageClass wasn't set properly for DataVolumes in KubeVirt. Fixed.
=> Fix datavolume storage class

ansible/configs/hybrid-cloud/pre_infra.yml
I accidentally called the azure subscriptions role twice.
Omitting the first.
```paste below
```
=> error in double role call - omit

ansible/configs/test-empty-config/post_software.yml, ansible/configs/test-empty-config/sample_vars.yml
Add ability to set `test_empty_config_passthrough_user_data` to have test-empty-config set arbirtary values in its user data.
=> Add test_empty_config_passthrough_user_data to test-empty-config

ansible/roles_ocp_workloads/ocp4_workload_rhacm_clusters/tasks/cluster_kconf.yml
I didn't see kconf_path used in any of the CIs we have now.
So disabling this seems fine.
```paste below
```
=> omit cluster specific kconf_path until really needed

ansible/roles_ocp_workloads/ocp4_workload_rhacm_clusters/templates/azure/install_config_azure.yaml.j2
ocp4_workload_rhacm_clusters - jinja2 for loop was failing.  Omitting.
```paste below
```
=> omit the jinja2 loop for azure zones

ansible/cloud_providers/ec2_destroy_env.yml, ansible/cloud_providers/ec2_infrastructure_deployment.yml, ansible/configs/hybrid-cloud/destroy_env_ec2.yml, ansible/configs/ocp4-cluster/destroy_env_ec2.yml, ansible/roles-infra/infra-ec2-ssh-key/tasks/create.yaml, ansible/roles/control-user/tasks/ssh-config.yml, ansible/roles/locate_env_authorized_key/readme.adoc, ansible/roles/locate_env_authorized_key/tasks/main.yaml, ansible/roles/set_env_authorized_key/tasks/main.yml, docs/SSH_keys_and_access.adoc
The `create_ssh_provision_key` infra role generates and store new SSH
key pair for each provisioning job. Plus setting following environment
variables:
- ssh_provision_pubkey_content
- ssh_provision_pubkey_path
- ssh_provision_key_path
- ssh_provision_key_name
In some cases this algorithm is not working well (e.g., the key pair can be lost
if not stored at persistent storage and destroy job will fail). This
change allow to bring your own permanent key by setting following
variables:
- ssh_provision_key_path
- ssh_provision_key_name
- ssh_provision_pubkey_content (optional)
And this provided key will be reused by provisioning and destroy jobs.
For example set following variables at AgnosticV:
```
ssh_provision_key_name: "my_private_ssh_key.pem"
ssh_provision_key_path: …
```
=> Add config to externally provide private SSH key used for provision and destroy at EC2

ansible/roles_ocp_workloads/ocp4_workload_managed_cluster_workload/tasks/workload.yml
ocp4_workload_managed_cluster_workload didn't have credentials to actually do that labs.
```paste below
```
=> add authn to managed cluster workload

ansible/lifecycle_ec2.yml
This change, if applied, fixes start and stop actions for EC2 (aws) when
there are Terminating or Terminated instances.
The error message is the following:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to change state for instance i-06641ecc4a23f3948, error: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>IncorrectInstanceState</Code><Message>This instance 'i-06641ecc4a23f3948' is not in a state from which it can be stopped.</Message></Error></Errors><RequestID>529e8468-0813-419c-b719-24bdbd34132a</RequestID></Response>"}
```
see GPTEINFRA-3798.
This happens because of a bug in the version of the aws collection that we use.
Since it's not easy to update the collection, this change uses another
approach to …
=> ec2: Fix lifecycle when there are terminated vm

ansible/roles_ocp_workloads/ocp4_workload_managed_cluster_workload/tasks/workload.yml
ocp4_workload_managed_cluster_workload could use let's encrypt.  Let's try.
```paste below
```
=> add lets encrypt to managed cluster

ansible/roles/ocp_cleanup_failed_pods/tasks/main.yaml
Start is broken because of that role.
Can we enable best-effort for that?
ocp_cleanup_failed_pod role
```paste below
```
=> ocp_cleanup_failed_pod: enable best effort mode

ansible/configs/rhel-container-security/requirements.yml
Fixes the following error:
```
TASK [infra-ec2-ssh-key : include_tasks] ***************************************
14:35:45
204
fatal: [localhost]: FAILED! => {"reason": "couldn't resolve module/action 'amazon.aws.ec2_key'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/tmp/awx_598475_a21j0zef/project/ansible/roles-infra/infra-ec2-ssh-key/tasks/create.yaml': line 9, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: Create infra key\n      ^ here\n"}
```
=> Add requirements.yml for rhel-container-security

ansible/roles_ocp_workloads/ocp4_workload_mta/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle/tasks/workload.yml
user.data was missing for MTA single-user workload 
```paste below
```
=> workload mta: add user data for single user

ansible/roles_ocp_workloads/ocp4_workload_retail_aiml_workshop/templates/object-detection-rest-pipeline.yaml.j2
Remove SSL Verify for the gitea repo
```paste below
```
=> Removed SSLVerify for gitea repo

ansible/roles_ocp_workloads/ocp4_workload_paloalto_prismacloud/tasks/workload.yml
Remove task -  Deploy the console to the cluster
```
Attempt to solve 
Error from server (AlreadyExists): error when creating \"/home/ec2-user/twistlock/twistlock_console.yaml\": persistentvolumeclaims \"twistlock-console\" already exists"],
https://tower.dark-tower-prod.infra.open.redhat.com/#/jobs/playbook/603537/host-event/302891412/json?job_search=page_size:20;order_by:-finished;not__launch_type:sync 
```
=> ocp4_workload_paloalto_prismacloud / tasks / workload.yaml

ansible/configs/test-empty-config/lifecycle_hook.yml
empty-config not creating any resource, the start/stop should just
ensure the connection to the cloud-provider is working
=> Create a hook for lifecycle for empty-config

ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/templates/applicationset.yaml.j2
Added workload to deploy Tackle2 to a cluster. Either for a single user or for multiple users.
This workload requires OpenShift Gitops to be installed - and the gitops controller service account to have cluster-admin permissions.
It depends on the following repos:
https://github.com/redhat-gpte-devopsautomation/agnosticd_workload_helm_charts
And this container image:
https://quay.io/repository/gpte-devops-automation/tackle2-setup
Source for the container image:
https://github.com/redhat-gpte-devopsautomation/tackle2-setup-container
ocp4_workload_mta_tackle2
=> Add Tackle2 workload

ansible/roles_ocp_workloads/ocp4_workload_mtv/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mtv/tasks/workload.yml
It takes a long time for the operator to report success on the forkliftcontroller installation. Optionally turn off waiting for success. Also fix wait condition (which seems to have changed recently).
ocp4_workload_mtv
=> Add a flag to omit waiting for MTV deployment, fix wait condition

ansible/roles_ocp_workloads/ocp4_workload_kubevirt/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/files/hyperconverged.yaml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/templates/hyperconverged.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/templates/applicationset.yaml.j2
When tainting nodes that should *only* run VMs the HyperConverged object needs to have a field .spec.workload.tolerations to set tolerations for the virt-handler daemon set to run on those nodes and make them available for VM scheduling.
This PR adds (optional) support to add workload tolerations to the HyperConverged custom resource.
=> Add support for tolerations for kubevirt workloads

ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/templates/storagecluster.yaml.j2
When Nodes are tainted ODF components don't get scheduled on those nodes.
Add optional support to add tolerations to all ODF components.
ocp4_workload_openshift_data_foundations
=> Added toleration support to ODF workload

ansible/roles/bastion-base/.yamllint, ansible/roles/bastion-base/README.adoc, ansible/roles/bastion-base/tasks/main.yml, ansible/roles/bastion-base/templates/bastion_ssh_config.j2
New very light bastion-base role
New role Pull Request
- removed redundant cruft seen in bastion-light (why helm on OSP or Ansible nodes?, jq etc -its a RHN package?)
- installs bastion specific base packages NOT common_packages
Designed to be called like this:
```
roles:
- bastion-base
- bastion-my-use-case-optimitations...
```
ansible/roles/bastion-base
```paste below
```
=> Created new bastion-base role, very light, minimal, with FQCNs

ansible/cloud_providers/osp_infrastructure_deployment.yml, ansible/configs/multi-cloud-capsule/infra_configs/osp_infrastructure_deployment.yml, ansible/configs/osp-migration/destroy_env.yml, ansible/configs/osp-migration/infra.yml, ansible/configs/osp-satellite-vm/destroy_env.yml, ansible/configs/osp-satellite-vm/infra.yml, ansible/lifecycle_osp.yml, ansible/roles-infra/infra-osp-dry-run/tasks/main.yml
Changing Openstack configs to use the "os_server_info" module instead of the openstack.cloud collection.
```paste below
```
=> Changing openstack ansible module to os_server_info

ansible/configs/sandbox/ec2_destroy_env.yml, ansible/configs/sandbox/ibm_destroy_env.yml
removed extra setup_runtimes from sandbox
sandbox
```paste below
```
=> removed extra setup_runtimes

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/applicationset.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/templates/applicationset.yaml.j2
Made Helm Charts for Code Server and Tackle2 more "helm compliant". Should facilitate better re-use.
Updated workloads to use the updated charts.
ocp4_workload_codeserver
ocp4_workload_mta_tackle2
ocp4_workload_ama_shared
=> Update workloads to use fixed helm charts

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/templates/kubevirt/applicationset.yaml.j2
With cpu not quoted there was a diff error in ArgoCD leading to out of sync status.
Fix by quoting cpu request.
=> Fix diff error in App Set for Ora DB

ansible/cloud_providers/gcp_infrastructure_deployment.yml, ansible/cloud_providers/gcp_ssh_config_setup.yml
re-add ssh config to ocp on gcp
gcp cloud provider
```paste below
```
=> re-add ssh config to ocp on gcp

ansible/configs/rhel-custom-security-content/requirements.yml
```paste below
TASK [infra-ec2-ssh-key : include_tasks] ***************************************
fatal: [localhost]: FAILED! => {"reason": "couldn't resolve module/action 'amazon.aws.ec2_key'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/tmp/awx_598475_a21j0zef/project/ansible/roles-infra/infra-ec2-ssh-key/tasks/create.yaml': line 9, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: Create infra key\n      ^ here\n"}
```
Similar to: #5111
=> Add requirements.yml file to rhel-custom-security-content config.

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/templates/apps/application.yaml.j2
AMA Demo did not have the IP Address of the Tomcat VM configured.
Fixed.
=> Add customers Host configuration

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/per_user_workload.yaml
rhjcd-patch-add retries to workload for upload task
```paste below
```
=> add retries to workload for upload task

ansible/configs/ocp4-equinix-aio/requirements.yml
Bumps requirement for the base_software component to get the latest version that provides a mirrorlist for the openstack-victoria repo instead of a wonky baseurl that was failing some deployments
CNV Lab
=> Ocp4 aio cnvlab

ansible/configs/ocp4-cluster/default_vars_ec2.yml, ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
OCP 4.11 Installer now checks if the rootVolume.storage.size is set. This has been a required variable since at least 4.6 - but it hasn't been checked so far.
Adding a default rootVolume for AWS for 100 (Gigabytes).
ocp4-cluster
=> Fix missing storage size on AWS

ansible/roles/ocp4_machineset_config/defaults/main.yml, ansible/roles/ocp4_machineset_config/tasks/disable-base-worker-machinesets.yml, ansible/roles/ocp4_machineset_config/tasks/enable-cluster-autoscaler.yml, ansible/roles/ocp4_machineset_config/tasks/machineset-group-aws.yml, ansible/roles/ocp4_machineset_config/tasks/machineset-group-openstack.yml, ansible/roles/ocp4_machineset_config/tasks/set-facts.yml, ansible/roles/ocp4_machineset_config/templates/machineset-aws.j2, ansible/roles/ocp4_machineset_config/vars/main.yml
providerSpec changed for MachineSets in OCP 4.11.
Adding support for 4.11 while supporting existing versions.
Changed check for apiVersion to check for Kind. This unifies AWS and OSP code.
Add support for storage type for AWS (e.g. gp3 instead of gp2).
ocp4_machineset_config
=> Add support for OCP 4.11 to MachineSet role

ansible/roles-infra/infra-aws-open-environment/defaults/main.yaml
Fix bug caused by lack of default for sandbox_enable_ui.
Role infra-aws-open-environment
=> Add default for sandbox_enable_ui

ansible/configs/ansible-automation-platform/env_vars.yml, ansible/configs/ansible-automation-platform/files/hosts_template.j2, ansible/roles/aap_deploy/defaults/main.yml, ansible/roles/aap_deploy/templates/automationcontroller_inventory.j2
Add execution nodes optionally to AAP config
Allows to decide if the control nodes are hybrid or only control.
configs/ansible-automation-platform
roles/aap_deploy
It is required for Summit Connect 2022 because we found out that the deployment of a single execution node takes too long during a lab (30 minutes out of 2 hours!). Linked to https://github.com/redhat-gpe/agnosticv/pull/6414
=> Add execution nodes optionally to AAP config

ansible/roles-infra/infra-aws-open-environment/defaults/main.yaml, ansible/roles-infra/infra-aws-open-environment/tasks/print_user_info.yaml
Add defaults for `sandbox_user_info_data_enable` and `sandbox_user_info_messages_enable` to role `infra-aws-open-environment`.
Role infra-aws-open-environment
=> Add user info default vars for infra-aws-open-environment

ansible/configs/ansible-automation-platform/env_vars.yml, ansible/roles/vscode-server/defaults/main.yml
Redirect vscode server download to GPTE S3
This can avoid DoS blocking from GitHub, especially when doing mass deployment.
code-server role
Necessary for Summit connect 2022
=> Redirect vscode server download to GPTE S3

ansible/roles-infra/infra-equinix-metal-resources/tasks/delete_project.yaml
Use project id when destroying an Equinix Metal project
```paste below
```
=> Use project ID instead of name when destroying

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/dev-module-guides-install.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/dev-username-distribution-install.yml
Fix ocp4_workload_ama_demo_shared for the vscode URL and add namespace param
```paste below
```
=> Fix ocp4_workload_ama_demo_shared for the vscode URL and add namespace param

ansible/roles/bastion-base/tasks/main.yml
Changes the module used for the installation of bastion packages from DNF to Package in the event of using older version of RHEL.
roles/bastion-base/tasks/main.yml
```paste below
```
=> Update bastion-base roll to be inclusive

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml
Apparently OpenShift gitops does not require pipelines any more. Removing check.
=> Remove check for pipelines

ansible/roles/ocp4-workload-workshop-admin-storage/defaults/main.yml, ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
The OCP4 Admin/Storage workshop got some updates for 2022, which requires a new workshop definition file. This change to the role adds a variable which will support overriding which workshop file to load via AgnosticV.
Technically this is a role modification and not much of a new feature.
=> Adds default workshop file var (for later override)

ansible/configs/containerize-app-demo/default_vars_ec2.yml
Updating security groups for bastion to allow 8080
```paste below
```
=> Containerize App Demo, Updating Security Groups

ansible/roles-infra/infra-azure-create-inventory/tasks/main.yml, ansible/roles/agnosticd_save_output_dir/tasks/create-output-dir-archive.yml
This change, if applied, fixes the error:
```
TASK [infra-azure-create-inventory : Build inventory] **************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'env_authorized_key_path' is undefined\n\nThe error appears to be in '/tmp/awx_689835_k7s97kyq/project/ansible/roles-infra/infra-azure-create-inventory/tasks/main.yml': line 50, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Build inventory\n  ^ here\n"}
```
see GPTEINFRA-4132
The key doesn't have to be saved per host, as the ssh config is generated and we populate a section for each host.
Tested in Execution environment ee-multicloud:v0.0.6
=> azure: do not define ssh key file per host

ansible/roles/user-create-ansible-service-account/tasks/main.yml
This section was breaking lab deployments that did not have need of specific python versions to be installed. This update is to remove that as a requirement.
user-create-ansible-service-account
```paste below
```
=> Update service_account_role, conditonal to turn off python install

ansible/configs/convert-to-rhel/default_vars.yml
Adding variable to stop service account from attempting to install python.
```paste below
```
=> Convert to RHEL add option to remove python install

ansible/roles/ocp-workload-migration/templates/operator.yml.j2, ansible/roles/ocp4-workload-migration/defaults/main.yml
Due to the removal of older versions of operator from the operator hub, the lab is failing to deploy. 
This PR updates the versions to the most recent ones. 
agnoticd roles: 
- ocp-workload-migration
- ocp4-workload-migration
=> BUGFIX - Migration Toolkit for Containers OCP4 Lab

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/defaults/main.yaml
ama shared demo workload had confusing defaults for the lab guides.
Removing defaults (which on top of being confusing were just wrong).
Set values now in AgnosticV (already there).
=> Remove confusing defaults. Set in AgnosticV as per environment.

ansible/roles_ocp_workloads/ocp4_workload_pipelines/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
Change openshift-pipelines workload to download tkn from cluster instead of the internet. Remove now obsolete variables.
=> Change pipelines logic to download from cluster

ansible/cloud_providers/gcp_infrastructure_deployment.yml, ansible/configs/ocp4-cluster/destroy_env_gcp.yml, ansible/configs/ocp4-cluster/files/cloud_providers/gcp_cloud_template.j2, ansible/configs/ocp4-cluster/post_software.yml, ansible/roles-infra/infra-gcp-template-destroy/tasks/main.yml
update the way the bastion hostname is figured out
ocp4-cluster
```paste below
```
=> update the way the bastion hostname is figured out

.gitignore, ansible/configs/just-a-bunch-of-nodes/default_vars.yml, ansible/configs/just-a-bunch-of-nodes/default_vars_equinix_metal.yml, ansible/configs/just-a-bunch-of-nodes/pre_software.yml, ansible/configs/ocp4-equinix-aio/default_vars_equinix_metal.yml, ansible/roles/bastion-lite/defaults/main.yml, ansible/roles/bastion-lite/tasks/main.yml, ansible/roles/bastion-lite/templates/bastion_ssh_config.j2
This change, if applied, remove the dependency of env_authorized_key for
the bastion-lite role.
Instead, generate an SSH key on the bastion and use that to allow the
root@bastion user to ssh to any host.
That makes the bastion-lite role cloud-agnosticd.
- tested with just-a-bunch-of-nodes on equinix and AWS
- generate a key on the bastion and use that to setup additional access
to all the hosts.
The additional access is for the users when they ssh to the bastion:
```
ssh bastion...
sudo -i
ssh node1.GUID.internal
```
- bastion-lite role
- just-a-bunch-of-nodes  config, equinix, ec2
tested using ee-multicloud:v0.0.7
=> bastion-lite: Remove env_authorized_key dependency

ansible/configs/ocp4-cluster/post_software.yml
fix bad var check in ocp4 cluster
ocp4-cluster
```paste below
```
=> fix bad var check in ocp4 cluster

ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/templates/code-server.service.j2
Enable a custom system service for code server on the bastion to allow for podman commands.
=> Enable custom system service for code server on bastion

ansible/roles/locate_env_authorized_key/tasks/main.yaml
This change, if applied, fixes the error:
```
fatal: [localhost -> localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ssh_provision_key_name'\n\nThe error appears to be in '/tmp/awx_784394_ybsdlu5a/project/ansible/roles/locate_env_authorized_key/tasks/main.yaml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set env_authorized_key_path_pub\n  ^ here\n"}
```
=> locate_env_authorized_key: fallback to old var

ansible/roles-infra/infra-azure-create-inventory/tasks/main.yml, ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml, ansible/roles/open-env-azure-create-open-env/tasks/main.yml
add validation if the resource group is already deleted
ocp4 on azure
```paste below
```
=> add validation if the resource group is already deleted

ansible/roles/install_operator/tasks/install.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
Update some retry counts to not fail when installing in APAC and pulling images takes a long time.
=> Updated timeouts

ansible/roles_ocp_workloads/ocp4_workload_gitops_workshop/templates/argocd_cr.yaml.j2
Added the ability to add more non defaults to argocd CR like:
```yaml
ocp4_workload_openshift_gitops_argo_cr_additional_values: |
resourceTrackingMethod: annotation
```
Adjust ocp4_workload_openshift_gitops
nothing
=> Introduce ocp4_workload_openshift_gitops_argo_cr_additional_values

.github/workflows/asciidoc.yml
tonynv/asciidoctor-action has been renamed, use new name of a fork instead.
=> Use our own fork for asciidoctor-action

ansible/configs/containerize-app-demo/post_software.yml
redhat_subscription module not working on RHEL 9, reverting to command
```paste below
```
=> Containerize App Unregister

ansible/configs/rosa/destroy_env.yml
```
TASK [Destroy ROSA Cluster] ****************************************************
fatal: [bastion.tn6q6.internal]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/rosa", "delete", "cluster", "-y", "--cluster=rosa-tn6q6"], "delta": "0:00:02.335637", "end": "2022-09-30 03:33:22.355779", "msg": "non-zero return code", "rc": 1, "start": "2022-09-30 03:33:20.020142", "stderr": "ERR: There is no cluster with identifier or name 'rosa-tn6q6'", "stderr_lines": ["ERR: There is no cluster with identifier or name 'rosa-tn6q6'"], "stdout": "", "stdout_lines": []}
```
see GPTEINFRA-4538
- config/rosa
=> rosa: fix fail destroy when cluster doesn't exist

ansible/configs/ocp4-cluster/files/requirements_k8s.txt
New release of 22.1.0 is incompatible our version of python or ansible.
Config ocp4-cluster.
=> Add explicit version of pyOpenSSL for ocp4-cluster config

ansible/roles-infra/create_ssh_provision_key/defaults/main.yaml, ansible/roles-infra/create_ssh_provision_key/tasks/main.yaml
Add `create_ssh_provision_key_enable_user_info_data` flag to the `create_ssh_provision_key` role to have it report the generated SSH private key in user info data. Defaults to `false`.
Role `create_ssh_provision_key`
=> Add create_ssh_provision_key_enable_user_info_data flag

ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
Increase wait for tkn-cli-serve in ocp4_workload_pipelines from 6m40s to 30m. Investigation of a recent failure showed that the deployment became ready around 20m after the failure. Not sure why it takes so long, but better to wait a bit longer than to fail.
Role ocp4_workload_pipelines
=> Increase ocp4_workload_pipelines wait for tkn-cli-serve

ansible/roles_ocp_workloads/ocp4_workload_opentour_dach_2022/defaults/main.yaml
Update ocp4_workload_opentour_dach_2022 role defaults to reference variables used by ocp4_workload_authentication.
Role ocp4_workload_opentour_dach_2022
=> Update ocp4_workload_opentour_dach_2022 user default vars

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
Fix `ocp4_workload_gitea_operator` use of `ocp4_workload_gitea_operator_generate_user_format` in user info.
Role ocp4_workload_gitea_operator
=> Fix ocp4_workload_gitea_operator user name format

ansible/roles_ocp_workloads/ocp4_workload_servicemesh/tasks/install_jaeger_operator.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh/tasks/install_kiali_operator.yml, ansible/roles_ocp_workloads/ocp4_workload_servicemesh/tasks/install_servicemesh_operator.yml
Race condition made it possible to fetch install plan before a status was set on it.
Role ocp4_workload_servicemesh
=> Add check in ocp4_workload_servicemesh for status.phase

ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/workload.yml
It will be common in labs to require the cluster ingress domain in the per-user information.
=> Add setting openshift_cluster_ingress_domain in ocp4_workload_authentication

ansible/roles-infra/infra_osp_lifecycle/tasks/get-servers.yml
VMs created outside of the stack is most probably they don't have the correct tags, so the VMs are never stopped.
=> Remove filters for server_info module

ansible.cfg
Set any_errors_fatal to prevent ansible execution from continuing after error.
ansible.cfg
=> Add any_errors_fatal to ansible.cfg

ansible/configs/sap-integration/files/requirements_k8s.txt
rhjcd-patch-remove cryptography from k8s reqs file per https://issues.redhat.com/browse/GPTEINFRA-4302
```paste below
```
=> remove cryptography from k8s reqs file

ansible/roles/host-ocp4-installer/tasks/main.yml
When the OCP4 installer fails, there is a `always` ansible block to fetch the installer log.
This change, if applied, adds a step to run the `agnosticd_save_output_dir` role so the installer logs will be found in the outputdir archive for our production environments when this happens.
- host-ocp4-installer role
=> Save output dir to s3 when OCP4 installer fails

ansible/configs/satellite-hackfest/pre_software.yml
This PR removes the fully qualified collection name from legacy deployment.
```paste below
```
=> satellite-hackfest remove ansible.builtin fqcn

ansible/configs/satellite-hackfest/setup_lab_user.yml
Copy module was using src where content was appropriate.
```paste below
```
=> satellite-hackfest ssh key content

ansible/roles/agnosticd_save_output_dir/tasks/main.yml
Have `agnosticd_save_output_dir` always run on localhost with `run_once`.
Role `agnosticd_save_output_dir`
=> Set run_once and delegate to localhost for agnosticd_save_output_dir

ansible/configs/satellite-hackfest/pre_software.yml
This update changes the role order so that it is not accidentally overwritten by another role,
```paste below
```
=> satellite-hackfest update pre_software role order

ansible/roles/host-ocp4-installer/defaults/main.yml, ansible/roles/host-ocp4-installer/tasks/print_cluster_info.yml
Add `host_ocp4_installer_set_user_data_kubeadmin_password` variable to have host-ocp4-installer role report the kubeadmin password as `agnosticd_user_info` data. Defaults to false.
Role host-ocp4-installer.
=> Add variable to have ocp4-host-installer report kubeadmin password

ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/templates/applicationset.yaml.j2
The workload was hardcoded to Tackle2 channel `stable-v2.0`. Added support to use newer versions as well as matching seed pods.
Defaults are the current behaviour.
ocp4_workload_mta_tackle2
=> Add support for newer Tackle2 versions

ansible/configs/sap-smart/default_vars.yml
Add generate passwords for sap-smart config. The value for `tower_password` and `master_sap_password` should be generated dynamically and stored in the output directory.
=> Add generate passwords for sap-smart config

ansible/configs/ansible-multitier-rhel8/files/cloud_providers/ec2_cloud_template.j2
Update ansible-multi-tier-rhel8 template to use new key name var.
ansible-multitier-rhel8
```paste below
```
=> ansible-multitier-rhel-8 update key_name var

ansible/configs/ansible-multitier-rhel8/default_vars_ec2.yml
Update ssh key variable in node dictionary
ansible-miltitier-rhel8
```paste below
```
=> ansible-multitier-rhel8 update ssh key var

ansible/configs/ansible-multitier-rhel8/default_vars.yml
Updates env_authroized_key var
ansible-multitier-rhel8
```paste below
```
=> ansible-multitier-rhel8 update env_auth_key

ansible/roles/install_operator/tasks/install.yml
The jquery to wait for installplan was always true. So that meats it doesn't wait on the installplan. Useally it fails later the the "Wait for CSV" stept becasuse if scipts also the installplan approval. No Approved installplan -> no csv... Installation fails.
The fixed based on
ansible/roles_ocp_workloads/ocp4_workload_servicemesh/tasks/install_servicemesh_operator.yml, line 15:
```
- name: Wait until InstallPlan is created k8s_info: api_version: operators.coreos.com/v1alpha1 kind: InstallPlan namespace: openshift-operators register: r_install_plans vars: _query: >- [?starts_with(spec.clusterServiceVersionNames[0], 'servicemesh') && status.phase] retries: 30 delay: 5 until:
- r_install_plans.resources | length > 0
- r_install_plans.resources | to_json | from_json | json_query(_query)
``` …
=> Fixed jquery to wait for InstallPlan is created

ansible/roles/automation-controller-config/tasks/job_workflow_template.yml
Add retries to automation-controller-config-job role to attempt to deal with sporadic 403 errors we have encountered after workflow template creation.
Role automation-controller-config-job
=> Add retries to automation-controller-config-job workflow launch

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/get_cluster_credentials.yml
Added logic to HyperShift workload to write kubeconfig and kubeadmin password to /home/{{ student_name }}/.kube.
=> Write kubeconfig and password to file

ansible/configs/ibm-rhoic/default_vars.yml
Upgrading RHOIC OCP 4 minor version from 7 to 11
IBM_RHOIC
Requesters are complaining that the RHOIC version is too old. I have confirmed in the IBM UI that 4.11 is supported, but there is no option to select that as it appears to be hardcoded currently.
```
=> RHOIC version is currently hardcoded at 4.7 - need to upgrade to 4.11

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/templates/openshift-gitops.yaml.j2
Turns out the App Mod catalog items break the application controller for the system ArgoCD for higher numbers.
This PR adds the capability to update the requests/limits for individual argocd components.
=> Add variables to customize resources for the system ArgoCD

ansible/roles/agnosticd_save_output_dir/tasks/main.yml, ansible/roles/agnosticd_save_output_dir/tasks/save-output-dir.yml
Remove use of `delegate_facts` in `agnosticd_save_output_dir` role. `set_fact` does not work with `delegate_facts`.
Role agnosticd_save_output_dir
=> Fix delegate_facts issue in agnosticd_save_output_dir

ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/applicationset.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle2/templates/applicationset.yaml.j2
Tags need quotes around them to prevent 1.0 becoming 1 - and resulting in ImagePull errors.
ocp4_workload_mta_tackle2
ocp4_workload_codeserver
=> Image tags need quotes to prevent tag manipulation

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/get_cluster_credentials.yml
Secret location for hypershift credentials moved in the latest operator update...
=> Fix location of secrets for hypershift

docs/SSH_keys_and_access.adoc
* add section about `output_dir` storage which is important for SSH access as the output_dir is not persistent in Tower and Controller.
See GPTEINFRA-4470
SSH Doc
=> SSH doc: Add deprecated vars and roles

ansible/roles/open-env-azure-invite-user/tasks/main.yml
update azure invite user to use new RH cicd user
open-env-azure-invite-user
```paste below
```
=> update azure invite user to use new RH cicd user

ansible/roles/ocp4_machineset_config/README.adoc, ansible/roles/ocp4_machineset_config/defaults/main.yml, ansible/roles/ocp4_machineset_config/tasks/machineset-group-aws.yml, ansible/roles/ocp4_machineset_config/templates/machineset-aws.j2, ansible/roles/ocp4_machineset_config/vars/main.yml, ansible/roles_ocp_workloads/ocp4_workload_machinesets/defaults/main.yml
When creating MachineSets with disk type io1 it is necessary to specify the iops for that disk as well.
This PR adds that variable to the MachineSet Group definition and the role implementing that.
ocp4_machineset_config
ocp4_workload_machinesets
=> Add support for machinesets on AWS to specify iops for disks

ansible/roles_ocp_workloads/ocp4_workload_mta6/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta6/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta6/templates/applicationset.yaml.j2
MTA6 is now a Red Hat Operator. Add support to use a catalogsource snapshot for deploying the operator.
ocp4_workload_mta6
=> Add support for catalogsnapshots to MTA6 workload

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/templates/clusterrolebinding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/templates/job.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/templates/namespace.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops_fix_argocd/templates/serviceaccount.yaml.j2
Sometimes ArgoCD DEX servers can't connect to the OpenShift API - and then users can not login. Fix is to just restart every argocd-dex-server pod on the cluster.
Also sometimes the OpenShift GitOps repo server pod has locks in its ephemeral storage that prevent rollout of all applications. Fix is to restart that pod as well.
This workload deploys a job that does all that.
ocp4_workload_openshift_gitops_fix_argocd
=> Add new workload to fix argocd deployments

ansible/roles/ocp4_workload_stackrox_demo_apps/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_hands_on_rhacs/tasks/workload.yml
1. This role calls the role ocp4_workload_stackrox_demo_apps, the network anomaly task is not needed for RHACS 3.72, as confirmed with SME mfoster
2. this role is running deployments from Googlecloudplatform repo, they have changed their manifests in their repo, hence our CI is breaking. I have made changes so that the working version of the manifest is used in our CI. Coincidentally these change happened last night and our monitoring system has this ticket https://gpte.statuspage.io/incidents/9yv4kn3wv5yw
This PR will fix this issue too.
role ocp4_workload_hands_on_rhacs
```paste below
```
=> Change role ocp4_workload_hands_on_rhacs to match API requirements of RHACS 3.72.1

ansible/roles-infra/infra_osp_lifecycle/tasks/get-servers.yml
Use same variable name as infra-osp-create-inventory role
Try to fix the lifecycle error:
```
'r_osp_facts' is undefined
```
Can't test locally, need someone to test this code.
=> infra_osp_lifecycle: Use consistent variable name

ansible/cloud_providers/osp_infrastructure_deployment.yml
Add delay for OSP linux to allow router table and OVN to sync FIP (7 minutes hardcoded)
ansible/cloud_providers/osp_infrastructure_deployment.yml
High Failure rate due to FIP inaccessible on OSP VM's, but manual connection works almost immediately.
```
=> We're having issues with the FIP not being accessible in OSP

ansible/configs/osp16-concepts-architecture/files/cloud_providers/osp_cloud_template_master.j2
Before Jinja 2.10 the [indent parameter was called indentfirst](https://github.com/pallets/jinja/blob/c9593aa388a04ca6a1a15a4436269f762c36a7b5/src/jinja2/filters.py#L797).
=> Change indentfirst to indent

CODEOWNERS
following up on #5674
Billy knows how to test the images filters and is able to maintain that file.
=> Add Billy to manage AWS image definitions

ansible/configs/osp16-concepts-architecture/files/cloud_providers/osp_cloud_template_master.j2
Before Jinja 2.10 the [indent parameter was called indentfirst](https://github.com/pallets/jinja/blob/c9593aa388a04ca6a1a15a4436269f762c36a7b5/src/jinja2/filters.py#L797).
=> Wrong parameter for indent

ansible/roles_ocp_workloads/ocp4_workload_le_certificates/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_le_certificates/tasks/workload.yml
Add `ocp4_workload_le_certificates_failure_is_fatal` flag to `ocp4_workload_le_certificates` workload.
Role `ocp4_workload_le_certificates`
=> Add option to ocp4_workload_le_certificates to not fail on error

ansible/configs/osp16-concepts-architecture/pre_infra.yml
migration_host_ansible_ssh_private_key_content will contain the private key, encrypted using ansible-vault
=> Introduce new private var for migration host

ansible/configs/ansible-middleware-workshop/README.adoc, ansible/configs/ansible-middleware-workshop/default_vars.yml, ansible/configs/ansible-middleware-workshop/default_vars_ec2.yml
These changes allow the installation of lets encrypt certs on the frontend server as part of the workshop.  It comprises of the installation of the socat library which is required by letsencrypt standalone mode and opening port 80 in the frontend security group.
=> Update to allow letsencrypt cert to be installed on frontend server

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/templates/openshift-gitops.yaml.j2
Changed system ArgoCD route TLS configuration to use edge instead of reencryopt - which caused problems.
=> Change route to edge for system argocd

ansible/roles/host-ocp4-installer/tasks/print_cluster_info.yml
Print kubeadmin user password from `host-ocp4-installer` when also storing it as user info.
Role `host-ocp4-installer`
=> Add user info message for kubeadmin password

ansible/action_plugins/agnosticd_user_info.py
Put per-user messages generated by `agnosticd_user_info` in the result object so that it can be recover from the event log.
`agnosticd_user_info` action plugin
=> Capture per-user agnosticd_user_info messages in result

ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/remove_workload.yml
Make destroy of Hypershift clusters more robust (especially in case where the provision failed).
=> Add base domain and ignore errors to destroy

ansible/roles_ocp_workloads/ocp4_workload_le_certificates/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_le_certificates/tasks/workload.yml
This change removes a hardcoded wait time on ocp4_workload_le_certificates role in favor of configurable one, with default being set to previously hardcoded value. Sleep is there to allow kube-apiserver employ the new certificates, but in specific conditions a time longer than 12 minutes may be needed for the things to settle down.
ocp4_workload_le_certificates role
```paste below
BEFORE:
TASK [ocp4_workload_le_certificates : Wait 12m for all APIservers to be back up] ***
Pausing for 1200 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
AFTER:
TASK [ocp4_workload_le_certificates : Wait for some time for all APIservers to be back up (default 12 minutes)] ***
Pausing for 2000 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
```
=> [ocp4_workload_le_certificates] Change wait time to be configurable instead of a hardcode

ansible/configs/ocp4-equinix-aio/requirements.yml
Include a patch from Alberto to prevent issues with VM first boot / OCP install
=> include Alberto VM Boot patch

ansible/roles_ocp_workloads/ocp4_workload_gitops_workshop/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_workshop/templates/argocd_cr.yaml.j2
Modifies the configuration of the user Argo CD instances for this workshop as follows:
- Uses edge termination instead of passthrough so it will use the wildcard TLS certificate, avoids problem of users having to accept a private certificate
- Adds RBAC to enable logging into Argo CD using the OpenShift credential instead of requiring users to lookup the Argo CD certificate
- Adds RBAC to all instances for the opentlc-mgr user so the workshop owner can easily assist users with problems.
- Disables login via the secret to avoid confusion
Changes to ocp4_workload_gitops_workshop role to support the OpenShift GitOps workshop
Additional changes required in Workshop material, only merge into development for now (i.e. no test or prod environments)
=> Use cluster TLS and add Argo CD RBAC for workshop user to each instance

ansible/configs/ocp4-cluster/requirements.yml
- Update ocp4-cluster config requirements.yml to update amazon.aws collection from 2.2.0 to 5.2.0 to fix issue with community.aws 4.1.1.
- Sort requirements.yml content.
=> Update ocp4-cluster requirements amazon.aws to 5.2.0

ansible/roles-infra/infra-vmc-resources/tasks/delete_instances.yaml
When a provision fails, the cleanup was not deleting the project because the folder was empty.
=> [infra-vmc-resources] Delete project even if is empty.

ansible/configs/ocp4-equinix-aio/requirements.yml
Bumping requirements to enhance security (bastion host now gets upgraded before being started to make sure we avoid any OpenSSH CVEs) and 4.12 compatibility (update in instructions) 
- Security fix Pull Request
- 
Fixed lots of instructions due to changes in 4.12' CNV
Trying to get the whole env more secure to avoid issues with Equinix sec team
=> [Equinix-AiO] bumping requirements for 4.12 support

ansible/roles-infra/infra-vmc-resources/tasks/create_instance.yaml
Add retries to infra-vmc-resources role to adapt to vcenter API timeout issues.
Role infra-vmc-resources
=> Add retries to infra-vmc-resources

ansible/filter_plugins/core.py, ansible/filter_plugins/tests/test_core.py, ansible/install_collections_ee.yml, ansible/install_galaxy_roles.yml
This change, if applied, updates the install_galaxy tasks to skip collections that are already installed when running in an execution environment.
- Always Prefer the collections baked in the EE.
- Add a WARNING when conflicts exist
- install the missing collections
Create a jinja2 filter agnosticd_filter_out_installed_collections() for plumbing.
- core install_galaxy playbook
This change should only impact when running ansible using an execution environment.
Tested with `ee-multicloud:v0.0.9`
=> Skip installing existing collections when using EE

.github/workflows/build-ee-dispatch.yml, .github/workflows/build-ee.yml
The branch / tag is already automatically present in the Workflow dispatch form, no need to add it in the workflows.
=> build-ee-dispatch: remove redundant input

ansible/roles-infra/infra-ec2-template-create/tasks/detect_custom_images.yml
Rename deprecated ec2_ami_facts to its alias ec2_ami_info.
- [infra-ec2-template-create/tasks/detect_custom_images.yml](https://github.com/redhat-cop/agnosticd/compare/jbon-ee-fix?expand=1#diff-780ac3766ca42bd7c29497083b8f469ab357e8eea7f7bc374ee374d08b2219eb)
tested with `ee-multicloud:v0.0.10`
=> Rename deprecated ec2_ami_facts

ansible/install_galaxy_roles.yml
Fix bug in AgnosticD core that fails on collection installation within execution environment when no collections are required.
AgnosticD Core
=> Fix handling of requirements without collections

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
Fixes an error where the hypervisor public IP was not gathered.
Adds an extra verification to make sure sushy-tools are running before launching cluster deployment.
```paste below
```
=> Fixes for ocp4_workload_5gran_deployments_lab role

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml
Fixes an issue with a wait being done with the k8s_info module that sometimes fails to wait for the pod to be ready.
```paste below
```
=> Fixes a bug on argocd wait for role ocp4_workload_5gran_deployments_lab

ansible/configs/ocp4-equinix-aio/post_software.yml, ansible/configs/ocp4-equinix-aio/requirements.yml
Adding dynamically passed vars from the roles to the CNV Lab + fixing the lab for 4.12
Allows to get the generated root password in the bookbag instructions as well as the openshift console URL and kubeadmin password 
Fixes lab instructions for Openshift Virtualization 4.12
=> Adding dynamic vars to cnvlab

ansible/roles/ocp4-workload-workshop-admin-storage/defaults/main.yml, ansible/roles/ocp4-workload-workshop-admin-storage/files/production-cluster-admin.json
Update the Openshift Template to `template.openshift.io/v1` from just `v1` to fix deployment errors on Admin Storage Workshop.
ocp4-workload-admin-storage
=> Fix OpenShift Template apiVersion

ansible/roles_ocp_workloads/ocp4_workload_gitops_workshop/tasks/workload.yml
Adds back the web-terminal operator that was removed for troubeshooting. In an attempt to workaround install_operator not checking the operator properly we pre-install the devworkspace-operator first.
```paste below
```
=> Add web terminal operator back and preinstall devworkspace-operator

ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/workload.yml
Modernized the ODF workload. Updated all the modules. General cleanup.
Updated the way to label worker nodes.
Updated the logic to remove the default from existing storage classes - this was broken on OCP 4.12.
ocp4_workload_openshift_data_foundation
=> Update ODF workload to properly remove default storage classes

ansible/configs/aap2-ansible-workshops/vars/automate_smart_mgmt_vars.yml
rhjcd-patch-add ami block per @heatmiser 
add a new block section to the automate smart management var file for accessing the required ami's
aap2-ansible-workshop ami block for automate_smart_mgmt_vars.yml
=> add ami block per msavage

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-tomcat-vm.yml
On the new oVirt platform it is necessary to specify `follow` to get details about the NICs. Added to all workloads that use oVirt.
=> Add follow to tasks to get ovirt NICs

ansible/roles_ocp_workloads/ocp4_workload_mta6/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta6/templates/tackle.yaml.j2
This is just for the single user operator install, without argo application(set).
https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/6.0/html/release_notes/mta-6-0-1
=> Add rwx_supported to mta6

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
SUMMARY
Adds extra checks:
- When installing sushy-tools a restart is required if it is going to be executed twice.
- Disables firewalld since it is mandatory to be disabled. If I am right, firewalld, it is not enabled by default in RHPDS but anyway just in case it is enabled later on.
- Updating the commid id for an external repo we are using.
- Mounting an extra disk on /var/lib/libvirt since the installation by default does not allow selecting the proper disk size for the root filesystem. Since we are running multiple VMs the /var/lib/libvirt folder it gets exhausted easily. The task selects a disk > 500GB which is not in use.
- Adds a wait for the registry to be running before trying to log into it.
ISSUE TYPE
COMPONENT NAME …
=> Adds sushy restart, firewalld disabled and new commit id for kcli gh

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-user.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-user.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-user.yml
To troubleshoot Tomcat VMs sometimes it's necessary to shutdown/start the VMs. This PR adds permissions to the created user to manipulate the Tomcat VM in addition to the Oracle VM.
ocp4_workload_ama_mad_roadshow
=> Allow users to also manage Tomcat VM

ansible/roles_ocp_workloads/ocp4_workload_starburst/templates/starburst-secret.j2
Depending on how the value for `starburst_license` is included Ansible may spontaneously convert the string to a dictionary/mapping because it is JSON structured data within the string. To handle this case we must test the data type before determining if the `to_json` filter will be required.
Also, it is best to used a secret's `data` field with `b64encode` rather that `stringData` as encoding removes any potential issues with newlines in the generated YAML.
Role ocp4_workload_starburst
=> Fix starburst-secret to handle automatic data conversion

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-tomcat-vm.yml
Query for NIC would fail occasionally when executed too quickly. Fixed check by defaulting to an empty array if nothing was returned.
Also added task to check for the Oracle Database to be up and running before continuing. This prevents Tomcat VMs from being created that can't connect to the database.
=> Fix check for oVirt VM IPs - and check for running database

ansible/configs/expanding-workload-rhel/image_builder_repos.yml, ansible/configs/expanding-workload-rhel/pre_software.yml
This PR will satisfy the requirements of building an on premise cockpit driven image-builder integrated with a satellite.
```paste below
```
=> Add image builder configuration to Wxpand your workload to the cloud CI

ansible/configs/expanding-workload-rhel/image_builder_repos.yml
This update resolves issues with osbuild-composer
```paste below
```
=> update playbook for dynamic reading of repos

ansible/configs/sandbox/default_vars_vmc.yaml, ansible/configs/sandbox/post_software_vmc.yml
If the the option in the CI is enabled, api.apps.domain and *.apps.domain will be created
=> [SANDBOX VMC] Add the option to create DNS for OCP

ansible/configs/ent-demo-ate-base/post_software.yml
Simply an incorrect var in config ent-demo-ate-base - changed to `subdomain_base_suffix`
config ent-demo-ate-base
=> Fix var typo subdomain_base_suffix ent-demo-ate-base

ansible/roles-infra/infra-ec2-template-destroy/defaults/main.yaml, ansible/roles-infra/infra-ec2-template-destroy/tasks/main.yml
Do not fail on cloudformation errors when in sandbox.  The account will be nuked anyway and this failure just hangs up deletion.
roles-infra/infra-ec2-template-destroy
```paste below
```
=> Do not fail on cloudformation errors when in sandbox

ansible/configs/sap-smart/default_vars.yml
Deleted extra @ in default_vars.yaml
```paste below
```
=> Fixed typo in sap-smart config

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/rhods/odh-dashboard-config.yaml.j2
Adjustment of RHODS configuration for the MAD Dev module 6. Default notebook size is now smaller to consume less resources on the cluster.
Not a real bugfix, simply a configuration adjustment to consume less resources.
=> guimou-mad-dev-rhods-adjust

ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/setup_htpasswd.yml
AgnosticD user info was missing the number of provisioned users. Added to the output.
=> user info was missing number of provisioned users

ansible/roles-infra/infra-images/defaults/main.yaml
Add RHEL GOLD versions supported in labsat to supported list
infra-images
```paste below
```
=> Update infra-images with supported RHEL8
