redhat-cop/agnosticd

- ansible/configs/bu-workshop/cleanup.yml
- ansible/configs/bu-workshop/ssh_vars.yml
- ansible/main.yml
This brings back using an SSH config file for accessing hosts through the bastion. However, it creates the file in `workdir` and then (at least for the bu-workshop) references the file as part of the `ssh_extra_args`.
Generating the file will happen in all runs and for all env types. However, currently only the bu-workshop env type actually uses this file in its SSH config.
The generated config file does not rely on a template, so it should not cause any errors when running the playbook. However, the ControlPath is set to `/tmp/%h-%r` which might have issues on MacOS.
It also makes the bu-workshop cleanup playbook more thorough, deleting all of the generated files out of the workdir.
> switch to using ssh config file (for bu-workshop)

- ansible/configs/ocp-ha-lab/README.adoc
- Add inventory like the previous command
- add ANSIBLE_REPO_PATH, fix error because of undefined variable:
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ANSIBLE_REPO_PATH' is undefined\n\nThe error appears to have been in '/home/user/Git/ansible_agnostic_deployer/ansible/configs/ocp-ha-lab/destroy_env.yml': line 36, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Destroy cloudformation template\n      ^ here\n"}
> ocp-ha-lab, README: fix destroy command

- Preparing_your_workstation.adoc
`touch ~/.ssh/config` is not enough. This error can occur in some playbooks during provisioning (depending on the user's umask of course):
fatal: [ec2-35-158-247-170.eu-central-1.compute.amazonaws.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Bad owner or permissions on /home/user/.ssh/config\r\nCouldn't read packet: Connection reset by peer\r\n", "unreachable": true}
this commit sets mode for `~/.ssh/config` to `600`
>  Preparing_your_workstation.adoc: fix  ~/.ssh/config mode

- ansible/configs/ocp-workshop/files/hosts_template.j2
zabbix alerts are currently set to trigger above 90%. The current setting (90-80%)
results in false-positive. Lower those values.
> change garbage collection threshold

- ansible/configs/ocp-workshop/files/ocp_report.adoc.j2
- ansible/configs/ocp-workshop/post_software.yml
Generate asciidoc report at the end of post_software playbook.
export report to `workdir/`
> ocp-workshop: generate report

- ansible/cloud_providers/ec2_ssh_config_setup.yml
following the today bug with:
```
ERROR! A worker was found in a dead state
```
> comment debug task

- ansible/configs/ocp-workshop/post_software.yml
Let's use the aws_* variables set in env_secret_vars.yml instead of
~/.aws/credentials
> Fix aws credentials for ocp_report play

- ansible/configs/ansible-provisioner/post_software.yml
- ansible/configs/ocp-workshop/files/hosts_template.j2
- ansible/roles/zabbix-client/defaults/main.yml
- scripts/README.adoc
- scripts/ansible-provisioner.rc.example
- scripts/ocp-workshop-3.5.rc.example
- scripts/wrapper.sh
- tested ocp-workshop deployment with ocp 3.6
- validate ocp-workshop deployment with ocp 3.5 is still working
- add role zabbix-client to ansible-provisioner
- add wrapper.sh script in `scripts/` directory
- end-user script to facilitate deployments
- add README.adoc
- add 2 examples of RC files
> ocp-workshop 3.6 + ansible-provisioner scripts

- ansible/configs/ansible-provisioner/post_software.yml
- ansible/configs/ocp-workshop/post_software.yml
-  gather facts before generating report
- This should fix the 'ansible_process' not defined error.
- fix conditional '== true'
- even when running the playbook with -e ocp_report=true, the report generation was always skipped. This commit fix the syntax and those conditional. Also fix other similar conditional.
- add the guid in the report generated filename
> Fix report and conditional

- ansible/configs/ocp-ha-lab/files/hosts_template.j2
tested opc-ha-lab config with 3.6.
host inventory file needs this var in our case, because we usually use small VM and do not follow requirements/recommandations
> ocp-ha-lab: disable checks

- ansible/configs/ocp-ha-lab/env_vars.yml
- ansible/configs/ocp-ha-lab/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/ocp-workshop/env_vars.yml
- ansible/configs/ocp-workshop/files/cloud_providers/ec2_cloud_template.j2
Use variables to be able to simply change size of the device attached for rootfs.
* ocp-workshop
* ocp-ha-lab
> use variables for root fs size in ec2 templates + add one for bastion as well

- ansible/cloud_providers/ec2_infrastructure_deployment.yml
- ansible/configs/ans-tower-lab/destroy_env.yml
- ansible/configs/ansible-provisioner/destroy_env.yml
- ansible/configs/generic-example/destroy_env.yml
- ansible/configs/ocp-demo-lab/destroy_env.yml
- ansible/configs/ocp-ha-lab/destroy_env.yml
- ansible/configs/ocp-implementation-lab/destroy_env.yml
- ansible/configs/ocp-workshop/destroy_env.yml
- ansible/configs/opentlc-shared/destroy_env.yml
- ansible/configs/single-ipa/destroy_env.yml
- ansible/configs/three-tier-app/destroy_env.yml
When we trigger several destroy actions at the same time, it happens that the
cloudformation module fail because of AWS MaxRequest/s policy (Throttling).
This commit adds:
- retry 5 times
- wait 1 minute between retry
This should help ensure each stack is properly destroyed.
> add do-until loop for cloudformation destroy

- ansible/cloud_providers/ec2_infrastructure_deployment.yml
- ansible/inventory/ec2.ini
- ansible/inventory/ec2.sh
- ansible/roles/opentlc-integration/tasks/packages.yml
- ensure stack creation is complete: add a condition on output.
Sometime stack creation fails, resulting in a non-complete stack (some VM
created, other components missing). The cloudformation module does not register
a failure in that case.
- debug complete register of cloudformation instead of only 'stack_outputs'
which is not very informative.
- update ec2.ini to use cache: improves the overall performance a lot
we are using refresh_inventory only in a few places like just after
cloudformation stack creation.
- update ec2.ini to list non-running instances
Sometime after Cloudformation stack creation, we directly update ec2.py cache.
Some instances might not be ready and running.
- ec2.sh: add a wrapper to ec2.py.
This wrapper implements recommandations from: …
> improvements from stress tests

- ansible/configs/ans-tower-lab/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/generic-example/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/ocp-ha-lab/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/ocp-workshop/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/three-tier-app/files/cloud_providers/ec2_cloud_template.j2
The problem during the stress tests appears to be a race condition established
between the creation of the Elastic IP resource and the VPC Gateway Attachment
resource that connects the created VPC to the wider internet. For the EIP to be
created successfully, it needs to be created in a VPC with an established
network connection.
It appears that in most cases, the Gateway Attachment is created before the
EIPs, and the stack is therefore successful. The failures occur when the EIP
creation is attempted before the Gateway Attachment. To avoid this condition,
this commit makes the EIP resources dependent on the Gateway Attachment using a
DependsOn statement.
> cloudformation templates: fix race condition

- ansible/configs/ocp-workshop/files/hosts_template.j2
I changed the default node selectors for metrics and logging. This worked in an OCP-Workshop environment stood up for the OCP_Operations course. Should work elsewhere as well.
> Changed node selectors for metrics and logging

- README.adoc
Immediately recognized it, because I also do that all the time in adoc files. The links are written the other way around and without `()`.
> replacing markdown links with adocs links

- ansible/cloud_providers/ec2_infrastructure_deployment.yml
- ansible/configs/ocp-ha-lab/files/cloud_providers/ec2_cloud_template.j2
internaldns tags were missing in the ocp-ha-lab Cloudformation template.
Also add better defaults in `ec2_infrastructure_deployment.yml` for shortname and internaldns vars:
default to `private_dns_name` if tags do not exist.
> ocp-ha-lab: fix hostname

- ansible/roles/bastion/defaults/main.yml
- ansible/roles/bastion/tasks/main.yml
- ansible/roles/set_env_authorized_key/tasks/main.yml
- set `use_own_key` to true by default so user's private SSH key is not copied to
bastion
- fix boolean logic:
`{{key_name}}.pem` was copied to bastion even when `use_own_key` was true
- when copying `{{key_name}}.pem` to bastion, copy it to `{{key_name}}.pem`, not
`{{env_authorized_key}}`  (probably a typo/omission)
> fix ssh key behavior

- ansible/roles/ocp-workload-parksmap-demo/defaults/main.yml
- ansible/roles/ocp-workload-parksmap-demo/files/workshop-mlbparks.yaml
- ansible/roles/ocp-workload-parksmap-demo/files/workshop-nationalparks.yaml
- ansible/roles/ocp-workload-parksmap-demo/files/workshop-parksmap.yaml
- ansible/roles/ocp-workload-parksmap-demo/files/workshopper-template.yaml
- ansible/roles/ocp-workload-parksmap-demo/readme.adoc
- ansible/roles/ocp-workload-parksmap-demo/tasks/main.yml
- ansible/roles/ocp-workload-parksmap-demo/tasks/post_workload.yml
- ansible/roles/ocp-workload-parksmap-demo/tasks/pre_workload.yml
- ansible/roles/ocp-workload-parksmap-demo/tasks/remove_workload.yml
- ansible/roles/ocp-workload-parksmap-demo/tasks/workload.yml
This workload deploys a version of parksmap application demo.
It creates 2 projects:
- One with the full demo deployed, and the guides to learn the demo
- One empty project to exercise the demo
There's still some pending changes:
- me understanding better how to include other roles (siamak roles for workshopper and common_facts, etc... although the common facts should be core to the workloads IMHO)
- update to the workshop instructions and move the workshop.yml out of my personal repo into the openshift-labs one
> Parksmap workload

- ansible/configs/ocp-ha-lab/env_vars.yml
- ansible/configs/ocp-ha-lab/files/hosts_template.3.9.14.j2
- ansible/configs/ocp-ha-lab/files/repos_template.j2
@newgoliath @sborenst @fridim Please review. Updated HA Workshop for 3.9. I also removed all logic for releases before 3.7. We don't run any classes on earlier versions any more.
> Updated HA Workshop for OCP 3.9

- ansible/roles/ocp-workload-fuse-ignite/readme.adoc
On line 58 of the readme.adoc, *ocp-workload-fuse-ignite* should replace *ocp-workload-3scale-multitenant*
> Correction to reference to 3scale workload file

- ansible/configs/ansible-cicd-lab/create_host.yml
- ansible/configs/ansible-cicd-lab/env_vars.yml
- ansible/configs/ansible-cicd-lab/post_software.yml
- ansible/configs/ansible-cicd-lab/tower_setup.yml
At the subject says. The setup works now but there seems to still be issues with the credentials or something around it: doing a ping on the hosts from the inventory in Tower doesn't yet work, I didn't analyse in depth, running out of time. Merge and continue from there.
> fix tower admin name, fix tower setup delegation to bastion and fix ansible_host for the inventory

- ansible/configs/rhte-ocp-workshop/pre_software.yml
Error is :
Failed to connect to the host via ssh: ssh: Could not resolve hostname support1.8d25.internal
during playbook run from bastion.
Populate /etc/hosts to keep dns resolution local.
> rhte-ocp-workshop: populate /etc/hosts for internaldns

- ansible/configs/rhte-ocp-workshop/post_infra.yml
We can manually add them for a couple of clientVM, no big deal.
> rhte-ocp-workshop: ignore errors when creating clientVM DNS records

- ansible/configs/rhte-oc-cluster-vms/post_software.yml
Error is:
TASK [Reboot VM] ***************************************************************
Friday 07 September 2018  13:10:04 +0000 (0:05:02.849)       0:17:49.293 ******
fatal: [clientvm.ce4a.internal]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to ec2-18-182-111-209.ap-northeast-1.compute.amazonaws.com closed.\r\n", "unreachable": true}
to retry, use: --limit
@/tmp/rhte-oc-cluster-vms-ce4a/ansible_agnostic_deployer/ansible/main.retry
'ignore_errors' is not enough because SSH connection is close by 'shutdown -r
now'
use async + poll=0 too.
> rhte-oc-cluster-vms: Fix reboot

- ansible/configs/ocp-gpu-single-node/env_vars.yml
- ansible/configs/ocp-gpu-single-node/files/cloud_providers/ec2_cloud_template.j2
I was missing a DNS entry for the router in my cloudformation template. I was also using RHSM and now that GPTE has the 3.10.14 repos I have switched to using "file".
> Switches to file repos and adds missing cloudapps dns entry

- ansible/configs/ansible-cicd-lab/files/tower_hosts_template.j2
RabbitMQ doesn't like non-alphanumerical passwords according to https://docs.ansible.com/ansible-tower/latest/html/installandreference/tower_install_wizard.html (and based on experience).
I've fixed this by protecting the password using a regexp_replace.
Side note: if this proves working for the CI/CD Lab, it should be fixed in a generic manner, there are other places potentially impacted:
```
[.../ansible_agnostic_deployer]$ grep -r rabbitmq_password .
./ansible/configs/ans-tower-lab/files/tower_hosts_template.j2:rabbitmq_password="{{tower_admin_password}}"
./ansible/configs/ansible-cicd-lab/files/tower_hosts_template.j2:rabbitmq_password={{ tower_admin_password | regex_replace('[^a-zA-Z0-9]') }}
./ansible/roles/install-tower/templates/tower_template_inventory.j2:rabbitmq_password={{tower …
```
> Protect rabbitmq password to avoid non-alphanumerical passwords

- ansible/configs/ansible-cicd-lab/env_vars.yml
- ansible/software_playbooks/tower.yml
Add variable `tower_setup_version` to fix Tower version instead of latest. Latest broke our build after Tower 3.3 was released.
> Add variable to fix Tower version instead of latest.

- ansible/configs/ansible-cicd-lab/docker_setup.yml
- ansible/configs/ansible-cicd-lab/env_vars.yml
- ansible/configs/ansible-cicd-lab/post_software.yml
- ansible/configs/ansible-cicd-lab/requirements.yml
- ansible/roles/host-gogs-server/tasks/main.yml
- ansible/roles/host-jenkins-server/tasks/main.yml
- Make Jenkins and Gogs roles more idempotent.
- Add Docker to CI/CD server.
- Push Tower and CI/CD VMs to xlarge.
> Bigger VMs, Docker and more idempotency for Ansible CI/CD Lab

- ansible/configs/ansible-cicd-lab/env_vars.yml
Make sure all app users are called admin and have the same (usual) password.
> unify passwords and users

- ansible/roles/molecule/tasks/main.yml
configparser lib is in a bad state after the installation of Molecule making flake8 unusable (python linter)
A reinstallation of the library fixes the issue
> Force reinstallation of configparser lib

- ansible/configs/ocp-ha-lab/files/hosts_template.3.10.34.j2
- ansible/configs/ocp-ha-lab/files/hosts_template.3.9.41.j2
default setting is "latest." 
prevent unintended upgrades by specifying version.
> ocp-ha-lab: add ocs version lock

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/readme.adoc
- ansible/roles/ocp-workload-integreatly/tasks/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/post_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/pre_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/remove_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
**Summary**
Adding Integreatly ocp-workload role
**Validation**
Provision Workload:
```
HOST_GUID=pmccarthy
DOMAIN="$HOST_GUID.openshiftworkshop.com"
TARGET_HOST="master.$DOMAIN"
SSH_USER="ec2-user"
SSH_PRIVATE_KEY="ocp-workshop.pem"
GUID=pmccarthy
WORKLOAD="ocp-workload-integreatly"
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
-e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
-e"ansible_ssh_user=${SSH_USER}" \
-e"ANSIBLE_REPO_PATH=`pwd`" \
-e"ocp_workload=${WORKLOAD}" \
-e"guid=${GUID}" \
-e"ocp_user_needs_quota=false" \
-e"ACTION=create"
```
Remove workload:
```
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
-e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
-e"ansible_ssh_user=${SSH_USER}" \ …
```
> Adding ocp-workload-integreatly role

- ansible/configs/ansible-cicd-lab/env_vars.yml
Added variable to disable TLS web hook verification in CICD lab
> Added variable to disable TLS web hook verification

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/remove_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
**Summary**
Updating Integreatly install command by removing additional params
Setting become_override to True
**Validation**
```
HOST_GUID=pamccart
DOMAIN="$HOST_GUID.openshiftworkshop.com"
TARGET_HOST="master.$DOMAIN"
SSH_USER="ec2-user"
SSH_PRIVATE_KEY="ocp-workshop.pem"
GUID=pamccart
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
-e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
-e"ansible_ssh_user=${SSH_USER}" \
-e"ANSIBLE_REPO_PATH=`pwd`" \
-e"ocp_workload=${WORKLOAD}" \
-e"guid=${GUID}" \
-e"ocp_user_needs_quota=false" \
-e"ACTION=create"
```
> Updating Integreatly installer workload

- ansible/configs/archive/ocp-storage-cns_based_on_ocp-workshop/post_software.yml
- ansible/configs/ocp-workshop/post_software.yml
- ansible/configs/rhte-ocp-workshop/post_software.yml
- ansible/roles/infra-ec2-create-inventory/tasks/main.yml
use `ec2_instance_facts` module instead of ~~`ec2_remote_facts`~~
This works with ocp-workshop environment.
- Continue testing on different environments
- Merge this **after** RHTE
> Fix ec2_remote_facts deprecation warnings

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
**Summary**
Now that the Integreatly catalog item has LetsEncrypt enabled by default, we need to set a flag as part of the Integreatly install.
Also bumped Integreatly release tag
> Setting TLS flag for Integreatly workload

- ansible/roles/ocp-workload-parksmap-demo/files/workshopper-template.yaml
Wayne Boxall reported on Oct 23rd that the guides were incomplete. I missed to fix this sooner. This is a patch that should fix the issue.
> Update parksmap with instructions valid for 3.10 and 3.11

- ansible/roles/ocp-workload-parksmap-demo/files/workshopper-template.yaml
In the provided template 2 parameters were expected but were not in the parameters section. This parameters are additional to the standard guide for the parksmap demo, that's the reason they were missing. In the regular workshops these are not needed.
> Fixed missing parameters

- ansible/cloud_providers/ec2_destroy_env.yml
- ansible/configs/ocp-clientvm/env_vars.yml
- ansible/configs/ocp-clientvm/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/ocp-clientvm/post_software.yml
- ansible/configs/ocp-clientvm/pre_infra.yml
- ansible/configs/ocp-clientvm/software.yml
- ansible/roles/bastion-opentlc-ipa/tasks/main.yml
- ansible/roles/bastion/tasks/main.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/infra-ec2-template-create/tasks/detect_custom_images.yml
- ansible/roles/infra-ec2-template-create/tasks/main.yml
- ansible/roles/infra-ec2-template-create/tasks/select_custom_image.yml
- ansible/roles/infra-ec2-template-generate/templates/cloud_template.j2
- ansible/roles/ocp-client-vm/tasks/configure_docker.yml
- ansible/roles/ocp-client-vm/tasks/main.yml
- ansible/roles/ocp-client-vm/tasks/packages.yml
- ansible/roles/set-repositories/tasks/main.yml
- ansible/roles/set-repositories/tasks/satellite-repos.yml
- builds/packer/readme.adoc
- builds/packer/rhel_gold.json
Enable use of custom images:
The AMI is detected before the cloudformation stack is created.
There is 2 detection strategies:
- using the image name
variable: `custom_image_filter`
example: `custom_image_filter: RHEL 7.5 GOLD packer 1542702393`
- specific image using tags and the tuple `(env_type, version, stage)`
variable: `custom_image_stage`
This allows us to enable or disable an AMI easily by adding or not the stage into its tag `stages`. env_type and version have to match too.
example: `custom_image_stage: PROD`
If no AMI is found, then it defaults to what is used in the template.
> Custom images using packer

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/pre_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
Adding support for LetsEncrypt staging Root Certificate
Integreatly Workload
This change allows Integreatly to support LE staging environments for both Dev and Test while continuing support in Prod. 
It will mean that `--skip-tags production` will need to be set for both Dev and Test catalog items in Cloudforms
> Adding support for LE Staging Cert

- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
Updating LetsEncrypt logic in Integreatly role by using `lets_encrypt_production` instead of tags
Integreatly
> Replacing prod tag with lets_encrypt_production var

- ansible/roles/ocp-workload-dm7-qlb-demo/tasks/workload.yml
- ansible/roles/ocp-workload-pam-order-it-hardware/tasks/workload.yml
'oc volume' command was removed in OpenShift 3.11. Replacing with 'oc set volume'.
- ocp-workload-dm7-qlb-demo
- ocp-workload-pam-order-it-hardware
n.a.
> Replace removed 'oc volume' command with 'oc set volume'.

- ansible/roles/ocp-workload-fsi-cc-dispute-demo/tasks/workload.yml
Deployment failed because check whether project existed did not function correctly, causing the project not to be created.
- ocp-workload-fsi-cc-dispute-demo
n.a.
> Fixes check whether project already exists.

- ansible/configs/ansible-cicd-lab/env_vars.yml
- ansible/software_playbooks/tower.yml
The Ansible CI/CD lab didn't deploy because the task to add the Tower license in the Tower software playbook failed. I added a variable to the Ansible CI/CD lab environment and a check for that variable in the playbook
-  `ansible/configs/ansible-cicd-lab/env_vars.yml`
-  `ansible/software_playbooks/tower.yml`
I could only test that the deployment of the Ansible CI/CD lab works if `tower_license_use_insecure` is defined _and_ set to `True`.
```
TASK [Add the tower license] ***************************************************
Monday 25 February 2019  10:50:58 -0500 (0:00:02.012)       0:20:09.733 ******* 
skipping: [tower1.90d9.internal]
TASK [Add the tower license (with --insecure)] *********************************
Monday 25 February 2019 …
```
> Cicd lab fixes

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
We want to have the variable eval_self_signed_certs default to true unless we are in an environment where lets encrypt production is being used.
Integreatly Workshop
> default to self signed certs unless le is production

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
Updating Integreatly release version to v1.2.0
Integreatly
There is a PR (https://github.com/redhat-cop/agnosticd/pull/332) for bumping to 1.2.0, but we decided to update to 1.2.1 directly.
> Bumping Integreatly release version v 1.2.1

- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
Fixes https://issues.jboss.org/browse/INTLY-1316
The evals user has been removed from the Integreatly environment. This PR removes the reference to that user in the ready notification email
Integreatly
> Remove evals user from email text

- ansible/roles/ocp-workload-odo-workshop/tasks/pre_remove_workload.yml
- ansible/roles/ocp-workload-odo-workshop/tasks/pre_workload.yml
When running the role, the copy task was trying to copy to the target host and not to the same host where the playbook was run.
This role needs to copy the .kube/config file from a location in the bastion server to a different location ALSO on the bastion server (where the playbook is run).
ocp-workload-odo-workshop
Copy task was not run from-to bastion server. With this change, we make the copy task happen on the bastion server.
> Fixed copy task to get root's kube/config

- ansible/roles/ocp4-workload-cluster-autoscale/defaults/main.yml
- ansible/roles/ocp4-workload-cluster-autoscale/readme.adoc
- ansible/roles/ocp4-workload-cluster-autoscale/tasks/main.yml
- ansible/roles/ocp4-workload-cluster-autoscale/tasks/post_workload.yml
- ansible/roles/ocp4-workload-cluster-autoscale/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-cluster-autoscale/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-cluster-autoscale/tasks/workload.yml
This will create a cluster autoscaler (max size 9 nodes) and create a machineautoscaler for each existing machineset. In other words, it finds all the current machinesets in the cluster, and creates one machine autoscaler for each one.
This means that this role should come before any other roles that might create additional machinesets (eg: infra nodes).
It also means that for regions like us-east-1 where the cluster gets 6 sets but only 3 nodes (default), autoscalers will be created for machinesets that effectively end up unused. That's not really a problem, so w/e.
ocp4-workload-cluster-autoscale
none
> Adds cluster autoscale for ocp4 and cleans some descriptions

- ansible/roles/ocp4-workload-infra-nodes/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-infra-nodes/tasks/workload.yml
- ansible/roles/ocp4_machineset_config/README.adoc
- ansible/roles/ocp4_machineset_config/defaults/main.yml
- ansible/roles/ocp4_machineset_config/meta/main.yml
- ansible/roles/ocp4_machineset_config/tasks/aws-machineset-group.yml
- ansible/roles/ocp4_machineset_config/tasks/aws.yml
- ansible/roles/ocp4_machineset_config/tasks/disable-base-worker-machinesets.yml
- ansible/roles/ocp4_machineset_config/tasks/enable-cluster-autoscaler.yml
- ansible/roles/ocp4_machineset_config/tasks/main.yml
- ansible/roles/ocp4_machineset_config/tasks/set-facts.yml
- ansible/roles/ocp4_machineset_config/templates/aws-machineset.yml.j2
- ansible/roles/ocp4_machineset_config/templates/clusterautoscaler.yml.j2
- ansible/roles/ocp4_machineset_config/templates/machineautoscaler.yml.j2
- ansible/roles/ocp4_machineset_config/vars/main.yml
Switch to cleaner ansible role for machineset management. Also fixes quoting issue in jq by eliminating use of jq in machineset creation.
ocp4_machineset_config
ocp4-workload-infra-nodes
Adds ocp4_machineset_config
> Switch to ocp4_machineset_config for ocp4-workload-infra-nodes

- ansible/roles/ocp4-workload-workshopper/defaults/main.yml
- ansible/roles/ocp4-workload-workshopper/readme.adoc
- ansible/roles/ocp4-workload-workshopper/tasks/main.yml
- ansible/roles/ocp4-workload-workshopper/tasks/post_workload.yml
- ansible/roles/ocp4-workload-workshopper/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-workshopper/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-workshopper/tasks/workload.yml
a role for deploying the workshopper app, which generates lab guides from markdown/adoc.
ocp4-workload-workshopper
* `_deployed_guide_name` is the name that will be passed to `new-app` and will be used for the route. 
* `_deployed_guide_string_url` is a public URL that will return a string that contains everything that should be passed to `new-app`. The expectation is that this will be the path to `workshopper` (eg:`quay.io/osevg/workshopper`), the required Workshopper args (`CONTENT_URL_PREFIX` and `WORKSHOPS_URLS`), and any extra vars you want to pass into workshopper (eg: `-e OPENSHIFT_MASTER="http://127.0.0.1:8443"`). An example string is below:
```
quay.io/osevg/workshopper -e CONTENT_URL_PREFIX=https://raw.githubusercontent.com/thoraxe/istio-lab-summit-2019/ma …
```
> workshopper role that deploys a labguide into a project

- ansible/roles/ocp4-workload-workshopper/tasks/workload.yml
modification to the ocp4-workload-workshopper role to add the kubeadmin password to the environment variables
> adds kubeadmin password to workshopper

- ansible/configs/ocp4-workshop/post_software.yml
This commit, if applied will mount and update /etc/fstab for:
/home/ec2-user/cluster-GUID to /home/lab-user/cluster-GUID as bind ReadOnly
```paste below
```
> OCP4 Workshop: mount bind ReadOnly cluster dir to lab-user

- ansible/configs/ocp4-ha-lab/software.yml
- ansible/configs/ocp4-shared/software.yml
- ansible/configs/ocp4-workshop/software.yml
If applied, this commits transforms the ocp4_installer_version before using
version_compare filter.
Indeed, with previous versions the string starts with 'v', and now it's '4.0.0'
```paste below
```
> OCP4: fix version comparison

- ansible/roles/ocp-workload-dm7-qlb-demo/defaults/main.yml
- ansible/roles/ocp-workload-dm7-qlb-demo/files/rhdm73-kieserver-cors.yaml
- ansible/roles/ocp-workload-dm7-qlb-demo/tasks/workload.yml
- ansible/roles/ocp-workload-fsi-cc-dispute-demo/defaults/main.yml
- ansible/roles/ocp-workload-fsi-cc-dispute-demo/tasks/workload.yml
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/tasks/workload.yml
- ansible/roles/ocp-workload-pam-order-it-hardware/defaults/main.yml
- ansible/roles/ocp-workload-pam-order-it-hardware/files/rhpam73-businesscentral-openshift-with-users.yaml
- ansible/roles/ocp-workload-pam-order-it-hardware/tasks/workload.yml
Due to the shutdown of registry.access.redhat.com, all the RHPAM and RHDM demos started to fail. This PR fixes this by:
- Checking whether the required ImageStreams are in the "openshift" namespace
- If not present, provision the ImageStreams in the "openshift" namespace
I need to use the "openshift" namespace instead of the project namespace, as I need the credentials to pull from "registry.redhat.io", which are present in the "openshift" namespace, but not in the project namespace.
- rhpam-order-it-hw
- rhdm-qlb-loan
- fsi-cc-dispute
Talked to Sha to discuss possible fixes, and this seemed the best option (unitil we move to a dedicated Quay instance).
> Move to registry redhat io

- ansible/roles/ocp4-workload-istio-controlplane/tasks/workload.yml
This updates the `ocp4-workload-istio-controlplane` role to use a slightly different configuration. It was tested against an existing cluster.
> changes the configuration of the deployed istio controlplane

- ansible/roles/ocp4-workload-istio-tutorial/tasks/workload.yml
The istio tutorial customer image reference is wrong, it currently references customer:latest and not customer:v1
ocp4-workload-istio-tutorial
@thoraxe FYI
> Fix customer image name for istio tutorial

- ansible/roles/ocp4-workload-build-your-own-operator/defaults/main.yml
- ansible/roles/ocp4-workload-build-your-own-operator/readme.adoc
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/main.yml
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/post_remove_workload.yml
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/post_workload.yml
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/pre_remove_workload.yml
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-build-your-own-operator/tasks/workload.yml
This is a replacement for https://github.com/redhat-cop/agnosticd/pull/416, which addresses the issues raised there. 
The workload is now referencing a tagged release rather than just a branch https://github.com/openshift-labs/lab-build-your-own-operator/releases/tag/v1.1
Also fixed another task that needed chdir added to it.
> Ocp4 workload build your own operator (replaces PR 416)

- ansible/configs/linklight-foundations/lab_vars/foundations_all_vars.yml
Ansible Foundations labs are deployed by an older version of linklight which often leaves artifacts around on AWS, such as undeleted ec2 instances.
To enable it to be updated to a much more recent version of linklight a new var `username` needed to be added to the foundations_all_vars.yml
config/linklight-foundations
All other fixes related to this are external to agnosticd e.g. OPEN_ADMIN deployer scripts and linklight
> Added new username var to linklight foundations vars to allow linklight to be updated to more recent version

- ansible/lifecycle.yml
Start using agnosticd for idleing / start environments.
With agnosticv coming, i need to use agnosticd not only for deploying and destroying, but also for stopping and starting environments.
We would pass the same args to `ansible-playbook` as we do for `main.yml` or `destroy.yml` playbooks.
When cloudforms 'stop' or 'start' an environment, in OPEN_Admin scripts (or in tower in the future) i suggest we look for those files:
- `ansible/configs/$ENVTYPE/lifecycle.yml`
- `ansible/configs/$ENVTYPE/start.yml`
- `ansible/configs/$ENVTYPE/stop.yml`
If they exist, they will be used. If not, the default is the file present in this PR, `ansible/lifecycle.yml`.
This logic cannot be implemented in agnosticd, since playbook can only be *imported* and not dynamically *included*. …
> Add lifecycle.yml for start/stop/status action

- ansible/roles/ocp4-workload-istio-tutorial/tasks/workload.yml
The ocp4-workload-istio-tutorial was missing a deployment which this PR adds.
> adds missing curl deployment

- ansible/roles/ocp4-workload-security-compliance-lab/tasks/quay.yml
Changed quay operator version to summit version
ocp4-workload-security-compliance-lab
The workload was using the latest quay operator, which is not currently working for the version of quay used by this lab. Update to use the last known working operator version.
> Use the summit version of the quay operator

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/remove_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
Integreatly installation does not install AMQ Streams by default but RHPDS should install AMQ Streams.
These changes sets the required flag to install AMQ Streams.
Fixes: https://issues.jboss.org/browse/INTLY-1914
integreatly
> Add integreatly operator params

- ansible/configs/ocp-workshop/files/project-template.j2
- ansible/roles/ocp4-workload-project-request-template/templates/project_request_template.j2
a) changed minimal requested memory to allow Launcher deployment ([it's currently requesting 8M](https://github.com/fabric8-launcher/launcher-operator/blob/d0124534296c3d1239fb0110ce70876bfe9dd3fa/templates/fabric8-launcher.yaml#L225-L229)). I picked "6Mi" value to match min requested memory for a pod.
b) **dropped**, see discussion below ~~bumped UserQuota for OCP4 workshop. This will enable opentlc-mgr user to utilize all available resources (I calculated CPU and memory based on 3x m4.2xlarge worker nodes available).~~
~~This is mainly motivated by the problems discovered during Integreatly installation. We are starting to test new MW products on OpenShift 4.~~
ocp-workshop, ocp4-workshop
**dropped**, see discussion below ~~P.S: This change is motivated by 3Scale …
> Change limits and quotas

- ansible/roles/ocp4-workload-projectreaper-operator/defaults/main.yml
- ansible/roles/ocp4-workload-projectreaper-operator/readme.adoc
- ansible/roles/ocp4-workload-projectreaper-operator/tasks/main.yml
- ansible/roles/ocp4-workload-projectreaper-operator/tasks/post_workload.yml
- ansible/roles/ocp4-workload-projectreaper-operator/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-projectreaper-operator/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-projectreaper-operator/tasks/workload.yml
- ansible/roles/ocp4-workload-projectreaper-operator/templates/crd.j2
- ansible/roles/ocp4-workload-projectreaper-operator/templates/operator.j2
- ansible/roles/ocp4-workload-projectreaper-operator/templates/project.j2
- ansible/roles/ocp4-workload-projectreaper-operator/templates/project_tracker.j2
- ansible/roles/ocp4-workload-projectreaper-operator/templates/role.j2
- ansible/roles/ocp4-workload-projectreaper-operator/templates/role_binding.j2
- ansible/roles/ocp4-workload-projectreaper-operator/templates/service_account.j2
Introduce a project reaper that will delete any projects created by a user that is no longer defined to the cluster based on the USER resource. The operator has been integrated as ocp4-workload-projectreaper-operator.
New role: ocp4-workload-projectreaper-operator
Operator Image: quay.io/redhattraining/rht-project-reaper-operator:v0.0.1
Source code for this operator is in a private repository https://github.com/redhattraining/do999.git
Recommend use in env_vars.yml:
```
default_workloads:
...omitted...
- ocp4-workload-projectreaper-operator
...omitted...
```
> New operator integration: Project Reaper

- ansible/roles/ocp4-workload-infra-nodes/tasks/workload.yml
- ansible/roles/ocp4_machineset_config/README.adoc
- ansible/roles/ocp4_machineset_config/tasks/aws-machineset-group.yml
- ansible/roles/ocp4_machineset_config/tasks/aws.yml
- ansible/roles/ocp4_machineset_config/templates/aws-machineset.yml.j2
* Preserve worker AWS tags
* Add role setting to default node role labels
Ansible role ocp4_machineset_config
Previous version did not preserve AWS instance tags in the worker machineset configs. This version keeps the user tags. This is needed so that jobs that suspend ec2 instances by tag will find ec2 instances created because of configuration generated by this role.
> Update ocp4_machineset_config role

- ansible/configs/ocp4-ha-lab/software.yml
- ansible/configs/ocp4-shared/software.yml
- ansible/configs/ocp4-workshop/software.yml
- ansible/roles/host-ocp-installer/tasks/main.yml
Fixes redhat-cop#464.
- ansible/configs/ocp4-ha-lab/software.yml
- ansible/configs/ocp4-shared/software.yml
- ansible/configs/ocp4-workshop/software.yml
- ansible/roles/host-ocp-installer/tasks/main.yml
Features: Improvement on deployment resiliency, in particular with deployments from a physical host.
Changes:
- Deployment tasks now runs in async mode.
- Every deployment is given a 2h time quantum.
- Similar to https://github.com/redhat-cop/agnosticd/blob/c023f9a8bf92c95141a8bc0023d7b15526ef2cdd/ansible/configs/ocp4-shared/destroy_cluster.yml#L8-L13 (Thanks @fridim with https://github.com/redhat-cop/agnosticd/issues/464#issuecomment-504638671)
```paste below
Same as usual.
```
> Avoid hanging issue on long running deployment tasks.

- ansible/roles/ocp4-workload-metering/tasks/pre_workload.yml
Fix race condition where the workload can run before the meterings.metering.openshift.io CRD is created by the operator.
ocp4-workload-metering
Failure addressed by this PR:
```
TASK [ocp4-workload-metering : Create Metering Custom Resource with Route and Resource Limits] ***
Tuesday 25 June 2019  18:16:07 +0000 (0:00:17.178)       0:57:13.177 ********** 
failed: [clientvm.95ca.internal] (item=./templates/metering.j2) => {"changed": false, "item": "./templates/metering.j2", "msg": "Failed to find exact match for metering.openshift.io/v1alpha1.Metering by [kind, name, singularName, shortNames]"}
```
> Add wait for metering CRD to ocp4-workload-metering

- .gitignore
- ansible/roles/ocp4-workload-workshop-admin-storage/defaults/main.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/readme.adoc
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/main.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/post_workload.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
Adds OpenShift and Container Storage for Administrators workshop role
- roles
- ocp4-workload-workshop-admin-storage
A new role for deploying [OpenShift and Container Storage for Administrators workshop](https://github.com/openshift/openshift-cns-testdrive/tree/ocp4-dev) inside [Homeroom Dashboard](https://github.com/openshift-labs/workshop-dashboard).
> Ocp4 workload workshop admin storage

- ansible/roles/infra-ec2-template-create/tasks/main.yml
- ansible/roles/infra-ec2-template-generate/tasks/main.yml
Refers to #466 
Changes:
- Simplification of cloudtemplate validation.
- Merging launch CloudFormation templete task into one.
- Launch CloudFormation template ***
- validate cloudformation template (local) + validate cloudformation template (S3) -> validate cloudformation template (local)
Before:
```
TASK [infra-ec2-template-generate : AWS Generate CloudFormation Template] ***********************************************************************************
Sunday 23 June 2019  12:00:56 +0200 (0:00:00.035)       0:00:03.122 ***********
ok: [localhost]
...
TASK [infra-ec2-template-generate : validate cloudformation template (local)] *******************************************************************************
Sunday 23 June 2019  12:00:57 +0200 (0:00:00.035) …
```
> Refactoring cloudformation template usage.

- ansible/roles/ocp-workload-optaweb-vrp/tasks/pre_workload.yml
Fixes failing rsync on optaweb-vrp deployment.
ocp-workload-optaweb-vrp
n.a.
> Removed copy-files task as there are no files to be copied.

- ansible/roles/ocp4-workload-workshop-admin-storage/readme.adoc
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
Fix .stdout references in workload.yml
Please ensure the email notify users to access the workshop at "{{ Route.result.spec.host }}"
Something like admin-labguide.apps.cluster-32e4.sandbox483.opentlc.com
> Ocp4 workload workshop admin storage - .stdout fixes

- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
Enable route access for `kubeadmin` user
Fixes access forbidden issues that doesn't come up if user logged-in was kubeadmin and not system:admin.
Systems requested on cloudforms default oc user to system:admin preventing access.
> add ansible_user to subject of rolebinding enabling route access

- ansible/roles/ocp4-workload-workshop-admin-storage/readme.adoc
- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
Add new features
Bugfix grabbed wrong ssh username.
Admonition which previously do not show red border will now show red border
Like the following
> Update dashboard image to 3.5.0, user info: spacing

- ansible/roles/ocp4-workload-open-data-hub/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-open-data-hub/tasks/workload.yml
Remove use of lookup and use k8s src
Remove yq
If OpenShift rest client cache file do not exist, do not attempt to delete a non-existent file.
ocp4-workload-open-data-hub
```paste below
```
> Remove lookup. uses k8s src, remove yq, workaround fixes

- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
Allow service account cluster-admin access
Allow workshop attendees to visit console within homeroom with service account and full access.
```paste below
```
> Add web console back to workshop

- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
Grab exact quay.io image used on namespace openshift-console for embedding console used inside homeroom environment.
```paste below
```
> grab embedded console image from openshift-console

- ansible/roles/ocp4-workload-upgrade-cluster/README.adoc
- ansible/roles/ocp4-workload-upgrade-cluster/defaults/main.yml
- ansible/roles/ocp4-workload-upgrade-cluster/tasks/main.yml
- ansible/roles/ocp4-workload-upgrade-cluster/tasks/post_workload.yml
- ansible/roles/ocp4-workload-upgrade-cluster/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-upgrade-cluster/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-upgrade-cluster/tasks/workload.yml
- Adding a role that upgrades a existing ocp 4 cluster to newer version. 
- This workload is needed for hands-on lab on Openshift Developer Console in RHTE 2019 since Developer Console has not been released yet and we need a way to upgrade the cluster to latest 4.2.
ocp4-workload-upgrade-cluster
```paste below
```
> Add a workload that upgrades ocp 4 cluster to newer version

- ansible/roles/ocp4-workload-idm/tasks/workload.yml
Fix bug in ipa-cacert-manage command in ocp4-workload-idm.  The CA certs were not being uploaded so the cert install failed thus leaving self-signed certificates for Identity Manager.
Fixes #527 
config/ocp4-workshop - ocp4-workload-idm
None
> Fixed typo in ipa-cacert-manage command

- ansible/roles/ocp-workload-migration/defaults/main.yml
- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
Exposes a new variable for the migration workload that allows a user to specify a branch of the migration operator repo.
> Add branch variable for mig-operator repo in migration workload

- ansible/roles/ocp4-workload-open-data-hub-student/tasks/workload.yml
Removes merge_type which caused issues with student workloads
ocp4-workload-open-data-hub-infra
ocp4-workload-open-data-hub-student
```paste below
```
> Remove merge_type merge

- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
Updated workload.yml adding delegate_to in order to execute some tasks on the bastion host.
ocp-workload-edge-deployments
delegate_to added to certain tasks in order to execute tasks on bastion host instead of master
> Updated workload.yml adding delegate_to

- ansible/roles/ocp-workload-edge-deployments/tasks/pre_workload.yml
- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
adding "delegate_to" in order to copy APB source file on the bastion
ansible/roles/ocp-workload-edge-deployments/tasks/pre_workload.yml
> adding "delegate_to" in order to copy APB source file on the bastion

- ansible/roles/ocp4-workload-ceph/tasks/pre_workload.yml
Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>
Fixed issue : CI was failing due to using deprecated jinja2 templating in a when clause.
> Fixing CI failures with Ceph workload

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/files/wait-for-deployment
Improved the wait for deployment script so it doesn't fail if the deployment doesn't exist.
```paste below
```
> Improved wait-for-deployment script on ocp4-workload-rhte-kubefed-app-portability

- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml has bad task and looks like it is blocking CI tests from passing.
This fixes the broken task.
> Fix broken task blocking CI checks

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
These password variables had different values every time they were read :man_facepalming: 
Using a filename makes them sticky values.
integreatly
@mikenairn @pmccarthy
> user passwords are incorrect in the email

- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
add become: true to :
- Generate a brand new SSH key on MASTER that will be used also by APB container (provision.yml)
- add new ssh-key as authorized on BASTION host
> add become: true to  workload.yml for some tasks

- ansible/roles/ocp-workload-migration/tasks/post_workload.yml
Changes post_workload task to not print the route for debugging.
```paste below
```
> Update OCP migration workload to not get migration route

- ansible/roles/ocp4-workload-istio-tutorial-student/readme.adoc
- ansible/roles/ocp4-workload-istio-tutorial-student/tasks/workload.yml
Removes creation of ServiceMeshMemberRoll as we now use the same project namespace as the controlplane.
ocp4-workload-istio-tutorial-student
```paste below
```
> removed creating ServiceMeshMemberRoll + readme edits

- ansible/roles/ocp-workload-mssql/templates/manifest.yaml.j2
using a longer delay to run the db-init.sh script within the entrypoint to fix an issue with the database script running before the DB comes up
ocp-workload-mssql
> Update ocp-workload-mssql for bugfix

- ansible/roles/ocp-workload-openshift-applier/readme.adoc
- ansible/roles/ocp-workload-openshift-applier/tasks/main.yml
- ansible/roles/ocp-workload-openshift-applier/tasks/post_workload.yml
- ansible/roles/ocp-workload-openshift-applier/tasks/pre_workload.yml
- ansible/roles/ocp-workload-openshift-applier/tasks/remove_workload.yml
- ansible/roles/ocp-workload-openshift-applier/tasks/workload.yml
This PR adds support for utilizing [openshift-applier](https://github.com/redhat-cop/openshift-applier) as a workload as part of the various configs - e.g.: part of the `default_workloads`. 
ocp-workload-openshift-applier
```paste below
```
> Adding openshift-applier workload

- ansible/roles/ocp4-workload-operator-mssql/defaults/main.yml
- ansible/roles/ocp4-workload-operator-mssql/tasks/workload.yml
bug fix in operator mssql workload
ocp4-workload-operator-mssql
```paste below
```
> ocp4-workload-operator-mssql : fixing wrong namespace in operator mssql

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_infra/files/scc.yaml
Fix issue where deployer now fails when creating an SCC with apiVersion securitycontext.openshift.io. Setting SCC apiVersion to v1
Workload: ocp4-workload-rhte-analytics_data_ocp_infra
N/A
> RHTE Analytics Data - Change rook scc apiVersion to v1

- ansible/roles/ocp4-workload-ml-workflows-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/per_user_remove_workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/per_user_workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/workload.yml
Fixes the ML Workflows Workshop to work with recent changes to the analytics/ODH workshop roles it depends on.
ocp4-workload-ml-workflows-workshop
This includes fixes to the ML Workflows Workshop to work with recent changes to the analytics/ODH workshop roles it depends on.
NB:  all roles must be run with the following variable settings:  ```-e"jupyter_notebook_memory=6Gi" -e"deploy_odh_cr=true" -e"rgw_service_ip=rook-ceph-rgw-my-store" -e"rgw_service_port=8000"```  Since we don't control the ODH roles, we can't set them there.
> updates workflows workshop to work with changes to other roles

- ansible/roles/ocp-workload-dekorate-component-operator/defaults/main.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/workload.yml
feat: Add sudoer cluster role to lab A2026 for user1, opentlc-mgr
chore: Bump workshop to latest version of the operator
> feat: Add sudoer cluster role to lab A2026

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_infra/files/scc.yaml
This reverts a one-line change that was added in 7da383be72f0e978612ae7ce873ba70b4a097547 to potentially resolve the error
"""
Failed to find exact match for security.openshift.io/v1.SecurityContextConstraints by [kind, name, singularName, shortNames]
"""    
This same error occurs when the apiversion is "security.openshift.io/v1" or "v1" so I want to restore the file to what has been verified to work.
Workload ocp4-workload-rhte-analytics_data_ocp_infra
This error never occurs when run outside of the lab deployer system
> Revert a SCC apiVersion update in ocp4-workload-rhte-analytics_data_ocp_infra

- ansible/roles/ocp4-workload-rhte-jupyter-spark/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-rhte-jupyter-spark/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-rhte-jupyter-spark/tasks/workload.yml
Fixes to remove conditions in inherited tasks and empty remove_workload
- Bugfix Pull Request: removed silent var in the conditional, as was giving problems in the pre_workload.yml. Empty remove_workload.yml from any task.
ocp4-workload-rhte-jupyter-spark role
> Fixes to remove conditions in inherited tasks and empty remove_workload

- ansible/roles/ocp4-workload-ml-workflows-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/files/opendatahub_v1alpha1_opendatahub_cr.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/files/operator.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/files/role.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/files/role_binding.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/files/service_account.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/readme.adoc
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/main.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/per_user_operator_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/per_user_post_operator_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/per_user_pre_operator_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/per_user_remove_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/post_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/tasks/workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/templates/jupyterhub-single-user-profile-user.configmap.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/templates/kafka/strimzi-cluster-operator.deployment.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/templates/kafka/strimzi.clusterrolebinding.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/templates/kafka/strimzi.rolebinding.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/templates/kafka/strimzi.serviceaccount.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/templates/opendatahub-operator.operatorgroup.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/templates/opendatahub-operator.v0.4.0.clusterserviceversion.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/templates/opendatahub_v1alpha1_opendatahub_cr.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/templates/workshop-notebook.imagestream.yaml.j2
This commit both fixes long deploy times in S2020 and sets variables in the ODH role that are specific to S2020.  It improves deploy times by pipelining waits for the ODH operator to be available (looping over all of the tasks before waiting for each user before looping over waits for each user and then looping over post-wait tasks for each user).
It is necessary to pipeline rather than provision each user in parallel because Ansible [doesn't support running include files asynchronously](https://github.com/ansible/ansible/issues/22716).
NB:  After merging this commit, the student workload for S2020 should change to `ocp4-workload-rhte-analytics_data_ocp_workshop_s2020` instead of `ocp4-workload-rhte-analytics_data_ocp_workshop`.
> pipeline waits for ODH operator deploy in S2020

- ansible/roles/ocp4-workload-ml-workflows-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/per_user_workload.yml
This commit removes a check for `instructor_mode` in the S2020 automation, which we had added to the role for DevConf.
This commit prevents a role failure in S2020 when `instructor_mode` wasn't defined (and adds a default for `instructor_mode` if we need to add a check for it in the future).
- `ocp4-workload-ml-workflows-workshop`
> s2020:  fix instructor_mode-related failures

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
Add a check to ensure the `ImageStream` is properly defined in OpenShift before attempting to import its images.
> Wait for imagestream to be defined before attempting import

- ansible/roles/ocp4-workload-logging/tasks/workload.yml
logging is very unstable 1/2 of deployments have failed logging.
Try to fix this error:
```
TASK [ocp4-workload-logging : Create OpenShift Objects for Logging] ************
Friday 20 September 2019  21:54:18 +0000 (0:00:00.094)       1:02:44.572 ****** 
changed: [clientvm.68ed.internal] => (item=./files/namespace.yaml)
changed: [clientvm.68ed.internal] => (item=./files/operatorgroup.yaml)
changed: [clientvm.68ed.internal] => (item=./files/elasticsearch_catalog_source.yaml)
failed: [clientvm.68ed.internal] (item=./files/elasticsearch_subscription.yaml) => {...}
changed: [clientvm.68ed.internal] => (item=./files/logging_catalog_source.yaml)
changed: [clientvm.68ed.internal] => (item=./files/logging_subscription.yaml)
...ignoring
```
ocp-workload-logging
```paste below …
```
> ocp-workload-logging: add retry to the k8s first task

- ansible/roles/infra-aws-sandbox/defaults/main.yml
- ansible/roles/infra-aws-sandbox/tasks/keypair.yml
- ansible/roles/infra-aws-sandbox/tasks/main.yml
- ansible/roles/infra-aws-sandbox/tasks/manual_cleanup.yml
- ansible/roles/infra-aws-sandbox/tasks/profile.yml
- ansible/roles/infra-aws-sandbox/tasks/regions.yml
- ansible/roles/infra-aws-sandbox/tasks/reset.yml
Sometimes the aws-nuke command fails to nuke a sandbox.
Indeed, it happens that resources have complex dependencies and aws-nuke is not ready to deal with those dependencies.
This change brings workarounds to fix certain situations:
* Deactivate termination protection on all the instances
* VPC deletion when default security group has egress or ingress rules referring other security groups, see  https://github.com/rebuy-de/aws-nuke/issues/410
* VPC deletion when EIP are still associated
aws-infra-sandbox role
> Fix aws-nuke edge cases

- ansible/configs/ocp-workloads/env_vars.yml
- ansible/configs/ocp-workloads/examples/cakephp-openshift-applier.yml
- ansible/configs/ocp-workloads/post_infra.yml
- ansible/configs/ocp-workloads/requirements.yml
- ansible/roles/ocp-workload-openshift-applier/tasks/main.yml
Patch ocp-workloads config to work with openshift-applier.
- add openshift-applier in `requirements.yml`
- add `become_override` to `env_vars.yml`  (default false)
> Ocp workloads with openshift applier

- ansible/roles/ocp4-workload-ceph/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-ceph/tasks/workload.yml
This PR ensures that ceph volumes are removed upon cluster destroy/termination on EC2. Currently volumes can potentially be left intact on EC2 if issues with workload removal arise.
- Set  delete_on_termination during the provisioning of volumes on worker nodes
- Double retries OSD/MON pods to come online, in some environments the current ~5mins gets very close to exhaustion
@pranavgaikwad @jwmatthews
> ocp4-workload-ceph: Clean up volumes on cluster termination

- ansible/configs/ocp4-workshop/post_software.yml
Move calling of workloads to before the cluster shutdown enablement logic.
That way the workloads should not be affected by rotating cluster operators (like API Server operators)
ocp4_workshop
> Move Workloads before cluster shutdown enabled

- ansible/roles/ocp4-workload-security-compliance-lab/tasks/infrastructure.yml
The latest jenkins image contains 2 versions of java (1.8 and 1.11).  The /usr/libexec/s2i/run script currently does not properly select a java version since it was not written to handle the case of more than one version. This pull request will update the run script to select the 1.8 java version
ocp4-workload-security-compliance-lab
> Update jenkins docker build to select a java version

- ansible/configs/ocp-workshop/files/cloud_providers/ec2_cloud_template.j2
Fixes #574   
Added "Domain: vpc" as a property to "AWS::EC2::EIP"  in the AWS CloudFormation Template.  This corrects the error for accounts where "standard" is the default domain value rather than "vpc".
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html
```paste below
```
> Added missing vpc setting to AWS::EC2:EIP

- ansible/configs/ocp-workloads/examples/cakephp-openshift-applier.yml
- ansible/roles/ocp-workload-openshift-applier/tasks/post_workload.yml
This commit, if applied, makes ocp-workload-openshift-applier add the annotation 'openshift.io/requester' for the namespaces specified in `target_namespaces` list.
When the applier workload is run as 'system:admin' and 'ocp_username' var is
provided, the 'target_namespaces' are annotated properly.
ocp-workload-openshift-applier
> openshift-applier workload: allow annotation for ocp_username

- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
This route is only used in print debug user.info tasks later, no need to fail
because of this.
```paste below
```
> Add ignore_errors to the task trying to get the webapp route

- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
Use set -o pipefail to be aware when the ansible-playbook command fails
```paste below
```
> Integreatly: don't fail silently

- ansible/roles/ocp_workload_shared_cluster_access/README.adoc
- ansible/roles/ocp_workload_shared_cluster_access/defaults/main.yml
- ansible/roles/ocp_workload_shared_cluster_access/tasks/main.yml
- ansible/roles/ocp_workload_shared_cluster_access/tasks/post_workload.yml
- ansible/roles/ocp_workload_shared_cluster_access/tasks/pre_workload.yml
- ansible/roles/ocp_workload_shared_cluster_access/tasks/remove_workload.yml
- ansible/roles/ocp_workload_shared_cluster_access/tasks/workload.yml
- ansible/roles/ocp_workload_shared_cluster_access/vars/main.yml
Add ocp_workload_shared_cluster_access
A workload to enable self-provisioner access and create a cluster resource quota for the user.
ocp_workload_shared_cluster_access
> Add ocp_workload_shared_cluster_access

- ansible/roles/ocp-workload-migration/README.adoc
- ansible/roles/ocp-workload-migration/defaults/main.yml
- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
- ansible/roles/ocp-workload-migration/tasks/workload.yml
Adds support for newer versions of migration operator
Removes support for pre-RHTE versions.
ocp-workshop-migration 
```paste below
```
> ocp-workload-migration : Supporting new versions of migration operator

- ansible/configs/ocp4-workshop/lifecycle.yml
5 Minutes to wait for nodes to show NotReady was too long. 2 Minutes should be fine. Setting to 3 Minutes to be safe. This may also eliminate the need or the second go around on CSRs.
> Reduce wait time for startup to 3 minutes

- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/files/deploy_certs.yml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/tasks/workload.yml
Fixed script that is deployed for certbot deploy hook to deploy certificates.
- Delete secrets first before recreate.
- Delete ingress-controller pods (to force picking up of certificates)
> Updated logic to certificate renewal for LE Certs

- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/workload.yml
there was a bug in service mesh 1.0.1 that's a show stopper. 1.0.1 just fixed a CVE which we don't care about for workshops
> revert to 1.0.0 for envoy bugfix

- ansible/configs/linklight-foundations/post_infra.yml
The Ansible Foundations Labs as they are deployed by Ansible Workshop deployer don't carry a guid tag. This adds that to an existing tagging task.
config: ansible-foundations
Very simple change. Requested for cost manangement
> Added guid tag for linklight

- ansible/configs/ocp4-ha-lab/destroy_env.yml
- ansible/configs/ocp4-shared/destroy_env.yml
- ansible/configs/ocp4-workshop/destroy_env.yml
Disable janitor by default
Janitor is a readonly tool that list all the resources that remain for a user.
Sometimes it fails, and also it's an expensive task. Deactivate by default.
```paste below
```
> Disable janitor in deletion

- ansible/configs/ocp4-workshop/lifecycle.yml
Use idempotent logic to retrieve CertificateSigningRequest (do not fail if there are no CSRs - e.g. after a subsequent resume)
This still approves all CSRs (even already approved ones). It may be too risky to merge the commented out when: clause.
> Use idempotent logic to retrieve CertificateSigningRequest

- ansible/roles/ocp4-workload-project-request-template/templates/project_request_template.j2
Project request template can't be created with `kind: templates`, This change sets the kind to `Template`.
> Fix kind on project request template

- ansible/configs/ocp4-workshop/lifecycle.yml
When stopping/starting instances of an environment, we are (temporarily)
filtering only by the tag `guid`. It used to be filtered by (`guid`,
`env_type`). It was changed to (`guid`) because of a change in CF:
`env_type` was not passed in the `cloud_tags` dictionary, and the instances only had `guid` in their tags.
To be able to stop the environments we commented out tags with key `env_type`.
Now this is fixed in Cloudforms, and also `env_type` and `guid` tags are
enforced in agnosticd.
All environments now have both `guid` and `env_type` tags.
This commit if applied will restore filters to (`guid`, `env_type`).
(guid, env_type) is a better filter in case of guid collision.
ocp4-workshop  lifecycle.yml
> ocp4-workshop lifecycle: enable env_type when filtering instances

- ansible/configs/ocp-clientvm/pre_software.yml
- ansible/configs/ocp4-workshop/software.yml
- ansible/roles/bastion/tasks/k8s.yml
- ansible/roles/bastion/tasks/main.yml
Instead of installing EPEL I downloaded all relevant RPMs from our mirrored EPEL Repo and added them to our public GPTE S3 Bucket.
Tested this on Client VM and OCP4 Workshop.
This should pin the "correct (old)" rpms until we have a proper solution.
> Pin EPEL sourced RPMs from GPTE Public S3 Bucket

- ansible/roles/ocp4-workload-security-compliance-lab/tasks/workload.yml
The "checkout all the remote" task was attempting to (unnecessarily) fetch all remote branches when only master is required.  The command now seems invalid for some unknown reason (causing a failure), so it is being removed. Task was likely put in as part of a "copy-and-paste" without being analyzed for necessity.
ocp4-workload-security-compliance-lab role
> Remove broken task to fetch all branches. Only master is necessary

- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
- upstream author created unused ssh-keys
- I did the same copy twice, the second one was busted
> fix broken copy, remove unnecessary ssh keys

- ansible/roles/ocp-workload-ocp-ops-view/defaults/main.yml
- ansible/roles/ocp-workload-ocp-ops-view/tasks/post_workload.yml
- ansible/roles/ocp-workload-ocp-ops-view/tasks/pre_workload.yml
- ansible/roles/ocp-workload-ocp-ops-view/tasks/remove_workload.yml
- ansible/roles/ocp-workload-ocp-ops-view/tasks/workload.yml
Now the role uses the copied .kube/config so that it doesn't have any dependency with any other role
> Use the copied kube/config

- ansible.cfg
- ansible/ansible.cfg
Working on the OSP cloud provider in agnosticd revealed that when using the same hostname for hosts accross different concurrent deployments (for example `bastion`, the deployments fail.
This is because they share the same controlpath socket.
When running `ansible-playbook` with `-vvv`, it shows:
```
ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="cloud-user"' -o ConnectTimeout=60 -o StrictHostKeyChecking=no -F /home/opentlc-mgr/nstephan/63e1/output_dir/ocp4-disconnected-osp-lab_63e1_ssh_conf -o ControlPath=/home/opentlc-mgr/.ansible/cp/7e8c96cf49 bastion
```
Notice the `-o …
> Don't set ControlP* via ansible since we generate our own ssh_conf

- ansible.cfg
- ansible/ansible.cfg
- ansible/cloud_providers/osp_infrastructure_deployment.yml
- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
Setting the `ssh_args=` degraded performance for scp & sftp. It was causing the following warnings:
`[WARNING]: sftp transfer mechanism failed`
`[WARNING]: scp transfer mechanism failed`
This PR reverts that change.
To fix the issue it was originally meant to, the `cloud_provider` for OSP has been changed to add `ansible_ssh_common_args` and append the ssh_conf as well as the ControlPath pointing to a unique socket for each deployment, even if they have the same hostnames (guid will be unique).
This was only applied to the OSP cloud provider, since AWS and others were not experiencing a problem. This change minimizes the potential impact on other cloud providers.
Also, changed the default env_vars to use file repo_method.
> Fix multiple OSP Deployments

- ansible/roles/ocp-workload-gogs/defaults/main.yml
- ansible/roles/ocp-workload-gogs/readme.adoc
- ansible/roles/ocp-workload-gogs/tasks/main.yml
- ansible/roles/ocp-workload-gogs/tasks/post_workload.yml
- ansible/roles/ocp-workload-gogs/tasks/pre_workload.yml
- ansible/roles/ocp-workload-gogs/tasks/remove_workload.yml
- ansible/roles/ocp-workload-gogs/tasks/workload.yml
- ansible/roles/ocp-workload-gogs/templates/configmap_app.j2
- ansible/roles/ocp-workload-gogs/templates/deployment_app.j2
- ansible/roles/ocp-workload-gogs/templates/deployment_postgresql.j2
- ansible/roles/ocp-workload-gogs/templates/project.j2
- ansible/roles/ocp-workload-gogs/templates/pvc_data.j2
- ansible/roles/ocp-workload-gogs/templates/pvc_postgresql_data.j2
- ansible/roles/ocp-workload-gogs/templates/route.j2
- ansible/roles/ocp-workload-gogs/templates/service_account.j2
- ansible/roles/ocp-workload-gogs/templates/service_app.j2
- ansible/roles/ocp-workload-gogs/templates/service_postgresql.j2
- ansible/roles/ocp-workload-gogs/tests/test-local.yml
Workload to deploy gogs. This workload is used in OpenShift BU workshops (for now) and it's meant to replace the role `https://github.com/siamaksade/ansible-openshift-gogs` used in the current APB
> Workload to deploy gogs

- ansible/configs/ocp4-workshop/post_software.yml
This may or may not fix NotReady nodes. Regardless shouldn't hurt.
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/305
> Add tentative fix for cluster shutdown

- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/workload.yml
2.8.0 introduced better support for `is defined` on dicts where stuff doesn't exist. the provisioning server still runs 2.7.9 which needs more loving care.
> fixes issues with ansible 2.7.9 compat

- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/workload.yml
we had to use a snapshot image of the operator catalog and this changes to use a working one
> changes to how operator catalog is deployed

- ansible/roles/ocp4-workload-nexus-operator/tasks/workload.yml
Nexus workload was not correctly checking for the nexus pod as the pod was named something like `nexus-6b6bf487db-94s2f` and it was checking for `nexus`.
We add a k8s_fact to get the pod name to check for it's status.
> Checking correctly for nexus pod

- ansible/roles/infra-osp-resources-destroy/tasks/delete_osp_resources.yml
The teardown was failing when there were instances, volumes, and trunks created by the OpenShift machine-api. 
The trunks were not being deleted by the `neutron purge`, so they will now be deleted prior to that. `neutron purge` will pick up everything else.
The volumes were not being deleted by `openstack project purge`. I think this is because these volumes were created in such a way that they were not set to be deleted with the instance. If we ran this command again, it might pick up these volumes as unused and remove them, but this is more foolproof.
> Add tasks for trunk & volume cleanup

- ansible/roles/ocp4-workload-nexus-operator/tasks/workload.yml
The nexus pod was taking too long to start and the label selector query was returning empty and hence the following task was erroring with an undefined variable. Now we check the status in the CR status for Running.
> The nexus pod was taking too long to start

- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/files/deploy_certs.yml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/templates/api-server.j2
Trying to provision LE certs for the API endpoint through the `ocp4-workload-enable-lets-encrypt-certificates` and the `_lets_encrypt_certificates_install_api: true` variable fails with the following error:
```
TASK [ocp4-workload-enable-lets-encrypt-certificates : Add Certs to API Server] ***
Thursday 21 November 2019  20:06:30 +0000 (0:00:01.580)       0:42:47.789 ***** 
fatal: [clientvm.7hrdp.internal]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'api_hostname' is undefined\n\nThe error appears to be in '/var/lib/awx/projects/_8__agnosticd_ocp4_workshop_prod_128/ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/tasks/workload.yml': line 105, column 7, but may\nbe elsewhere in the file depending on the exact syntax …
```
> Fix broken API LE cert config

- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
Memory quota was too small to complete the labs as they are being written. This increases the default value to 160GB per project.
> Change default memory quota in OSP project

- ansible/roles/ocp-workload-etherpad/defaults/main.yml
- ansible/roles/ocp-workload-etherpad/templates/etherpad.txt.j2
Logic was using user_count which always was 200. Now using num_users with defaults to the amount of users selected when provisioning the environment.
Also, upgraded etherpad to 1.7.5
> Updates to num users logic and 1.7.5 of etherpad

- ansible/roles/ocp4-workload-ccnrd/files/preparelab_ccn.sh
CRW has updated the operator to install CRW 2 by default. This is a major revision to CRW (and underlying Che) so for now we must use the `previous` operator update channel so that existing CCN roadshows continue to use CRW 1.2 while we plan the transition to CRW 2.
> Update workload to track CodeReady Workspaces operator updates

- ansible/roles/infra-osp-resources-destroy/tasks/delete_osp_resources.yml
Fix error:
```
TASK [infra-osp-resources-destroy : Delete any remaining volumes in project] ***
Wednesday 27 November 2019  16:01:07 -0500 (0:00:07.011)       0:00:18.334 **** 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "set -o pipefail; openstack volume list --project 5f15-project -f value -c ID | xargs openstack volume delete", "delta": "0:00:04.411550", "end": "2019-11-27 16:01:12.052755", "msg": "non-zero return code", "rc": 123, "start": "2019-11-27 16:01:07.641205", "stderr": "usage: openstack volume delete [-h] [--force | --purge]\n                               <volume> [<volume> ...]\nopenstack volume delete: error: too few arguments", "stderr_lines": ["usage: openstack volume delete [-h] [--force | --purge]", "                               <volume> [<volume> ...]", …
```
> Fix deletion osp

- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
Increasing security group quotas in this config to allow for IPI installs. Without this, IPI will try to create a number of security groups and will exceed the quota set for this assuming it would be used for UPI installs.
> bump quotas to enable IPI for short term

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/main.yml
in v1.6.x of integreatly we want to use a new inventory file, however the
older releases of integreatly should still maintain using the older hosts
inventory file.
this change adds a version check to ig_version, if it is within the current
known legacy versions that are installable from pds, the older hosts
inventory will be used. Else, the new pds inventory will be used.
the aim of this is to ensure the removal of this logic will be simple once
it is no longer needed.
Integreatly (RHMI)
@trepel @pmccarthy would you mind taking a look, i'm not familiar with how this repo can be tested from an intly perspective?
> ensure backwards compatibility ready for v1.6.x

- ansible/roles/ocp4-workload-app-deploy-homework/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-app-deploy-homework/templates/cluster_resource_quota.j2
Some IBMers have a "_" in their user name. For example benoit_godin@be.ibm.com.
"_" is an invalid character for a Kubernetes resource - so creating a cluster resource quota including the user name fails. Fixed by removing the user name from the name of the quota.
> Fix App Deploy Homework for Users with "_" in their user name

- ansible/roles/infra-osp-template-generate/tasks/generate_osp_template.yml
variables cannot be chained in a set_fact
```paste below
```
> Fix set_fact

- ansible/configs/ocp-clientvm/sample_vars_osp.yml
- ansible/configs/ocp4-cluster/destroy_env.yml
- ansible/configs/ocp4-cluster/env_vars.yml
- ansible/configs/ocp4-cluster/post_infra.yml
- ansible/configs/ocp4-cluster/post_software.yml
- ansible/configs/ocp4-disconnected-osp-lab/destroy_env.yml
- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/post_infra.yml
- ansible/configs/ocp4-disconnected-osp-lab/post_software.yml
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
- ansible/configs/three-tier-app/sample_vars_osp.yml
- ansible/roles/host-ocp4-provisioner/tasks/osp_prereqs.yml
- ansible/roles/infra-osp-create-inventory/tasks/main.yml
- ansible/roles/infra-osp-dns/tasks/nested_loop.yml
- ansible/roles/infra-osp-dns/tasks/pre_checks.yml
Those variables:
ocp_cluster_dns_server
ocp_cluster_dns_zone
are not ocp related. This commit if applied will rename them.
Those are not used neither in OPEN_Admin neither agnosticv gpte repo.
```paste below
```
> Change ddns variable names

- ansible/include_vars.yml
This loop_control.label fails on ansible **2.7.9** when everything is skipped in the
playbook:
```
TASK [Include vars files] *********************************************************************************************************************************************************************
Monday 09 December 2019  03:40:35 -0500 (0:00:00.044)       0:00:04.049 *******
fatal: [localhost]: FAILED! => {"msg": "'dict object' has no attribute 'stat'"}
to retry, use: --limit @/tmp/agnosticd/ansible/destroy.retry
```
This commit if applied fix that error.
> Fix include_vars playbook when everything is skipped

- ansible/lifecycle.yml
The `lifecycle.yml` was using the `os_server_info` module, but that is only available in Ansible 2.9+. We are currently using Ansible 2.8.6 for these OSP configs and the module was called `os_server_facts`. This PR will update the playbook to use the proper module and reference the proper results, including `ansible_facts`.
> Update os_server_info > os_server_facts

- ansible/lifecycle.yml
The last PR missed changing the actual module names. This one fixes that.
> Redo of os_server_facts module change

- ansible/roles/bastion/tasks/main.yml
- ansible/roles/set-repositories/tasks/rhn-repos.yml
The RSHM playbook for the `set-repositories` role had lot of issues and was not reliable. This is an effort to make it idempotent while using `repo_method: rhn` variable.
This has been tested several times in the Novello OSP environment with no errors.
At the same time I'm adding `ignore_errors: yes` to the Mosh Iptables task, to be aligned to the previous tasks for Mosh and others where errors where ignored if the packages are not installed. This was particularly failing in a vanilla RHEL 8.1 deployment.
Role not working properly
The `set-repositories` role
> Modidy RHSM playbook and fix issues for RHEL 8 based bastion

- ansible/lifecycle.yml
The lifecycle playbook fails with test-empty-config
- project_tag is not always defined, for example test-empty-config
- project_tag can be built using env_type+guid
> lifecycle.yml: check guid and env_type instead of project tag

- ansible/roles/ocp4-workload-ccnrd/files/preparelab_ccn.sh
Scale the `rhamt-web-console-executor` pod based on the number of users
The `rhamt-web-console-executor` pod only has a single instance, which means all users running RHAMT are processed sequentially. This fix scales the pod based on the number of users in the cluster.
> Scale the rhamt-web-console-executor

- ansible/roles/ocp4-workload-ceph/files/aws_helper.yaml
- ansible/roles/ocp4-workload-ceph/tasks/pre_workload.yml
This fix runs AWS ansible modules in virtualenv to workaround boto dependencies
```paste below
```
> ocp4-workload-ceph : Workaround for boto dependencies

- ansible/cloud_providers/test_infrastructure_deployment.yml
- ansible/configs/test-empty-config/README.adoc
- ansible/configs/test-empty-config/post_infra.yml
- ansible/configs/test-empty-config/post_software.yml
- ansible/configs/test-empty-config/pre_infra.yml
- ansible/configs/test-empty-config/pre_software.yml
- ansible/configs/test-empty-config/software.yml
Added the ability to fail the test-empty-config at any stage
test-empty-config
(README up to date). Added a task to each stage including clour provider to fail via an optional boolean:
```
fail_pre_infra
fail_test_cloud_provider
fail_post_infra
fail_pre_software
fail_software
fail_post_software
```
For example:
`ansible-playbook main.yml -e @configs/test-empty-config/sample_vars.yml -e '{ "fail_software" : true }'
`
> Added the ability to fail test-empty-config at any stage

- ansible/configs/ans-tower-lab/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Microsoft updated the AMIs for Server 2012 used by the following configs:
ans-tower-lab
Updated both configs CF J2 template for 4 regions:
us-east-1
eu-central-1
ap-southeast-1
ap-northeast-1
> Fixes to updated AMI ids for Server 2012

- ansible/roles/set_env_authorized_key/files/host_ssh_config.j2
The *.example.com Host will be added to the ssh config file that is placed. This is in addition to the existing *.internal and ec2* so that we can support new deployments easily on OpenStack.
> add *.example.com to default ssh conf

- ansible/roles/bastion-lite/files/bastion_ssh_config.j2
- ansible/roles/bastion/files/bastion_ssh_config.j2
Add `*.example.com` to additional ssh config templates for support of OpenStack environments.
> Add example.com to additional templates

- ansible/roles/ocp4-workload-istio-controlplane-student/tasks/workload.yml
- ansible/roles/ocp4-workload-istio-tutorial-student/tasks/deployment_wait.yml
when a cluster is really big it can take a lot longer the mesh operator to do its thing.
> increases waittime for service mesh deployments for large clusters

- ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/tasks/pre_workload.yml
use_ssh_args needed in rsync tasks to copy files to node.
Should fix this problem:
TASK [ocp-workload-pam7-cc-dispute-dmn-pmml : Copy the files used in this role] ***
Wednesday 18 December 2019 22:40:47 -0500 (0:00:01.493) 0:42:43.798 ****
fatal: [clientvm.test-7e17.internal]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -i /home/opentlc-mgr/.ssh/opentlc_admin_backdoor.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --no-motd --exclude=.git,*.qcow2 --out-format=<>%i %n%L /tmp/sandboxes-gpte-OCP4_RHPAM_DMN_AI_DEMO-dev-test-7e17-3910/agnosticd/ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/files/ …
> Added use_ssh_args option to rsync task to copy workload files.

- ansible/roles/host-ocp-nfs/handlers/main.yml
- ansible/roles/host-ocp-nfs/tasks/nfs_exports.yml
There are several changes happening in RHEL 8 regarding NFS Server service. As an example the following ones that prevent using this role as-is:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#the-nobody-user-replaces-nfsnobody_shells-and-command-line-tools
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#the-etc-sysconfig-nfs-file-and-legacy-nfs-service-names-are-no-longer-available_file-systems-and-storage
In order to evaluate the RHEL major version for some tasks, some conditionals have been added to configure the system accordingly to the corresponding RHEL release
Role not working in RHEL 8
Role host-ocp-nfs
> Fix issues with NFS and RHEL 8

- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
Since we are beginning to add solvers and resets to FTL for labs that rely on this config, changing the env var to true by default for FTL.
> Enable FTL by default in ocp4-disco config

- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/requirements.yml
- ansible/roles/bastion-lite/tasks/main.yml
- add new env var for defining whether it will use python3
- rev ftl-injector to latest tag
- fix use_python3 var in bastion-lite role
> FTL injector fixes for OCP4 disconnected config

- ansible/roles/ocp4-workload-istio-controlplane-student/tasks/workload.yml
For really large deployments of this catalog item, the service mesh control plane operator deploys pretty slowly.
> bumps the control plane wait time for really large deployments

- ansible/roles/ocp-workload-optaweb-employee-rostering/defaults/main.yml
- ansible/roles/ocp-workload-optaweb-employee-rostering/readme.adoc
- ansible/roles/ocp-workload-optaweb-employee-rostering/tasks/main.yml
- ansible/roles/ocp-workload-optaweb-employee-rostering/tasks/post_workload.yml
- ansible/roles/ocp-workload-optaweb-employee-rostering/tasks/pre_workload.yml
- ansible/roles/ocp-workload-optaweb-employee-rostering/tasks/remove_workload.yml
- ansible/roles/ocp-workload-optaweb-employee-rostering/tasks/wait_for_build.yml
- ansible/roles/ocp-workload-optaweb-employee-rostering/tasks/wait_for_deploy.yml
- ansible/roles/ocp-workload-optaweb-employee-rostering/tasks/workload.yml
New OptaPlanner Demo to demonstrate the Employee Rostering use case.
ocp-workload-optaweb-employee-rostering
This is the second of two OptaWeb applications that demonstrate selected OptaPlanner use cases in the form of a reference implementation that can be used by solution architects to show how to build a real-world application with Red Hat Business Automation product.
This PR is based on previous work of @DuncanDoyle: #471.
> Add OptaWeb Employee Rostering Demo

- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/post_workload.yml
Since the OC client is pre-installed, we should also pre-install this client.
This is used in the OCS4 module of the ocp4-workload-workshop-admin-storage workshop
NooBaa-CLI-installer
> Pre-install the NooBaa CLI on the bastion host

- ansible/roles/ocp4-workload-ceph/tasks/pre_workload.yml
**SUMMARY**
The worker nodes variable needs to be sanitized before passing to AWS helper script, this is to avoid python structures on values when calling helper script modules
**ISSUE TYPE**
**COMPONENT NAME**
**ADDITIONAL INFORMATION**
This can be reproduced by running the ceph workload and inspecting the values passed to ec2_vol module, see sample : 
```
"ok: [localhost]", "", "TASK [Provisioning new ebs volumes for worker nodes] ***************************", "failed: [localhost] (item={u'name': u'ui-0280e2ccb7ff4f242', u'aZone': u'ueu-west-1a'}) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"item\": {\"aZone\": \"ueu-west-1a\", \"name\": \"ui-0280e2ccb7ff4f242\"}, \"msg\": \"Invalid id: \\\"ui-0280e2ccb7ff4f242\\\"\"}", "failed: …
```
> ocp4-workload-ceph : Sanitize worker var before calling AWS helper scripts

- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/post_workload.yml
This reverts commit 3391068702b8c4ed8b81913d40e45d07229bf0bf.
The commit broke the workshop build since /usr/local/bin is not
writable...
I'm pulling the commit back for now until we have a better plan.
This is used in the OCS4 module of the ocp4-workload-workshop-admin-storage workshop
NooBaa-CLI-installer
> Revert "Pre-install the NooBaa CLI on the bastion host"

- ansible/roles/ocp4-workload-ceph/defaults/main.yml
**SUMMARY**
Ceph rbdplugin crashes when using cephcsi canary images
**ISSUE TYPE**
**COMPONENT NAME**
**ADDITIONAL INFORMATION**
This can be reproduced by running the ceph workload and inspecting the pods on the rookio-ceph namespace : 
```
NAME                                          READY     STATUS             RESTARTS   AGE
csi-cephfsplugin-7cv5b                        2/2       Running            0          5m
csi-cephfsplugin-mb7df                        2/2       Running            0          5m
csi-cephfsplugin-nwtv9                        2/2       Running            0          5m
csi-cephfsplugin-provisioner-0                3/3       Running            0          5m
csi-rbdplugin-j5hxq                           1/2       CrashLoopBackOff …
```
> ocp4-workload-ceph: Switch cephcsi to stable image

- ansible/configs/ocp4-disconnected-osp-lab/destroy_env.yml
- ansible/configs/ocp4-disconnected-osp-lab/files/general-ms.yaml.j2
The `destroy_env` was missing the role to clean up bastion DNS entry. This adds that.
This PR also includes a change to disable trunk ports in the template machineset file provided for the labs using this config.
> OCP4 Disconnected DNS & Trunks

- ansible/configs/osp-migration/destroy_env.yml
- ansible/configs/osp-migration/env_vars.yml
- ansible/configs/osp-migration/infra.yml
- ansible/configs/osp-migration/instance_loop.yml
- ansible/configs/osp-migration/pull_repo.yml
- ansible/configs/osp-migration/requirements.yml
- ansible/configs/osp-migration/sample_vars.yml
- ansible/main.yml
OS PROJECT NAME was missing in the task responsible of the deletion of the user stack.
This PR if applied will fix that.
The PR also contains minor changes:
- Do not create DNS names if the name doesn't include the GUID (failsafe)
- wait for the stack to be deleted, do not fire & forget
- remove unused comments
- add space in jinja2 anchors (style)
- automatically import templates from the redhat-gpe private repo
> Fix deletion in osp-migration config

- ansible/include_vars.yml
`env_vars.yml` is a bad name and should be renamed to `default_vars.yml`.
This commit if applied, will update the `include_vars.yml` play so it looks
for the following files and include them if they exist:
- `cloud_providers/{{ cloud_provider }}_default_vars.yml`
Global default vars related to the cloud provider
- `configs/{{ env_type }}/env_vars.yml`
Legacy env_vars.yml (replaced by default_vars.yml)
- `configs/{{ env_type }}/default_vars.yml`
Default vars of the config
- `configs/{{ env_type }}/default_vars.{{ cloud_provider }}.yml`
`configs/{{ env_type }}/default_vars_{{ cloud_provider }}.yml`
Default vars of the config, specific to a cloud provider
-  `configs/{{ env_type }}/env_secret_vars.yml`
Lecacy secret vars file.
In order not to break current configs, `env_vars.yml` files are …
> Introduce default_vars.yml

- ansible/roles/ocp-workload-migration-training/README.adoc
- ansible/roles/ocp-workload-migration-training/defaults/main.yml
- ansible/roles/ocp-workload-migration-training/files/cors.yaml
- ansible/roles/ocp-workload-migration-training/files/lab8/deploy.sh
- ansible/roles/ocp-workload-migration-training/files/lab8/destroy.sh
- ansible/roles/ocp-workload-migration-training/files/lab8/probe.sh
- ansible/roles/ocp-workload-migration-training/tasks/main.yml
- ansible/roles/ocp-workload-migration-training/tasks/post_workload.yml
- ansible/roles/ocp-workload-migration-training/tasks/pre_workload.yml
- ansible/roles/ocp-workload-migration-training/tasks/remove_workload.yml
- ansible/roles/ocp-workload-migration-training/tasks/workload.yml
- ansible/roles/ocp4-workload-migration-training/README.adoc
- ansible/roles/ocp4-workload-migration-training/defaults/main.yml
- ansible/roles/ocp4-workload-migration-training/files/probe.sh
- ansible/roles/ocp4-workload-migration-training/tasks/main.yml
- ansible/roles/ocp4-workload-migration-training/tasks/post_workload.yml
- ansible/roles/ocp4-workload-migration-training/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-migration-training/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-migration-training/tasks/workload.yml
- ansible/roles/ocp4-workload-migration-training/templates/migstorage.yaml.j2
OCP migration team requested forking to a new name of (very simple) roles dedicated to training because they are SO DIFFERENT from Engineering's roles that they use for hack-fests, RHTE, Summit, CI, etc.
ocp-workload-migration -> ocp-workload-migration-training
No significant changes.
> rename roles for OCP migration training

- ansible/roles/ocp4-workload-logging/files/curator_configmap.yaml
- ansible/roles/ocp4-workload-logging/tasks/workload.yml
Add logging curation defaults to the logging role to prevent disks from filling up.
> Add logging curator configuration to enable log cleanup

- ansible/roles/host-lets-encrypt-certs-certbot/defaults/main.yml
- ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml
- ansible/roles/host-lets-encrypt-certs-certbot/templates/run-certbot.j2
With the introduction of non-route53 DNS providers, we need a new way to request Let's Encrypt certs using a DNS-01 check. These changes modify the `host-lets-encrypt-cert-certbot` role to preserve functionality using r53 DNS but also allow for the `rfc2136` DNS plugin.
> [WIP]Enable Let's Encrypt certs for other DNS plugins

- ansible/roles/bastion/files/bastion_ssh_config.j2
- ansible/roles/set_env_authorized_key/files/host_ssh_config.j2
Reverts redhat-cop/agnosticd#1000
@miteshrh 
I think we should iterate over the hosts and just use the private ip address, instead of a wildcard 192.168.*. Something in the tone of
```
Host {{ host.name }}
Hostname {{ host.private_ip_address }}
...
```
> Revert "ssh_config template update for bastion and set_env_authorized_key roles"

- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/files/rfc2136.ini.j2
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
This PR introduces changes to the `ocp4-disconnected-ha-lab` config. Along with #995 it will provision Let's Encrypt certs for both api and wildcard domain using DNS-01 validation with rfc2136 certbot DNS plugin. The certs will be added to the student user directory for use during the labs.
It also updates the `env_vars` to match what is intended as defaults.
The changes in this PR only affect the `ocp4-disconnected-ha-lab` config.
ocp4-disconnected-ha-lab
> OCP4 Disconnected Config update for certificates

- ansible/roles/bastion-lite/templates/bastion_ssh_config.j2
There is an extra `endif` in the jinja for the ssh config in the `bastion-lite` role. This removes it.
bastion-lite
> fix bastion-lite ssh

- ansible/roles/satellite-public-hostname/tasks/main.yml
SUMMARY
Role: satellite-public-hostname can add public hostname for both cloud aws and osp
ISSUE TYPE
- Feature enhanced
> multiple cloud support added

- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
When writing the authentication and security lab, it was discovered that the `node-ssh` Pod could not SSH to nodes in the cluster other than the one it was running on. This was due to the `master_sg` and `worker_sg` security groups limiting ingress SSH to the bastion. 
This change makes it so that SSH works between all workers and masters within the tenant. You still cannot SSH in from the outside, except to the bastion.
> Update SG rules to allow SSH in network

- ansible/configs/osp-migration/instance_loop.yml
when `metadata.hostname` = `bastion-GUID` for example, register:
- bastion-GUID.CLUSTER.osp.opentlc.com
- bastion.GUID.CLUSTER.osp.opentlc.com
- bastion-GUID.GUID.CLUSTER.osp.opentlc.com
> osp-migration: register hostname directly too

- tests/jenkins/downstream/poll_email.py
This commit, if applied, adds the logic to retry when the IMAP login fails.
It implements the exponential backoff.
This commit fixes an error that occur when there are a significant number
of concurrent jenkins job running:
Traceback (most recent call last):
File "./tests/jenkins/downstream/poll_email.py", line 111, in <module>
args.timeout))
File "./tests/jenkins/downstream/poll_email.py", line 65, in wait_email
M = connect()
File "./tests/jenkins/downstream/poll_email.py", line 54, in connect
M.login(username, password)
File "/usr/lib64/python2.7/imaplib.py", line 520, in login
raise self.error(dat[-1])
imaplib.error: [ALERT] Too many simultaneous connections. (Failure) …
> poll_email.py: handle 'too many connections' error at login

- ansible/roles/ocp4-workload-ceph/templates/cephfs.yaml.j2
- ansible/roles/ocp4-workload-ceph/templates/rbd.yaml.j2
**SUMMARY**
Stable images must use proper secret name for rbd storage class, see : 
https://github.com/ceph/ceph-csi/issues/543
**ISSUE TYPE**
**COMPONENT NAME**
**ADDITIONAL INFORMATION**
> ocp4-workload-ceph: Fix rbd secret name for stable images

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
Ensures that generated passwords for integreatly users are never repeated.
Fixes: https://issues.redhat.com/browse/INTLY-4211
`ocp-workload-integreatly` role 
- Provision a plain RHPDS OCP3 cluster
- Clone this repo and checkout this branch 
- Export the following variables: (change `HOUST_GUID` and `GUID` accordingly)
```sh
HOST_GUID=dimitra-667d                                                
DOMAIN="$HOST_GUID.open.redhat.com"
TARGET_HOST="master.$DOMAIN"
SSH_USER="ec2-user"
SSH_PRIVATE_KEY="ocpkey.pem"
GUID=dimitra-667d
```
- Run the ocp integreatly workload to kick off the integreatly installation: 
```sh
WORKLOAD="ocp-workload-integreatly"                                   
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \ …
```
> Ensure generated passwords are not repeated

- ansible/roles/infra-aws-sandbox/defaults/main.yml
The infra-aws-sandbox role should never be run against a non-sandbox AWS account.
BUT, just in case, we blacklist our known accounts as a failsafe.
if an account is in `aws_nuke_account_blacklist`, aws-nuke will just won't do
anything.
> infra-aws-sandbox: Add new AWS accounts to aws-nuke blacklist

- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
This PR disables the gitea installation for current Integreatly workshops. This is because the image that the gitea operator is deployment no longer exists. A fixed version of Gitea will be included in the next release again.
> disable gitea

- ansible/roles/tower-license-injector/tasks/main.yml
```
[WARNING]: While constructing a mapping from [...]/agnosticd/ansible/roles/tower-license-injector/tasks/main.yml, line 3, column 5, found a duplicate dict key (content). Using last defined value only.
```
Indeed the line is duplicate and needed one to be removed.
roles/tower-license-injector
only a warning...
> Remove duplicate line tower_license content parameter

- docs/Preparing_your_workstation.adoc
Only documentation changes done during the AgnosticD training:
The links were still markdown style and not rendering properly.
Added the necessary dnf commands for Fedora where all dependencies
are properly packaged.
docs/Preparing_your_workstation.adoc
The existing instructions were far too complex for Fedora. It can be so easy as a one liner :smirk:
> Fix links and add Fedora specifics to preparing workstation

- ansible/roles/infra-osp-dry-run/defaults/main.yml
- ansible/roles/infra-osp-dry-run/templates/basic_heat_template.yml.j2
Do not use instance as it has a dependency on the image.
Just create a SSH key in the template.
> dry-run-osp: simplify heat template

- .gitignore
- ansible/action_plugins/agnosticd_user_info.py
- ansible/library/agnosticd_user_info.py
Add agnostid_user_info module implemented as action plugin.
This module is proposed as a replacement for using debug statements.
Switching to this module allows us to more easily programatically
capture output by putting user info directly into the output dir.
agnosticd user info
This PR only adds the `agnosticd_user_info` module. Configs and workloads will need to be adapted to use it. In order to convert to `agnosticd_user_info`:
Go from this:
```
- name: Show generated password
debug:
msg: "user.info: generated password {{ generated_password }}"
```
To this:
```
- name: Show generated password
agnosticd_user_info:
msg: "generated password {{ generated_password }}"
```
This module also supports outputing structured data, so the following may be preferred to allow …
> Add agnosticd_user_info module

- ansible/roles/bastion/tasks/main.yml
The `bastion` role passes `install_dependencies: false` to the `ftl-injector` role. This causes the conditional check to fail and no virtual envs are set up for FTL. The default in the `ftl_injector` role is true for this.
- bastion
> Remove install_dependencies var for ftl-injector task in bastion role

- ansible/configs/osp-sandbox/env_vars.yml
- ansible/configs/osp-sandbox/files/secret.yaml.j2
The original version of this config used the same DNS server and zone for both the provisioned project and what is provided to the user for further use. This will break those apart and allow a new DNS zone, server, (and keys) to be defined.
osp-sandbox
> OSP-Sandbox separate DNS vars

- ansible/configs/osp-sandbox/sample_vars.yml
Fix incorrect setting for env_type in osp-sandbox sample_vars.yml
env_type set incorrectly in sample_vars.yml
> Fix env_type to osp-sandbox in its sample_vars.yml

- ansible/configs/ocp-workloads/ocp-workload.yml
- ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml
- ansible/roles/ocp4-workload-aws-jumpbox/tasks/workload.yml
- ansible/roles/ocp4-workload-aws-jumpbox/templates/create_jumpbox.j2
- ansible/roles/ocp4-workload-aws-jumpbox/templates/delete_jumpbox.j2
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/tasks/workload.yml
This PR fixes the Certbot (and aws jumpbox) roles by specifying the virtualenv binary. It also changes the default for the certbot role to use Python3 instead of Python2.
> Fix certbot

- ansible/roles/infra-osp-template-generate/templates/cloud_template_master.j2
- ansible/roles/infra-osp-template-generate/templates/nested_version/cloud_template_master.j2
Using Python2 generates the strings from an array with module template with u"TEST" instead TEST
Playbook:
> - hosts: localhost
>   gather_facts: false
>   vars:
>     servers: 
>      - "8.8.8.8"
>      - "1.1.1.1"
>   tasks:
>   - template:
>      src: templates/test.j2
>      dest: /tmp/test
Template:
> Original: {{ servers }}
> After PR: [{{ servers | list | join(",") }}]
File generated using Python 2:
> Original: [u'8.8.8.8', u'1.1.1.1']
> After PR: [8.8.8.8,1.1.1.1]
> Small change to support Python2

- ansible/configs/test-empty-config/post_software.yml
Sometimes, the last debug statement is not printed in the logs fetch by
tower-cli job monitor
To fix that, move up the debug task required by Cloudforms so the whole deployment
doesn't fail.
```paste below
```
> Move debug statement up in the play

- ansible/destroy.yml
When running in babylon, the output_dir is created by agnosticd.
Destroy.yml should also include the creation of output_dir, like main.yml.
> destroy: output_dir should be created

- ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/defaults/main.yml
- ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/tasks/workload.yml
Fixes a bug in the RHPAM DMN PMML demo where a Docker build was created based on an IS with a certain tag before that IS tag was available in the cluster.
> Wait for RHPAM IS tags to become available in the cluster.

- ansible/action_plugins/agnosticd_user_info.py
- ansible/completion_callback.yml
- ansible/configs/test-empty-config/post_software.yml
- ansible/configs/test-empty-config/software.yml
- ansible/destroy.yml
- ansible/lifecycle_entry_point.yml
- ansible/main.yml
- ansible/setup_runtime.yml
Add completion callback and userinfo to agnosticd for babylon integration.
Main entry point playbooks
When initially adopted this will result in duplicate completion callbacks from ansible tower and agnosticd. These will not cause any issues with babylon processing.
> Add completion callback

- ansible/configs/three-tier-app/sample_vars/private-dns-osp.yml
Added a sample vars file for three-tier-app using a new pattern of config/<config-name>/sample_vars/ directory as a form of blueprints to allow users to start a particular customized config quickly.
This one allows three-tier-app to deploy onto an OSP cluster with all but the bastion private and not exposed.
three-tier-app enhancement
No change to the code base, just an optional vars files
> Added a sample vars file for a private three-tier-app on OSP

- ansible/roles/infra-osp-resources-destroy/defaults/main.yaml
- ansible/roles/infra-osp-resources-destroy/tasks/main.yml
- ansible/roles/infra-osp-resources-destroy/tasks/project_resources.yml
Introduce `osp_force_delete_all_resource` variable. Defaults to false.
If the user is using `osp_project_create = false` and working with an existing project, he/she cannot delete the resources inside the project.
If the user is alone in that project, he might want to just delete everything and start fresh.
This commit introduces a new variable that allows that.
Also: prefer the osp_project_id when possible because that doesn't requirement
privileged access to list all the project.
> Allow delete all resource when developing from a sandbox

- ansible/configs/ocp4-disconnected-osp-lab/destroy_env.yml
- ansible/configs/ocp4-disconnected-osp-lab/post_infra.yml
- ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml
Another python2 vs python3 problem.
This [task](https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml#L47-L50) was added in #1089 and unfortunately doesn't work in python3 environments since it is not specifying the executable so when we have no pip and no executable defined, it fails.
This PR is a workaround for now. We need a real effort to fix these python2/3 issues, but I need this to unblock for now. Fortunately not all configs have been tagged otherwise all of the OCP4-disconnected deploys would have failed all week.
The PR also has has a small change to add the port option for the DNS tasks similar to what was added to the role.
ocp4-disconnected-ha-lab
> Certbot breaking in python3

- ansible/roles/ocp4-workload-migration/defaults/main.yml
- ansible/roles/ocp4-workload-migration/tasks/workload.yml
- ansible/roles/ocp4-workload-migration/templates/mig_storage.yml.j2
This PR adds optional automated configuration of an OCS MCG bucket. This is intended primarily to be used in conjunction with the ocp4-workload-ocs-operator role.
ocp4-workload-migration role
> add OCS migstorage bucket config option and tasks

- ansible/configs/ocp-clientvm/README.adoc
- ansible/configs/ocp-clientvm/default_vars.yml
- ansible/configs/ocp-clientvm/pre_software.yml
- ansible/configs/ocp-clientvm/requirements-ruby.yml
- ansible/roles/bastion-3scale/defaults/main.yml
- ansible/roles/bastion-3scale/tasks/main.yml
Added changes to the ocp-clientvm to install ruby and 3scale toolbox.
default vars are false so these are not installed.
These tools are needed for 3scale API Lifecycle labs.
> Added role to install 3scale toolbox and ruby.

- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
This PR will extend the ocp4-disconnected config to optionally run the FTL solvers in the software phase. This is accomplished by setting `test_enable: true` and providing the `test_pull_secret`.
> [WIP]Update config to optionally run solver

- ansible/completion_callback.yml
Fix for Ansible 2.7 completion callback error when `__meta__` not defined.
Completion callback playbook.
Prior to Ansible 2.8, default handling behaved differently as describe here:
https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.8.html
This caused the check in the `when` condition in the callback playbook to show noisy errors with Ansible 2.7.
> Fix callback error warning for Ansible 2.7

- ansible/roles/ocp4-workload-ceph/defaults/main.yml
- ansible/roles/ocp4-workload-ceph/templates/storagecluster.yml.j2
- ansible/roles/ocp4-workload-ocs-operator/defaults/main.yml
- ansible/roles/ocp4-workload-ocs-operator/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-ocs-operator/tasks/workload.yml
- ansible/roles/ocp4-workload-ocs-operator/templates/storagecluster.yml.j2
- adds new resource limits on Ceph to allow running on smaller clusters
- replaces NooBaa System CR with StorageCluster CR in ocs-operator workload
ocp4-workload-ocs-operator
```paste below
```
> Improvements to OCS workloads

- ansible/configs/ans-tower-lab/pre_software.yml
Python 2 FTL issue breaking ftl-injector
ans-tower-lab fails
Older FTL implementation commented out.
> Removed old FTL code from ans-tower-lab config, python 2 issue

- ansible/action_plugins/agnosticd_user_info.py
- ansible/completion_callback.yml
- ansible/configs/test-empty-config/post_software.yml
- ansible/configs/test-empty-config/software.yml
- ansible/setup_runtime.yml
Add ability to collect data in the output directory and pass the data in job completion callback.
agnosticd_user_info
Usage example:
```
- name: Return user info data:
agnosticd_user_info:
msg: Generated password is {{ generated_password }}
data:
generated_password: "{{ generated_password }}"
```
> Add data support to agnosticd_user_info

- ansible/roles/ocp-workload-3scale-ocp-vm-ai/defaults/main.yml
- ansible/roles/ocp-workload-3scale-ocp-vm-ai/readme.adoc
- ansible/roles/ocp-workload-3scale-ocp-vm-ai/tasks/main.yml
- ansible/roles/ocp-workload-3scale-ocp-vm-ai/tasks/post_workload.yml
- ansible/roles/ocp-workload-3scale-ocp-vm-ai/tasks/pre_workload.yml
- ansible/roles/ocp-workload-3scale-ocp-vm-ai/tasks/remove_workload.yml
- ansible/roles/ocp-workload-3scale-ocp-vm-ai/tasks/workload.yml
Migration of Ravello Blueprint to AgnosticD - 3scale Implementation course
https://github.com/redhat-gpe/3scale_implementation/issues/191
ocp-workload-3scale-ocp-vm-ai
> Migration of Ravello Blueprint to AgnosticD - 3scale Implementation course

- ansible/include_vars.yml
- ansible/roles/infra-ec2-create-inventory/tasks/main.yml
- ansible/roles/infra-osp-create-inventory/tasks/main.yml
- include_vars.yml: don't stats files on all hosts but only on localhost
> Support ansible_python_interpreter tag  / metadata

- ansible/roles/ocp-workload-optaweb-employee-rostering/defaults/main.yml
- ansible/roles/ocp-workload-optaweb-employee-rostering/readme.adoc
I have successfully tested the deployment on DEV cluster but the deployment times out when the GPTE team tries to set up a catalog item for this demo.
ocp-workload-optaweb-employee-rostering
Another commit in this PR is related to #1089. When I tested the role today I was surprised that it fails both on my machine on on DEV cluster's bastion with the following:
```
TASK [ocp-workload-optaweb-employee-rostering : Remove user Project] **********
Wednesday 12 February 2020  15:27:16 +0100 (0:00:00.024)       0:00:00.667 **** 
fatal: [bastion.dev.openshift.opentlc.com]: FAILED! => {
"changed": false,
"module_stderr": "Shared connection to bastion.dev.openshift.opentlc.com closed.\r\n",
"module_stdout": "/bin/sh: /opt/virtualenvs/k8s/bin/python: No such file or …
```
> Increase OptaWeb Employee Rostering build timeout

- ansible/roles/ocp-workload-migration/templates/operator.yml.j2
- ansible/roles/ocp4-workload-migration/defaults/main.yml
- ansible/roles/ocp4-workload-migration/templates/mig-operator-subscription-downstream.yml.j2
Upgrade CAM Operator to version 1.1 for both OCP 3 and 4 workloads.
Part of Summit 2020 Lab for OpenShift Migrations
cc @pranavgaikwad @djwhatle @jmontleon
> OpenShift Migration Workload:  Upgrade to use CAM 1.1 in both OCP 3 and 4 workloads

- ansible/configs/three-tier-app/post_software.yml
Bringing config `three-tier-app` up to date with much more recent rpms breaks ipa code, this issue has also been seen elsewhere. Fixed by restarting both key services in the correct order.
config three-tier-app
Should perhaps migrate into the `bastion-opentlc-ipa` role
> Work around for oddjobd needing messagebus service restart

- ansible/configs/osp-sandbox/env_vars.yml
removed the dns_nameservers parameter from env_vars.yaml
see https://bugzilla.redhat.com/show_bug.cgi?id=1748015 for more info
osp-sandbox config
> removed dns_nameservers var see: bugzilla 1748015

- ansible/configs/ocp4-workshop/lifecycle.yml
We didn't set the k8s virtualenv. Therefore the cluster start logic never approved CSRs. :-( Resulting in broken RHPDS clusters.
> Add ansible_python_interpreter to ensure cluster recovery works.

- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/workload.yml
For ocp4-workload-homeroomlab-starter-guides, don't install the cluster logging operator in the workload.
> Don't install cluster logging operator in the workload.

- ansible/roles/ocp4-workload-ccnrd/tasks/install-codeready.yaml
- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
CodeReady's default token lifespan of 5 minutes is insufficient for day-long workshops, so this increases the timeout to 8 hours. Otherwise users constantly get logged out and have to log back in to continue.
ocp4-workload-ccnrd
> increase codeready keycloak token lifespan

- .gitignore
After running the example config, `git status` reported that `action_plugins/agnosticd_user_info.pyc` is not tracked. The `.pyc` files shouldn't be versioned as they are generated at runtime.
The change is pretty simple as it only adds `*.pyc` to `.gitignore`.
> Add *.pyc files to .gitignore

- .github/workflows/asciidoc.yml
- docs/Contributing.adoc
- docs/Creating_a_cloud_deployer.adoc
- docs/Creating_a_config.adoc
- docs/Creating_an_OpenShift_Workload.adoc
- docs/FAQ.adoc
- docs/Makefile
- docs/Preparing_your_workstation.adoc
- docs/README.adoc
- docs/Supported_Cloud_Providers.adoc
- docs/User_stories.adoc
This PR will automatically build the docs/ folder into pretty html. If merged, it will look something like this; https://jamesread.github.io/agnosticd/
The hope is that HTML/pretty versions of this documentation will make the repository a little more accessible for first time contributors. 
Here's how it works;
1. On commit, this will fire a GitHub post-commit action [asciidoc.yaml](https://github.com/jamesread/agnosticd/blob/pr-asciidoc-ghpages/.github/workflows/asciidoc.yml)  
2. This action fires up an asiidoctor container, and builds `docs/README.adoc` into `public/index.html`
3. `public/index.html` is pushed to a gh-pages branch automatically. See: https://github.com/jamesread/agnosticd/tree/gh-pages
This commit mostly comprises 2 things; 1) A GitHub action, and 2) Formatting changes …
> Publish docs/*.adoc's into into GitHub pages pretty HTML

- ansible/configs/ansible-tower-implementation/default_vars_osp.yml
Edited default_vars_osp.yaml to open port 80 for tower instance.
> Allowed port 80 in SG

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/add_che_user.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/create_che_workspace.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-codeready.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/verify_che_workspace.yaml
Use default RHPDS password for CRW accounts to match OCP password.
Add an extra attempt to pre-start workspaces for those that tried to start before their container images were pulled down.
> Update CRW password; increase robustness of pre-warming of workspaces

- ansible/configs/ansible-tower-implementation/post_software.yml
- ansible/roles/tower-license-copy/tasks/main.yml
Role `tower-license-copy` created.
Edited configs/ansible-tower-implemetation/post_software.yml to call the role.
> Role added to copy tower license

- ansible/roles/ocp4-workload-quarkus-workshop/templates/devfile.json.j2
By declaring `~/.m2` as a volume in the Che devfile, the pre-cached artifacts in the underlying container image are hidden. This fixes that so that builds go faster and take less network to do so.
> remove m2 mount so pre-cached artifacts are visible

- ansible/roles/ocp-workload-optaweb-employee-rostering/tasks/workload.yml
The application becomes unresponsive after being used for a short time
when relying on the default memory settings. I even saw it crash with
OutOfMemoryError once.
Increasing the heap memory size addresses these issues. I used the
application with increased JVM memory settings for some time and the memory consumption
settled down on 1.4 Gi so I assume 2 Gi should be enough (unless there's
a memory leak).
DM7 OptaWeb Employee Rostering Demo
The demo is not yet in production. It has passed DEV onboarding during which I have identified the memory issue. I'd like to get this merged before I request moving the demo from DEV to TEST stage.
```paste below
```
> OptaWeb Employee Rostering: Increase JVM heap memory

- ansible.cfg
hide this:
```
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
```
> Deactivate localhost warning

- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
By declaring `~/.m2` as a volume in the Che devfile, the pre-cached artifacts in the underlying container image are hidden. This fixes that so that builds go faster and take less network to do so.
> dont hide .m2

- ansible/configs/ansible-windows/env_vars.yml
- ansible/configs/ansible-windows/pre_software.yml
- ansible/configs/ansible-windows/sample_vars.yml
ansible-windows had old style ftl-injection code and incorrect vars
Simple fix ftl-injection now done in bastion role. Plus sample_vars had an incorrect env_type
> Fix ansible windows 2020 03 02

- ansible/configs/ocp-workshop/README.adoc
- ansible/configs/ocp-workshop/files/cloud_providers/ec2_cloud_template.j2
- ansible/roles/infra-ec2-template-generate/defaults/main.yml
DO NOT MERGE
This is an initial test of changing the default AWS AMI image to the less expensive AMIs for ocp-workshop (OCP3) based workloads.
Please checkout this PR and test with your workloads ASAP.
ocp-workshop
RHEL AWS AMIs with the string *Hourly* in the name are to be avoided because they cause a support fee with AWS.  RHEL AWS AMIs with the string *Access* in the name MUST be used to avoid the AWS support fee.  All of these images belong to the AWS AMI OwnerId: 309956199498
> ocp-workshop - set default AMI to RH Cloud Access

- ansible/cloud_providers/osp_default_vars.yml
- ansible/configs/ocp-clientvm/default_vars_osp.yml
- ansible/configs/ocp4-cluster/destroy_env.yml
- ansible/configs/ocp4-cluster/post_infra.yml
- ansible/configs/ocp4-disconnected-osp-lab/destroy_env.yml
- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/files/rfc2136.ini.j2
- ansible/configs/ocp4-disconnected-osp-lab/post_infra.yml
- ansible/configs/osp-migration/dns_loop.yml
- ansible/configs/osp-migration/env_vars.yml
- ansible/configs/osp-sandbox/env_vars.yml
- ansible/configs/osp-sandbox/files/secret.yaml.j2
- ansible/roles/infra-osp-dns/tasks/nested_loop.yml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/templates/rfc2136.ini.j2
- docs/First_OSP_Env_walkthrough.adoc
Deploying on an existing OSP infrastructure with own DNS server and an already existing key, there is no user variable to specify your own value of "key_algorithm" for nsupdate module of Ansible. Only key with the default value "hmac-md5" can be used.
Proposed changes allow user to define their own "ddns_key_algorithm". The default value "hmac-md5" is used in case the new "ddns_key_algorithm" user definable variable is not used.
Fixes #1216
n/a
n/a
> CHANGE included ddns_key_algorithm variable in all related files

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/remove_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
In the integreatly ansible installation repo, we've just changed the default for Gitea to be "false", so there shouldn't be a need to override that here.
Additionally, the default for amq_streams is already "true" in the group vars for the "PDS" flavour of integreatly (which is used here), so that also shouldn't need to be overridden.
integreatly
> Clean up intly vars

- ansible/configs/ansible-tower-advanced/env_vars.yml
The default sizing was too small and needed to be increased for Tower UI to run properly.
config ansible-tower-advanced
n/a
> Increase AWS instance type to t2.large

- ansible/roles/ocp4-workload-quay-operator/defaults/main.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/workload.yml
Quay Operator has a bug where the SCC doesn't get picked up resulting in a crashing Quay Pod. Added workaround to kill pod to pick up SCC.
> add workaround for Quay Operator bug

- ansible/configs/ocp-clientvm/files/cloud_providers/ec2_cloud_template.j2
stopgap so Noelia can use RHEL81GOLD on ocp-clientvm 
ocp-clientvm
aws ami template creation and ami definition and selection process needs to be generalized.  I'm working on it in another workstream.
> add stopgap RHEL81GOLD to config ocp-clientvm

- ansible/configs/ocp-clientvm/files/cloud_providers/ec2_cloud_template.j2
- ansible/roles/infra-ec2-template-generate/defaults/main.yml
fixed ocp-clientvm  set `clientvm_image_name=RHEL81GOLD` failed to apply to single-instance clientvm.  Only worked for deploying multiple clientVMs  
ocp-clientvm
infra-ec2-template-generate
> Clientvm rhel81 and gold

- ansible/configs/sap-hana/default_vars.yml
A new flavour has been created and assigned by default to the HANA instances in order the reduce the total blueprint size and required resources.
> Change the default flavour for HANA hosts

- ansible/roles/ocp-workload-optaweb-employee-rostering/tasks/workload.yml
The application becomes unresponsive and runs out of memory if user loads and uses all of the available tenants. Increasing initial JVM heap from 2 to 4 Gi and allowing max heap of 8 Gi should allow the user to work with all of the tenants that are available in the app out of the box.
DM7 OptaWeb Employee Rostering Demo
Discovered in the TEST stage by testing the demo more thoroughly.
> Increase OptaWeb Employee Rostering memory to 4 Gi

- ansible/configs/ocp4-cluster/destroy_env.yml
This commit, if applied, fixed the following error:
```
ERROR! the role 'infra-gcp-create-inventory' was not found in /home/travis/build/redhat-cop/agnosticd/ansible/configs/ocp4-cluster/roles:/home/travis/build/redhat-cop/agnosticd/roles:/home/travis/build/redhat-cop/agnosticd/ansible/roles:/home/travis/build/redhat-cop/agnosticd/ansible/configs/ocp4-cluster
The error appears to be in '/home/travis/build/redhat-cop/agnosticd/ansible/configs/ocp4-cluster/destroy_env.yml': line 64, column 13
```
> ocp4-cluster: use include_role because gcp role don't exist yet

- ansible/roles/ocp4-workload-nfs-server/README.md
- ansible/roles/ocp4-workload-nfs-server/defaults/main.yml
- ansible/roles/ocp4-workload-nfs-server/files/Dockerfile
- ansible/roles/ocp4-workload-nfs-server/files/run_nfs.sh
- ansible/roles/ocp4-workload-nfs-server/tasks/main.yml
- ansible/roles/ocp4-workload-nfs-server/tasks/post_workload.yml
- ansible/roles/ocp4-workload-nfs-server/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-nfs-server/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-nfs-server/tasks/workload.yml
- ansible/roles/ocp4-workload-nfs-server/vars/main.yml
This role can be used to deploy an NFS server pod inside an OpenShift cluster. It is helpful when you need more than RWO that is provided with AWS & OpenStack.
A PV will be provisioned for the NFS server pod
A new storage class will be created
A project and associated objects will be created to run the NFS server pod
A statefulset will be created to deploy the NFS server pod
The script that runs will set up a finite number of exports (to be variablized)
PVs will be created
ocp4-workload-nfs-server
> OCP4 NFS workload role

- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/OWNERS
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/OWNERS
Not sure if there is an official policy to describe who owns each role, but I've adopted owners file for this purpose. Maybe something that should be done by default for each role?
Summit 2020
> Added owners for ocp4-workload-pam-fraudmanagement-workshop

- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
Minor tweak to the admin-storage workshop workload for an env var
> sets OC version when deploying labguide

- tools/virtualenvs/openstack-ansible-2.9-python3.txt
- tools/virtualenvs/openstack-ansible-latest.txt
To use `foreman-ansible-modules` for satellite communication we need `apipy` installed.
I believe it's quite small dependency, so there is no need to create separate environment for it
- `tools/virtualenvs/openstack-ansible-latest.txt`
- `tools/virtualenvs/openstack-ansible-2.9-python3.txt`
> Add apipy to openstack virtualenv

- ansible/configs/ocp-workshop/files/cloud_providers/ec2_cloud_template.j2
There was a bug in the ocp-workshop template: the same image_id was being used in two regions.
This fixes that by using the agnosticd var aws_image_region_mapping in the ocp-workshop cloudformations template.  var aws_dns_mapping added for more template clarity and brevity.
ocp-workshop
> ocp-workshop: simplify ec2 cloudformations templ

- ansible/configs/satellite-multi-region/requirements.yml
- ansible/configs/satellite-multi-region/software.yml
- ansible/configs/satellite-vm/requirements.yml
- ansible/configs/satellite-vm/software.yml
- ansible/install_galaxy_roles.yml
- ansible/roles/satellite-manage-organization/README.adoc
- ansible/roles/satellite-manage-organization/tasks/main.yml
- ansible/roles/satellite-manage-organization/tasks/version_6.x.yml
- tests/static/requirements.txt
- tests/static/syntax-check.sh
This is switching the organization creation for satellite to be done through 'foreman-ansible-modules'
satellite-manage-organization
The satellite team provides sets of ansible modules. It only makes sense to use them. This is a first PR with this change, others will follow after we set course in this one.
The PR needs to have the collection of foreman modules installed locally with it's dependencies.
I've opened PR for them to get taken care of automatically
```bash
pip install apypie
ansible-galaxy collection install theforeman.foreman
```
> Satellite role - create organization through foreman-ansible-modules

- ansible/configs/osp-migration/instance_loop.yml
For some labs we need to add some extradns, for example wildcard. Example on the **stack_user.yaml**:
```
"extradns": 
- str_replace:
template: "*.apps-REPL"
params:
REPL: {get_param: project_guid}
```
> Adding extradns for instances

- ansible/roles/ocp-workload-optaweb-employee-rostering/tasks/workload.yml
#1279 didn't fix the application instability. I didn't know about resource [requests and limits](https://docs.openshift.com/container-platform/3.11/dev_guide/compute_resources.html#dev-requests-vs-limits). What I observed after giving JVM more memory was that the process exceeded the container memory limit after some time and was killed by OOM killer. I have educated myself on this topic and I am now setting memory limit to a number higher than the JVM's max heap size to avoid being killed by OOM killer.
Fix verified by solving all built-in data sets several times.
DM7 OptaWeb Employee Rostering Demo
> Set memory request and limit

- .gitignore
- ansible/install_galaxy_roles.yml
- docs/README.adoc
Galaxy roles in development branch are currently broken because of a typo. This PR includes a fix.
It also fixes path for ansible collections, new feature added in a previous commit.
> Fix typo in galaxy requirements + fix  collections  path

- ansible/roles/ocp4-workload-ccnrd/files/eventing-operator.v0.12.0.csv.yaml
- ansible/roles/ocp4-workload-ccnrd/files/knative-serving-cm.yaml
- ansible/roles/ocp4-workload-ccnrd/files/serverless-operator.v1.4.1.csv.yaml
- ansible/roles/ocp4-workload-ccnrd/files/serverless_eventing_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/serverless_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/add_role.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-serverless.yaml
Override hard-coded memory settings of knative-eventing and knative-serving to support large deployments. Also update to latest versions of each.
The knative-eventing and knative-serving operators create hard-coded, and small memory limits for their webhooks. For large clusters, this easily overwhelms the webhooks and they go into crash loops with OOMKilled (out of memory - killed). This causes some exercises in this workshop to fail that deal with serverless and Knative eventing with Kafka.
There is no easy way to override these values as they are hard-coded into the manifests of the operator, so this bugfix overrides that by providing customized manifests for the operator. @danieloh30 and I have been consulting with the serverless eng team on …
> Workaround OOMKilled issues with knative-serving and knative-eventing

- ansible/configs/ocp4-disconnected-osp-lab/software.yml
The annotations in grafana were extreme. Removing the install annotations to focus on the actual disk performance once the cluster is running. Still optional to enable the tests.
> remove overwatch annotations for install test

- ansible/roles/ocp-client-vm/tasks/main.yml
The ocp-client-vm role was trying to install packages on RHEL 8 that were causing problems or should no longer be necessary in RHEL 8 - specifically docker. This adds a conditional to differentiate between the list of packages for RHEL 8 vs RHEL 7
> Add rhel 7/8 conditional for clientvm role

- ansible/roles/ocp4-workload-quay-operator/tasks/workload.yml
Prevent a snowflake situation where the pod existed but no container status did yet.
> Add 10 second delay

- ansible/configs/sap-hana/default_vars.yml
- ansible/configs/sap-hana/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/sap-hana/files/hosts_template.j2
- ansible/configs/sap-hana/software.yml
Change bastion hostname to get more sap-specific one and avoid conflicts with others on Satellite. Change how inventory for ansible in the bastion is generated.
> Change bastion hostname and ansible inventory

- ansible/configs/ocp-clientvm/files/repos_template.j2
- ansible/configs/ocp-clientvm/pre_software.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/set-repositories/tasks/satellite-repos.yml
Some additional changes to support agnostic clientVM for RHEL 8 & 7. Mainly changes to satellite-repo role so we can register systems instead of bypassing with certs. Key change was adding a randomization to the hostname so they don't overwrite each other in Satellite.
ocp-clientvm
common
> [WIP] changes to satellite role for rhel8

- ansible/roles/set-repositories/tasks/main.yml
- ansible/roles/set-repositories/tasks/satellite-repos.yml
The rhel 7 repos were broken in the previous due to gather_facts being disabled. This adds a task to run setup and gather minimal facts for the necessary role.
> Fix set-repositories role

- ansible/configs/satellite-vm/README.adoc
- ansible/configs/satellite-vm/default_vars_ec2.yml
- ansible/configs/satellite-vm/default_vars_osp.yml
- ansible/configs/satellite-vm/software.yml
- ansible/roles/satellite-libvirt/README.adoc
- ansible/roles/satellite-libvirt/defaults/main.yml
- ansible/roles/satellite-libvirt/handlers/main.yml
- ansible/roles/satellite-libvirt/tasks/libvirt.yml
- ansible/roles/satellite-libvirt/tasks/main.yml
- ansible/roles/satellite-libvirt/tasks/proxy_libvirt.yml
- ansible/roles/satellite-libvirt/templates/network/default.xml.j2
- ansible/roles/satellite-libvirt/templates/pool/default.xml.j2
- ansible/roles/satellite-provisioning/README.adoc
- ansible/roles/satellite-provisioning/defaults/main.yml
- ansible/roles/satellite-provisioning/tasks/main.yml
- ansible/roles/satellite-provisioning/tasks/provisioning_resources.yml
For OpenStack the most convenient method of provisioning is nested libvirt provisioning.
This PR adds ability to install libvirt and enables the provisioning on it. 
- config `satellite-vm`
- new role `satellite-libvirt`
- new role `satellite-provisioning`
Role `satellite-libvirt` installs libvirt eighter on satellite itself, or it's capsule, role `satellite-provisioning` set up the satellite to be able to provision on this resource.
> Satellite roles enabling libvirt provisioning

- ansible/configs/osp-migration/post_software.yml
For deploy bookbag with OSP+VNC we require information of OSP (user, password, auth url)
> Fill agnosticd_user_info with OSP information for bookbag+ospvnc

- ansible/configs/osp-migration/env_vars.yml
We need to short the project name as much as possible to avoid errors (max length is 64)
> Remove student name from project name

- ansible/roles/set-repositories/tasks/satellite-repos.yml
In #1344 was introduced a typo. It fails to register to the satellite now.
Role `set-repositories`
> Fix typo in set-repositories/satellite-repos.yml

- ansible/cloud_providers/azure_infrastructure_deployment.yml
- ansible/cloud_providers/gcp_infrastructure_deployment.yml
- ansible/configs/aro/env_vars.yml
the various ocp-workshop configs when using Azure generate the keys in pre_software.yml where ocp4-cluster does it in pre_infra.yml (most of my testing), so I updated the infrastructure deployment for azure and gcp to check if the files exist instead of if the variable is set.
gcp_infrastructure_deployment.yml
azure_infrastructure_deployment.yml
config/aro
Also added the variable env_authorized_keys variable to config/aro so it doesn't cause any errors in case anything decides to look for the value in the future too.
> Checking if generated key were created or not before deployment

- ansible/roles/ocp4-workload-ccnrd/files/kafka_knative_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/knative-serving-cm.yaml
- ansible/roles/ocp4-workload-ccnrd/files/osm_namespace.yaml
- ansible/roles/ocp4-workload-ccnrd/files/osm_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/pipelines_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/serverless-operator.v1.5.0.csv.yaml
- ansible/roles/ocp4-workload-ccnrd/files/serverless_subscription.yaml
Updates to recently released/latest versions of OpenShift Serverless, Knative eventing, Knative Kafka Eventing, OpenShift service mesh operators
This also includes an update to the workaround that we are carrying until OCP 4.4 is released as originally implemented in https://github.com/redhat-cop/agnosticd/pull/1308
cc @danieloh30
> Upgrade Knative serving/eventing/kafka/istio operators to latest

- ansible/configs/satellite-vm/README.adoc
- ansible/configs/satellite-vm/default_vars.yml
- ansible/configs/satellite-vm/software.yml
- ansible/roles/satellite-manage-hostgroup/README.adoc
- ansible/roles/satellite-manage-hostgroup/tasks/main.yml
Add role `satellite-manage-hostgroup` to add ability to manage hostgroups.
Role `satellite-manage-hostgroup`
Takes array of hostgroups as `satellite_hostgroups` and create them in the satellite.
> Satellite role to manage hostgroups in satellite

- ansible/configs/satellite-vm/README.adoc
- ansible/configs/satellite-vm/default_vars.yml
- ansible/configs/satellite-vm/software.yml
- ansible/roles/satellite-manage-userroles/README.adoc
- ansible/roles/satellite-manage-userroles/tasks/main.yml
- ansible/roles/satellite-manage-userroles/tasks/role.yml
- ansible/roles/satellite-manage-userroles/tasks/user.yml
Add role satellite-manage-userroles to add ability to manage authorization through users and roles.
Role `satellite-manage-userroles`
Takes array for roles as `satellite_roles` and array for users as `satellite_users` and create them in the satellite.
> Satellite role to manage authorization - users and user roles

- ansible/configs/sap-hana/default_vars.yml
The CI is failing because there is a not required variable used for local testing in the config. Removing that variable.
> Removing not required key_name

- ansible/configs/test-empty-config/post_software.yml
Add `test_empty_config_multi_user` variable to optionally call `agnosticd_user_info` with multiple users.
config test-empty-config
> Add variable test_empty_config_multi_user

- ansible/roles/satellite-manage-hostgroup/README.adoc
- ansible/roles/satellite-manage-hostgroup/tasks/main.yml
Add domain, subnet, subnet6 and compute_profile to the hostgroup
Role `satellite-manage-hostgroup`
Now we should be able to set up all the parameters for seamless provisioning
> Satellite - add networking setting for hostgroup

- ansible/configs/satellite-vm/README.adoc
- ansible/configs/satellite-vm/default_vars_osp.yml
- ansible/roles/satellite-provisioning/README.adoc
- ansible/roles/satellite-provisioning/defaults/main.yml
- ansible/roles/satellite-provisioning/tasks/provisioning_resources.yml
Ability to customize satellite's subnet name
Role `satellite-provisioning`
Previously I had an static name for the subnet and network - that's not a great idea.
> Satellite - add name to subnet

- ansible/roles/satellite-provisioning/tasks/provisioning_resources.yml
Keeps the default provisioning url.
Role `satellite-provisioning`
As we've solved the dns resolution issue in satellite, we don't need to change the provisioning url anymore.
> Satellite - keep default provisioning url

- ansible/configs/test-empty-config/post_software.yml
Simple fix to test-empty-config user info data to clean up example for documentation purposes.
test-empty-config
The code included a variable that did not make sense in context.
> Fix to test-empty-config user info data

- ansible/roles/set-repositories/tasks/satellite-repos.yml
Modification and addition in the role: set-repositories
Role : set-repositories
Conditional value changed from aws to ec2
```
- name: Remove rh-amazon-rhui-client package
tags: packer
package:
name: rh-amazon-rhui-client
state: absent
when: cloud_provider == 'ec2'
```
Following code gives ease to filter nodes in satellite sepcially especially when deployed on osp ( novello ) cloud.  
```
- name: Randomize hostname for Satellite
copy:
dest: /etc/rhsm/facts/katello.facts
content: {"network.fqdn": "{{ inventory_hostname }}.{{guid}}.internal-{{ ansible_date_time.iso8601_basic | lower }}"}
when: cloud_provider == 'osp'  
```
> modified Role:set-repositories

- ansible/configs/ansible-workshops/ansible.cfg
- ansible/configs/linklight-foundations/ansible.cfg
Ansible Workshop (aka linklight) based configs have their own ansible.cfg (historically the routers were sensitive to ssh timeouts etc). Builds on PR #1385 and extends same change to 2 other related configs.
This adds roles_path to pick up new roles structure changes in agnosticd
Ansible Workshop based configs are a special case in that they are a deployed wrapped in a deployed plus the network equipment they sometimes deploy are sensitive to ssh config.
config/ansible-workshops
config/linklight-foundations
> Added roles_path ansible.cfg in all ansible_workshop based configs

- ansible/configs/ocp4-disconnected-osp-lab/files/fio-test.sh.j2
- ansible/configs/ocp4-disconnected-osp-lab/files/fio.Dockerfile
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
These changes clean up some of the testing tasks to help evaluate performance of OCP on OSP config. The updated script should send results directly to overwatch. It can still be enabled or disabled by var.
> Update test tasks for OCP on OSP

- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/workload.yml
a recent update to the way we deploy something broke something else. This fixes that.
> necessary change to references to deployed items

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/templates/cephobjectstore.yaml.j2
Fixes an error in role `ocp4-workload-rhte-analytics_data_ocp_workshop` when creating a CephObjectStore
ocp4-workload-rhte-analytics_data_ocp_workshop
> Fix ODH CR for CephObjectStore

- ansible/configs/ansible-tower-advanced/env_vars.yml
Bumped Tower version to 3.6.2 for ansible-tower-advanced and simplified admin password (it was a mess to test things)
(somewhere in-between)
config ansible-tower-advanced
Required for the Summit
> Tower version to 3.6.2 for ansible-tower-advanced and simplified password

- ansible/roles/satellite-manage-manifest/README.adoc
- ansible/roles/satellite-manage-manifest/tasks/version_6.x.yml
Adds ability to access manifest secured by basic auth.
Role `satellite-manage-manifest`
We need to download secured manifest files.
> Satellite manifest add basic auth for manifest fetch

- ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
Set the `public_dns_name` for all the hosts that have the `public_dns: true` flag
`infra-osp-create-inventory`
Adding a flag to `metadata` to state what instances have the dns enabled, setting the fact `has_public_dns` and afterwards using that flag to set `public_dns_name` for all linux hosts.
Fixing a typo in groups and `metadata` definition.
> OSP - public hostname

- ansible/roles-infra/infra-osp-template-generate/defaults/main.yaml
Enable pings for `DefaultSG` - unsure if it's necessary, but without it the build hangs on non-public hosts because of failed ping.
Role `infra-osp-template-generate`
Allow public ICMP (ping)
> Enable public ping by default

- ansible/roles/satellite-capsule-rex/README.adoc
- ansible/roles/satellite-capsule-rex/defaults/main.yml
- ansible/roles/satellite-capsule-rex/tasks/main.yml
Satellite ssh config to enable remote execution run against hosts created by agnosticd
Role `satellite-capsule-rex`
Role adds ssh config to be able to ssh to the agnosticd provisioned hosts without DNS record.
> Satellite remote execution capsule config

- ansible/roles/satellite-manage-setting/README.adoc
- ansible/roles/satellite-manage-setting/tasks/main.yml
Role to manage Satellite settings
Role `satellite-manage-setting`
Allows to manage settings of satellite.
> Satellite role to manage settings

- ansible/configs/ansible-tower-implementation/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/multi-cloud-capsule/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/sap-hana/files/cloud_providers/osp_cloud_template_master.j2
- ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_master.j2
Fixing metadata setting for custom `stack_templates`
Custom `osp_cloud_template_master` templates
I've introduced a metadata earlier, but forgot to set them in all templates
> Fix osp public dns metadata for all cloud_templates

- tools/virtualenvs/openstack-ansible-2.9-python3.txt
- tools/virtualenvs/openstack-ansible-latest.txt
I've introduced misspelled dependency in previous PR.
virtualenv `openstack-ansible`
I've brought `apipy` instead of `apypie` :roll_eyes:
> Fix dependencies for foreman-ansible-modules

- ansible/roles/satellite-insights/README.adoc
- ansible/roles/satellite-insights/handlers/main.yml
- ansible/roles/satellite-insights/tasks/main.yml
- ansible/roles/satellite-insights/tasks/version_6.7.yml
Role that enables satellite insights reuse the same account for multiple labs.
Role `satellite-insights`
We need to tweak the gem for accessing Red Hat cloud to have specific `branch_id` for every satellite to distinguish between labs.
> Satellite insights role - enable multiple labs

- ansible/configs/ocp4-disconnected-osp-lab/files/fio-test.sh.j2
When tests are enabled, the results were not being reported to overwatch because of a missing var in the payload. GUID is not an env var on the masters, so this will set it when the template is written out by Ansible.
> Update fio test script to report to overwatch

- ansible/configs/selinux-policy/env_vars.yml
Set ansible_python_interpreter for selinux-policy config and set image to RHEL81.
selinux-policy config
> Set ansible_python_interpreter for selinux-policy config

- ansible/roles/satellite-installation/tasks/version_6.7.yml
The `web console` button in satellite open the webconsole in the same tab. It feels bit weird to first users and those are the target group in the labs.
`satellite-installation`
> Satellite - fix webconsole button

- ansible/configs/ansible-tower-advanced/post_software.yml
Add SSH-based Git repo on bastion host of ansible-tower-advanced config (for the Summit 2020)
ansible-tower-advanced config
Include the git-server-ssh role and some glue around it to make sure the ec2-user _and_ Tower can access the Git repo created.
> Add SSH-based Git repo on bastion host of ansible-tower-advanced config

- ansible/roles/bastion/tasks/main.yml
@thoraxe needs way to add a random public key to the bastion VM (ansible-user).
> Add a public key to ansible_user on the bastion if specified

- ansible/configs/ocp4-workshop/ocp_workloads.yml
Allow infra_workloads to be set as list or string for ocp4-workshop config
> Allow infra_workloads to be set as list for ocp4-workshop

- ansible/configs/ocp4-cluster/default_vars.yml
- ansible/configs/ocp4-cluster/files/fio-test-job.yaml.j2
- ansible/configs/ocp4-cluster/files/fio-test.sh
- ansible/configs/ocp4-cluster/files/fio.Dockerfile
- ansible/configs/ocp4-cluster/post_software.yml
- ansible/configs/ocp4-disconnected-osp-lab/files/fio-test.sh.j2
Performance (etcd) testing was already an option in the OCP4 disconnected config. These changes add the capability to the ocp4-cluster config as well. In addition, the workload will launch as a job pod instead of using Ansible to have podman run the container on the master directly.
ocp4-cluster
> Add fio test as job pod

- ansible/configs/selinux-policy/post_software.yml
post_software.yml file contains undefined variable student_name. This
should be replaced by student_user
> Fix typo in SELinux workshop post_software

- ansible/roles/common/defaults/main.yml
With the introduction of RHEL8 to some configs, this will update the common package defaults to add stuff that is usually needed. This avoids having to recreate the list over and over in config default_vars.
common
> update common default package list

- ansible/configs/satellite-vm/pre_software.yml
…lude_roles v roles
roles: showing unpredictable variable inclusion when used with agnosticv --extra-vars. include_role is safer and avoids certain bugs seen in roles: 
satellite-vm
> Moved Configure satellites and capsules  play to include_roles

- ansible/configs/ocp4-workshop/env_vars.yml
Set `student_name` in ocp4-workshop config env_vars to prevent error when `install_student_user` is true but `student_name` is not set.
> Add default student_name to env_vars for ocp4-workshop config

- ansible/configs/satellite-vm/pre_software.yml
- ansible/roles/set-repositories/tasks/satellite-repos.yml
Satellite specific roles running into var naming collisions. Internal vars have no prefix so GPTEs use of Satellite over-rides any end-users hoping to configure their own satellites e.g. `satellite_url` rtc.
Fix should be backward compatible and is not a substitute for a better thought out internal naming convention for user exposed role vars however it does adopt the pattern of prefixing the vars with the role name (dashes `-` notwithstanding).
Config satellite-vm
Role set-repositaries
Blocker on on-boarding Summit lab
> Role set repositaries var changes 2020 04 02

- ansible/configs/ocp-clientvm/default_vars.yml
IPA breaks when krb package is update. This reverts the default for ocp-clientvm to false.
ocp-clientvm
> change update_packages to false

- ansible/roles-infra/infra-ec2-template-generate/tasks/main.yml
- ansible/roles-infra/infra-ec2-template-generate/tasks/validate_instances_amis.yaml
* save $
* reduce deployment failures 
* reduce support calls
* reduce complexity in agnosticV settings
* tested against ocp-clientvm
- test aws account access to images, upgrade and downgrade as necessary.
- for all instances and the aws account
- validate images that begin with RHEL against aws_ami_reigon_mapping
- validate against AWS bumping configs that use RHEL<VERSION> images to RHEL<VERSION>GOLD
- change successful bumps
- degrade RHEL<VERIONS>GOLD failures to RHEL<VERSION>
- validate all images
- continue CF template generation
infra-ec2-template-generate
Emit a CF tempalte only - no need to deploy env
1. create launch script:
```
cd ~/agnosticv/
GUID=test_clientvm
./merge.sh gpte OCP_CLIENTVM dev > $HOME/ocp_clientvm.yaml …
```
> infra-ec2-template-generate: upgrades the strong, downgrades the weak

- ansible/configs/ocp-clientvm/default_vars.yml
- ansible/configs/ocp-clientvm/default_vars_ec2.yml
Without `unique: true` the clientvm was being named incorrectly in ec2 config.
ocp-clientvm
> add unique var back to clientvm

- ansible/configs/ocp-clientvm/post_software.yml
bastion name for ocp-clientvm is clientvm, not bastion.
config/ocp-clientvm
> use clientvm., not bastion. hostnames

- ansible/roles/tower-custom-venv/tasks/loop.yml
- ansible/roles/tower-settings-update/tasks/main.yml
- ansible/roles/tower-user-create/tasks/main.yml
The tower-create-venv role supported only the system python, typically python2.
Extended it to allow an **optional** `virtualenv_python` so, for example, python3 based virtualenvs can be created
In addition extended supporting roles to be more flexible and configurable for tower creds i.e. not hardcoded to `admin` user etc
All tower-based configs
```
> Add the ability to build python3 venv to tower-create-venv

- ansible/configs/ansible-tower/env_vars.yml
- ansible/configs/ansible-tower/post_software.yml
- ansible/configs/ansible-tower/requirements.yml
The commits in the PR, if applied, will update the ansible-tower config in order to have [node-exporter](https://github.com/prometheus/node_exporter) installed on all nodes via the role [node-exporter](https://galaxy.ansible.com/cloudalchemy/node-exporter)
ansible-tower config
> Ansible tower add node exporter

- ansible/roles/ocp4-workload-quarkus-workshop/files/amqstreams_subscription.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/codeready_subscription.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/jaeger_subscription.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/verify-workload.yaml
This fix removes the `startingCSV` values so that the operator subscriptions always get the version appropriate for the OCP release it's being installed on, rather than starting with a specific version and then auto-upgrading (which takes more time and could fail the deployment).
It also adds `retries` to the verification step in case an operator takes a bit longer than expected to asynchronously provision.
> Fix operator versions; add retries to avoid slow operators failing

- ansible/configs/ocp4-cluster/default_vars.yml
- ansible/configs/ocp4-cluster/files/fio-test-job.yaml.j2
- ansible/configs/ocp4-cluster/post_software.yml
- ansible/configs/ocp4-disconnected-osp-lab/default_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/files/fio-test-job.yaml.j2
- ansible/configs/ocp4-disconnected-osp-lab/files/fio-test.sh
- ansible/configs/ocp4-disconnected-osp-lab/files/fio.Dockerfile
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
The previous implementation to run etcd fio tests was hacky to run a container on one of the masters via ssh. This brings in the previous updates to run this as a job pod since OpenShift is already installed. It will also report back directly to Overwatch instead of uploading to s3 bucket for later processing.
Also updates vars across both configs for consistency.
ocp4-cluster
> Update performance test playbooks

- ansible/configs/ocp4-cluster/default_vars_osp.yml
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
For the OpenStack cloud provider, the openshift installer attempts to pull in a copy of RHCOS and store it in Glance for every deployment. This can be bypassed by specifying an image in the `install-config.yaml`. This is optional and is disabled by default, but the following vars in the `default_vars_osp.yml` file can be set to change this behaviour.
ocp4-cluster
> Add ability to specify RHCOS image

- ansible/action_plugins/agnosticd_user_info.py
- ansible/library/agnosticd_user_info.py
- docs/README.adoc
- docs/User_Info.adoc
Fixes and add documentation for `agnosticd_user_info`:
- Fix missing blank lines in output.
- Do not show "user.info:" style messages when user is set.
- Append user messages rather than replace.
- Add documentation.
`agnosticd_user_info`
> Fix agnosticd_user_info

- ansible/action_plugins/agnosticd_user_info.py
`agnosticd_user_info` was printing:
```
"msg": "user.info:"
```
When called with an empty string. This caused odd behavior with our CloudForms integration scripts. A trailing space is required:
```
"msg": "user.info: "
```
This PR fixes this issue.
`agnosticd_user_info`
> Fix blank line output to include trailing space

- ansible/configs/ans-tower-lab/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Microsoft replaced and deleted old, 2012 Windows AMI breaking 2 configurations with hardcoded AMIs
Ansible Tower
Ansible for Windows
Ansible Homeworkl
> Fix for Ansible labs with broken Windows 2012 AMI

- ansible/configs/rhel8lab/post_software.yml
Add `agnosticd_user_info` call to rhel8lab post software to record workstation public IP.
rhel8lab config
> Add agnosticd_user_info for rhel8lab workstation public ip

- ansible/configs/satellite-vm/destroy_env.yml
satellite-vm config destroy.yml had redundant code that **failed** to call OSP destroy playbook. Simpler and cleaner syntax adds support for OSP and future clouds
Satellite-vm config
> Simplified and added support for OSP destruction in satellite-vm config

- ansible/configs/osp-migration/post_infra.yml
Previously guacamole was using IPA authentication, new version is using local user (htpasswd)
This code is printing just printing guacamole information and including the password to the open-init.sh script
> Add guacamole information (username / password) to user.info

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
`agnosticd_user_info` for ocp4-workload-quarkus-workshop workload misprinted the username in the output as "useruserX", doubling the "user" prefix.
ocp4-workload-quarkus-workshop workload
> Fix Username in ocp4-workload-quarkus-workshop agnosticd_user_info

- ansible/configs/ocp4-disconnected-osp-lab/pre_software.yml
- ansible/roles/bastion-lite/tasks/main.yml
At some point we lost the addition of the GUID to the skel/.bashrc file in the bastion-lite role. This adds it back in and removes a redundant task to create it in the ocp4-disconnected config.
bastion-lite
> Add GUID addition back to skel

- ansible/configs/satellite-vm/post_software.yml
While setting the agnosticd_user_info for satellite-vm  the hosts group  was incorrect. This commit changes it to the correct one.
> Fixed the host group for satelllite-vm

- ansible/configs/ocp4-workshop/post_software.yml
Fix openshift_api_url var in ocp4-workshop config.
Recent PR introduced an issue with a variable name prefix `ocp4_workshop_` that should not have been there.
> Fix openshift_api_url var in ocp4-workshop config

- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
In the cloud provider template, the default was to enable the use of the `swiftoperator` role. Since the Novello clusters will not run Swift, this should be defaulted to false. Some of the new clusters don't even have this role defined and deployments fail. If you need to use it, you can still set the `osp_use_swift` var in a config.
infra-osp-template-generate
> change swiftoperator role default to false

- ansible/configs/rhel-container-security/destroy_env.yml
Prevent failure when attempting to unregister unreachable hosts from satellite on destroy.
rhel-container-security config
> Add ignore_unreachable to rhel-container-security destroy

- ansible/roles/ocp-workload-integreatly/defaults/main.yml
- ansible/roles/ocp-workload-integreatly/tasks/remove_workload.yml
- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
This reverts commit 52ef77ff449478f99f1b4c5d8ac1030211ceee00.
This change causes integreatly workshops for both 1.5.2 and 1.6.0 to break due to gitea being installed.   See https://issues.redhat.com/browse/INTLY-6721 for more details.
> Revert "Clean up intly vars (#1222)"

- ansible/configs/rhel-custom-security-content/destroy_env.yml
- ansible/configs/selinux-policy/destroy_env.yml
Fix delete of rhel-custom-security-content and selinux-policy configs when hosts are unreachable and so cannot be unregistered from satellite.
rhel-custom-security-content and selinux-policy configs
```paste below
```
> Fix destroy with unreachable hosts

- ansible/configs/sap-rhvh/default_vars.yml
Ovirt engine setup roles fails with empty variable and requires a 'null' value
sap-rhvh
> Ovirt Engine role requiring 'null' variable

- ansible/configs/ocp4-workshop/post_software.yml
- ansible/configs/ocp4-workshop/templates/htpasswd.j2
Some workloads use `user_count` while others use `user_count_start` and `user_count_end`. This pull request adds support for ocp4-workshop to output user info to honor these variables when set.
> Supoort user_count_start and user_count_end for ocp4-workshop config

- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/per_user_remove_workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/per_user_workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/workload.yml
In ocp4-workload-ml-workflows-workshop workload role, add check to wait for jupyterhub deployment config in user namespace. Without this the command to scale the deployment config may run before the deployment config is created.
PR also includes various style changes to make the codebase more robust.
ocp4-workload-ml-workflows-workshop workload role
> Add check for jupyterhub dc to ocp4-workload-ml-workflows-workshop workload

- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/pipeline-buildconfig.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/pipeline-deploymentconfig.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/workshop-notebook-buildconfig.yaml.j2
Fix use of `project_name` variable in templates in workload ocp4-workload-ml-workflows-workshop
ocp4-workload-ml-workflows-workshop workload
> Fix project_name in templates for ocp4-workload-ml-workflows-workshop

- ansible/configs/studentvm/pre_software.yml
- ansible/roles-studentvm/studentvm-user/tasks/main.yml
The new `studentvm` workload was missing a task to add the GUID to the user `.bashrc`. This will add that in as part of the config. I also added an identical task in the `studentvm-user` role. Having it in both places doesn't hurt and it makes sure it is there before any user is either created automatically or manually, depending on the workloads selected.
studentvm
studentvm-user
> Add guid to skel file for studentvm

- ansible/roles-studentvm/studentvm-user/defaults/main.yml
- ansible/roles/common/defaults/main.yml
This PR changes the default for the student VM user workload to enable sudo. You can still override this and set to false if you need, but that should not be as common.
It also adds the buildah and skopeo packages to the common list for EL8.
common
studentvm-user
> enable sudo and set default packages

- ansible/configs/ocp4-disconnected-osp-lab/post_software.yml
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
- ansible/roles/ocp-infra-osp-fip/tasks/main.yml
When we get an `e` in our GUID, it is sometimes interpreted as an exponent instead of a string. This will change the names of clusters from `$GUID` to `cluster-$GUID`.
ocp-infra-osp-fip
ocp4-cluster
> Update cluster name for OCP4 installs

- ansible/roles/ocp4-workload-ml-workflows-infra-summit2020/defaults/main.yml
- ansible/roles/ocp4-workload-ml-workflows-infra-summit2020/tasks/workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/per_user_remove_workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/per_user_workload.yml
* Replace `user_count_end` in infra workload with `user_count` so that the two lab roles are now consistent
* Clean up some inconsistencies in the way the build pipeline is set up (as opposed to the build config) in the workshop role
> RHS_2020_T77D26: Fix for `user_count` and minor fixes for pipeline build

- ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml
- fix the path, use absolute
- do not redirect to /dev/null, we should know when something goes wrong
- add post-hook according to documentation
hosts-lets-encrypt-certs-certbot role
> Fix cronjob PATH + post-hook

- ansible/configs/ocp4-cluster/files/cloud_providers/azure_cloud_template.j2
Did not account for longer guids than I tested with.
Storage accounts in Azure have a 24 character limit, just added error correction around that.
Also added a minimum of 1 windows VMs as the default to fix another issues in the template. The more intensive and proper fix excluding all the copyOf sections will come someday.
config/ocp4-cluster
N/A
> Fixing azure tempalte in ocp4-cluster

- ansible/roles/ocp4-workload-quarkus-workshop/files/codeready_cr.yaml
CodeReady Workspaces 2.1 introduces a new requirement that one must use TLS-enabled routes. This change updates the custom resource used to deploy CodeReady to enable this feature.
```paste below
```
> enable TLS support for CRW to align with CRW 2.1 requirements

- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Config ansible-windows needs 2012 R2 AMIs - currently set to pre R2
Config ansible-windows
> Fix ansible-windows to 2012 R2 AMIs

- ansible/roles/ocp4-workload-logging/tasks/workload.yml
With the release of the elasticsearch operator 4.4, this version is now the default, even though it is not compatible with OCP 4.3. This PR causes us to prefer to install the subscription channel that matches the cluster version.
ocp4-workload-logging role
> Update ocp4-workload-logging to match version

- ansible/configs/satellite-vm/post_software.yml
The #1567 used incorrect group again, we should run this on localhost.
We have all the information locally, no need to involve remote hosts.
@jkupferer could you take a look?
Config `satellite-vm`
> Satellite propagate all needed user_info

- .github/workflows/asciidoc.yml
The image links are broken on the docs site because they aren't getting copied over to the gh-pages branch in the CI workflow,. This should fix that.
Documentation CI
> Copy images to gh-pages branch so they show up in documentation

- ansible/roles/ocp4-workload-integreatly/defaults/main.yml
- ansible/roles/ocp4-workload-integreatly/meta/main.yml
- ansible/roles/ocp4-workload-integreatly/readme.adoc
- ansible/roles/ocp4-workload-integreatly/tasks/main.yml
- ansible/roles/ocp4-workload-integreatly/tasks/post_workload.yml
- ansible/roles/ocp4-workload-integreatly/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-integreatly/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-integreatly/tasks/workload.yml
Adding new base template OCP4 role for managing Red Hat Managed Integration (Integreatly) installations. This role does not do anything yet but will act as the foundation for future development which will be progressed over the coming days/weeks
Equivalent OCP3 role can be found [here](https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles/ocp-workload-integreatly)
Red Hat Managed Integration (Integreatly)
> Adding new OCP4 role for RHMI 2.x (Integreatly)

- ansible/roles-infra/infra-osp-resources-destroy/tasks/project_resources.yml
Retry logic for race conditions where a volume is in process of
being detached. Also ignore volumes that are found to be already
deleted for whatever reason.
infra-osp-resources-destroy role
> Add retries to infra-osp-resources-destroy role

- .github/workflows/asciidoc.yml
Github workflow was failing because of file permissions on image copy. Add sudo.
GitHub workflow for asciidoc
> [WIP] Asciidoc workflow fix

- ansible/configs/sap-hana/pre_software.yml
When moving to e4s repositories some issues downloading from Satellite are causing the package installation to fail. It looks like locking RHEL release solves these issues.
sap-hana
> Locking to specific release to avoid metadata download issues

- ansible/roles/ocp-workload-migration/templates/operator.yml.j2
- ansible/roles/ocp4-workload-migration/templates/mig-operator-subscription-downstream.yml.j2
- removes `startingCSV` from OCP 4 workload to accept latest z-stream
- updates SHAs on OCP 3 side to align with latest z-stream 
```paste below
```
> Migration Workloads : align migration workloads with latest z-stream

- ansible/configs/ocp-workshop/files/hosts_template.3.11.104.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.129.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.153.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.154.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.16.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.161.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.43.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.51.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.59.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.69.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.82.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.88.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.98.j2
OLM install seems to be breaking as of late. Since this is an unsupported component in 3.11 removing... also it changed dramatically in 4.x so there isn't even value in it being there.
> Remove OLM by default from all OCP 3.11 Configs

- ansible/roles/ocp-workload-migration/tasks/post_workload.yml
- ansible/roles/ocp4-workload-migration/tasks/post_workload.yml
This change allows us to use agnosticd_user_info to inject deployment variables into our bookbag.
We wish to host a permanent bookbag demo page using this. 
```paste below
```
> Migration Workloads : agnosticd_user_info variables in the migration workload

- ansible/roles/ocp4-workload-integreatly/defaults/main.yml
- ansible/roles/ocp4-workload-integreatly/sample_vars/ocp4_workload_integreatly_vars.yml
- ansible/roles/ocp4-workload-integreatly/tasks/post_workload.yml
This change generates 50 eval users to be used by integreatly workshop
JIRA: https://issues.redhat.com/browse/INTLY-7046
Red Hat Managed Integration (Integreatly)
```paste below
Wednesday 29 April 2020  12:02:49 +0100 (0:00:00.023)       0:01:17.094 ******* 
=============================================================================== 
ocp4-workload-integreatly-minio : Create objects for Minio operator ------------------------------------------------------------------------------------------------------------------------------------------------------------------ 17.31s
ocp4-workload-integreatly : Generate dedicated admin password ----------------------------------------------------------------------------------------------------------------------------------------- …
```
> OCP4 Integreatly workload - evals user generation logic

- ansible/configs/ocp4-cluster/default_vars_osp.yml
This variable being defined in the default vars for the OSP cloud provider made it impossible to test OCP 4.4 with native functionality where it pulls in its own copy of RHCOS. This variable can still be set to force the installer to use a version of RHCOS that is present in Glance on the clusters.
ocp4-cluster
> Remove RHCOS default

- ansible/roles/ocp4-workload-ml-workflows-infra-summit2020/templates/open-data-hub/subscription.yml.j2
"alpha" went away -- switch to "legacy"
hotfix for IBM Think
`ocp4-workload-ml-workflows-infra-summit2020`
This replaces the subscription channel for the Open Data Hub operator.
> update ODH subscription channel

- ansible/configs/aro/destroy_env.yml
This will stop the potential for a conflict with the client ID
config/aro/destroy
N/A
> releasing the client ID after the cluster is destroyed

- ansible/configs/ansible-workshops/vars/networking_arista_tower_workshop_vars.yml
- ansible/configs/ansible-workshops/vars/networking_cisco_tower_workshop_vars.yml
- ansible/configs/ansible-workshops/vars/networking_juniper_tower_workshop_vars.yml
- ansible/configs/ansible-workshops/vars/networking_multivendor_tower_workshop_vars.yml
- ansible/configs/ansible-workshops/vars/rhel_90_tower_workshop_vars.yml
- changing networking to network to match workshop scaffolding and reduce complexity
- adding RHEL 90 workshop (shortened version of workshop)
see release PR here: https://github.com/ansible/workshops/pull/819 . this is not merged yet, trying to coordinate RHPDS with master branch changes that affect RHPDS
ansible workshops
feel free to text/call me, gchat me, slack me, want to make sure I don't break anything :)
> matching RHPDS to master branch of github.com/ansible/workshops

- ansible/configs/sap-rhvh/post_software.yml
Add `nmcli` commands to cloud-init to generate persistent eth0 configuration
sap-rhvh
> Add nmcli commands to cloud-init

- ansible/configs/sap-rhvh/post_software.yml
Cloud-init is wrongly trying to get metadata info from OSP causing eth0 info to reset to DHCP once VM is rebooted. Making eth0 configuration immutable once configured properly in the first run.
sap-rhvh
> Make eth0 inmutable to avoid cloud-init existing issues

- ansible/roles-infra/infra-ec2-template-generate/tasks/main.yml
- ansible/roles-infra/infra-ec2-template-generate/tasks/security_groups.yml
- ansible/roles-infra/infra-ec2-template-generate/templates/cloud_template.j2
- ansible/roles-infra/infra-osp-template-generate/tasks/main.yml
- ansible/roles-infra/infra-osp-template-generate/tasks/security_groups.yml
- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
If a config has security groups and use those, the default security groups are still create, for nothing.
The commits in this PR addresses that and make sure only used security groups are created in the templates.
> Create security groups only if they are used in 'instances'

- ansible/roles_ocp_workloads/ocp4_workload_project_request_template/templates/project_request_template.j2
This fixes a bug where the limitrange in the project request template didn't get created properly thus preventing creation of new projects by non cluster-admins.
> Fix bug in limitrange creation

- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/templates/coolstore-catalog-mongodb-persistent.j2
Fix for wrong apiVersion in the route definition for the catalog service.
> ocp4_workload_fuse_online: fix apiVersion 

- ansible/configs/osp-migration/infra.yml
1) Send a mail if documentation_link variable in agnosticV exists
2) The previous commit was not working properly because is was replacing first 443
> Send documentation link and fix issue with port order

- ansible/configs/test-empty-config/post_software.yml
Add a test to ensure multiline secrets are passed correctly through all the
Babylon components, and are not reduced to single-line variables.
configs/test-empty-config
> test-empty-config: add test for multiline secrets

- ansible/cloud_providers/azure_infrastructure_deployment.yml
- ansible/configs/aro/destroy_env.yml
- ansible/configs/aro/post_software.yml
- ansible/configs/aro/pre_software.yml
- ansible/configs/aro/software.yml
- ansible/roles-infra/infra-azure-create-inventory/tasks/main.yml
- ansible/roles-infra/infra-azure-create-service-principal/tasks/main.yml
- ansible/roles-infra/infra-azure-delete-service-principal/tasks/main.yml
- ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml
- ansible/roles/satellite-register-host/tasks/register.yml
- ansible/roles/set-repositories/tasks/satellite-repos.yml
Cleaned up environment variables for roles and cloud_provider related to provisioning and destroying on Azure
Also found a change to another role caused an error in ocp4-cluster config when used on Azure or GCP since they use the RHEL8 image from their respective marketplace and not a custom gold image.
config/aro
cloud_provider/azure
roles-infra/*azure*
roles/set-repositories
roles/satellite
Tested with aro3, aro4, ocp4-cluster, and ocp-workshop using Azure
> Clean-up related to Azure environment variables

- ansible/configs/ocp4-disconnected-osp-lab/default_vars.yml
- ansible/roles-infra/infra-osp-template-generate/defaults/main.yaml
- ansible/roles-infra/infra-osp-template-generate/tasks/security_groups.yml
- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
Currently the list of security groups generated are based on what is in use by instances. In some configs, we need to create security groups that are not yet used. With this change, you can now force all of the groups to be created with the `create_unused_security_groups` var. 
oc4-disconnected
osp-infra-template-generate
> Fix OSP Security Group list

- ansible/roles_studentvm/studentvm_ocp4/defaults/main.yml
I was a little aggressive with the version of `istioctl` I originally included and it didn't work with the workloads we needed. This takes us to a well known version in workloads we run, such as the advanced service mesh course.
studentvm_ocp4
> rollback version of istioctl in studentVM

- ansible/configs/osp-migration/infra.yml
- ansible/configs/osp-migration/post_software.yml
Creating keypair with a opentlc-mgr reachs a quota limit
This reverts: https://github.com/redhat-cop/agnosticd/commit/a26d7d7ca06a82342eb16aab0e4f5efb90a584cf
> [osp-migration] Create objects with user instead opentlc-mgr

- ansible/roles/ocp4-workload-ccnrd/defaults/main.yml
- ansible/roles/ocp4-workload-ccnrd/files/redis-template.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-username-distribution.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/post_workload.yml
- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
Adds a lightweight, frontend tool to provide a password-protected aggregated list of links to the individual workshop guides and a way to distribute user IDs and assign/unassign users.
The tool itself was originally developed by the Red Hat EMEA partner team and has been very well received. This PR only introduces the integration code to use the tool. The actual container image for the tool is [external on quay.io](https://quay.io/repository/openshiftlabs/username-distribution).
> Add Username Distribution tool frontend for CCN Roadshow

- ansible/roles/ocp4-workload-ccnrd/defaults/main.yml
Remove commas from lab descriptions to avoid parse errors later on when URLs and descriptions are presented to user.
> replace commas to avoid URL parse errors

- ansible/roles_studentvm/studentvm_user/tasks/main.yml
Adding amq workstation URL so that student should find AMQ workstation console easily by seeing the details in last mail.
studentvm for amq foundation
> Adding amq workstation url

- ansible/roles/ocp-workload-fsi-client-onboarding-demo/defaults/main.yml
- ansible/roles/ocp-workload-fsi-client-onboarding-demo/tasks/workload.yml
Fixes an ImagePull problem with the FSI Client Onboarding demo after images have been permanently moved to registry.redhat.io, which requires a login.
ocp-workload-fsi-client-onboarding-demo
The script, like some other scripts that use RHPAM and BPM Suite, now checks for the availability of the IS in the OpenShift namespace, and if the IS is not there yet, adds it. We need to user the "openshift" namespace, as the builder service account in that namespace has pull access to registry.redhat.io.
> Fix ImageStream issue.

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/fuse/create-instance.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/templates/fuse-syndesis.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/templates/kubeletconfig-pods.yml.j2
update integreatly workload to include per-user fuse online service discovery in 3scale. even though [1] will still cause an issue in 3scale 2.8. also ensure that pod quotas are not hit on large user count installations.
[1] https://issues.redhat.com/browse/THREESCALE-4851
@ciaranRoche @dimitraz @pmccarthy mind taking a look? i'll give you all write permissions to this branch
role: `roles_ocp_workloads/ocp4_workload_integreatly`
commit a05891e1d15494b971283d7d3236a800d21b5b31
increase default node pod quota to 500
ensure the default node pod quota is updated for the openshift
cluster, to avoid hitting pod quota limits upon rhmi installation.
verification:
- run the installation
- wait for the installation to get to rhmi cr checks
- once the rhmi cr checks begin, run …
> rhmi 3scale service discovery

- ansible/configs/ocp4-ha-lab/destroy_env.yml
- ansible/configs/ocp4-workshop/destroy_cluster.yml
- ansible/configs/ocp4-workshop/destroy_env.yml
It happens that the `openshift-install destroy` comamnd loops forever with this kind of error messages:
```
time="2020-05-26T14:17:29Z" level=debug msg="search for and delete matching instances by tag matching aws.Filter{\"openshiftClusterID\":\"66564c10-bc6f-4c81-a373-719a03722447\"}"
time="2020-05-26T14:17:29Z" level=info msg="describe instances: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 0eb0b0e6-913d-4d2f-8abd-7f2e60b5f548"
```
This happens when the AWS credential file `.aws/credentials` is modified on the
clientVM between provision and destroy.
This commit will fix that by ensuring the credentials are passed as environment
variables. The ocp4-workshop being aws-only, it's OK to specify the environment variables there. …
> Fix aws credential in ocp4-workshop destroy playbook

- ansible/configs/three-tier-app/files/hosts_template.j2
ansible_become=yes removed from templeate
> ansible_become removed

- ansible/configs/rhel-custom-security-content/post_software.yml
Update user output information for RHEL Custom Security Content workshop. This way users can access the lab environment by following the email sent as a result of the deployment.
Points users to the rendered version of the bookbag documentation hosted here:
https://2020-summit-labs.gitlab.io/rhel-custom-security-content
> Update user output information to RHEL Custom Security Content lab.

- ansible/configs/rhel-custom-security-content/post_software.yml
A follow-up to #1829 . We need to escape characters `<` and `>` since the content is used in a HTML page.
> Escape HTML special characters on user output information.

- ansible/configs/selinux-policy/post_software.yml
This way users can access the lab environment by following the email sent as a result of the deployment.
Points users to the rendered version of the bookbag documentation hosted here:
https://2020-summit-labs.gitlab.io/selinux-policy-bookbag/
> Update user output information to SELinux policy writing workshop

- ansible/roles-infra/infra-azure-create-inventory/tasks/main.yml
Immediate goal is to make OCP4 on Azure IaaS functional, so this is the only PATH that fails. A wider cleanup of environment settings will come after for the Azure cloud provider and roles.
roles-infra/infra-azure-create-inventory
N/A
> Making OCP4 on Azure IaaS have a functional destroy

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/threescale/create-tenant.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/templates/keycloakclient-3scale-workshop.yml.j2
fix unicode string handling discussed in [1] in the 3scale workshop
sso client updates.
this ensures the sso client custom resource does not contain any 'u'
characters.
components:
- role: roles_ocp_workloads/ocp4_workload_integreatly
[1] https://stackoverflow.com/questions/41521138/ansible-template-adds-u-to-array-in-template
> ocp4_workload_integreatly: fix unicode string handling in list append

- ansible/roles/ocp4-workload-ccnrd/files/sso74-image-stream.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/post_workload.yml
- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
Minor fix to make workload idempotent when deploying imagestream. Also added extra URL in `user.info` for username distribution admin console.
> use k8s to deploy imagestream; include admin URL in user.info

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/fuse/create-instance.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/threescale/create-tenant.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/tasks/post_workload.yml
Create a 3scale tenant and fuse instance for the `dedicated-admin` user for the `ocp4_workload_integreatly` role.
Fixes: https://issues.redhat.com/browse/INTLY-8153
Role: `ocp4_workload_integreatly`
Verification steps
- Provision an ocp 4.4 workshop (note: increase the number of ocp users to increase the number of nodes. 60-100 should be enough for `50` evals users)
- Run an integreatly installation from this branch 
- Log in as the `dedicated-admin` user, ensure this user can:
- Access the fuse console from solution explorer
- Access the 3scale console from solution explorer
- Run through the walkthroughs and can access the links to the 3scale and fuse consoles 
- Login is as an `evals` user, ensure this user can: 
- Access the fuse console from solution explorer
- …
> [ocp4_workload_integreatly] Create dedicated admin 3scale tenant and fuse instance

- ansible/roles-infra/infra-azure-ssh-key/tasks/main.yml
Enforcing the keyvault to only use up to its 24 character limit
roles-infra/infra-azure-ssh-key
forgot about the 24 character limit on the keyvault name which also needs to be globally unqiue
> enforcing character limit on keyvault name

- ansible/configs/ocp4-cluster/post_software.yml
- ansible/roles/host-ocp4-destroy/tasks/azure_prereqs.yml
- ansible/roles/host-ocp4-destroy/tasks/gcp_prereqs.yml
- ansible/roles/host-ocp4-destroy/tasks/main.yml
- ansible/roles/host-ocp4-destroy/templates/osServicePrincipal.json.j2
Giving kubeadmin password on GCP and Azure so the web console can be used and removing the actual cloud credentials post-install (and readding them during the destroy) so lab users can't deploy their own Azure and GCP assets. 
role/host-ocp4-destroy
This brings up almost completely inline with how AWS is treated by AgnosticD for ocp4-cluster.
> Removing credentials so lab users can't access them

- ansible/configs/selinux-policy/post_software.yml
Update selinux-policy workshop user output.
Note that I have added the option `-o "ServerAliveInterval 30"` to the ssh command so users are not disconnected after some period of absence, aka reading workshop's text for more than a few minutes
> Update selinux-policy email to follow selinux-policy docs

- ansible/roles/satellite-publish-content-views/README.adoc
- ansible/roles/satellite-publish-content-views/tasks/main.yml
- ansible/roles/satellite-publish-content-views/tasks/version_6.x.yml
A role to check for updated repositories after a sync, then publish new versions of any content views which contain those repositories.
This is designed to run after any sync tasks, and only checks for updates in the last day. It also checks whether a content view has been published in the last day and does not publish a new version if that is the case. It will also not publish a content view that is set to publish automatically.
satellite-publish-content-views
```paste below
PLAY [satellite] ***************************************************************************************************************************************************************************
TASK [Gathering Facts] *********************************************************************************** …
```
> Add role satellite-publish-content-view

- ansible/configs/studentvm/default_vars_osp.yml
The format of the output was wrong for the OSP provider with studentvm. 
subdomain base was being created without a . between the other vars. We define osp_cluster_dns_zone without a . prefix everywhere, so the var was created as something like `guidsubdomainbasesuffix` with no . between.
studentvm
> Fix StudentVM user.info output

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/tasks/post_workload.yml
ensure dedicated admin fuse online instance is counted in fuse
online verification check.
components:
> fix expected fuse online instance count

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/tasks/post_workload.yml
parse the user count param with the int filter to ensure it's not
treated as a string
components:
verification:
- run the role, ensure it does not fail
> ensure user count param is treated as int

- ansible/configs/selinux-policy/post_software.yml
Use HTML enconding to output double quotes into selinux-policy post_software
> Use HTML enconding to output double quotes into selinux-policy post_software

- ansible/configs/ocp4-cluster/post_software.yml
- ansible/configs/ocp4-workshop/software.yml
Reverts redhat-cop/agnosticd#1937
I'm not sure how this was tested. It is breaking things because the syntax for the block doesn't appear to be correct. I also don't understand why we have the same tasks in both software and post-software phase?
I don't have the bandwidth to test the fix, but it should be as simple as a `-` and some spaces.
```
The error appears to have been in '/tmp/ocp4-workshop-046f/ansible_agnostic_deployer/ansible/configs/ocp4-workshop/software.yml': line 117, column 11, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: Make a copy of the cluster install config
^ here
```
> Revert "Get OCP4 installation logs in a block"

- ansible/configs/sap-hana/default_vars.yml
The upstream `https://github.com/linux-system-roles/sap-preconfigure` role requires now a new variable to skip errors in case the host needs a reboot. Adding this to the config so the e2e process doesn't fail because of this.
sap-hana
> Add new required variable for upstream SAP Ansible Role

- ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml
In the `infra-osp-dns` role, the `nsupdate` is used to update DNS for the deployed instances. When creating a new instance, the module uses the `key_algorithm` attribute to specify the algorithm of the TSIG key, and it defaults to `hmac-md5`. However, this attribute is not present for instance deletion, which leads to failure when the key algorithm is not `hmac-md5`.
This pull request adds the attribute, with `hmac-md5` default value.
infra-osp-dns
> Add nsupdate algorithm to deletion task for infra-osp-dns role

- ansible/lifecycle_osp.yml
* Instance shelving allows to retain the state of an instance without having it consume resources.
A shelved instance will be retained as a bootable instance this is useful as part of an instance to conserve resources.
* This patch maintains compatibility with vm_state stopped 
OpenStack Provider
> Using instance shelve on OpenStack 

- ansible/configs/ocp4-cluster/lifecycle_hook_post_start.yml
- ansible/lifecycle.yml
- ansible/lifecycle_entry_point.yml
- ansible/lifecycle_hook.yml
Enable lifecycle hooks. These should work for all lifecycle actions (start / stop / status).
There is a default hook in the agnosticd directory that's just a no-op.
ocp4-cluster now implements a post start hook to approve any CSRs for clusters newer than 4.4.7 that have been sleeping through the 24h cert rotation window.
Global
ocp4-cluster
Needed to implement lifecycle for ocp4-cluster config - and this PR avoids doing a one off for the config.
@fridim Can you double check that this should work for sandboxed environments? I can't test that from my laptop...
> Enable Lifecycle Hooks (and implement start hook for ocp4-cluster)

- ansible/roles/ocp4-workload-ccnrd/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
Need separator to be other than comma for auto testing of CI. This is required for Jenkins testing as all CloudForm input parameter also comma separated.
ocp4-workload-ccnrd role --> task --> workload and remove workload
> Need separator to be other than comma for auto testing of CI

- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/files/gogs_admin_rules_cluster_role.yaml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/files/gogs_crd.yaml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/tasks/workload.yml
Add a new workload to configure a cluster for use in the OpenShift Advanced Application Deployment ILT.
This workload adds the gogs CRD and gogs-admin-rules cluster role to the cluster.
ocp4_workload_app_deploy_ilt
> Add app_deploy_ilt workload

- ansible/configs/osp-sandbox/files/secret.yaml.j2
OSP Sandbox deploys need osp user and password vars with the postfix `_member`. This enhancement deploys the secrets.yaml file with the prefix already added and "ready to go"
osp-sandbox
Some configs
> Feature update  osp-sandbox config secrets template to use _member postfix

- ansible/roles-infra/infra-osp-dry-run/tasks/main.yml
OSP sandboxes use an auth postfix _member. This adds support to dry run so it will succeed on both sandbox and non-sandbox deploys
roles-infra/infra-osp-dry-run
> Fix osp dry run to support sandbox via _member postfixes for auth

- ansible/configs/ocp4-cluster/files/cloud_providers/azure_cloud_template.j2
Adjusting hostname for the bastion so its always unique, apparently Satellite gets cranky occasionally otherwise.
config/ocp4-cluster
Discovered by an auto test
> Update ocp4-cluster on azure for satellite limit

- ansible/roles_ocp_workloads/ocp4_workload_kubevirt/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_kubevirt/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_kubevirt/templates/subscription.yaml.j2
The first issue that this PR fixes is the meta/main.yml syntax.
Then, it adds variables for the HCO version.
It also renames sub.yaml into subscription.yaml.j2, while turning it into a template that uses version.
Finally, it adds a task to wait for the subscription to succeed.
> Fix workload ocp4_workload_kubevirt

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/fuse/create-instance.yml
creating a new file per pull secret can cause inode issues on
hosts running the role, as a new file is created for each run of
the pull secret copy
this commit will reuse the same file for all pull secrets to avoid
this issue occuring
components:
> do not create per-user pull secret files

- ansible/roles/a_simple_webserver/handlers/main.yml
- ansible/roles/a_simple_webserver/tasks/pre_install.yml
- ansible/roles/a_simple_webserver/tasks/smoketest.yml
Changed a_simple_webserver role to start and enable firewalld if the service is to be used. I also added a flush handlers during the smoke test.
```paste below
```
> Updated to start and enable firewalld if boolean| true

- ansible/roles/host-ocp4-provisioner/templates/clouds.yaml.j2
When provisioning hosts for OCP4 on OpenStack, the user domain can be different from "Default". This pull request allows setting an `ocp4_auth_user_domain`, that will anyway default to "Default" for backward compatibility.
> host-ocp4-provisioner - Allow non Default user domain in OpenStack

- ansible/configs/ansible-tower-implementation/pre_software.yml
SUMMARY
Update epel-release rpm for ansible tower implementation. URL: http://d3s3zqyaz8cp2d.cloudfront.net/repos/epel/Packages/e/epel-release-7-11.noarch.rpm
ansible-tower-implementation pre software config
> Update epel-release rpm for ansible tower implementation

- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
When deploying OCP4 on OpenStack, the platform may have some features enabled, or not, such as Octavia for load balancing, and trunk support. The current template as fixed values for these two properties. This pull request allows setting them via variables, while defaulting to the current values.
Also, in OpenStack, the machine network may overlap with existing networks out of OpenStack. This pull request allows setting the `machineCIDR` property from a variable, while defaulting to `10.0.0.0/16` for backward compatibility.
> host-ocp4-installer - Allow more variables in install-config.yaml

- ansible/configs/ans-tower-lab/pre_software.yml
- ansible/configs/ansible-advanced/pre_software.yml
- ansible/configs/ansible-provisioner/post_software.yml
- ansible/configs/satellite-infrastructure/pre_software.yml
- ansible/configs/satellite-vm/pre_software.yml
- ansible/configs/smart-management/pre_software.yml
- ansible/roles/rhel-epel/defaults/main.yml
Updating epel installer url with cloudform url: http://d3s3zqyaz8cp2d.cloudfront.net/repos/epel/Packages/e/epel-release-7-11.noarch.rpm in the place of https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
We can use our CloudForms repo.
Ansible deployer affected some CI.
> Updating epel installer url with cloudform url

- ansible/configs/ocp4-cluster/destroy_env.yml
When the DNS records for the OCP4 floating IPs are created by AgnosticD, the names are `api.cluster-{{ guid }}` and `*.apps.cluster-{{ guid }}`. In the destruction tasks, the `cluster-` part is missing, so the records are not removed. This pull request fixes that.
ocp4-cluster
> ocp4-cluster - Fix FIP DNS records deletion

- ansible/configs/ocp4-disconnected-osp-lab/destroy_env.yml
In the `destroy_env.yml`, this config was not using the correct base domain to cleanup the API & wildcard DNS entries. This small change fixes that to delete the records with `cluster-guid` instead of just `guid`.
> Change config ocp4-disconnected-osp-lab

- ansible/roles_ocp_workloads/ocp4_workload_kubevirt/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/workload.yml
It may happen that the Subscription CR is not picked by the controller when we check its status, so the `status` property doesn't exist yet. This pull request allows an empty `status` property.
It also adds a small pause to be sure that the operator group is created.
> Ocp4 workload kubevirt allow time for subscription status

- ansible/configs/ocp4-cluster/default_vars_osp.yml
- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_master.j2
When deploying OCP4, the description of the floating IPs is used by the installer to identify the floating IP for the API when `lbFloatingIP` is not set in the `install-config.yaml` file. The convention is to set `API` or `Ingress` followed by `<cluster-name>.<ocp4_base_domain>`.
This pull request updates the description is OpenStack default vars to match the convention.
It also update the OpenStack Heat templates to set the description if present. Setting the `description` property doesn't actually set the description on the floating ip. We need to set `value_specs.description` instead.
- Enhancement Pull Request
ocp4-cluster
> ocp4-cluster - Update FIP descriptions and ensure they are set

- ansible/completion_callback.yml
This commit, if applied, fixes the following error:
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'agnosticd_callback_url != ''' failed. The error was: error while evaluating conditional (agnosticd_callback_url != ''): 'dict object' has no attribute 'callback'\n\nThe error appears to have been in '/tmp/sandboxes-gpte-OCP4_WORKSHOP_CCN_RS_DEV_TRACK_SFDC_LARGE-prod-ccn2-99d2-...
```paste below
```
> Fix completion_callbacks.yml, add tests to work with ancient versions of ansible (2.7)

- ansible/configs/ocp4-ha-lab/README.adoc
Changes the ocp4-ha-lab docs replacing env_vars.yml to default_vars.yml
Fixes #2034 
ocp4-ha-lab
> Change documentation ocp4-ha-lab to move from env_vars.yml to default_vars.yml

- ansible/roles/ocp-infra-osp-fip/defaults/main.yml
- ansible/roles/ocp-infra-osp-fip/tasks/main.yml
Follow-up of https://github.com/redhat-cop/agnosticd/pull/1968 to add the `key_algorithm` to `nsupdate` call in `ocp-infra-osp-fip` role.
ocp-infra-osp-fip
> Change role ocp-infra-osp-fip to support nsupdate algorithm in nsupdate calls

- ansible/configs/ocp4-disconnected-osp-lab/files/clouds.yaml.j2
- ansible/roles/host-ocp4-provisioner/templates/clouds.yaml.j2
Recently, the `osp_auth_username_member` and `osp_auth_password_member` were introduced. The `ocp4-disconnected-osp-lab` and `host-ocp4-provisioner` roles don't use it to expand the `clouds.yaml.j2` template. This pull request adds the support for them.
The `ocp4-disconnected-osp-lab` also didn't support the ability to use an existing project, so the pull request checks if `osp_project_create` is set and uses existing user if yes, like `host-ocp4-provisioner` does.
> OSP - User _member variable for username and password

- ansible/completion_callback.yml
- docs/README.adoc
- docs/Variables.adoc
The variables agnosticd_callback_url and agnosticd_callback_token should
be functionaly when set and __meta__ vars are not set. This is required
for GUID Grabber bookbag integration.
> Fix functionality for agnosticd_callback_* vars

- ansible/roles/host-ocp4-provisioner/tasks/osp_prereqs.yml
With the change to use `osp_auth_username|password_member` vars for the OSP cloud provider to actually create things, this role was failing when generating the `clouds.yaml` file on the bastion node. This is because the fact that set these values was associated with the localhost running agnosticd and not the bastion where the task that generated the `clouds.yaml` was being run.
> Fix role host-ocp4-provisioner

- ansible/roles-infra/infra-osp-resources-destroy/tasks/heat.yml
The OpenStack roles now use `osp_auth_username_member` and `osp_auth_password_member` as credentials. The Heat stack deletion tasks file was still using `osp_auth_username` and `osp_auth_password`. This pull request updates the variable names and allows to use the _old_ names for backward compatibility.
The project detection may also fail in the case where it was not created by AgnosticD. Because the user can provide an existing project id, the pull request also allows to fall back to `osp_project_id` variable.
infra-osp-template-create
> infra-osp-resources-destroy - Fix Heat stack deletion

- ansible/roles-infra/infra-osp-resources-destroy/tasks/heat.yml
Reverts redhat-cop/agnosticd#1995
The exact thing that I was worried about happened...we have `osp_auth_username_member` defined (from defaults) and no `osp_auth_password_member`, so it was mixing users and passwords and failing. We use `osp_auth_username_member` in an additional task for cleaning up keypairs, so I need that defined in defaults if not explicit.
This cleanup needs to go back for a deeper review. In the meantime, cleaning up *inside* a sandbox just won't work and that is not what this was intended for in it's initial and current state.
@fdupont-redhat
> Revert "infra-osp-resources-destroy - Fix Heat stack deletion"

- ansible/roles_ocp_workloads/ocp4_workload_nexus_operator/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_nexus_operator/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_nexus_operator/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_nexus_operator/templates/nexus.j2
* Re-enable the capability in Nexus Operator to customize Nexus Repositories
* Add checks for Nexus Image (`latest` is no longer valid due to frequently changing Nexus container images). Minimum image is now `3.24.0` (for Dockerhub nexus images) or `3.24.0-ubi-1` for Redhat Registry nexus images
* Add additional settings to specify how the repositories should be customized
* Added flag to enable/disable anonymous access
Additional related changes in the Operator
* Remove Groovy Scripts from Operator, replace with REST API calls
OpenShift 4 Workload: Nexus Operator
The capability to customize repositories was lost in the operator during the last round of updates and fixes. This re-enables this capability - and in a much better way.
> Update with new customization options (repos etc)

- ansible/configs/sap-rhvh/default_vars.yml
Change the default RHEL 7 image for RHVM instance to match the name of the image in PROD
sap-rhvh
> Change default image for RHVM instance

- ansible/configs/sap-rhvh/pre_software.yml
Lock RHEL release to prevent metadata pull issues
sap-rhvh
> Lock RHEL release in the Bastion host

- ansible/configs/sap-hana/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/sap-rhvh/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/sap-smart/files/cloud_providers/osp_cloud_template_master.j2
This commit follows #1702 and #1744 
Apply the fix on the standalone templates as well, so security groups not used
at deployment are not created in the heat template.
@makentenza must approve this PR before it is merged.
configs:
- sap-hana
- sap-rhvh
- sap-smart
> Fix config sap-hana sap-rhvh sap-smart: in OSP heat, create SG only when used in 'instances'

- ansible/roles-infra/infra-osp-resources-destroy/tasks/keypairs.yml
The current version of this role will allow you to delete the admin account if you know it's username and password and you set the `osp_auth_username_member` var to an incorrect value. This change adds a check into the task list that will ensure the user that it will be deleting is not the same as the `osp_auth_username`, which would be the admin account.
infra-osp-resources-destroy
> fix role infra-osp-resources-destroy

- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
Add required Jaeger operator whenever istio is installed.
> install required jaeger operator before service mesh install for m4

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/defaults/main.yml
As per discussions with Nate, we're going to change default namespace for the ocp4_workload_rhacm workload from `advanced-cluster-management` to `open-cluster-management` to better align with the documentation.
```paste below
```
> Changed default namespace to open-cluster-management

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/idp/create-sso-idp.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/sample_vars/ocp4_workload_integreatly_vars.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/templates/keycloakrealm-idp.yml.j2
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/templates/keycloakuser-idp.yml.j2
add an additional sso realm idp for the rhmi 2.x role. this replaces
the current htpasswd approach.
components:
verification:
- an install of this role completes against a 4.4 workshop
- the login screen for the cluster presents two identitity providers
- you can login to the rhmi identity provider using the users provided
in the logged details
> create external sso realm as cluster idp

- ansible/roles_ocp_workloads/ocp4_workload_pntae/defaults/main.yml
ocp4_workload_pntae fails when attempting to place file inside /usr/local/bin/. I updated the become_overide: to true to resolve.
```paste below
```
> ocp4_workload_pntae update become_overide: to true

- ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/templates/clusterresourcequota.j2
- ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/templates/namespace.j2
role: roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp
The role breaks when guid contains no alfabetical characters. This PR fixes this. Tesed sucessfully with guid 1234
> ocp4_workload_amq_streams_dev_exp: deployment fails when guid is has no alphabetical characters

- ansible/roles-infra/infra-osp-dns/tasks/instance_loop.yml
Error when provisioning more than 1 instance count. Failed on fatal: [localhost]: FAILED! => {"msg": "The conditional check '_instance.count > 1' failed. The error was: Unexpected templating type error occurred on ({% if _instance.count > 1 %} True {% else %} False {% endif %}): '>' not supported between instances of 'str' and 'int'
ansible/roles-infra/infra-osp-dns
Deploying configs/ansible-tower-implementation, using osp_vars.yml on sandbox environment caused this error to appear.
```paste below
```
> Updated roles-infra/infra-osp-dns to remove errors.

- docs/Contributing.adoc
In contributing.adoc, point to redhat-cop guidelines.
- Mention redhat-cop guidelines
- Are issues mandatory for PR ?
- Specify where to document config variables
> Change Contributing guidelines

- ansible/configs/ansible-windows/files/hosts_template.j2
Ansible 2.9.10 introduces a bug when used with Windows machines when inventory contains **any** `become` references
ansible-windows config
Simply removes the 2 become references from the Jinja /etc/ansible/hosts files which are not necessary
> Fixe to windows ansible 2.9.10 become issue

- ansible/cloud_providers/azure_infrastructure_deployment.yml
All the logic exists to create a custom password, but we missed passing it to the parameters file.
Azure cloud provider
This is a complete oversight on my part. When testing you should override things you pass in the default password as a parameter you don't notice it isn't getting overridden.
> Change Azure cloud provider to support custom Windows pwd

- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
When using filters with the instance.count variable, it was interpreted as a string. This was causing single server instance counts to become numbered, breaking the later dns logic (below from infra-osp-dns/tasks/nested_loop.yml)
ansible_facts.openstack_servers[?name=='{{ _instance_name }}'].public_v4 | [0]
This is resolved by adding the integer filter into the logic of the template. This was already in place for most sections, fixed it in this one case.
roles-infra/osp-generate-template
Steps to reproduce:
Step 1: Filter like so within an instance dictionary for count
instances:
- name: "tower"
count: "{{ tower_instance_count | default(1) }}"
tower_instance_count: 1
Step 2: Launch config and view the saved osp_cloud_master_template.yaml
########### tower0 …
> Fix role osp-generate-template cloud_template_master.j2

- docs/Contributing.adoc
closes #2135
`docs/Contributing.adoc`
> Change doc Contributing.adoc, add link to yamllint ex and doc

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml
Minor fix to update URL to keycloak for the user guides.
Was inadvertently left off of https://github.com/redhat-cop/agnosticd/pull/2159 cc @jkupferer
> update URL to match CRW 2.2 changes

- ansible/roles/ocp4-workload-ccnrd/files/codeready_cr.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-codeready.yaml
Fix ocp4-workload-ccnrd not to use Keycloak instance environment variables in CRW 2.2.0
codeready_cr.yaml
install-codeready.yaml
```paste below
```
> Fix ocp4-workload-ccnrd not to use Keycloak instance environment variables in CRW 2.2.0

- ansible/roles/ocp4-workload-jdg-workshop/files/codeready_cr.yaml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/install-codeready.yaml
Fix ocp4-workload-jdg-workshop not to use Keycloak instance environment variables in CRW 2.2.0
codeready_cr.yaml
install-codeready.yaml
```paste below
```
> Fix ocp4-workload-jdg-workshop not to use Keycloak instance environment variables in CRW 2.2.0

- ansible/roles/host-ocp4-destroy/.yamllint
- ansible/roles/host-ocp4-destroy/defaults/main.yml
- ansible/roles/host-ocp4-destroy/meta/main.yml
- ansible/roles/host-ocp4-destroy/tasks/azure_prereqs.yml
- ansible/roles/host-ocp4-destroy/tasks/gcp_prereqs.yml
- ansible/roles/host-ocp4-destroy/tasks/main.yml
Updating host-ocp4-destroy to set the cluster_name default value using defaults instead of a task, added an azure specific set_fact for cluster_name in the azure prereqs, and updated yamllint and meta because I'm touching the role so why not.
roles/host-ocp4-destroy
Seems like a better way to hand having a default value when we might want more cloud specific overrides later on
> Update role host-ocp4-destroy

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhsso.yaml
To avoid timing issues in terms of it tries to get a token before RH-SSO is ready to serve.
```paste below
```
> Add ocp4-workload-quarkus-workshop to check RH-SSO running

- ansible/configs/ocp4-workshop/software.yml
Previously we checked for the string:
'validate AWS credentials: mint credentials check: error simulating policy: Throttling: Rate exceeded'
But "mint" was not present. This shortens the check to look for:
'error simulating policy: Throttling: Rate exceeded'
> Fix ocp4-workshop install retry on throttling rate exceeded

- ansible/roles/ocp4-workload-jdg-workshop/tasks/install-codeready.yaml
Remove ocp4-workload-jdg-workshop to remove unused importing Realm
```paste below
```
> Remove ocp4-workload-jdg-workshop to remove unused importing Realm

- ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile
- ansible/roles/ocp4-workload-quarkus-workshop/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/templates/devfile.json.j2
Update ocp4-workload-quarkus-workshop to add prebuild .m2 in CRW 2.2 base image
```paste below
```
> Update ocp4-workload-quarkus-workshop to add prebuild .m2

- ansible/roles/ocp4-workload-jdg-workshop/files/codeready_subscription.yaml
- ansible/roles/ocp4-workload-jdg-workshop/files/stack.Dockerfile
- ansible/roles/ocp4-workload-jdg-workshop/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-jdg-workshop/templates/devfile.json.j2
Fix ocp4-workload-jdg-workshop to use latest CRW image and add rebuild .m2 in custom CRW base image.
```paste below
```
> Fix ocp4-workload-jdg-workshop to use latest CRW image 

- ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/tasks/workload.yml
#1875 ### SUMMARY
Increase delay and retries waiting for IS tag to become available on the cluster.  Should fix a problem when the cluster is slow importing the IS.
> Increased retries and delays waiting for IS to become available.

- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/files/deploy_certs.sh
- ansible/roles/ocp4-workload-idm/files/deploy_certs.sh
- ansible/roles_ocp_workloads/ocp4_workload_le_certificates/files/deploy_certs.sh
This commit, if applied, fixes the following error:
```
Running post-hook command: /home/ec2-user/certbot/renewal-hooks/deploy/deploy_certs.sh
post-hook command "/home/ec2-user/certbot/renewal-hooks/deploy/deploy_certs.sh" returned error code 1
Error output from post-hook command deploy_certs.sh:
ERROR! the playbook: ./deploy_certs.yml could not be found
```
> Fix LetsEncrypt renewal hook

- ansible/configs/ocp-gpu-single-node/env_vars.yml
- ansible/configs/ocp-implementation-lab/env_vars.yml
- ansible/configs/ocp-workshop-with-clientvms/env_vars.yml
- ansible/configs/ocp-workshop/env_vars.yml
- ansible/configs/ocp4-ha-lab/default_vars.yml
- ansible/configs/ocp4-workshop/env_vars.yml
- ansible/roles/ocp4-workload-authentication/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_authentication/defaults/main.yml
This fixes a number of places in the AgnosticD code where an insecure protocol is used to fetch the OpenTLC IPA certificate authority cert and so fixes a potential man-in-the-middle attack vulnerability.
The old location was http://ipa1.opentlc.com/ipa/config/ca.crt
The new location uses AWS S3: https://gpte-public.s3.amazonaws.com/opentlc_ipa_ca.crt
- Security Pull Request
Configs, some of which may be abandoned/unused:
ocp4-ha-lab, ocp4-workshop, ocp-workshop, ocp-implementation-lab, ocp-workshop-with-clientvms, ocp-gpu-single-node
Roles: ocp4-workload-authentication
> Fix to use secure protocol to download OpenTLC IPA certificate

- ansible/roles-infra/infra-osp-resources-destroy/tasks/project_resources.yml
Destroy of openstack resources fails with message of the sort:
```
"No volume with a name or ID of 'cd7cd421-de53-4889-97de-0ea4c31bb7f3' exists."
```
This sets a failed_when to ignore this and still attempt to complete the deletion.
Infra role infra-osp-resources-destroy
> Fix role infra-osp-resources-destroy reset volume error on destroy

- ansible/configs/ocp4-cluster/destroy_env.yml
This commit, if applied, will fix the following error:
```
TASK [Test the bastion host is available, if not skip host-ocp4-destroy] *******
fatal: [bastion.959d.internal]: FAILED! => {"changed": false, "elapsed": 60, "msg": "timed out waiting for ping module test success: Failed to connect to the host via ssh: no such identity: opentlc_admin_backdoor: No such file or directory\r\nno such identity: /tmp/gpte-OCP45_WORKSHOP-dev-959d-28022/output_dir/959dkey: No such file or directory\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password)."}
```
There is a mismatch between provision and destroy.
The key used when provision is `~/.ssh/..pem` but for destroy it's a generated
key because the varaible `set_env_authorized_key` is true by default in this
config.
The default_ssh_key …
> Fix ocp4-cluster destroy_env.yml SSH connection (ec2 only)

- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
The operator role didn't create an admin user for gitea, so you couldn't
really do anything. This adds a var for the user and password and makes
sure that the admin is created idempotently (although it won't fix or
change a password if run a second time).
> Adds admin when gitea operator is deployed

- ansible/configs/rhel8lab/post_software.yml
closes #NUM
added several lines for the agnosticd_user_info module to print out ssh/user/pass info when RHEL8 Lab is deployed
removed extraneous blank lines (71-74)
```paste below
```
> change config rhel8lab

- ansible/configs/ocp-workshop/files/cloud_providers/ec2_cloud_template.j2
The s3user dependency is missing in the S3BucketPolicy.
This commit if applied, tries to fix this error:
- AWS::S3::BucketPolicy BucketPolicy CREATE_FAILED: Invalid principal in policy
> Fix ocp-workshop cloudformation error on s3bucketpolicy

- ansible/configs/ocp4-cluster/default_vars_ec2.yml
- ansible/configs/ocp4-workshop/env_vars.yml
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
This PR adds support to specify which AWS zones in any given region the cluster gets installed.
By specifying a YAML list of availability zones the installer only creates MachineSets for the specified zones instead of one MachineSet for every discovered zone. This should make it possible to install into us-east-1 from a Sandbox (just specify less than the default 6 availability zones). But it also makes setting up clusters easier with multiple workers (say 4) that are spread over less than the default zones (like just 2 - for 2 workers in each of the two zones).
Example:
```
openshift_machineset_aws_region: us-east-2
openshift_machineset_aws_zones:
- us-east-2a
- us-east-2b
```
When openshift_machineset_aws_zones is not specified or empty ( [] ) the default behavior will be all available …
> Add support to limit MachineSet creation to specified AWS zones

- ansible/roles-infra/infra-azure-ssh-key/defaults/main.yml
PR https://github.com/redhat-cop/agnosticd/pull/2183 removed a set_fact that this role relied on. So setting a default in the role so it won't fail anymore.
roles-infra/infra-azure-ssh-key
I need to get tags updated in test and prod faster so things like this don't get included by accident
> Change role infra-azure-ssh-key

- ansible/roles-infra/infra-azure-create-inventory/defaults/main.yml
PR https://github.com/redhat-cop/agnosticd/pull/2183 removed a set_fact that this role relied on. So setting a default in the role so it won't fail anymore.
roles-infra/infra-azure-create-inventory
I need to get tags updated in test and prod faster so things like this don't get included by accident
> Change role infra-azure-create-inventory

- ansible/configs/ocp4-ha-lab/files/install-config.yaml.j2
- ansible/configs/ocp4-workshop/files/install-config.yaml.j2
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Change to safely quote all YAML values in OpenShift install-config.yaml produced by jinja template. This will allow use of strings for cluster_name that would otherwise be interpreted as integers or exponential notation (ex: `1e34`)
ocp4-ha-lab config
host-ocp4-installer role
> Change to quote all values in ocp4 install-config

- ansible/roles-infra/infra-gcp-ssh-key/defaults/main.yml
PR https://github.com/redhat-cop/agnosticd/pull/2183 removed a set_fact that this role relied on. So setting a default in the role so it won't fail anymore.
roles-infra/infra-gcp-ssh-key
I need to get tags updated in test and prod faster so things like this don't get included by accident
> Change role infra-gcp-ssh-key

- ansible/roles-infra/infra-gcp-create-inventory/defaults/main.yml
PR https://github.com/redhat-cop/agnosticd/pull/2183 removed a set_fact that this role relied on. So setting a default in the role so it won't fail anymore.
roles-infra/infra-gcp-create-inventory
I need to get tags updated in test and prod faster so things like this don't get included by accident
> Change role infra-gcp-create-inventory

- ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
Ansible seems to randomly select the private IP when there are multiple IPs available to OpenStack instances with multiple NICs. This is specifically affecting the `kni-osp` config where the `private_v4` would sometimes be the pxe network and sometimes the app network - when it always needs to be the app network in this case.
With this change, a config can specify the following two vars to make sure we select the right IP to use. This will default to false, so it will only run if enabled by the config.
`mutli_network` - bool
`multi_network_primary` - full name of the network that you want the IPs selected from
infra-osp-create-inventory
> Change role infra-osp-create-inventory

- ansible/roles_ocp_workloads/ocp4_workload_serverless/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_serverless/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_serverless/templates/catalogsource.j2
- ansible/roles_ocp_workloads/ocp4_workload_serverless/templates/subscription.j2
Add support for Operator Catalog Mirrors to the Serverless Operator. Also download tkn from the installed version of Serverless which always matches the installed version.
> Add support for Catalog Snapshots to Serverless Operator

- ansible/configs/ocp4-ha-lab/files/install-config.yaml.j2
- ansible/configs/ocp4-workshop/README.adoc
- ansible/configs/ocp4-workshop/files/install-config.yaml.j2
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Change to use variable `ocp4_pull_secret` rather than `ocp4_token` and to guard against structured data value in `ocp4_pull_secret`.
ocp4-ha-lab config
host-ocp4-installer role
> Change to use ocp4_pull_secret rather than ocp4_token

- ansible/configs/just-a-bunch-of-nodes/sample_vars_osp.yml
- ansible/configs/multi-cloud-capsule/default_vars.yml
- ansible/configs/rhel-container-security/sample_vars_osp.yml
- ansible/configs/rhel8lab/my_vars_osp_rhel8lab.yml
- ansible/configs/rhel8lab/sample_vars/private-dns-osp.yml
- ansible/configs/rhel8lab/sample_vars_osp.yml
- ansible/configs/rhel8lab/sample_vars_osp.yml.ORIG
- ansible/configs/satellite-infrastructure/default_vars.yml
- ansible/configs/satellite-vm/default_vars.yml
- ansible/configs/smart-management/default_vars.yml
- ansible/configs/three-tier-app/sample_vars/private-dns-osp.yml
The variable `update_all_packages` doesn't exist. In the role 'common' it is
simply called `update_packages`.
This commit if applied, will rename the variables, or just remove it in case the
other variable is already in the file.
sample_vars are usually safe to change, default_vars need a little more extra
precautions.
> Fix occurences of variable 'update_all_packages', rename it to 'update_packages'

- ansible/configs/osp-migration/infra.yml
There is some issues with Distributed Router on OSP Clusters, the idea of this PR is:
Possibility to have in agnosticv the variable: use_openstack_centralized_router (boolean)
If this variable is True, it will use the admin user to create the objects (required for centralized router)
If is false, will continue to use the created user during the lab deployment
> Update config osp-migration to allow create objects as admin for distributed routers

- ansible/roles/ocp4-workload-cnvlab/tasks/post_workload.yml
Adding agnosticd user info output for the kubeadmin password that was missed in the first PR.
> Adding output for kubeadmin password for agnosticd user info

- ansible/configs/test-empty-config/destroy_env.yml
- ansible/configs/test-empty-config/infra.yml
- ansible/configs/test-empty-config/post_infra.yml
- ansible/configs/test-empty-config/post_software.yml
- ansible/configs/test-empty-config/pre_infra.yml
- ansible/configs/test-empty-config/pre_software.yml
- ansible/configs/test-empty-config/software.yml
Fix config test-empty-config where there were various `when` condition tests missing `bool` filter. This is a problem because the string "false" ends up evaluating to a true value.
test-empty-config config
> Fix config test-empty-config when errors without bool filter

- ansible/configs/sap-integration/requirements.yml
Temporarily disable the use of the `sap-hana-preconfigure` role in the `sap-integration` config. It is causing Travis failures due to it using `include`. 
We will need to decide whether restricting the use of `include` is appropriate since it is not actually deprecated.
```
> disable sap-hana-preconfigure role

- ansible/configs/rhel8lab/post_software.yml
closes #NUM
at least one necessary variable is only defined for "workstation", not "localhost".
moved access info output from "localhost" to "workstation" task
config rhel8lab
```paste below
```
> fix config rhel8lab

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_rhacm/templates/multiClusterHub.j2
With the release of RHACM 2.0, this PR will update the version of RHACM being deployed and remove unnecessary tasks and vars for the etcd workaround needed in previous version.
@mvazquezc FYI
> Change workload ocp4_workload_rhacm for GA release

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml
After the `multiclusterhub` CR was created, Ansible checks for the status too quickly and that field is not present. This adds a short pause before it starts the retry loop.
> Update workload ocp4_workload_rhacm

- ansible/roles/ocp4-workload-migration/README.adoc
- ansible/roles/ocp4-workload-migration/meta/main.yml
- ansible/roles/ocp4-workload-migration/tasks/post_workload.yml
- ansible/roles/ocp4-workload-migration/templates/mig-operator-subscription-downstream.yml.j2
This PR updates ocp4-workload-migration to use the latest available release 1.2.4. It also adds minor safe guarding code around usage of agnosticd_user_info module.
Previously, the workload used release 1.1
```paste below
```
> Change workload ocp4-workload-migration to use the latest available release

- ansible/roles/ocp-workload-migration/README.adoc
- ansible/roles/ocp-workload-migration/meta/main.yml
- ansible/roles/ocp-workload-migration/tasks/post_workload.yml
- ansible/roles/ocp-workload-migration/templates/operator.yml.j2
This PR updates ocp-workload-migration to use the latest available release 1.2.4. It also adds minor safe guarding code around usage of agnosticd_user_info module.
```paste below
```
> Change workload ocp-workload-migration to use the latest available release 

- ansible/configs/hacluster-pntae/post_software.yml
bugfix for hacluster-pntae
moved the pntae's customization before flight-check
```paste below
```
> hacluster-pntae: move handling of pntae data before flight-check

- ansible/roles-infra/infra-osp-resources-destroy/tasks/heat.yml
- ansible/roles/host-ocp4-installer/tasks/main.yml
…that fail due to slow OpenStack environments, and where timeouts are common
This adds an additional rescue step for scenarios where the openshift-installer may fail due to hitting a timeout, where instead of the playbook exiting, it will attempt to wait for the cluster to stabilise (with `wait-for bootstrap-complete` and `wait-for install-complete`). In addition, if the cluster is running on OpenStack it will forcefully reboot the nodes as it's common for the hosts to get stuck in a `NotReady` state, and it's been proven that forcing a reboot can recover things. This patch, if executed against a non-OSP environment, will only attempt the additional wait, so it's not invasive.
roles/host-ocp4-installer
> Added a retry mechanism for OpenShift IPI installations

- ansible/roles/ocp4-workload-dil-streaming/templates/che-cluster.yaml.j2
DIL Streaming
Simple update to the che cluster, making the it not timeout after 30 mins of idle time. 
```paste below
```
> [Change][config] - DIL Streaming workshop - Stop che workspace being timeout

- ansible/configs/osp-migration/pre_infra.yml
This PR add the environment variable OS_CACERT to the migration host used to download images from IBM cloud 
osp-migration
> Add OS_CACERT environment variable migration host

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml
Update ocp4-workload-quarkus-workshop to increase Redis cache duration
```paste below
```
> Update ocp4-workload-quarkus-workshop to increase redis cache duration

- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
Migration workloads require combined OCP3 + OCP4 deployment in order to generate bookbag documentation. Since currently, there are two different catalog items for both the clusters, we cannot leverage `agnosticd_user_info` variable from OCP3 side. This PR creates a file on the OCP3 bastion host with properties for bookbag deployment. Sensitive information is not included in the file. The goal is to make it easier for users to generate bookbag docs using this file as input.
```paste below
```
> Change workload ocp-workload-migration to save bookbag variables in a file

- ansible/roles/rhel-custom-security-content-verification/tasks/main.yml
Remove xrdp package from the verification workload since it's not being installed anymore.
Align with changes from: https://github.com/redhat-cop/agnosticd/pull/2248
> Remove xrdp package from the verification workload.

- ansible/roles/ocp4-workload-ml-workflows-infra-summit2020/templates/serverless/subscription.yml.j2
Updated subscription channel for serverless operator from 'techpreview' to '4.3'.
> update serverless subscription channel'

- ansible/configs/osp-migration/post_software.yml
Currently labconsole is on OCP 4.1 and it was required to move to a new cluster
> update config osp-migration to use new labconsole hosted on OCP4.4 shared cluster

- ansible/roles_ocp_workloads/ocp4_workload_authentication/defaults/main.yml
Added variable documentation on how to provide a filter for LDAP (e.g. to restrict access to members of a specific group)
> Added documentation on how to add a filter to the LDAP configuration.

- ansible/roles/ocp4-workload-ocs-poc/README.adoc
- ansible/roles/ocp4-workload-ocs-poc/defaults/main.yml
- ansible/roles/ocp4-workload-ocs-poc/tasks/workload.yml
- ansible/roles/ocp4-workload-ocs-poc/templates/namespace.yml.j2
- ansible/roles/ocp4-workload-ocs-poc/templates/subscription.yml.j2
This PR adds the ability to use a custom operator source. This is useful when users want to install the latest ocs-operator from `redhat-operators` operator sources. By default, existing catalog source snapshot is used which is pinned to `stable-4.2` channel of OCS operator. 
Fixes #2316 
ocp4-workload-ocs-poc
```paste below
```
> Change workload ocp4-workload-ocs-poc to allow using custom operator source

- ansible/roles/ocp4-workload-dil-streaming/templates/user_registration.yaml.j2
This PR fixes https://github.com/RedHatWorkshops/dayinthelife-streaming/issues/64 where students were assigned the same workshop user, using now latest version from openshiftlabs (same as other middleware workshops)
user-registration
```paste below
```
> use latest image for user-registration from openshiftlabs

- ansible/roles/agnosticd_dynamic/tasks/install-git-source.yaml
- ansible/roles/agnosticd_dynamic/tasks/main.yml
The `agnosticd_dynamic` role has two bugs, one is a typo which causes the role to fail when using git sources (filter name is incorrect).
The second bug is also related to git sources where the symbolic link was using an incorrect source.
Add the following variable to pull in a dynamic git source
```
agnosticd_dynamic_role_git_sources:
- repo: https://github.com/redhat-cop/openshift-applier.git
version: v2.1.2
role_paths:
openshift-applier: roles/openshift-applier
```
```paste below
```
> Fix two issues with agnosticd_dynamic role

- ansible/roles-infra/infra-ec2-template-create/defaults/main.yml
Add uuid tag with default empty string to standard ec2 instance tags.
Infrastructure role infra-ec2-template-create
> Change role infra-ec2-template-create to add uuid to cloud tags

- ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/tasks/workload.yml
Fixes an issue of creating an IS when it already exists in the cluster.
n.a.
> Applying instead of creating RHPAM IS.

- ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/tasks/grafana_workload.yml
Sets Grafana limits on Deployment instead of DeploymentConfig (seems to have changed in a recent RHPDS upgrade).
> Grafana is now a deployment instead of a deployment config.

- ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/tasks/workload.yml
Fix oc commands for dataloader, as the dataloader is now a deployment instead of a deployment config.
n.a.
> Dataloader is now a deployment instead of a deployment config.

- tests/static/syntax-check.sh
Fix static test syntax-check.sh git clone of https://github.com/ansible/workshops.git by setting branch to master.
AgnosticD static tests
> Fix static tests git clone for ansible workshops

- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_nested.j2
Creating multiple servers in parallel creates multiple calls to the metadata server. That can cause deployment failure. To avoid this, OSP provides an option to create a virtual disk to access to metadata, to enable that, "config_drive: True" is needed on the Heat template.
> Update role-infra infra-osp-template-generate to use add a parameter to heat template

- ansible/configs/ocp4-cluster/default_vars.yml
- ansible/roles/host-ocp4-installer/files/cluster-network-03-config.yml
- ansible/roles/host-ocp4-installer/tasks/generate_install_config.yml
- ansible/roles/host-ocp4-installer/tasks/main.yml
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Add Support for OVN networking Plugin to ocp4-cluster config (for OCP 4.6+)
Config: ocp4-cluster
Role: host-ocp4-installer
This currently requires a nightly release.
To enable:
```
ocp4_installer_use_dev_preview: true
ocp4_installer_version: 4.6.0
ocp4_installer_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.6/openshift-install-linux.tar.gz
ocp4_client_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.6/openshift-client-linux.tar.gz
ocp4_network_type: OVNKubernetes
```
> Add support for OVN Networking for OCP 4.6+

- ansible/roles_ocp_workloads/ocp4_workload_serverless/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml
Added support to Serverless workload to install the matching serverless version for the cluster version.
Bugfix to not wait for Completed pods on Remove.
> Add support to install matching serverless channel for cluster version

- ansible/roles/set-repositories/tasks/satellite-repos.yml
When launching a config multiple times with `repo_method: satellite` the current role breaks. This is due to `/etc/rhsm/rhsm.conf` containing the default values for the Red Hat CDN but pointing to a `/etc/yum.repos.d/redhat.repo` file with satellite repository values. When attempting to use the package module in these conditions (even when removing a pacakge) the repo data is polled failing with a "Unable to find metadata for <repo>". Since no repository info is required to remove the role specified packages we can add `disablerepo: "*"` to these tasks and skip the poll up to the point where we re-install the `katello-ca-consumer-latest` to replace the default values of `rhsm.conf`.
set-repositories/tasks/satellite-repos.yml
To reproduce run a config registering to a …
> Resolve bug for re-registering a previous satellite host

- ansible/roles/ocp4-workload-cnvlab/tasks/workload.yml
We've seen some issues with busy clusters and commands that only
have a single attempt cause entire deployment failures. This is
largely happening post-deployment when the OpenShift cluster is
already up and running. This patch attempts to provide some
more attempts where we've seen these failures
ocp4-workload-cnvlab
> Add additional attempts to deploy the CNV Lab Workbook

- ansible/configs/ansible-workshops/pre_infra.yml
user.info has traditionally lacked context and users have been unable to tell which type of workshop the user.info (email) pertains to.
This is exacerbated by the fact that users may well spin up 2 or more **different** workshops at a time.
Fix puts identifying information into user.info
Config: ansible_workshops
> Enhance user.info for Ansible Workshops to contain workshop name

- ansible/roles/ocp4-workload-ccnrd/tasks/install-guides.yaml
Fix missing brace to define a parameter in install-guide task
```paste below
```
> Fix missing brace

- ansible/configs/rhel-custom-security-content/post_software.yml
Do not print out user info when deployment uses bookbag documentation interface.
> Print out user info only when bookbag is not defined.

- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin-student/tasks/workload.yml
Change workload role ocp4-workload-workshop-dashboard-cluster-admin-student to use `agnosticd_user_info` in order to allow this content to be picked up by the babylon infrastructure.
ocp4-workload-workshop-dashboard-cluster-admin-student
> Change ocp4-workload-workshop-dashboard-cluster-admin-student agnosticd_user_info

- ansible/roles/vscode-server/tasks/nginx-server.yml
The new vscode-server role uses certbot/letsencrypt which **fails** when used with an email address ending example.com. This occurs throughout many Agnosticd configs.
Rolew made more robust by re-writing any example.com emails to opentlc.com
> Make VSCode role more robust

- ansible/configs/ocp4-cluster/workloads.yml
This changes the workload.yml in ocp4-config to run the student_workloads through a list filter. This has been tested locally for a deployment using `student_workloads: []`
ocp4-cluster
> Update config ocp4-cluster with student_workload list

- ansible/roles-infra/infra-ec2-template-create/.yamllint
- ansible/roles-infra/infra-ec2-template-create/defaults/main.yml
- ansible/roles-infra/infra-ec2-template-create/tasks/main.yml
Use default `uuid` tag value `none` rather than empty string for ec2 templates.
This resolves an issue reported by @prakhar1985 when `uuid` variable is not set.
The need for this change is a bit of a mystery because according to AWS documentation an empty string is a valid tag value.
role infra-ec2-template-create
> Change role infra-ec2-template-create to use "none" as default uuid

- ansible/roles/ocp4-workload-ccnrd/files/cheplugin-meta.yaml
- ansible/roles/ocp4-workload-ccnrd/files/codeready_cr.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-codeready.yaml
Fix to create multiple namespaces for each CRW workspace with enabling MTA IDE plugin
```paste below
```
> Fix to create multiple namespaces for each CRW workspace

- ansible/roles/set-repositories/tasks/satellite-repos.yml
Installing the Satellite CA certificate sometimes fails with a GPG error.
Using `yum` instead of `package` with the `disable_gpg_check: true` parameter fixes this.
> Update Satellite CA package installation mechanism

- ansible/configs/ocp4-cluster/destroy_env_ec2.yml
Destroy failed (well, starting instances failed) when there were terminated instances still around. Added filters and better logic to only start stopped instances and leave terminated instances alone.
ocp4-cluster
> Update logic for ocp4-cluster ec2 destroy

- ansible/roles/bastion-lite/tasks/main.yml
- ansible/roles/host-ocp4-provisioner/tasks/osp_prereqs.yml
Fix bastion-lite and host-ocp4-provisioner to allow `ansible_user` home directory to be in a location other than `/home/{{ ansible_user }}`. Ansible path evaluation honors the standard `~USER/` syntax to lookup a user home directory.
Roles bastion-lite and host-ocp4-provisioner
> Fix roles bastion-lite and host-ocp4-provisioner user home dir

- ansible/roles_ocp_workloads/ocp4_workload_machinesets/tasks/workload.yml
The check to create infra nodes always evaluated to true. This should fix it.
ocp4_workload_machineset
> fix check to create infra nodes

- ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/infrastructure.yml
The shell command used to retrieve the OCP internal registry route is incorrect, resulting in a failure of the lab. Fixed the grep.
> Fix the command used to retrieve the image registry url

- ansible/roles-infra/infra-aws-sandbox/defaults/main.yml
Once a Backup plan and vault is created in the account, it cannot be
deleted and aws-nuke fails.
This commit, if applied, fixes that by ignoring those default resources.
> Change infra-aws-sandbox, Fix aws-nuke failing because of AWSBackup default

- ansible/configs/rhel-security/software.yml
Configure ssh keys so `student_name` user can connect ssh passwordless between nodes without having to switch to `root` before.
rhel-security
> Add key configuration for student_name.

- ansible/roles_ocp_workloads/ocp4_workload_example_shared_cluster/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/workload.yml
Some workloads used the wrong check (availableReplicas) to check for ready pods. Replaced with the proper check (readyReplicas).
> Fix check for ready pods (availableReplicas -> readyReplicas)

- ansible/configs/cloud-credentials/default_vars.yml
- ansible/configs/cloud-credentials/default_vars_ec2.yml
- ansible/configs/cloud-credentials/files/cloud_providers/ec2_cloud_template.j2
- ansible/configs/cloud-credentials/infra.yml
- ansible/configs/cloud-credentials/post_infra.yml
- ansible/configs/cloud-credentials/pre_infra.yml
The first version of cloud-credentials had a few issues generating the cloudformation template for EC2. Rather than use the full template generate role, the necessary minimum tasks have been added to the config in order to avoid changes to a well used cloud provider role.
cloud-credentials
> Update config cloud-credentials for template generation

- ansible/roles/ocp-workload-mediawiki/README.adoc
- ansible/roles/ocp-workload-mediawiki/defaults/main.yml
- ansible/roles/ocp-workload-mediawiki/files/mariadb.yml
- ansible/roles/ocp-workload-mediawiki/files/mediawiki-ns.yml
- ansible/roles/ocp-workload-mediawiki/files/mediawiki-route.yml
- ansible/roles/ocp-workload-mediawiki/meta/main.yml
- ansible/roles/ocp-workload-mediawiki/tasks/main.yml
- ansible/roles/ocp-workload-mediawiki/tasks/post_workload.yml
- ansible/roles/ocp-workload-mediawiki/tasks/pre_workload.yml
- ansible/roles/ocp-workload-mediawiki/tasks/remove_workload.yml
- ansible/roles/ocp-workload-mediawiki/tasks/workload.yml
- ansible/roles/ocp-workload-mediawiki/templates/mediawiki.yml.j2
This PR adds a new workload `ocp-workload-mediawiki`. It is meant to be deployed on 3.x OpenShift clusters. It will be used in CAM labs to demonstrate a use-case of migration as described here: https://github.com/konveyor/mig-operator/blob/master/docs/usage/10.md
ocp-workload-mediawiki
The reason `oc` command is used is that the 3.x lab envs we deploy don't have python-openshift available.
```paste below
```
@jwmatthews @tsanders-rh
> Add workload MediaWiki sample application for OpenShift migration demos

- ansible/roles_ocp_workloads/ocp4_workload_windows_node/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/files/sshcmd.sh
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/catalogsource.j2
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/namespace.j2
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/operatorgroup.j2
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/sshsecrets.j2
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/subscription.j2
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/windows-ms.j2
This workload deploys a windows node on a 4.6 cluster. It also deploys ssh helper scripts in order to get a powershell connection into the windows node.
This playbook deploys a Windows Server 2019 with Containers instance and adds it as a OpenShift node. A few things to note.
* This playbook requires 4.6
* OCP 4.6 needs to be installed using OVNKubernetes network plugin
* I temporarily extract the install keys in order to list the ami to get the right Windows ami dynamically.
* I backup the aws config for the ec2-user and restore it once I get the right ami.
> Ocp4 workload windows node

- ansible/cloud_providers/azure_infrastructure_deployment.yml
- ansible/configs/aro/destroy_env.yml
- ansible/roles-infra/infra-azure-create-inventory/tasks/main.yml
- ansible/roles-infra/infra-azure-create-service-principal/tasks/main.yml
- ansible/roles-infra/infra-azure-delete-service-principal/tasks/main.yml
- ansible/roles-infra/infra-azure-ssh-key/tasks/main.yml
- ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml
- ansible/roles/host-ocp4-provisioner/tasks/azure_prereqs.yml
Remove PATH environment variable for az commands to enable execution when
az is installed within a python virtualenv.
azure cloud_provider
aro config
Roles:
- infra-azure-create-inventory
- infra-azure-create-service-principal
- infra-azure-delete-service-principal
- infra-azure-ssh-key
- infra-azure-template-destroy
- host-ocp4-provisioner
> Remove set PATH for az commands

- ansible/roles/ocp4-workload-quarkus-workshop/files/rhsso-template.yaml
Occasionally, depending on timing, RH-SSO will come up ahead of its dependent database (postgres). When this happens, SSO will fail to initialize but continue to run and never be able to work properly. This adds health probes to the app so that OpenShift will kill and restart the pod in this case, so that it can come back up and connect properly.
> Add health probes for SSO

- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_windows_node/templates/windows-ms.j2
This PR improves the playbook by using `ec2_ami_info` instead of calling the `shell` module and running the `aws` cli. A byproduct of this, is that I no longer need to touch the `~ec2-user/.aws/credentials` file at all. Therefore I've removed that part of the playbook, which simplifies the playbook.
Enhancement.
`ec2_ami_info` added to this playbook.
N/A
> Using ec2_ami_info module instead of using shell with the aws cli

- ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/quay.yml
The currentCSV parameter is in a nested array so an additional filter through `first` is required.
```paste below
```
> Retrieve parameter from nested array

- ansible/roles_ocp_workloads/ocp4_workload_dso/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/infrastructure.yml
Variables related to the bastion were incorrectly hardcoded. Instead use the `guid` and `subdomain_base_suffix`. Also Update jenkins version from `latest` to `2`
```paste below
```
> Replace incorrect hardcoded values

- ansible/configs/ansible-multitier-infra/files/hosts_template.j2
TASK [generate ansible hosts file] *
Friday 11 September 2020 23:33:45 +0000 (0:00:00.184) 0:05:46.005 **
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'inventory_groups' is undefined"}
See log on admin-dev: dev-collections-lab-76b1.log
hosts_template.j2
> inventory_group error fixed

- ansible/configs/ansible-multitier-infra/default_vars_osp.yml
P address. Additionally, please check that", "   your computer has a publicly routable IP address and that no", "   firewalls are preventing the server from communicating with the", "   client. If you're using the webroot plugin, you should also verify", "   that you are serving files from the webroot path you provided.", " - Your account credentials have been saved in your Certbot", "   configuration directory at /etc/letsencrypt. You should make a", "   secure backup of this folder now. This configuration directory will", "   also contain certificates and private keys obtained by Certbot so", "   making regular backups of this folder is ideal."]}
default_vars_ops.yml
443 open.
> SG fixed for certbot

- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/README.adoc
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/defaults/main.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/meta/main.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/tasks/main.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/tasks/post_workload.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/tasks/pre_workload.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/tasks/remove_workload.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/tasks/workload.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/templates/buildconfig.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/templates/imagestream.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_setup/templates/project.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/.yamllint
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/README.adoc
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/defaults/main.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/meta/main.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/tasks/main.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/tasks/post_workload.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/tasks/pre_workload.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/tasks/remove_workload.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/tasks/workload.yaml
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/deployment.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/project.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/pvc.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/rolebinding.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/rolebinding_image_puller.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/route.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/service.yaml.j2
- ansible/roles_ocp_workloads/ocp4_workload_bookbag_user/templates/service_account.yaml.j2
This PR introduces two new bookbag workloads:
*ocp4_workload_bookbag_setup*: this workload builds a bookbag image from a git repository.
*ocp4_workload_bookbag_user*: this workload deploys a bookbag for a user in a new project from the image that the other role created.
Use case:
On a shared cluster use *ocp4_workload_bookbag_setup* as an `infra_workload` to create the image.
Then use *ocp4_workload_bookbag_setup* as a `student_workload` to deploy x number of bookbags
Second use case:
Create the image when setting up a shared cluster.
On demand when provisioning an environment deploy the workloads that make up the environment and the ocp4_workload_bookbag_user role to deploy the matching bookbag.
ocp4_workload_bookbag_setup
ocp4_workload_bookbag_user
Example …
> New bookbag roles.

- ansible/roles/ocp4-workload-ccnrd/files/cheplugin-meta.yaml
To maintain all images in a single repository, quay.io, I cloned the rhamt-vscode-extension:java11 image to quay.io.
```paste below
```
> Clone rhamt-vscode-extension:java11 image from dockerhub to quay.io

- ansible/roles-infra/infra-osp-resources-destroy/defaults/main.yaml
The infra-osp-resources-destroy role does not define a default for `osp_project_create`, while the role infra-osp-project-create defines this as true. The result is that a config provisions without this set but fails on destroy.
Role infra-osp-rsources-destroy
> Fix role infra-osp-resources-destroy to set default osp_project_create

- ansible/roles-infra/infra-ec2-template-generate/defaults/main.yml
- ansible/roles-infra/infra-ec2-template-generate/tasks/locate_availability_zones.yml
- ansible/roles-infra/infra-ec2-template-generate/tasks/main.yml
This commit, if applied, adds a feature to auto detect availbility zones (AZ)
that can host all the instance types defined in the `instances` variable.
If the AZ is omitted in the CloudFormation template, AWS doesn't guarantee to pick the right AZ and that sometimes results in errors of the type:
> "resource_status_reason: Your requested instance type (c3.large) is not supported in your requested Availability Zone (us-east-1a). Please retry your request by not specifying an Availability Zone or choosing us-east-1b, us-east-1d, us-east-1c, us-east-1e."
In order to fix that, this commit adds a set of tasks in the
infra-ec2-template-generate role that do the following:
- Get all the instance types
- For each instance type, get all AZs that support it
- Calculate the intersection of all AZs …
> AWS CloudFormation: auto-select AvailabilityZone

- ansible/roles/ocp4-workload-dil-streaming/templates/user_registration.yaml.j2
Day in the streaming life
Add a user assignment duration. Default is 2 hours. This would explain why user assignments are timing out
Closes #2520
> Fix workload dil-streaming user_registration

- ansible/configs/kni-osp/default_vars.yml
Fix k8i-osp config by commenting vars that should be set from secrets.
In some cases, such as `osp_project_id`, when a var is not set then AgnosticD will dynamically adjust its behavior. In the case of `osp_project_id`, to create a project for the deployment. Because the defaults set this to `FROM_SECRETS` it broke this behavior.
config kni-osp
> Fix kni-osp config by commenting default vars from secrets

- ansible/roles_ocp_workloads/ocp4_workload_rhte19_shadowman/defaults/main.yml
Fixes #2549
ocp4_workloads_rhte19_shadowman
The defaults/main.yml variable "documentation_link" was missing the role prefix.
```paste below
```
> Fixing missing prefix in default variables

- ansible/lifecycle_osp.yml
The debug statement is not necessary and is polluting the logs, remove it by adding verbosity.
> Change lifecycle OSP: Dont' print facts (huge debug)
