redhat-cop/agnosticd

ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/workload.yml
properly use ansible groups to address RHEL workers
```paste below
```
=> Wi p judd rhel refactor

ansible/configs/ocp4-equinix-aio/default_vars_equinix_metal.yml, ansible/configs/ocp4-equinix-aio/requirements.yml, ansible/configs/ocp4-equinix-aio/sample_vars_equinix_metal.yml
=> bump versions for CNV on equinix metal

ansible/roles-infra/infra-equinix-metal-resources/tasks/delete_instances.yaml, ansible/roles-infra/infra-equinix-metal-resources/tasks/lookup_project.yaml, ansible/roles-infra/infra-equinix-metal-resources/tasks/start_instances.yaml, ansible/roles-infra/infra-equinix-metal-resources/tasks/stop_instances.yaml
=> incease pagination to 1000 (maximum)

ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/tasks/gitea_create_user.yml, ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/templates/argocd_argocd.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/templates/argocd_namespace.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/templates/dev_namespace.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/templates/pipelines_namespace.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/templates/prod_namespace.yaml.j2
Update Argo CD to v2.1.7 - hopefully that'll fix some of the ILT Final Lab issues.
=> Update to ArgoCD v2.1.7

ansible/cloud_providers/equinix_metal_infrastructure_deployment.yml, ansible/roles-infra/infra-generic-wait_for_linux_hosts/defaults/main.yaml, ansible/roles-infra/infra-generic-wait_for_linux_hosts/tasks/main.yml
=> Parameterize infra_generic_wait_for_linux_hosts

ansible/roles/ocp4-workload-oadp/tasks/workload.yml
Fixing the retry pause and rescue block. 
Indentation fix. 
role: ocp4-workload-oadp
=> Fix rescue block and indentation

ansible/roles/ocp4-workload-ccnrd-stable/files/ccn-sso-template.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/eap74-openjdk11-image-stream.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/sso-image-stream.yaml
=> updating stable ccn with ce workload

ansible/roles/ocp4-workload-ccnrd-stable/defaults/main.yml, ansible/roles/ocp4-workload-ccnrd-stable/files/cheplugin-meta.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/codeready_cr.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/community-operators-index.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/coolstore-monolith-binary-build-template.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/coolstore-monolith-pipeline-build-template.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/elasticsearch_subscription.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/redhat-operators-index.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/stack.Dockerfile, ansible/roles/ocp4-workload-ccnrd-stable/files/stack_imagestream.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/create_che_workspace.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-guides.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/remove_workload.yml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/workload.yml, ansible/roles/ocp4-workload-ccnrd-stable/templates/devfile.json.j2
=> merging CE to stable

ansible/roles_ocp_workloads/ocp4_workload_nginx_ingress/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_nginx_ingress/templates/controller.yml.j2
Just making a couple things variables so we can adjust them on the fly as required.
roles_ocp_workloads/ocp4_workload_nginx_ingress
N/A
=> CHANGE: Updating NGINX workload role for better reuse

ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/ccn-sso-template.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/cheplugin-meta.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/community-operators-index.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/eap74-openjdk11-image-stream.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/redhat-operators-index.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack.Dockerfile, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack_imagestream.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/install-amqstreams.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/install-codeready.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/install-guides.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/install-jaeger.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/install-serverless.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/install-servicemesh.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/install-username-distribution.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/pre_workload.yml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/workload.yml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/templates/devfile.json.j2
Update ocp4-workload-ccn-cuttingedge to upgrade openshift 4.9
- 
```paste below
```
=> Update ocp4-workload-ccn-cuttingedge to upgrade openshift 4.9

ansible/configs/satellite-hackfest/post_software.yml
=> Updating default password for Web UI

ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Windows ami update
us-east-1:
RHELAMI: ami-9ceabde6
WIN2012R2AMI: ami-020f5700d1dc12aa9 # Windows_Server-2012-R2_RTM-English-64Bit-Base-*
us-east-2:
RHELAMI: ami-111f3474
WIN2012R2AMI: ami-0096c2ab70593cfa1 # Windows_Server-2012-R2_RTM-English-64Bit-Base-*
eu-central-1:
RHELAMI: ami-284cdc47
WIN2012R2AMI: ami-013b651fe97fa22d6 # Windows_Server-2012-R2_RTM-English-64Bit-Base-*
ap-southeast-1:
RHELAMI: ami-01e99e7d
WIN2012R2AMI: ami-004fb28be2cd88a72 # Windows_Server-2012-R2_RTM-English-64Bit-Base-*
=> Windows ami update

ansible/configs/ansible-windows/env_vars.yml, ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Quick fix in evn_vars.yml for windows ami
=> Ansible windows ami

ansible/configs/ansible-windows/env_vars.yml
image name added in instances
Ansible windows
=> Ansible windows fix

ansible/roles_studentvm/studentvm_ocp4/defaults/main.yml, ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
Mostly support newer versions of kubeseal and kn. But also set defaults to current versions.
studentvm_ocp4
=> Updated to support newer cli tool versions

tools/virtualenvs/azure_open_envs-ansible2.10-python3.8-2022-01-07.txt
create new virtual env for azure open env
open-env-azure
```paste below
```
=> create new virtual env for azure open env

ansible/configs/open-environment-azure/README.adoc, ansible/configs/open-environment-azure/default_vars.yml
=> cleanup vars for azure open env

tools/virtualenvs/azure_open_envs-ansible2.10-python3.6-2022-01-07.txt
=> remove winrm from virtualenv

tools/virtualenvs/azure_open_envs-ansible2.10-python3.6-2022-01-07.txt
Update virtual environment build for Azure OPEN Environment
open-env-azure
```paste below
```
=> update azure open environment virtual env

tools/virtualenvs/azure_open_envs-ansible2.10-python3.6-2022-01-07.txt
remove winrm from azure open env virtualenv
open-env-azure
```paste below
```
=> remove winrm from azure open env virtualenv

ansible/configs/aap2-ansible-workshops/vars/automate_smart_mgmt_vars.yml
=> Updating Filter with Wildcard

tools/virtualenvs/azure_open_envs-ansible2.9-python3.6-2022-01-10.txt
=> one more try for venv

tools/virtualenvs/azure_open_envs-ansible2.9-python3.6-2022-01-10.txt
add containerregistry to azure open env virtenv
open-env-azure
```paste below
```
=> add containerregistry to azure open env virtenv

ansible/configs/sap-smart/post_software.yml
Added SElinux command to restore the context in sap-smart lab and solve issue described in https://bugzilla.redhat.com/show_bug.cgi?id=1873319 
```paste below
```
=> Solve Pulp error in sap-smart lab

ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml
=> Fix variable name

ansible/configs/open-environment-azure/post_software.yml
update environment output from azure open environment
open-env-azure
```paste below
```
=> update environment output from azure open environment

ansible/roles/ocp4-workload-debezium-demo/tasks/post_workload.yml
Commenting out the OCP Console section, as this is provided by the OCP4 Authentication Role
```paste below
```
=> ocp4-workload-debezium-demo user_info

ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml
=> Update variable for dns_zone on infra-osp-dns role

ansible/configs/sap-smart/post_software.yml
Refactored the code to solve the Pulp 500 error caused by MongoDB
```paste below
```
=> Solve Pulp error in sap-smart config

ansible/configs/test-empty-config/status.yml
Add status playbook for test-empty-config to allow this config to be useful to testing status functionality.
=> Add status for test-empty-config

ansible/configs/sap-hana/README.adoc, ansible/configs/sap-integration/README.adoc, ansible/configs/sap-rhvh/README.adoc, ansible/configs/sap-smart/README.adoc
Remove my information from the SAP configurations owners
Multiple SAP configs
=> Remove myself as the owner of SAP repos

ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml
=> Fix cluster_dns_server var and port

.gitignore, ansible/configs/ocp4-cluster/default_vars_ec2.yml, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/workload.yml
workload ocp4_workloads/ocp4_workload_rhel_worker is ready for QA.
This workload creates a RHEL 8 instance in an ALREADY EXISTING OpenShift cluster VPC.
The student runs openshift-ansible playbooks on the bastion to install OpenShift on the RHEL8 instance and have it join the cluster.
* Student user is expected, not ec2-user - aka 'lab-user'
* Configures AWS networking, IAM, etc
* adds proper ssh keys to RHEL 8 instance
* Sets up RHEL repos on RHEL 8 instance to install OpenShift on RHEL8
* git Clones openshift-ansible repo onto bastion
```paste below
```
=> ocp4_workload_rhel_worker ready for QA

ansible/roles/open-env-azure-invite-user/tasks/main.yml
Add CICD to new user check
```paste below
```
=> Add CICD to new user check

ansible/roles/open-env-azure-invite-user/tasks/main.yml
fix broken which in open env azure
open-env-azure
```paste below
```
=> fix which in open env azure

ansible/roles/open-env-azure-invite-user/tasks/main.yml
fix when again on open-env-azure
open-env-azure
```paste below
```
=> fix when again on open-env-azure

ansible/configs/sap-smart/default_vars.yml, ansible/configs/sap-smart/post_software.yml
Added one host to create a Pacemaker cluster for the SAP HANA tier and demo the Near Zero Downtime maintenance capabilities
```paste below
```
=> Added resources to sap-smart config for NZD demo

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
=> Fix travis errors

ansible/configs/open-environment-azure/post_software.yml, ansible/roles/open-env-azure-create-open-env/tasks/main.yml, ansible/roles/open-env-azure-delete-open-env/tasks/main.yml
add service principal (api creds) to azure open env
open-env-azure
```paste below
```
=> add service princ to azure open env

ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/post_workload.yml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
Fix user.info module in ocp4-workload-ccnrd-cuttingedge
```paste below
```
=> Fix user.info module in ocp4-workload-ccnrd-cuttingedge

ansible/roles_ocp_workloads/ocp4_workload_dynatrace/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_dynatrace/files/example_app_template.yml, ansible/roles_ocp_workloads/ocp4_workload_dynatrace/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_dynatrace/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_dynatrace/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_dynatrace/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_dynatrace/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_dynatrace/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_dynatrace/templates/namespace.j2
This is to be used as a basis for a Dynatrace catalog item in RHDPS.  This will be used for tracking Dynatrace lab deployments and to have a landing page for Dynatrace labs in RHPDS.
ocp4_workload_dynatrace
This was tested on the OCP 4.9 Workshop.  The lab guide will be on dynatrace.com and will include installing and configuring the operator.   
```
ansible [core 2.11.6] 
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/gejames/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /home/gejames/.local/lib/python3.8/site-packages/ansible
ansible collection location = /home/gejames/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/bin/ansible
python version = …
```
=> add workload ocp4_workload_dynatrace

ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
Fix ocp4-workload-ccn-cuttingedge to update user.info
```paste below
```
=> Fix ocp4-workload-ccn-cuttingedge to update user.info

ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/post_workload.yml
Fix ocp4-workload-ccn-cuttingedge to fix user.info module
```paste below
```
=> Fix ocp4-workload-ccn-cuttingedge to fix user.info module

ansible/roles/ocp4-workload-dil-serverless/tasks/post_workload.yml
Add data information in email when deploying azure
dil-serverless-multicloud
```paste below
```
=> add data to message body

ansible/roles/ocp4-workload-ccnrd-stable/tasks/post_workload.yml
Fix ocp2-workload-ccn-stable to remove quote
```paste below
```
=> Fix ocp2-workload-ccn-stable to remove quote

ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
Fix ocp4-workload-quarkus-workshop to replace user.info module
```paste below
```
=> Fix ocp4-workload-quarkus-workshop to replace user.info module

ansible/configs/rosa/software.yml
fix bug in agnosticd_user_info for rosa
rosa
```paste below
```
=> fix bug in agnosticd_user_info for rosa

ansible/configs/rosa/default_vars.yml, ansible/configs/rosa/default_vars_ec2.yml, ansible/configs/rosa/software.yml
standardize rosa to use bastion
rosa
```paste below
```
=> standardize rosa to use bastion

ansible/configs/rosa/default_vars_ec2.yml
Update rosa bastion default image type
rosa
```paste below
```
=> Update rosa bastion default image type

ansible/configs/open-environment-azure/post_software.yml
update azure open environment details
```paste below
```
=> update azure open environment details

ansible/lookup_plugins/bitwarden.py
Add `bitwarden` lookup plugin.
Lookup plugin `bitwarden`
=> Add bitwarden lookup plugin

CODEOWNERS
=> Add lookup plugin to codeowners

ansible/configs/sandbox/pre_infra_ec2.yml
Update password generation and output for ROSA
rosa
```paste below
```
=> Update password generation and output for ROSA

ansible/roles/ocp4-workload-debugging-workshop/defaults/main.yml
crwoperator.v2.12.1
```paste below
```
=> Updating Codeready operator version to 2.12

ansible/roles/ocp4-workload-debugging-workshop/tasks/post_workload.yml
=> Updating openshift-workspaces in the namespaces

ansible/roles/ocp4-workload-debugging-workshop/defaults/main.yml
Reverts redhat-cop/agnosticd#4450
=> Revert "Updating Codeready operator version to 2.12"

ansible/roles_ocp_workloads/ocp4_workload_adv_day2_ops_ilt/tasks/workload.yml
Update the AWS Access Key ID variable to work out of the box.
ocp4_workload_adv_day2_ops_ilt
=> Update the variable name used for the AWS Access Key ID

ansible/roles/ocp4-workload-debugging-workshop/tasks/post_workload.yml
Reverts redhat-cop/agnosticd#4452
=> Revert "Updating openshift-workspaces in the namespaces"

ansible/roles/ocp4-workload-debugging-workshop/defaults/main.yml
=> codeready operator version downgraded to crwoperator.v2.12.1

ansible/roles/ocp4-workload-debugging-workshop/defaults/main.yml
change the version of elasticsearch version to 5.2.7-18
Elasticsearch operator version 
```paste below
```
=> elasticsearch-operator.5.2.7-18

ansible/roles/ocp4-workload-debugging-workshop/tasks/post_workload.yml
=> update using k8s_info

ansible/roles/ocp4-workload-debugging-workshop/tasks/post_workload.yml
=> indentation issue with k8s_info command

ansible/roles_ocp_workloads/ocp4_workload_rhacm/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml
Refactor `ocp4_workload_rhacm` to use `install_operator` role.
ansible 2.9.20
config file = /Users/singularity/src/agnosticd/ansible.cfg
configured module search path = ['/Users/singularity/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /Users/singularity/.virtualenvs/deployer/lib/python3.10/site-packages/ansible
executable location = /Users/singularity/.virtualenvs/deployer/bin/ansible
python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
```
ansible==2.9.20
appdirs==1.4.4
attrs==21.4.0
autopage==0.5.0
Babel==2.9.1
boto3==1.20.46
botocore==1.23.46
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.11
cliff==3.10.0
cmd2==2.3.3
cryptography==36.0.1 …
```
=> Refactor ocp4_workload_rhacm to use install_operator

ansible/install_galaxy_roles.yml
Use collections path to determine where to install collections.
Automatic ansible-galaxy requirements resolution.
=> Fix to install collections into collections paths

ansible/roles_ocp_workloads/ocp4_workload_mtv/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mtv/files/forkliftcontroller.yaml, ansible/roles_ocp_workloads/ocp4_workload_mtv/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mtv/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_mtv/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mtv/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mtv/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mtv/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mtv/tasks/workload.yml
New workload to deploy the Migration Toolkit for Virtualization Operator and ForkliftController.
ocp4_workload_mtv
=> Created new workload to deploy migration toolkit for virtualization

ansible/roles/install_operator/defaults/main.yml, ansible/roles/install_operator/meta/main.yml, ansible/roles/install_operator/tasks/install.yml, ansible/roles/install_operator/tasks/main.yml, ansible/roles/install_operator/tasks/remove.yml
Added the operator name to every task in the install_operator role to make it easier to see at a glance which operator is being installed / removed.
=> Add operator name to all tasks

docs/Preparing_your_workstation.adoc, tools/execution_environments/ansible2.9-legacy-pyvenv/do-all.sh, tools/execution_environments/ansible2.9-legacy-pyvenv/install_binaries.sh, tools/execution_environments/ee-multicloud-public/build.sh, tools/execution_environments/ee-multicloud-public/install_binaries.sh, tools/execution_environments/ee-multicloud/build.sh, tools/execution_environments/ee-multicloud/install_binaries.sh, tools/execution_environments/readme.adoc
* Push to both PROD registries, the active and the passive.
* update documentation, link EE doc from top doc
* add example of config for ansible-navigator
=> Update build scripts for EE and documentation

ansible/roles_ocp_workloads/ocp4_workload_rhacm/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/files/multiclusterhub.yaml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml
Catalog Snapshot Handling was not working. Fixed.
=> Fix ACM Workload's snapshot handling

ansible/configs/ocp4-equinix-aio/requirements.yml
updating cnvlab version for ocp4-equinix-aio
=> updating cnvlab version for ocp4-equinix-aio

ansible/configs/sap-hana/software.yml
Uncommented AAP2 install as requested
```paste below
```
=> Uncomment  AAP2 Install

ansible/configs/sap-hana/default_vars_osp.yml, ansible/configs/sap-hana/post_software.yml, ansible/configs/sap-hana/software.yml
Updates the playbooks to avoid controller installation until offline_token vault is fixed
- Temporary Bugfix Pull Request
configs/sap-hana
Change requested by Ahsen Shah
=> Updated config/sap-hana to avoid tower/controller provisioning

ansible/roles/ocp4-workload-ccnrd-stable/files/ccn-sso-template.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/cheplugin-meta.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/community-operators-index.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/eap74-openjdk11-image-stream.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/redhat-operators-index.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/stack.Dockerfile, ansible/roles/ocp4-workload-ccnrd-stable/files/stack_imagestream.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-amqstreams.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-codeready.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-guides.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-jaeger.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-serverless.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-servicemesh.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-username-distribution.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/post_workload.yml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/pre_workload.yml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/workload.yml, ansible/roles/ocp4-workload-ccnrd-stable/templates/devfile.json.j2
=> Updating Stable CCN with CE base

ansible/roles/ocp4-workload-debezium-demo/tasks/provision_streams.yaml
=> Updating AMQ Sream version to beta2

ansible/roles/ocp4-workload-debezium-demo/tasks/provision_streams.yaml
Reverts redhat-cop/agnosticd#4510
=> Revert "Updating AMQ Sream version to beta2"

ansible/roles/ocp4-workload-debezium-demo/templates/snapshot-catalogsource.yaml.j2
=> Updating snapshot_redhat_catalog version to v4.9

ansible/roles_ocp_workloads/ocp4_workload_mta/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta/files/tackle.yaml, ansible/roles_ocp_workloads/ocp4_workload_mta/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_mta/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta/tasks/workload.yml
New workload to deploy Migration Toolkit for Applications (well, Tackle Community until MTA is GA...)
ocp4_workload_mta
=> Add workoad to deploy MTA

ansible/roles/ocp4-workload-debezium-demo/defaults/main.yaml, ansible/roles/ocp4-workload-debezium-demo/readme.adoc, ansible/roles/ocp4-workload-debezium-demo/tasks/post_workload.yml, ansible/roles/ocp4-workload-debezium-demo/tasks/provision_e2e_demo.yaml, ansible/roles/ocp4-workload-debezium-demo/tasks/provision_instructions.yaml, ansible/roles/ocp4-workload-debezium-demo/tasks/provision_mysql_demo.yaml, ansible/roles/ocp4-workload-debezium-demo/tasks/provision_pgsql_demo.yaml, ansible/roles/ocp4-workload-debezium-demo/tasks/provision_registry.yaml, ansible/roles/ocp4-workload-debezium-demo/tasks/provision_streams.yaml, ansible/roles/ocp4-workload-debezium-demo/tasks/remove_workload.yml, ansible/roles/ocp4-workload-debezium-demo/tasks/workload.yml, ansible/roles/ocp4-workload-debezium-demo/templates/instructions-group.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/instructions-services.json.j2, ansible/roles/ocp4-workload-debezium-demo/templates/instructions-webapp.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connect.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connector-camel-elastic.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connector-camel-sql.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connector-mssql.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connector-mysql.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/kafka-demo.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/kafka-topic.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/postgresql.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/registry-subscription.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/registry.yaml.j2, ansible/roles/ocp4-workload-debezium-demo/templates/snapshot-catalogsource.yaml.j2
=> Development debezium demo ahsen

ansible/configs/sap-hana/default_vars.yml, ansible/configs/sap-hana/software.yml
Debugging AAP2 installation
configs/sap-hana
```paste below
```
=> configs/sap-hana: changing offline_tokne variable

ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/cheplugin-meta.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/community-operators-index.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/redhat-operators-index.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack.Dockerfile, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack_imagestream.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/install-guides.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/templates/devfile.json.j2
Update ocp4-workload-ccnrd-cuttingedge for OpenShift 4.10
```paste below
```
=> Update ocp4-workload-ccnrd-cuttingedge for OpenShift 4.10

ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/per_user_workload.yaml
=> increase waits for servicemesh workload csv

ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/per_user_workload.yaml
=> add more tries and delay to servicemesh install csv

ansible/roles/ocp4-workload-quarkus-workshop/files/redhat-operators-index.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile, ansible/roles/ocp4-workload-quarkus-workshop/files/stack_imagestream.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-amqstreams.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-codeready.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-jaeger.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhsso.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/pre_workload.yml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/verify-workload.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml, ansible/roles/ocp4-workload-quarkus-workshop/templates/devfile.json.j2
Update-ocp4-workload-quarkus-workshop to upgrade OpenShift 4.10
```paste below
```
=> Update-ocp4-workload-quarkus-workshop to upgrade OpenShift 4.10

ansible/roles/set_env_authorized_key/tasks/main.yml
=> set_env_authorized_key: Add missing delegate_to

ansible/roles/set_env_authorized_key/tasks/main.yml
=> Add missing become to delegated task

ansible/roles-infra/infra-images/defaults/main.yaml
Tested with:
```yaml
- hosts: localhost
gather_facts: false
tasks:
- include_role:
name: infra-images
vars:
instances:
- name: bastion0
image: RHEL8-default
- name: bastion1
image: RHEL9-default
- name: bastion2
image: RHEL8-latest
- name: bastion3
image: RHEL9-latest
```
Before:
```
ok: [localhost] => (item=bastion0) => {
"msg": "bastion0 - RHEL-8.6.0_HVM_BETA-20220302-x86_64-5-Access2-GP2 - ami-0c4c735481cedcc09 - Red Hat BYOL Linux"
}
ok: [localhost] => (item=bastion1) => {
"msg": "bastion1 - RHEL-9.0.0_HVM_BETA-20211026-x86_64-10-Access2-GP2 - ami-02032f132f9ac0929 - Red Hat BYOL Linux"
}
ok: [localhost] => (item=bastion2) => {
"msg": "bastion2 - RHEL-8.6.0_HVM_BETA-20220302-x86_64-5-Hourly2-GP2 - ami-073c570ae7a0977cb - Red Hat Enterprise Linux"
}
ok: [localhost] => (item=bastion3) …
```
=> infra-images: Update pattern not to pick BETA AMIs

ansible/configs/test-empty-config/post_software.yml
Fix off-by-one error in test-empty-config.
=> Fix test-empty-config user count off-by-one error.

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern/templates/values-global.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern/templates/values-secret.yaml.j2
Updated validated patterns workload to support more patterns and s3 buckets.
ocp4_workload_validated_pattern
=> Update validated patterns workload

ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/tasks/workload.yml
set starting csv to null in workload
```paste below
```
=> change rhods operator starting csv

ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/templates/kafka-cluster-provisioner-rb.j2, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/templates/kafka-cluster-provisioner.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/templates/kafka-ephemeral.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/templates/kafka-topic.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/templates/kafka-user.yaml.j2
Creating a new workload to install AMQ Streams operator and create a new empty cluster.
Using install operator role to install AMQ Streams operator and created a new Task do configure a new AMQ Streams cluster
N/A
```paste below
ansible==2.9.27
argcomplete==1.12.3
awscli==1.22.60
Babel==2.9.1
bcrypt==3.2.0
Beaker==1.10.0
beautifulsoup4==4.9.3
blivet==3.4.3
blivet-gui==2.3.0
boto3==1.21.4
botocore==1.24.5
Brlapi==0.8.2
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.4
chrome-gnome-shell==0.0.0
click==8.0.1
colorama==0.4.3
configobj==5.0.6
cryptography==3.4.7
cupshelpers==1.0
dasbus==1.6
dbus-python==1.2.18
decorator==5.0.9
defusedxml==0.7.1
distro==1.6.0
docutils==0.15.2
fedora-third-party==0.8
fluidity-sm==0.2.0
fros==1.1
git-cola==3.11.0
gpg==1.15.1 …
```
=> Add new workload to install AMQ Streams operator and create a new cluster

ansible/configs/sap-smart/requirements.yml
=> Sap-smart: add ansible collections

ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/tasks/workload.yml
=> whitespace and syntax edit to rhods workload.yml

ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/tasks/workload.yml
=> Kabdo ocp4 rhods olm

ansible/configs/open-environment-azure-subscription/post_software.yml
Fix bug in post_software for open-environment-azure-subscription
```paste below
```
=> fix bug in post_software

tools/virtualenvs/azure_open_envs-ansible2.9-python3.6-2022-01-10.txt, tools/virtualenvs/azure_open_envs-ansible2.9-python3.6-2022-04-06.txt
Update azure open env virtualenv
azure open env virtualenv
```paste below
```
=> Update azure open env virtualenv

ansible/configs/open-environment-azure-subscription/default_vars.yml, ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
add better auth to azure function api
roles/open-env-azure-add-user-to-subscription
roles/open-env-azure-remove-user-from-subscription
```paste below
```
=> add better auth to azure function api

ansible/configs/ocp-clientvm/post_software.yml
=> Updating user.info in clientvm config

ansible/configs/ocp-clientvm/.yamllint, ansible/configs/ocp-clientvm/post_software.yml
=> adding line-length

ansible/configs/ocp-clientvm/post_software.yml
=> revert the changes

ansible/roles/open-env-azure-add-user-to-subscription/README.md, ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml, ansible/roles/open-env-azure-create-open-env/README.md, ansible/roles/open-env-azure-delete-open-env/README.md, ansible/roles/open-env-azure-install-aro/README.md, ansible/roles/open-env-azure-invite-user/README.md, ansible/roles/open-env-azure-invite-user/tasks/main.yml, ansible/roles/open-env-azure-remove-user-from-subscription/README.md, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
update email to requester_email for azure CIs
open-env-azure-add-user-to-subscription
open-env-azure-create-open-env
open-env-azure-delete-open-env
open-env-azure-install-aro
open-env-azure-invite-user
```paste below
```
=> update email to requester_email for azure CIs

ansible/roles/open-env-azure-invite-user/tasks/main.yml
add debugging to email check in open env aro
ROLE: open-env-azure-invite-user
```paste below
```
=> add debugging to email check

ansible/cloud_providers/ec2_infrastructure_deployment.yml, ansible/roles/locate_env_authorized_key/tasks/main.yaml
=> Fix ocp-workloads failing because of locate_env_authorized_key role

ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
update remove role assignment for azure subscription
```paste below
```
=> update remove role assignment for azure subscription

ansible/configs/open-environment-azure-subscription/post_software.yml
add aap email text to open-env-azure-subscription
open-env-azure-subscription
```paste below
```
=> add aap to open env azure subscription

ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/files/tomcat/manager.xml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/files/tomcat/tomcat.service, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/rhev-setup-im-user.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/rhev-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/rhev-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/rhev-setup-user.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/vm-common-install-and-configure.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/vm-oracledb-install-and-configure.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/vm-tomcat-install-and-configure.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/templates/tomcat/persistence.properties, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/templates/tomcat/tomcat-users.xml.j2
This workload now also configures a Tomcat VM connecting an application to the oracle database.
ocp4_workload_ama_rhev_vm
=> Added Tomcat configuration to AMA VM Workload

ansible/configs/kni-osp/files/cloud_providers/osp_cloud_template_master.j2
=> Testing fix to heat template

ansible/configs/kni-osp/files/cloud_providers/osp_cloud_template_master.j2
Reverts redhat-cop/agnosticd#4639
=> Revert "Troubleshooting heat templates"

ansible/roles/open-env-azure-invite-user/tasks/main.yml
=> one more try to fix the azure invite user role

ansible/configs/kni-osp/requirements.yml
=> Adding collection requirements.yml

ansible/configs/open-environment-azure-subscription/post_software.yml
fix typos in open-env-azure-subscription email
```paste below
```
=> fix typos in open-env-azure-subscription email

ansible/configs/open-environment-gcp/README.adoc, ansible/configs/open-environment-gcp/default_vars.yml, ansible/configs/open-environment-gcp/destroy_env.yml, ansible/configs/open-environment-gcp/infra.yml, ansible/configs/open-environment-gcp/post_infra.yml, ansible/configs/open-environment-gcp/post_software.yml, ansible/configs/open-environment-gcp/pre_infra.yml, ansible/configs/open-environment-gcp/pre_software.yml, ansible/configs/open-environment-gcp/requirements.yml, ansible/configs/open-environment-gcp/software.yml, ansible/roles/gcp-get-token/README.md, ansible/roles/gcp-get-token/tasks/main.yml, ansible/roles/open-env-gcp-add-user-to-project/README.md, ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml, ansible/roles/open-env-gcp-remove-project/README.md, ansible/roles/open-env-gcp-remove-project/tasks/main.yml
Initial commit of GCP OPEN Environment config and roles
config: open-environment-gcp
role: gcp-get-token
role: open-env-gcp-add-user-to-project
role: open-env-gcp-remove-project
```paste below
```
=> Add GCP OPEN Environment config and roles

tools/virtualenvs/gcp_open_envs-ansible2.9-python3.6-2022-04-11.txt
add psutil to the gcp virtenv
```paste below
```
=> add psutil to the requrements

ansible/configs/kni-osp/pre_infra.yml
=> Reverting ssh key generation role temporarily

ansible/configs/hands-on-with-openshift-virtualization/requirements.yml
Add Ansible Galaxy requirements for hands-on-with-openshift-virtualization config.
Config hands-on-with-openshift-virtualization
=> Add requirements.yaml for hands-on-with-openshift-virtualization

ansible/configs/hands-on-with-openshift-virtualization/files/cloud_providers/osp_cloud_template_master.j2
Reformat and fix issues with `osp_cloud_template_master.j2` in config `hands-on-with-openshift-virtualization`
Config hands-on-with-openshift-virtualization
=> Reformat osp_cloud_template_master.j2 for hands-on-with-openshift-virtualization

ansible/configs/kni-osp/files/profile.go
=> Changing rootdisk device to sdb from vdb

ansible/roles_ocp_workloads/ocp4_workload_opentlc_webconsole/defaults/main.yml
As requested by @jkupferer 
ocp4_workload_opentlc_webconsole
=> Remove public links

ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/per_user_workload.yaml
Fix erroneous loop in ocp4_workload_servicemesh_workshop role
=> Fix loop in service mesh workshop

ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/defaults/main.yml
Version bump for workshop image in the Service Mesh Workshop
=> Bump workshop dashboard image tag for service mesh workshop

ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/templates/datagrid-cache.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/templates/datagrid-cluster.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_lpe_datagrid/templates/datagrid-secret.yaml.j2
Creating a new workload to install Red Hat Data Grid operator and create a new empty cluster.
Using install operator role to install Red Hat Data Grid  operator and created a new Task do configure a new Red Hat Data Grid cluster
N/A
```paste below
ansible==2.9.27
argcomplete==1.12.3
awscli==1.22.60
Babel==2.9.1
bcrypt==3.2.0
Beaker==1.10.0
beautifulsoup4==4.9.3
blivet==3.4.3
blivet-gui==2.3.0
boto3==1.21.4
botocore==1.24.5
Brlapi==0.8.2
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.4
chrome-gnome-shell==0.0.0
click==8.0.1
colorama==0.4.3
configobj==5.0.6
cryptography==3.4.7
cupshelpers==1.0
dasbus==1.6
dbus-python==1.2.18
decorator==5.0.9
defusedxml==0.7.1
distro==1.6.0
docutils==0.15.2
fedora-third-party==0.8
fluidity-sm==0.2.0
fros==1.1
git-cola==3.11.0 …
```
=> Red Hat Data Grid Last product enviorment workload

ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/meta/README.adoc, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/argocd.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/gitea-secret.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/namespace-demo.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/namespace-pipeline.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/pipelinerun.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/postgresql/deployment.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/postgresql/pvc.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/postgresql/secret.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/postgresql/service.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/rolebinding-clusterview.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/rolebinding-retail-pipeline.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/service-account.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/rhev-remove-im-user.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/rhev-setup-im-user.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/vm-tomcat-install-and-configure.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/workload.yml
AMA GitOps Deployment Workload
ocp4_workload_ama_gitops
=> Add ama gitops workload, add workload removals, minor fixes

ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/templates/gitea-secret.yaml.j2
Bugfix release to address issues introduced when adding yamllint compliance...
ocp4_workload_ama_gitops
=> Fix ama gitops workload

ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/tasks/workload.yml
rhjcd-patch-set ignore errors for remove rhods resource limits
```paste below
```
=> set ignore errors for remove rhods resource limits

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/pre_workload.yml
cc: @d-jana 
fix login command
=> 🦊 debug login command 🦊

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/pre_workload.yml
cc @d-jana 
removing debug. this is working ok now.
=> 🦊 remove debug - working ok now 🦊

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/post_workload.yml
cc @d-jana 
add learner details to provisioning email
=> 🎷 add user email info 🎷

ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/templates/code-server-coder.json.j2, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/templates/code-server-config.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/templates/run_vscode_certbot.j2
Added workload to deploy and configure VSCode Server on the bastion.
=> Add workload to install and configure VSCode Server on Bastion

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/pre_workload.yml
- fix up annoying email typos
- add retry to oc login
cc: @d-jana
=> 🦌 fix annoying email typos 🦌

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/workload.yml
cc: @d-jana 
one small change. ipa changes now merged upstream
=> 🍄 use redhat-cop repo 🍄

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/pre_workload.yml
cc: @d-jana 
does this look better/sane ?
=> 🕶️ retries until 🕶️

ansible/configs/ansible-middleware-workshop/requirements.yml
Added amazon collection to requirements.yml
ansible-middleware-workshop config
```paste below
```
=> Added amazon ansible collection to requirements.yml

ansible/configs/ansible-middleware-workshop/requirements.yml
=> adding ansible.posix.authorized_key

ansible/roles_ocp_workloads/ocp4_workload_ama_rhev_vm/tasks/workload.yml
use host_virtualenv capability to set up the virtualenv on the bastion.
ocp4_workkload_ama_rhev_vm
=> Removed now obsolete code

ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/tasks/workload.yml
Need to specify variable scope if set from another workload.
ocp4_workload_ama_gitops
=> Fix variable scope

ansible/roles_ocp_workloads/ocp4_workload_ama_gitops/tasks/workload.yml
SUMMARY
Don't fail if no IP address available.
ISSUE TYPE
COMPONENT NAME
ocp4_workload_gitops
=> Make variable handling more robust

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/workload.yml
remove login, not needed
retry helm install if fails
cc: @d-jana
=> 🐿️ add retry's to helm install 🐿️

ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/templates/smcp-basic.yaml.j2
Creates a new role for Latest Product Environment (LPE) for Openshift Service Mesh (OSSM).
This solves https://issues.redhat.com/browse/PFECD-712.
LPE OpensShfif Service Mesh
=> Add role LPE Service Mesh

ansible/configs/ocp4-workshop/requirements.yml
=> adding roles

ansible/roles_ocp_workloads/ocp4_workload_tl500/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/workload.yml
cc: @d-jana 
- generate passwords
=> 🔒 gen passwords 🔒

ansible/roles_ocp_workloads/ocp4_workload_lpe_fuse/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_fuse/templates/camel-k-integration-platform.yml.j2
Added the runtime version for the IntegrationPlatform
=> Create a runtime version

ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_online/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_online/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_online/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_online/templates/role-binding.yml.j2
=> correct post and remove workload AMQ Online

ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_broker/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_broker/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_broker/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_broker/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_broker/templates/role-binding.yml.j2
=> correct post and remove workload AMQ Broker

ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_amq_streams/templates/role-binding.yml.j2
=> correct post and remove workload AMQ Streams

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/setup-gitops.yml
For some reason ~{{ ansible_user }} resolves as /root. Which doesn't work of course.
So replacing that with a new variable to set the home directory to use.
=> Fix ansible_user resolving as root

ansible/configs/open-environment-azure-subscription/default_vars.yml, ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml
add DNS zone generation to subscription based azure
```paste below
```
=> add DNS zone generation to subscription based azure

ansible/configs/open-environment-azure-subscription/post_software.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
add email to azure open env to explain  DNS domain
```paste below
```
=> update azure subscription email

ansible/configs/open-environment-azure-subscription/post_software.yml, ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
very rough draft of adding app and AP to azure sub based env.  also emergency fix for deletions.
open-env-azure-subscription
```paste below
```
=> add application and SP to subscription based env

ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_servicemesh/tasks/workload.yml
Fixes some issues with the recently created LPE Service Mesh role.
This role has not yet been onboarded in rhpds/opentlc, but these changes are required to do so.
ocp4_workload_lpe_servicemesh
=> Fix lpe servicemesh

ansible/configs/open-environment-gcp/default_vars.yml, ansible/configs/open-environment-gcp/post_software.yml, ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml, ansible/roles/open-env-gcp-remove-project/tasks/main.yml
add dns to open-env-gcp
open-env-gcp
```paste below
```
=> add dns to open-env-gcp

ansible/configs/open-environment-gcp/post_software.yml, ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml, ansible/roles/open-env-gcp-remove-project/tasks/main.yml
added service account and cleaned up final email
open-env-gcp
```paste below
```
=> added service account and cleaned up final email

ansible/configs/hands-on-with-openshift-virtualization/files/approve_csr.sh
OpenShift certificates are autorotate, as I have a script to approve CSRs, now will wait till is autorotated
=> Update approve_csr.sh to wait till certificate autorotate condition

ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/templates/code-server-config.yaml.j2
Bugfix to fix wrong indentation in the VS Code Server config file.
=> Fixed indentation error in VSCode config file

ansible/configs/sap-smart/default_vars.yml
=> Update RHEL version to 8.6 for sap-smart lab

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/workload.yml
RHEV -> RHV. Also used RHEV user instead of VM user in user output.
=> Change nomenclature, fix wrong variables for VM Info

ansible/roles_ocp_workloads/ocp4_workload_mta_tackle/tasks/workload.yml
Tackle CR reports ready even if it is not. Added check for the last deployment to be ready.
ocp4_workload_mta_tackle
=> Add checks to see that Tackle is _actually_ deployed

ansible/configs/rosa/requirements.yml
add requirements.yml for rosa that includes AWS collection
rosa
```paste below
```
=> add requirements.yml for rosa that includes AWS collection

ansible/configs/rosa/requirements.yml
add requirements.yml for rosa that includes AWS collection
rosa
```paste below
```
=> update collections for rosa

ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller/templates/subscription.j2
Update ansible controller operation channel to stable-2.2
Role: ocp4_workload_lpe_automation_controller
=> Update operator version

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-tomcat-vm.yml
A new (much faster) storage system has been created in RHV. Add support to specify that one to deploy VMs.
=> Add support to deploy from managed storage in RHV

ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller/templates/subscription.j2
Added application access information 
Role
=> Ansible controller lpe

ansible/roles_ocp_workloads/ocp4_workload_big_demo/files/kustomization.yaml, ansible/roles_ocp_workloads/ocp4_workload_big_demo/files/pr-manifest-task.yaml, ansible/roles_ocp_workloads/ocp4_workload_big_demo/files/update-manifest-task.yaml, ansible/roles_ocp_workloads/ocp4_workload_big_demo/tasks/workload.yml
Yay more fixes.
ocp4_workload_big_demo
=> Fix big demo

ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/create_user_workloads.yml
=> Updating tasks

ansible/roles_ocp_workloads/ocp4_workload_servicemesh_workshop/tasks/create_user_workloads.yml
Fix user list type problems in service mesh role
=> Fix user list type problems in service mesh role

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/vm-tomcat-install-and-configure.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/workload.yml
Revert use of package module to install things for vscode. Also fix one variable omission in ama demo.
=> Fix package errors

ansible/configs/sap-hana/default_vars_osp.yml
=> Use RHEL 8.4 in SAP E2E Automation lab

ansible/roles/ocp4_workload_stackrox_demo_apps/tasks/openshift_policy_fix.yml
Fixing stackrox demo: make sure there's a item.json.id
role: ansible/roles/ocp4_workload_stackrox_demo_apps/
```paste below
```
=> Fixing stackrox demo: make sure there's a item.json.id

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/setup-gitops.yml
Remove hardcoded repository names from the ama workload.
=> Remove hardcoded repo names

ansible/configs/sap-hana/default_vars.yml
rhjcd-patch-comment epel vars
default var for tower install in the role
=> comment epel vars

ansible/configs/sap-hana/software.yml
rhjcd-patch-comment epel block in software.yml
```paste below
```
=> comment epel block in software.yml

ansible/roles_ocp_workloads/ocp4_workload_acm_cloud_credentials/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_acm_cloud_credentials/templates/azure_secret.j2
New task added to set requester_email variable
role: ocp4_workload_acm_cloud_credentials
=> Update role 

ansible/configs/sap-hana/files/inventory.j2
=> Adding Towwr inventory template to sap-hana config

ansible/configs/sap-hana/default_vars.yml
rhjcd-patch-update tower installer url to 3.8
```paste below
```
=> update tower installer url to 3.8

ansible/configs/sap-hana/software.yml
=> Commenting out Ansible Tower deployment for sap-hana

ansible/configs/sap-hana/print_info.yml
=> Comment out Tower login info for sap-hana

ansible/configs/sap-hana/post_software.yml
=> Comment out Tower post-config for sap-hana

ansible/configs/sap-hana/print_info.yml
=> Uncomment Tower references in print_info.yml

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_app_services/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_app_services/tasks/setup-app-services-lab.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_app_services/templates/app-services/catalog/catalog-service/route.yaml.j2
Added route definition to catalog service.
roles_ocp_workloads/ocp4_workload_ama_demo_app_services
```paste below
```
=> Added route to catalog service

ansible/configs/sap-integration/requirements.yml
=> adding keys

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/workload.yml
That one is embarrassing.... replace "true" with "bool"
=> Fix true -> bool

ansible/roles_ocp_workloads/ocp4_workload_acm_cloud_credentials/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/tasks/gitea_setup_repo.yml, ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/templates/update_repo.sh.j2
Somehow this has been failing to replace variables recently. Trying to make more robust.
Also fix indentation errors in @miteshget 's workload.
ocp4_workload_acm_cloud_credentials
=> Fix app deploy final lab

ansible/configs/sap-smart/sat_workload.yml
=> comment out the repos

ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/templates/update_repo.sh.j2
Somehow git clone complains about an expired cert...
- Bugfix/Workaround Pull Request
=> Add insecure connection

ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller/tasks/workload.yml
added install_plan wait task in the role
Role ocp4_workload_lpe_automation_controller
=> Add wait task in aap_operator role

ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller/tasks/config.yml, ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller/tasks/workload.yml
Added wait tasks for cvs to be install/created
role: ocp4_workload_lpe_automation_controller
=> Aap operator

ansible/configs/sandbox/default_vars.yml, ansible/configs/sandbox/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/sandbox/post_software_ec2.yml
Add default vars for:
- sandbox_enable_ui
- sandbox_user_info_messages_enable
- sandbox_user_info_data_enable
sandbox config
=> Add controls for agnosticd_user_info in sandbox config

ansible/roles_ocp_workloads/ocp4_workload_acm_cloud_credentials/tasks/workload.yml
When condition added to run aws and azure credentials tasks
Role : lpe-automation-controller
=> when conditions added

ansible/roles_ocp_workloads/ocp4_workload_acm_cloud_credentials/tasks/workload.yml
Default value is set for boolean variable
role: ocp4_workload_acm_cloud_credentials
=> default boolean value set

ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/per_user_operator_workload.yml, ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/per_user_remove_workload.yml
=> update k8s facts to info

ansible/roles/ocp4-workload-ocs-poc/defaults/main.yml
rhjcd-patch-update channel to 4.10
```paste below
```
=> update channel to 4.10

ansible/configs/sap-smart/post_software.yml, ansible/configs/sap-smart/requirements.yml
=> updating infra-ansible version

ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller/tasks/workload.yml
Increased retries count because of load.
role: ocp4_workload_lpe_automation_controller
=> increased retries counts

ansible/configs/sap-hana/default_vars.yml, ansible/configs/sap-hana/requirements.yml, ansible/configs/sap-hana/software.yml
=> Update Ansible version sap-hana

ansible/configs/sap-hana/pre_software.yml
=> Deleted duplicated check for repo in sap-hana

ansible/roles_ocp_workloads/ocp4_workload_cyberark_dap/defaults/main.yml
Recommended fix for cyberark
cyberark_dap
```paste below
```
=> proposed changes to cyberark

ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/tests/test-local.yml
This is new role which installs awscli, rosa_cli and also sets .aws/credentials.
Role: ocp4_workload_rosa_cli
=> New role rosa_cli for epic_demo

ansible/roles_ocp_workloads/ocp4_workload_eksctl/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_eksctl/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_eksctl/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_eksctl/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_eksctl/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_eksctl/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_eksctl/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_eksctl/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_eksctl/tests/test-local.yml
This role install eksctl on node.
Role: ocp4_workload_eksctl
=> New role ocp4_workload_eksctl

ansible/configs/sap-hana/software.yml
=> Install ansible-core for sap-hana (RHEL 8.4)

ansible/configs/sap-hana/default_vars.yml
=> Update to ansible 2.9 for sap-hana

ansible/configs/sap-hana/software.yml
=> Delete installation of ansible-core for sap-hana

ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/tasks/workload.yml
enabled become=true
role: ocp4_workload_rosa_cli
=> enabled become

ansible/roles_ocp_workloads/ocp4_workload_big_demo/files/gitconfig, ansible/roles_ocp_workloads/ocp4_workload_big_demo/files/pr-manifest-task.yaml, ansible/roles_ocp_workloads/ocp4_workload_big_demo/files/update-manifest-task.yaml, ansible/roles_ocp_workloads/ocp4_workload_big_demo/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_big_demo/templates/cicd/app-ci-pipeline.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_big_demo/templates/cicd/task-gitea-pull-request.yaml.j2
Bugfix: used ansible.builtin.file instead of ansible.builtin.copy...
ocp4_workload_big_demo
=> Fix update of GitOps manifests in gitops repo

ansible/configs/sap-smart/post_software.yml
Disable become for local task.
=> Fix sap-smart config to disable become on local task

ansible/roles_ocp_workloads/ocp4_workload_mta_tackle/templates/seed-tackle.sh.j2
Update ocp4_workload_mta_tackle to update the assessment answer in MTA
```paste below
```
=> Update ocp4_workload_mta_tackle to update the assessment answer in MTA

ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/tasks/workload.yml
Saw retries go down to almost zero. Adding a few more for margin for error.
ocp4_workload_rhods_olm
=> Increase retries for more buffer

ansible/configs/sap-smart/default_vars.yml, ansible/configs/sap-smart/post_software.yml
=> updating manifest file

ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/cluster_kconf.yml, ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/workload.yml
Added tasks to store managed cluster context in bastion
Role: ocp4_workload_acm_aws_cluster
=> managed cluster context added

ansible/roles_ocp_workloads/ocp4_workload_mta_tackle/templates/seed-tackle.sh.j2
Fix ocp4_workload_mta_tackle to fix the answer
```paste below
```
=> Fix ocp4_workload_mta_tackle to fix the answer

ansible/configs/sap-smart/software.yml
=> moving pip module installation after ansible tower

ansible/configs/sap-smart/default_vars.yml
=> locking rhel version to 8.4

ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/templates/storagecluster.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/templates/storagesystem.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundations/templates/toolbox.yaml.j2
OpenShift Container Storage got renamed as OpenShift Data Foundations. Deployment also changed.
New workload to support the new ODF.
ocp4_workload_openshift_data_foundations
=> Add workload openshift_data_foundations

ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/cluster_kconf.yml, ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/workload.yml
Set default variable's value
ocp4_workload_acm_aws_cluster
=> defaulting variable

ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/cluster_kconf.yml, ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/workload.yml
Set up .bashrc for users
ocp4_workload_acs_aws_cluster
=> set up .bashrc 

ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/cluster_kconf.yml, ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/workload.yml
default ~/.kube/config added to bashrc
role: ocp4_workload_acm_aws_cluster
=> set up default kconfig

ansible/configs/sap-smart/default_vars.yml
=> updating rhel lock verison to 8

ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/cluster_kconf.yml, ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/workload.yml
Added task to copy kubeconfig of managed cluster
ocp4_workstation_acm_aws_cluster
=> copy kubeconfig task

ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/cluster_kconf.yml, ansible/roles_ocp_workloads/ocp4_workload_acm_aws_cluster/tasks/workload.yml
fixed userinfo 
ocp4_workstation_acm_aws_cluster
=> userinfo modified 

ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller/tasks/workload.yml
added time delay 
automation-controller-config
=> pause added

ansible/configs/sap-hana/default_vars.yml
=> adding repos

ansible/configs/sap-hana/post_software.yml
=> adding  role config-ansible-tower-subscription-manifest

ansible/roles_ocp_workloads/ocp4_workload_rhacs/defaults/main.yml
remove never-used variable
I think the pinned csv in the workload was causing the csv errors in deployment
```paste below
```
=> rhacs workload: remove pinned csv

ansible/configs/sap-hana/print_info.yml
=> fixing ssh key part

ansible/roles/install_operator/tasks/install.yml
=> debug starting csv

ansible/configs/sap-hana/default_vars.yml, ansible/configs/sap-hana/print_info.yml
=> ssh key fix from tower

ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack.Dockerfile, ansible/roles/ocp4-workload-ccnrd-cuttingedge/files/stack_imagestream.yaml, ansible/roles/ocp4-workload-ccnrd-cuttingedge/templates/devfile.json.j2
Fix ocp4-workload-ccnrd-cuttingedge to fix mandrel version
```paste below
```
=> Fix ocp4-workload-ccnrd-cuttingedge to fix mandrel version

ansible/configs/sap-hana/default_vars_osp.yml
=> Use RHEL 8.6 for HANA and S/4HANA hosts

ansible/roles_ocp_workloads/ocp4_workload_mta_tackle/tasks/install_operator_multi_user.yml
Timeout for Keycloak was not long enough.
ocp4_workload_mta_tackle
=> Increase timeout to wait for keycloak

ansible/configs/sap-hana/default_vars.yml
=> Change SAP HA template for sap-hana

ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller/templates/automationcontroller.j2
UBI init container image added in automation controller pod
Role: ocp4_workload_lpe_automation_controller
=> Init ubi added in Automation Controller

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/setup-gitops.yml
Travis checks made me break things...
ocp4_workload_ama_shared
=> Fix mismatched quote

ansible/configs/sap-hana/default_vars.yml
=> Clean up default vars for sap-hana

ansible/configs/sap-hana/default_vars.yml
=> Update default vars for sap-hana

ansible/roles-infra/create_ssh_provision_key/defaults/main.yaml
=> Remove possible unecessary .pem in pubkey path

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/setup-gitops.yml
Another formatting error because of Travis checks...
=> Fix another error caused by travis

ansible/roles_ocp_workloads/ocp4_workload_codeserver/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/tasks/install_multi_user.yml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/tasks/install_single_user.yml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/deployment.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/namespace.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/pvc.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/route.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/service.yaml.j2
New workload to deploy code server to OpenShift. Single or Multi User.
ocp4_workload_codeserver
=> New codeserver workload

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta_tackle/tasks/workload.yml
Some workloads needed to add agnosticd_user_info data statements.
=> added agnosticd user data

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/workload.yml
forgot the user / data previxes
ocp4_workoad_ama_demo_shared
=> Fix user data

ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/workload.yml
Authentication did not add the console URL to the User Info. Fixed.
Also updated k8s -> kubernetes.core.k8s and replace k8s_facts with k8s_info.
=> Update authentication with console

ansible/roles/ocp4-workload-ocs-poc/tasks/workload.yml
=> updating apiextensions in ocp4-workload-ocs-poc

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/setup-gitops.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
Add Maven development enviornment to AMA Demo Bastion
Increase Gitea Operator check timeouts.
=> Add maven to ama demo

ansible/roles/ocp4-workload-ocs-poc/defaults/main.yml
=> reverting the ocs_channel version

ansible/configs/hybrid-cloud-binder/README.adoc, ansible/configs/hybrid-cloud-binder/default_vars.yml, ansible/configs/hybrid-cloud-binder/default_vars_ec2.yml, ansible/configs/hybrid-cloud-binder/destroy_env.yml, ansible/configs/hybrid-cloud-binder/files/cloud_providers/azure_cloud_template.j2, ansible/configs/hybrid-cloud-binder/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/hybrid-cloud-binder/files/cloud_providers/ec2_cloud_template_json.j2, ansible/configs/hybrid-cloud-binder/files/cloud_providers/terraform_ec2_cloud_template.tf.j2, ansible/configs/hybrid-cloud-binder/files/cloud_providers/terraform_ec2_cloud_template.tfvars.j2, ansible/configs/hybrid-cloud-binder/files/repos_template.j2, ansible/configs/hybrid-cloud-binder/infra.yml, ansible/configs/hybrid-cloud-binder/post_infra.yml, ansible/configs/hybrid-cloud-binder/post_software.yml, ansible/configs/hybrid-cloud-binder/pre_infra.yml, ansible/configs/hybrid-cloud-binder/pre_software.yml, ansible/configs/hybrid-cloud-binder/requirements.yml, ansible/configs/hybrid-cloud-binder/sample_vars.yml, ansible/configs/hybrid-cloud-binder/sample_vars_ec2.yml, ansible/configs/hybrid-cloud-binder/sample_vars_equinix_metal.yml, ansible/configs/hybrid-cloud-binder/sample_vars_osp.yml, ansible/configs/hybrid-cloud-binder/software.yml, ansible/configs/hybrid-cloud-binder/status.yml, ansible/configs/hybrid-cloud-binder/update.yml
new config destined to drive the hybrid-cloud demo
```paste below
```
=> create new config - empty for now

ansible/roles/ocp4-workload-ocs-poc/tasks/workload.yml
Reverts redhat-cop/agnosticd#5010
=> Revert "updating apiextensions in ocp4-workload-ocs-poc"

ansible/roles/ocp4-workload-ocs-poc/defaults/main.yml
=> adding v4.10_2022_07_04 in ocp4_workload_ocs_poc

ansible/configs/hybrid-cloud/.pre_infra.yml@neomake_57995_4.yml
=> hybrid-cloud omit tmp_kubeconfig

ansible/configs/hybrid-cloud/.pre_infra.yml@neomake_57995_4.yml, ansible/configs/hybrid-cloud/pre_infra.yml
omit kubeconfig from env for call to azure
config/hybrid-cloud
```paste below
```
=> Judd hybrid cloud omit kubeconfig

ansible/configs/hybrid-cloud/requirements.yml
add azure collection to requirements.txt
config/hybrid-cloud
```paste below
```
=> add azure collections to requirements.txt

ansible/configs/hybrid-cloud/default_vars.yml
add default_vars.yml from config/open-azure..*/
configs/hybrid-cloud
```paste below
```
=> add default_vars from config/open-azure

ansible/roles/install_operator/defaults/main.yml
Reverts redhat-cop/agnosticd#5029
=> Revert "Update main.yml"

ansible/configs/hybrid-cloud/default_vars.yml, ansible/configs/hybrid-cloud/pre_infra.yml
=> hybrid cloud debug env send to azure role

ansible/configs/hybrid-cloud/default_vars.yml, ansible/configs/hybrid-cloud/pre_infra.yml
no such thing as `ansible_env`
=> hybrid cloud debug env

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/deploy_project.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_amqstreams_operator.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_grafana.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_prometheus.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/workload.yml
Updating module name `k8s` & `k8s_info` with full module names.
Also fixing `from_yaml_all` to `from_yaml_all | list`
=> Updating with module name

ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/tasks/cluster.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/tasks/cluster_kconf.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/templates/clusterdeployment.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/templates/install_config.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/templates/klusterletaddonconfig.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/templates/machinepool.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/templates/managedcluster.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/templates/namespace.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/templates/secret_auth_token.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/templates/secret_aws_creds.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/templates/secret_install_config.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/templates/secret_ssh_privatekey.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_aws_cluster/tests/test-local.yml
Renamed ocp4_workload_acm_aws_cluster -> ocp4_workload_rhacm_aws_cluster
Role: ocp4_workload_rhacm_aws_cluster
=> ocp4_workload role renamed to ocp4_workload_rhacm_aws_cluster

ansible/configs/hybrid-cloud/pre_infra.yml
Userinfo added for azure
Config: hybrid-cloud
=> Userinfo added

ansible/roles_ocp_workloads/ocp4_workload_rhacm_cloud_credentials/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_cloud_credentials/tasks/workload.yml
azure credentials fixed
role: ocp4_workload_rhacm_cloud_credentials
=> azure credentials

ansible/roles_ocp_workloads/ocp4_workload_managed_cluster_workload/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_managed_cluster_workload/tasks/workload.yml
=> Change order as per Ritesh's request

ansible/roles_ocp_workloads/ocp4_workload_rhacm_clusters/tasks/cluster_azure.yaml
Indentation Fixed for set_fact
=> Indentation Fixed for set_fact

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/setup-gitops.yml
AMA Shared Workload needed more user information.
=> Add more user info

ansible/configs/ocp4-cluster/post_software.yml
Clean-up `agnosticd_user_info` for ocp4-cluster config and report bastion ssh details with `agnosticd_user_info` data.
=> Report ssh access info as user data

ansible/configs/hybrid-cloud/post_software.yml
improve user_data output for bastion host info
```paste below
```
=> Report ssh access info as user data in config/hybrid-cloud

ansible/roles_ocp_workloads/ocp4_workload_rhacm_clusters/tasks/cluster_kconf.yml
ocp4-workload-rhacm-clusters yaml lint
workload ocp4-workload-rhacm-clusters
```paste below
```
=> fix line too long

ansible/roles_ocp_workloads/ocp4_workload_rhacm_clusters/tasks/cluster_aws.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_clusters/tasks/cluster_azure.yaml
=> fix typo, prefer >-

ansible/roles_ocp_workloads/ocp4_workload_rhel_worker/tasks/remove_workload.yml
Hey @bbethell-1  as long as you're cleaning up - this removes a Travis warning.
```paste below
```
=> fix truthy complaint from Travis

ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/workload.yml
for Hybrid Cloud Demo, need some user info that never made it into data.
```paste below
```
=> add user data where missing

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhods_olm/tasks/workload.yml
=> Judd hybrid cloud even more user info

ansible/configs/ansible-advanced-v2/post_software.yml
Fixed truthy error
config: ansible-advanced-aap2
=> Fixed truthy error

ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/workload.yml
There were trailing quotes in the bastion URL
```paste below
```
=> remove extra trailing quotes from vscode workload

ansible/configs/ansible-automation-platform/software.yml, ansible/roles_ocp_workloads/ocp4-workload-cnad-app-modernization/defaults/main.yml, ansible/roles_ocp_workloads/ocp4-workload-fsi-risk-analytics/defaults/main.yml, ansible/roles_ocp_workloads/ocp4-workload-fsi-risk-analytics/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cyberark_dap/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_plus/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_windows_node/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_xray_pipeline_lab/tasks/per_user_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_xray_pipeline_lab/tasks/source-bucket.yaml
=> Fix static tests

ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_setup/templates/object-detection-app-git-buildconfig.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_setup/templates/object-detection-rest-buildconfig.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_setup/templates/object-detection-rest-pipeline-run.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_setup/templates/object-detection-rest-pipeline.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_setup/templates/trigger-template.yaml.j2
=> Updated the SSL to false for the pipeline

ansible/roles/ocp4-workload-3scale-servicemesh-demo/defaults/main.yaml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/readme.adoc, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/pre_workload.yml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/provision_api.yaml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/provision_bookinfo.yaml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/provision_ocs.yaml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/provision_sso.yaml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/provision_threescale.yaml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/provision_webapp.yaml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/remove_workload.yml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/workload.yml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/ocs-group.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/ocs-noobaa.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/ocs-operatorgroup.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/ocs-subscription.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/servicemesh-controlplane.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/sso-subscription.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/threescale-apimanager.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/threescale-objectbucketclaim.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/threescale-s3-auth-secret.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/threescale-subscription.yaml.j2
3scale Service Mesh Web Assemble Module
```paste below
```
=> Update Istio Adapter to WASM

ansible/configs/tech-desktop-901/.yamllint, ansible/configs/tech-desktop-901/README.adoc, ansible/configs/tech-desktop-901/default_vars.yml, ansible/configs/tech-desktop-901/default_vars_azure.yml, ansible/configs/tech-desktop-901/default_vars_ec2.yml, ansible/configs/tech-desktop-901/default_vars_osp.yml, ansible/configs/tech-desktop-901/destroy_env.yml, ansible/configs/tech-desktop-901/files/cloud_providers/azure_cloud_template.j2, ansible/configs/tech-desktop-901/files/hosts_template.j2, ansible/configs/tech-desktop-901/files/repos_template.j2, ansible/configs/tech-desktop-901/post_infra.yml, ansible/configs/tech-desktop-901/post_software.yml, ansible/configs/tech-desktop-901/pre_infra.yml, ansible/configs/tech-desktop-901/pre_software.yml, ansible/configs/tech-desktop-901/software.yml
This pull request is for RHEL9 Readiness lab with course code tech-desktop-901.
```paste below
```
=> tech-desktop-901 added

ansible/configs/satellite-hackfest/default_vars_osp.yml, ansible/configs/satellite-hackfest/pre_software.yml
Updating the Satellite Hackfest config to reflect 6.11 release, also updated code for new repository names.
```paste below
```
=> Satellite Hackfest CI, update system name and repository info

ansible/configs/tech-imagebuilder-901/.yamllint, ansible/configs/tech-imagebuilder-901/README.adoc, ansible/configs/tech-imagebuilder-901/default_vars.yml, ansible/configs/tech-imagebuilder-901/default_vars_azure.yml, ansible/configs/tech-imagebuilder-901/default_vars_ec2.yml, ansible/configs/tech-imagebuilder-901/default_vars_osp.yml, ansible/configs/tech-imagebuilder-901/destroy_env.yml, ansible/configs/tech-imagebuilder-901/files/cloud_providers/azure_cloud_template.j2, ansible/configs/tech-imagebuilder-901/files/hosts_template.j2, ansible/configs/tech-imagebuilder-901/files/repos_template.j2, ansible/configs/tech-imagebuilder-901/post_infra.yml, ansible/configs/tech-imagebuilder-901/post_software.yml, ansible/configs/tech-imagebuilder-901/pre_infra.yml, ansible/configs/tech-imagebuilder-901/pre_software.yml, ansible/configs/tech-imagebuilder-901/sample_variables/README.adoc, ansible/configs/tech-imagebuilder-901/sample_variables/rhel8_server_on_ec2.yml, ansible/configs/tech-imagebuilder-901/sample_variables/rhel8_server_on_osp.yml, ansible/configs/tech-imagebuilder-901/sample_variables/secrets_example_all.yml, ansible/configs/tech-imagebuilder-901/sample_variables/secrets_example_ec2.yml, ansible/configs/tech-imagebuilder-901/sample_variables/secrets_example_osp.yml, ansible/configs/tech-imagebuilder-901/software.yml
This is RHEL 9 Image Builder Lab part of RHEL 9 readiness training and course code is tech-imagebuilder-901
```paste below
```
=> WIP - New Config for RHEL 9 Image Builder tech-imagebuilder-901

ansible/cloud_providers/osp_infrastructure_deployment.yml, ansible/configs/multi-cloud-capsule/infra_configs/infra-osp-create-inventory.yml, ansible/configs/multi-cloud-capsule/infra_configs/osp_infrastructure_deployment.yml, ansible/configs/osp-migration/destroy_env.yml, ansible/configs/osp-migration/infra.yml, ansible/configs/osp-satellite-vm/destroy_env.yml, ansible/configs/osp-satellite-vm/infra.yml, ansible/configs/rhel8lab/infra-osp-create-inventory.yml, ansible/lifecycle_osp.yml, ansible/roles-infra/infra-ec2-create-inventory/tasks/main.yml, ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml, ansible/roles-infra/infra-osp-dry-run/tasks/main.yml
** THIS CHANGE CAN BREAK STUFF **
Please do not automatically merge, this is for review.
```paste below
```
=> changing `os_server_info` to `openstack.cloud.server_info` and updating var names

ansible/configs/sandbox/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/sandbox/post_infra_ec2.yml, ansible/configs/sandbox/post_software_ec2.yml, ansible/roles-infra/infra-aws-open-environment/tasks/print_user_info.yaml
removed student user in lieu of admin user
sandbox
```paste below
```
=> removed student user in lieu of admin user

ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/templates/configmap-rook-ceph-operator-config.yaml.j2
More locations are necessary for tolerations to be added for things to work. ODF is something....
ocp4_workload_openshift_data_foundations
=> More changes for toleration support on ODF

ansible/roles/user-create-ansible-service-account/.yamllint, ansible/roles/user-create-ansible-service-account/README.adoc, ansible/roles/user-create-ansible-service-account/defaults/main.yml, ansible/roles/user-create-ansible-service-account/files/.vimrc, ansible/roles/user-create-ansible-service-account/meta/main.yml, ansible/roles/user-create-ansible-service-account/tasks/copy-contents.yml, ansible/roles/user-create-ansible-service-account/tasks/copy-files.yml, ansible/roles/user-create-ansible-service-account/tasks/copy-templates.yml, ansible/roles/user-create-ansible-service-account/tasks/create-directory.yml, ansible/roles/user-create-ansible-service-account/tasks/create-user.yml, ansible/roles/user-create-ansible-service-account/tasks/main.yml, ansible/roles/user-create-ansible-service-account/tasks/ssh-config.yml, ansible/roles/user-create-ansible-service-account/templates/ssh_config.j2
New role: user-create-ansible-service-account
Name says it all, creates a specific type of service account tuned for ansible (e.g. allows multiple pythons but sets desired defaults etc, customizes ssh config etc)
ansible/roles/user-create-ansible-service-account
=> Created an Ansible Service Account creation role

ansible/configs/sandbox/infra.yml, ansible/configs/sandbox/infra_ec2.yml
update sandbox infra to only use open env role
sandbox
```paste below
```
=> update sandbox infra to only use open env role

ansible/configs/tech-imagebuilder-901/README.adoc, ansible/configs/tech-imagebuilder-901/default_vars.yml, ansible/configs/tech-imagebuilder-901/post_software.yml, ansible/configs/tech-imagebuilder-901/software.yml
=> WIP Tech imagebuilder 901

ansible/roles-infra/infra-aws-open-environment/tasks/print_user_info.yaml
update user_info to look better in adoc formatting
sandbox
```paste below
```
=> update user info text for adoc

ansible/configs/sandbox/requirements.yml
add requirements.yml to sandbox
sandbox
```paste below
```
=> add requirements.yml to sandbox

ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_setup/templates/object-detection-rest-pipeline.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_setup/templates/task-sanity-check-model.yaml.j2
=> Updated ssl verification to false for the sanity check task

ansible/configs/hybrid-cloud-binder/README.adoc, ansible/configs/hybrid-cloud-binder/default_vars.yml, ansible/configs/hybrid-cloud-binder/destroy_env.yml, ansible/configs/hybrid-cloud-binder/infra.yml, ansible/configs/hybrid-cloud-binder/post_infra.yml, ansible/configs/hybrid-cloud-binder/post_software.yml, ansible/configs/hybrid-cloud-binder/pre_infra.yml, ansible/configs/hybrid-cloud-binder/pre_software.yml, ansible/configs/hybrid-cloud-binder/requirements.yml, ansible/configs/hybrid-cloud-binder/sample_vars.yml, ansible/configs/hybrid-cloud-binder/sample_vars_ec2.yml, ansible/configs/hybrid-cloud-binder/sample_vars_equinix_metal.yml, ansible/configs/hybrid-cloud-binder/sample_vars_osp.yml, ansible/configs/hybrid-cloud-binder/software.yml, ansible/configs/hybrid-cloud-binder/status.yml, ansible/configs/hybrid-cloud-binder/templates/auto-import-secret.yaml.j2, ansible/configs/hybrid-cloud-binder/templates/klusterlet-addon-config.yaml.j2, ansible/configs/hybrid-cloud-binder/templates/managed-cluster.yaml.j2, ansible/configs/hybrid-cloud-binder/update.yml
- import clusters into RHACM and validate; extensive readme
- remove the fail trigger task
=> judd hybrid cloud binder import and validate clusters

ansible/configs/tech-cockpit-901/.yamllint, ansible/configs/tech-cockpit-901/README.adoc, ansible/configs/tech-cockpit-901/default_vars.yml, ansible/configs/tech-cockpit-901/default_vars_osp.yml, ansible/configs/tech-cockpit-901/destroy_env.yml, ansible/configs/tech-cockpit-901/files/hosts_template.j2, ansible/configs/tech-cockpit-901/files/ssh_config.j2, ansible/configs/tech-cockpit-901/post_infra.yml, ansible/configs/tech-cockpit-901/post_software.yml, ansible/configs/tech-cockpit-901/pre_infra.yml, ansible/configs/tech-cockpit-901/pre_software.yml, ansible/configs/tech-cockpit-901/requirements.yml, ansible/configs/tech-cockpit-901/sample_vars/sample_vars_osp.yml, ansible/configs/tech-cockpit-901/setup_cloud_user.yml, ansible/configs/tech-cockpit-901/software.yml
RHEL 9 Readiness: Live VM migration using RHEL 9 Web Console (Cockpit)
```
This config has been tested for only OpenStack provider as RHEL9 image is unavailable for AWS atm.
```
=> Add config tech-cockpit-901

ansible/configs/open-environment-gcp/post_software.yml, ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml
move GCP projects into folders per IT req
open-environment-gcp
```paste below
```
=> move GCP projects into folders per IT req

ansible/configs/multi-network-app-pntae/files/cloud_providers/osp_cloud_template_master.j2, ansible/configs/tech-networking-901/files/cloud_providers/osp_cloud_template_master.j2
tech-networking-901:
modified cloud_providers jinja template osp_cloud_template_master.j2
```paste below
```
=> multi-network-app-pntae:

ansible/lifecycle_osp.yml
=> Rewriting lifecycle_osp to utilize ansible modules instead of cli client

ansible/configs/tech-imagebuilder-901/default_vars.yml
Fixed node_instance_type variable 
Config: tech-imagebuilder-901
=> fixed osp instance type  variable

ansible/configs/ocp4-cluster/destroy_env_azure.yml
ocp4-cluster
```paste below
```
=> fix ocp on azure destroy

ansible/configs/tech-desktop-901/post_software.yml
Enable console access for tech-desktop-901
```paste below
```
=> tech-desktop-901 enable console access

ansible/configs/tech-imagebuilder-901/software.yml
GUI package installation removed
Remove the GUI package installation
```paste below
```
=> Updating config

ansible/roles/ocp4_approve_certificate_signing_requests/tasks/approve-certificate-signing-requests.yml
Report failure if certificates API is not found.
Role ocp4_approve_certificate_signing_requests
=> Change certificates api to v1

ansible/roles_ocp_workloads/ocp4_workload_bookbag/README.md, ansible/roles_ocp_workloads/ocp4_workload_bookbag/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_bookbag/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_bookbag/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_bookbag/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_bookbag/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_bookbag/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_bookbag/templates/bookbag-base-bc.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_bookbag/templates/bookbag-base-is.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_bookbag/templates/bookbag-rolebinding.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_bookbag/templates/bookbag-template.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_bookbag/templates/firefox-argocd-fix.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_bookbag/templates/firefox-bookbag-crb.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_bookbag/templates/firefox-bookbag-deployment.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_bookbag/templates/firefox-bookbag-route.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_bookbag/templates/firefox-bookbag-svc.yml.j2
=> Bookbag generic

ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_cli/tasks/workload.yml
- set profile in rosa commands and delete useless stuff
- manage profiles and regions more carefully
=> judd workload rosa cli better profiles

ansible/configs/hybrid-cloud-binder/default_vars.yml, ansible/configs/hybrid-cloud-binder/post_software.yml, ansible/roles_ocp_workloads/ocp4_workload_bookbag_ohc_demo/tasks/workload.yml
* add empty default vars to ohc bookbag role
* add feature switches for
** bookbag enable
** import clusters
=> introduce bookbag to hybrid_cloud_binder

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/files/redis/redis-template.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/dev-module-guides-install.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/dev-username-distribution-install.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/workload.yml
Update ocp4_workload_ama_demo_shared to add user distribution and guides
```paste below
```
=> Update ocp4_workload_ama_demo_shared to add user distribution and guides

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/dev-username-distribution-install.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/workload.yml
Fix the file name and set num_users var
```paste below
```
=> Fix ocp4_workload_ama_demo_shared for the file name and set num_users var

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/dev-username-distribution-install.yml
Fix ocp4_workload_ama_demo_shared to update vscode url
```paste below
```
=> Fix ocp4_workload_ama_demo_shared to update vscode url

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/dev-username-distribution-install.yml
Update ocp4_workload_ama_demo_shared to update module titles
```paste below
```
=> Update ocp4_workload_ama_demo_shared to update module titles

ansible/roles/ocp4-workload-oadp/tasks/workload.yml
=> adding retries 30 in Approved install plan

ansible/roles/ocp4-workload-oadp/tasks/workload.yml
Reverts redhat-cop/agnosticd#5280
=> Revert "adding retries 30 in Approved install plan"

ansible/lifecycle_osp.yml
=> Fixing OSP environment vars

ansible/roles-infra/infra-azure-create-inventory/tasks/main.yml
=> Use new var name for create-inventory azure role

ansible/lifecycle_osp.yml
Fix indentation in debug statements.
=> Fix indentation in ansible/lifecycle_osp.yml

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/templates/apps/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/templates/cicd/applicationset.yaml.j2
=> Fix repo names

ansible/configs/aap2-ansible-workshops/vars/automate_smart_mgmt_vars.yml
Add CentOS 7.8 AMI stanza specifying AMI from RHPDS AWS account
- Update config Pull Request
Ansible workshop deploy config
=> Add CentOS 7.8 AMI stanza

ansible/configs/aap2-on-azure/README.adoc, ansible/configs/aap2-on-azure/default_vars.yml, ansible/configs/aap2-on-azure/destroy_env.yml, ansible/configs/aap2-on-azure/infra.yml, ansible/configs/aap2-on-azure/post_infra.yml, ansible/configs/aap2-on-azure/post_software.yml, ansible/configs/aap2-on-azure/pre_infra.yml, ansible/configs/aap2-on-azure/pre_software.yml, ansible/configs/aap2-on-azure/requirements.yml, ansible/configs/aap2-on-azure/software.yml
Hands on lab for Ansible Automation Platfomr 2 on Azure marketplace
=> New config aap2-on-azure

ansible/roles-infra/infra-azure-create-inventory/tasks/main.yml, ansible/roles/agnosticd_save_output_dir/tasks/create-output-dir-archive.yml
Reverts redhat-cop/agnosticd#5311
Breaks my current work.
=> Revert "azure: do not define ssh key file per host"

ansible/configs/ocp4-cluster/lifecycle_hook_post_start.yml
Remove block
https://github.com/redhat-cop/agnosticd/blob/development/ansible/configs/ocp4-cluster/lifecycle_hook_post_start.yml#L25-L28
introduced by 4e1482ee829ee93abf2ebeed07d003cb983792a8
=> fix lifecycle in ocp4-cluster

ansible/lifecycle_azure.yml
Make status work for azure cloud provider
azure cloud provider in core
```paste below
```
=> fix status for azure cloud provider

ansible/configs/containerize-app-demo/requirements.yml
Update amazon.aws collection version
```paste below
```
=> Containerize your app, updating aws collection version

ansible/configs/aap2-on-azure/post_software.yml
Added Bookbag in post software
=> Update post_software.yml Book bag

ansible/configs/containerize-app-demo/requirements.yml
=> testing if aws collection is needed

CODEOWNERS
- Add Pat for Azure
- remove unknown owner @redhat-gpst/agnosticd-maintainers (error
reported by github)
CODEOWNERS update
=> Add @rut31337 as a codeowner for azure files

ansible/configs/containerize-app-demo/requirements.yml, ansible/configs/convert-to-rhel/requirements.yml
Update requirements.yml for both sales play demos
```paste below
```
=> Sales Play Demos Update requirements

ansible/roles/user-create-ansible-service-account/tasks/main.yml
Updating this role to use package instead of dnf.
user-create-ansible-service-account
```paste below
```
=> update dnf to package

ansible/configs/convert-to-rhel/default_vars.yml
Update the Convert to RHEL CI to install python2
```paste below
```
=> Convert to RHEL python version update

ansible/configs/containerize-app-demo/requirements.yml
Updating collections list 
```paste below
```
=> Containerize app demo update requirements

ansible/configs/containerize-app-demo/default_vars.yml
Adding variable
```paste below
```
=> Containerize App Demo add var to disable python install

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/deploy_projects.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/setup_bastion.yml
Bugfix. Renamed some included files, didn't change the include statement.
ocp4_workload_quarkus_super_heroes_demo
=> Fix include tasks

ansible/configs/ansible-automation-platform/post_software.yml
=> Add Lab URL to Provision Message

ansible/configs/ansible-automation-platform/post_software.yml
=> Remove Quotes

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/setup_bastion.yml
Ansible got confused by extra readability spaces.
ocp4_workload_quarkus_super_heroes_demo
=> Fix ansible conversion error

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/dev-module-guides-install.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/dev-username-distribution-install.yml
Lots of hardcoded repository names and application names.
Replaced all occurrences with variables instead. Variables have the default of the previously hardcoded values.
=> Add more parameters for Guides and User Picker applications.

ansible/configs/ocp-workshop/env_vars.yml
=> Add Key Var

ansible/configs/persistent-satellite-demo/destroy_env.yml, ansible/configs/persistent-satellite-demo/pre_infra.yml, ansible/configs/persistent-satellite-demo/satellite_workload.yml
included satellite workload
config: persistent-satellite-demo
=> included satellite workload

ansible/configs/persistent-satellite-demo/destroy_env.yml, ansible/configs/persistent-satellite-demo/pre_infra.yml, ansible/configs/persistent-satellite-demo/satellite_workload.yml
fixed title 
config: persistent-satellite-demo
=> Satellite tech sales

ansible/roles/rhel-graphical/tasks/main.yml
Fix a configuration issue with latest versions of tigervnc packages.
The user allowed to run the server should be configured on a different file now.
```paste below
```
=> Fix vnc server setup in rhel-security config.

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/setup_bastion.yml
Attempt to fix podman for quarkus super heroes demo.
ocp4_workload_quarkus_super_heroes_demo
=> Update bastion config for podman

ansible/configs/ocp4-cluster/requirements.yml
add google cloud collection to ocp4-cluster
ocp4-cluster
```paste below
```
=> add google cloud collection to ocp4-cluster

ansible/configs/hybrid-cloud-binder/post_software.yml
- put lots of retries in hybrid-cloud-binder
- copy UPI install files from aws_dev_a to hub
=> judd hybrid cloud copy UPI files

ansible/configs/ocp4-cluster/post_software.yml
fix issue with setting bastion public hostname
ocp4-cluster 
```paste below
```
=> fix issue with setting bastion public hostname

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/deploy_cicd.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/setup_bastion.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/templates/argocd/argocd-application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/templates/argocd/argocd-repo-secret.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/templates/tekton/pipeline.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/templates/tekton/secret-gitea-token.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/templates/tekton/task-update-kustomize-image.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/templates/tekton/task-update-kustomize-swagger.yaml.j2
Fix swagger url issue in heroes app.
Fix gitconfig issue for vscode on bastion.
Externalize gitea vars for better maintainability.
=> Acc new app swagger and gitconfig fix

ansible/lookup_plugins/equinix_api.py
Example:
```
- name: Get current capacity
set_fact:
equinix_metal_capacity: "{{ lookup('equinix_api', '/capacity') }}"
```
=> Add equinix API lookup

ansible/cloud_providers/azure_infrastructure_deployment.yml
add tag to resource groups created in azure infra
```paste below
```
=> add tag to resource groups created in infra

ansible/roles/bastion-lite/tasks/create_bastion_ssh_key_and_access.yml
=> add missing file, follow-up #5384

ansible/roles/bastion-lite/tasks/main.yml
Fix include to look for task in current directory
bastion-lite
```paste below
```
=> Fix include to look for task in current directory

ansible/configs/ocp4-cluster/destroy_env_gcp.yml
fix problem with destroy for gcp
ocp4-cluster
```paste below
```
=> fix problem with destroy for gcp

ansible/cloud_providers/gcp_destroy_env.yml, ansible/configs/ocp4-cluster/post_software.yml, ansible/roles-infra/infra-gcp-template-destroy/tasks/main.yml
fix destroy for gcp
ocp4-cluster
```paste below
```
=> fix destroy for gcp

ansible/configs/hybrid-cloud-binder/default_vars.yml, ansible/configs/hybrid-cloud-binder/post_software.yml, ansible/configs/hybrid-cloud-binder/templates/secured_cluster.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacs_secured_cluster/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_secured_cluster/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_secured_cluster/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_rhacs_secured_cluster/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_secured_cluster/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_secured_cluster/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_secured_cluster/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_secured_cluster/tasks/workload.yml
- add trivial role for rhacs operator install
- spell hybrid correctly, handsome
- refactor to always login to clusters; deploy RHACS SecureCluster
- bump RHACS secured_cluster version to match OHC Hub Central
=> judd hybrid cloud rhacs secured cluster

ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/workload.yml
Wait time increased to find aap route
Role: ocp4_workload_gitops_aap
=> Wait time increased against bugfix

ansible/configs/sap-integration/default_vars.yml, ansible/configs/sap-integration/default_vars_ec2.yml, ansible/configs/sap-integration/destroy_env_osp.yml, ansible/configs/sap-smart/files/cloud_providers/osp_cloud_template_master.j2
=> Update for SSH changes

ansible/configs/ocp4-cluster/destroy_env_azure.yml
add start to azure destroy
ocp4-cluster
```paste below
```
=> add start to azure destroy

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/files/setup_podman_user_service, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/setup_bastion.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_vscode_bastion/templates/code-server.service.j2
Use lab-user instead of ansible-user for the demo environment.
Fix podman once and for all (??)
ocp4_workload_quarkus_super_heroes_demo
=> Switch to lab-user, finally enable podman

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/setup_bastion.yml
Fix git config after setup bastion change to lab-user
=> Fix git config acc app dev

ansible/configs/persistent-satellite-with-nodes/README.adoc, ansible/configs/persistent-satellite-with-nodes/default_vars.yml, ansible/configs/persistent-satellite-with-nodes/default_vars_ec2.yml, ansible/configs/persistent-satellite-with-nodes/destroy_env.yml, ansible/configs/persistent-satellite-with-nodes/post_infra.yml, ansible/configs/persistent-satellite-with-nodes/post_software.yml, ansible/configs/persistent-satellite-with-nodes/pre_infra.yml, ansible/configs/persistent-satellite-with-nodes/pre_software.yml, ansible/configs/persistent-satellite-with-nodes/requirements.yml, ansible/configs/persistent-satellite-with-nodes/sample_vars/ec2_vars.yml, ansible/configs/persistent-satellite-with-nodes/satellite_workload.yml, ansible/configs/persistent-satellite-with-nodes/software.yml
New config `persistent-satellite-with-nodes` which creates satellite user and two nodes.
Config: persistent-satellite-with-nodes
=> New config

.github/workflows/labeler.yml
=> Fix permission for labeler Github Action

ansible/roles-infra/infra-azure-create-inventory/tasks/main.yml
try to fix azure deploy by using env based auth
azure cloudprovider
```paste below
```
=> switch to env based auth

ansible/configs/hybrid-cloud-binder/post_software.yml
- clean out unnecessary searches for route to central
- remove transport from URL, because duplicated
=> judd hybrid cloud fix route

ansible/configs/hybrid-cloud-binder/post_software.yml, ansible/configs/hybrid-cloud-binder/templates/secured_cluster.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacs_demo_pipeline/tasks/pre_workload.yml
- remove transport from URL, because duplicated
- tighten and correct central endpoints
=> judd hybrid cloud fix roxctl

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/coolstore-event-listener.yaml.j2
=> fixed event listener

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/sonarqube-scan-task.yaml.j2
=> add name for scan code task

ansible/lifecycle_azure.yml
fix status by handling incosistent az command output
azure cloud provider lifecycle status
```paste below
```
=> fix status by handling incosistent az command output

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/create-sonarqube-resources.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/workload.yml
change admin password on provisioning
=> Change password on Sonarqube

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/app-coolstore-ci.yaml.j2
issue with service account sync on argo
=> ignore service account sync differences

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/workload.yml
Added tasks to capture route and user information for ArgoCD
```paste below
```
=> Added tasks to capture route and user information for ArgoCD

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/workload.yml
=> Add credentials for apps

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/ci-build-configs.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/ci-imagestreams.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/coolstore-build-configs.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/coolstore-imagestreams.yaml.j2
remove labels and add http prefix
=> Apac summit 08

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/coolstore-build-configs.yaml.j2
Increase build memory limit for inventory
=> Increase build memory limit for inventory

ansible/configs/summit-hybrid-cloud-binder/post_software.yml
Add new cluster aws-prod-cluster-a in binder
config: summit-open-hybrid-cloud
=> Apac summit

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/workload.yml
=> Updated the url for sonarqube to http

ansible/configs/hybrid-cloud-binder/post_software.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_demo_apps/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_demo_apps/files/demos/spring4shell/everything.yaml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_demo_pipeline/tasks/workload.yml
- room to breathe
- deploy apps for rhacs demo
=> judd hybrid cloud rhacs app

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/unit-test-task.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/web-ui-ci-pipeline.yaml.j2
=> add unit test task

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/unit-test-task.yaml.j2
=> Fix pipeline

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/image-check-task.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/image-scan-task.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/unit-test-task.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/web-ui-ci-pipeline.yaml.j2
=> Update names as per Steven's request

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/update-repo-task.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/web-ui-ci-pipeline.yaml.j2
=> Reorder tasks

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/web-ui-ci-pipeline.yaml.j2
=> fix missing task ref

ansible/configs/tech-desktop-901/software.yml
=> async limit exceeded

ansible/configs/tech-desktop-901/software.yml
=> retry added

ansible/roles_ocp_workloads/ocp4_workload_gitops_workshop/templates/argocd_cr.yaml.j2
Reverts redhat-cop/agnosticd#5478
=> Revert "Introduce ocp4_workload_openshift_gitops_argo_cr_additional_values"

ansible/configs/convert-to-rhel/post_software.yml
Added code to ensure CentOS system is updated by the end
Added package module to update system.
```paste below
```
=> Convert2RHEL Update post_software.yml

ansible/configs/summit-hybrid-cloud-binder/post_software.yml
DC cluster added 
Config: summit-open-hybrid-cluster
=> add dc cluster

ansible/configs/summit-hybrid-cloud-binder/post_software.yml
Renamed imported cluster
config: summit-open-hybrid-binder
=> Rename imported cluster

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/create-sonarqube-resources.yml
=> updated sonarqube url to https

ansible/roles_ocp_workloads/ocp4_workload_opentour_dach_2022/tasks/workload.yml
Tiny update of my opentour 2022 dach role
opentour 2022 dach role
nothing
=> Added hello-dev & hello-main to my  opentour 2022 dach role

ansible/configs/ansible-middleware-workshop/post_software.yml
Minor change to EC2 instructions to remove SSH login details.
ansible-middleware-workshop
```
=>  Edit to the ec2 instructions

ansible/configs/containerize-app-demo/post_software.yml
This code unregisters the bastion system so external repos can be installed in the lab.
```paste below
```
=> Containerize App Demo removing subscription bug fix

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
Double amount of retries
ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
nothing
=> Double amount of retries

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
=> Update Multi-User Provision Data

ansible/roles-infra/infra-images/defaults/main.yaml
add more text to avoid getting BETA for rhel9
infra-images
```paste below
```
=> add more text to avoid getting BETA for rhel9

ansible/roles-infra/infra-images/defaults/main.yaml
fix typo in rhel9 search string
infra-images
```paste below
```
=> fix typo in rhel9 search string

ansible/roles_ocp_workloads/ocp4_workload_gitops_workshop/tasks/workload.yml
- name: Modify the web terminal DevWorkspaceTemplate with a custom tools image
kubernetes.core.k8s:
definition: "{{ lookup('file', 'devworkspacetemplate.yaml' ) | from_yaml }}"
state: present
>>>>  retries: 5
>>>>   delay: 30
```
=> ocp4_workload_gitops_workshop - workload

ansible/roles_ocp_workloads/ocp4_workload_gitops_workshop/tasks/workload.yml
{
"msg": "Unsupported parameters for (kubernetes.core.k8s) module: delay, register, retries, until Supported parameters include: api_key, api_version, append_hash, apply, ca_cert, client_cert, client_key, context, continue_on_error, delete_options, force, generate_name, host, impersonate_groups, impersonate_user, kind, kubeconfig, label_selectors, merge_type, name, namespace, no_proxy, password, persist_config, proxy, proxy_headers, resource_definition, server_side_apply, src, state, template, username, validate, validate_certs, wait, wait_condition, wait_sleep, wait_timeout",
"invocation": {
"module_args": {
"definition": {
"apiVersion": "workspace.devfile.io/v1alpha2",
"kind": "DevWorkspaceTemplate",
"metadata": {
"annotations": {
"controller.devfile.io/allow-import-from": "*"
}, …
=> Revert changes to ocp4_workload_gitops_workshop

ansible/configs/sap-integration/pre_infra.yml
rhjcd-patch-call create_ssh_provision_key in pre-infra
```paste below
```
=> call create_ssh_provision_key in pre-infra

ansible/configs/sap-integration/files/requirements_k8s.txt
rhjcd-patch-bump kubernetes to 12.0.1
```paste below
```
=> bump kubernetes to 12.0.1

ansible/configs/sap-integration/requirements.yml
Reverts redhat-cop/agnosticd#5408
=> Revert "Update requirements.yml"

ansible/configs/aap2-ansible-workshops/vars/configascode_vars.yaml
rhjcd-patch-create configascode vars file
```paste below
```
=> create configascode vars file

ansible/configs/aap2-ansible-workshops/vars/configascode_vars.yml
Update vars for ansible configascode
aap2 workshop vars
```paste below
```
=> Update vars for ansible configascode

ansible/configs/odf-dr-binder/README.adoc, ansible/configs/odf-dr-binder/default_vars.yml, ansible/configs/odf-dr-binder/default_vars_ec2.yml, ansible/configs/odf-dr-binder/destroy_env.yml, ansible/configs/odf-dr-binder/files/cloud_providers/azure_cloud_template.j2, ansible/configs/odf-dr-binder/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/odf-dr-binder/files/cloud_providers/ec2_cloud_template_json.j2, ansible/configs/odf-dr-binder/files/cloud_providers/terraform_ec2_cloud_template.tf.j2, ansible/configs/odf-dr-binder/files/cloud_providers/terraform_ec2_cloud_template.tfvars.j2, ansible/configs/odf-dr-binder/files/repos_template.j2, ansible/configs/odf-dr-binder/infra.yml, ansible/configs/odf-dr-binder/post_infra.yml, ansible/configs/odf-dr-binder/post_software.yml, ansible/configs/odf-dr-binder/pre_infra.yml, ansible/configs/odf-dr-binder/pre_software.yml, ansible/configs/odf-dr-binder/requirements.yml, ansible/configs/odf-dr-binder/sample_vars.yml, ansible/configs/odf-dr-binder/software.yml, ansible/configs/odf-dr-binder/stop.yml, ansible/configs/odf-dr-binder/templates/auto-import-secret.yaml.j2, ansible/configs/odf-dr-binder/templates/klusterlet-addon-config.yaml.j2, ansible/configs/odf-dr-binder/templates/managed-cluster.yaml.j2, ansible/configs/odf-dr-binder/templates/secured_cluster.yaml.j2, ansible/configs/odf-dr-binder/templates/set_oauth_token_age.yml.j2, ansible/configs/odf-dr-binder/update.yml
This is binder config for ODF DR which is under development.
```paste below
```
=> Added Binder Config for ODF DR

ansible/roles_ocp_workloads/ocp4_workload_3scale_workshop/files/ec2_cloud_template.j2
rhjcd-patch-add ec2 cloud template.j2 to 3scale workshop
```paste below
```
=> add ec2 cloud template.j2 to 3scale workshop

ansible/configs/satellite-hackfest/setup_lab_user.yml
Update variables for ssh configuration
```paste below
```
=> Satellite-hackfest update ssh key variables

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/create-stackrox-secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/inform-only-policy-tasks.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/coolstore-build-configs.yaml.j2
=> Apac summit 10.1

ansible/roles/agnosticd_save_output_dir/tasks/main.yml
Fix indent level.
Role `agnosticd_save_output_dir`
=> Fix indent level on apply in agnosticd_save_output_dir

ansible/roles_ocp_workloads/ocp4_workload_submariner/README.adoc, ansible/roles_ocp_workloads/ocp4_workload_submariner/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_submariner/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_submariner/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_submariner/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_submariner/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_submariner/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_submariner/templates/aws-secret.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_submariner/templates/managed-cluster-set.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_submariner/templates/submariner-addon.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_submariner/templates/submariner-broker.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_submariner/templates/submariner-config.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_submariner/templates/update-cluster-label.yaml.j2
New role: ocp4_workload_submariner
role: ocp4_workload_submariner
=> New ocp4 workload role

ansible/roles/agnosticd_save_output_dir/tasks/main.yml, ansible/roles/host-ocp4-installer/tasks/main.yml
=> Revert outputdir-to-s3 change

ansible/configs/satellite-hackfest/pre_software.yml
Adding the student user role to the satellite-hackfest environment
```paste below
```
=> satellite-hackfest add student role

ansible/roles_studentvm/studentvm_ocp4/defaults/main.yml
=> updating url for odo package

ansible/roles_studentvm/studentvm_ocp4/defaults/main.yml, ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
=> Updating url for odo again

ansible/roles/ocp4-workload-camel3-workshop/tasks/provision_odf.yaml
=> adding delay in provision_odf.yaml

ansible/configs/ansible-multitier-rhel8/pre_infra.yml, ansible/configs/ansible-multitier-rhel8/pre_software.yml
Updates to the new ssh roles for The Definitive RHEL 8 lab.
summit-rhel-8-lab
```paste below
```
=> Summit RHEL 8 Lab update for new ssh roles

ansible/configs/smart-management-foundations/pre_software.yml
Updates ssh role to most recent interation
```paste below
```
=> smart-management-foundations Updating ssh role

ansible/configs/ansible-multitier-rhel8/default_vars.yml, ansible/configs/ansible-multitier-rhel8/default_vars_ec2.yml
Update private key file definition in two places
ansible-multitier-rhel8
```paste below
```
=> update private key file

ansible/roles/ocp4-workload-workshop-admin-storage/defaults/main.yml
Fix default value for WORKSHOP_FILE in ocp4-workload-workshop-admin-storage.
Role ocp4-workload-workshop-admin-storage
=> Fix WORKSHOP_FILE default for ocp4-workload-workshop-admin-storage

ansible/configs/smart-management-foundations/pre_software.yml
CI failing at this stage, removing as I cannot remember why it was installed in the first place.
```paste below
```
=> smart-management-foundations remove pip install

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/files/managedcluster.yaml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/files/managedclusteraddon.yaml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/get_cluster_credentials.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/hypershift-deployment.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/namespace-hypershift.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/secret-aws-credentials.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/secret-s3-credentials.yaml.j2
New workload to enable HyperShift on an ACM 2.6+ installation.
Optionally deploy HyperShift clusters.
=> Add Hypershift workload

ansible/roles_studentvm/studentvm_ocp4/defaults/main.yml
=> updating odo url

ansible/roles_ocp_workloads/ocp4_workload_3scale_workshop/tasks/post_workload.yml
Updating the output message to be easier to understand.
ocp4_workload_3scale_workshop
=> ocp4_workload_3scale_workshop: updating output message

ansible/roles_ocp_workloads/ocp4_workload_opentour_dach_2022/tasks/argocd_info.yml, ansible/roles_ocp_workloads/ocp4_workload_opentour_dach_2022/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_opentour_dach_2022/templates/apps/cluster-configuration.yaml.j2
Improve Red Hat OpenTour DACH 2022 workshop
Improve Red Hat OpenTour DACH 2022 workshop 
=> Improve Red Hat OpenTour DACH 2022 workshop

ansible/configs/smart-management-foundations/setup_lab_user.yml
Fix variables for SSH key copy
```paste below
```
=> Fix variables for SSH key copy

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern/tasks/workload.yml
This is in support of the Validated Patterns "MultiCloud GitOps - Deployed" Service Catalog.
We need to install the *make* utility to deploy our latest pattern.  We have added a task to add
the *make* utility to the bastion host.
*ocp4_workload_validated_pattern*
None
=> Added task to install the make utility.

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern/tasks/workload.yml
Fixes issue with installation of the make utility.
ocp4_workload_validated_pattern
None
=> Vp update for make utility install

docs/Deploying_Using_Execution_Environments.adoc
Added documentation on how to use Execution Environments to run AgnosticD (for OpenShift deployments.
=> Added doc on execution environments

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern/tasks/workload.yml
- Added command to source the virtualenv environment to our Validated Pattern task
ocp4_workload_validated_pattern
None
=> Vp v1 1 updates - source addition for virtualenv

ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/README.md, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/files/create-git-webhooks.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/ansible-builder-task.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/docker-config.json.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/el-route.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/event-listener.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/github-secret.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/hub-push-secret.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/link-secret-sa.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/pipeline-ansible-builder.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/pipeline-run.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/pvc.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/registry-pull-secret.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/trigger-binding.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/trigger-template.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/trigger.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/templates/webhook-post-body.json.j2
=> WIP: Ansible ee v1.1

docs/Setup AgnosticD on Mac.adoc, tools/deployer_scripts/aad_create, tools/deployer_scripts/aad_destroy, tools/deployer_scripts/aad_workload
Added docs and shell scripts to develop for OpenShift using AgnosticD
=> Add OCP AgnosticD docs for OpenShift Development

docs/Setup AgnosticD on Mac.adoc, tools/deployer_scripts/aad_create, tools/deployer_scripts/aad_destroy
=> Updates to docs and scripts

docs/Setup AgnosticD on Mac.adoc, tools/deployer_scripts/aad_create, tools/deployer_scripts/aad_destroy, tools/deployer_scripts/aad_workload
Instructions and shell scripts for deploying on M1 Macs now work end to end.
=> Tested and should work

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/secret-aws-credentials.yaml.j2, docs/Setup AgnosticD on Mac.adoc
Hypershift workload used the wrong (old) variable for the ocp pull secret.
Also updated docs one more time for macOS setup.
=> Fix hypershift

ansible/roles_ocp_workloads/ocp4_workload_mta6/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta6/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta6/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_mta6/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta6/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta6/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta6/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta6/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta6/templates/applicationset.yaml.j2
Migration Toolkit for Applications V6 has been released (based on Tackle2).
This PR adds a workload to deploy MTA to a cluster.
ocp4_workload_mta6
=> Add Workload to deploy MTA 6

ansible/configs/rhte23-rhel-edge/.yamllint, ansible/configs/rhte23-rhel-edge/README.adoc, ansible/configs/rhte23-rhel-edge/default_vars.yml, ansible/configs/rhte23-rhel-edge/default_vars_osp.yml, ansible/configs/rhte23-rhel-edge/destroy_env.yml, ansible/configs/rhte23-rhel-edge/files/hosts_template.j2, ansible/configs/rhte23-rhel-edge/files/ssh_config.j2, ansible/configs/rhte23-rhel-edge/post_infra.yml, ansible/configs/rhte23-rhel-edge/post_software.yml, ansible/configs/rhte23-rhel-edge/pre_infra.yml, ansible/configs/rhte23-rhel-edge/pre_software.yml, ansible/configs/rhte23-rhel-edge/requirements.yml, ansible/configs/rhte23-rhel-edge/sample_vars/sample_vars_osp.yml, ansible/configs/rhte23-rhel-edge/setup_cloud_user.yml, ansible/configs/rhte23-rhel-edge/software.yml
This config is to provide hands on lab for "RHEL for Edge" at RHTE23.
Includes one bastion VM and two other VMs to simulate edge devices.
config name: rhte23-rhel-edge
```paste below
```
=> new config rhte23-rhel-edge

ansible/configs/sap-hana/default_vars.yml
=> removing epel url

ansible/configs/sap-hana/default_vars.yml, ansible/configs/sap-hana/software.yml
=> disabling ansible package version 6.3.0 

ansible/configs/sap-hana/software.yml
=> adding epel gpgcheck

ansible/configs/sap-hana/software.yml
=> revert changes

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/workload.yml
Updates TL500 Workshop to 4.11
=> 🐧 TL500 - 4.11 values file for base 🐧

ansible/configs/sap-smart/default_vars.yml
Reverts redhat-cop/agnosticd#5658
=> Revert "Update default_vars.yml"

ansible/configs/sap-smart/software.yml
Adding
- name: Ensure additional packages are installed
yum:
name:
- ansible
state: present
exclude:
- ansible-6.3.0-1.el8.noarch
=> Update software.yml - SAP SMART 

ansible/roles-infra/infra-aws-open-environment/tasks/print_user_info.yaml
Change from  
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html to
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html
ributing.adoc
=> Update URL in AWS OPEN Sandbox

ansible/configs/ocp4-ha-lab/default_vars.yml, ansible/configs/ocp4-ha-lab/files/aws_upi_bootstrap_parameters.json.j2, ansible/configs/ocp4-ha-lab/files/aws_upi_control_plane_parameters.json.j2, ansible/configs/ocp4-ha-lab/files/aws_upi_worker_parameters.json.j2, ansible/configs/ocp4-ha-lab/pre_software.yml, ansible/configs/ocp4-ha-lab/software.yml
Config updated as per 4.11.11 version, RHCOS images and RHEL9 images of VMs
VM images changes to RHEL90 GOLD
Necessary changes in jinja template of nodes for rhcos ami images as per us-east-2
Few fixes config
=> Config updated as per 4.11.11 version, RHCOS images and RHEL9 images of VMs

ansible/roles-infra/infra-images/defaults/main.yaml
ami-0f5b11b0103837b0d
RHEL-9.1.0_HVM-20221101-x86_64-2-Access2-GP2
roles-infra/infra-image
Adding the RHEL91 Image to the list
=> Adding RHEL91 Image to GOLD image list

ansible/roles/common/tasks/main.yml, ansible/roles/common/tasks/packages_el9.yml
Task added for RHEL9 - Install common packages for RHEL 9
Package file created for RHEL9 - packages_el9.yml
- New/update role Pull Request
=> Updated the role as per RHEL9

ansible/roles/common/tasks/main.yml, ansible/roles/common/tasks/packages_el9.yml
Co-authored-by: Sarvesh Pandit <sapandit@redhat.com>
```paste below
```
=> Updated the role as per RHEL9 (#5676)

ansible/configs/ocp4-ha-lab/post_software.yml, ansible/configs/ocp4-ha-lab/software.yml
This is just moving task from software.yaml file to post_software.yaml file as it was failing.
=> Task moved from software to post_software file

ansible/configs/rosa/software.yml
update ROSA with warning about ROSA token.
rosa 
```paste below
```
=> update ROSA with warning about ROSA token.

ansible/configs/ansible-middleware-workshop/post_software.yml
Remove Bastion output as it uses the incorrect credentials
=> Ansible Middleware Workshop

ansible/configs/rosa/software.yml
=> ROSA Token Warning

ansible/configs/hybrid-cloud-binder/post_software.yml, ansible/configs/hybrid-cloud-binder/requirements.yml, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_ohc/tasks/stackrox_create_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_ohc/tasks/workload.yml
Incorporated summit pipeline which includes sonarqube code scanning and acs image scanning for aiml workload.
Config: Hybrid-cloud-binder
=> Aiml DevSecOps pipeline

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/templates/openshift-gitops.yaml.j2
Add support to the GitOps workload to
a) change the TLS encryption on the route to re-encrypt to prevent certificate warnings
b) update resource customizations for the ArgoCD object.
=> Add support for resource customizations and secure route

ansible/configs/hybrid-cloud-binder/default_vars.yml, ansible/configs/hybrid-cloud-binder/post_software.yml, ansible/configs/hybrid-cloud-binder/sample_vars.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_ee/files/create-git-webhooks.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/create-sonarqube-resources.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/create-stackrox-secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/inform-only-policy-tasks.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/tasks/inform_only_policy_tasks.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/tasks/sonarqube_create_resources.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/tasks/stackrox_create_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_ohc/tasks/inform_only_policy_tasks.yml, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_ohc/tasks/sonarqube_create_resources.yml, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_ohc/tasks/stackrox_create_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_sonarqube/tasks/workload.yml
ignore errors on ai_ml rhacs image integration - or @treddy08 please create a unique name for the integration
ocp4_workload_object_detection_ai_ml_ohc
```paste below
```
=> more idempotent coolstore and aiml

ansible/configs/quay-rhel-poc/.yamllint, ansible/configs/quay-rhel-poc/README.adoc, ansible/configs/quay-rhel-poc/default_vars.yml, ansible/configs/quay-rhel-poc/default_vars_ec2.yml, ansible/configs/quay-rhel-poc/default_vars_osp.yml, ansible/configs/quay-rhel-poc/destroy_env.yml, ansible/configs/quay-rhel-poc/files/hosts_template.j2, ansible/configs/quay-rhel-poc/files/repos_template.j2, ansible/configs/quay-rhel-poc/post_infra.yml, ansible/configs/quay-rhel-poc/post_software.yml, ansible/configs/quay-rhel-poc/pre_infra.yml, ansible/configs/quay-rhel-poc/pre_software.yml, ansible/configs/quay-rhel-poc/sample_variables/README.adoc, ansible/configs/quay-rhel-poc/sample_variables/rhel8_server_on_ec2.yml, ansible/configs/quay-rhel-poc/sample_variables/rhel8_server_on_osp.yml, ansible/configs/quay-rhel-poc/sample_variables/secrets_example_all.yml, ansible/configs/quay-rhel-poc/sample_variables/secrets_example_ec2.yml, ansible/configs/quay-rhel-poc/sample_variables/secrets_example_osp.yml, ansible/configs/quay-rhel-poc/software.yml
This PR adds a new config which deploys a RHEL machine for Quay and Clair deployment for hands-on labs.
The config has been locally tested to work perfectly with openstack and aws providers.
Quay on RHEL POC
```paste below
```
=> Add config quay-rhel-poc

ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/single_user_controller.yml
Create dev-admin user for automation controller
=> [WIP] create dev-admin user for controller

ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/single_user_controller.yml
=> fix for delayed service startup

ansible/roles/automation-controller-config/defaults/main.yml, ansible/roles/automation-controller-config/tasks/main.yml, ansible/roles/automation-controller-config/tasks/users.yml
Added tasks to add users in automation controller
role: automation-controller-config
=> user addition task

ansible/configs/ocp4-ha-lab/post_software.yml
Adding Bookbag role in the post software with action create for the Ci ILT_OCP4_ADVANCED_INFRA_DEPLOY
=> adding bookbag

ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/tasks/sonarqube_create_resources.yml
=> Check json output

ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/files/kustomization.yaml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/templates/cicd/app-ci-pipeline.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/templates/cicd/deploy-scan-task.yaml
=> added acs deploy scan

ansible/configs/osp16-director-deployment/files/cloud_providers/osp_cloud_template_master.j2
Add depends_on to avoid race condition issue
=> [osp16-director-deployment] Update osp_cloud_template_master.j2

ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/templates/cicd/deploy-scan-task.yaml, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_ohc/tasks/sonarqube_create_resources.yml
=> Add 'not defined' statement for project check

ansible/roles_ocp_workloads/ocp4_workload_adv_app_deploy_ilt_final_lab/templates/argocd_secret_gitea_credentials.yaml.j2
ArgoCD on 4.10 needs an extra annotation for a repo secret.
=> Add annotations to ArgoCD secret for final lab.

.github/workflows/static-checks-pr.yml, tests/static/tox.ini
=> Fix static checks

ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/argocd_info.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/single_user_controller.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/single_user_hub.yml
Fixed userinfo 
role: ocp4_workload_gitops_aap
=> fixed userinfo

ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_ohc/templates/app/pipeline.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_ohc/templates/rest/pipeline.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_ohc/templates/sonarqube-scan-task.yaml.j2
=> Change task name of code scanning

ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/templates/common/tasks/task-add-ee.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/templates/common/tasks/task-launch-job-template.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/templates/common/tasks/task-update-job-template.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/templates/section2/pipelines/pipeline.yaml.j2
variablized credentials for registry
role: ocp4_workload_tekton_execution_environment
=> rectification

ansible/roles/automation-controller-config/tasks/credential.yml
Added options for creating container registry credentials in automation controller. 
role: automation-controller-config
=> extended credentials inputs

ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/templates/section2/pipelines/pipeline.yaml.j2
Fixed syntax errors
role: tekton-execution-environment
=> Rh23 tekton mod

ansible/configs/quay-rhel-poc/post_software.yml
Added task to generate bookbag.
corresponding agV is merged. 
bookbag has been tested locally.
Task name: Deploy bookbag
=> Change config quay-rhel-poc to include bookbag task

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/dev-username-distribution-install.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/dev-username-distribution-install.yml, ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/tasks/additional/gitea-webhooks.yml
PR to fix yamllint warnings/errors
=> Fixing yamllint errors

ansible/configs/sap-rhvh/pre_software.yml
=> removing non-existence repo

ansible/roles_ocp_workloads/ocp4_workload_pntae/tasks/workload.yml
Grading script location updated to https://www.opentlc.com/download/pntae/ocp4/
=> Grading script location updated

ansible/roles_ocp_workloads/ocp4_workload_snyk/tasks/workload.yml
Adding more retries to  Wait until CSV is Installed - from 15 to 20 
ocp4_workload_snyk
=> ocp4_workload_snyk - increasing retires 

ansible/configs/rosa/software.yml
fix rosa email output
rosa
```paste below
```
=> fix rosa email output

ansible/configs/sap-rhvh/pre_software.yml
=> removing the lock for rhel-release

ansible/configs/rosa/software.yml
cleanup rosa email
rosa
```paste below
```
=> cleanup rosa email

ansible/configs/ocp4-cluster/destroy_env_ec2.yml
fix user created rosa destroy
ocp4-cluster
```paste below
```
=> fix rosa destroy

ansible/configs/sap-rhvh/pre_software.yml
=> adding fstype in rhvm_image_device

ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/templates/cicd/task-gitea-pull-request.yaml.j2
=> Change logging info to Git instead of GitHub

ansible/configs/sap-rhvh/software.yml
=> locking ansible version

ansible/configs/sap-rhvh/software.yml
=> lock ansible version in seperate play

ansible/configs/sap-rhvh/software.yml
=> adding yum version lock for ansible

ansible/configs/sap-rhvh/post_software.yml
=> adding correct directoy for img

ansible/configs/devsecops-vld-framework-binder/README.adoc, ansible/configs/devsecops-vld-framework-binder/default_vars.yml, ansible/configs/devsecops-vld-framework-binder/default_vars_ec2.yml, ansible/configs/devsecops-vld-framework-binder/destroy_env.yml, ansible/configs/devsecops-vld-framework-binder/files/cloud_providers/azure_cloud_template.j2, ansible/configs/devsecops-vld-framework-binder/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/devsecops-vld-framework-binder/files/cloud_providers/ec2_cloud_template_json.j2, ansible/configs/devsecops-vld-framework-binder/files/cloud_providers/terraform_ec2_cloud_template.tf.j2, ansible/configs/devsecops-vld-framework-binder/files/cloud_providers/terraform_ec2_cloud_template.tfvars.j2, ansible/configs/devsecops-vld-framework-binder/files/repos_template.j2, ansible/configs/devsecops-vld-framework-binder/import_clusters_to_hub.yaml, ansible/configs/devsecops-vld-framework-binder/infra.yml, ansible/configs/devsecops-vld-framework-binder/post_infra.yml, ansible/configs/devsecops-vld-framework-binder/post_software.yml, ansible/configs/devsecops-vld-framework-binder/pre_infra.yml, ansible/configs/devsecops-vld-framework-binder/pre_software.yml, ansible/configs/devsecops-vld-framework-binder/requirements.yml, ansible/configs/devsecops-vld-framework-binder/sample_vars.yml, ansible/configs/devsecops-vld-framework-binder/software.yml, ansible/configs/devsecops-vld-framework-binder/stop.yml, ansible/configs/devsecops-vld-framework-binder/templates/auto-import-secret.yaml.j2, ansible/configs/devsecops-vld-framework-binder/templates/klusterlet-addon-config.yaml.j2, ansible/configs/devsecops-vld-framework-binder/templates/managed-cluster.yaml.j2, ansible/configs/devsecops-vld-framework-binder/templates/secured_cluster.yaml.j2, ansible/configs/devsecops-vld-framework-binder/update.yml
New multicomponent config for DevSecOps Validated Pattern. It will use ocp4-clusters as subcomponent.  
=> New binder config - DevSecOps Validated Pattern

ansible/configs/sap-rhvh/pre_software.yml
adding resizefs to grow the partition
```paste below
```
=> updating filesystem module

ansible/configs/sap-rhvh/pre_software.yml
=> adding resizefs after the disk mount

ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/multi_user_controller.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/single_user_controller.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/workload.yml
Added wait for controller to be available 
role: ocp4_workload_gitops_app
=> added task to check status

ansible/roles_ocp_workloads/ocp4_workload_rhacs_secured_cluster/tasks/workload.yml
Increased Retry for sensor
-->
```
=> Increased Retry for sensor

ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/tasks/workload.yml
added wait for triggers to be created for sno
role: ocp4_workload_tekton_execution_environment
=> added wait

ansible/configs/devsecops-vld-framework-binder/post_software.yml
fix for validate devsecops framework binder config
config: vld-devsecops-framework-binder
=> fixed for managed cluster

ansible/configs/open-environment-azure-subscription/post_software.yml
Add note to not delete azure subs
```paste below
```
=> Add note to not delete azure subs

ansible/configs/smart-management-foundations/post_software.yml
=> adding labuser setting to satellite

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/stackrox_create_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/update_acm_requirements.yaml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acs-signature-policy.json.j2
Add the manifests to deploy to production
=> add prod cluster manifests

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/stackrox_create_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/update_acm_requirements.yaml
=> Hcp devsecops v1.1.6

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/update_devsecops_repository.yaml
=> Remove kafka operator creation

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/inform_only_policy_tasks.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/stackrox_create_secrets.yml
Seems to be an intermittent error when in the URI module when calling stackrox
=> Retries on GET requests

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/stackrox_create_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml
=> Add longer retry for stackrox

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/stackrox_create_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml
=> Hcp devsecops v1.2.0

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/templates/openshift-gitops.yaml.j2
Introduce sync timeout for argo reconciliation
```paste below
```
=> Hcp devsecops v1.2.1

ansible/roles/ocp4-workload-jdg-workshop/tasks/post_workload.yml, ansible/roles/ocp4-workload-sso-workshop/tasks/post_workload.yml
fixed two roles to use agnosticd_user_info instead
- Enhancement Pull Request
ocp4-workload-sso-workshop
ocp4-workload-jdg-workshop
=> change to agnosticd_user_info

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/trigger_globex_webhook.yaml
=> Add timestamp for page updated

ansible/configs/ocp4-cluster/default_vars_azure.yml, ansible/configs/ocp4-cluster/files/cloud_providers/azure_cloud_template.j2
ocp4-cluster
```paste below
```
=> add ability to specify offer for rhel in azure

ansible/configs/ocp4-cluster/default_vars_azure.yml, ansible/configs/ocp4-cluster/files/cloud_providers/azure_cloud_template.j2
add required plan to azure gold image
ocp4-cluster
```paste below
```
=> Azure gold

ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/hosted-cluster-auth.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/managed-cluster.yaml.j2
Fixed a few things, added a few things
=> Updated with fixes and improvements

tools/virtualenvs/README.adoc
=> Update venv known issues for equinix

ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/tasks/additional/stackrox-policy-configuration.yml
Task failing in RHTE load testing, added retries
Role https://github.com/redhat-cop/agnosticd/security/dependabot
=> Improve robustness of intermittent stackrox task

ansible/roles_ocp_workloads/ocp4_workload_dso/tasks/gogs.yml
Sometimes Gogs is taking time come up and running, so increasing retries times ocp4_workshop_dso
=> Sometimes Gogs is taking time come up and running

ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/setup_authentication.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/setup_oauth_certificate.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/certmanager/placementbinding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/certmanager/placementrule.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/certmanager/policy.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/hosted-cluster-auth.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/secret-oauth.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_le_certificates/templates/api-certificate-secret.j2, ansible/roles_ocp_workloads/ocp4_workload_le_certificates/templates/ingress-controller-certificate-secret.j2
Added support to add certificates to a hosted cluster.
=> Add certificate support

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/.gitignore, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml
Signed-off-by: Mario Vazquez <mavazque@redhat.com>
We are onboarding a new lab onto RHPDS. This is the ansible role that configures the lab.
=> 5G RAN Deployment Lab Role

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_hashicorp_vault.yaml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/app/vault/acm-subscription.yml.j2
=> Save unsealing key file

ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/workload.yml
added based domain in user_data
role: ocp4_workload_gitops_aap
=> added based domain

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/files/stateful-set-vault.yaml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/files/unseal.sh, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_hashicorp_vault.yaml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/app/vault/acm-channel.yml.j2
=> Added post webhook for vault

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_hashicorp_vault.yaml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml
=> Add user logging for vault data

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_hashicorp_vault.yaml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml
=> Add missing namespace for oc command

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_hashicorp_vault.yaml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml
=> Insert missing namespace

ansible/configs/ocp4-cluster/requirements.yml
rhjcd-patch-add community.aws collection to reqs
```paste below
```
=> add community.aws collection to reqs

ansible/configs/equinix-baremetal-node/README.adoc, ansible/configs/equinix-baremetal-node/default_vars_equinix_metal.yml, ansible/configs/equinix-baremetal-node/destroy_env.yml, ansible/configs/equinix-baremetal-node/post_infra.yml, ansible/configs/equinix-baremetal-node/post_software.yml, ansible/configs/equinix-baremetal-node/pre_infra.yml, ansible/configs/equinix-baremetal-node/pre_software.yml, ansible/configs/equinix-baremetal-node/requirements.yml, ansible/configs/equinix-baremetal-node/sample_vars_equinix_metal.yml, ansible/configs/equinix-baremetal-node/software.yml
=> New config to create a baremetal node on equinix

ansible/configs/ocp4-cluster/requirements.yml
- Revert ansibele.aws to 2.2.0
- Revert adding community.aws
=> Revert changes to ocp4-cluster requirements.yml

ansible/configs/equinix-baremetal-node/software.yml
=> adding infra_workload

ansible/configs/equinix-baremetal-node/requirements.yml
community.crypto.openssh_keypair
```paste below
```
=> adding collections

ansible/configs/equinix-baremetal-node/requirements.yml
=> Adding community.crypto

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
=> adding become: false

ansible/configs/equinix-baremetal-node/default_vars_equinix_metal.yml
=> adding variables

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/.gitignore, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/files/pull-secret.json
=> removing gitignore

ansible/configs/equinix-baremetal-node/software.yml
=> removing kcli 

ansible/configs/equinix-baremetal-node/requirements.txt
=> adding kubernetes==23.3.0

ansible/configs/equinix-baremetal-node/requirements.yml
=> adding - name: kubernetes.core   version: 2.3.0

ansible/configs/osp17-director-deployment/post_software.yml
=> ssh and bookbag in post_software.yaml

ansible/configs/equinix-baremetal-node/default_vars_equinix_metal.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/.gitignore, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/files/pull-secret.json, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/files/pull-secret.json.j2
=> Ocp4 workload 5gran deployments

ansible/configs/devsecops-vld-framework-binder/import_clusters_to_hub.yaml, ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> label logic added

ansible/configs/devsecops-vld-framework-binder/import_clusters_to_hub.yaml, ansible/configs/devsecops-vld-framework-binder/post_software.yml
Adding custom value to label (purpose) for managed clsuters.
=> adding labels for managed clusters

ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> Fixed typo

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/defaults/main.yml
=> Fixes for post argo and kafka migration

ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/workload.yml
Added agnosticd_user_info data for quay 
role: ocp4_workshop_quay_operator
=> added agnostic user data

ansible/configs/devsecops-vld-framework-binder/post_software.yml
Argocd is getting deployed by ACM so added tasks in binder to fetch user data from dev and prod clusters.
=> Added argocd user data task for prod and dev clusters

ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> Fixed typo on line 223

ansible/configs/devsecops-vld-framework-binder/post_software.yml
Update argocd task to get route
=> update agrocd route task

ansible/lifecycle_ec2.yml, ansible/roles-infra/infra-ec2-create-inventory/tasks/main.yml, ansible/roles-infra/infra-ec2-template-generate/.yamllint, ansible/roles-infra/infra-ec2-template-generate/tasks/main.yml, ansible/roles-infra/infra-ec2-template-generate/tasks/upload_template-aws_s3.yml, ansible/roles-infra/infra-ec2-template-generate/tasks/upload_template-s3_object.yml, ansible/roles/agnosticd_restore_output_dir/tasks/fetch-from-s3-aws_s3.yml, ansible/roles/agnosticd_restore_output_dir/tasks/fetch-from-s3-s3_object.yml, ansible/roles/agnosticd_restore_output_dir/tasks/restore-from-s3.yml, ansible/roles/agnosticd_save_output_dir/tasks/upload-archive-s3-aws_s3.yml, ansible/roles/agnosticd_save_output_dir/tasks/upload-archive-s3-s3_object.yml, ansible/roles/agnosticd_save_output_dir/tasks/upload-archive-s3.yml, ansible/roles/common/tasks/main.yml, ansible/roles/edge_nodes_info/tasks/main.yml, ansible/roles/set-repositories/tasks/satellite-repos.yml
Support updated `amazon.aws` and `community.aws` collections.
- ocp4-cluster config
- save/restore output dir roles
=> Support updated amazon collections in requirements.

ansible/configs/devsecops-vld-framework-binder/post_software.yml
Incorrectly named variable leading to ansible job failure.
=> Incorrect variable naming

ansible/configs/devsecops-vld-framework-binder/post_software.yml, ansible/roles/agnosticd_restore_output_dir/tasks/restore-from-s3.yml
=> Fix to restore s3 file.

ansible/roles-infra/infra-ec2-template-generate/tasks/main.yml, ansible/roles/agnosticd_save_output_dir/tasks/upload-archive-s3.yml
Fix additional missing parenthesis
```paste below
```
=> Fix additional missing parenthesis

ansible/configs/devsecops-vld-framework-binder/import_clusters_to_hub.yaml
Missing fix for one of the files where the variable was named incorrectly.
=> Fix missing variable name

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/common/acm-channel.yml.j2
Add higher reconciliation rate for acm
```paste below
```
=> Add higher reconciliation rate for acm

ansible/configs/devsecops-vld-framework-binder/post_software.yml
Added few tasks to fetch route, username and password for user data from hub cluster.
=> tasks to fetch  argocd route from  hub cluster

ansible/configs/devsecops-vld-framework-binder/import_clusters_to_hub.yaml
Change variable name just to be aligned with format. 
=> changed variable name

tools/execution_environments/ee-multicloud-public/requirements.yml
Add the "CoP" AAP2 Controller collection to simplify configuring and managing AAP2 Controller based demos, configs etc.
Medium term goal to move away from AgnosticD's duplication of roles in this area to a more mature and documented collection under active community development
execution_environments/ee-multicloud-public
=> Add the 'Cop' Controller collection under its preferred new name to EE

ansible/roles_ocp_workloads/ocp4_workload_codeserver/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_codeserver/templates/applicationset.yaml.j2
Add support for limits (with defaults) for Code Server workload
ocp4_workload_codeserver
=> Add Limits to Code Server

ansible/configs/ocp4-equinix-aio/requirements.yml
=> Bumping ocp4_aio_infra_role_deploy_bastion

.github/workflows/build-ee-dispatch.yml, .github/workflows/build-ee.yml, tools/execution_environments/ee-multicloud-public/Containerfile
Add the option to run the workflow manually providing the inputs and secrets.
=> Add workflow_dispatch to build-ee

tools/execution_environments/ee-multicloud-public/requirements.yml
Establish a convention of alphabetic ```requirement.yml``` for clarity and ease of use
execution_environments/ee-multicloud-public
=> Sort ee-multicloud-public requirements.yml order

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_hashicorp_vault.yaml
Fix spelling error on user data
```paste below
```
=> Fix spelling error on user data

ansible/configs/osp17-director-deployment/post_software.yml
=> osp17-director-deployment - post_software.yaml

ansible/configs/devsecops-vld-framework-binder/post_software.yml
Remove default argocd instance
```paste below
```
=> Remove default argocd instance

ansible/configs/ocp4-cluster/destroy_env_ec2.yml, ansible/roles/rosa-delete-clusters-cli/tasks/main.yaml
* had too many calls to hosts:
* too many conditional variables for execution
* shell -> command
* fully qualify modules
* better task names
=> cleanup rosa-delete-clusters-cli role

docs/README.adoc
=> update toc and spacing

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/files/pull-secret.json, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/files/pull-secret.json.j2, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
=> Added fixes to the ocp4_workload_5gran_deployments_lab role

ansible/configs/sap-hana/default_vars_osp.yml
=> RHEL version to 8.6 for Tower host in sap-hana

tools/execution_environments/ee-multicloud-public/Containerfile, tools/execution_environments/ee-multicloud-public/compare.sh, tools/execution_environments/ee-multicloud-public/ee-report.sh, tools/execution_environments/ee-multicloud-public/readme.adoc, tools/execution_environments/ee-multicloud-public/requirements.txt, tools/execution_environments/ee-multicloud-public/requirements.yml, tools/execution_environments/readme.adoc
=> EE: Add missing requirements for collections

ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/multi_user_controller.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/single_user_controller.yml
Set validate_cert to false in uri module to check status of automation controller.
role: ocp4_workload_gitops_aap
=> set validate cert to false

ansible/configs/sandbox/infra.yml, ansible/configs/sandbox/pre_infra.yml
Reverts redhat-cop/agnosticd#5756
=> Revert "move ec2 stuff to pre_infra and remove infra.yml"

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/files/stateful-set-vault.yaml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml
=> Change image name

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_hashicorp_vault.yaml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_sonarqube.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/common/acm-namespace-sonarqube.yml
=> Fix issues with new vault image and pvc for sonarqube

ansible/roles/bookbag/tasks/deploy-bookbag.yaml
Add retries to bookbag deploy.
Role: bookbag
=> Add retries in deploy bookbag

ansible/roles/deploy_automationcontroller/defaults/main.yml, ansible/roles/deploy_automationcontroller/tasks/automationcontroller_installer_venv.yml, ansible/roles/deploy_automationcontroller/tasks/main.yml, ansible/roles/deploy_automationcontroller/templates/automationcontroller_inventory.j2
AAP2.3 Installer needs changes to role deploy_automationcontroller
- Bigger timeouts
- new venv with python changes
- Updated to FQCNs throughout
role deploy_automationcontroller
=> Update aap2 installer role deploy_automationcontroller to support aap2.3

ansible/roles/aap_controller_cert_issue/tasks/main.yml
Refactor, add FQCN to aap2 controller cert role
Add new user name and password to simplify working with other roles
Make task names etc more consistent with Controller v Tower
roles/aap_controller_cert_issue
=> Refactor and enhance aap_controller_cert_issue logic

ansible/configs/aap2-ansible-workshops/vars/automate_smart_mgmt_vars.yml
rhjcd-patch-fix pre_build_controller_ami block indent
-->
rhjcd-patch-fix pre_build_controller_ami block indent
=> fix pre_build_controller_ami block indent

ansible/configs/rosa/software.yml
add user_info data for service complete email template
rosa
```paste below
```
=> add user_info data for service complete email template

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-oracle-vm.yml
=> Increasing wait period between checks for RHV VM

ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-tomcat-vm.yml
=> Changing conditional to wait for a IPv4 address

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-tomcat-vm.yml
=> Updating to wait for IPv4 address

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-tomcat-vm.yml
=> Adding conditionals to prevent early errors.

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-tomcat-vm.yml
=> Fixing a typo in the tomcat vm setup

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-tomcat-vm.yml
=> Increasing wait delay to 30sec from 10

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/deploy_projects.yml
Reference: https://github.com/quarkusio/quarkus/pull/27172
=> Fix quarkus.smallrye-openapi.servers

ansible/configs/aro/post_software.yml
Add post service msg for ARO
aro
```paste below
```
=> Add post service msg for ARO

ansible/configs/aro/htpasswd.yml
Remove data from htpasswd file in aro
aro
```paste below
```
=> Remove data from htpasswd file in aro

ansible/roles_ocp_workloads/ocp4_workload_rhacm/files/multiclusterhub.yaml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm/templates/multiclusterhub.yaml
- add availabilityConfig to template
- move template to proper place
- add availabilityConfig to mhc spec
- cleanup double newlines
=> judd workload rhacm availability

ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/setup_ldap.yml, ansible/roles_ocp_workloads/ocp4_workload_authentication/templates/configmap-ldap-ca-cert.yaml.j2
Thanks to @thomas-crowe and @jkupferer was able to replace the last command module in the auth workload.
=> Replace command module

ansible/configs/open-environment-azure/post_software.yml
fix variable names for aro service complete email
aro 
```paste below
```
=> fix pretty aro variable names

ansible/roles_ocp_workloads/ocp4_workload_gitops_amqstreams/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_amqstreams/files/create_acm_application.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_amqstreams/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_amqstreams/templates/acm-application.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_amqstreams/templates/acm-placement-rule.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_amqstreams/templates/acm-subscription.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_amqstreams/templates/amqstreams-namespace.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_hashicorp_vault/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_data_foundation/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_gitops/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_gitops/templates/acm-subscription.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_quay_registry/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_quay_registry/templates/acm-subscription.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_sonarqube/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_sonarqube/templates/acm-subscription.yml.j2
Additional fixes to gitops roles
```paste below
```
=> Devsecops acm consolidate 1.8

ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> Move roles to binder

ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> Move observability to post software

ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> Devsecops acm consolidate 1.9

ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_data_foundation/files/create_acm_application.yml
=> Change repo sub directory

ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_data_foundation/files/create_acm_application.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_gitops/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_quay_registry/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_sonarqube/defaults/main.yml
=> Devsecops acm consolidate 1.11

ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/setup_htpasswd.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/workload.yml
Add additional (missing) fields to user_info data section.
=> Add additional user info

ansible/configs/devsecops-vld-framework-binder/post_software.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_quay.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/rolebinding-argocd-edit-codeserver.yml.j2
=> Argo edit rights on ci namespace

ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/rhev-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/rhv-setup-tomcat-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-oracle-vm.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhv-setup-tomcat-vm.yml
=> Improve getting IP address of VM

tools/execution_environments/ee-multicloud-public/readme.adoc
=> Add changelog for ee-multicloud:v0.0.12

ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_data_foundation/files/create_acm_application.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_gitops/files/create_acm_application.yml
=> Fix variable issue

ansible/roles_ocp_workloads/ocp4_workload_3scale_workshop/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_3scale_workshop/templates/microcks-install.yaml.j2
item deployment is currently failing caused by the microcks operator update.
ocp4_3scale_workshop
=> fixing microcks deployment failure caused by operator update

ansible/configs/devsecops-vld-framework-binder/post_software.yml, ansible/configs/devsecops-vld-framework-binder/requirements.yml
Included one external ocp_application_validation role to validate argocd, rhacm or fire & forget kind of deployed application.
=> Include validation

ansible/configs/osp17-director-deployment/test.yml
Update bastion in test.yaml to have root permission while executing the task
=> updated file test.yaml

ansible/configs/osp17-director-deployment/test.yml
Update bastion in test.yaml to provide correct key location
=> Updated test.yaml as per new error log

ansible/configs/devsecops-vld-framework-binder/requirements.yml
Fixed typo in requirements.yml
config: devsecops-vld-framwork-binder
=> Fixed role parameter

ansible/configs/osp17-director-deployment/requirements.txt
Updated openstack.cloud version to resolve auto-stop issue
=> updated openstack.cloud package version

ansible/configs/expanding-workload-rhel/image_builder_repos.yml
Updated setup playbook for bastion reboot and starting cockpit
```paste below
```
=> Update Expanding workload to cloud cockpit setup

ansible/configs/devsecops-vld-framework-binder/import_clusters_to_hub.yaml, ansible/configs/devsecops-vld-framework-binder/post_software.yml
Replaced manual application validation tasks with ocp_application_validation role
config: devsecops-vld-framwork-binder
=> adding validation role

ansible/configs/devsecops-vld-framework-binder/import_clusters_to_hub.yaml
fixed indentation for validation 
=> indentation fix

ansible/configs/devsecops-vld-framework-binder/post_software.yml
Included api_version for ArgoCD in ocp_application_validation variable.
=> include api_version for argocd

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/pre_workload.yml
=> Clean up pre and post workload

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
SUMMARY
Removes a duplicated task
ISSUE TYPE
COMPONENT NAME
ADDITIONAL INFORMATION
cc/ @mvazquezc
=> Removes a duplicated task causing failure

ansible/roles-infra/infra-images/defaults/main.yaml
Adding RHEL87GOLD-LATEST IMAGE
=> Commit new RHEL87GOLD Image

ansible/configs/expanding-workload-rhel/image_builder_repos.yml
Needed to hard code file path
```paste below
```
=> fix file paths

ansible/configs/expanding-workload-rhel/image_builder_repos.yml
Fixes broken service on startup
```paste below
```
=> Update expanding workload for broken service

ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/certmanager/placementbinding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/certmanager/placementrule.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/certmanager/policy.yaml.j2
Added a few configuration flags (quota, cert manager) to hypershift workload.
=> Added config flags to hypershift workload

ansible/configs/devsecops-vld-framework-binder/import_clusters_to_hub.yaml, ansible/configs/devsecops-vld-framework-binder/post_software.yml
only updated validation variables
=> update validation variables

ansible/configs/ent-demo-ate-base/default_vars.yml, ansible/configs/ent-demo-ate-base/post_software.yml
Minor fix for ent-demo-ate-base
- turn of podman, not currently needed
- refactor user info/date, unnecessary complexity
config ent-demo-ate-base
=> Turn off Podman fix and refactor ent-demo-ate-base

ansible/configs/ent-demo-ate-base/post_software.yml
Prior fix was rushed and included new type
Fix bad var in ent-demo-ate-base post_software.yml
config ent-demo-ate-base
=> Fix a truncated prior fix, bad var in ent-demo-ate-base

ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> Add conditions for storage cluster

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/create_hypershift_cluster.yml
hypershift CLI failed with no CRD registered. Add check to wait for CRD to be registered.
=> Add check for HostedCluster CRD

ansible/configs/rosa-manual/.yamllint, ansible/configs/rosa-manual/README.adoc, ansible/configs/rosa-manual/default_vars.yml, ansible/configs/rosa-manual/default_vars_ec2.yml, ansible/configs/rosa-manual/destroy_env.yml, ansible/configs/rosa-manual/files/cloud_providers/ec2_cloud_template.j2, ansible/configs/rosa-manual/post_infra.yml, ansible/configs/rosa-manual/post_software.yml, ansible/configs/rosa-manual/pre_infra.yml, ansible/configs/rosa-manual/pre_infra_ec2.yml, ansible/configs/rosa-manual/pre_software.yml, ansible/configs/rosa-manual/requirements.yml, ansible/configs/rosa-manual/software.yml, ansible/configs/rosa-manual/templates/bastion_ssh_config.j2, ansible/configs/rosa/action_plugins
Create new rosa manual install config.  This gets ROSA CLI installed and ROSA login run but does not install the cluster.
rosa-manual-install
```paste below
```
=> Rosa manual install

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_acm_requirements.yml
=> Missed the namespace variable

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/create_hypershift_cluster.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/get_cluster_credentials.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/workload.yml
More logic updates and safety checks for Hypershift deployed clusters. Also change logic to find the names of kubeadmin password and kubeconfig from the hosted cluster instead of just assuming.
=> More Hypershift updates for 2.7

ansible/configs/devsecops-vld-framework-binder/post_software.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_acm_requirements.yml
=> Add virtual environment before querying Kubernetes
