- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/defaults/main.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/readme.adoc
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/main.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/post_remove_workload.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/post_workload.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/pre_remove_workload.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tasks/workload.yml
- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/tests/test-local.yml
Workload for RHTE19 lab "Build an operator"
ocp4-workload-build-an-operator-homeroomlab
This role deploys the build an operator workshop homeroom lab
> Lab build an operator for RHTE19

- ansible/configs/aro/README.adoc
- ansible/configs/aro/destroy_env.yml
- ansible/configs/aro/post_software.yml
- ansible/configs/aro/software.yml
- ansible/configs/ocp-workshop/post_software.yml
Addes Post-Software check completed output to ARO and OCP-Workshop config
ARO and OCP-Workshop
N/A
> Adding Post-Software output line to ARO and OCP-Workshop config

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/readme.adoc
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/tasks/post_workload.yml
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/tasks/workload.yml
ocp4-workload-rhte-kubefed-app-portability role update
```paste below
```
> rhte update

- ansible/roles/ocp4-workload-open-data-hub/readme.adoc
- ansible/roles/ocp4-workload-open-data-hub/tasks/per_user_workload.yml
- ansible/roles/ocp4-workload-open-data-hub/tasks/post_workload.yml
- ansible/roles/ocp4-workload-open-data-hub/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-open-data-hub/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-open-data-hub/tasks/workload.yml
Now doing multi-user deployments
Prints routes for each user,
Each user has their own AccessKey and SecretKey
**Accepts -e"num_users=NN"**
ocp4-workload-open-data-hub
```paste below
```
> ODH Multi-user

- ansible/roles/ocp4-workload-ceph/defaults/main.yml
- ansible/roles/ocp4-workload-ceph/tasks/post_workload.yml
- ansible/roles/ocp4-workload-ceph/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-ceph/templates/operator-openshift-with-csi.yaml.j2
Adds new configuration options to Ceph workload
> ocp4-workload-ceph : New configuration options

- ansible/roles/ocp4-workload-open-data-hub/defaults/main.yml
- ansible/roles/ocp4-workload-open-data-hub/tasks/pre_workload.yml
Debug user_count and remove default
```paste below
```
> Debug user_count and remove default

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/tasks/post_workload.yml
Fixes a permission problem
```paste below
```
> small permissions fix

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/tasks/post_workload.yml
User group was incorrect, changed to users
```paste below
```
> Change to correct group

- ansible/roles/ocp4-workload-ceph/defaults/main.yml
- ansible/roles/ocp4-workload-ceph/files/cephfs/csi-node-plugin-psp.yaml
- ansible/roles/ocp4-workload-ceph/files/cephfs/csi-nodeplugin-rbac.yaml
- ansible/roles/ocp4-workload-ceph/files/cephfs/csi-provisioner-psp.yaml
- ansible/roles/ocp4-workload-ceph/files/cephfs/csi-provisioner-rbac.yaml
- ansible/roles/ocp4-workload-ceph/files/rbd/csi-node-plugin-psp.yaml
- ansible/roles/ocp4-workload-ceph/files/rbd/csi-provisioner-psp.yaml
- ansible/roles/ocp4-workload-ceph/tasks/post_workload.yml
- ansible/roles/ocp4-workload-ceph/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-ceph/tasks/workload.yml
- increased timeout values for Mon pods. 
- new validations around Ceph PVCs before removing Ceph
- addressed Ansible deprecation warnings with bool vars
> ocp4-workload-ceph : Increased timeouts, validations for Ceph PVCs

- ansible/roles/ocp4-workload-open-data-hub-infra/defaults/main.yml
- ansible/roles/ocp4-workload-open-data-hub-infra/readme.adoc
- ansible/roles/ocp4-workload-open-data-hub-infra/tasks/main.yml
- ansible/roles/ocp4-workload-open-data-hub-infra/tasks/post_workload.yml
- ansible/roles/ocp4-workload-open-data-hub-infra/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-open-data-hub-infra/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-open-data-hub-infra/tasks/workload.yml
- ansible/roles/ocp4-workload-open-data-hub-student/defaults/main.yml
- ansible/roles/ocp4-workload-open-data-hub-student/readme.adoc
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/main.yml
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/post_workload.yml
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/workload.yml
Uses multiple role strategy to create open-data-hub deployment.
Can replace ocp4-workload-open-data-hub
ocp4-workload-open-data-hub-infra
ocp4-workload-open-data-hub-student
```paste below
```
> ODH multi-role

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/files/gen-mongo-certs
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/files/init-lab
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/files/namespace-cleanup
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/files/wait-for-deployment
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/tasks/workload.yml
Added helper scripts that will be used during the lab
```paste below
```
> Added helper scripts

- ansible/roles/ocp4-workload-open-data-hub-student/readme.adoc
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-open-data-hub-student/tasks/workload.yml
replace student_name with ocp_username
picked wrong variable previously
ocp4-workload-open-data-hub-student
```paste below
```
> replace student_name with ocp_username

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/files/gen-mongo-certs
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/files/namespace-cleanup
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/files/wait-for-mongo-replicaset
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/tasks/workload.yml
Fixed typo + added a new mongo helper script
```paste below
```
> Fixed typo + added mongo helper script

- ansible/roles/ocp-workload-edge-deployments/tasks/pre_workload.yml
- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
FIXES: add delegate_to to every tasks (also for oc commands)
add delegate_to to every tasks (also for oc commands)
```
> add delegate_to to every tasks (also for oc commands)

- ansible/roles/ocp-workload-edge-deployments/tasks/pre_workload.yml
- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
bug fixing - sintax error due to wrong ','
fixing wrong ',' on workload.yml
> bug fixing - sintax error due to wrong ','

- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
rebasing on redhat-cop/agnosticd development branch
> Update workload.yml after rebasing 

- ansible/roles/ocp-workload-dekorate-component-operator/defaults/main.yml
- ansible/roles/ocp-workload-dekorate-component-operator/files/capability_v1alpha2.yml
- ansible/roles/ocp-workload-dekorate-component-operator/files/component_v1alpha2.yml
- ansible/roles/ocp-workload-dekorate-component-operator/files/link_v1alpha2.yml
- ansible/roles/ocp-workload-dekorate-component-operator/files/sa.yml
- ansible/roles/ocp-workload-dekorate-component-operator/files/user-rbac.yml
- ansible/roles/ocp-workload-dekorate-component-operator/it.sh
- ansible/roles/ocp-workload-dekorate-component-operator/readme.adoc
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/helm.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/kubedb.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/main.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/operator.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/post_workload.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/pre_workload.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/remove_workload.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/tekton.yml
- ansible/roles/ocp-workload-dekorate-component-operator/tasks/workload.yml
- ansible/roles/ocp-workload-dekorate-component-operator/templates/cluster-rbac.j2
- ansible/roles/ocp-workload-dekorate-component-operator/templates/operator.j2
- ansible/roles/ocp-workload-dekorate-component-operator/templates/pvc.yml.j2
- ansible/roles/ocp-workload-dekorate-component-operator/templates/tiller-rbac.yml.j2
- ansible/roles/ocp-workload-dekorate-component-operator/templates/values.yml.j2
Add new role for the RHTE Lab (S2026)
> Add new role for the RHTE Lab (S2026)

- ansible/roles/ocp-workload-mssql/defaults/main.yml
- ansible/roles/ocp-workload-mssql/tasks/pre_workload.yml
- ansible/roles/ocp-workload-mssql/tasks/workload.yml
- ansible/roles/ocp-workload-mssql/templates/manifest.yaml.j2
- ansible/roles/ocp-workload-parks-app/README.adoc
- ansible/roles/ocp-workload-parks-app/defaults/main.yml
- ansible/roles/ocp-workload-parks-app/tasks/main.yml
- ansible/roles/ocp-workload-parks-app/tasks/post_workload.yml
- ansible/roles/ocp-workload-parks-app/tasks/pre_workload.yml
- ansible/roles/ocp-workload-parks-app/tasks/remove_workload.yml
- ansible/roles/ocp-workload-parks-app/tasks/workload.yml
- ansible/roles/ocp-workload-robot-shop/README.adoc
- ansible/roles/ocp-workload-robot-shop/defaults/main.yml
- ansible/roles/ocp-workload-robot-shop/tasks/main.yml
- ansible/roles/ocp-workload-robot-shop/tasks/post_workload.yml
- ansible/roles/ocp-workload-robot-shop/tasks/pre_workload.yml
- ansible/roles/ocp-workload-robot-shop/tasks/remove_workload.yml
- ansible/roles/ocp-workload-robot-shop/tasks/workload.yml
- ansible/roles/ocp-workload-sock-shop/README.adoc
- ansible/roles/ocp-workload-sock-shop/defaults/main.yml
- ansible/roles/ocp-workload-sock-shop/tasks/main.yml
- ansible/roles/ocp-workload-sock-shop/tasks/post_workload.yml
- ansible/roles/ocp-workload-sock-shop/tasks/pre_workload.yml
- ansible/roles/ocp-workload-sock-shop/tasks/remove_workload.yml
- ansible/roles/ocp-workload-sock-shop/tasks/workload.yml
New demo apps custom built for OpenShift 3 and 4, intended to demo migrations using the Cluster Application Migration Tool workload. 
- Sock Shop App : Micro services demo e-commerce store that sells socks. (Stateful)
- Robot Shop App : An e-commerce store that sells robots and AI tech. (Stateful)
- Parks App : A web application that visualizes Historic Places and Monuments on maps. (Stateless)
Updating existing MsSQL app 
- ocp-workload-robot-shop
- ocp-workload-sock-shop
- ocp-workload-parks-app
- ocp-workload-mssql
> New sample apps for migration demos

- ansible/roles/ocp4-workload-ccnrd/README.adoc
- ansible/roles/ocp4-workload-ccnrd/defaults/main.yml
- ansible/roles/ocp4-workload-ccnrd/tasks/main.yml
- ansible/roles/ocp4-workload-ccnrd/tasks/post_workload.yml
- ansible/roles/ocp4-workload-ccnrd/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-ccnrd/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
> Add Hands-On Lab for Advanced Cloud-Native App Development for RHTE 2019

- ansible/roles/ocp4-workload-rhte-a0009/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-a0009/readme.adoc
- ansible/roles/ocp4-workload-rhte-a0009/tasks/main.yml
- ansible/roles/ocp4-workload-rhte-a0009/tasks/post_workload.yml
- ansible/roles/ocp4-workload-rhte-a0009/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-rhte-a0009/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-rhte-a0009/tasks/workload.yml
- ansible/roles/ocp4-workload-rhte-a0009/templates/crd.j2
- ansible/roles/ocp4-workload-rhte-a0009/templates/opentlc-workshop.j2
- ansible/roles/ocp4-workload-rhte-a0009/templates/operator.j2
- ansible/roles/ocp4-workload-rhte-a0009/templates/project.j2
- ansible/roles/ocp4-workload-rhte-a0009/templates/role.j2
- ansible/roles/ocp4-workload-rhte-a0009/templates/role_binding.j2
- ansible/roles/ocp4-workload-rhte-a0009/templates/service_account.j2
> Added Roles for the A0009 RHTE Lab

- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/Dockerfile
- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/apb.yml
- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/playbooks/deprovision.yml
- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/playbooks/provision.yml
- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
update apb to use ec2_user as remote_user  and become:true
fix id_rsa missing on DockerFile
update default remote host where containers will be deployed by APB
> Update APB configuration 

- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
Adds new tasks for migration configuration
```paste below
```
> New settings for migration tool configuration

- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/apb.yml
- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/playbooks/provision.yml
fix remote_user on provision.yml + bug fixing
> fix remote_user on provision.yml + bug fixing

- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/playbooks/provision.yml
generate new ssh key file inside provision.yml
-Bug Fix Pull Request
```
> generate new ssh key file inside provision.yml

- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/defaults/main.yml
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/files/codeready-workspaces-operator-installer/README.adoc
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/files/codeready-workspaces-operator-installer/custom-resource.yaml
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/files/codeready-workspaces-operator-installer/deploy.sh
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/files/codeready-workspaces-operator-installer/deploy.sh.orig
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/files/codeready-workspaces-operator-installer/migrate_1.0_to_1.1.sh
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/files/codeready-workspaces-operator-installer/migrate_1.1_to_1.2.sh
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/readme.adoc
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/tasks/main.yml
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/tasks/post_workload.yml
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/tasks/wait_for_build.yml
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/tasks/wait_for_deploy.yml
- ansible/roles/ocp4-workload-rhte19-optaplanner-101-lab-infra/tasks/workload.yml
RHTE OptaPlanner Lab
ocp4-workload-rhte19-optaplanner-101-lab-infra
n.a.
> Initial import of RHTE19-OptaPlanner lab OCP4 environment.

- ansible/roles/ocp-workload-parks-app/README.adoc
- ansible/roles/ocp-workload-robot-shop/README.adoc
Updated Readmes
ocp-workload-robot-shop
ocp-workload-parks-app
```paste below
```
> Demo Apps : Readme updates

- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/Dockerfile
- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/playbooks/provision.yml
- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
ssh key generation on master + authorizing it on bastion and use inside apb container 
```
> ssh key generation on master + authorizing it on bastion and use inside apb container 

- ansible/roles/ocp4-workload-istio-controlplane/readme.adoc
- ansible/roles/ocp4-workload-istio-controlplane/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-istio-controlplane/tasks/workload.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin/defaults/main.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin/readme.adoc
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin/tasks/clean-environment.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin/tasks/main.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin/tasks/post_workload.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin/tasks/workload.yml
Miastra (service mesh/istio) Tech Preview 12
Add homeroom role
Updated roles
ocp4-workload-istio-controlplane
New Role
ocp4-workload-workshop-dashboard-cluster-admin
```paste below
```
> Service mesh Tech Preview 12 + Homeroom Cluster Admin Role

- ansible/roles/ocp-workload-mssql/tasks/workload.yml
- ansible/roles/ocp4-workload-operator-mssql/README.adoc
- ansible/roles/ocp4-workload-operator-mssql/defaults/main.yml
- ansible/roles/ocp4-workload-operator-mssql/tasks/main.yml
- ansible/roles/ocp4-workload-operator-mssql/tasks/post_workload.yml
- ansible/roles/ocp4-workload-operator-mssql/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-operator-mssql/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-operator-mssql/tasks/workload.yml
- ansible/roles/ocp4-workload-operator-mssql/templates/manifest.yaml.j2
- ansible/roles/ocp4-workload-operator-mssql/templates/marketplace.yaml.j2
- ansible/roles/ocp4-workload-operator-mssql/templates/namespace.yaml.j2
Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>
Adds a new workload for MsSQL operator. The operator manages a replicated MsSQL deployment.
ocp4-workload-operator-mssql
```paste below
```
> MsSQL Operator Workload 

- ansible/roles/ocp-workload-integreatly-rhte-2019-lab/readme.adoc
- ansible/roles/ocp-workload-integreatly-rhte-2019-lab/tasks/create-tenants.yml
Removes unnecessary step from workload. Fixes readme error.
`ocp-workload-integreatly-rhte-2019-lab`
> Fixes for ocp-workload-integreatly-rhte-2019-lab 

- ansible/roles/ocp4-workload-operator-mssql/tasks/workload.yml
Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>
Fixes in Operator Mssql worklaod
ocp4-workload-operator-mssql
```paste below
```
> Fixes in Operator MsSQL workload

- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/playbooks/provision.yml
- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
fixed conflict files 
rebase + merging on:
ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/playbooks/provision.yml
as stated on https://github.com/redhat-cop/agnosticd/pull/595
```
> fixed conflict files 

- ansible/roles/ocp4-workload-istio-controlplane/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-istio-controlplane/tasks/workload.yml
- ansible/roles/ocp4-workload-istio-tutorial/readme.adoc
- ansible/roles/ocp4-workload-istio-tutorial/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-istio-tutorial/tasks/workload.yml
- ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin/tasks/workload.yml
Enable multitenancy in ServiceMesh components in a workshop.
ocp4-workload-istio-controlplane
ocp4-workload-istio-tutorial
ocp4-workload-workshop-dashboard-cluster-admin
```paste below
```
> Enable multitenancy in ServiceMesh components in a workshop.

- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
use openssh_keypair, fixing typo, merge with upstream redhat-cop
> use openssh_keypair, fixing typo, merge with upstream redhat-cop

- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
> fixing path on dir creation

- ansible/roles/ocp4-workload-quarkus-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-quarkus-workshop/files/cm-custom-codeready.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/codeready.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/codeready_catalog_source.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/codeready_namespace.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/codeready_operatorgroup.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/codeready_subscription.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/quarkus-realm.json
- ansible/roles/ocp4-workload-quarkus-workshop/files/stack.json
- ansible/roles/ocp4-workload-quarkus-workshop/files/strimzi_catalog_source.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/strimzi_subscription.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/files/workspace.json
- ansible/roles/ocp4-workload-quarkus-workshop/readme.adoc
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/create_che_workspace.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/create_project.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/main.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/templates/che-limitrange.j2
- ansible/roles/ocp4-workload-quarkus-workshop/templates/che-user.j2
- ansible/roles/ocp4-workload-quarkus-workshop/templates/stack.imagestream.j2
Introduce a new workload for a full-day Quarkus workshop based on OCP 4, CodeReady, and Quarkus.
This role is expected to be run against an existing OCP 4 cluster with `user_count` number of users already created in OCP, and will do the following:
1. Create per-user namespaces (OCP projects)
1. Deploy workshopper guides
1. Install CodeReady via its operator
1. Workaround CodeReady bugs on OCP 4 (persistent volume config, elastic load balancer conflict)
1. Configure keycloak for workshop
1. Configure codeready for workshop
1. Install Strimzi via its operator
> Quarkus workshop

- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
fix id_rsa.pub key + use guid variable on master .pem file->
> fix id_rsa.pub key + use guid variable on master .pem file

- ansible/roles/ocp4-workload-ml-workflows-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/files/workshop-resources.yaml
- ansible/roles/ocp4-workload-ml-workflows-workshop/readme.adoc
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/main.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/post_workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/tasks/workload.yml
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/custom-notebook-destination-imagestream.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/custom-notebook-imagestream.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/pipeline-buildconfig.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/pipeline-deploymentconfig.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/pipeline-imagestream.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/pipeline-s2i-imagestream.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/pipeline-service.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/python36-imagestream.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/workshop-notebook-buildconfig.yaml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/workshop-notebook-imagestream.yaml.j2
This is a role for the ML Workflows Workshop at RHTE.  This pull request depends on #569
- `ansible/roles/ocp4-workload-ml-workflows-workshop`
Task order should be
* `ocp4-workload-rhte-analytics_data_ocp_infra` Run once per cluster, defining `jupyter_notebook_memory=6Gi` and `deploy_odh_cr=true`
* `ocp4-workload-rhte-analytics_data_ocp_workshop` Run once per user in the class, supply the name of the OCP user with the variable `user_name`, and supply the user's project name in the variable `project_name`; also define `jupyter_notebook_memory=6Gi` and `deploy_odh_cr=true`.
* `ocp4-workload-ml-workflows-workshop` with the name of the OCP user with the variable `user_name` and the user's project name in the variable `project_name`.
> RHTE ML Workflows Workshop

- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
fixing guid on "add new ssh-key as authorized on BASTION host" task
```
> fixing guid on "add new ssh-key as authorized on BASTION host" task

- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
- ansible/roles/ocp-workload-migration/tasks/workload.yml
Getting new changes in migration operator which this workload depends on. 
```paste below
```
> ocp-workload-migration : Sync with latest changes in operator

- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/Dockerfile
> update id_rsa to id_rsa.pub

- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
copy id_rsa.pub and id_rsa to BASTION host on /tmp/{{guid}}
>  copy id_rsa.pub and id_rsa to BASTION host on /tmp/{{guid}}

- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/tasks/pre_workload.yml
Added retries to the synchronize task.
ocp-workload-rhte19-optaplanner-101-lab-infra
n.a.
> Added retries to rsync.

- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
> fixing typo

- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/Dockerfile
- ansible/roles/ocp-workload-edge-deployments/tasks/pre_workload.yml
- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
> Fixing Dockerfile 

- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/Dockerfile
- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/playbooks/provision.yml
- ansible/roles/ocp-workload-edge-deployments/tasks/workload.yml
fix various stuff for apb container
> fix various stuff for apb container 

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/tasks/workload.yml
Added retries for argocd deployment
```paste below
```
> Added retries

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/templates/argocd_install.j2
Add route creation for argocd
```paste below
```
> Add route creation for argocd

- ansible/configs/README.adoc
Hello, I am new to this community. I found a broken link, and fixed it. Please review.
> Fixing broken link in docs

- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/playbooks/deprovision.yml
- ansible/roles/ocp-workload-edge-deployments/files/deploy-containers-apb/playbooks/provision.yml
- ansible/roles/ocp-workload-edge-deployments/files/project-iot-development.yaml
> Fixing issue on ansible edge role

- ansible/roles/ocp-workload-migration/tasks/post_workload.yml
- ansible/roles/ocp-workload-migration/templates/migstorage.yaml.j2
- ansible/roles/ocp4-workload-noobaa/README.adoc
- ansible/roles/ocp4-workload-noobaa/defaults/main.yml
- ansible/roles/ocp4-workload-noobaa/tasks/main.yml
- ansible/roles/ocp4-workload-noobaa/tasks/post_workload.yml
- ansible/roles/ocp4-workload-noobaa/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-noobaa/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-noobaa/tasks/workload.yml
- Added new workload to deploy NooBaa on OCP4 cluster. 
- Added default storage in migration workload to use NooBaa backend
ocp4-workload-noobaa (new)
ocp-workload-migration 
```paste below
```
> New workload for NooBaa operator

- ansible/configs/rhte-ans-tower/tower_workloads.yml
> infra_workload block deleted deleted

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/files/verify-contexts
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/tasks/workload.yml
Added a helper script that checks context creation
```paste below
```
> Added another helper script

- ansible/roles/ocp-workload-migration/tasks/post_workload.yml
> Fix for migration workload when NooBaa hasn't been installed

- ansible/roles/ocp-workload-integreatly-rhte-2019-lab/readme.adoc
- ansible/roles/ocp-workload-integreatly-rhte-2019-lab/tasks/create-tenants.yml
Adding a developer tenant URL for this lab.
> fix: add developer tenant back to rhte rhmi lab

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_infra/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_infra/tasks/workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/per_user_workload.yml
Fixes issues in RHTE Data Analytics Workshop
- Resolve possible error during infra workload run where /tmp/osrcp*json file needs to be manually removed with sudo
- Remove LimitRange from user projects
- Add delay between retries when querying for pod status in project rook-ceph-system
Role ocp4-workload-rhte-analytics_data_ocp_infra
Role ocp4-workload-rhte-analytics_data_ocp_workshop
> RHTE data analytics - delete LimitRanges and /tmp/osrcp*

- ansible/roles/ocp-workload-rhte19-optaplanner-101-lab-infra/tasks/pre_workload.yml
Fix synchronize
ocp-workload-rhte19-optaplanner-101-lab-infra
n.a.
> Use SSH args in synchronize task.

- ansible/roles/ocp4-workload-quarkus-workshop/readme.adoc
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
Adds `aws_region` ansible variable to be used when configuring ELB.
This replaces the hard-coded region name in `workload.yml`
> parameterize aws_region

- ansible/roles/infra-aws-get-sandbox/defaults/main.yaml
- ansible/roles/infra-aws-get-sandbox/readme.adoc
- ansible/roles/infra-aws-get-sandbox/tasks/get.yaml
- ansible/roles/infra-aws-get-sandbox/tasks/main.yaml
- ansible/roles/infra-aws-get-sandbox/tasks/pre_checks.yaml
- ansible/roles/infra-aws-get-sandbox/tasks/unvault.yml
- ansible/roles/infra-aws-release-sandbox/defaults/main.yaml
- ansible/roles/infra-aws-release-sandbox/readme.adoc
- ansible/roles/infra-aws-release-sandbox/tasks/main.yml
- ansible/roles/infra-aws-release-sandbox/tasks/pre_checks.yaml
- ansible/roles/infra-aws-release-sandbox/tasks/profile.yaml
- ansible/roles/infra-aws-release-sandbox/tasks/release.yaml
- ansible/roles/infra-aws-release-sandbox/tests/test-get-release-sandbox.yml
- ansible/roles/infra-aws-sandbox/README.adoc
- ansible/roles/infra-aws-sandbox/defaults/main.yml
- ansible/roles/infra-aws-sandbox/tasks/ipa.yml
- ansible/roles/infra-aws-sandbox/tasks/pre_checks.yml
- ansible/roles/infra-aws-sandbox/tasks/reset.yml
- ansible/roles/infra-aws-sandbox/tasks/test_ipa.yml
Create roles to get-sandbox and release-sandbox
```paste below
```
> Add get-sandbox and release-sandbox roles

- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
Added new tasks to download all scripts from mig-agnosticd repo instead of just cors script
```paste below
```
> Fixes in migration workload

- ansible/roles/ocp4-workload-noobaa/tasks/remove_workload.yml
> Fixed typo in removal of NooBaa workload

- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
Fixes issue with missing user on deployer host
```paste below
```
> Migration : delegating tasks to bastion host

- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
Downloading CPMA binary on bastion host
```paste below
```
> Migration Workload : Downloading CPMA binary on bastion host

- ansible/roles/ocp-workload-integreatly-iot/tasks/workload.yml
Try fixing the "missing file" deployment issue.
ocp-workload-integreatly-iot
> Try fixing missing file issues during deployment

- ansible/roles/ocp-workload-integreatly/tasks/workload.yml
Added retry to a failing task, as suggested by @fridim in the chat.
ocp-workload-integreatly / workload.yml
> Add retry as requested in chat

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
Add `user.info` debug output to include in resulting emails for provisioning
> add userinfo

- ansible/roles/ocp-workload-integreatly-iot/files/010-CustomResourceDefinition-iot-project.yaml
- ansible/roles/ocp-workload-integreatly-iot/files/010-ServiceAccount-iot-operator.yaml
- ansible/roles/ocp-workload-integreatly-iot/files/020-ClusterRole-iot-operator.yaml
- ansible/roles/ocp-workload-integreatly-iot/files/020-ClusterRole-iot-tenant-edit.yaml
- ansible/roles/ocp-workload-integreatly-iot/files/020-ClusterRole-iot-tenant-view.yaml
- ansible/roles/ocp-workload-integreatly-iot/files/020-ClusterRole-qdr-configurator.yaml
- ansible/roles/ocp-workload-integreatly-iot/files/030-ClusterRoleBinding-iot-operator.yaml
- ansible/roles/ocp-workload-integreatly-iot/files/050-Deployment-iot-operator.yaml
- ansible/roles/ocp-workload-integreatly-iot/tasks/workload.yml
Deploy the missing iot-operator.
ocp-workload-integreatly-iot
> Deploy the missing iot-operator

- ansible/roles/ocp4-workload-quarkus-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-quarkus-workshop/readme.adoc
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/remove_workload.yml
Use proper variable for # of participants (`num_users`), not number of openshift users created (`user_count`)
> use num_users instead user_count

- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
removing unnecessary extra directory
```paste below
```
> Migration Workload : remove extra directory

- ansible/roles/ocp-workload-dekorate-component-operator/defaults/main.yml
Bump version of halkyon operator to v0.1.5. #720
> Bump version of halkyon operator to v0.1.5.

- ansible/roles/ocp-workload-dekorate-component-operator/defaults/main.yml
Bump halkyon operator version to 0.1.7
> Bump halkyon operator version to 0.1.7

- ansible/roles/ocp4-workload-ccnrd/README.adoc
> ocp4-workload-ccnrd

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop_s2020/templates/opendatahub_v1alpha1_opendatahub_cr.yaml.j2
This commit fixes a minor misconfiguration for S2020 that we had to correct manually in APAC.
- `ocp4-workload-rhte-analytics_data_ocp_workshop_s2020`
> changes for RHTE NA

- ansible/roles/ocp-workload-developer-environment/tasks/post_workload.yml
- print NO SSH warning
- Print the API for oc login command
TASK0568652
> ocp-workload-developer-environment: add more user.info

- ansible/cloud_providers/none_infrastructure_deployment.yml
Just add a missing file for PR https://github.com/redhat-cop/agnosticd/pull/738
> Add missing file for ocp-workloads config

- ansible/configs/ocp4-workshop/files/kubelet-bootstrap-cred-manager-ds.yaml
> Updated Kube Cred Manager Daemon Set to support cluster shutdown

- ansible/configs/ocp4-workshop/files/kubelet-bootstrap-cred-manager-ds.yaml
> Fix kube cred manager

- ansible/configs/ocp-workloads/examples/cakephp-openshift-applier.yml
Create a rolebinding for the namespace instead.
> OpenShift Applier: don't use target_namespaces in example

- ansible/configs/three-tier-app/env_vars.yml
- ansible/configs/three-tier-app/pre_software.yml
> three-tier-app: load bastion-student-user role

- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/workload.yml
- ansible/roles/ocp4-workload-istio-controlplane-student/tasks/workload.yml
there were some issues in the istio control plane and student workload deployments - this is an attempt to fix them
> changes how deployments are verified

- ansible/roles/ocp4-workload-istio-workshop-homeroom/defaults/main.yml
- ansible/roles/ocp4-workload-istio-workshop-homeroom/readme.adoc
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/main.yml
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/post_workload.yml
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/workload.yml
adds the role to deploy homeroom specifically for the service mesh workshop
> adds homeroom for service mesh workshop

- ansible/roles/ocp4-workload-app-deploy-homework/defaults/main.yml
- ansible/roles/ocp4-workload-app-deploy-homework/tasks/post_workload.yml
- ansible/roles/ocp4-workload-app-deploy-homework/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-app-deploy-homework/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-app-deploy-homework/tasks/workload.yml
- ansible/roles/ocp4-workload-app-deploy-homework/templates/cluster_resource_quota.j2
- ansible/roles/ocp4-workload-app-deploy-homework/templates/jenkins_role_binding.j2
Updated workload for OCP 4 Advanced App Deploy Homework. Converted to k8s where possible, cleaned things up.
> Updated App Deploy Homework workload

- ansible/roles/ocp4-workload-ccnrd/files/preparelab_ccn.sh
Missing a `]` in two `elif` statements @danieloh30
```paste below
```
> Fix syntax error

- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/workload.yml
simple fix to some k8s_facts checks.
> forgot to change what we check for after changing what we deploy

- ansible/roles/ocp-workload-migration/README.adoc
- ansible/roles/ocp4-workload-ceph/README.adoc
Cleaned up doc to remove a bad reference
cc @newgoliath
> Removed a bad ref to nonexistent velero workload

- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/workload.yml
zeroing in on the right config...
> fixes mismatch in other operators

- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/defaults/main.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/readme.adoc
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/main.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/post_remove_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/post_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/pre_remove_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tests/test-local.yml
This workload adds a homeroom lab for OpenShift Pipelines (tekton) available at https://github.com/openshift-labs/lab-tekton-pipelines
> Added workload for tekton labs with homeroom

- ansible/roles/ocp4-workload-istio-controlplane-infra/tasks/workload.yml
the workshop was setting up es but wasn't using it, and it caused a problem, so I'm removing it.
> removes elasticsearch operator which is unused

- ansible/roles/ocp4-workload-project-request-template/tasks/workload.yml
Workaround for template(s) bug in openshift python module.
> Workaround for templates bug in openshift python module

- ansible/roles/ocp4-workload-quarkus-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-quarkus-workshop/files/stack.json
- ansible/roles/ocp4-workload-quarkus-workshop/files/workspace.json
Update to Quarkus 0.27
This updates the Che workspace to use a Quarkus 0.27-compatible stack definition.
> update to Quarkus 0.27

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_infra/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/readme.adoc
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/per_user_operator_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/templates/opendatahub-operator.v0.4.0.clusterserviceversion.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/templates/workshop-notebook-openshift-image.imagestreamtag.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/templates/workshop-notebook.imagestream.yaml.j2
Update roles for RHTE Analytics and Data Engineering Workshop
- ocp4-workload-rhte-analytics_data_ocp_infra
- ocp4-workload-rhte-analytics_data_ocp_workshop
RHTE Analytics and Data Engineering Workshop updates
Adding updates that were performed to the cluster that didn't make it into the RHTE final code freeze
Run the same deployment of the RHTE 2019 S1003 workshop
> Update RHTE S1003 Analytics Data Engineering Workshop

- ansible/roles/ocp4-workload-project-request-template/tasks/workload.yml
- ansible/roles/ocp4-workload-project-request-template/templates/project_request_template.j2
Needed to change Template as well...
> Fix project template

- ansible/configs/ocp-ha-disconnected-lab/env_vars.yml
- ansible/configs/ocp-ha-disconnected-lab/files/hosts_template.3.11.129.j2
- ansible/configs/ocp-ha-disconnected-lab/files/labs_hosts_template.3.11.129.j2
- ansible/configs/ocp-ha-lab/files/hosts_template.3.11.129.j2
Add missing nfs vars to env_vars
> Add 129 to ha lab

- ansible/configs/ans-tower-lab/env_vars.yml
- ansible/configs/ans-tower-lab/files/repos_template.j2
- ansible/configs/ans-tower-lab/sample_vars.yml
- ansible/roles/install-tower/tasks/install_tower.yml
own_repo_path is fixed
config ready to install the latest version of tower 3.5.3-1 for LAB
config ready to install latest tower version 3.5.3-1 for HW with the install-tower role
> repo path and 3.5.3-1 version

- ansible/configs/ocp-ha-disconnected-lab/env_vars.yml
Update Ansible for 2.8 in order to run FTL in this lab.
> Update Ansible to 2.8

- ansible/configs/ocp-ha-disconnected-lab/env_vars.yml
> Update ha lab

- ansible/configs/ocp-ha-disconnected-lab/env_vars.yml
- ansible/configs/ocp-ha-disconnected-lab/pre_software.yml
> Install Bastion for HA Lab (to get FTL etc.)

- ansible/configs/ocp-workshop/requirements.yml
> add FTL to ocp-workshop

- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-migration/tasks/workload.yml
fix bad variable name, simplify code
> Mig prod bugs

- ansible/roles/ocp-workload-migration/tasks/pre_workload.yml
- fix broken copy
- remove unnecessary ssh keys
> fix broken copy, remove unnecessary ssh keys

- ansible/configs/ocp4-disconnected-osp-lab/files/repos_template.j2
- ansible/configs/ocp4-disconnected-osp-lab/post_software.yml
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
- add more user.info
- add additional helper env vars
- add repo file jinja
> OpenStack config updates

- ansible/configs/ocp4-workshop/files/repos_template.j2
- ansible/configs/ocp4-workshop/files/run-openshift-install.j2
- ansible/configs/ocp4-workshop/software.yml
- ansible/roles/bastion/tasks/k8s.yml
- ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml
- ansible/roles/host-lets-encrypt-certs-certbot/templates/run-certbot.j2
- ansible/roles/ocp4-workload-aws-jumpbox/tasks/workload.yml
- ansible/roles/ocp4-workload-aws-jumpbox/templates/aws_inventory.yml
- ansible/roles/ocp4-workload-aws-jumpbox/templates/create_jumpbox.j2
- ansible/roles/ocp4-workload-aws-jumpbox/templates/create_jumpbox.yml
- ansible/roles/ocp4-workload-aws-jumpbox/templates/delete_jumpbox.j2
- ansible/roles/ocp4-workload-aws-jumpbox/templates/delete_jumpbox.yml
- ansible/roles/ocp4-workload-aws-jumpbox/templates/setup_jumpbox.j2
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/defaults/main.yml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/files/router-certs.j2
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/tasks/main.yml
- ansible/roles/ocp4-workload-enable-lets-encrypt-certificates/tasks/workload.yml
Add Pinned EPEL Repo to configured repositories (for openshift python library)
Set up Virtualenvs for the OpenShift Installer and Certbot
Change logic for installer and certbot to execute a shell script that activates the virtualenv first.
Fix AWS Jumpbox role
> Untangled Python dependency hell (hopefully)

- ansible/roles/ocp-workload-terminal/tasks/workload.yml
> Change logic to get  apps hostname suffix for oauth client

- ansible/configs/ocp-workshop/files/hosts_template.3.11.159.j2
> added new host template for 3.11.159

- ansible/configs/ocp4-disconnected-osp-lab/README.adoc
- ansible/configs/ocp4-disconnected-osp-lab/pre_software.yml
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
- Add GUID to /etc/skel/.bashrc
- Fix env vars added to .bashrc
> osp config fixes

- ansible/roles/ocp4-workload-homeroomlab-starter-guides/defaults/main.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/php-is.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/readme.adoc
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/deploy_workshop.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/extra
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/main.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/post_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/workload.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/templates/project.j2
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tests/test-local.yml
Infra type of workload to deploy the OCP starter-guides for OCP 4 to replace the APBs.
> Homeroomlab for Starter Guides all languages

- ansible/roles/ocp-workload-etherpad/defaults/main.yml
- ansible/roles/ocp-workload-etherpad/readme.adoc
- ansible/roles/ocp-workload-etherpad/tasks/main.yml
- ansible/roles/ocp-workload-etherpad/tasks/post_workload.yml
- ansible/roles/ocp-workload-etherpad/tasks/pre_workload.yml
- ansible/roles/ocp-workload-etherpad/tasks/remove_workload.yml
- ansible/roles/ocp-workload-etherpad/tasks/workload.yml
- ansible/roles/ocp-workload-etherpad/templates/configmap_app.j2
- ansible/roles/ocp-workload-etherpad/templates/deployment_app.j2
- ansible/roles/ocp-workload-etherpad/templates/deployment_mysql.j2
- ansible/roles/ocp-workload-etherpad/templates/etherpad.txt.j2
- ansible/roles/ocp-workload-etherpad/templates/project.j2
- ansible/roles/ocp-workload-etherpad/templates/pvc_mysql.j2
- ansible/roles/ocp-workload-etherpad/templates/route.j2
- ansible/roles/ocp-workload-etherpad/templates/secret_mysql.j2
- ansible/roles/ocp-workload-etherpad/templates/service_account.j2
- ansible/roles/ocp-workload-etherpad/templates/service_app.j2
- ansible/roles/ocp-workload-etherpad/templates/service_mysql.j2
- ansible/roles/ocp-workload-etherpad/tests/test-local.yml
Workload to deploy Etherpad for OpenSHift BU workshops moving from APBs
> Etherpad workload

- docs/Preparing_your_workstation.adoc
- tools/builds/Dockerfile-aws
- tools/builds/Dockerfile-aws-pypy
- tools/builds/readme.adoc
> Fix AWS docker image

- tools/builds/readme.adoc
Now that the images are built by quay, add a section to pull the images from
Quay.
> Update readme for docker images

- ansible/configs/ocp-workshop/files/ocp_report.adoc.j2
> OCP3 Workshop: Fix ocp report undefined variable error

- ansible/roles/ocp4-workload-homeroomlab-building-images/defaults/main.yml
- ansible/roles/ocp4-workload-homeroomlab-building-images/readme.adoc
- ansible/roles/ocp4-workload-homeroomlab-building-images/tasks/main.yml
- ansible/roles/ocp4-workload-homeroomlab-building-images/tasks/post_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-building-images/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-building-images/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-building-images/tasks/workload.yml
- ansible/roles/ocp4-workload-homeroomlab-building-images/tests/test-local.yml
New homeroom workshop for developing images using buildah and podman on OpenShift
> Workload for Building images with podman workshop

- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/deploy_workshop.yml
An update in original repo where a variable name was changed.
> Fixed name of variable project name when using scripts 2.x

- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/defaults/main.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/readme.adoc
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/post_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/workload.yml
- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tests/test-local.yml
Update to tekton lab 3.1 with scripts 2/x
> Tekton lab update

- ansible/roles/ocp4-workload-osevg-workshop-tracker/defaults/main.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/readme.adoc
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tasks/main.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tasks/post_workload.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tasks/workload.yml
- ansible/roles/ocp4-workload-osevg-workshop-tracker/tests/test-local.yml
Workload that adds tracking capabilities to know the cluster_name, cluster_version, workshop_type and number of users for OSEVG statistics.
> Workshop tracker for OSEVG team

- ansible/configs/ocp4-disconnected-osp-lab/files/general-ms.yaml.j2
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
For the Machine Managment lab, this jinja template is being added as a shortcut for people to use in an `ansible` command to create the yaml correctly.
> Add template for machinesets

- ansible/roles/ocp4-workload-build-an-operator-homeroomlab/defaults/main.yml
Released version 1.0 of workshop for RHPDS
> Update to 1.0 version of workshop for RHPDS

- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/defaults/main.yml
Workshop version has been updated to 3.2
> Update to newest version

- ansible/roles/ocp4-workload-homeroomlab-k8s-fundamentals/defaults/main.yml
- ansible/roles/ocp4-workload-homeroomlab-k8s-fundamentals/readme.adoc
- ansible/roles/ocp4-workload-homeroomlab-k8s-fundamentals/tasks/main.yml
- ansible/roles/ocp4-workload-homeroomlab-k8s-fundamentals/tasks/post_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-k8s-fundamentals/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-k8s-fundamentals/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-k8s-fundamentals/tasks/workload.yml
- ansible/roles/ocp4-workload-homeroomlab-k8s-fundamentals/tests/test-local.yml
Workshop for teaching Kubernetes fundamentals using OpenShift
> Workshop about k8s fundamentals

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/readme.adoc
> Closes #885

- ansible/roles/infra-osp-project-create/tasks/main.yaml
- ansible/roles/infra-osp-resources-destroy/tasks/main.yml
- ansible/roles/infra-osp-resources-destroy/tasks/project_resources.yml
- ansible/roles/infra-osp-template-generate/templates/cloud_template_master.j2
Changes required to be able to use an existing project and just create/destroy an heat template there.
> Be able to use OSP cloudprovider with osp_project_create = false

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/tasks/post_workload.yml
added setup git and tested the changes
> added setup git

- ansible/configs/ocp4-workshop/README.adoc
> Fix readme

- ansible/roles/infra-osp-create-inventory/tasks/main.yml
> Image ID is not always present depending on the python modules

- ansible/configs/ocp-clientvm/env_vars.yml
- ansible/configs/ocp-clientvm/files/cloud_providers/ec2_cloud_template.j2
> Fix clientvm imageid error

- README.adoc
- ansible/configs/multi-region-tower/env_vars.yml
- ansible/configs/multi-region-tower/files/hosts_template.j2
- ansible/configs/multi-region-tower/sample_vars_babylon.yml
- ansible/configs/multi-region-tower/tower_workloads.yml
Fixed regions and tested multi-region
> Multi region dt

- ansible/configs/ocp-workshop/env_vars.yml
- ansible/configs/ocp-workshop/files/htpasswd.openshift
- ansible/configs/ocp4-workshop/files/htpasswd.j2
- ocp-workshop
- ocp4-workshop
> Introduce new vars: nfs_volume_type (ocp3) and user_base_name (ocp*)

- .gitignore
- docs/First_OSP_Env_walkthrough.adoc
> Clarify which credentials to use for the Openstack UI.

- ansible/roles/infra-osp-wait_for_linux_hosts/tasks/main.yml
> Add sane defaults while waiting for hosts

- ansible/lifecycle.yml
And this one catches the r_instances var and pulls from ansible_facts with the module change.
> Change ansible_facts for r_instances

- ansible/lifecycle.yml
Last thing to remove from lifecycle - status confirmed locally.
> Remove flavor.original_name from status

- README.adoc
> README: Add link to Tony's video

- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-kubefed-app-portability/templates/argocd_install.j2
created a new argocd_install.j2 with the content from https://raw.githubusercontent.com/argoproj/argo-cd/v1.3.6/manifests/install.yaml
added to this
https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles/ocp4-workload-rhte-kubefed-app-portability/templates/argocd_install.j2#L2132
https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles/ocp4-workload-rhte-kubefed-app-portability/templates/argocd_install.j2#L1807-L1820
Route:
https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles/ocp4-workload-rhte-kubefed-app-portability/templates/argocd_install.j2#L2172-L2191
tested.
> upgrade argo

- ansible/roles/ocp-workload-rhte19-shadowman/defaults/main.yml
- ansible/roles/ocp-workload-rhte19-shadowman/tasks/post_workload.yml
Adding post_workload logging to be included in CloudForms notification email
> Adding post_workload logging

- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/files/pv-registry.yaml.j2
- ansible/configs/ocp4-disconnected-osp-lab/files/pv-user.yaml.j2
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
These changes will add:
- NFS configuration to utility VM for registry and user storage
- File to create registry PV
- File to create user PV
> Add NFS for ocp4 disconnected lab

- ansible/configs/three-tier-app/requirements.yml
Upgraded the version of ftl-injector used by config three-tier-app
three-tier-app is used as the test bed for FTL and changes are required for new FTL functionality in the **external** ftl-injector role
> Three tier app: upgrade ftl-injector version in config's requirements.yml

- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/files/pv-registry.yaml.j2
- ansible/configs/ocp4-disconnected-osp-lab/files/pv-user.yaml.j2
- ansible/configs/ocp4-disconnected-osp-lab/files/pvc-registry.yaml
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
- Add PVC file for image-registry-storage
- Fix the PV & PVC files to use different storageclass
- Add port to utility VM SG for NFSv4 ingress
- Fix the exports file to work more better with NFSv4
> NFS updates for ocp4-disco config

- ansible/roles/ocp4-workload-quay-operator/defaults/main.yml
- ansible/roles/ocp4-workload-quay-operator/templates/quay.j2
Update Operator to 1.0.1
Update Quay (Default) to 3.2.0
Add RepoMirroring for 3.2.0
Increase Memory Requests for 6Gi
> Update quay operator version

- ansible/roles/ocp4-workload-shared-cluster-access/README.adoc
- ansible/roles/ocp4-workload-shared-cluster-access/defaults/main.yml
- ansible/roles/ocp4-workload-shared-cluster-access/tasks/main.yml
- ansible/roles/ocp4-workload-shared-cluster-access/tasks/post_workload.yml
- ansible/roles/ocp4-workload-shared-cluster-access/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-shared-cluster-access/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-shared-cluster-access/tasks/workload.yml
- ansible/roles/ocp4-workload-shared-cluster-access/vars/main.yml
Add dedicated workload for OCP4 Shared Clusters.
> Add ocp4-workload-shared-cluster-access

- ansible/configs/three-tier-app/start.yml
- ansible/configs/three-tier-app/stop.yml
Created start.yml and stop.yml in three-tier-app config which starts and stops the env, These are similar playbook which are in multi-region-tower
> start and stop playbook added

- ansible/roles/ocp4-workload-quay-operator/templates/quay.j2
Add workaround for 0.0.5 operator (for labs)
> Workaround for old Quay Operator

- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
Updaed the `oc new-app` command to use the `{{ HOMEROOM_IMAGE }}` ansible variable
> Updated to use the HOMEROOM_IMAGE ansible variable

- ansible/roles/ocp4-workload-quay-operator/templates/crd.j2
> Update Quay CRD

- ansible/roles/ocp4-workload-workshop-admin-storage/tasks/workload.yml
Updating terminal image to use quay.io/openshiftroadshow/lab-ocp-ocs
> Updating terminal image

- ansible/configs/ans-tower-lab/requirements.yml
- ansible/configs/ansible-tower/requirements.yml
- ansible/configs/ansible-windows/requirements.yml
- ansible/configs/ocp-clientvm/requirements.yml
- ansible/configs/ocp-ha-disconnected-lab/requirements.yml
- ansible/configs/ocp-workshop/requirements.yml
- ansible/configs/ocp4-cluster/requirements.yml
- ansible/configs/ocp4-disconnected-osp-lab/env_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/files/pv-user.yaml.j2
- ansible/configs/ocp4-disconnected-osp-lab/requirements.yml
- ansible/configs/ocp4-ha-lab/requirements.yml
- ansible/configs/ocp4-shared/requirements.yml
- ansible/configs/ocp4-workshop/requirements.yml
- ansible/configs/rhte-ans-tower/requirements.yml
- ansible/configs/test-empty-config/requirements.yml
- ansible/configs/three-tier-app/requirements.yml
- Fix some files provided in ocp4-disco config
- Rev all configs that import ftl-injector to v0.16.0
> ftl-injector & ocp4-disco

- ansible/configs/ocp-ha-lab/files/hosts_template.3.11.153.j2
- ansible/configs/ocp-ha-lab/files/labs_hosts_template.3.11.153.j2
Saw an error in rhpds-admins mailing list that someone tried to deploy HA Lab 3.11.153. Not sure where that value came from in CloudForms..... but I added support for that release to the config.
> Added 3.11.153 templates for HA Lab

- ansible/configs/osp-migration/README.adoc
- ansible/configs/osp-migration/destroy_env.yml
- ansible/configs/osp-migration/dns_loop.yml
- ansible/configs/osp-migration/env_vars.yml
- ansible/configs/osp-migration/infra.yml
- ansible/configs/osp-migration/instance_loop.yml
- ansible/configs/osp-migration/post_infra.yml
- ansible/configs/osp-migration/post_software.yml
- ansible/configs/osp-migration/pre_infra.yml
- ansible/configs/osp-migration/pre_software.yml
- ansible/configs/osp-migration/requirements.yml
- ansible/configs/osp-migration/sample_vars.yml
- ansible/configs/osp-migration/software.yml
- ansible/configs/three-tier-app/sample_vars_osp.yml
- ansible/include_vars.yml
- ansible/main.yml
- ansible/roles/infra-osp-create-inventory/tasks/main.yml
ocp-migration
This config is use to deploy generated HEAT templates
The config uses its own `infra.yml` file, so  cloud_provider/osp*  are not used here.
> Osp migration bp

- ansible/roles/host-ocp-nfs/tasks/nfs_exports.yml
Fix deployment errors due to no facts being collected.
> Collect facts to fix error when using ansible_facts later

- ansible/configs/test-empty-config/post_software.yml
> empty-config: Add debug message expected by cloudforms

- ansible/roles/bastion/files/bastion_ssh_config.j2
- ansible/roles/set_env_authorized_key/files/host_ssh_config.j2
Roles updated bastion and set_env_authorized_key
Files changed 
ansible/roles/bastion/files/bastion_ssh_config.j2
ansible/roles/set_env_authorized_key/files/host_ssh_config.j2
> ssh_config template update for bastion and set_env_authorized_key roles

- ansible/roles/bastion/templates/bastion_ssh_config.j2
How has nobody fixed that yet?
> Fixed extra endif

- ansible/configs/test-empty-config/pre_software.yml
This message is expected by cloudforms
> Add debug message

- ansible/roles/ocp4-workload-homeroomlab-starter-guides/defaults/main.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/per_user.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/workload.yml
Updating the workload for the OpenShift 4 Getting Started workshop. These changes ensure that a Project and User are created for each user and that appropriate permissions are set. It also sets some settings that are necessary for the Nexus repo.
ocp4-workload-homeroom-starter-guides
> Updates to starter workshop for user permissions and Nexus fixes

- ansible/roles/ocp4-workload-quarkus-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
> Create a short version of Quarkus workshop

- README.adoc
tweak fo front page docs
```paste below
```
> front page docs tweak

- ansible/configs/osp-migration/infra.yml
After creating the environment, some servers have floating IP and security group allows access to some services. This pull request is to print how to access them.
> Adding user.info output to show how to access to the services

- ansible/configs/ansible-tower/env_vars.yml
- ansible/configs/ansible-tower/sample_vars.yml
- ansible/configs/ansible-tower/tower_workloads.yml
- ansible/roles/tower-custom-venv/defaults/main.yml
- ansible/roles/tower-custom-venv/readme.adoc
- ansible/roles/tower-custom-venv/tasks/loop.yml
- ansible/roles/tower-custom-venv/tasks/main.yml
Create a new tower infra-workload to support custom virtualenvs in tower
new variable: `tower_custom_virtualenvs`
The workload is not in the default workloads. It needs to be explicitly enabled.
tower-custom-venv
> Tower custom venv

- ansible/configs/just-some-nodes-example/destroy_env.yml
- ansible/configs/just-some-nodes-example/env_vars.yml
- ansible/configs/just-some-nodes-example/sample_vars_osp.yml
- ansible/roles/infra-common-ssh-config-generate/defaults/main.yml
- ansible/roles/infra-osp-template-generate/templates/cloud_template_master.j2
Prepare just-some-nodes-example for OSP
> Fix just some nodes osp

- ansible/configs/ocp-ha-lab/files/hosts_template.3.11.154.j2
- ansible/configs/ocp-ha-lab/files/labs_hosts_template.3.11.154.j2
lab is failing for students because of ruby version.  best to just upgrade to a recent release of ocp3
* add files to support 3.11.154
ocp-ha-lab
> allow ocp-ha-lab to 3.11.154

- ansible/configs/osp-migration/infra.yml
Add user.info: with the access info
> Fix user.info to include :

- ansible/roles/ocp-workload-bxms-pam-foundations/defaults/main.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/readme.adoc
- ansible/roles/ocp-workload-bxms-pam-foundations/tasks/main.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/tasks/post_workload.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/tasks/pre_workload.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/tasks/remove_workload.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/tasks/workload.yml
- ansible/roles/ocp-workload-bxms-pam-foundations/templates/rhpam-dev-businesscentral.yaml
- ansible/roles/ocp-workload-bxms-pam-foundations/templates/rhpam-dev-kieserver.yaml
The foundations course uses a subset of assets used in the advanced course. The new workload is suited for this purpose.
ocp-workload-bxms-pam-foundations
As per QA requirement each course will have its own entry and workload.
> separating foundations and advanced courses

- ansible/configs/test-empty-config/destroy_env.yml
- ansible/configs/test-empty-config/infra.yml
- ansible/roles/infra-aws-dry-run/tasks/cloudformation.yml
- ansible/roles/infra-aws-dry-run/tasks/ec2.yml
- ansible/roles/infra-aws-dry-run/tasks/main.yml
- ansible/roles/infra-osp-dry-run/defaults/main.yml
- ansible/roles/infra-osp-dry-run/tasks/main.yml
- ansible/roles/infra-osp-dry-run/templates/basic_heat_template.yml.j2
Use those 2 roles in test-empty-config depending on the variable cloud_provider
- role: infra-aws-dry-run
- role: infra-osp-dry-run
- config: test-empty-config
> Create 2 new roles: infra-aws-dry-run and infra-osp-dry-run

- ansible/roles/ocp4-workload-ccnrd/files/preparelab_ccn.sh
- ansible/roles/ocp4-workload-quarkus-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
> enforce knative-eventing 0.10.0 version

- ansible/roles/ocp4-workload-ceph/tasks/workload.yml
> Bug fix in Ceph workload

- ansible/configs/ocp4-workshop/pre_software.yml
Add selinux package to system python to fix selinux errors.
> Add selinux package to system python to fix selinux errors

- ansible/configs/osp-sandbox/README.adoc
Simple update to readme file.
osp-sandbox
> Readme update for osp-sandbox

- tools/find_ami.sh
Add rhel8.1 to `find_ami.sh`
also add profile
> Update find ami, add rhel8.1

- ansible/roles/tower-job-template-create/tasks/main.yml
default to 1
```paste below
```
> ansible-tower: Set fork when creating the job_template

- ansible/configs/ocp-ha-lab/files/hosts_template.3.11.154.j2
- ansible/configs/ocp-ha-lab/files/labs_hosts_template.3.11.154.j2
Fixes need in inventory for openshift_logging_es_pvc_dynamic=true even for NFS provisioning
ocp-ha-lab 3.11.154
You're looking lovely today.
> openshift_logging_es_pvc_dynamic=True now required

- ansible/configs/osp-sandbox/post_software.yml
Users who order this config should be using a different DNS domain. This PR will update the email to point them at the correct domain.
> Change user.info DNS zone

- ansible/configs/just-some-nodes-example/default_vars.yml
- ansible/configs/just-some-nodes-example/default_vars_azure.yml
- ansible/configs/just-some-nodes-example/default_vars_ec2.yml
- ansible/configs/just-some-nodes-example/default_vars_osp.yml
- ansible/configs/just-some-nodes-example/files/hosts_template.j2
- ansible/configs/just-some-nodes-example/sample_vars_osp.yml
- ansible/configs/test-empty-config/sample_vars_osp.yml
- docs/First_OSP_Env_walkthrough.adoc
- docs/Preparing_your_workstation.adoc
Improve just-some-nodes-example user experience.
- update Docs and first OSP deploy
- First_OSP_Env_walkthrough.adoc     updated to use the new catalog item
> [WIP] Improve just-some-nodes-example (OSP)

- ansible/configs/three-tier-app/pre_software.yml
FTL virtualenv breaking deploy
three tier app breaking in ftl-injector phase
Commented out ftl-injector play from pre_software.yml
> Removed ftl-injector play from pre_software.yml three-tier-app

- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/README.adoc
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/files/olm-operatorgroup/global.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/post_workload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_cluster.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_per_cluster_amqstreams.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_per_cluster_codereadyworkspaces.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_per_project_amqstreams.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_per_project_codereadyworkspaces.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_per_project_fuseworkload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/templates/amq-streams/cluster.j2
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/templates/amq-streams/topic.j2
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/templates/codeready-workspaces/workspace.j2
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/templates/olm-operatorgroup/group.j2
Moved amq streams and che to be cluster wide.
ocp4-workload-pam-fraudmanagement-workshop
Summit lab
> Updated amq-streams and crc to be central, 1 per cluster

- ansible/configs/ocp4-cluster/requirements.yml
- ansible/configs/ocp4-disconnected-osp-lab/requirements.yml
- ansible/configs/ocp4-ha-lab/requirements.yml
- ansible/configs/ocp4-shared/requirements.yml
- ansible/configs/ocp4-workshop/requirements.yml
Update ftl-injector tag for OCP4 configs from 0.16.0 to 0.17.0
> Update FTL-injector to v0.17.0

- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/cl-instance.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/clo-namespace.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/clo-og.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/clo-sub.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/eo-namespace.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/eo-og.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/eo-rb.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/eo-role.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/eo-sub.yml
- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/workload.yml
Add cluster logging to ocp4-workload-homeroomlab-starter-guides
> Add cluster logging to ocp4-workload-homeroomlab-starter-guides

- ansible/configs/ocp4-disconnected-osp-lab/software.yml
Cutting down the amount we deploy in the test for disconnected install.
> Remove lab 4 solver from config

- ansible/roles/ocp-workload-odo-workshop/files/tsb-instance.yml
- ansible/roles/ocp-workload-odo-workshop/files/tsb-namespace.yml
- ansible/roles/ocp-workload-odo-workshop/files/tsb-og.yml
- ansible/roles/ocp-workload-odo-workshop/files/tsb-sub.yml
- ansible/roles/ocp-workload-odo-workshop/tasks/workload.yml
Enable service catalog and template service broker for odo lab
ocp-workload-odo-workshop
> Enable service catalog and template service broker for odo lab

- ansible/roles/ocp4-workload-homeroomlab-starter-guides/files/clo-sub.yml
Update channel for cluster logging in ocp4 starter workshop
> Update channel for cluster logging

- ansible/configs/ocp4-disconnected-osp-lab/post_software.yml
Add return of user data in babylon anarchy callback.
> Return user data for ocp4-disconnected-osp-lab

- ansible/configs/ocp-ha-disconnected-lab/files/labs_hosts_template.3.11.154.j2
- ansible/configs/ocp-ha-disconnected-lab/files/labs_hosts_template.3.11.161.j2
- ansible/configs/ocp-ha-lab/files/hosts_template.3.11.161.j2
- ansible/configs/ocp-ha-lab/files/labs_hosts_template.3.11.161.j2
- ansible/configs/ocp-workshop/files/hosts_template.3.11.161.j2
Add support to deploy OCP 3.11.161
> Added 3.11.161 hosts files

- ansible/roles/ocp-workload-file-uploader/README.adoc
- ansible/roles/ocp-workload-file-uploader/defaults/main.yml
- ansible/roles/ocp-workload-file-uploader/tasks/main.yml
- ansible/roles/ocp-workload-file-uploader/tasks/post_workload.yml
- ansible/roles/ocp-workload-file-uploader/tasks/pre_workload.yml
- ansible/roles/ocp-workload-file-uploader/tasks/remove_workload.yml
- ansible/roles/ocp-workload-file-uploader/tasks/workload.yml
Adds new demo app intended to demo OpenShift Migration tool
ocp-workload-file-uploader
```paste below
```
> New workload for demo file uploader application

- ansible/roles/ocp-client-vm/defaults/main.yml
- ansible/roles/ocp-client-vm/tasks/main.yml
Update client tools to latest versions
Refactor the OCP 4 specific tools into a block.
Added KNative (kn) tool
> Update Client versions, refactor OCP 4 tools into block

- ansible/roles/set-repositories/tasks/file-repos.yml
- ansible/roles/set-repositories/tasks/satellite-repos.yml
> Fix set-repositories role for rhel8

- ansible/configs/sap-hana/README.adoc
- ansible/configs/sap-hana/default_vars.yml
- ansible/configs/sap-hana/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/sap-hana/files/hosts_template.j2
- ansible/configs/sap-hana/requirements.yml
- ansible/configs/sap-hana/software.yml
Add more customization to the template and reduce the parameters required from the user.
Add Satellite, add block device for software and remove NFS role as NFS will be directly mounted on the new block device with the software.
Modify instructions and remove not required lines
sap-hana agnosticd config
> Add Satellite, SAP Software and more customization

- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/defaults/main.yml
The workshop was rewritten to use a different structure.
> Update to new version of the lab

- ansible/roles/ocp4-workload-migration/defaults/main.yml
- ansible/roles/ocp4-workload-migration/tasks/workload.yml
adds a new wait condition for subscription to get ready
```paste below
```
> OpenShift Migration Workload : minor fix

- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/README.adoc
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/defaults/main.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/tasks/main.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/tasks/post_workload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/tasks/workload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/tasks/workload_project.yml
Verifaction for ocp4-workload-pam-fraudmanagement-workshop
ocp4-workload-pam-fraudmanagement-workshop-verification
Summit lab
> Added verification for ocp4-workload-pam-fraudmanagement-workshop

- ansible/roles/ocp4-workload-tektoncd-foundations/defaults/main.yml
- ansible/roles/ocp4-workload-tektoncd-foundations/files/pipelines-subscription.yml
- ansible/roles/ocp4-workload-tektoncd-foundations/readme.adoc
- ansible/roles/ocp4-workload-tektoncd-foundations/tasks/main.yml
- ansible/roles/ocp4-workload-tektoncd-foundations/tasks/post_workload.yml
- ansible/roles/ocp4-workload-tektoncd-foundations/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-tektoncd-foundations/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-tektoncd-foundations/tasks/workload.yml
New role for OCP 4 TektonCD Foundations Lab
`ocp4-workload-tektoncd-foundations`
None
> Added Tekton foundations workload

- ansible/roles/ocp-workload-migration/templates/operator.yml.j2
- ansible/roles/ocp4-workload-migration/defaults/main.yml
- ansible/roles/ocp4-workload-migration/tasks/workload.yml
Upgrades image to v1.1.1
Minor improvement in pause 
```paste below
```
> Migration Workload : release upgrade

- ansible/configs/ocp4-workshop/lifecycle.yml
> Fix workshop restart logic

- ansible/roles/ocp4-workload-tektoncd-foundations/defaults/main.yml
- ansible/roles/ocp4-workload-tektoncd-foundations/tasks/post_workload.yml
Validation playbook for ocp4-workload-tektoncd-foundations config
ocp4-workload-tektoncd-foundations
> Added validation playbook for Tekton foundations lab

- ansible/roles/ocp-workload-pam7-offer-management-dmn-pmml/tasks/workload.yml
Bug fix on workload ocp-workload-pam7-offer-management
ocp-workload-pam7-offer-management
> image stream not available

- ansible/configs/osp-migration/infra.yml
I need the value of osp_cluster_dns_zone to define the fqdn of the servers
> Pass to the stack the DNS zone variable

- ansible/roles/ocp-workload-mssql/defaults/main.yml
- ansible/roles/ocp-workload-mssql/templates/pvc.yaml.j2
Minor changes in PVCs of demo MsSQL app
ocp-workload-mssql
```paste below
```
> Minor changes in demo apps

- ansible/configs/ansible-tower-implementation/pre_software.yml
> Removed FTL injector

- ansible/configs/ansible-tower-implementation/default_vars.yml
install_ftl: false in default_vars.yml
```
> set install_ftl:false

- ansible/configs/ansible-tower-implementation/files/repos_template.j2
Added Red Hat Software Collection repo in repos_template.j2
> Fixed repo template

- README.adoc
Updated broken links in README
README
```paste below
```
> Updated example links

- ansible/configs/linklight/vars/windows_workshop.yml
Adds a windows_workshop var file to linklight to allow windows workshops
Adds support for Windows workshop to the **existing** linklight config
> Added windows var file to config linklight

- ansible/roles/satellite-installation/tasks/main.yml
- ansible/roles/satellite-installation/tasks/version_6.7.yml
This commit adds changes needed for sat 6.7 install
> Changes in role for sat 6.7 beta installation

- ansible/action_plugins/agnosticd_user_info.py
- ansible/configs/test-empty-config/post_software.yml
- ansible/library/agnosticd_user_info.py
Add ability to set data for particular users using agnosticd_user_info.
agnosticd_user_info action plugin.
> Add agnosticd_user_info per-user data

- ansible/configs/sap-hana/default_vars.yml
- ansible/configs/sap-hana/post_software.yml
- ansible/configs/sap-hana/requirements.yml
Update the dependencies of the roles to the latest cut release
Update the software volume name with a new version
Update the device's requirements for HANA File Systems
> Update role dependencies and complete workflows

- ansible/configs/osp-migration/env_vars.yml
- ansible/configs/osp-migration/pre_infra.yml
- ansible/library/convert_blueprint.py
This module uses a new host with access to all ceph cluster,
the host must be configured before use it
* Download blueprint images from IBM Cloud
* Convert images and upload to Ceph Cluster
* Create OpenStack Glance images
osp-migration
> Add new module to download OSP images from IBM

- ansible/roles/ocp4-workload-ccnrd/templates/osm_smcp.yaml
Enable policy checks so that authentication with RH-SSO works with istio. cc @danieloh30 
> enable policy checks for service mesh

- ansible/configs/osp-migration/pre_infra.yml
For become true on migration host
osp-migration
> Set become true to import images to ceph

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/confirm_che_workspace.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-amqstreams.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-codeready.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-jaeger.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/verify-workload.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
Add a step at the end to verify all components are operational to the extent needed for the workshop. Remove unnecessary `ignore_errors` conditionals in loops.
> add verification step; remove unneeded ignore_errors conditionals

- ansible/configs/osp-migration/pre_infra.yml
Add "Bastion" host variable to the import host
> Add "Bastion" host variable to the import host

- ansible/library/convert_blueprint.py
Clean up output dir 
ansible module
> Cleanup output_dir on import host

- docs/Creating_a_cloud_deployer.adoc
- docs/Creating_a_config.adoc
- docs/Creating_an_OpenShift_Workload.adoc
- docs/First_OSP_Env_walkthrough.adoc
- docs/Preparing_your_workstation.adoc
- docs/README.adoc
I felt that there was some work to be done to improve the overall "flow" of the documentation, to help out new users get used to AgnosticD. This PR does contain a couple of changes to documentation - removing duplicates, but it mostly alters the table of contents into smaller, more easy to find and digest chunks.
There are also some placeholders for providing more details about sample_vars.yml, deafult_vars.yml, etc. 
If merged, the Table of Contents will look like this;
docs/
> Docs flow/table of contents cleanup

- ansible/roles/ocp4-workload-ccnrd/files/stack.Dockerfile
Add a precompilation step to the Dockerfile used to generate the CodeReady Workspaces base image to pre-cache maven artifacts to speed up initial builds during the workshop.
**NOTE** this file is not actually used in the agnosticD workload execution, but is kept in here to be close to the source code that uses it.
> pre-cache all projects used in labs to speed initial compilation

- ansible/configs/sap-hana/default_vars.yml
Upgrade 'sap-hana' config with a new image version for new software, enable external access to the Application Server instance and change the DB instance type to suppport S/4HANA installation.
> Upgrade lab with new software image and resources requirements

- ansible/roles/ocp-workload-3scale-demo/defaults/main.yml
- ansible/roles/ocp-workload-3scale-demo/tasks/workload.yml
Update of 3scale API management to version 2.7.0.GA
3scale security demo
```paste below
```
> update playbook to 3scale 2.7.0.GA

- ansible/roles/ocp-workload-rocket-chat/README.adoc
- ansible/roles/ocp-workload-rocket-chat/defaults/main.yml
- ansible/roles/ocp-workload-rocket-chat/tasks/main.yml
- ansible/roles/ocp-workload-rocket-chat/tasks/post_workload.yml
- ansible/roles/ocp-workload-rocket-chat/tasks/pre_workload.yml
- ansible/roles/ocp-workload-rocket-chat/tasks/remove_workload.yml
- ansible/roles/ocp-workload-rocket-chat/tasks/workload.yml
Adds Rocket Chat demo workload
ocp-workload-rocket-chat
```paste below
```
> New demo app for migrations

- ansible/roles/ocp4-workload-quay-operator/defaults/main.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/workload.yml
- ansible/roles/ocp4-workload-quay-operator/templates/catalogsourceconfig.j2
- ansible/roles/ocp4-workload-quay-operator/templates/operatorgroup.j2
- ansible/roles/ocp4-workload-quay-operator/templates/subscription.j2
4.1 deploys operators differently...
> Fix operator for OCP 4.1 (RHPDS)

- ansible/roles/ocp4-workload-rhsso-foundations/tasks/post_workload.yml
> add post software task

- ansible/roles/ocp4-workload-ccnrd/files/ccn-sso72-template.yaml
> update RH-SSO 7.3

- ansible/roles/ocp4-workload-homeroomlab-dev-tools/defaults/main.yml
- ansible/roles/ocp4-workload-homeroomlab-dev-tools/readme.adoc
- ansible/roles/ocp4-workload-homeroomlab-dev-tools/tasks/main.yml
- ansible/roles/ocp4-workload-homeroomlab-dev-tools/tasks/post_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-dev-tools/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-dev-tools/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-dev-tools/tasks/verify_workload.yml
- ansible/roles/ocp4-workload-homeroomlab-dev-tools/tasks/workload.yml
Add workload for ocp4-workload-homeroomlab-dev-tools
ocp4-workload-homeroomlab-dev-tools
> Add workload for ocp4-workload-homeroomlab-dev-tools

- ansible/roles/ocp4-workload-quay-operator/tasks/workload.yml
> Fix workaround

- ansible/roles/ocp4-workload-quay-operator/tasks/workload.yml
> Another approach 1

- ansible/roles/ocp4-workload-istio-controlplane-student/tasks/workload.yml
This cleans up the control plane resource usage. 
```paste below
```
> Update workload to use default (minimal) resources

- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_per_project_fuseworkload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/templates/amq-streams/cluster.j2
Kafka was using incorrect config which caused message loss.
Summit 2020 lab
> Fixed kafka config causing broker to not receive messages

- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/tasks/workload_per_project_amqstreamsworkload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/tasks/workload_project.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_per_project_amqstreamsworkload.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_project.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/templates/amq-streams/topic.j2
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/templates/bucketrepo/deployment.j2
Adds workload deployment for amq streams for ocp4-workload-pam-fraudmanagement-workshop
Summit 2020 lab
> Added kafka workload to ocp4-workload-pam-fraudmanagement-workshop

- ansible/configs/osp-migration/pre_infra.yml
Update remote_user and add OS_INTERFACE
osp-migration
> Update remote_user for osp-migration

- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/workload.yml
Remove logging from ocp4-workload-homeroomlab-starter-guides
> Remove logging from ocp4-workload-homeroomlab-starter-guides

- ansible/ansible.cfg
Add infra roles lookup to `ansible/ansible.cfg`
> Add infra roles to ansible/ansible.cfg

- ansible/roles/ocp4-workload-ocs-operator/tasks/workload.yml
fixes ocs-operator role for ansible 2.8
> reverts k8s_info to k8s_facts

- ansible/configs/ocp4-disconnected-osp-lab/default_vars.yml
- ansible/configs/ocp4-disconnected-osp-lab/files/fio-test.sh.j2
- ansible/configs/ocp4-disconnected-osp-lab/software.yml
Remove the bucket name and region from the defaults
Add URI calls during test phases to report into overwatch
> Remove bucket from defaults and add tests

- ansible/install_galaxy_roles.yml
> galaxy role import: Be explicit, use parenthesis in the condition

- ansible/roles/ocp4-workload-ccnrd/files/knative-serving-cm.yaml
- ansible/roles/ocp4-workload-ccnrd/files/serverless-operator.v1.5.0.csv.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-serverless.yaml
- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
Same as https://github.com/redhat-cop/agnosticd/pull/1308 but this updates to the latest knative-serving operator, which was just updated today.
> Update knative-serving operator workaround

- ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/defaults/main.yml
Fixed some bugs in the lab and pushed a new version.
Fixed https://github.com/openshift-labs/lab-tekton-pipelines/issues/76
tekton lab
> Updated to latest version of this lab

- ansible/configs/ocp-workloads/env_vars.yml
- ansible/configs/ocp-workloads/ocp-workload.yml
- ansible/configs/ocp-workloads/post_software.yml
We don't set the virtualenv to run the workloads in when deploying via AgnosticV
> Add virtualenv to workloads deployed to shared clusters.

- ansible/configs/ocp-workloads/ocp-workload.yml
- ansible/configs/ocp-workloads/post_software.yml
> Fix stat check

- ansible/configs/ocp-workloads/destroy_env.yml
- ansible/configs/ocp-workloads/post_software.yml
Destroy needed check for virtualenv as well.
Deploy had double logic to deploy list of workloads
> Fix workload destroy

- ansible/configs/ocp-workloads/env_vars.yml
> Fix default dictionary

- ansible/roles/ocp4-workload-quay-operator/tasks/remove_workload.yml
> Fix scc cleanup (Quay Operator Bug)

- ansible/configs/ocp-workloads/destroy_env.yml
- ansible/configs/ocp-workloads/env_vars.yml
- ansible/configs/ocp-workloads/post_software.yml
- ansible/roles/host-virtualenv/defaults/main.yml
- ansible/roles/host-virtualenv/meta/main.yml
- ansible/roles/host-virtualenv/readme.adoc
- ansible/roles/host-virtualenv/tasks/main.yml
- ansible/roles/ocp4-workload-authentication/defaults/main.yml
- ansible/roles/ocp4-workload-authentication/tasks/workload.yml
- ansible/roles/ocp4-workload-logging/defaults/main.yml
- ansible/roles/ocp4-workload-logging/tasks/workload.yml
- ansible/roles/ocp4-workload-machinesets/defaults/main.yml
- ansible/roles/ocp4-workload-machinesets/tasks/workload.yml
- ansible/roles/ocp4-workload-quay-operator/defaults/main.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/workload.yml
Make workloads consistent with Ansible naming
> Change _input -> _vars, _secret -> _secrets

- ansible/roles/ocp4-workload-quay-operator/defaults/main.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-quay-operator/tasks/workload.yml
- ansible/roles/ocp4-workload-quay-operator/templates/catalogsourceconfig.j2
- ansible/roles/ocp4-workload-quay-operator/templates/project.j2
- ansible/roles/ocp4-workload-quay-operator/templates/subscription.j2
Check for ClusterVersion to make the role work on both 4.1 and 4.3
Fix cleanup of anyuid SCC.
> More checks.

- ansible/configs/ansible-tower-implementation/default_vars.yml
ansible_distribution_major_version. set in default_vars.yml due to change in install_common_package role.
> RHEL Version set

- ansible/configs/ansible-tower-implementation/default_vars_osp.yml
Added a new node which will act as git server for the course.
> Added git server

- ansible/roles/satellite-installation/README.adoc
- ansible/roles/satellite-installation/defaults/main.yml
- ansible/roles/satellite-installation/tasks/main.yml
- ansible/roles/satellite-installation/tasks/remove_epel_repos.yml
- ansible/roles/satellite-installation/tasks/version_6.4.yml
- ansible/roles/satellite-installation/tasks/version_6.6.yml
- ansible/roles/satellite-installation/tasks/version_6.7.yml
Improve satellite installation to prepare it for libvirt provisioning if necessary later and adds cockpit support for 6.7 version.
`satellite-installation`
Enable support for cockpit and libvirt in satellite
> Improve satellite installation

- ansible/configs/ocp4-ha-lab/post_software.yml
- ansible/configs/ocp4-ha-lab/software.yml
Set agnosticd_user_info for ocp4-ha-lab config
ocp4-ha-lab config
> Add agnosticd_user_info for ocp4-ha-lab

- ansible/configs/ocp4-workshop/post_software.yml
- ansible/configs/ocp4-workshop/software.yml
Convert user info to use agnosticd_user_info for ocp4_workshop config.
ocp4_workshop config
All debug user.info in ocp4_workshop converted to agnosticd_user_info
> Add agnosticd_user_info for ocp4_workshop

- ansible/roles/ocp-workload-example/defaults/main.yml
- ansible/roles/ocp-workload-example/readme.adoc
- ansible/roles/ocp-workload-example/tasks/post_workload.yml
- ansible/roles/ocp-workload-example/tasks/pre_workload.yml
- ansible/roles/ocp-workload-example/tasks/remove_workload.yml
- ansible/roles/ocp-workload-example/tasks/workload.yml
Docs, docs, docs. And Examples.
> Update documentation in example workload with dictionary approach

- ansible/configs/ansible-tower-implementation/default_vars.yml
- ansible/configs/ansible-tower-implementation/default_vars_osp.yml
- ansible/configs/ansible-tower-implementation/files/hosts_template.j2
- ansible/configs/ansible-tower-implementation/sample_vars_osp.yml
- ansible/configs/ansible-tower-implementation/software.yml
- ansible/roles/git-server-ssh/README.md
- ansible/roles/git-server-ssh/defaults/main.yml
- ansible/roles/git-server-ssh/handlers/main.yml
- ansible/roles/git-server-ssh/meta/main.yml
- ansible/roles/git-server-ssh/tasks/main.yml
- ansible/roles/git-server-ssh/tests/inventory
- ansible/roles/git-server-ssh/tests/test.yml
- ansible/roles/git-server-ssh/vars/main.yml
Git server VM provision
Changed hosts_template.j2 to add git VM
Role Added: git-server-ssh
This role will be installing local git repo server and initialise empty repo which will accessible by ssh.
> Git server added and empty git repo server role added

- ansible/configs/aro/env_vars.yml
- ansible/configs/aro/software.yml
Allowing compute_count to be configurable via the RHPDS order form instead of hard coded.
config/aro/software.yml
> Allowing aro to have a configurable compute_count

- ansible/configs/osp-migration/post_software.yml
> Move to lowercase the bookbag variables

- ansible/configs/ansible-tower-implementation/default_vars.yml
- ansible/configs/ansible-tower-implementation/post_software.yml
- ansible/roles/git-copy-files/.travis.yml
- ansible/roles/git-copy-files/README.md
- ansible/roles/git-copy-files/defaults/main.yml
- ansible/roles/git-copy-files/files/apache-setup.yml
- ansible/roles/git-copy-files/files/httpd.conf.j2
- ansible/roles/git-copy-files/files/index.html.j2
- ansible/roles/git-copy-files/handlers/main.yml
- ansible/roles/git-copy-files/meta/main.yml
- ansible/roles/git-copy-files/tasks/main.yml
- ansible/roles/git-copy-files/tests/inventory
- ansible/roles/git-copy-files/tests/test.yml
- ansible/roles/git-copy-files/vars/main.yml
Role added for copying lab files to lab git lab server.
> Role git repo files needed for the lab

- ansible/ansible.cfg
Symlink the `ansible/ansible.cfg` -> `ansible.cfg`
> Symlink ansible/ansible.cfg to root ansible.cfg

- ansible/configs/osp-migration/post_infra.yml
Run open-init script for ravello migration when it exists
osp-migration
> Run open-init script for ravello migration

- ansible/configs/osp-migration/post_infra.yml
Remove check if bastion exists
osp-migration
> Fix bastion check on OSP migration

- ansible/roles/ocp4-workload-pipelines/defaults/main.yml
- ansible/roles/ocp4-workload-pipelines/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-pipelines/tasks/workload.yml
- ansible/roles/ocp4-workload-pipelines/templates/installplan.j2
- ansible/roles/ocp4-workload-pipelines/templates/subscription.j2
- ansible/roles/ocp4-workload-serverless/defaults/main.yml
- ansible/roles/ocp4-workload-serverless/files/knative_serving.yaml
- ansible/roles/ocp4-workload-serverless/files/namespace.yaml
- ansible/roles/ocp4-workload-serverless/meta/main.yml
- ansible/roles/ocp4-workload-serverless/readme.adoc
- ansible/roles/ocp4-workload-serverless/tasks/main.yml
- ansible/roles/ocp4-workload-serverless/tasks/post_workload.yml
- ansible/roles/ocp4-workload-serverless/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-serverless/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-serverless/tasks/workload.yml
- ansible/roles/ocp4-workload-serverless/templates/installplan.j2
- ansible/roles/ocp4-workload-serverless/templates/subscription.j2
New workload to deploy OpenShift Serverless
> Ocp4 workload serverless

- ansible/roles/ocp4-workload-ccnrd/files/amqstreams_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/codeready_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/kafka_knative_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/osm_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/pipelines_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/serverless_eventing_subscription.yaml
- ansible/roles/ocp4-workload-ccnrd/files/serverless_subscription.yaml
> remove startingCSV

- ansible/configs/sap-hana/default_vars.yml
- ansible/configs/sap-hana/files/hosts_template.j2
In order to make hostname uniques for every lab request add the guid key to the instances names
sap-hana
> Make hostnames unique adding the guid

- ansible/configs/sap-hana/default_vars.yml
- ansible/configs/sap-hana/files/hosts_template.j2
To be consistent with the rest of the configs, move 'guid' as suffix of the hostname
sap-hana
> Put guid as suffix instead preffix

- ansible/configs/sap-hana/default_vars.yml
Fix group limits in Tower and add extra variable for Satellite
sap-hana
> Fix group limits in Tower and add extra variable for Satellite

- ansible/configs/sap-hana/post_software.yml
Remove become from localhost plays
sap-hana
> Remove become from localhost plays

- ansible/roles/ocp4-workload-authentication/defaults/main.yml
- ansible/roles/ocp4-workload-nexus-operator/tasks/workload.yml
> Fix machinesets

- ansible/configs/satellite-vm/README.adoc
- ansible/configs/satellite-vm/software.yml
- ansible/roles/satellite-manage-compute-profile/README.adoc
- ansible/roles/satellite-manage-compute-profile/tasks/main.yml
Adds ability to create compute profiles
Role `satellite-manage-compute-profile`
Just another satellite role :upside_down_face:
> Satellite role to create a compute profile

- ansible/roles/satellite-manage-activationkey/tasks/version_6.x.yml
- ansible/roles/satellite-manage-content-view/README.adoc
- ansible/roles/satellite-manage-content-view/tasks/_create_content_view.yml
Ability to add filter in the content views
Role `satellite-manage-content-view`
Role `satellite-manage-activationkey` - small fix
Adds content view filters and fixes the issue with the activation key creation being mandatory.
> Satellite add filters for content views

- ansible/configs/ocp-clientvm/default_vars.yml
Adding clarification on student_password.
```paste below
```
> Clarify student_password usage

- ansible/configs/satellite-multi-region/post_software.yml
- ansible/configs/satellite-vm/post_software.yml
- ansible/roles/satellite-verification/README.adoc
- ansible/roles/satellite-verification/tasks/main.yml
Satellite install verification
`satellite-verification`
For now we only came up with checking wheter the services are up and running.
> Satellite - verification of install

- ansible/configs/sap-hana/post_software.yml
Add descriptive information to be sent to the user
sap-hana
> Add information to be sent to the user

- ansible/roles/ocp-workload-odo-workshop/defaults/main.yml
Updates to the odo workshop to fix bugs (it doesn't work on 4.x) and change the example application.
ocp-workload-odo-workshop
The change is simply to pull from a different branch for the lab content; the rest of the agnosticd setup should work fine.
```paste below
```
> Changed branch for odo workshop

- ansible/roles/ocp-client-vm/tasks/main.yml
lab-user was hardcoded in paths to update, even when `student_name` was defined as something different.
ocp-clientvm
> remove hardcoded lab-user

- ansible/configs/ocp4-workshop/env_vars.yml
Set default for ocp4-workshop `update_packages` to true. It was breaking in the common role without this and that can be addressed separately.
ocp4-workshop
> change default var for update_packages

- ansible/configs/satellite-vm/README.adoc
- ansible/roles/satellite-register-host/README.adoc
- ansible/roles/satellite-register-host/tasks/katello_agent.yml
- ansible/roles/satellite-register-host/tasks/main.yml
- ansible/roles/satellite-register-host/tasks/register.yml
- ansible/roles/satellite-register-host/tasks/remote_execution.yml
Role to register hosts, that we created in the infrastructure.
Role `satellite-register-host`
Installs satellite certificate, register with registration key, enables remote execution on the hosts.
> Satellite hosts registration

- ansible/roles/ocp-workload-mig-verification/tasks/post_workload.yml
- ansible/roles/ocp-workload-mig-verification/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-mig-verification/tasks/post_workload.yml
Adds new variables required by Bookbag for lab
ocp-workload-mig-verification
ocp4-workload-mig-verification
```paste below
```
> Migration Lab : added agnosticd_user_info variables for bookbag

- ansible/configs/ocp4-workshop/env_vars.yml
sadface, we can't update all packages without breaking things like IPA. This will have to be fixed more strategically.
ocp4-workshop
> update_packages back to false

- docs/Contributing.adoc
Please help me formulate here some guideline and rules for reviewing PRs.
> Add section about PR review in Contributing doc

- ansible/configs/sap-hana/post_software.yml
Public hostnames reported to the users have wrong information
sap-hana
> Replace public hostname with the correct one

- ansible/configs/ocp-clientvm/post_software.yml
This will add some user.info to the clientvm config when using `install_student_user`, which is needed to generate the email The New Way.
ocp-clientvm
> Nstephan userinfo

- ansible/configs/satellite-vm/default_vars.yml
- ansible/configs/satellite-vm/default_vars_osp.yml
- ansible/configs/satellite-vm/pre_infra.yml
- ansible/configs/satellite-vm/satellite_add_host_instance.yml
Adds default osp configuration for satellite.
Config `satellite-vm`
Adds security group configurations, and capsule and host instances configuration for OSP cloud provider.
> Satellite osp configuration

- ansible/configs/ansible-tower-implementation/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/multi-cloud-capsule/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/sap-hana/files/cloud_providers/osp_cloud_template_master.j2
- ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_master.j2
> Revert osp dns metadata changes

- ansible/configs/studentvm/default_vars_osp.yml
- ansible/roles-studentvm/studentvm-bash-prompt/tasks/main.yml
- ansible/roles-studentvm/studentvm-ocp4/tasks/main.yml
> Minor fixes to StudentVM Roles

- ansible/configs/satellite-vm/README.adoc
- ansible/configs/satellite-vm/sample_vars_ec2.yml
- ansible/configs/satellite-vm/sample_vars_osp.yml
- ansible/configs/satellite-vm/software.yml
Satellite VM config - include all the roles.
Config `satellite-vm`
Include all the roles that are necessary for feature full install of satellite.
> Satellite-vm software step

- ansible/configs/satellite-vm/README.adoc
- ansible/configs/satellite-vm/default_vars.yml
- ansible/configs/satellite-vm/destroy_env.yml
- ansible/configs/satellite-vm/files/hosts_template.j2
- ansible/configs/satellite-vm/files/repos_template.j2
- ansible/configs/satellite-vm/post_software.yml
- ansible/configs/satellite-vm/pre_software.yml
Preparation, finish and destroy steps for `satellite-vm`.
Role `satellite-vm`
- Installs pip from epel, setup repositories for each host bit differently
> Satellite VM - pre and post steps

- tests/static/setup.py
For example:
- when: true
...
restults in a python error.
```paste below
```
> Fix test when there is a boolean 'when'

- ansible/configs/selinux-policy/env_vars.yml
- ansible/configs/selinux-policy/post_software.yml
- ansible/configs/selinux-policy/pre_software.yml
- ansible/configs/selinux-policy/sample_vars.yml
Fixes some bugs and returns user data for SSH access to the bastion host for the selinux-policy config.
selinux-policy config
> Student SSH access for selinux-policy config

- ansible/configs/satellite-vm/default_vars.yml
Minor change to satellite default repositories
Default vars of `satellite-vm`
> Satellite - default repositories

- ansible/configs/ansible-tower-implementation/default_vars_osp.yml
Updated default_vars_osp.ya,l to add SG for Git server
> Opened TCP ports on git server

- ansible/configs/ansible-tower-implementation/default_vars_osp.yml
- ansible/roles/git-copy-files/files/apache-setup.yml
> osp vars and playbook fixed

- ansible/configs/ansible-tower-implementation/post_software.yml
- ansible/roles/setup-postfix/.travis.yml
- ansible/roles/setup-postfix/README.md
- ansible/roles/setup-postfix/defaults/main.yml
- ansible/roles/setup-postfix/handlers/main.yml
- ansible/roles/setup-postfix/meta/main.yml
- ansible/roles/setup-postfix/tasks/main.yml
- ansible/roles/setup-postfix/tests/inventory
- ansible/roles/setup-postfix/tests/test.yml
- ansible/roles/setup-postfix/vars/main.yml
Added a role to setup postfix mail server on tower server.
> setup mail server on tower

- ansible/roles/satellite-provisioning/tasks/dns_resolve.yml
Wrong regex in provisioning task.
Role `satellite-provisioning`
> Satellite fix regex in provisioning

- ansible/roles/satellite-capsule-rex/tasks/main.yml
I've missed one place while renaming variable :man_facepalming: 
Role `satellite-capsule-rex`
> Satellite rex - fix variable name

- ansible/roles/ocp4-workload-istio-tutorial-student/tasks/workload.yml
removed istio proxy annotations for CPU and MEMORY to use less resources on the lab
```paste below
```
> removed istio proxy annotations

- ansible/configs/sap-hana/post_software.yml
Make the output of the SSH key multiline and remove '/n' characters.
sap-hana
> Make RSA output multiline

- ansible/configs/selinux-policy/env_vars.yml
> as per JK, add student_user definition

- ansible/roles/ocp4-workload-istio-workshop-homeroom/files/hosted-workshop-production.json
- ansible/roles/ocp4-workload-istio-workshop-homeroom/files/workshop-settings.j2
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/workload.yml
for the service mesh workshop this is a change to how homeroom is deployed
> converts to use template for lab-ossm

- ansible/configs/rhel-container-security/env_vars.yml
- ansible/configs/rhel-container-security/post_software.yml
- ansible/configs/rhel-container-security/pre_software.yml
Moved vars and added user info support
rhel-container-security
```paste below
```
> Changes for summit test deploy

- ansible/roles-infra/infra-ec2-template-create/tasks/detect_custom_images.yml
changing ec2_ami_facts to ec2_ami_info
Fixes #1038 
Detect custom images under infra-ec2-template-create/tasks
> changed ec2_ami_facts to ec2_ami_info

- ansible/roles-infra/infra-ec2-template-create/tasks/detect_custom_images.yml
Reverts redhat-cop/agnosticd#1466
> Revert "changed ec2_ami_facts to ec2_ami_info"

- ansible/roles/ocp-workload-3scale-demo/defaults/main.yml
update 3scale version
3scale security demo
```paste below
```
> update version to 2.8.0.GA

- ansible/configs/osp-migration/pre_infra.yml
Add condition for migration key
> Add condition for migration key

- ansible/configs/osp-migration/pull_repo.yml
updated pull_repo.yaml 
added a block with a condition platform == "Babylon" to encode and decode ssh private key.
> Novello test fix

- ansible/configs/osp-migration/post_infra.yml
Use replace module to replace multiple occurrences of PasswordAuthentication in sshd_config
osp-migration
> Use replace to enable PasswordAuthentication

- ansible/roles/host-ocp4-provisioner/tasks/osp_prereqs.yml
> Fix swift check - use variable instead of installer version

- ansible/roles/ocp4-workload-aws-jumpbox/templates/create_jumpbox.yml
Another small one - since us-east-2 has limit issues...
> Add us-west-1 to supported regions for AWS Jumpbox

- ansible/roles/ocp4-workload-ceph/defaults/main.yml
- ansible/roles/ocp4-workload-ceph/templates/subscription.yml.j2
- ansible/roles/ocp4-workload-ocs-operator/defaults/main.yml
- ansible/roles/ocp4-workload-ocs-operator/templates/subscription.yml.j2
ocp4-workload-ocs-operator
```paste below
```
> OCS workloads : remove starting csv option

- ansible/roles/ocp4-workload-ml-workflows-infra-summit2020/defaults/main.yml
> Add default for rgw_endpoint_url

- ansible/roles-infra/infra-ec2-create-inventory/tasks/main.yml
> Do not fail if some instances don't have a public ip address

- ansible/configs/rhel-container-security/destroy_env.yml
Fixed destroy to check for stopped instances
Fixed destroy to check for stopped instances
```paste below
```
> Code to start instances that may have stopped.

- ansible/configs/ansible-tower/env_vars.yml
The postgresql DB should not be exposed
The admin password should be provided, or generated.
> Security fix tower

- ansible/cloud_providers/gcp_infrastructure_deployment.yml
- ansible/configs/ocp4-cluster/default_vars_azure.yml
- ansible/configs/ocp4-cluster/default_vars_gcp.yml
- ansible/configs/ocp4-cluster/files/cloud_providers/azure_cloud_template.j2
- ansible/configs/ocp4-cluster/sample_vars/ocp4_cluster_azure_bare_bones.yml
- ansible/configs/ocp4-cluster/sample_vars/ocp4_cluster_gcp_bare_bones.yml
- ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml
- ansible/roles-infra/infra-gcp-template-destroy/tasks/main.yml
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
- ansible/roles/set-repositories/tasks/satellite-repos.yml
Updating to RHEL 8, adding sample_vars for base install for GCP and Azure, and fixing a couple quirks that I found testing the sample_vars.
Azure and GCP cloud providers and config/ocp4-cluster
Follow-up to some changes Wolfgang made like introducing sample_vars.
> A few bug fixes and updates for Azure and GCP

- ansible/configs/ocp-clientvm/files/cloud_providers/ec2_cloud_template.j2
ClientVM is a special snowflake and needs multiple DNS entries. Until it slowly dies, adding a slightly tweaked custom CFN template back.
ocp-clientvm
> add custom cfn template for clientvm

- ansible/roles/ocp-workload-3scale-demo/defaults/main.yml
- ansible/roles/ocp-workload-3scale-demo/tasks/config.yml
change the way the url is generated to reuse the wildcard cert for *.apps.
3scale-security-demo
```paste below
```
> change to use the wildcard cert for *.apps.

- ansible/configs/rhel8lab/my_vars_osp_rhel8lab.yml
- ansible/configs/rhel8lab/sample_vars_osp.yml
Comment out some vars, remove some values from 
rhel8lab
> Clean up vars in rhel8lab

- ansible/configs/rhel8lab/sample_vars_osp.yml
sample_vars_osp contained hardcoded and non-generic values breaking deploy if used
rhel8lab
> Made rhel8lab sampe_vars_osp generic and deployable

- ansible/configs/rhel-container-security/destroy_env.yml
Fix destroy logic for rhel-container-security config. Config was based on OpenShift 4 config.
rhel-container-security config
> Fix destroy for rhel-container-security config

- ansible/configs/selinux-policy/env_vars.yml
Changed AWS instance types to optimize costs. Lab owner has agreed.
```paste below
```
> Change instance types

- ansible/configs/ocp-workshop/post_software.yml
Add agnosticd_user_info to ocp-workshop config
ocp-workshop config
> Add agnosticd_user_info to ocp-workshop config

- ansible/configs/sap-hana/post_software.yml
PR to solve an issue with the user info message as an extra '+' char was in the config.
sap-hana
> Solve user info typo on extra char

- ansible/configs/sap-rhvh/post_software.yml
Add credentials, password and other required information to be sent to the user
sap-rhvh
> Add required information to be sent to the user

- ansible/configs/ansible-workshops/vars/security_tower_workshop_vars.yml
> set autolicense to true

- ansible/configs/satellite-vm/post_software.yml
Added the agnosticd variables needed for the satellite guide
> Setup satellite-vm user variables

- ansible/configs/sap-hana/files/hosts_template.j2
- ansible/configs/sap-hana/software.yml
Add required configuration for SAP HANA RHEL lab after QA test
sap-hana
> Add additional required configuration after SAP RHEL lab review

- ansible/configs/ansible-workshops/vars/advanced_tower_vars.yml
Adding new vars for advanced ansible tower workshop from summit
advanced tower
> Rut31337 patch 1

- ansible/configs/ocp4-workshop/post_software.yml
- ansible/configs/ocp4-workshop/software.yml
- ansible/roles/ocp4-workload-istio-workshop-homeroom/tasks/workload.yml
Add user data for agnosticd_user_info to ocp4-workshop and messages for ocp4-workload-istio-workshop-homeroom.
ocp4-workshop config and ocp4-workload-istio-workshop-homeroom workload
> Add agnosticd_user_info for ocp4-workshop users

- ansible/configs/ocp4-cluster/default_vars_osp.yml
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Simple change to minimize the vars used.
ocp4-cluster
> remove rhcos var and consolidate with single

- ansible/configs/sap-rhvh/default_vars.yml
- ansible/configs/sap-rhvh/requirements.yml
Lock the ovirt engine role to specific tag and add new required variable
sap-rhvh
> Lock galaxy role to specific version and add additional variable

- ansible/configs/ansible-tower/env_vars.yml
> Fix security groups in ansible-tower config

- ansible/configs/rhel-container-security/env_vars.yml
Bug fix: Added bc package needed for lab
Added bc package needed for lab
```paste below
```
> Added bc rhel8 package

- ansible/configs/ocp4-workshop/env_vars.yml
- ansible/configs/ocp4-workshop/ocp_workloads.yml
- ansible/configs/ocp4-workshop/post_software.yml
- ansible/configs/ocp4-workshop/templates/htpasswd.j2
Finish reconciling vars `user_count`, `user_count_start`, and `user_count_end` for ocp4-workshop.
ocp4-workshop
> Reconcile user_count variables for ocp4-workshop

- ansible/configs/sap-rhvh/files/rhhi-playbooks/spice_proxy.j2
- ansible/configs/sap-rhvh/software.yml
Configure ovirt-engine to use a proxy for SPICE
sap-rhvh
> Configure SPICE Proxy for ovirt-engine

- ansible/configs/sap-rhvh/software.yml
Small fix the module used to install a package
sap-rhvh
> Quick fix on package install

- tests/static/syntax-check.sh
Show git commit in travis tests after cloning ansible/workshops
tests
> Show tests ansible workshops git state

- ansible/roles/ocp4-workload-debugging-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-debugging-workshop/defaults/sample_vars.yml
- ansible/roles/ocp4-workload-debugging-workshop/readme.adoc
- ansible/roles/ocp4-workload-debugging-workshop/tasks/post_workload.yml
- ansible/roles/ocp4-workload-debugging-workshop/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-debugging-workshop/templates/cluster_role_binding.j2
- ansible/roles/ocp4-workload-debugging-workshop/templates/debugging-workshop.j2
- ansible/roles/ocp4-workload-debugging-workshop/templates/operator.j2
- ansible/roles/ocp4-workload-debugging-workshop/templates/project.j2
- ansible/roles/ocp4-workload-debugging-workshop/templates/service_account.j2
> Updated for Babylon tests

- ansible/configs/ocp4-workshop/.yamllint
- ansible/configs/ocp4-workshop/destroy_cluster.yml
- ansible/configs/ocp4-workshop/destroy_env.yml
- ansible/configs/ocp4-workshop/env_vars.yml
- ansible/configs/ocp4-workshop/files/kubelet-bootstrap-cred-manager-ds.yaml
- ansible/configs/ocp4-workshop/files/oauth-htpasswd.yaml
- ansible/configs/ocp4-workshop/files/oauth-opentlc-ldap.yaml
- ansible/configs/ocp4-workshop/lifecycle.yml
- ansible/configs/ocp4-workshop/ocp_workloads.yml
- ansible/configs/ocp4-workshop/post_infra.yml
- ansible/configs/ocp4-workshop/post_software.yml
- ansible/configs/ocp4-workshop/pre_infra.yml
- ansible/configs/ocp4-workshop/pre_software.yml
- ansible/configs/ocp4-workshop/software.yml
No functional changes, just yamllint fixes to standardize style for ocp4-workshop config.
Just following the bare-bones standard `yamllint` rules, ignoring line length and spaces after start of comment.
> Bulk fixes to ocp4-workshop for yamllint

- tests/static/syntax-check.sh
Add yamllint check against all directories containing a `.yamllint` file.
static code checks
> Add yamllint static check

- ansible/configs/osp-satellite-vm/post_infra.yml
- ansible/configs/osp-satellite-vm/post_software.yml
- ansible/configs/osp-satellite-vm/sample_vars.yml
Variables for bookbag, necessary for bookbag to work with this @agonzalezrh 
Some nice to have changes along the lines.
`osp-satellite-vm`
> improve, share all necessary info

- ansible/configs/osp-satellite-vm/post_infra.yml
Reset the satellite `instance_id`
> Change satellite_id after image copy

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/workload.yml
I think this fixes a problem i'm having
> changes a user_count reference to num_users

- ansible/roles/ocp4-workload-ml-workflows-infra-summit2020/tasks/pipelines.yml
- ansible/roles/ocp4-workload-ml-workflows-infra-summit2020/tasks/workload.yml
Add Tekton resource validation to the Infra role.
> Move KNative/Pipeline at the front of the process

- ansible/configs/sap-rhvh/default_vars.yml
- ansible/configs/sap-rhvh/files/rhhi-playbooks/gluster_inventory.j2
- ansible/configs/sap-rhvh/post_software.yml
- ansible/configs/sap-rhvh/pre_software.yml
Use new flavours for RHV to fit required VMs abd pre-create VMs in RHV
sap-rhvh
> Add new sizes and pre-create VMs in RHV

- ansible/configs/ocp4-cluster/files/cloud_providers/azure_cloud_template.j2
Storage names don't like hyphens or underscores either
config/ocp4-cluster
N/A
> Updating Azure template

- ansible/configs/sap-rhvh/post_software.yml
Solve memory issues where guaranteed memory value was higher that assigned value
sap-rhvh
> Solve guaranteed memory value for VMs

- ansible/roles/ocp4-workload-ml-workflows-workshop/defaults/main.yml
Uses a new s2i builder image to fix a problem in deployed model services.
`ocp4-workload-ml-workflows-workshop`
> update s2i image tag for statistics-to-serverless lab

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/create_project.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
The last pull request introduced a bug in the user project creation. This pull request fixes that issue while also introducing safe task level variable naming using `t_` prefix to indicate var is task level.
ocp4-workload-quarkus-workshop-user-create-project workload role
> Fix loop var for user project creation

- ansible/roles/ocp4-workload-logging/tasks/workload.yml
This is the same logic applied to the elasticsearch operator, now also required for the logging operator.
ocp4-workload-logging
> Update ocp4-workload-logging to match version

- ansible/roles/ocp4-workload-quay-operator/defaults/main.yml
Postgres keeps crashing bringing down Quay. So upping the resources.
> Updated resources for Quay Ecosystem

- ansible/configs/sap-hana/default_vars.yml
Update instances default image to RHEL 8.1
sap-hana
> Update default RHEL version to 8.1

- ansible/configs/sap-hana/default_vars.yml
Move to e4s repositories for SAP deployments
sap-hana
> Move to e4s repositories

- ansible/roles/ocp-workload-example/tasks/post_workload.yml
Just a naming change in two tasks.
> Fix task name in post_software in example workload

- ansible/configs/rhel-container-security/software.yml
Add ansible retries to podman pull commands in rhel-container-security config.
rhel-container-security config
> Add podman pull retries to rhel-container-security config

- ansible/configs/rhel-container-security/software.yml
Fix the podman pull command for the workshopper container to retry failures in the event of a communications issue with quay.io
rhel-container-security config
> Fix podman workshoper image pull in rhel-container-security

- ansible/roles/set-repositories/tasks/satellite-repos.yml
Add retries to set-repositories download satellite cert task.
set-repositories role
> Add retries to download satellite cert in set-repositories role

- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_per_cluster_amqstreams.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/templates/amq-streams/cluster.j2
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/templates/amq-streams/operator.j2
Upgraded to latest streams for ocp4-workload-pam-fraudmanagement-workshop
ocp4-workload-pam-fraudmanagement-workshop
> Upgraded amq streams to next version for ocp4-workload-pam-fraudmanagement-workshop

- ansible/configs/ocp-workloads/ocp-workload.yml
- ansible/roles/ocp4-workload-integreatly-minio/defaults/main.yml
- ansible/roles/ocp4-workload-integreatly-minio/meta/main.yml
- ansible/roles/ocp4-workload-integreatly-minio/readme.adoc
- ansible/roles/ocp4-workload-integreatly-minio/tasks/main.yml
- ansible/roles/ocp4-workload-integreatly-minio/tasks/post_workload.yml
- ansible/roles/ocp4-workload-integreatly-minio/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-integreatly-minio/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-integreatly-minio/tasks/workload.yml
- ansible/roles/ocp4-workload-integreatly-minio/templates/clusterrole.yml.j2
- ansible/roles/ocp4-workload-integreatly-minio/templates/crd.yml.j2
- ansible/roles/ocp4-workload-integreatly-minio/templates/deployment.yml.j2
- ansible/roles/ocp4-workload-integreatly-minio/templates/project.yml.j2
- ansible/roles/ocp4-workload-integreatly-minio/templates/rolebinding.yml.j2
- ansible/roles/ocp4-workload-integreatly-minio/templates/secret.yml.j2
- ansible/roles/ocp4-workload-integreatly-minio/templates/serviceaccount.yml.j2
- ansible/roles/ocp4-workload-integreatly/sample_vars/ocp4_workload_integreatly_vars.yml
Deploys the minio operator as part of the pre-workload tasks
https://issues.redhat.com/browse/INTLY-7040
> Deploy minio operator in integreatly ocp4 workload

- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/tasks/workload_per_cluster_codereadyworkspaces.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/templates/codeready-workspaces/operator.j2
Upgraded codeready workspaces to latest for ocp4-workload-pam-fraudmanagement-workshop
> Upgraded codeready workspaces to latest for ocp4-workload-pam-fraudmanagement-workshop

- ansible/configs/sap-hana/default_vars.yml
Remove Satellite creds from the configuration
sap-hana
> Remove Sat credentials from the configuration

- ansible/configs/osp-migration/pull_repo.yml
Be able to specify a git tag along with the template name
> Add the ability to specify the tag for templates

- ansible/configs/ocp4-workshop/software.yml
Retry openshift-install on throttling rate during credential check
> Retry openshift-install on throttling rate during credential check

- ansible/configs/ansible-tower-implementation/post_software.yml
task added to get user info for learners.
> user.info added for mail

- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/OWNERS
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop-verification/meta/main.yml
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/OWNERS
- ansible/roles/ocp4-workload-pam-fraudmanagement-workshop/meta/main.yml
Moved to using meta as a way to describe ownership
> Added meta/main.yml for ocp4-workload-pam-fraudmanagement-workshop

- ansible/configs/ocp4-cluster/default_vars.yml
- ansible/configs/ocp4-cluster/post_software.yml
- ansible/configs/ocp4-cluster/sample_vars/ocp4_cluster_aws_bare_bones.yml
- ansible/configs/ocp4-cluster/sample_vars/ocp4_cluster_aws_htpasswd_certs.yml
- ansible/configs/ocp4-cluster/sample_vars/ocp4_cluster_aws_htpasswd_certs_logging_infra.yml
- ansible/configs/ocp4-cluster/sample_vars/ocp4_cluster_osp_bare_bones.yml
- ansible/configs/ocp4-cluster/sample_vars/ocp4_cluster_osp_htpasswd_certs.yml
- ansible/configs/ocp4-cluster/sample_vars/ocp4_cluster_osp_htpasswd_certs_logging_infra.yml
- ansible/roles/host-ocp4-destroy/tasks/main.yml
- ansible/roles/host-ocp4-installer/tasks/install_installer.yml
- ansible/roles/host-ocp4-installer/tasks/main.yml
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
fix cluster_name variable.
Remove remote_user in favor of ansible_user to make things consistent.
Update ocp4-cluster sample vars files for new workloads (and variables)
> Fix cluster name

- ansible/roles_ocp_workloads/README.md
Developers might get confused with directory strucgture
roles_ocp_workloads directory
> add README to roles_ocp_workloads

- ansible/configs/sap-rhvh/files/kvm-nested.conf.j2
- ansible/configs/sap-rhvh/post_software.yml
- ansible/configs/sap-rhvh/pre_software.yml
Change VMs FQDN and add VMs info to /etc/hosts in the bastion host
sap-rhvh
> Change VMs FQDN and add VMs info to /etc/hosts in the bastion host

- ansible/roles/ocp4-workload-quarkus-workshop/templates/devfile.json.j2
> Increase memorylimit to 4Gi in CRW

- ansible/configs/osp-migration/infra.yml
Currently is using the openstack command
TODO:
Create an Ansible module to apply tags
> Tag openstack project with the student name

- ansible/roles/tower-user-create/tasks/main.yml
> Add the ability to create auditor users

- ansible/configs/sap-rhvh/post_software.yml
Map VMs to specific hosts, remove memory reservation and add extra required disks
sap-rhvh
> Minor changes and extra capabilities after initial QA review

- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_homework/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_homework/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_homework/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_homework/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_homework/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_homework/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_homework/templates/cluster_resource_quota.j2
- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_homework/templates/jenkins_role_binding.j2
- ansible/roles_ocp_workloads/ocp4_workload_developer_environment/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_developer_environment/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_developer_environment/tasks/idle_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_developer_environment/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_developer_environment/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_developer_environment/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_developer_environment/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_developer_environment/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_developer_environment/templates/cluster_resource_quota.j2
- ansible/roles_ocp_workloads/ocp4_workload_project_request_template/templates/project_request_template.j2
- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/README.adoc
- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/templates/cluster_resource_quota.j2
New roles for OCP 4.4 Shared Cluster Access.
Copied existing roles into new directory, renamed, updated with proper variables, unified logic.
> Ocp44 shared cluster roles

- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/files/amq-artemis-address-crd.yml
- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/files/amq-artemis-broker-crd.yml
- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/files/amq-artemis-scaledown-crd.yml
- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/files/amq-broker-address-incomingorders.yml
- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/files/amq-broker-address-notifications.yml
- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/files/amq-broker-cr.yml
- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/files/amq-broker-operator-role.yml
- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/files/amq-broker-operator-rolebinding.yml
- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/files/amq-broker-operator-serviceaccount.yml
- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/files/amq-broker-operator.yml
- ansible/roles_ocp_workloads/ocp4_workload_fuse_online/tasks/workload.yml
New labs in the Fuse Foundations Part I Fuse Online course require an AMQ broker.
> ocp4_workload_fuse_online: added AMQ broker deployment

- ansible/configs/sap-rhvh/post_software.yml
Add affinity groups to place VMs on specific Hosts
sap-rhvh
> Add affinity groups to place VMs on specific Hosts

- ansible/configs/osp-migration/infra.yml
> Add port 8443 as https accesible and add port to the url shown

- ansible/roles/ocp4-workload-ccnrd/tasks/install-amqstreams.yaml
> Fix kafka-source installation

- ansible/roles/ocp4-workload-ccnrd/tasks/install-amqstreams.yaml
> Remove duplicated commands

- ansible/roles/ocp4-workload-jdg-workshop/files/codeready_cr.yaml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/add_che_user.yaml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/confirm_che_workspace.yaml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/create_che_workspace.yaml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/install-codeready.yaml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/post_workload.yml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/verify-workload.yaml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/verify_che_workspace.yaml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/workload.yml
> Fix TLS in CRW and Keycloak

- ansible/roles/ocp4-workload-ccnrd/tasks/install-amqstreams.yaml
> improve install knative-sources

- ansible/roles/ocp4-workload-ccnrd/tasks/install-amqstreams.yaml
> Fix knative-sources

- ansible/configs/osp-migration/post_infra.yml
> updated gucamole output

- ansible/configs/osp-migration/infra.yml
Adds new metadata to instances
osp-migration
> Set server metadata

- docs/First_OSP_Env_walkthrough.adoc
Point to opentlc instead of rhpds
Point to opentlc instead of rhpds
```paste below
```
> Point to opentlc instead of rhpds

- ansible/configs/sap-hana/default_vars.yml
- ansible/configs/sap-hana/software.yml
SAP software can't be present on partners training. As the software is present by default, this will remove the content when a non-Red Hatter request this item
sap-hana
> Remove software content when external request

- ansible/configs/osp-migration/infra.yml
- ansible/configs/osp-migration/post_infra.yml
* Add task names
* Send labconsole information
> [osp-migration] Add console information to user.info and add some information extra

- ansible/configs/osp-migration/post_infra.yml
To avoid issues on mail clients
> [osp-migration] replace < with *

- ansible/roles/ocp4-workload-ausgeben-infra/defaults/main.yml
- ansible/roles/ocp4-workload-ausgeben-infra/readme.adoc
- ansible/roles/ocp4-workload-ausgeben-infra/tasks/main.yml
- ansible/roles/ocp4-workload-ausgeben-infra/tasks/post_workload.yml
- ansible/roles/ocp4-workload-ausgeben-infra/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-ausgeben-infra/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-ausgeben-infra/tasks/workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/files/ausgeben.csv
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/workload.yml
* adds a role to deploy ausgeben, a credentials granting app
* tweaks the data engineering workshop to properly put information into ausgeben
> adds ausgeben role and reworks data eng to use it

- ansible/roles/ocp4-workload-ccnrd/files/rhamt-template.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-jaeger.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-rhamt.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-servicemesh.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
> Update RHAMT 4.3.1.Final and Jaeger bugfix for M2

- ansible/configs/smart-management/post_software.yml
loop added in agnostic user info
> Minor Change config:smart-management

- ansible/configs/satellite-infrastructure/requirements.yml
- ansible/configs/smart-management/post_software.yml
Role added in satellite-infrastructure config
config: satellite-infrastructure
> Role addition in Config:satellite-infrastructure

- docs/First_OSP_Env_walkthrough.adoc
changed another rhpds reference and pointed to labs.opentlc.com
changed another rhpds reference and pointed to labs.opentlc.com
```paste below
```
> another rhpds reference

- ansible/configs/sap-hana/files/hosts_template.j2
Add conditional to Ansible Inventory generated for the Lab to reflect the different configuration available for each Lab implementation
sap-hana
> Add conditionals to Ansible Inventory to reflect the real environment

- ansible/configs/smart-management/pre_software.yml
Hide strong password which was exposed at beginning 
> Hide user info config:smart-management

- ansible/configs/smart-management/post_software.yml
- ansible/configs/smart-management/pre_software.yml
> ssh info added config:smart-management

- ansible/configs/smart-management/post_software.yml
user password added in user.info
> user password config: smart-management

- ansible/configs/smart-management/pre_software.yml
bastion-student-user role added to config:smart-management
> bastion-student-user role added

- ansible/configs/smart-management/pre_software.yml
- ansible/configs/smart-management/requirements.yml
Role version specified in smart-management config as per suggestion given by GC.
> Role version 

- ansible/configs/satellite-infrastructure/requirements.yml
- ansible/configs/smart-management/pre_software.yml
- ansible/configs/smart-management/requirements.yml
Role version specified in satellite-infrastructure config as per suggestion given by GC.
config: satellite-infrastructure
> external role version 

- ansible/configs/ansible-tower-implementation/README.adoc
Readme content added to config: ansible-tower-implementation
> README added config:ansible-tower-implementation

- ansible/configs/ansible-tower-implementation/README.adoc
- ansible/configs/satellite-infrastructure/README.adoc
README.adoc updated 
config: satellite-infrastructure
> README update 

- ansible/configs/smart-management/README.adoc
README.adoc updated for config:smart-management
> README Update

- ansible/configs/ansible-tower-implementation/README.adoc
- ansible/roles/tower-copy-ssh/README.adoc
- ansible/roles/tower-copy-ssh/README.md
- ansible/roles/tower-credential-create/README.adoc
README.adoc added for Role: tower-credential-create
Role: tower-credential-create
> README.adoc

- ansible/cloud_providers/azure_infrastructure_deployment.yml
- ansible/configs/aro/destroy_env.yml
- ansible/configs/aro/post_software.yml
- ansible/configs/aro/pre_software.yml
- ansible/configs/aro/software.yml
- ansible/roles-infra/infra-azure-create-inventory/tasks/main.yml
- ansible/roles-infra/infra-azure-create-service-principal/tasks/main.yml
- ansible/roles-infra/infra-azure-delete-service-principal/tasks/main.yml
- ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml
- ansible/roles/satellite-register-host/tasks/register.yml
- ansible/roles/set-repositories/tasks/satellite-repos.yml
Reverts redhat-cop/agnosticd#1725
> Revert "Clean-up related to Azure environment variables"

- ansible/configs/three-tier-app/pre_software.yml
ssh keys and configs added to {{student_user}} home
config: three-tier-app
> capability to run ansible from user

- ansible/configs/three-tier-app/post_software.yml
- ansible/configs/three-tier-app/pre_software.yml
password based authentication and user.info added for both cloud providers ec2 & osp. 
> user.info added

- ansible/roles/ocp4-workload-ccnrd/tasks/install-guides.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-username-distribution.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/remove_workload.yml
> Add more helpful links in Username Distribution GUI

- ansible/configs/three-tier-app/env_vars.yml
- ansible/configs/three-tier-app/files/hosts_template.j2
- ansible/configs/three-tier-app/files/repos_template.j2
- ansible/configs/three-tier-app/post_software.yml
1- Support node has been removed, Now we have bastion, frontend, app1, app2 and appdb1(in place of support)
2- support removed from hosts_template.j2.
3- Converted repos_template.j2 to dynamic template.
4- Removed spaces from few lines in post_software.yml.
> Major Update

- ansible/roles/ocp4-workload-ccnrd/files/stack.Dockerfile
> Add npm installation to CRW image

- ansible/configs/three-tier-app/files/hosts_template.j2
- ansible/configs/three-tier-app/post_software.yml
frontend renamed to frontend0 for OSP 
> fixed user info

- ansible/configs/three-tier-app/default_vars_ec2.yml
- ansible/configs/three-tier-app/default_vars_osp.yml
> security rules added

- ansible/configs/three-tier-app/default_vars_osp.yml
rules port changed from 0 to 1 for osp
> Port changed 0 to 1

- ansible/configs/three-tier-app/default_vars_ec2.yml
- ansible/configs/three-tier-app/default_vars_osp.yml
> Minor change

- tests/static/syntax-check.sh
Improve the output of the tests.
- Tests PullRequest
> tests: print output only when it fails

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/threescale/create-tenant.yml
small cleanup tasks for the `ocp4_workload_integreatly` role
role: `ocp4_workload_integreatly`
> ocp4_workload_integreatly: cleanup role

- ansible/configs/ans-tower-lab/default_vars.yml
- ansible/configs/ans-tower-lab/default_vars_ec2.yml
- ansible/configs/ans-tower-lab/default_vars_osp.yml
- ansible/configs/ans-tower-lab/sample_vars_ec2.yml
- ansible/configs/ans-tower-lab/sample_vars_osp.yml
default_{vars,vars_ec2,vars_osp}.yml and sample_vars_{ec2,osp}.yml files added
> Default variable files added

- ansible/configs/ans-tower-lab/files/hosts_template.j2
- ansible/configs/ans-tower-lab/files/repos_template.j2
> new templates added

- ansible/configs/ans-tower-lab/files/hosts_template.j2
- ansible/configs/ans-tower-lab/files/repos_template.j2
- ansible/configs/ans-tower-lab/post_software.yml
- ansible/configs/ans-tower-lab/pre_infra.yml
- ansible/configs/ans-tower-lab/pre_software.yml
Pre and Post software updated
Pre_infra modified 
> Pre & Post software

- ansible/configs/ans-tower-lab/destroy_env.yml
> destroy.yml modified

- ansible/configs/ans-tower-lab/default_vars_ec2.yml
- ansible/configs/ans-tower-lab/default_vars_osp.yml
- ansible/configs/ans-tower-lab/destroy_env.yml
> security group rules

- ansible/roles_ocp_workloads/ocp4_workload_quay_operator/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/workload.yml
needs a workaround to re-enable read/write for the repo PVC.
> Add quay 33 operator workaround

- ansible/roles/ocp4-workload-ccnrd/tasks/install-username-distribution.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
> Improve RHAMT PostgreSQL issue

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/fuse/create-instance.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/threescale/create-tenant.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/tasks/workload.yml
JIRA: https://issues.redhat.com/browse/INTLY-8171
> added retry & delay to k8s blocks

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml
> Replace username-distribution:1.1 tag with latest

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
> Bugfix userid disappear in workshoppoer in Quarkus workshop

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/fuse/create-instance.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/files/threescale/create-tenant.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_integreatly/tasks/workload.yml
Include `until` value in any retry blocks.
Role `ocp4_workload_integreatly`
> Intly 8171 add retry logic to k8s

- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/defaults/main.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/files/operator.yaml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/per_user_operator_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/per_user_pre_operator_workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/tasks/workload.yml
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/templates/opendatahub-operator.v0.5.2.clusterserviceversion.yaml.j2
- ansible/roles/ocp4-workload-rhte-analytics_data_ocp_workshop/templates/opendatahub_v1alpha1_opendatahub_cr.yaml.j2
Fixes error preventing the jupyter notebook from spawning successfully in the Data Engineering workshop. Updates the Open Data Hub deployment to 0.5.2
ocp4-workload-rhte-analytics_data_ocp_workshop
VERIFICATION STEPS:
Deploy the Data Engineering workshop
Login as the user and attempt to spawn a jupyter notebook
the notebook should spawn without any errors displayed
> Fix jupyterhub error in Data Engineering workshop

- ansible/configs/a-base-config/README.adoc
- ansible/configs/a-base-config/default_vars.yml
- ansible/configs/a-base-config/default_vars_azure.yml
- ansible/configs/a-base-config/default_vars_ec2.yml
- ansible/configs/a-base-config/default_vars_osp.yml
- ansible/configs/a-base-config/destroy_env.yml
- ansible/configs/a-base-config/files/cloud_providers/azure_cloud_template.j2
- ansible/configs/a-base-config/files/hosts_template.j2
- ansible/configs/a-base-config/files/repos_template.j2
- ansible/configs/a-base-config/post_infra.yml
- ansible/configs/a-base-config/post_software.yml
- ansible/configs/a-base-config/pre_infra.yml
- ansible/configs/a-base-config/pre_software.yml
- ansible/configs/a-base-config/sample_variables/README.adoc
- ansible/configs/a-base-config/sample_variables/rhel8_server_on_osp.yml
- ansible/configs/a-base-config/sample_variables/sample_vars.yml
- ansible/configs/a-base-config/sample_variables/secrets_example.yml
- ansible/configs/a-base-config/software.yml
a-base-config will be used for an upcoming agnosticD training session.
a-base-config
```paste below
```
> Created a-base-config for training purposes 

- ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/post_workload.yml
Fixes #1861
ocp4_workload_shared_cluster_access workload
*Pending @stencell *
This change will send users useful information to connect with the environment.
Affects user.info through agnosticd_user_info module.
> Include user_info to the final output at OpenTLC

- ansible/configs/selinux-policy/post_software.yml
> update login help with ssh command

- training/01_Introduction/02_What_Is.adoc
> Agd training

- ansible/configs/osp-migration/env_vars.yml
- ansible/configs/osp-migration/infra.yml
Set stack create timeout for os_stack
osp-migration
> Add stack_create_timeout variable

- ansible/configs/ansible-tower-advanced/sample_vars.yml
- ansible/roles_ocp_workloads/ocp4_workload_example/readme.adoc
My git pre-hooks detected a valid AWS key.  Even though the AWS username was obfuscated, it still failed the security test.
config/ansible-tower-advanced
More security checks recommended.
> Dont even hint at revealing AWS keys

- training/02_Getting_Started/01_Introduction.adoc
- training/02_Getting_Started/02_config_your_environment.adoc
- training/02_Getting_Started/06_deploying_a_base_config_osp.adoc
- training/02_Getting_Started/07_deploying_a_base_config_aws.adoc
fixing style and creating index doc
07_deploying_a_base_config_aws.adoc
01_Introduction.adoc
06_deploying_a_base_config_osp.adoc
02_config_your_environment.adoc
> fixing style and creating index doc

- ansible/roles/ocp4-workload-ai-spam-demo-odh/defaults/main.yml
- ansible/roles/ocp4-workload-ai-spam-demo-odh/files/deploy_role.yaml
- ansible/roles/ocp4-workload-ai-spam-demo-odh/files/operator.yaml
- ansible/roles/ocp4-workload-ai-spam-demo-odh/tasks/workload.yml
- ansible/roles/ocp4-workload-ai-spam-demo-odh/templates/opendatahub-operator.v0.5.2.clusterserviceversion.yaml.j2
- ansible/roles/ocp4-workload-ai-spam-demo-odh/templates/opendatahub_v1alpha1_opendatahub_cr.yaml.j2
This PR resolves issues with JupyterHub deploying notebooks in `OpenShift 4 AI/ML Workflows Demo`. The resolves the error in the JupyterHub webui 'Error: Trying to setup service "spark" for user user1: missing "resources" key in definition` when the user attempts to spawn the notebook.
Role `ocp4-workload-ai-spam-demo-odh`
```paste below
```
> Add updates to deploy ODH 0.5.2

- ansible/configs/ansible-advanced/README.adoc
- ansible/configs/ansible-advanced/default_vars.yml
- ansible/configs/ansible-advanced/default_vars_ec2.yml
- ansible/configs/ansible-advanced/default_vars_osp.yml
- ansible/configs/ansible-advanced/destroy_env.yml
- ansible/configs/ansible-advanced/files/hosts_template.j2
- ansible/configs/ansible-advanced/files/hosts_template_backup.j2
- ansible/configs/ansible-advanced/files/repos_template.j2
- ansible/configs/ansible-advanced/files/tower_cli.j2
- ansible/configs/ansible-advanced/post_infra.yml
- ansible/configs/ansible-advanced/post_software.yml
- ansible/configs/ansible-advanced/pre_infra.yml
- ansible/configs/ansible-advanced/pre_software.yml
- ansible/configs/ansible-advanced/requirements.yml
- ansible/configs/ansible-advanced/sample_vars_ec2.yml
- ansible/configs/ansible-advanced/sample_vars_osp.yml
- ansible/configs/ansible-advanced/software.yml
New config ansible advanced for sandbox
env_type: ansible-advanced
> New config: ansible-advanced

- ansible/configs/ansible-advanced/post_software.yml
user info added in post_software_task
env_type: ansible-advanced
> user info added

- ansible/configs/test-empty-config/destroy_env.yml
- ansible/configs/test-empty-config/post_software.yml
Add ACTION variable to `include_role` for bookbag in `test-empty-config`
test-empty-config
> Add test-empty-config set ACTION var

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml
> Update username-distribution:1.2 in Quarkus workshop

- ansible/configs/ansible-advanced/post_software.yml
User info for user.info fixed
env_type: ansible-advance
> user.info fixed

- ansible/configs/ansible-advanced/post_software.yml
user info added for Novello env
env_type: ansible_advanced
> user info for Novello

- ansible/roles/bookbag/tasks/remove_workload.yaml
Fix bookbag role failures when attempt to delete project and project is not found.
bookbag role
> Fix bookbag role to only remove project if found

- ansible/roles_ocp_workloads/ocp4_workload_integreatly/tasks/post_workload.yml
> remove additional quote from rhmi 2.x role

- ansible/configs/ansible-advanced/requirements.yml
gitlab ansible galaxy role added in requirements.yml 
env_type: ansible-advanced
> requirements.yml updated

- ansible/configs/ansible-advanced/requirements.yml
- ansible/configs/ansible-advanced/software.yml
role name updated in requirements.yml
role added in software.yml
> role updated

- training/01_Introduction/03_Configs_Roles.adoc
> Add description of configs to AgnosticD Training Docs

- ansible/roles_ocp_workloads/ocp4_workload_kubevirt/readme.adoc
Update ocp4_kubevirt_workload readme.adoc to fix format
```paste below
```
> Update ocp4_kubevirt_workload readme.adoc to fix format

- ansible/configs/ansible-advanced/requirements.yml
- ansible/configs/ansible-advanced/software.yml
1: Role source changed to organisation.
2: User info added.
env_type: ansible-advanced
> role source updated

- ansible/configs/ansible-advanced/requirements.yml
- ansible/configs/ansible-advanced/software.yml
- ansible/configs/ansible-tower-implementation/default_vars.yml
- ansible/configs/ansible-tower-implementation/files/repos_template.j2
- ansible/configs/ansible-tower-implementation/pre_software.yml
env_type: ansible-tower-implementation
Bugfix:
epel repository issue fixed
> Epel repo fix

- ansible/configs/a-base-config/sample_variables/rhel8_server_on_osp.yml
- ansible/configs/a-base-config/software.yml
Minor style changes & commented example changes to sample var file.
```paste below
```
> Updating sample additions & software.yml for lab

- training/01_Introduction/03_Configs_Roles.adoc
> Adding Content to Training Module 01 [FIX]

- training/01_Introduction/04_Cloud_Provider_Def.adoc
> Add empty line to doc training: 04_Cloud_Provider_Def.adoc

- training/01_Introduction/01_Welcome.adoc
- training/01_Introduction/01a_Dev_Story_Infra.adoc
- training/01_Introduction/01b_Dev_Story_MW.adoc
- training/01_Introduction/04_Cloud_Provider_Def.adoc
> Adding Dev Story to Training

- training/01_Introduction/01b_Dev_Story_MW.adoc
fixing typo in 01b_Dev_Story_MW.adoc
> fixing typo in 01b_Dev_Story_MW.adoc

- training/01_Introduction/03_Configs_Roles.adoc
Updating bold text in training file
> updating bold text in file

- training/01_Introduction/05_AgnosticD_in_Prod.adoc
dev story for infra roles - training
> updating dev story for infra roles (training)

- ansible/configs/osp-migration/post_software.yml
> osp-migration: remove user.info from the message

- ansible/configs/ansible-windows/files/repos_template.j2
Changed static yum repositories to dynamic in env_type: ansible-windows
> yum dynamic repos

- ansible/configs/ansible-windows/files/hosts_template.j2
- ansible/configs/ansible-windows/files/repos_template.j2
host template modified for env_type: ansible-windows
> host template update

- ansible/configs/ansible-windows/env_vars.yml
- ansible/configs/ansible-windows/files/hosts_template.j2
- ansible/configs/ansible-windows/files/repos_template.j2
env_vars.yml modified to support dynamic yum repos in env_type: ansible-windows
> env_vars modifed

- ansible/configs/ansible-windows/destroy_env.yml
- ansible/configs/ansible-windows/env_vars.yml
- ansible/configs/ansible-windows/files/hosts_template.j2
- ansible/configs/ansible-windows/files/repos_template.j2
destroy_env.yml updated with new contents for env_type: ansible-windows
> destroy_env.yml

- ansible/roles/ocp4-workload-jdg-workshop/files/redis-template.yaml
- ansible/roles/ocp4-workload-jdg-workshop/files/stack.Dockerfile
- ansible/roles/ocp4-workload-jdg-workshop/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/install-username-distribution.yaml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/post_workload.yml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/workload.yml
- ansible/roles/ocp4-workload-jdg-workshop/templates/devfile.json.j2
> Add username distribution and update CRW with Quarkus Stack

- ansible/configs/ansible-tower-implementation/default_vars.yml
Repo missing rhel-7-server-ansible-2.9-rpms
default_vars.yaml
> Repo missing rhel-7-server-ansible-2.9-rpms

- ansible/configs/three-tier-app/default_vars.yml
- ansible/configs/three-tier-app/sample_vars_ec2.yml
- ansible/configs/three-tier-app/sample_vars_osp.yml
> repo_version updated

- ansible/configs/smart-management/files/repos_template.j2
- ansible/configs/smart-management/pre_software.yml
- ansible/configs/three-tier-app/default_vars.yml
- ansible/configs/three-tier-app/files/repos_template.j2
- ansible/configs/three-tier-app/sample_vars_ec2.yml
- ansible/configs/three-tier-app/sample_vars_osp.yml
epel repo installation task removed from pre_software.yml
env_type: smart-management
> removed epel repo installation task

- ansible/configs/ansible-tower-implementation/files/repos_template.j2
- ansible/configs/smart-management/files/repos_template.j2
- ansible/configs/smart-management/pre_software.yml
- ansible/configs/three-tier-app/default_vars.yml
- ansible/configs/three-tier-app/files/repos_template.j2
- ansible/configs/three-tier-app/sample_vars_ec2.yml
- ansible/configs/three-tier-app/sample_vars_osp.yml
epel repo updated in repos_template.j2 file
env_type: ansible-tower-implementation
> epel repo modified

- ansible/configs/ansible-tower-implementation/files/repos_template.j2
- ansible/configs/ansible-tower-implementation/pre_software.yml
- ansible/configs/smart-management/files/repos_template.j2
- ansible/configs/smart-management/pre_software.yml
- ansible/configs/three-tier-app/default_vars.yml
- ansible/configs/three-tier-app/files/repos_template.j2
- ansible/configs/three-tier-app/sample_vars_ec2.yml
- ansible/configs/three-tier-app/sample_vars_osp.yml
epel repo installation task removed from pre_software.yml
-
env_type: ansible-tower-implementation
> epel task removed

- ansible/configs/ansible-tower-implementation/files/repos_template.j2
- ansible/configs/ansible-tower-implementation/pre_software.yml
- ansible/configs/smart-management/files/repos_template.j2
- ansible/configs/smart-management/pre_software.yml
- ansible/configs/smart-management/requirements.yml
- ansible/configs/three-tier-app/default_vars.yml
- ansible/configs/three-tier-app/files/repos_template.j2
- ansible/configs/three-tier-app/sample_vars_ec2.yml
- ansible/configs/three-tier-app/sample_vars_osp.yml
requirements.yml modified for satellite-installation galaxy role which is now internal 
env_type: smart-management
> requirements.yml

- ansible/configs/three-tier-app/default_vars.yml
rhel-7-server-ansible-2.9-rpms repo added
default_vars updated
> rhel-7-server-ansible-2.9-rpms repo added

- ansible/configs/ans-tower-lab/default_vars.yml
- ansible/configs/ans-tower-lab/default_vars_ec2.yml
- ansible/configs/ans-tower-lab/sample_vars.yml
- ansible/configs/ans-tower-lab/sample_vars_ec2.yml
tower_version updated.
default_vars.yaml updated.
> Tower version

- ansible/configs/smart-management/files/repos_template.j2
- ansible/configs/smart-management/pre_software.yml
Added a task which removes epel repository from open_{{env_type}}.repo file on satellite.
env_type: smart-management
> added epel repo removed task

- ansible/roles_ocp_workloads/ocp4_workload_project_request_template/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/README.adoc
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/templates/cluster_resource_quota.j2
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/templates/limitrange.j2
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/templates/monitoring_project.j2
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/templates/operator_group.j2
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/templates/subscription_grafana.j2
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/templates/subscription_prometheus.j2
New OCP 4 Workload to set up the Quarkus Experienced ELT environment on a Shared Cluster.
ocp4_workload_quarkus_experienced_elt
> New workload for Quarkus Experienced ELT

- ansible/configs/sap-hana/README.adoc
- ansible/configs/sap-rhvh/README.adoc
- ansible/configs/sap-smart/README.adoc
Add author information to AgnosticD configs
multiple
> Add author information to config's README file

- ansible/roles_ocp_workloads/ocp4_workload_example_shared_cluster/readme.adoc
- training/05_Middleware_on_OpenShift/05_01_Simple_Example_Lab.adoc
Lab 1 formatting for module 5 of training/
training
ocp4_workloads
```paste below
```
> training m05 lab01 WK notes and formatting

- ansible/roles_ocp_workloads/ocp4_workload_project_request_template/templates/project_request_template.j2
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_quarkus_experienced_elt/templates/limitrange.j2
> Add debugging

- training/05_Middleware_on_OpenShift/05_03_Dedicated_Cluster_Example_Lab.adoc
Adds the final lab for ocp4_workload training
roles_ocp_workloads
```paste below
```
> Add training module 5 lab 3

- ansible/roles/ocp4-workload-quarkus-workshop/defaults/main.yml
- ansible/roles/ocp4-workload-quarkus-workshop/readme.adoc
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/verify-workload.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
> Split into 2 modules

- training/05_Middleware_on_OpenShift/05_01_Simple_Example_Lab.adoc
Mass changes based on Nate's branch: command  and instructions updating. Noelia added oc client install instructions, references to OpenShift Documentation and Ansible documentation.
> Update and Expand lab 03_01

- ansible/roles/ocp4-workload-ccnrd/tasks/install-username-distribution.yaml
Add a new feature to enable individually block/unblock userids from admin GUI 
install-username-distribution.yaml
```paste below
```
> Add new feature in username distribution in CCN

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml
Add a new feature to enable individually block/unblock userids from admin GUI
install-username-distribution.yaml
```paste below
```
> Add new feature in username distribution in Quarkus Workshop

- docs/Contributing.adoc
*MInor* stylistic changes to the Contributors guide.
No changes to general rules and guidelines
docs/Contributing.adoc
Minor changes, more substantive changes will require discussion etc
> Updates Contributors guide - wording changes, stylistic etc

- ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile
- ansible/roles/ocp4-workload-quarkus-workshop/meta/main.yml
Added new Metadata and update Quarkus version(1.3.4) in Quarkus workshop
```paste below
```
> Add new Meta data and update Quarkus version in Quarkus workshop

- ansible/roles/ocp4-workload-jdg-workshop/files/stack.Dockerfile
- ansible/roles/ocp4-workload-jdg-workshop/meta/main.yml
- ansible/roles/ocp4-workload-jdg-workshop/tasks/install-username-distribution.yaml
Add a new feature to enable individually block/unblock userids from admin GUI
install-username-distribution.yaml
```paste below
```
> Add new feature in username distribution in JDG workshop

- ansible/roles/ocp4-workload-ccnrd/files/stack.Dockerfile
- ansible/roles/ocp4-workload-ccnrd/meta/main.yml
Add metadata and update RHBQ version 1.3.4.Final
stack.Dockerfile
meta/main.yml
```paste below
```
> Add metadata and update RHBQ version

- ansible/configs/three-tier-app/default_vars_ec2.yml
- ansible/configs/three-tier-app/post_software.yml
- ansible/configs/three-tier-app/pre_software.yml
- ansible/configs/three-tier-app/setup_lab_user.yml
1: Image update now it is RHEL77
2: New task file setup_lab_user.yml added which creates lab-user to run lab instructions.
3: Clean up done in default_vars_ec2.yml and pre_software.yml
> Added few task in config three-tier-app 

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml
Fixess #2093 
```paste below
```
> Added workaround for installing RHACM on OCP 4.2+, Fixes #2093

- ansible/configs/ocp4-cluster/default_vars_azure.yml
This will make the naming consistent with outer workloads that RHPDS is deploying in to the subscription (aro3 and aro4)
N/A
> Updating cluster_name for Azure in ocp4-cluster

- ansible/configs/ansible-tower-implementation/action_plugins
- ansible/configs/ansible-tower-implementation/default_vars.yml
- ansible/configs/ansible-tower-implementation/default_vars_ec2.yml
- ansible/configs/ansible-tower-implementation/files/hosts_template.j2
- ansible/configs/ansible-tower-implementation/files/repos_template.j2
- ansible/configs/ansible-tower-implementation/post_software.yml
- ansible/configs/ansible-tower-implementation/sample_vars/sample_vars_ec2.yml
- ansible/configs/ansible-tower-implementation/setup_lab_user.yml
- ansible/configs/three-tier-app/default_vars_ec2.yml
- ansible/configs/three-tier-app/post_software.yml
- ansible/configs/three-tier-app/pre_software.yml
- ansible/configs/three-tier-app/setup_lab_user.yml
1: Delete -> action_plugins directory deleted from config 
2: Modify: host_template.j2 is modified to work with ec2 cloud provider
3: Modify: repos_template.j2, repo_version variable added to repo baseurl
4: Modify: default_vars.yml, cleanup and variable addition
5- Modify:  default_vars_ec2.yml, prepared for ec2 cloud provider
6- Modify: post-software.yml, user.info entry updated for multi cloud providers
7- Create: setup_lab_user.yml, lab user tasks
env_type: ansible-tower-implementation
> Enhancement config: ansible-tower-implementation

- ansible/roles/git-copy-files/tasks/main.yml
modified static git server name to variable
Role: git-copy-files
> fix add git_server variable

- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
Remove Service Mesh installation condition in M4 of CCN Dev Track
workload.yml
```paste below
```
> Remove Service Mesh installation condition in M4 of CCN Dev Track

- ansible/configs/sap-rhvh/post_software.yml
Add retries while getting SSH Key from Manager to prevent random isses when not ready
sap-rhvh
> Add retries while getting SSH Key from Manager

- docs/Variables.adoc
Add variable documentation for __meta__ and agnosticv_meta and fix underscore evaluation in asciidoc.
Variable documentation.
> Add variable documentation for __meta__ and agnosticv_meta

- ansible/configs/ocp4-ha-lab/requirements.yml
FIX ocp4-ha-lab to fix ocp4 infra homework
config ocp4-ha-lab
```paste below
```
> FIX ocp4-ha-lab to fix ocp4 infra homework  - increment ftl-injector version

- ansible/roles/set-repositories/tasks/unregister.yml
Add role to unregister from subscription manager.
Add role to unregister from subscription manager.
> Add subscription-manager unregister

- ansible/configs/ansible-tower-implementation/default_vars.yml
- ansible/configs/ansible-tower-implementation/default_vars_ec2.yml
- ansible/configs/ansible-tower-implementation/default_vars_osp.yml
- ansible/configs/ansible-tower-implementation/sample_vars/ec2_vars.yml
- ansible/configs/ansible-tower-implementation/sample_vars/osp_vars.yml
Done some clean up in default and sample variable files.
> Clean up config:ansible-tower-implementation

- ansible/configs/ansible-tower-implementation/setup_lab_user.yml
1: Task file setup_lab_user.yml added
config/env_type: ansible-tower-implementation
> Add setup_lab_user.yml config:ansible-tower-implementation

- ansible/configs/ansible-tower-implementation/post_software.yml
- ansible/configs/ansible-tower-implementation/pre_software.yml
- ansible/configs/ansible-tower-implementation/setup_lab_user.yml
- ansible/configs/ansible-tower-implementation/software.yml
1: Modify- pre_software.yml
2: Modify- Post_software.yml
3: Modify- software.yml
aligned all content as par latest practice. 
> Fix config ansible-tower-implementation

- ansible/configs/ansible-tower-implementation/default_vars_osp.yml
- ansible/configs/ansible-tower-implementation/post_software.yml
- ansible/configs/ansible-tower-implementation/pre_software.yml
- ansible/configs/ansible-tower-implementation/setup_lab_user.yml
- ansible/configs/ansible-tower-implementation/software.yml
Modified security rules parameter
> Minor change ansible-tower-implementation

- ansible/configs/ans-tower-lab/default_vars_ec2.yml
- ansible/configs/ans-tower-lab/default_vars_osp.yml
- ansible/configs/ans-tower-lab/files/repos_template.j2
- ansible/configs/ans-tower-lab/post_software.yml
- ansible/configs/ans-tower-lab/pre_software.yml
- ansible/configs/ans-tower-lab/sample_vars_ec2.yml
- ansible/configs/ans-tower-lab/sample_vars_osp.yml
1: default variables files updated for security rules
2: Pre and Post software.yml updated with few new contents
3: setup_lab_user.yml update with few changes
> Modify config:ans-tower-lab

- ansible/configs/ans-tower-lab/files/ssh_config.j2
- ansible/configs/ans-tower-lab/setup_lab_user.yml
lab_user setup config file added 
> Added lab_user setup

- ansible/cloud_providers/ibm_infrastructure_deployment.yml
- ansible/roles-infra/infra-ibm-rg-creation/tasks/main.yml
- ansible/roles-infra/infra-ibm-sshkey-upload/tasks/main.yml
- ansible/roles-infra/infra-ibm-sshkey-upload/tasks/upload_sshkey.yml
- ansible/roles-infra/infra-ibm-template-create/tasks/main.yml
- ansible/roles-infra/infra-ibm-template-generate/tasks/generate_ibm_template.yml
- ansible/roles-infra/infra-ibm-template-generate/tasks/locate_template.yml
- ansible/roles-infra/infra-ibm-template-generate/tasks/main.yml
- ansible/roles-infra/infra-ibm-workspace-create/tasks/create_ibm_workspace.yml
- ansible/roles-infra/infra-ibm-workspace-create/template/workspace-template.json.j2
To be reviewed and merged by @stencell 
This PR provides a WIP progress to the ibm cloud provider and also templates and logic to the IBM provider sandbox-style deploy
First approach to IBM Cloud provider, and IBM roles-infra
Considering this PR is not affecting the 'development' branch, please avoid to merge.
> Add more logic to the ibm cloud provider branch

- ansible/configs/ansible-advanced/software.yml
Gitlab role removed. 
software.yaml updated.
> Role removed

- ansible/configs/ansible-tower-implementation/post_software.yml
user.info changed. 
user.info changed.
Changes: access Red Hat Ansible Tower console via browser
> Changed To access Red Hat Ansible Tower console via browser

- ansible/configs/ansible-tower-implementation/files/ssh_config.j2
- ansible/configs/ansible-tower-implementation/setup_lab_user.yml
fix lab-user (devops) to run all linux commands
> Fix lab-user for config:ansible-tower-implementation

- ansible/configs/ansible-tower-implementation/files/ssh_config.j2
- ansible/configs/ansible-tower-implementation/post_software.yml
- ansible/configs/ansible-tower-implementation/setup_lab_user.yml
License copy task removed from post_software because it is part of setup-lab-user.yml now
> Cleaned up 

- ansible/roles/ocp4-workload-jdg-workshop/tasks/confirm_che_workspace.yaml
Add Output warning message in DG workshop
confirm_che_workspace.yaml
```paste below
```
> Change workload of ocp4-workload-jdg-workshop to add Output warning message

- ansible/roles/ocp4-workload-ml-workflows-infra-summit2020/templates/pipelines/subscription.yml.j2
- ansible/roles/ocp4-workload-ml-workflows-workshop/templates/pipeline-definition.yaml.j2
- Use OpenShift Pipelines v1.0.1 (Red Hat)
- Update pipeline definition to account for Tekton 'kn' task changes
> Update Openshift Pipelines setup

- ansible/roles-infra/infra-osp-template-generate/templates/nested_version/cloud_template_master.j2
This PR changes the indentation style in the infra-osp-template-generate infra role to more easily match if/endif and for/endfor pairs.
roles-infra/infra-osp-template-generate
> Change roles-infra infra-osp-template-generate jinja indent

- ansible/configs/ansible-tower-implementation/post_software.yml
Added two more info lines in user.info 
> Added info in user.info

- ansible/configs/sap-smart/post_software.yml
Install katello agent package and enable Sat host for remote execution over registered SAP hosts
sap-smart
> Install katello agent package and enable Sat host for remote execution

- ansible/roles_ocp_workloads/ocp4_workload_app_deploy_ilt/readme.adoc
> Update config ocp4-cluster add gogs reference in readme.adoc

- ansible/configs/ans-tower-lab/post_software.yml
- ansible/configs/ans-tower-lab/pre_software.yml
- ansible/configs/ansible-tower-implementation/post_software.yml
1: Modify- pre_software to work with ansible tower homework lab
2: Modify- post_software, user.info messages
> Modify config ans-tower-lab

- ansible/configs/ans-tower-lab/files/tower_cli.j2
- ansible/configs/ans-tower-lab/sample_vars/ec2_vars.yml
- ansible/configs/ans-tower-lab/sample_vars/homework_ec2_vars.yml
- ansible/configs/ans-tower-lab/sample_vars/osp_vars.yml
1: Added sample_vars directory and moved sample_variables files under this directory
2: Added tower_cli.j2 template file. 
> Add config: ans-tower-lab

- ansible/configs/ans-tower-lab/files/tower_cli.j2
- ansible/configs/ans-tower-lab/sample_vars/ec2_vars.yml
- ansible/configs/ans-tower-lab/sample_vars/homework_ec2_vars.yml
- ansible/configs/ans-tower-lab/sample_vars/osp_vars.yml
- ansible/configs/ans-tower-lab/setup_lab_user.yml
Modify setup_lab_user.yml and added .vimrc entries for devops user
> Modify setup_lab_user.yml

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhsso.yaml
Fix ocp4-workload-quarkus-workshop to add RH-SSO healthcheck
```paste below
```
> Fix ocp4-workload-quarkus-workshop to add RH-SSO healthcheck

- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/cluster_role.j2
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/cluster_role_binding.j2
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/crd.j2
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/gitea.j2
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/operator.j2
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/project.j2
- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/service_account.j2
Added OpenShift workload to deploy the Gitea Operator along with an (optional) Gitea Instance.
As per request of Erik.
> Added ocp4_workload_gitea_operator

- ansible/roles/ocp4-workload-jdg-workshop/tasks/verify-workload.yaml
Remove verification of custom realm
```paste below
```
> Remove ocp4-workload-jdg-workshop for verification of custom realm

- ansible/configs/ansible-windows/files/cloud_providers/ec2_cloud_template.j2
Update WIN2012R2AMI to Windows_Server-2012-R2_RTM-English-64Bit-Base-2020.06.10 as old image was no longer available.
ansible-windows config
> Update config ansible-windows to new ami

- ansible/configs/test-empty-config/post_software.yml
> fix test-empty-config: don't gather facts

- ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
These changes will cause user.info to be output depending on which
booleans are enabled. It will output the values that the settings for
the booleans control.
> Adds user.info output to gitea operator role

- ansible/roles/ocp4-workload-debezium-demo/defaults/main.yaml
- ansible/roles/ocp4-workload-debezium-demo/readme.adoc
- ansible/roles/ocp4-workload-debezium-demo/tasks/main.yml
- ansible/roles/ocp4-workload-debezium-demo/tasks/post_workload.yml
- ansible/roles/ocp4-workload-debezium-demo/tasks/pre_workload.yml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_e2e_demo.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_mysql_demo.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_pgsql_demo.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_streams.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/provision_webapp.yaml
- ansible/roles/ocp4-workload-debezium-demo/tasks/remove_workload.yml
- ansible/roles/ocp4-workload-debezium-demo/tasks/workload.yml
- ansible/roles/ocp4-workload-debezium-demo/templates/apache-php-app.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/configmap-data-sql.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/debezium-tooling.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/elasticsearch.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/extra-services.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connect.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connector-elastic.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connector-mssql.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-connector-mysql.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/kafka-demo.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/mssql-server-linux.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/mysql.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/oauthclient.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/postgresql.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/scc-anyuid.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/streams-subscription.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/tutorial-web-app.yaml.j2
- ansible/roles/ocp4-workload-debezium-demo/templates/webapp.yaml.j2
This is a 3 demo scenarios to show change data capture with debezium and kafka
debezium-demo
```paste below
```
> cdc with debezium and kafka demos

- ansible/roles/control-user/README.adoc
- ansible/roles/control-user/defaults/main.yml
- ansible/roles/control-user/files/.vimrc
- ansible/roles/control-user/meta/main.yml
- ansible/roles/control-user/tasks/copy-contents.yml
- ansible/roles/control-user/tasks/copy-files.yml
- ansible/roles/control-user/tasks/copy-templates.yml
- ansible/roles/control-user/tasks/create-directory.yml
- ansible/roles/control-user/tasks/create-user.yml
- ansible/roles/control-user/tasks/main.yml
- ansible/roles/control-user/tasks/ssh-config.yml
- ansible/roles/control-user/templates/ssh_config.j2
Added new role called control-user which creates devops like user to run lab instructions instead using root. 
role: control-user
> Add new role:control-user

- ansible/roles/gitlab-server/README.adoc
- ansible/roles/gitlab-server/defaults/main.yml
- ansible/roles/gitlab-server/meta/.galaxy_install_info
- ansible/roles/gitlab-server/meta/main.yml
- ansible/roles/gitlab-server/tasks/firewalld.yml
- ansible/roles/gitlab-server/tasks/install-gitlab-server.yml
- ansible/roles/gitlab-server/tasks/main.yml
- ansible/roles/gitlab-server/templates/gitlab-root-password.sh
- ansible/roles/gitlab-server/templates/gitlab-root-token.sh
New role added which installs gitlab server and sets gitlab root token
role: gitlab-server
> New Role gitlab-server

- ansible/roles/handle-course-data-pntae/README.adoc
- ansible/roles/handle-course-data-pntae/tasks/get_course_data.yml
- ansible/roles/handle-course-data-pntae/tasks/get_coursescript.yml
- ansible/roles/handle-course-data-pntae/tasks/main.yml
- ansible/roles/handle-course-data-pntae/tasks/run_course_scripts-adv.yml
- ansible/roles/handle-course-data-pntae/tasks/run_course_scripts.yml
This role handles PNTAE's course specific data for the published catalog.
When this role is included in pntae's catalog, it enables PNTAE's content developers
to make necessary modifications to the catalog without using agnosticd.
handle-course-data-pntae
PNTAE's content developers can push all the necessary modifications for the catalog
at PNTAE's git repository or any other public url and the training catalog will pull
and execute the data from there.
```paste below
```
> Handle course data pntae

- ansible/roles/gitlab-config/README.md
- ansible/roles/gitlab-config/defaults/main.yml
- ansible/roles/gitlab-config/meta/main.yml
- ansible/roles/gitlab-config/tasks/create-group.yml
- ansible/roles/gitlab-config/tasks/create-project.yml
- ansible/roles/gitlab-config/tasks/create-user.yml
- ansible/roles/gitlab-config/tasks/main.yml
New role added gitlab-config which creates user,group and project in gitlab server.
role: gitlab-config
> New role gitlab-config

- ansible/configs/ansible-gitOps-integration/README.adoc
- ansible/configs/ansible-gitOps-integration/default_vars.yml
- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
- ansible/configs/ansible-gitOps-integration/destroy_env.yml
- ansible/configs/ansible-gitOps-integration/files/clouds.yaml.j2
- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
- ansible/configs/ansible-gitOps-integration/files/repos_template.j2
- ansible/configs/ansible-gitOps-integration/files/ssh_config.j2
- ansible/configs/ansible-gitOps-integration/files/tower_cli.j2
- ansible/configs/ansible-gitOps-integration/post_infra.yml
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/pre_infra.yml
- ansible/configs/ansible-gitOps-integration/pre_software.yml
- ansible/configs/ansible-gitOps-integration/requirements.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/ec2_vars.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
- ansible/configs/ansible-gitOps-integration/software.yml
New config created for RHTE, called ansible-gitOps-integration, which installs control (as bastion), utility(gitlab server) and tower (Ansible Tower) nodes by default.
> New Config:ansible-gitOps-integration for RHTE

- ansible/configs/ansible-gitOps-integration/files/gitconfig.j2
Added gitconfig.j2 Jinja template 
> Added gitconfig.j2 config:ansible-gitOps-intergration

- ansible/configs/ansible-gitOps-integration/files/gitconfig.j2
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
> Modify sample vars

- ansible/configs/ansible-gitOps-integration/files/gitconfig.j2
- ansible/configs/ansible-gitOps-integration/files/ssh_config.j2
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
Modify ssh_config.j2 template to work with gitlab
> Modify ssh_config.j2

- ansible/configs/ansible-gitOps-integration/files/gitconfig.j2
- ansible/configs/ansible-gitOps-integration/files/ssh_config.j2
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
- ansible/configs/ansible-gitOps-integration/software.yml
Bugfix by added selinux context task in software.yml
> Bugfix for gitlab

- ansible/configs/ansible-gitOps-integration/files/gitconfig.j2
- ansible/configs/ansible-gitOps-integration/files/ssh_config.j2
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/pre_software.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
- ansible/configs/ansible-gitOps-integration/software.yml
Modify variables to setup common password for everything 
> Modify variables

- ansible/configs/ansible-gitOps-integration/files/gitconfig.j2
- ansible/configs/ansible-gitOps-integration/files/ssh_config.j2
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/pre_software.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
- ansible/configs/ansible-gitOps-integration/software.yml
Modify variables value to strong password
> Modify variables in software.yml

- PULL_REQUEST_TEMPLATE.md
> Pr template

- ansible/configs/selinux-policy/post_software.yml
Adding Bookbag Deploy Task
Adding bookbag deploy task for testing
bookbag
> Update post_software.yml in SELinux Policy Summit Lab

- ansible/configs/selinux-policy/post_software.yml
Updating indentation... again... -_-
Put task in the right place
> Update bookbag task in post_software.yml

- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
- ansible/configs/ansible-gitOps-integration/files/gitconfig.j2
- ansible/configs/ansible-gitOps-integration/files/ssh_config.j2
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/pre_software.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
- ansible/configs/ansible-gitOps-integration/software.yml
Modify security group to open port 22 for utility node
> Modify ansible-gitOps-integration Security Group

- ansible/configs/ansible-gitOps-integration/pre_software.yml
Added tower-admin-password setup task
> Add task ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/files/pip-requirements.txt
Bugfix
cryptography==2.4.2 version fixed
```
> BugFix: ansible-gitOps-integration config

- ansible/configs/ocp4-ha-lab/files/install-config.yaml.j2
- ansible/configs/ocp4-workshop/files/install-config.yaml.j2
- ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Add documentation explaining quoting of ocp4_pull_secret for OpenShift install-config.yaml.
ocp4-ha-lab config
host-ocp4-installer role
> Add jinja comment describing pullSecret escape

- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/templates/argocr.j2
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/templates/catalogsource.j2
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/templates/clusterrolebinding.j2
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/templates/operatorgroup.j2
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/templates/operatorsubscription.j2
- ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/templates/project.j2
* supports catalog snapshots
* doesn't support much of the argo CR
* pretty basic
ocp4_workload_argocd_operator
> ArgoCD Operator

- ansible/configs/ansible-tower-pntae/post_software.yml
ansible-tower-pntae
This config is for pntae's ansible-tower related trainings. This is based on ansible-tower-implementation catalog with few modifications in it.
```paste below
```
> Added handle-course-data-pntae role

- ansible/roles/ocp-workload-pam7-offer-management-dmn-pmml/tasks/rhpam_openshift_dmn_pmml_workload.yml
Added "--wait=true" for binary builds.
ocp-workload-pam7-offer-management-dmn-pmml
> Added wait to binary build.

- ansible/configs/rhel-custom-security-content/post_software.yml
Add bookbag ansible role to workshop's deployment.
> Enable automated bookbag deployment for RHEL Custom Security Content.

- ansible/configs/ansible-tower-implementation/setup_lab_user.yml
> Fix for when condition

- ansible/configs/ansible-tower-implementation/setup_lab_user.yml
- ansible/roles/control-user/README.adoc
- ansible/roles/control-user/defaults/main.yml
- ansible/roles/control-user/tasks/main.yml
- ansible/roles/control-user/tasks/ssh-config.yml
Removed and modified variables
1: defaults/main.yml 
2: tasks/main.yml
3: README.adoc
4: tasks/ssh-config.yml
role: control-user
> Updated role control-user

- ansible/configs/three-tier-app/setup_lab_user.yml
Added bool in condition in setup_lab_user.yml
config three-tier-app
> Added bool config three-tier-app

- ansible/configs/ansible-tower-implementation/default_vars_ec2.yml
ARY
t3.medium not available in us-east-1e AZ.
instance type
> instance type changed

- ansible/configs/three-tier-app/post_software.yml
- ansible/configs/three-tier-app/sample_vars_ec2.yml
- ansible/configs/three-tier-app/sample_vars_osp.yml
- ansible/configs/three-tier-app/setup_lab_user.yml
Following files modified to replace setup_lab_user.yml with control-user role
1: post_software.yml
2: sample_vars_osp.yml
3: sample_vars_ec2.yml
config: three-tier-app
> Modify config three-tier-app

- ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile
- ansible/roles/ocp4-workload-quarkus-workshop/files/stack_imagestream.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml
- ansible/roles/ocp4-workload-quarkus-workshop/templates/devfile.json.j2
Update OCP 4.5.3 in Quarkus workshop. The base OCP image should be upgraded to OCP 4.5.3 to merge this PR.
```paste below
```
> Update OCP 4.5.3 in Quarkus workshop

- ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml
Fix ocp4-workload-quarkus-workshop to update guide repository
```paste below
```
> Fix ocp4-workload-quarkus-workshop to update guide repository

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml
Better checks for the availability of the RHACM subscription and multiclusterhub resource.
> Change workload ocp4_workload_rhacm

- ansible/roles/tower-installation/README.adoc
- ansible/roles/tower-installation/defaults/main.yml
- ansible/roles/tower-installation/tasks/configure_tower_cli.yml
- ansible/roles/tower-installation/tasks/main.yml
- ansible/roles/tower-installation/tasks/setup_tower.yml
- ansible/roles/tower-installation/templates/inventory.j2
- ansible/roles/tower-installation/templates/tower_cli.j2
New role tower-installation which is very dynamic and have variables to provides inputs according to the requirement of the config.
role: tower-installation
> New role tower-installation

- ansible/configs/ansible-tower-pntae/post_software.yml
bugfix for ansible-tower-pntae
moved the pntae's customization before flight-check
```paste below
```
> ansible-tower-pntae: move handle-pntae-data before flight-check

- ansible/roles/tower-auth-integration/README.adoc
- ansible/roles/tower-auth-integration/tasks/ldap_auth.yml
- ansible/roles/tower-auth-integration/tasks/main.yml
- ansible/roles/tower-auth-integration/templates/variables_template.j2
New role named 'tower-auth-integration'  which integrates tower with ldap for authentication
Role: tower-auth-integration
> New role tower-auth-integration

- ansible/roles/rhel-graphical/tasks/main.yml
Remove undefined variable to prevent ansible errors.
rhel-graphical
> Remove undefined variable to prevent ansible errors.

- ansible/roles/rhel-graphical/tasks/main.yml
Revert back conditionals to test RHEL versions.
rhel-graphical
> Revert back conditionals to test RHEL versions.

- ansible/configs/ansible-gitOps-integration/lets-encrypt-nginx.yml
Added task file for generating lets encrypt certificate
> Add tasks ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
- ansible/configs/ansible-gitOps-integration/lets-encrypt-nginx.yml
Modify host_template.j2 template
> Modify config ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
- ansible/configs/ansible-gitOps-integration/lets-encrypt-nginx.yml
- ansible/configs/ansible-gitOps-integration/post_software.yml
Included lets-encrypt tasks in post_software.yml
> Modify ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
- ansible/configs/ansible-gitOps-integration/lets-encrypt-nginx.yml
- ansible/configs/ansible-gitOps-integration/post_software.yml
testserver ec2 instance added in default_vars_ec2.yml
> Added ec2 instances ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
- ansible/configs/ansible-gitOps-integration/lets-encrypt-nginx.yml
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/ec2_vars.yml
sample_ec2.yml updated with instance info
> Update sample_ec2 ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
- ansible/configs/ansible-gitOps-integration/lets-encrypt-nginx.yml
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/ec2_vars.yml
testserver added in osp default variable file
> Update osp instance ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
- ansible/configs/ansible-gitOps-integration/lets-encrypt-nginx.yml
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/ec2_vars.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
variables updated for sample_vars/osp
> Update osp variables ansible-gitOps-integration

- ansible/configs/ans-tower-lab/default_vars_ec2.yml
default_vars_ec2.yaml updated. bastion name changed to control as standard for all AA courses.
ans-tower-lab
> Feature Pull Request: bastion name changed to control

- ansible/configs/ans-tower-lab-ng/README.adoc
- ansible/configs/ans-tower-lab-ng/default_vars.yml
- ansible/configs/ans-tower-lab-ng/default_vars_ec2.yml
- ansible/configs/ans-tower-lab-ng/default_vars_osp.yml
- ansible/configs/ans-tower-lab-ng/destroy_env.yml
- ansible/configs/ans-tower-lab-ng/files/hosts_template.j2
- ansible/configs/ans-tower-lab-ng/files/repos_template.j2
- ansible/configs/ans-tower-lab-ng/files/ssh_config.j2
- ansible/configs/ans-tower-lab-ng/files/tower_cli.j2
- ansible/configs/ans-tower-lab-ng/post_infra.yml
- ansible/configs/ans-tower-lab-ng/post_software.yml
- ansible/configs/ans-tower-lab-ng/pre_infra.yml
- ansible/configs/ans-tower-lab-ng/pre_software.yml
- ansible/configs/ans-tower-lab-ng/requirements.yml
- ansible/configs/ans-tower-lab-ng/sample_vars/ec2_vars.yml
- ansible/configs/ans-tower-lab-ng/sample_vars/homework_ec2_vars.yml
- ansible/configs/ans-tower-lab-ng/sample_vars/osp_vars.yml
- ansible/configs/ans-tower-lab-ng/setup_lab_user.yml
- ansible/configs/ans-tower-lab-ng/software.yml
- ansible/configs/ans-tower-lab-ng/test-homework-fix.sh
> New config request: Ansible Adnvance Tower LAB NG

- ansible/configs/ans-tower-lab-ng/post_software.yml
user info updated.
ans-tower-lab-ng post_software.yml
> User info updated

- ansible/configs/ansible-multitier-infra/post_software.yml
bastion hostname changed to control.
> bastion hostname changed

- ansible/configs/ans-tower-lab-ng/default_vars_ec2.yml
Replaced t3 instance type to t2 multiple failures in past in us-east-1e AZ
> control node instance type changed

- ansible/configs/osp-migration/pre_infra.yml
Remove environment variable OS_CACERT
osp-migration
> Remove OS_CACERT from pre_infra

- ansible/roles/ocp4-workload-dil-streaming/tasks/provision_shared.yaml
- ansible/roles/ocp4-workload-dil-streaming/templates/che-devfile.yaml.j2
- ansible/roles/ocp4-workload-dil-streaming/templates/configmap-data-sql.yaml.j2
- ansible/roles/ocp4-workload-dil-streaming/templates/mssql-server-linux.yaml.j2
- ansible/roles/ocp4-workload-dil-streaming/templates/scc-anyuid.yaml.j2
Fixes https://github.com/RedHatWorkshops/dayinthelife-streaming/issues/7
Database initialization is not working when installing, moving to persistent store and fix the initialization process to wait for the database to be deployed
```paste below
```
> make db persistent

- ansible/configs/ocp4-disconnected-osp-lab/files/general-ms.yaml.j2
Update ILT MachineSet template to core os 4.5
> Updated machineset template for OCP 4.5

- ansible/configs/ansible-tower-pntae/default_vars_osp.yml
- ansible/configs/ansible-tower-pntae/post_software.yml
Install GUI on tower VM
and enable console access for the catalog
```paste below
```
> ansible-tower-pntae changes to enable console access and

- ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
The URL for the `istioctl` download changed. This updates it in the task.
ocp4_workload_studentvm
> Updated role ocp4_workload_studentvm

- ansible/roles_studentvm/studentvm_ocp4/tasks/main.yml
> Fixed istioctl download path

- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
Removed extra endfor from hosts_template.j2 template
> Bugfix ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
- ansible/configs/ansible-gitOps-integration/rh_event.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
Added event task file for tower load
> Added Task file ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/files/hosts_template.j2
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/rh_event.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
Included event tasks in post_software.yml
> Add ansible-gitOps-integration

- ansible/roles/ocp-workload-bxms-pam/defaults/main.yml
workload was deploying a bad version of nexus.
ocp-workload-bxms-pam
> nexus update for CVE

- ansible/roles/tower-installation/tasks/awx_cli.yml
- ansible/roles/tower-installation/tasks/tower_cli.yml
Added two task files for awx_cli and tower_cli 
role: tower-installation
> Update role tower-installation

- ansible/roles/tower-installation/tasks/awx_cli.yml
- ansible/roles/tower-installation/tasks/tower_cli.yml
- ansible/roles/tower-installation/templates/awx_rc.j2
- ansible/roles/tower-installation/templates/tower_cli.j2
1: Modified tower_cli.j2
2: Added awx_clli.j2 template
role: ansible-installation
> Added template role: ansible-installation

- ansible/roles/ocp4-workload-ccnrd/defaults/main.yml
- ansible/roles/ocp4-workload-ccnrd/files/mta-template.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/add_mta_user.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-guides.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/install-mta.yaml
- ansible/roles/ocp4-workload-ccnrd/tasks/workload.yml
RHMAT 4.3.1 product is changed to MTA 5.0 recently so CCN workshop(module 1) needs to upgrade for this.
```paste below
```
> Update ocp4-workload-ccnrd for upgrade MTA 5.0 from RHAMT 4.3.1

- ansible/configs/three-tier-app/files/repos_template.j2
Modify baseurl 
config three-tier-app
> Modify baseurl three-tier-app

- ansible/configs/ans-tower-lab/files/repos_template.j2
> Epel repo url changed

- ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/tasks/wait_for_deploy.yml
Fix OCP_PROJECT variable name in wait for deploy script.
ocp-workload-pam7-cc-dispute-dmn-pmm
> Fixed project variable in wait for deploy scripts.

- ansible/configs/hacluster-pntae/pre_software.yml
remove task for disabling beta repo
```paste below
```
> hacluster-pntae: remove task for disabling beta repository

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/defaults/main.yml
The z-stream for ACM was bumped and we are not using an offline catalog yet. This PR bumps the CSV to 2.0.1.
> Update role ocp4_workload_rhacm to new CSV

- ansible/roles_ocp_workloads/ocp4_workload_rhacm/defaults/main.yml
There is a new release of ACM. Until we set up the offline operator catalog, this is needed to accommodate the new version.
> Update role ocp4_workload_rhacm with new release

- ansible/configs/rhel-security/default_vars.yml
The flavors were identified incorrectly.
rhel-security
> Update config rhel-security flavor dict

- ansible/configs/rhel-security/default_vars.yml
> Update rhel-security flavor instance type

- ansible/roles_ocp_workloads/ocp4_workload_jenkins/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/readme.adoc
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/tasks/deploy_jenkins.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/catalogsource.j2
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/installplan.j2
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/jenkins.j2
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/operatorgroup.j2
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/project.j2
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/pvc.j2
- ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/subscription.j2
New workload to be used for the RHTR Pipelines Lab: Deploy the Jenkins Operator and set up a Jenkins instance.
ocp4_workload_jenkins
> Initial version of the Jenkins Operator Workload

- ansible/roles/ocp4-workload-ml-workflows-infra-summit2020/templates/serverless/subscription.yml.j2
Bug Fix - updating serverless channel to 4.3
> update serverless subscription channel

- ansible/roles_ocp_workloads/ocp4_workload_nexus_operator/tasks/workload.yml
> Add missing check for nexus pod deployment

- ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/workload.yml
Move nexus config from role to agnosticv
> Remove Nexus Repo customization from starter lab

- ansible/configs/ansible-gitOps-integration/files/pip-requirements.txt
Added specific version of request module and updated cryptography python module version
> Updated pip-requirements ansible-gitOps-integration

- ansible/configs/rhel-security/post_software.yml
Deploy bookbag documentation in RHEL Security lab.
rhel-security
> Add bookbag deployment in RHEL Security lab.

- ansible/configs/ansible-gitOps-integration/default_vars.yml
Added python-modules based on rpm  instead pip  based
> python packages added config:ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/default_vars.yml
- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
To install vscode server open port 80 and 443 in control node
> Open port 80 and 443 config:ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/default_vars.yml
- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
- ansible/configs/ansible-gitOps-integration/pre_software.yml
vscode-server and control-user role added in pre-sorftware.yml file.
> vscode-server added config:ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/default_vars.yml
- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/pre_software.yml
clean up and user.info added in post_software.yml
> Cleanup and user.info updated config:ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/default_vars.yml
- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/pre_software.yml
- ansible/configs/ansible-gitOps-integration/software.yml
Done clean up for setting strong password in for gitlab server in software.yml
> Clean up in software.yml config:ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/README.adoc
- ansible/configs/ansible-gitOps-integration/default_vars.yml
- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/pre_software.yml
- ansible/configs/ansible-gitOps-integration/rh_event.yml
- ansible/configs/ansible-gitOps-integration/software.yml
> Doc update config:ansible-gitOps-integration

- ansible/configs/ansible-gitOps-integration/README.adoc
- ansible/configs/ansible-gitOps-integration/default_vars.yml
- ansible/configs/ansible-gitOps-integration/default_vars_ec2.yml
- ansible/configs/ansible-gitOps-integration/default_vars_osp.yml
- ansible/configs/ansible-gitOps-integration/post_software.yml
- ansible/configs/ansible-gitOps-integration/pre_software.yml
- ansible/configs/ansible-gitOps-integration/rh_event.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/ec2_vars.yml
- ansible/configs/ansible-gitOps-integration/sample_vars/osp_vars.yml
- ansible/configs/ansible-gitOps-integration/software.yml
Added variables for vscode-server role in sample vars
> Added new variables config:ansible-gitOps-integration

- ansible/roles/ocp4-workload-homeroomlab-starter-guides/defaults/main.yml
Test branch 4.4 for Starter Guides
> Change role ocp4-workload-homeroomlab-starter-guides  

- ansible/roles/satellite-installation/README.adoc
- ansible/roles/satellite-installation/defaults/main.yml
- ansible/roles/satellite-installation/tasks/main.yml
Add new variable to update all packages before install Satellite
satellite-installation
> Add variable to update packages for satellite-installation

- ansible/roles/ocp4-workload-ccnrd/templates/devfile.json.j2
Update mta-ide-plugin reference from external git repo to internal file in the agnosticd
```paste below
```
> Update mta-ide-plugin reference

- ansible/roles_ocp_workloads/ocp4_workload_shared_bastion_access/README.adoc
- ansible/roles_ocp_workloads/ocp4_workload_shared_bastion_access/defaults/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_bastion_access/meta/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_bastion_access/tasks/main.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_bastion_access/tasks/post_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_bastion_access/tasks/pre_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_bastion_access/tasks/remove_workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_bastion_access/tasks/workload.yml
- ansible/roles_ocp_workloads/ocp4_workload_shared_bastion_access/templates/cluster_resource_quota.j2
New workload to give OpenTLC users access to a shared cluster bastion VM.
ocp4_workload_shared_bastion_access
> New workload for Bastion Access

- ansible/configs/osp-satellite-vm/post_infra.yml
Remove command and use package module 
Fix typo 
osp-satelite-vm
> Remove command and use package instead

- ansible/roles_ocp_workloads/ocp4_workload_shared_bastion_access/tasks/post_workload.yml
- docs/Developing_Workloads_on_Bastion.adoc
Documentation for development on DEV bastion.
> Docs for Bastion

- ansible/configs/hacluster-pntae/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/multi-network-app-pntae/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/sap-hana/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/sap-integration/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/sap-rhvh/files/cloud_providers/osp_cloud_template_master.j2
- ansible/configs/sap-smart/files/cloud_providers/osp_cloud_template_master.j2
- ansible/roles-infra/infra-osp-dns/tasks/instance_loop.yml
- ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml
- ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
Changed cloud_template_master.j2 
Issue: 
In multi-server OSP config server names were assigned as server0, server1...
Changed loop.index0 to loop.index for names assigned server1,server2,....
> loop.index0 changed to loop.index in cloud_template_master.j2 template

- ansible/roles/ocp-workload-3scale-demo/defaults/main.yml
- ansible/roles/ocp-workload-3scale-demo/readme.adoc
- ansible/roles/ocp-workload-3scale-demo/tasks/pre_workload.yml
- ansible/roles/ocp-workload-3scale-demo/tasks/workload.yml
Update workload to migrate from shared 3.11 cluster to shared 4.x version
Update the 3scale version to 2.9.0.GA
3scale Security demo with OpenID Connect
```paste below
```
> update to ocp shared dev4 and 3scale 2.9.0.GA

- ansible/configs/osp-satellite-vm/post_infra.yml
Revert to command to remove satellite ca certs
osp-satellite-vm
> Revert remove satelite package

- ansible/action_plugins/agnosticd_user_info.py
- ansible/library/agnosticd_user_info.py
- docs/User_Info.adoc
Add support for `body` in `agnosticd_user_info` action plugin.
agnosticd_user_info action plugin
> Add agnosticd_user_info support for body

- ansible/configs/rhel-container-security/post_software.yml
- ansible/roles-infra/infra-osp-resources-destroy/tasks/project_resources.yml
Fix config rhel-container-security user info.
The `student_bastion_hostname` contained all variables from the bastion rather than the bastion hostname.
config rhel-container-security
> FIX config rhel-container-security bastion hostname
