ansible/configs/devsecops-vld-framework-binder/post_software.yml
- Feature Pull Reques
```paste below
```
=> Remove dev and prod argocd validations

ansible/configs/devsecops-vld-framework-binder/post_software.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/acm-application-set.yml.j2
=> Include ignore for service account

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_acm_requirements.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_demo_requirements.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/acm-application-set.yml.j2
=> Fix app set issue

ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> Remove argo dev and prod validations for route

ansible/configs/devsecops-vld-framework-binder/default_vars.yml
=> Default global variable to true

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/post_workload.yml
Adds more information to the output for the workload ocp4_workload_5gran_deployments_lab
```paste below
```
=> Adds more information to the output

ansible/configs/devsecops-vld-framework-binder/post_software.yml
Added agnosticd userinfo of the applications deployed in fire and forget way.
=> add agnosticd userinfo

ansible/configs/sap-smart/default_vars.yml
Changes branch for one of the repos used in sap-smart config to troubleshoot issue in RITM1381928
```paste below
```
=> Changed repo branch for sap-hana-hsr Tower template in sap-smart config

tools/execution_environments/ee-multicloud-public/requirements.txt, tools/execution_environments/ee-multicloud-public/requirements.yml
Add community.crypto
* https://github.com/ansible-collections/community.crypto
* https://galaxy.ansible.com/community/crypto
to ee-multicloud
- EE Pull Request
```paste below
```
=> Add community.crypto to ee-multicloud

tools/execution_environments/ee-multicloud-public/readme.adoc
Add changelog for ee-multicloud:v0.0.13
=> Add changelog for ee-multicloud:v0.0.13

ansible/configs/sap-smart/default_vars.yml
=> Added variables for HANA replication in sap-smart

ansible/roles_ocp_workloads/ocp4_workload_rhacs_authentication/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_authentication/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_authentication/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_authentication/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_authentication/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs_authentication/tasks/workload.yml
=> Initial commit of acs authentication role

ansible/configs/devsecops-vld-framework-binder/post_software.yml
Added new variables to for userinfo
=> updated userinfo

ansible/configs/expanding-workload-rhel/image_builder_repos.yml
Sleep 30 seconds before check again the service
=> [expanding-workload-rhel] Update image_builder_repos.yml

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/secret-aws-credentials.yaml.j2
Add suggested logic to encode JSON pull secret properly.
=> Add logic to make JSON work

ansible/configs/ent-demo-ate-binder/Makefile, ansible/configs/ent-demo-ate-binder/README.adoc, ansible/configs/ent-demo-ate-binder/default_vars.yml, ansible/configs/ent-demo-ate-binder/destroy_env.yml, ansible/configs/ent-demo-ate-binder/foo, ansible/configs/ent-demo-ate-binder/lifecycle.yml, ansible/configs/ent-demo-ate-binder/post_infra.yml, ansible/configs/ent-demo-ate-binder/post_software.yml, ansible/configs/ent-demo-ate-binder/pre_infra.yml, ansible/configs/ent-demo-ate-binder/pre_software.yml, ansible/configs/ent-demo-ate-binder/software.yml
Placeholder of skeleton config for ATE binder function in chained config
configs/ent-demo-ate-binder
=> Placeholder for the ent-demo-ate-binder config

ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> Remove condition for acs secured cluster

ansible/roles_ocp_workloads/ocp4_workload_gitops_rhacs_secured_cluster/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_rhacs_secured_cluster/templates/acm-application-set.yml.j2
=> Change channel

ansible/roles-infra/infra-ec2-template-destroy/tasks/main.yml
=>  infra-ec2-template-destroy: Fix typo

ansible/configs/sap-smart/pre_software.yml
=> Lock RHEL release for SAP hosts in sap-smart

ansible/configs/sap-smart/default_vars.yml
=> Lock RHEL release for SAP hosts

ansible/configs/sap-smart/post_software.yml
=> Registration of SAP hosts to repos moved to an earlier stage

ansible/configs/sap-smart/default_vars.yml
=> Added vars for pacemaker in sap-smart

ansible/configs/sap-smart/default_vars.yml
=> Changed variable names for SAP hosts in sap-smart

ansible/configs/sap-smart/default_vars.yml
=> Moving declaration of SAP hosts variables

ansible/configs/sap-smart/default_vars.yml
=> Correct typo in variable

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_acm_requirements.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_demo_requirements.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/acm-application-set.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/acm-placement.yml.j2
=> Fix for pipeline

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/acm-placement.yml.j2
=> Store placement in gitops namespace

ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> Fix for deployment state

ansible/configs/sap-smart/default_vars.yml
=> Uploaded new default_vars.yml for sap-smart

ansible/configs/sap-smart/default_vars.yml
=> Changed variables to use some from sap-hana config

ansible/roles/ocp4-workload-quarkus-workshop/files/devspaces_cr.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/devspaces_imagepuller.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/stack_imagestream.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-devspaces.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml, ansible/roles/ocp4-workload-quarkus-workshop/templates/devfile.json.j2
Fix the Dev Spaces CR issue in Quarkus Workshop
```paste below
```
=> Fix the Dev Spaces CR issue in Quarkus Workshop

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-devspaces.yaml
=> Fix Dev Spaces CR issue

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-devspaces.yaml
Add a task to check if DS service is created in Quarkus workshop
```paste below
```
=> Add a task to check if DS service is created in Quarkus workshop

ansible/roles/ocp4-workload-quarkus-workshop/files/kubernetes-imagepuller-operator_subscription.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-devspaces.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
Fix CheCluster CR issue in Quarkus workshop
```paste below
```
=> Fix CheCluster CR issue in Quarkus workshop

ansible/roles_ocp_workloads/ocp4_workload_acc_new_app_dev/tasks/remove_workload.yml
This code was copied from the other role upon creation so I forgot to remove.
=> Remove dirty code from ocp4_workload_acc_new_app_dev

ansible/install_galaxy_roles.yml
I forgot one condition to be fixed
=> Last fix for checks

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/acm-application-set.yml.j2
=> Add more retries in case of delayed operator

ansible/configs/sandbox/post_software_vmc.yml
The message was saying api.apps.domain instead api.domain
=> Update post_software_vmc.yml to indicate correct API DNS

ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_gitops/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_gitops/templates/acm-application-set.yml.j2
=> Create job for setting admin password

ansible/configs/devsecops-vld-framework-binder/post_software.yml
=> Remove argocd password set for dev and prod

ansible/configs/open-environment-azure/requirements.yml
add collection requirements to open env azure
```paste below
```
=> update requirements for azure open env

ansible/configs/open-environment-azure/default_vars.yml, ansible/configs/open-environment-azure/destroy_env.yml, ansible/configs/open-environment-azure/post_software.yml, ansible/configs/rosa-manual/default_vars.yml, ansible/configs/rosa-manual/destroy_env.yml, ansible/configs/rosa-manual/post_software.yml
Add capability to deploy a bookbag to ROSA and ARO environments.
rosa-manual
=> Add bookbag capability to ROSA and ARO envs

ansible/configs/open-environment-azure/requirements.yml
update open env azure requirement versions
```paste below
```
=> update open env azure requirement versions

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/admin_secret.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/automationcontroller.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/namespace.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/operatorgroup.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/subscription.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tests/test-local.yml
New OCP workload for Ansible Automation Platform 2
- ocp4_workload_ansible_automation_platform
role ocp4_workload_ansible_automation_platform
No Hub yet
Hardcoded, currently, to Stable 2.2
=> Skeleton for new OCP AAP2 workload, no PAH, yet

ansible/roles/ocp4-workload-quarkus-workshop/files/devspaces_cr.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml
Update CRW to DS in Quarkus workshop
```paste below
```
=> Update CRW to DS in Quarkus workshop

ansible/configs/open-environment-azure/pre_software.yml
add satellite and rhel8 azure-cli install
```paste below
```
=> add satellite and rhel8 azure-cli install

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_demo_requirements.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_infrastructure_prerequisites.yml
=> Change demo repo name

ansible/roles/bastion-lite/tasks/create_bastion_ssh_key_and_access.yml, ansible/roles/bastion-lite/tasks/main.yml
Given `bastion-lite` has essential ssh logic refactored to reduce other side effects:
- remove old unnecessary code eg jq
- light style cleanup
- FQCN for all task
role bastion-lite
=> Light refactor of bastion-lite role and FQCNs

ansible/roles/community-playbooks/defaults/main.yml, ansible/roles/community-playbooks/tasks/main.yml
Role clones the community repository and run the playbook from it.
role: community-playbooks
=> Initial cummunity role

ansible/roles/community-playbooks/tasks/main.yml
=> added cli to install package

ansible/cloud_providers/azure_infrastructure_deployment.yml
add retries to ARM deployment in Azure cloud provider
azure cloud provider
```paste below
```
=> add retries to ARM deployment in Azure cloud provider

ansible/roles/ocp4-workload-workshop-admin-storage/files/production-cluster-admin.json
Latest is broken so I am changing the version
```paste below
```
=> changing the origin-console version to 4.13.0

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_devspaces.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_logging.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_monitoring.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_tekton.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/devspace_workspace.yml.j2
This PR fixes an issue affecting Tekton pipeline provisioning. It also fixes a dependency issue when trying to warm up users' workspaces (DevSpaces). 
N/A
=> Fixing issues on ocp4_workload_performance_monitoring

docs/Working_with_bookbag.adoc
=> Mention ordering before Let's Encrypt

ansible/configs/odf-dr-binder/post_software.yml
Fixed indentation
```paste below
```
=> Summit rdr1

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/secret-aws-credentials.yaml.j2
Implement s3 permissions workaround until engineering can release an updated product.
=> Add workarounds for S3 permissions issues

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/workload.yml
=> Fix command to update s3

ansible/configs/odf-dr-binder/post_software.yml
Added additional user info content for bookbag
Config: odf-dr-binder
=> added user info contents

ansible/roles/bookbag/tasks/deploy-bookbag.yaml, ansible/roles/bookbag/tasks/workload.yaml
Add retries to bookbag role tasks.
bookbag role
=> Add retries to bookbag tasks

ansible/configs/aap2-ansible-workshops/vars/auto_satellite_vars.yml
rhjcd-patch-add auto satellite var file
```paste below
```
=> add auto satellite var file

ansible/configs/odf-dr-binder/post_software.yml
Fixed type in variable name
config: odf-dr-binder
=> Fixed typo in variable name

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/hypershift-override-images.yaml.j2
Add workaround to use different images for the HCP operator.
=> Add hcp image workaround

ansible/configs/rosa-manual/software.yml
=> Fix aws install location

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/workload.yml
HCP Workaround didn't take. Move up...
=> Move hcp workaround

ansible/roles/bookbag/tasks/deploy-bookbag.yaml
Fix get route check in bookbag role. Add default in case no `resources` is set.
Role bookbag.
=> Fix deploy bookbag route check

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/bucket-policy.json.j2
Add more workaround logic for the s3 bucket...
=> Add more s3 workarounds

ansible/configs/migrating-to-ocpvirt/templates/httpd/ssl.conf
Don't set headers for the new version of forklift
=> [Mig2ocpvirt] Update ssl.conf

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/workload.yml
Bump retries
roles_ocp_workloads/ocp4_workload_ansible_automation_platform
=> More retries for OCP AAP2 workload waiting for operators

ansible/roles/bookbag/tasks/workload.yaml
Add `--wait` to bookbag `oc start-build` command.
bookbag role
=> Add bookbag build wait

ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/files/requirements.yml, ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/files/starburst-ci.html, ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/templates/rhods/odh-dashboard-config.yml.j2
Followup of https://github.com/redhat-cop/agnosticd/pull/6207
=> Fraud detection usecase

ansible/configs/open-environment-azure/pre_software.yml
ARO environment needs GUID variable set on the bastion.
=> Add guid to .bashrc

ansible/roles/bookbag/tasks/workload.yaml
Add longer delay between bookbag build attempts and more retries.
bookbag role
=> Adjust bookbag image build retries

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
Reverts redhat-cop/agnosticd#6312
=> Revert "Fixes centos8 streams url"

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
=> Updates commit for our automation

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
Updates automation tooling to fix a bug rendering apps
```paste below
```
=> updates automation

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
=> Fix 5g role

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
=> Added final fix for 5g role

ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/files/requirements.yml
=> Updating aws module to 4.0.0

ansible/configs/open-environment-azure/pre_software.yml
Bugfix PR to fix location of .bashrc to add the GUID env var to. Copy/paste gone wrong...
open-environment-aro
=> Fix location of bashrc for setting GUID

ansible/configs/sap-smart/post_software.yml
=> adding lab register tasks

ansible/configs/sap-smart/post_software.yml
=> adding satellite register steps

ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/tasks/workload.yml
=> Updated for variable double quotes - Edge 1

ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/tasks/workload.yml
=> Updated role so that users can create project

ansible/configs/sap-smart/post_software.yml
=> Updating release version for rhel8

ansible/configs/sap-smart/default_vars.yml, ansible/configs/sap-smart/post_software.yml
https://github.com/redhat-cop/agnosticd/blob/development/ansible/configs/sap-smart/post_software.yml#L132
```paste below
```
=> adding hana_shana repos lock to 8.1

ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/tasks/workload.yml
=> Updated the formatting for the variable

tools/execution_environments/ee-multicloud-public/readme.adoc
=> ee-multicloud:v0.0.14 changelog

tools/execution_environments/ee-multicloud-public/Containerfile, tools/execution_environments/ee-multicloud-public/entrypoint.sh
=> Add entrypoint as it disapeared from upstream

ansible/roles/agnosticd_save_output_dir/tasks/upload-archive-s3-s3_object.yml
Attempt to work around amazon.aws.s3_object issue
Role agnosticd_save_output_dir
=> Add overwrite to upload-archive-s3-s3_object

ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/tasks/workload.yml
=> updated user variable

ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/tasks/workload.yml
=> added variable to metadata

ansible/configs/rhel-container-security/pre_software.yml
Minor fix to not nag about registering with Insights on the lab boxes
configs/rhel-container-security
=> Ensuring that insights nag doesn't exist

ansible/roles/automation_platform_loader/tasks/main.yml
Added an. `environment` to  block for role automation_platform_loader  
- allow token based auth to AAP2 controller
role automation_platform_loader
=> Added env creds for AAP2 to automation_platform_loader

ansible/roles/bookbag/defaults/main.yaml, ansible/roles/bookbag/tasks/wait-for-bookbag-deployment.yml
Set default `bookbag_deployment_retries` of 5
Role bookbag
=> Fix unset bookbag_deployment_retries variable

ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/tasks/workload.yml
=> Updated the bash script argument.

ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/tasks/workload.yml
=> Updated the script argument as per my discussion with Cory Latschkowski

ansible/roles/automation_platform_loader/tasks/machine_credential.yml, ansible/roles/automation_platform_loader/tasks/main.yml, ansible/roles/automation_platform_loader/tasks/ocp_bearer_token.yml
Cleaned up include_tasks files for AAP2 loader role
role automation_platform_loader
=> Add include_tasks to AAP2 Loader

ansible/roles/automation_platform_loader/tasks/machine_credential.yml, ansible/roles/automation_platform_loader/tasks/main.yml, ansible/roles/automation_platform_loader/tasks/ocp_bearer_token.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/files/grafana_dashboard_performance.yml.json, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_grafana.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_hyperfoil.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_tekton.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/setup_pipelines.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/devspace_workspace.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/loki-instance.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_voteapp/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/workload.yml
=> ocp4_workload_performance_monitoring: Fix Tekton issue

ansible/roles/automation_platform_loader/tasks/machine_credential.yml, ansible/roles/automation_platform_loader/tasks/main.yml, ansible/roles/automation_platform_loader/tasks/ocp_bearer_token.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/files/grafana_dashboard_performance.yml.json, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_grafana.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_hyperfoil.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_tekton.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/setup_pipelines.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/devspace_workspace.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/loki-instance.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_voteapp/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/workload.yml
ocp4_workload_performance_monitoring: Fix Hyperfoil patching error
=> ocp4_workload_performance_monitoring: Fix Hyperfoil patching error

ansible/roles/automation_platform_loader/tasks/main.yml
Enhance the AAP2 loader role to output the aap token as user_data
=> Output app2 token as agd data in aap2 loader role

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/defaults/main.yml
missing variable breaking the deployment
=> fix: adding missing variable

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/limits.yml.j2
quota limit was breaking DevWorkspaces deployments
=> fix: quota and limit names and CPU value

ansible/roles/host_virtualenv/tasks/main.yml
Fix pip install issues by upgrading pip prior to installing requirements.
Role host_virtualenv
=> Upgrade pip on virtualenv creation

ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/remove.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/templates/cert-manager-operarator.j2, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/tests/test-local.yml
Simple workload installing ocp4_workload_cert_manager_operator
roles_ocp_workloads/ocp4_workload_cert_manager_operator
=> Create ocp4_workload_cert_manager_operator role

ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/remove.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/templates/cert-utils-operarator.j2, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tests/test-local.yml
New role ocp4_workload_cert_utils_operator
ocp4_workload_cert_utils_operator
=> Ocp workload ocp cert utils 01

ansible/roles/automation_platform_loader/tasks/main.yml
Improve the token dereferencing to match doumentation when returing a token from awx.awx.token in automation_platform_loader role 
=> Update AAP2 token output to use controller_token in register

ansible/roles_ocp_workloads/ocp4_workload_gitops_workshop/files/devworkspacetemplate.yaml, ansible/roles_ocp_workloads/ocp4_workload_gitops_workshop/tasks/workload.yml
Update the DevWorkspaceTemplate for the OpenShift GitOps workshop with the unmanaged annotation so that changes to these are not reverted by the operator when the cluster is restarted.
OpenShift GitOps
=> Update DevWorkspaceTemplate with unmanaged annotation

ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tasks/pre_workload.yml
=> Fixed bad cp -r var artifacts in 2 new workloads

ansible/roles-infra/lc.yml
remove extra file in gcp lifecycle
```paste below
```
=> remove extra file

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/ocp_bearer_token_lifecycle.j2
Forgot to add j2 to prior PR
Extend bearer token life
roles_ocp_workloads/ocp4_workload_ansible_automation_platform
=> Ocp bearer token life 01

ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/templates/cert-manager-operarator.j2
This is now set to write channels and version
ocp4_workload_cert_manager_operator
=> Tweak the ocp4_workload_cert_manager_operator to correct yaml manifests

ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/templates/cert-utils-namespace.j2, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/templates/cert-utils-operator.j2, ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/templates/cert-utils-subscription.j2
Tweaks to ocp4_workload_cert_utils_operator to ensure correct version
ocp4_workload_cert_utils_operator
<
=> Tweak the ocp4_workload_cert_utils_operator to correct yaml manfests

ansible/configs/ansible-rhel-workshop/default_vars_ec2.yml, ansible/configs/ansible-rhel-workshop/files/hosts_template.j2, ansible/configs/ansible-rhel-workshop/pre_software.yml
Included control-role and update hosts template
=> include control role

ansible/configs/ansible-rhel-workshop/default_vars.yml, ansible/configs/ansible-rhel-workshop/files/hosts_template.j2
added ansible automation platform 2 repos
=> added repos

ansible/configs/ansible-rhel-workshop/files/hosts_template.j2
=> fixed ansible hosts file

ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/operator.yaml
Fix to cert-utils-operator
Deleted unnecessary resources
added in OperatorGroup
roles_ocp_workloads/ocp4_workload_cert_utils_operator
=> Updates to ocp4_workload_cert_utils_operator

tests/static/requirements.txt
=> Update requirements.txt to use ansible 2.10

ansible/roles/ocp4-workload-dil-serverless/tasks/user_terminal.yaml
Reverts redhat-cop/agnosticd#6394
This change did not work
=> Revert "ocp4-workload-dil-servless- user-terminal - authentication change "

ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/workload.yml
=> Added retries for ingress config

ansible/configs/ansible-rhel-workshop/default_vars.yml, ansible/configs/ansible-rhel-workshop/files/vscode_nginx.conf, ansible/configs/ansible-rhel-workshop/software.yml
added deploy_automationcontroller role and it's configuration file
=> added role and configuration

ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/templates/starburst/operands/route.yml.j2
Now the AWS bucket and starburst link will be printed to the user.
=> Changed route to edge termination and added info to the output.

ansible/roles/automation_platform_bastion/README.adoc, ansible/roles/automation_platform_bastion/defaults/main.yml, ansible/roles/automation_platform_bastion/tasks/main.yml
Allows customization of bastions used with AAP2
roles/automation_platform_bastion
=> Basic new role to customize AAP2 bastions

ansible/configs/ansible-rhel-workshop/default_vars.yml, ansible/configs/ansible-rhel-workshop/default_vars_ec2.yml, ansible/configs/ansible-rhel-workshop/post_software.yml, ansible/configs/ansible-rhel-workshop/requirements.yml, ansible/configs/ansible-rhel-workshop/software.yml
added automation controller configuration and letsencrypt role
=> Ansible rhel workshop patch 2

ansible/configs/ansible-rhel-workshop/default_vars.yml
added more variables for automation controlller role
=> added variables

ansible/roles/automation_platform_bastion/tasks/main.yml
Role modifying root owned files executing as ec2-user
- fix: become: true
roles/automation_platform_bastion
=> Fixed privilege automation_platform_bastion

ansible/configs/ansible-rhel-workshop/post_infra.yml, ansible/configs/ansible-rhel-workshop/requirements.yml, ansible/configs/ansible-rhel-workshop/software.yml
replaced roles section with tasks and included roles as task which were previously added as roles. 
component: ansible-rhel-workshop
=> Included roles

ansible/configs/ansible-rhel-workshop/software.yml
=> fixed replacement

tools/execution_environments/ee-multicloud-public/Containerfile, tools/execution_environments/ee-multicloud-public/azure-cli.repo
Update Containerfile with new azure-cli install because microsoft no longer supports the repo we were using.
azure-cli
```paste below
```
=> Update Containerfile with new azure-cli install

tools/execution_environments/ee-multicloud-public/readme.adoc
=> Update ee changelog

tools/execution_environments/ee-multicloud-public/compare_release.sh, tools/execution_environments/ee-multicloud-public/readme.adoc
=> EE version v0.0.16 changelog

ansible/configs/rhel-container-security/software.yml
Adds support to pull clair images for the workshop using the pull secret in the deployer
configs/rhel-container-security
=> adding pull secret to root for nodes to pull clair images

ansible/configs/open-environment-azure/software.yml
add helm command installation to ARO
```paste below
```
=> add helm command installation to ARO

ansible/configs/rosa-manual/default_vars.yml, ansible/configs/rosa-manual/software.yml
add install oc and helm to rosa manual
rosa-manual
```paste below
```
=> add install oc and helm to rosa manual

ansible/configs/open-environment-azure/software.yml, ansible/configs/rosa-manual/software.yml
fix typos in rosa and aro helm install
rosa_manual
open-env-azure
```paste below
```
=> fix typos in rosa and aro helm install

ansible/configs/sap-hana/software.yml
=> adding the task red hat insight register

ansible/configs/sap-hana/software.yml
=> adding ignore_errors because insight will fail to register

ansible/roles/open-env-azure-install-aro/tasks/main.yml
=> add pause before aro install

ansible/roles/ocp4-workload-camel3-workshop/tasks/provision_webapp.yaml, ansible/roles/ocp4-workload-camel3-workshop/templates/webapp-invites.yaml.j2
This change makes it easier for students to follow invitation links to Gitter/Slack/Discord to join the platform.
With multiple workshop clusters, this new service simplifies the process
With a single cluster, also.
=> new invitation service for docs

ansible/roles/open-env-azure-install-aro/tasks/main.yml
=> apply secret sauce from azure to preset role for azure RP

ansible/roles_ocp_workloads/ocp4_workload_showroom/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_showroom/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/buildconfig.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/deployment.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/imagestream.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/imagestream.yaml.j2.bak, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/namespace.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/route.bak, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/route.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/service.yaml.j2
Openshift showroom webserver workload
roles_ocp_workloads/ocp4_workload_showroom
=> Refactored showroom

ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/workload.yml
=> Add correct auth for ocp4_workload_showroom

ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml
simple var fix ocp4_workload_showroom
=> set ocp_username: user-redhat.com a la LPE Automation workload

ansible/roles/ocp4-workload-camel3-workshop/templates/webapp-invites.yaml.j2
deployment was clashing when resolving curly brackets
=> fix clash curly brackets

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/pre_workload.yml
=> Setup ocp workload auth

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/main.yml
When running our lab automation, we get random issues related to ssh connections:
~~~console
TASK [ocp4_workload_5gran_deployments_lab : Ensure trusted certs are updated] ***
fatal: [hypervisor]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to hypervisor.example.com closed.", "unreachable": true}
~~~
This change adds ssh connection retries.
```paste below
```
=> fixes an issue with the ssh tuning

ansible/roles/ocp4-workload-workshop-admin-storage/defaults/main.yml, ansible/roles/ocp4-workload-workshop-admin-storage/tasks/post_workload.yml
Reverts redhat-cop/agnosticd#6474
=> Revert "Add to AgD user.info for ocp4-workload-workshop-admin-storage "

ansible/configs/ansible-automation-platform/post_software.yml
Adding user data to access vars post provision. 
Needed to provide user vars via user-message-template in AgV.
=> Add User Data to ansible-automation-platform

ansible/roles/bastion-student-user/defaults/main.yml, ansible/roles/bastion-student-user/tasks/main.yml
Add setting `agnosticd_user_info` data for bastion access from bastion-student-user role.
Role bastion-student-user
=> Add setting bastion access data from bastion-student-user

ansible/roles/bookbag/tasks/workload.yaml
Add `guid` var to all bookbag deployments.
bookbag role
=> Add guid var to all bookbag deployments

ansible/roles/ocp4-workload-oadp/templates/dpa-1.2.yml.j2
role: ocp4-workload-oadp
```paste below
```
=> oadp: update DAP for v1.1.3

ansible/roles/ocp-workload-terminal/tasks/workload.yml
=> Update k8s_facts to k8s_info

ansible/roles/showroom/README.adoc, ansible/roles/showroom/README.md, ansible/roles/showroom/defaults/main.yml, ansible/roles/showroom/meta/main.yml, ansible/roles/showroom/tasks/10-showroom-user-setup.yml, ansible/roles/showroom/tasks/20-showroom-dependencies.yml, ansible/roles/showroom/tasks/30-showroom-clone-and-inject.yml, ansible/roles/showroom/tasks/40-showroom-render.yml, ansible/roles/showroom/tasks/50-showroom-service.yml, ansible/roles/showroom/tasks/main.yml, ansible/roles/showroom/templates/include_vars.adoc.j2
New role, prototyping/MVP for bookbag replacement - showroom
- creates showroom user and working dirs
- adds dependencies
- clones a showroom (antora) repo
- injects userdata into repo
roles/showroom
WIP but needs to test live in real CIs
=> Initial incomplete but partly functional showroom role

ansible/configs/base-infra/Makefile, ansible/configs/base-infra/default_vars.yml, ansible/configs/base-infra/default_vars_ec2.yml, ansible/configs/base-infra/post_software.yml, ansible/configs/base-infra/pre_software.yml
Stripping down the new(ish) config base-infra
- Remove redundant code
- Simplify
Added call to showroom role
config/base-infra
=> Cleanup and simplification base-infra config

ansible/configs/ocp4-cluster/gcp_instances_start.yml, ansible/roles-infra/infra-gcp-create-inventory/tasks/main.yml
fix issue that causes gcp delete failure when VM is already gone
gcp cloud provider
```paste below
```
=> fix issue that causes gcp delete failure when VM is already gone

ansible/roles/common/defaults/main.yml, ansible/roles/common/tasks/main.yml, ansible/roles/common/tasks/packages_extra.yml
Specifying `common_extra_packages` allows installation of extra packages without having to override the common_packages_el9 or common_packages_el8 variables.
common
=> Add support for `common_extra_packages`

ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/files/cee-cf-110, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/files/cee-cf-111, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/files/cee-cf-112, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/tasks/workload.yml
This workload copies files from the files directory in the workload to the remote system. It also moves local files around on the system to facilitate the scripts function.
ocp4_workload_pntae_single_node
```paste below
```
=> New workload for pntae scripts on OCP4.12

ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/tasks/workload.yml
ocp4_workload_pntae_single_node
```paste below
```
=> update group for dest

ansible/roles_ocp_workloads/ocp4_workload_gitops_eda/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_eda/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_eda/templates/cluster-role-binding.yml.j2
Added clusterrolebinding for service account
role: ocp4_workload_gitops_eda
=> added clusterrolebinding

ansible/configs/migrating-to-ocpvirt/pre_software.yml
=> [Mig2ocpvirt] Update pre_software.yml

ansible/configs/base-infra/requirements.yml
Added containers collection - required
=> Added container collection to base-infra

ansible/roles/showroom/tasks/40-showroom-render.yml, ansible/roles/showroom/tasks/60-showroom-verify.yml
showroom URL had duplicate . (period) in `showroom_host` breaking orchetration, rendering etc
=> Remove additional . (period) in showroom URL

ansible/configs/migrating-to-ocpvirt/pre_software.yml
=> [Mig2ocpvirt] Using epel RPM

ansible/roles/bastion-lite/tasks/main.yml
=> removing task Add ClientAlive Settings for SSHD

ansible/roles/showroom/tasks/60-showroom-verify.yml, ansible/roles/showroom/templates/index.html.j2
Minor UI changes for showroom role - lead with VSCode tab
roles/showroom
=> Improve showroom UI and agnosticd data

.quarkus/cli/plugins/quarkus-cli-catalog.json, ansible/roles/ocp4-workload-quarkus-workshop/files/community-operators-index.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/redhat-operators-index.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
Upgrade Quarkus workshop on OpenShift 4.13
```paste below
```
=> Upgrade Quarkus workshop on OpenShift 4.13

ansible/roles/ocp4-workload-ccnrd-stable/files/knative_eventing_cr.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/knative_serving_cr.yaml
Update Serverless API version in CCN
```paste below
```
=> Update Serverless API version in CCN

ansible/roles/open-env-azure-create-open-env/tasks/main.yml
=> Add retries to Azure tasks

ansible/roles/open-env-azure-create-open-env/tasks/main.yml
change the admin-consent az command to permission grant
```paste below
```
=> move admin-consent to grant

.github/workflows/lfs.yml
=> Try a more recent version of lfs-warning action

.github/workflows/lfs.yml
=> Try a more recent version of lfs-warning action (#6551)

ansible/roles/common/tasks/main.yml
Extra packages don't seem to be installed. Remove check for RHEL...
common
=> Remove RHEL check

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/files/crunchy-instance.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/files/grafana_dashboard_performance.yml.json, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/files/tekton_role.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_devspaces.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_hyperfoil_instance.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_serverless.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/devspace_cluster.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/loki-instance.yml.j2
updating performance_monitoring workshop
=> ocp4_workload_performance_monitoring: disabling infra_nodes by default and fixing pipeline stop permission

tools/execution_environments/ee-multicloud-public/requirements.txt
- EE Pull Request
```paste below
```
=> Update ee-multicloud and add passlib python module

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/defaults/main.yml
This PR fixes a small issue related to YAML multiline strings that affect our role.
N/A
=> ocp4_workload_performance_monitoring: fixing yaml multiline issue

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/devspace_cluster.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/loki-instance.yml.j2
This PR fixes a Jinja yaml template issue we caught when deploying with infra-nodes.
N/A
=> ocp4_workload_performance_monitoring: fixing loki yaml template formating

ansible/configs/equinix-baremetal-node/requirements.yml
New version 7.0.1 is failing with the venv
=> [equinix-baremetal-node] Update requirements.yml to fix the version

ansible/configs/ansible-rhel-workshop/default_vars.yml, ansible/configs/ansible-rhel-workshop/default_vars_ec2.yml, ansible/configs/ansible-rhel-workshop/post_software.yml, ansible/configs/ansible-rhel-workshop/requirements.yml, ansible/configs/ansible-rhel-workshop/software.yml
Fixed ansible-rhel-workshop config to fill the missing parts after the review
=> Fixed lab gaps after review

ansible/configs/ansible-rhel-workshop/setup_image_pull.yml, ansible/configs/ansible-rhel-workshop/software.yml
Added include_file to avoid module missing error
=> added include file to avoid module missing error

.quarkus/cli/plugins/quarkus-cli-catalog.json, ansible/roles_ocp_workloads/ocp4_workload_mta6/defaults/main.yml
Update MTA 6.1 in MAD Dev Track
```paste below
```
=> Update MTA 6.1 in MAD Dev Track

ansible/roles_ocp_workloads/ocp4_workload_mta6/defaults/main.yml
Update catalog version
```paste below
```
=> Update catalog version

ansible/roles/ocp4-workload-dil-streaming/tasks/provision_devspaces.yaml, ansible/roles/ocp4-workload-dil-streaming/tasks/single_user.yaml
Add Retires for failing task - fuse project
=> Update single_user.yaml - DIL Streaming

ansible/configs/ansible-rhel-workshop/default_vars.yml, ansible/configs/ansible-rhel-workshop/files/ansible-navigator.yml, ansible/configs/ansible-rhel-workshop/files/setup.yml, ansible/configs/ansible-rhel-workshop/software.yml
Added and modified following as per ansible rhel workshop -
1: Added setup.yml playbook 
2: Added ansible-navigator.yml config file
3: Modified Automation Controller variables for building inventory
=> Ansible rhel workshop patch 5

ansible/roles/vscode-server/templates/settings.json
Update vscode-server settings to use dark mode as default
=> Enabled dark mode

ansible/configs/ansible-rhel-workshop/software.yml
=> Fixed file path typo

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/config_infra.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/enable_userworkload_monitoring.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_crunchy_postgres.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/cluster-monitoring-configmap.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/devspace_cluster.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/pipeline.yml.j2
This PR fixes an issue when configuring cluster monitoring when there is no infra-nodes.
N/A
=> ocp4_workload_performance_monitoring: Devnation fix 03

ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/files/openshift_gitops_clusterrolebinding.yaml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/amq_streams_operator.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/globex.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/grafana-influx.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/openshift_gitops.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/rhsso.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/rhsso_operator.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/sentiment_analysis.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/serverless.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/globex-application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/grafana.yaml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/influxdb.yaml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/kafka-to-influxdb.yaml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/knative-eventing.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/knative-serving.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/namespace.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/openshift-gitops.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/reviews-simulator.yaml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/rhsso-application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/sentiment-analysis-application.yaml.j2
Sentiment Analysis Pattern specific role.
```paste below
```
=> Added role for Sentiment Analysis Pattern

ansible/roles/ocp4-workload-camel3-workshop/tasks/provision_streams.yaml
=> fix for Streams operator memory limit

ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/workload.yml
=> fixed ansible cmd

ansible/roles-infra/infra-aws-open-environment/defaults/main.yaml
Generate password with guaranteed uppercase, lowercase and number.
=> Fix password generation

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/workload.yml
I renamed my repo and need to change references to the repo names in the automation.
```paste below
```
=> Updated automation for hosted control plane demo

ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/tasks/workload.yml
=> Sentiment v3

ansible/configs/ansible-windows-workshop/README.adoc, ansible/configs/ansible-windows-workshop/default_vars.yml, ansible/configs/ansible-windows-workshop/default_vars_ec2.yml, ansible/configs/ansible-windows-workshop/destroy_env.yml, ansible/configs/ansible-windows-workshop/files/ansible-navigator.yml, ansible/configs/ansible-windows-workshop/files/hosts_template.j2, ansible/configs/ansible-windows-workshop/files/setup.yml, ansible/configs/ansible-windows-workshop/files/ssh_config.j2, ansible/configs/ansible-windows-workshop/files/vscode_nginx.conf, ansible/configs/ansible-windows-workshop/post_infra.yml, ansible/configs/ansible-windows-workshop/post_software.yml, ansible/configs/ansible-windows-workshop/pre_infra.yml, ansible/configs/ansible-windows-workshop/pre_software.yml, ansible/configs/ansible-windows-workshop/requirements.yml, ansible/configs/ansible-windows-workshop/software.yml, ansible/configs/ansible-windows-workshop/start.yml, ansible/configs/ansible-windows-workshop/stop.yml
New config for BU ansible windows workshop
=> New config for ansible windows workshop

ansible/configs/ansible-windows-workshop/post_software.yml
=> fixed quots

ansible/configs/ansible-windows-workshop/requirements.yml
Removed few collections which got conflict with ansible.workshops collection dependency
=> Removed collection due to conflict

ansible/configs/ansible-windows-workshop/default_vars_ec2.yml
removed user_count since it is not anymore required
=> removed undefined variable

ansible/configs/ansible-windows-workshop/default_vars_ec2.yml, ansible/configs/ansible-windows-workshop/deploy_gitea.yml, ansible/configs/ansible-windows-workshop/software.yml
Included gitea deployment task file
=> Added git deployment task file

ansible/configs/ansible-windows-workshop/default_vars_ec2.yml
=> enabled public dns for gitea

ansible/configs/ansible-windows-workshop/deploy_gitea.yml
added gitea service restart task
=> added service task

ansible/configs/ansible-windows-workshop/default_vars.yml, ansible/configs/ansible-windows-workshop/pre_software.yml
Remove bastion-student-user role
=> Remove bastion-student-user role

ansible/configs/ansible-windows-workshop/default_vars.yml
=> Enabled student_name variable

ansible/configs/ansible-windows-workshop/default_vars_ec2.yml, ansible/configs/ansible-windows-workshop/deploy_gitea.yml, ansible/configs/ansible-windows-workshop/post_software.yml, ansible/configs/ansible-windows-workshop/software.yml
Rename gitea instance to gitlab just to align poc with ansible windows workshop
=> rename gitea to gitlab

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/jboss-webserver56.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml
Add JBoss Web Server 5.6 ImageStream 
```paste below
```
=> Add JBoss Web Server 5.6 ImageStream in the MAD Dev Track

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/create_hypershift_cluster.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/managed-cluster.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/managedclusterset/managedclusterset.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/managedclusterset/managedclustersetbinding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/managedclusterset/namespace-submariner-broker.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/rhdp/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/rhdp/channel.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/rhdp/clusterrolebinding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/rhdp/managedclustersetbinding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/rhdp/namespace-applications.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/rhdp/namespace-channels.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/rhdp/namespace-policies.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/rhdp/placement.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/rhdp/secret.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/rhdp/subscription.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/secret-aws-credentials.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/secret-s3-credentials.yaml.j2
Update workload rhacm_hypershift for ACM 2.8 (and OCP 4.13).
Bugfixes
Pre-configure RHDP environment.
Pre-configure ManagedClusterSet.
=> Update workload rhacm_hypershift for ACM 2.8 with bugfixes

ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/workload.yml
Add a debug statement to validate the cert manager policy.
=> Add template to debug what's wrong with the policy

ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/workload.yml
Debug failed. Adding more debug info.
=> More_debug

ansible/configs/ansible-windows-workshop/default_vars.yml
Changed ansible_host value to external facing windows fqdn
=> changed ansible_host value

ansible/roles_ocp_workloads/ocp4_workload_blackhat_secured_container_pipelines/tasks/workload.yml
Fix for intermittent issue
```paste below
```
=> Bandaid on registered variable not defined

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/trigger_globex_webhook.yml
=> Fix to wait for code server pod

ansible/roles/eda_pods_on_bastion/README.md, ansible/roles/eda_pods_on_bastion/defaults/main.yml, ansible/roles/eda_pods_on_bastion/files/common/inventory, ansible/roles/eda_pods_on_bastion/files/common/requirements.txt, ansible/roles/eda_pods_on_bastion/files/common/requirements.yml, ansible/roles/eda_pods_on_bastion/files/patch_route/rulebook.yml, ansible/roles/eda_pods_on_bastion/files/resource_quota/rulebook.yml, ansible/roles/eda_pods_on_bastion/files/volume_snapshot/rulebook.yml, ansible/roles/eda_pods_on_bastion/meta/main.yml, ansible/roles/eda_pods_on_bastion/tasks/main.yml, ansible/roles/eda_pods_on_bastion/tasks/pods.yml, ansible/roles/eda_pods_on_bastion/tasks/pre-reqs.yml, ansible/roles/eda_pods_on_bastion/templates/podman-compose.yml.j2, ansible/roles/eda_pods_on_bastion/templates/service.j2
This PR has new role eda_pods_on_bastion which runs multiple eda event pods on bastion as systemd service.
role: eda_pods_on_bastion
=> New role eda_pods_on_bastion

ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/templates/cert-manager-subscription.j2
Set variables in Jinja template instead of using static value.
role: ocp4_workload_cert_manager_operator
=> setting variables for channel and csv

ansible/roles/eda_pods_on_bastion/tasks/pre-reqs.yml
rolling back to epel 8
role: eda_pods_on_bastion
=> rolling back to epel8

ansible/roles/eda_pods_on_bastion/defaults/main.yml, ansible/roles/eda_pods_on_bastion/tasks/main.yml
Setting ansible_python_interpreter to platform default.
role: eda_pods_on_bastion
=> Event driven ansible patch 6

ansible/roles_ocp_workloads/ocp4_workload_blackhat_secured_container_pipelines/tasks/trigger_globex_webhook.yml
Change the file to reflect a front end change for the blackhat attendees.
```paste below
```
=> Change file for pipeline trigger

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/workload.yml
Adding until loop for uploading manifest for intermittent issue.
role: ocp4_workload_ansible_automation_platform
=> Adding until loop to manifest upload task

ansible/roles/ocp4-workload-3scale-servicemesh-demo/readme.adoc, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/provision_api.yaml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/tasks/provision_user.yaml, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/ocs-subscription.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/servicemesh-controlplane.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/threescale-bookinfo-istio-product.yaml.j2, ansible/roles/ocp4-workload-3scale-servicemesh-demo/templates/threescale-subscription.yaml.j2
1. Upgrade to the latest versions of the components
```paste below
```
=> Update Service Mesh and OpenShift Versions

ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/argocd_info.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/multi_user_controller.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/multi_user_hub.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/single_user_controller.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/single_user_hub.yml
replace k8s_facts with k8s_info for the role ocp4_workload_gitops_aap
ocp4_workload_gitops_aap
=> replace k8s_facts with k8s_info

ansible/roles/vscode-server/defaults/main.yml, ansible/roles/vscode-server/tasks/main.yml
Defaulting the vscode_server_ansible_become variable with omit as value. 
=> default the vscode_server_ansible_become variable

ansible/configs/ansible-workshops-rhel/templates/windows_userdata.txt.j2
SUMMARY
ConfigureRemotingForAnsible.ps1 should point to the 2.15 branch of the ansible/ansible repo
ISSUE TYPE
Feature Pull Request
COMPONENT NAME
provisioner
=> Update ansible-workshops-rhel -  windows_userdata.txt.j2 url

ansible/configs/ansible-workshops-rhel/templates/skylight_windows_userdata.j2
fix ansible windows worshop role
Invoke-WebRequest -Uri https://raw.githubusercontent.com/ansible/ansible/stable-2.15/examples/scripts/ConfigureRemotingForAnsible.ps1 -OutFile C:\ConfigureRemotingForAnsible.ps1 
https://github.com/ansible/workshops/pull/2010/files - shows the fix too in _userdata
=> Ansible-Workshops-rhel - Update skylight_windows_userdata.j2

ansible/roles/ocp4-workload-quarkus-workshop/files/devspaces_cr.yaml
Add a pluginRegistry to fix the extension issue in RHDS
```paste below
```
=> Add a pluginRegistry to fix the extension issue in RHDS

ansible/configs/ans-tower-ops-demo/env_vars.yml, ansible/configs/ans-tower-ops-demo/files/cloud_providers/ec2_cloud_template_json.j2, ansible/configs/ansible-integrations/env_vars.yml, ansible/configs/ansible-integrations/files/cloud_providers/ec2_cloud_template_json.j2, ansible/configs/ansible-windows-elt/default_vars_ec2.yml, ansible/configs/ansible-windows-workshop/default_vars_ec2.yml, ansible/configs/ansible-windows/env_vars.yml
Change https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 to https://raw.githubusercontent.com/ansible/ansible/stable-2.15/examples/scripts/ConfigureRemotingForAnsible.ps1' to fix timeout issue across all agD windows ansible based demos
=> Fix Ansible Windows URL across all roles

ansible/roles/vscode-server/defaults/main.yml
=> set default value

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_quay.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/workload.yml
Add quay in bootstrapper
```paste below
```
=> include quay in bootstrap role

ansible/roles_ocp_workloads/ocp4_workload_quay_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_quay.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/workload.yml
=> Parameterize quay role

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_gitlab.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_external_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_vault.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/application-vault.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/cluster-secret-storage-vault.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/operator-config-cluster.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/secret-vault-token.yml.j2
Add hashicorp vault as a secret injector
```paste below
```
=> add vault capabilities

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_gitlab.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_templates.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_external_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_vault.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/application-vault.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/cluster-secret-storage-vault.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/operator-config-cluster.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/secret-vault-token.yml.j2
=> Remove token injection

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_external_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/cluster-secret-storage-vault.yml.j2
Change service account to vault auth
```paste below
```
=> DEV_HUB: Change service account to vault auth

ansible/roles/showroom/.yamllint, ansible/roles/showroom/defaults/main.yml, ansible/roles/showroom/meta/main.yml, ansible/roles/showroom/tasks/20-showroom-dependencies.yml, ansible/roles/showroom/tasks/30-showroom-clone-and-inject.yml
- Allows, optional, scm_ref for showroom content repo
- Minor linting improvements including a .yamllint at role level
roles/showroom
=> Enable showroom to support adoc branches, tags etc

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_templates.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-backstage.yml.j2
=> DEV-HUB: Add allow list for rule

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml
=> Fix incorrect array input

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/gitea.yaml.j2
Updated and moved the Gitea Operator to the RHPDS org (in both Github and Quay). Many more changes to the operator. See
https://github.com/rhpds/gitea-operator/blob/main/CHANGELOG.adoc
=> Update workload to support updated Gitea Operator.

ansible/roles_ocp_workloads/ocp4_workload_codeserver/tasks/workload.yml
fact _ocp4_workload_codeserver_gitea_url was never used.
=> Update codeserver gitea changes

ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/quay-admin-token-secret.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_templates.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-backstage.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_quay.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_vault.yml
=> Add quay to the RHDH demo

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/workload.yml
=> Add extra timeout

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_janus_argocd.yml
=> Add retry for helm install

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-backstage.yml.j2
=> Make backstage image configurable

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/templates/gitea.yaml.j2
Screwed up logic when converting fail statements to assert statements. Fixed.
Also made apiVersion of Gitea CR customizable via variable.
=> Fix assert statements, make apiVersion customizable

ansible/configs/ansible-lightspeed/files/settings.json.j2, ansible/configs/ansible-lightspeed/software.yml
Removed .git directory from cloned ansible-lightspeed repository.
Config: ansible-lightspeed
=> Removed dir

ansible/configs/ansible-lightspeed/files/settings.json.j2
Removed author directory trust setting which was set to never.
config: ansible-lightspeed
=> removed trust setting from vscode

ansible/configs/ansible-windows-workshop/default_vars_ec2.yml
Changed powershell script path to enable basic auth in windows server
=> windows powershell script path changed

ansible/configs/ocp4-on-rosa-with-rhods/templates/project-request-template.yaml
Updated project template to accommodate RHODS requirements.
- New project template for RHODS requirement
Fixed project template requirements.
```paste below
```
=> Updated project template

ansible/roles/ocp4-workload-ccnrd-stable/templates/osm_smcp.yaml.j2
Fix an issue to create ServiceMeshControlPlane
```paste below
```
=> Fix an issue to create ServiceMeshControlPlane

ansible/cloud_providers/azure_destroy_env.yml
Fix misplaced when in azure cloud provider
azure cloud provider
```paste below
```
=> Fix misplaced when in azure cloud provider

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-backstage.yml.j2
=> add official rhdh image

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-backstage.yml.j2
=> Fix pull request secret name

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-backstage.yml.j2
=> Encode secret before injection

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_quay.yml
=> Extend oauth token expiry

ansible/configs/service-interconnect-binder/post_software.yml
Removed become which was set to true
config: service-interconnect-binder
=> removed become true

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-backstage.yml.j2
=> fix bug on reading allow list

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_janus_argocd.yml
=> Add argo creds to info page

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_gitlab_runner.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-backstage.yml.j2
=> Add ignore for secret

ansible/configs/base-infra/post_software.yml
Extend config `base-infra` to deploy either showroom **or** nookbag 
=> Add nookbag option to base-infra config for Project Zero

ansible/configs/ocp4-cluster/post_infra.yml
=> Azure vm list block fix 02

ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/tasks/workload.yml
=> [WIP] - Add check for pool already created

ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/tasks/workload.yml
=> Delete user pools and domain if exists

ansible/roles/nookbag/tasks/40-showroom-render.yml
Reverts redhat-cop/agnosticd#6760
=> Revert "fix: Remove remote option"

ansible/configs/ocp4-on-rosa-with-rhods/workloads.yml
Removed demo provisioner from the config.
```paste below
```
=> Updated RHODS config to remove demo provisioner dependency

ansible/configs/prp-binder/README.adoc, ansible/configs/prp-binder/default_vars.yml, ansible/configs/prp-binder/default_vars_ec2.yml, ansible/configs/prp-binder/destroy_env.yml, ansible/configs/prp-binder/infra.yml, ansible/configs/prp-binder/lifecycle.yml, ansible/configs/prp-binder/post_infra.yml, ansible/configs/prp-binder/post_software.yml, ansible/configs/prp-binder/pre_infra.yml, ansible/configs/prp-binder/pre_software.yml, ansible/configs/prp-binder/requirements.yml, ansible/configs/prp-binder/roles/ocp_auth_bootstrapper/tasks/main.yml, ansible/configs/prp-binder/sample_vars.yml, ansible/configs/prp-binder/software.yml, ansible/configs/prp-binder/status.yml, ansible/configs/prp-binder/update.yml
this config/prp-binder is for binders that need to call workloads.
```paste below
```
=> config/prp-binder - calling workloads

ansible/roles/nookbag/defaults/main.yml, ansible/roles/nookbag/tasks/60-showroom-verify.yml
Fix broken user_infor output - nookbag role
(multiline expression broke a regex filter - switched to the cleaner and better `split`)
roles/nookbag
=> Fix broken nookbag url and add default port

ansible/configs/sap-integration/custom_workloads.yml, ansible/roles/bastion-lite/tasks/main.yml
…kloads.yml
```paste below
```
=> removing openshift-storage.noobaa.io

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml
Updates the automation we use to create the hub cluster. This reduces the overall time to provision.
```paste below
```
=> Updated 5gran cluster creation

ansible/configs/sap-integration/requirements.yml
=> adding community.general in requirements sap-integration

ansible/configs/sap-integration/pre_software.yml
=> Updating pre_software.yml sap-integration

ansible/configs/sap-integration/files/cloud_providers/osp_cloud_template_master.j2
=> adding cloud_provider file in sap-integration

ansible/configs/sap-integration/default_vars_ec2.yml
=> Update default_vars_ec2.yml in sap-integration

ansible/configs/sap-integration/custom_workloads.yml
=> sap-integration changes

ansible/configs/sap-integration/custom_workloads.yml
=> changing workload

ansible/configs/sap-integration/custom_workloads.yml
=> Update custom_workloads.yml in sap-integration

ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
Add deletion of resource locks in azure
```paste below
```
=> Add deletion of resource locks in azure

ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
Fix problem in indentation
```paste below
```
=> Fix problem in indentation

ansible/configs/sap-integration/destroy_env_ec2.yml
=> Update destroy_env_ec2.yml in sap-integration

ansible/configs/sap-integration/destroy_env_ec2.yml
=> fixing the syntax in sap-integration

ansible/roles_ocp_workloads/ocp4_workload_gitops_sonarqube/templates/acm-application-set.yml.j2
=> STSSC - Use internal quay image

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_gitea_requirements.yml
=> fix token access scopes

ansible/configs/sap-integration/default_vars.yml, ansible/configs/sap-integration/destroy_env_ec2.yml
Fix sap integration delete for controller
```paste below
```
=> Fix sap integration delete

ansible/configs/sap-integration/ec2_instances_start.yaml
add role to start instances
sap-integration 
```paste below
```
=> add role to start instances

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/workload.yml
=> Update workload.yml in ocp4_workload_ansible_automation_platform

ansible/roles/eda_controller_config/README.md, ansible/roles/eda_controller_config/defaults/main.yml, ansible/roles/eda_controller_config/meta/main.yml, ansible/roles/eda_controller_config/tasks/create/create_awx_token.yml, ansible/roles/eda_controller_config/tasks/create/create_credential.yml, ansible/roles/eda_controller_config/tasks/create/create_decision_env.yml, ansible/roles/eda_controller_config/tasks/create/create_project.yml, ansible/roles/eda_controller_config/tasks/create/create_rulebook_activation.yml, ansible/roles/eda_controller_config/tasks/list/list_activation.yml, ansible/roles/eda_controller_config/tasks/list/list_awx_token.yml, ansible/roles/eda_controller_config/tasks/list/list_credential.yml, ansible/roles/eda_controller_config/tasks/list/list_decision_env.yml, ansible/roles/eda_controller_config/tasks/list/list_project.yml, ansible/roles/eda_controller_config/tasks/list/list_rulebook.yml, ansible/roles/eda_controller_config/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/.yamllint, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/templates/cluster_rolebinding.j2, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/templates/eda_admin_secret.j2, ansible/roles_ocp_workloads/ocp4_workload_eda_controller/templates/eda_controller.j2
Adding two new roles
1- ocp4_workload_ eda_controller: Installs EDA on OpensShift.
2- eda_controller_config: This role configures EDA controller.
ROLE:
- ocp4_workload_ eda_controller
- eda_controller_config
=> New roles for EDA

ansible/roles_ocp_workloads/ocp4_workload_blackhat_secured_container_pipelines/tasks/setup_gitea_requirements.yml
=> BlackHat: Switch to new gitea operator

ansible/roles/eda_controller_config/defaults/main.yml, ansible/roles/eda_controller_config/tasks/main.yml
Event-driven Ansible with OpenShift demo CI has issue with vscode workspace with Tech-preview EDA-controller, which is fixed in this PR. 
role: eda_controller_config
=> Bugfix Event-driven ansible

ansible/roles_ocp_workloads/ocp4_workload_opentour_dach_2022/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_opentour_dach_2022/tasks/workload.yml
Updating the OpenTour Content 
Only the workshop specific role
Nothing to add.
=> Update opentour content

ansible/configs/sap-integration/lifecycle_hook_post_start.yml
=> Update lifecycle_hook_post_start.yml for sap-integration

ansible/roles_ocp_workloads/ocp4_workload_blackhat_secured_container_pipelines/tasks/setup_stackrox.yml
=> BlackHat: Add retries for stackrox route lookup

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_external_secrets.yml
=> Up version of external secrets operator

ansible/configs/rosa/requirements.yml, ansible/configs/rosa/workloads.yml
update k8s auth to openshift auth
rosa
```paste below
```
=> update k8s auth to openshift auth

ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/tasks/pre_workload.yml
=> updating new s3 bucket link ocp4_workload_fraud_detection_usecase

ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/templates/cicd/sonarqube-scan-task.yaml.j2
=> OHC-Demo: Tag version of sonarqube

tools/execution_environments/ee-multicloud-public/Containerfile
Some demos/labs will require to use sshpass to connect to nodes using password
=> Update Containerfile to include sshpass

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_external_secrets.yml
=> DevHub: Add version parameter to helm install

ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager_operator/templates/cert-manager-subscription.j2
ocp4_workload_cert_manager_operator CSV gets changed every month so made it optional in the template 
Role: ocp4_workload_cert_manager_operator
=> Changed CSV to optional

ansible/configs/service-interconnect-binder/skupper_azure_cluster.yml
Removed one automated task for creating skupper link between azure and aws.
Config: service-interconnect-binder
=> removed task for azurelink

ansible/roles-infra/infra-vmc-resources/tasks/create_additional_public_ips.yaml
=> [infra-vmc-resources] Update create_additional_public_ips.yaml

ansible/configs/ocp4-on-rosa-with-rhods/requirements.yml, ansible/configs/ocp4-on-rosa-with-rhods/workloads.yml
Update OKD and OCP Auth for ocp4-on-rosa-with-rhods
ocp4-on-rosa-with-rhods role
=> Update OKD and OCP Auth for ocp4-on-rosa-with-rhods

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_gitlab_runner.yml
=> DevHub: GitlabRunner test without starting csv

ansible/configs/ocp4-cluster/lifecycle_hook_post_start.yml
fix azure start
azure cloud provider lifecycle
```paste below
```
=> fix azure start

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern/templates/values-secret.yaml.j2
This PR updates the values-secret.yaml.j2 aJinja 2 teamplate to use the new values-secrets.yaml format for Validated Patterns.
Updates: ocp4_workload_validated_pattern
```
Update for new MultiCloud Gitops Deployed catalog item that deploys the MultiCloud GitOps Validated Pattern
```
=> Using new format for secrets

ansible/configs/ocp4-on-rosa-with-rhods/requirements.yml, ansible/configs/ocp4-on-rosa-with-rhods/workloads.yml
Reverts redhat-cop/agnosticd#6863
=> Revert "Update OKD and OCP Auth for ocp4-on-rosa-with-rhods"

ansible/configs/osp-migration/destroy_env.yml, ansible/configs/osp-satellite-vm/destroy_env.yml
fix OSP deletion
osp-migration
osp-satellite-vm
```paste below
```
=> fix OSP deletion

ansible/configs/osp17-director-deployment/files/cloud_providers/osp_cloud_template_master.j2
=> [osp17-director-deployment] Fix osp_cloud_template_master.j2

ansible/configs/rosa-manual/pre_infra_ec2.yml
Fix random key generation in rosa MOBB
rosa-manual
```paste below
```
=> Fix random key generation in rosa MOBB

ansible/roles-infra/infra-vmc-resources/tasks/delete_additional_public_ips.yaml
=> [infra-vmc-resources] Update delete_additional_public_ips.yaml

ansible/roles/podman_desktop/defaults/main.yml, ansible/roles/podman_desktop/tasks/main.yml
Added podman demo contents
Role: podman_desktop
=> RHEL9 desktop

ansible/configs/ocp4-on-rosa-with-rhods/pre_infra_ec2.yml, ansible/configs/rosa/pre_infra_ec2.yml, ansible/roles-infra/infra-aws-open-environment/defaults/main.yaml
fix random password generation to fit new AWS requirements
modified:   configs/ocp4-on-rosa-with-rhods/pre_infra_ec2.yml
modified:   configs/rosa/pre_infra_ec2.yml
modified:   roles-infra/infra-aws-open-environment/defaults/main.yaml
```paste below
```
=> fix random password generation to fit new AWS requirements

ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml, ansible/roles-infra/infra-osp-dry-run/tasks/main.yml, ansible/roles-infra/infra-osp-resources-destroy/tasks/detect_project.yml, ansible/roles-infra/infra-osp-resources-destroy/tasks/keypairs.yml, ansible/roles-infra/infra-osp-resources-destroy/tasks/project.yml, ansible/roles-infra/infra-osp-save-images/tasks/stop_vms.yml, ansible/roles-infra/infra_osp_bastion_on_openshift_network/tasks/add-bastion-to-openstack-network.yml, ansible/roles-infra/infra_osp_lifecycle/tasks/get-servers.yml
update openstack collection for osp infra
--- a/ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
--- a/ansible/roles-infra/infra-osp-dry-run/tasks/main.yml
--- a/ansible/roles-infra/infra-osp-resources-destroy/tasks/detect_project.yml
--- a/ansible/roles-infra/infra-osp-resources-destroy/tasks/keypairs.yml
--- a/ansible/roles-infra/infra-osp-resources-destroy/tasks/project.yml
---
--- a/ansible/roles-infra/infra-osp-save-images/tasks/stop_vms.yml
---
--- a/ansible/roles-infra/infra_osp_bastion_on_openshift_network/tasks/add-bastion-to-openstack-network.yml
---
--- a/ansible/roles-infra/infra_osp_lifecycle/tasks/get-servers.yml
```paste below
```
=> update collection for osp infra

ansible/roles_ocp_workloads/ocp4_workload_retail_aiml_workshop/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_retail_aiml_workshop/templates/retail-kustomize/retail-app.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_retail_aiml_workshop/templates/retail-prod-kustomize/retail-prod-app.yaml.j2
update storageclass to gp3 and api for routes
```paste below
```
=> update storageclass to gp3 and api for routes

ansible/roles/ocp4-workload-sso-workshop/tasks/install-guides.yaml
Fix guides version for ocp4-workload-sso-workshop
ocp4-workload-sso-workshop
=> fix version for guides

ansible/roles-infra/infra-osp-project-create/tasks/main.yml
fix typo in openstack module
infra-osp-project-create
```paste below
```
=> fix typo in openstack module

ansible/roles/showroom/defaults/main.yml, ansible/roles/showroom/tasks/main.yml
Added a simple `showroom_deploy` boolean and defaulted to true
- allows showroom deploy to be turned off
roles/showroom
=> Simple boolean SW switch to turn off showroom deploy

ansible/configs/ocp4-cluster/files/requirements_osp.txt
fix rhods destroy and prov
ocp4-cluster
```paste below
```
=> fix rhods destroy and prov

tools/execution_environments/ee-multicloud-public/requirements.txt
Update requirements.txt with openstack cli clients
ee-public
```paste below
```
=> Update requirements.txt with openstack cli clients

ansible/configs/ocp4-cluster/destroy_env_azure.yml, ansible/configs/ocp4-cluster/destroy_env_ec2.yml, ansible/configs/ocp4-cluster/destroy_env_osp.yml, ansible/configs/ocp4-cluster/destroy_env_vmc.yml, ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml
fix rhods provision and extra stuff in delete
ocp4-cluster
infra-osp-dns
```paste below
```
=> fix rhods provision and extra stuff in delete

ansible/roles/showroom/defaults/main.yml, ansible/roles/showroom/tasks/60-showroom-verify.yml
Add outputting `lab_ui_url` as agnosticd user_info
both as `msg` and `data`
roles/showroom
=> Add lab_ui_url to showroom role for API

ansible/configs/ocp4-equinix-aio/requirements.yml
fix bad indent in requirements.yml
configs/ocp4-equinix-aio 
```paste below
```
=> fix bad indent in requirements.yml

ansible/configs/ocp4-equinix-aio/requirements.yml
remove collections from eqx CNV, its now in the EE
configs/ocp4-equinix-aio
```paste below
```
=> remove collections from eqx CNV

ansible/roles/ansible_bu_setup_workshop/tasks/common/ansible-navigator.yml, ansible/roles/ansible_bu_setup_workshop/tasks/common/automation-controller.yml, ansible/roles/ansible_bu_setup_workshop/tasks/rhel_90.yml, ansible/roles/ansible_bu_setup_workshop/templates/coder.json.j2
Adding automation controller user creation task and modified workshop setup to align with original BU workshop.  
ROLE: ansible_bu_setup_workshop
=> Ansible BU workshop role

ansible/configs/ocp4-equinix-aio/requirements.yml
To dont require to use virt collection
=> [ocp4-equinix-aio] Update ocp4_aio_prepare_bastion tag

ansible/configs/hybrid-cloud-binder/post_software.yml
Remove for EE migration
- name: Check if desired virtualenv is available on the host
stat:
path: "/opt/virtualenvs/k8s/bin/python"
register: r_virtualenv
- name: Set Ansible Python interpreter to virtualenv
when: r_virtualenv.stat.exists
set_fact:
ansible_python_interpreter: "/opt/virtualenvs/k8s/bin/python"
=> OHC Binder - Update post_software.yml

ansible/configs/osp-migration/pre_infra.yml
remove path from sati
osp-migration
```paste below
```
=> remove path from sati

ansible/configs/osp-migration/pre_infra.yml
disable pipelining
osp-migration
```paste below
```
=> disable pipelining

ansible/configs/osp-migration/infra.yml
move to new collection
osp-migration
```paste below
```
=> move to new collection

ansible/configs/osp-migration/infra.yml
fix typo in collection name
osp-migration
```paste below
```
=> fix typo in collection name

ansible/configs/osp-migration/infra.yml
fix ansible_date_time with facts
osp-migration
```paste below
```
=> fix ansible_date_time with facts

ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
fix ip discovery in osp cloud provider
roles-infra/infra-osp-create-inventory
```paste below
```
=> fix ip discovery in osp cloud provider

ansible/configs/osp-migration/dns_loop.yml, ansible/configs/osp-migration/infra.yml
fix bad ip lookup
osp-migration
```paste below
```
=> fix bad IP lookup

ansible/configs/migrating-to-ocpvirt/files/rfc2136.ini.j2, ansible/configs/migrating-to-ocpvirt/pre_software.yml, ansible/configs/migrating-to-ocpvirt/templates/httpd/ssl.conf
To use this lab as a base for others, we require to use wildcard ssl cert
=> [migrating-to-ocpvirt] Use role host-lets-encrypt-certs-certbot 

ansible/configs/rosa-manual/destroy_env.yml
fix rosa-manual destroy
rosa-manual
```paste below
```
=> fix rosa-manual destroy

ansible/configs/hands-on-with-openshift-virtualization/default_vars.yml, ansible/configs/hands-on-with-openshift-virtualization/pre_infra.yml
move hands-on-with-openshift-virtualization CI to controller
hands-on-with-openshift-virtualization
```paste below
```
=> move hands-on-with-openshift-virtualization CI to controller

ansible/cloud_providers/osp_infrastructure_deployment.yml, ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml
update osp collection and variables
cloud_providers/osp_infrastructure_deployment.yml
roles-infra/infra-osp-dns/tasks/nested_loop.yml
```paste below
```
=> update osp collection and variables

ansible/configs/rosa-manual/destroy_env.yml, ansible/configs/rosa-manual/uninstall_rosa.yml
try to fix rosa uninstall
rosa-manual
```paste below
```
=> try to fix rosa uninstall

ansible/cloud_providers/osp_infrastructure_deployment.yml
fix instance search
cloud_providers/osp_infrastructure_deployment.yml
```paste below
```
=> fix instance search

ansible/configs/hands-on-with-openshift-virtualization/requirements.yml
=> Update requirements.yml to newer version of openstack.cloud

ansible/roles/ocp4-workload-quarkus-workshop/files/devspaces_cr.yaml
Update ocp4-workload-quarkus-workshop for the latest ImagePuller version of DS
```paste below
```
=> Update ocp4-workload-quarkus-workshop for the latest ImagePuller version of DS

ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/tasks/post_workload.yml
=> increasing wait time

ansible/configs/rosa-manual/software.yml
adding tasks to install gh and tkn clis
Config: rosa-manual
=> Added gh and tkn cli

ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml
attempt to fix https://controller.aap5nack2i7p6mie.ansiblecloud.redhat.com/#/jobs/playbook/55217/output
=> Update nested_loop.yml - attempt to fix failed find ip on osp

ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml
=> [infra-osp-dns] Get first IP searching for public ip

ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
=> [infra-osp-create-inventory] Improve find IPs

ansible/configs/ocp4-cluster/files/requirements_osp.txt, ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml, ansible/roles/host-ocp4-installer/tasks/main.yml, ansible/roles/host-ocp4-provisioner/files/openstack_requirements.txt
Implement Alberto's fixes into agD development for EE Openstack
=> OSP EE fixes 

ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
=> Osp ee fixes

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/workload.yml
Increasing retry limit of kafka cluster creation
ocp4_workload_serverless_ml_workshop
=> Increasing retry limit of kafka cluster creation

tools/execution_environments/ee-multicloud-public/readme.adoc, tools/execution_environments/ee-multicloud-public/release_cycle.adoc
Proposal of release cycle for execution environment.
=> ee-multicloud release cycle documentation

ansible/configs/base-infra/Makefile, ansible/configs/base-infra/default_vars_ec2.yml
As showroom moves to certs and new ports update base-infra SGs 
- tcp 8443
- tcp 8500-8525
Tweaks to non critical Makefile
\
=> Base infra showroom ports 02

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/defaults/main.yml
Update Serverless Operator Version
roles > ocp4_workload_serverless_ml_workshop
=> Update Serverless Operator Version

ansible/roles/ocp4-workload-ccnrd-stable/files/devspaces_cr.yaml
Update ocp4-workload-ccn-stable to upgrade Dev Spaces 3.8
```paste below
```
=> Update ocp4-workload-ccn-stable to upgrade Dev Spaces 3.8

ansible/roles/ocp4-workload-quarkus-workshop/files/devspaces_cr.yaml
Update ocp4-workload-quarkus-workshop for Dev Spaces 3.8
```paste below
```
=> Update ocp4-workload-quarkus-workshop for Dev Spaces 3.8

ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/README.md, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/openshift-admin-crb.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/openshift-oauth.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/openshift-openid-client-secret.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/rhsso-client-openshift.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/rhsso-instance.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/rhsso-realm-openshift.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/rhsso-user-openshift.yml.j2
Creates RHSSO authentication in Openshift with optional admin user and normal users.
```paste below
```
=> Initial commit of rhsso authentication with user creation

ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/sentiment-analysis-application.yaml.j2
=> sentiment aalysis: change to synch with helm edits

ansible/configs/rosa-manual/destroy_env.yml, ansible/configs/rosa/destroy_env.yml
fix bad flag in rosa destroy
rosa
rosa-manual
```paste below
```
=> Fix rosa destroy3

ansible/cloud_providers/azure_infrastructure_deployment.yml, ansible/configs/open-environment-azure/post_software.yml
fix bad default in azure open env
```paste below
```
=> fix bad default in azure open env

ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/defaults/main.yml
=> RHSSO-Auth: Fix not silent error

ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
use command to delete lock because collection is broken
```paste below
```
=> use command to delete lock because collection is broken

ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml
fix typo in lock deletion
```paste below
```
=> fix typo in lock deletion

ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/empty_resource_group.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
Remove recovery services vault azure
infra-azure-template-destroy
```paste below
```
=> Remove recovery services vault azure

ansible/configs/ocp4-cluster/destroy_env_ec2.yml
fix typo in ansible module
ocp4-cluster
```paste below
```
=> fix typo in ansible module

ansible/roles/open-env-azure-remove-user-from-subscription/tasks/empty_resource_group.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
Fix order azure delete
```paste below
```
=> Fix order azure delete

ansible/configs/roadshow-ocpvirt/templates/configureMTV.sh.j2
=> [ROADSHOW_OCPVIRT] Update configureMTV.sh.j2

ansible/roles_ocp_workloads/ocp4_workload_sonarqube/templates/cicd/sonarqube-persistent-deploy.yaml.j2
=> STSSC-WKS: Remove hardcoded storage class

ansible/roles/showroom/defaults/main.yml, ansible/roles/showroom/tasks/50-showroom-service.yml, ansible/roles/showroom/tasks/60-showroom-verify.yml, ansible/roles/showroom/templates/base_service_traefik_httpd/base_service_traefik_httpd.j2
Showroom role getting to production ready status
- clean up output
- clean up logic
role/showroom
=> More tweaks to showroom role, mainly robustness and var output

ansible/configs/containerize-app-demo/post_software.yml
Setting to correct bookbag role, bookbag is not being used in prod right now, so this old role is just causing failures.
containerize-app-demo - Deploy Bookbag
=> containerize-app-demo

ansible/configs/ent-demo-ate-base/default_vars_ec2.yml
=> Update default_vars_ec2.yml - misspelling in E2E

ansible/configs/convert-to-rhel/pre_software.yml
Adding debug tasks for broken c2r
convert-to-rhel config
```paste below
```
=> Adding debug tasks to see where password is breaking

ansible/configs/convert-to-rhel/post_software.yml, ansible/configs/convert-to-rhel/pre_software.yml
conver-to-rhel
```paste below
```
=> Update cars for broken password

ansible/configs/convert-to-rhel/pre_software.yml
convert-2-rhel
```paste below
```
=> Removing debugs after troubleshooting

ansible/configs/rosa-consolidated/software.yml
More defensive programming for rosa-consolidated - set defaults for print user data vars.
=> Add defaults for print user info vars

ansible/configs/rosa-consolidated/destroy_env.yml
Tried to destroy rosa clusters - even though the rosa CLI is not installed. Fixed to check for all options.
=> Fix rosa config destroy when no clusters defined

ansible/configs/podman-container-wksp/README.adoc, ansible/configs/podman-container-wksp/default_vars.yml, ansible/configs/podman-container-wksp/default_vars_ec2.yml, ansible/configs/podman-container-wksp/destroy_env.yml, ansible/configs/podman-container-wksp/files/ssh_config.j2, ansible/configs/podman-container-wksp/post_infra.yml, ansible/configs/podman-container-wksp/post_software.yml, ansible/configs/podman-container-wksp/pre_infra.yml, ansible/configs/podman-container-wksp/pre_software.yml, ansible/configs/podman-container-wksp/requirements.yml, ansible/configs/podman-container-wksp/software.yml, ansible/configs/podman-container-wksp/templates/novnc.service
=> adding new config

ansible/roles_ocp_workloads/ocp4_workload_stssc_on_ocp_wks/tasks/workload.yml
=> STSSC-wks: Remove showroom role

ansible/roles/ocp4-workload-dil-streaming/tasks/provision_shared.yaml, ansible/roles/ocp4-workload-dil-streaming/tasks/provision_userprojects.yaml
=> Improve DIL Streaming roles - add more retires

ansible/roles_ocp_workloads/ocp4_workload_stssc_on_ocp_wks/tasks/workload.yml
=> STSSC-wks: Add showroom task

ansible/roles_ocp_workloads/ocp4_workload_stssc_on_ocp_wks/tasks/workload.yml
=> STSSC-wks: Add ssh details for showroom

ansible/roles_ocp_workloads/ocp4_workload_stssc_on_ocp_wks/tasks/workload.yml
=> STSSC-wks: Add target host to showroom role

ansible/roles/install_operator/tasks/install.yml
Increasing retry count as sometimes operator installation taking more time
ansible/roles/install_operator/tasks/install.yml
=> Increasing retry count as sometimes operator installation taking more time

ansible/configs/podman-container-wksp/default_vars_ec2.yml
=> Update default_vars_ec2.yml in PODMAN_ROOTLESS_CONTAINER

ansible/configs/podman-container-wksp/pre_software.yml
=> Update pre_software.yml in podman-container-wksp

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/install_crw_operator.yaml
After upgrading from CRW to Devspace, we need to check for a different csv name.
=> Update check for Devspace Operator for Serverless ML Lab

ansible/roles-infra/create_ssh_provision_key/tasks/main.yaml
Fixes #6946
`create_ssh_provision_key` role
=> Add pubkey to user info. Fixes #6946

ansible/roles-infra/infra-ec2-template-generate/templates/cloud_template.j2
Fixes #6947
infra-ec2-template-generate role
=> add GroupName property

ansible/roles/showroom/tasks/20-showroom-user-setup.yml
Simplify showrooms machinectl escalation
roles/showroom
=> Showroom simplify machinectl 01

ansible/roles_ocp_workloads/ocp4_workload_quay_operator/defaults/main.yml
Upgrading Quay
Upgrading Quay version.
There is one user request: https://issues.redhat.com/browse/GPTEINFRA-6564
=> Update ocp4_workload_quay_operator_channel stable-3.9

ansible/configs/ent-demo-ate-binder/software.yml
=> [ent-demo-ate-binder] add environment variables

ansible/cloud_providers/azure_infrastructure_deployment.yml, ansible/configs/ocp4-getting-started-aro/README.adoc, ansible/configs/ocp4-getting-started-aro/default_vars.yml, ansible/configs/ocp4-getting-started-aro/destroy_env.yml, ansible/configs/ocp4-getting-started-aro/files/cloud_providers/azure_cloud_template.j2, ansible/configs/ocp4-getting-started-aro/files/cloud_providers/azure_parameters_template.j2, ansible/configs/ocp4-getting-started-aro/infra.yml, ansible/configs/ocp4-getting-started-aro/post_infra.yml, ansible/configs/ocp4-getting-started-aro/post_software.yml, ansible/configs/ocp4-getting-started-aro/pre_infra.yml, ansible/configs/ocp4-getting-started-aro/pre_software.yml, ansible/configs/ocp4-getting-started-aro/requirements.yml, ansible/configs/ocp4-getting-started-aro/software.yml, ansible/configs/ocp4-getting-started-aro/templates/agnosticd_user_info_upload.yaml.j2, ansible/configs/ocp4-getting-started-aro/templates/demo-operator-catalog-source.yaml, ansible/configs/ocp4-getting-started-aro/templates/demo-operator-namespace.yaml, ansible/configs/ocp4-getting-started-aro/templates/demo-operator-operator-group.yaml, ansible/configs/ocp4-getting-started-aro/templates/demo-operator-subscription.yaml, ansible/configs/ocp4-getting-started-aro/templates/demo-workshop-install.yaml.j2, ansible/configs/ocp4-getting-started-aro/workloads.yml, ansible/configs/open-environment-azure-subscription/default_vars.yml, ansible/roles/ocp4-workload-homeroomlab-odo/tasks/post_workload.yml, ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/post_workload.yml, ansible/roles/ocp4-workload-homeroomlab-tekton-pipelines/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_nexus_operator/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_nexus_operator_0.17/tasks/workload.yml
* bring config/ocp4-getting-started-aro back into existence
* Add user_info: data to several roles and workloads
* make conditional a debug in Azure cloud role to stop errors
```paste below
```
=> Cleaning up lots of Azure-related code

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/install_crw_operator.yaml, ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/per_user_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/templates/che_cluster.j2, ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/templates/crw_subscription.j2, ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/templates/rbac.j2
1. Fix namespace that Operator Group watches
2. Add CheCluster creation
3. Remove last remains of codeready to che
=> Update Operator Group and Renaming for Serverless ML Lab

ansible/configs/ent-demo-ate-base/default_vars.yml
Reverts redhat-cop/agnosticd#7104
=> Revert "[ent-demo-ate-base] Add hub cert"

tools/execution_environments/ee-multicloud-public/Containerfile, tools/execution_environments/ee-multicloud-public/entrypoint.sh
To fix issues with the dynamic collection installation and set variable /home/runner
=> [ee-multicloud-public] Update entrypoint script

ansible/roles/showroom/defaults/main.yml, ansible/roles/showroom/tasks/30-showroom-clone-and-inject.yml
Many labs do **not** have dynamic vars - make showroom injection optional but default on
roles/showroom
=> Tweaks to showroom, make var injection optional

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/files/kafka-cluster.yml
Update version of AMQ Streams.
=> upgrade kafka version

ansible/configs/rosa-consolidated/install_rosa_hcp.yml, ansible/configs/rosa-consolidated/install_rosa_sts.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_policies/tasks/workload.yml
Couple bugfixes and extra checks for ROSA installs.
Fix typo in OIDC_ENDPOINT variable...
=> Rosa bugfixes

ansible/configs/rosa-consolidated/software.yml, ansible/configs/rosa-consolidated/uninstall_rosa.yml
@fridim asked for log collection upon completion or failure of ROSA install.
Also added Terraform destroy for HCP cluster deletion to clean up VPCs etc.
rosa-consolidate
=> Add collection of logs, add terraform destroy for HCP

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/kubevirt/applicationset.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/kubevirt/datavolume.yaml.j2
I have not touched the existing Oracle VM as I intend to roll out this first and then remove the Oracle VM once the app is completely switched over to PostgreSQL.
=> Add postgresql kubevirt MAD roadshow

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/defaults/main.yml
=> update version of serverless

ansible/configs/rosa-consolidated/default_vars.yml, ansible/configs/rosa-consolidated/default_vars_ec2.yml, ansible/configs/rosa-consolidated/install_rosa_hcp.yml, ansible/configs/rosa-consolidated/post_software.yml, ansible/configs/rosa-consolidated/software.yml
Added Showroom to the ROSA consolidated config.
Also updated RHEL base image and fixed a few variables that weren't necessary.
Removed ignore_errors that didn't do anything anyway.
=> Add Showroom to ROSA config. Minor bugfixes and updates

ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml
allow for spaces in lock name
```paste below
```
=> allow for spaces in lock name

ansible/roles-infra/infra-azure-template-destroy/tasks/main.yml
fix bad az lock delete command
```paste below
```
=> fix bad az lock delete command

ansible/configs/ocp4-equinix-aio/requirements.yml
Will need to change to a new tag one @agonzalezrh  is back tomorrow
=> OCP4 AIO Equinix - Setting version to main until we can get a new tag

ansible/roles/ansible_bu_setup_workshop/tasks/auto_satellite.yml, ansible/roles/ansible_bu_setup_workshop/tasks/common/ansible-navigator.yml, ansible/roles/ansible_bu_setup_workshop/tasks/main.yml, ansible/roles/ansible_bu_setup_workshop/templates/hosts/auto_satellite.j2
Added step tasks for Auto Satellite CI n the role
role: ansible_bu_setup_workshop
=> adding auto satellite tasks

ansible/configs/migrating-to-ocpvirt/requirements.yml
=> updating collection ovirt.ovirt to 3.1.3

ansible/configs/sap-smart/default_vars.yml, ansible/configs/sap-smart/requirements.yml
=> Update requirements.yml in sap-smart

ansible/configs/migrating-to-ocpvirt/files/approve_csr.sh
Do a second test, and approve certs again
=> [migrating-to-ocpvirt] Update approve_csr.sh

ansible/roles_ocp_workloads/ocp4_workload_blackhat_secured_container_pipelines/tasks/setup_stackrox.yml
=> BLACKHAT-wsk: Add retry for route

ansible/roles_ocp_workloads/ocp4_workload_blackhat_secured_container_pipelines/tasks/trigger_globex_webhook.yml
=> Blackhat-wks: Add retry for codeserver

ansible/configs/ansible-bu-workshop/workloads.yml, ansible/roles/ansible_bu_setup_workshop/tasks/auto_satellite.yml
1: Enabled gather facts to use host facts.
2: Fixed typo for user info.
Config: asnible-bu-workshop
Role: ansible_bu_setup_workshop
=> Fixed ansible bu workshop

ansible/configs/migrating-to-ocpvirt/files/approve_csr.sh, ansible/configs/migrating-to-ocpvirt/post_software.yml
Increase the waiting time + add a delay for the check
=> [MIGRATING_TO_OCPVIRT] Last fix for approve CSR

ansible/cloud_providers/osp_destroy_env.yml, ansible/configs/sap-smart/requirements.yml
fix deletion of old CEE CIs
tech-cockpit-901
sap-e2e-automation
```paste below
```
=> fix deletion of old CEE CIs

ansible/configs/sap-hana/default_vars.yml
=> updating scm_url for project in sap_hana

ansible/configs/sap-hana/requirements.yml
=> bump requirements.yml in sap-hana

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_backstage.yml
=> RHDH: Fix to add common password for template

ansible/roles-infra/infra-vmc-sandbox/tasks/create_access.yml
=> [infra-vmc-sandbox] Fix role name for read only

ansible/configs/sap-hana/post_software.yml, ansible/configs/sap-hana/print_info.yml, ansible/configs/sap-smart/default_vars.yml
=> Update default_vars.yml sap-smart

ansible/configs/sap-hana/post_software.yml
Reverts redhat-cop/agnosticd#7190
=> Revert "Update post_software.yml - sap e2e user info"

ansible/configs/sap-hana/default_vars.yml, ansible/configs/sap-smart/default_vars.yml
=> adding repository in projects for Sap-hana and sap-smart

ansible/roles/install-command-line-tools/defaults/main.yml, ansible/roles/install-command-line-tools/tasks/oc-cli.yml
Removed unnecessary tasks and replaced the variable with right one as per Wolfgang's suggestion. 
role: install-command-line-tools
=> Modify Role install-command-line-tools

ansible/roles-infra/infra-osp-dns/tasks/main.yml
add check for dns delete
roles-infra/infra-osp-dns
```paste below
```
=> add check for dns delete

ansible/configs/sap-hana/post_software.yml
=> Update post_software.yml in sap-hana

ansible/configs/sap-hana/post_software.yml
=> removing bastion ssh_key info in sap-hana

ansible/configs/sap-hana/post_software.yml
=> updating user.info msg in sap-hana

ansible/configs/sap-hana/post_software.yml
=> Update post_software.yml in ap-hana

ansible/configs/sap-smart/post_software.yml
=> Update post_software.yml in sap-smart

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-rhsso-backstage.yml.j2
=> RHDH: Ensure retries are unlimited

ansible/configs/service-interconnect-binder/post_software.yml, ansible/configs/service-interconnect-binder/requirements.yml
Adding OKD community in service inetrconnect and update k8s auth to openshift auth
ansible/configs/service-interconnect-binder/requirements.yml
=> Adding OKD community in service inetrconnect and update k8s auth to openshift auth

ansible/roles/install-command-line-tools/defaults/main.yml, ansible/roles/install-command-line-tools/tasks/helm-cli.yml, ansible/roles/install-command-line-tools/tasks/main.yml
Added Helm Cli in the role
Role: install-command-line-tools
=> adding helm

ansible/roles_ocp_workloads/ocp4_workload_project_dance/tasks/setup_stackrox.yml
=> Project Dance: Expose internal registry

ansible/configs/ocp4-cluster/post_software.yml
=> [ocp4-cluster] fix CNV access info

ansible/configs/ansible-bu-workshop/default_vars.yml, ansible/roles/ansible_bu_aws_access_policy/defaults/main.yml, ansible/roles/ansible_bu_aws_access_policy/tasks/instances.yml, ansible/roles/ansible_bu_aws_access_policy/tasks/main.yml
Config clean up and re variable the role
Config: ansible-bu-workshop
Role: ansible_bu_aws_access_policy
=> Ansible BU Auto Satellite 

ansible/roles/ocp4-workload-quarkus-workshop/files/devspaces_cr.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile
Update ocp4-workload-quarkus-workshop to upgrade RHBQ 3.2
```paste below
```
=> Update ocp4-workload-quarkus-workshop to upgrade RHBQ 3.2

ansible/roles/ocp4-workload-quarkus-workshop/files/opentelemetry_subscription.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-opentelemetry.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
Update ocp4-workload-quarkus-workshop to install OpenTelemetry Operator
```paste below
```
=> Update ocp4-workload-quarkus-workshop to install OpenTelemetry Operator

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml
Update ocp4-workload-quarkus-workshop to update the guides based on rhbq 3.2
```paste below
```
=> Update ocp4-workload-quarkus-workshop to update the guides based on rhbq 3.2

ansible/roles/ocp4-workload-ccnrd-stable/files/devspaces_cr.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/opentelemetry_subscription.yaml, ansible/roles/ocp4-workload-ccnrd-stable/files/stack.Dockerfile, ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-guides.yaml, ansible/roles/ocp4-workload-ccnrd-stable/tasks/workload.yml
Update ocp4-workload-ccn-staboe to update RHBQ 3.2
```paste below
```
=> Update ocp4-workload-ccn-staboe to update RHBQ 3.2

ansible/configs/ocp4-on-rosa-with-rhods/post_software.yml
=> Deploy bookbag

ansible/configs/ansible-rhel-workshop/files/ansible-navigator.yml
Update ansible-navigator.yml ee to 2.4
-->
update the ee from 2.2 to 2.4
ee from registry
=> Update ansible-navigator.yml ee to 2.4

ansible/configs/ansible-rhel-workshop/files/ansible-navigator.yml
-->
typo - registry.redhat appeared twice
=> Update ansible-navigator.yml typo fix

ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/tasks/workload.yml, tools/runner/init.sh
The randomized passwords feature is never used by any of the CIs.
=> Remove ocp4_workload_authentication_rosa_user_password_randomized

ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml
Further investigation is needed for the hostpath-csi storageclass
=> [host-ocp4-assisted-installer] Increase the waiting time to 10min

ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/tasks/workload.yml
Second attempt to fix files location in rollouts workshop
ocp4_workload_rollouts_workshop
Discussed with Josh.
=> Fix files location in rollouts workshop

ansible/configs/sap-integration/destroy_env_osp.yml
fix osp delete sap
```paste below
```
=> fix osp delete sap

ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/tasks/workload.yml
Update workload.yml create gitops sub task  because it isn't found when deployed due to syntax
=> Update workload.yml create gitops sub task

ansible/roles_ocp_workloads/ocp4_workload_habana_gaudi_gpu_setup/README.md, ansible/roles_ocp_workloads/ocp4_workload_habana_gaudi_gpu_setup/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/README.md, ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/templates/accelerator_profile.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/templates/accelerator_profile_crd.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/templates/habana_notebook_imagestream.yaml.j2
Role to implement post habana and RHODS role deployment.
```paste below
```
=> Post habana and RHODS deployment configuration

ansible/roles_ocp_workloads/ocp4_workload_habana_post_rhods_setup/templates/habana_notebook_imagestream.yaml.j2
Updated imagestream namespace 
```paste below
```
=> Updated namespace for ImageStream

ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/tasks/workload.yml
Workaround gotcha in k8s module by using definitions with lookup instead of src
ocp4_workload_rollouts_workshop
Josh on thread where this is being discussed in AgnosticD chat
=> Use definitions with lookup to worksround k8s module gotcha

ansible/configs/satellite-hackfest/default_vars.yml
=> Update default_vars.yml in satellite-hackfest config

ansible/configs/satellite-hackfest/destroy_env.yml, ansible/configs/satellite-hackfest/pre_infra.yml, ansible/configs/satellite-hackfest/requirements.yml
=> Update destroy_env.yml in satellite-hackfest

ansible/configs/satellite-hackfest/pre_infra.yml
=> Update pre_infra.yml in satellite-hackfest

ansible/configs/satellite-hackfest/infra.yml
=> Create infra.yml in configs/satellite-hackfest

ansible/roles/ansible_bu_setup_workshop/tasks/common/ansible-navigator.yml, ansible/roles/ansible_bu_setup_workshop/tasks/common/automation-controller.yml, ansible/roles/ansible_bu_setup_workshop/tasks/common/cockpit.yml, ansible/roles/ansible_bu_setup_workshop/tasks/main.yml, ansible/roles/ansible_bu_setup_workshop/tasks/ripu.yml, ansible/roles/ansible_bu_setup_workshop/tasks/undefined_type.yml, ansible/roles/ansible_bu_setup_workshop/templates/hosts/ripu.j2, ansible/roles/ansible_bu_setup_workshop/templates/hosts/universal.j2, ansible/roles/ansible_bu_setup_workshop/templates/student-99-webui.json.j2
Added tasks for ansible bu RIPU workshop 
role: ansible_bu_setup_workshop
=> Ansible Bu RIPU workshop

ansible/configs/base-infra/Makefile, ansible/roles/showroom/defaults/main.yml, ansible/roles/showroom/tasks/10-showroom-dependencies.yml, ansible/roles/showroom/tasks/30-showroom-clone-and-inject.yml, ansible/roles/showroom/tasks/40-showroom-render.yml, ansible/roles/showroom/templates/service_second_terminal/service_second_terminal.j2, ansible/roles/showroom/templates/service_second_terminal/tab_second_terminal.j2, ansible/roles/showroom/templates/service_second_terminal/tablink_second_terminal.j2, ansible/roles/showroom/templates/service_single_terminal/service_single_terminal.j2, ansible/roles/showroom/templates/service_single_terminal/tablink_single_terminal.j2, ansible/roles/showroom/templates/user-data-as-attributes.j2
Simplifies lab creation and adds features 
- Adds support for multiple ttys as different users
- Moves var injection to antora.yml simplifying lab developer UX
- Adds sensible default ssh port fixing OCP V12N related bug
- Minor tidy up
roles/showroom
=> Showroom multiple tty tabs and antora.yml based attributes

ansible/roles/host-ocp4-assisted-installer/templates/installation-iso.yaml
It will help for troubleshooting in case of issues with the installation ISO
=> [host-ocp4-assisted-installer] Reduce DV size + dont remove DV

ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-guides.yaml
Update ocp4-workload-ccn-stable to upgrade OpenShift 4.14 in CCN
```paste below
```
=> Update ocp4-workload-ccn-stable to upgrade OpenShift 4.14 in CCN

ansible/configs/open-environment-azure-subscription/default_vars.yml, ansible/configs/open-environment-azure-subscription/post_software.yml, ansible/configs/open-environment-azure-subscription/requirements.yml, ansible/configs/open-environment-azure-subscription/software.yml, ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml, ansible/roles/open-env-azure-install-aro/tasks/main.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
Move aro to subscriptions
roles/open-env-azure-install-aro
configs/open-env-azure-add-user-to-subscription
```paste below
```
=> Move aro to subs

ansible/lookup_plugins/agnosticd_user_data.py
Allow fetching all user data with `agnosticd_user_data` by requesting `*`.
Lookup plugin `agnosticd_user_data`
=> Add support to fetch all user data with agnosticd_user_data

ansible/configs/service-interconnect-binder/post_software.yml
Make interconnect keys ee friendly
=>  Fix interconnect - convert to ee

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml
Update ocp4_workload_mad_roadshow to Fix the Argo issue
```paste below
```
=> Update ocp4_workload_mad_roadshow to Fix the Argo issue

ansible/roles/zero_touch_rhel_user/.vimrc, ansible/roles/zero_touch_rhel_user/.yamllint, ansible/roles/zero_touch_rhel_user/README.adoc, ansible/roles/zero_touch_rhel_user/defaults/main.yml, ansible/roles/zero_touch_rhel_user/meta/main.yml, ansible/roles/zero_touch_rhel_user/tasks/main.yml
New, lighter, role isolating user creation process for RHEL / Project Zero
roles/zero_touch_rhel_user
```paste below
```
=> new zero touch rhel user role - very simple and clean

ansible/configs/rosa-consolidated/install_rosa_cli.yml
Update tarball extract for rosa-consolidated install_rosa_cli.yml
Update tarball extract for rosa-consolidated install_rosa_cli.yml
```paste below
```
=> Update tarball extract for rosa-consolidated install_rosa_cli.yml

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml
Fix tomcat IP variable in MAD DEV
```paste below
```
=> Fix tomcat IP variable in MAD DEV

ansible/configs/osp17-director-deployment/pre_infra.yml
PLAY [Step 001 Migrating blueprints] ******************************************* TASK [Gathering Facts] *********************************************************
fatal: [150.239.16.29]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"150.239.16.29\". Make sure this host can be reached over ssh: Warning: Permanently added '150.239.16.29' (ECDSA) to the list of known hosts.\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nPermissions 0130 for '/tmp/output-ed4a44ad-07a3-5772-8f9a-deac0844fd54/ssh_key.pem' are too open.\r\nIt is required that your private key files are NOT accessible by others.\r\nThis private key …
=> OS17 Direcotor - fix role

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml
Fix the Cluster IP issue in ocp4_workload_mad_roadshow
```paste below
```
=> Fix the Cluster IP issue in ocp4_workload_mad_roadshow

ansible/configs/rosa-consolidated/destroy_env.yml, ansible/configs/rosa-consolidated/install_rosa_cli.yml, ansible/configs/rosa-consolidated/install_rosa_common_post.yml, ansible/configs/rosa-consolidated/install_rosa_common_pre.yml, ansible/configs/rosa-consolidated/install_rosa_hcp.yml, ansible/configs/rosa-consolidated/install_rosa_sts.yml, ansible/configs/rosa-consolidated/software.yml, ansible/configs/rosa-consolidated/uninstall_rosa.yml
set variable path to ROSA binary
```paste below
```
=> set variable path to ROSA binary

ansible/configs/rosa-consolidated/install_rosa_cli.yml
Update install_rosa_cli.yml untar
```paste below
```
=> Update install_rosa_cli.yml untar

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/guides/buildconfig.yaml.j2
Update PostgreSQL in MAD DEV
```paste below
```
=> Update PostgreSQL in MAD DEV

ansible/roles/control-user/tasks/ssh-config.yml
Use ssh_provision_* variables by default
Role control-user role
=> [control-user role] Update ssh-config.yml to use ssh_provision variables

ansible/roles/ocp4-workload-workshop-admin-storage/files/workshop-settings.j2
Remove bastion_fqdn variable
roles/ocp4-workload-workshop-admin-storage
=> [ocp4-workload-workshop-admin-storage] Update workshop-settings.j2

ansible/roles/showroom/tasks/30-showroom-clone-and-inject.yml, ansible/roles/showroom/templates/user-data-as-attributes.j2
Simplify tasks in showroom role to merge user-data into asciidoc attributes.
- Code clean-up
showroom role
=> Simplify showroom user data to atributes

ansible/configs/open-environment-azure-subscription/post_software.yml
as this isn't needed for aro sub
=> ARO MOBB SUB - remove preconfigure_aad

ansible/roles/showroom/tasks/30-showroom-clone-and-inject.yml
Set `f_user_data` fact to restore functionality in showroom role.
showroom role
=> Set f_user_data fact for showroom

ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/workload.yml
Add the option of removing kubeadmin
```paste below
```
=> RHSSO: Remove kube admin path

ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/workload.yml
Add URL prefix for RHSSO link
ocp4_workload_rhsso_authentication
=> [ocp4_workload_rhsso_authentication] Add URL prefix for RHSSO link

ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_sentiment_analysis_pattern/templates/grafana.yaml
Updated grafana user/passwd as vars
```paste below
```
=> Updated grafana user/passwd as vars

ansible/roles_ocp_workloads/ocp4_workload_rocket_chat/tasks/workload.yml
Changed hardcode user and password to variable
Role: ocp4_workload_rocket_chat
=> setup variable in rocketchat

ansible/configs/ansible-windows-workshop/default_vars.yml
Reverts redhat-cop/agnosticd#7315
=> Revert "Remove key_name  - Ansible Windows Workshop"

ansible/configs/rosa-consolidated/install_rosa_cluster_login.yml
Provision failures and successes show a large variability in how long it takes for ROSA login to succeed. Increase wait time to accommodate.
Config rosa-consolidated
=> Change rosa-consolidated to wait longer for login

ansible/configs/odf-dr-binder/post_software.yml
Adding Testing of SSH keys
ansible/configs/odf-dr-binder/post_software.yml
=> Update post_software.yml - odf-dr-binder for EE

ansible/configs/zero-touch-base-rhel/stop.yml
Environment variables are specific for EC2
config zero-touch-base-rhel
=> [zero-touch-base-rhel] Fix stop if the environment is not ec2

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/cicd/applicationset.yaml.j2
Update Postgres in MAD Dev
```paste below
```
=> Update Postgres in MAD Dev

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml
Add Postgresql, Remove Oracle and RHV in MAD Dev Track
```paste below
```
=> Add Postgresql, Remove Oracle and RHV in MAD Dev Track

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml
Fix typo in MAD DEV
```paste below
```
=> Fix typo in MAD DEV

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/files/storage-cluster.yml, ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/install_odf_operator.yaml
1. Fixed storage class name
2. Fixed CSV used
3. Fix label used for ODF/OCS
=> Fixed Storage Cluster Creation

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/cicd/applicationset.yaml.j2
Update the branch in the pipeline in MAD DEV
```paste below
```
=> Update the branch in the pipeline in MAD DEV

ansible/configs/open-environment-azure-subscription/post_software.yml
ARO URLs were missing from output data.
=> add some missing aro pre-deploy info to user data

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_backstage_repo.yml
=> RHDH: Bug - change repo name

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-rhsso-backstage.yml.j2
=> RHDH: Remove unneeded variable

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/workload.yml
=> RHDH: uncomment templating task

ansible/roles/rhel-graphical/tasks/main.yml
Create .config directory if doesn't exist
role rhel-graphical
=> [rhel-graphical] Create .config directory if doesn't exist

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml
Rename "credentials" to "ai_credentials"
role host-ocp4-assisted-installer
```paste below
```
=> [host-ocp4-assisted-installer] Rename register variable

ansible/configs/sap-hana/pre_infra.yml
=> Update pre_infra.yml in sap-hana

ansible/configs/sap-hana/pre_infra.yml
Reverts redhat-cop/agnosticd#7364
=> Revert "Update pre_infra.yml in sap-hana"

ansible/roles_ocp_workloads/ocp4_workload_project_dance/tasks/setup_tekton_chains.yml
=> Project Dance: add public key to vault

ansible/roles_ocp_workloads/ocp4_workload_project_dance/tasks/setup_tekton_chains.yml
=> Project Dance: Fix missing variable

ansible/configs/sap-hana/default_vars.yml
=> Update default_vars.yml in sap-hana

ansible/roles/ocp4-workload-quarkus-workshop/files/community-operators-index.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/devspaces_cr.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/redhat-operators-index.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
Update OpenShift 4.14 and Dev Spaces 3.9 in Quarkus workshop
```paste below
```
=> Update OpenShift 4.14 and Dev Spaces 3.9 in Quarkus workshop

ansible/roles_ocp_workloads/ocp4_workload_project_dance/tasks/setup_tekton_chains.yml
=> Project Dance: Remove unneccessary secret

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_vault.yml
=> Project Dance: do vault login retry

ansible/roles/ocp4-workload-eap8-workshop/tasks/install-gitea.yaml
update install-gitea.yml double delay time
=> update install-gitea.yml double delay time

ansible/configs/ansible-lightspeed/requirements.yml
Update kubevirt.core collection
Config ansible-lightspeed
=> [ansible-lightspeed] Update requirements.yml

ansible/roles/ocp4-workload-eap8-workshop/defaults/main.yml, ansible/roles/ocp4-workload-eap8-workshop/tasks/create_che_workspace.yaml, ansible/roles/ocp4-workload-eap8-workshop/tasks/install-gitea.yaml, ansible/roles/ocp4-workload-eap8-workshop/tasks/install-username-distribution.yaml, ansible/roles/ocp4-workload-eap8-workshop/tasks/load-artifacts.yaml, ansible/roles/ocp4-workload-eap8-workshop/tasks/post_workload.yml, ansible/roles/ocp4-workload-eap8-workshop/tasks/verify-workload.yaml, ansible/roles/ocp4-workload-eap8-workshop/tasks/workload.yml
Moved gitea to use existing workload
=> Moved gitea to use existing workload

tests/static/syntax-check.sh
Branchs on https://github.com/ansible/workshops.git are devel or main, default is devel
static checks
=> [syntax-check.sh] Change branch name for ansible-workshops

ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml
add pip upgrade to certbot role
host-letsencrypt-certs-certbot
```paste below
```
=> add pip upgrade to certbot role

ansible/roles_ocp_workloads/ocp4_workload_project_dance/files/tekton-chains.yaml, ansible/roles_ocp_workloads/ocp4_workload_project_dance/tasks/setup_rekor.yml, ansible/roles_ocp_workloads/ocp4_workload_project_dance/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_project_dance/templates/route-rekor.yml.j2
=> Project Dance: Install local rekor instance

ansible/roles_ocp_workloads/ocp4_workload_project_dance/tasks/setup_rekor.yml
=> RH1: Add retry for public key

ansible/roles_ocp_workloads/ocp4_workload_habana_gaudi_gpu_setup/templates/habana-gaudi/habana_gpu_deviceconfig.yaml.j2
Updated habana device config as per new structure by habana ai operator
```paste below
```
=> (WIP) Updated habana device config as per new structure by habana ai operator

ansible/roles_ocp_workloads/ocp4_workload_project_dance/files/tekton-config.yaml
=> Project Dance: Revert taskrun storage 

CODEOWNERS
- Repo pull request
```paste below
```
=> CODEOWNERS: req agnosticd-core for ee-multicloud

ansible/roles_ocp_workloads/ocp4_workload_submariner/tasks/workload.yml
CI Achieve Business Continuity with Red Hat OpenShift https://aap2-prod-us-east-2.aap.infra.demo.redhat.com/#/jobs/playbook/127430/output
```paste below
```
=> adding retries:50 in workload ocp4_workload_submariner

ansible/roles/ocp4-workload-nfs-provisioner/.yamllint, ansible/roles/ocp4-workload-nfs-provisioner/README.md, ansible/roles/ocp4-workload-nfs-provisioner/defaults/main.yml, ansible/roles/ocp4-workload-nfs-provisioner/files/openshift-template-nfs-client-provisioner.yaml, ansible/roles/ocp4-workload-nfs-provisioner/tasks/main.yml, ansible/roles/ocp4-workload-nfs-provisioner/tasks/post_workload.yml, ansible/roles/ocp4-workload-nfs-provisioner/tasks/pre_workload.yml, ansible/roles/ocp4-workload-nfs-provisioner/tasks/remove_workload.yml, ansible/roles/ocp4-workload-nfs-provisioner/tasks/workload.yml
For OpenShift running on CNV, this will allow to have RWX Filesystem.
New OCP4 role: ocp4-workload-nfs-provisioner
=> [ocp4-workload-nfs-provisioner] Add a new role for NFS provisioner

ansible/roles-infra/infra-images/defaults/main.yaml
=> Adding RHEL9.3 Gold Image

ansible/configs/rosa-consolidated/default_vars.yml, ansible/configs/rosa-consolidated/install_rosa_hcp.yml, ansible/configs/rosa-consolidated/install_rosa_sts.yml
Simplified deployment logic.
Added settings to set worker instances and disk sizes
Added settings to turn on autoscaler.
=> Add deployment properties to rosa

ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/deploy-showroom.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/prepare-variables.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/applicationset.yaml.j2
- start parsing shrm svc to user_data
- helm is insane, make all booleans to strings
- more changes to help helm
=> SHOWROOM OCP: fix helm truthiness, start debugging services

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhbk.yaml
Fix RHBK CRD verification in Quarkus workshop
```paste below
```
=> Fix RHBK CRD verification in Quarkus workshop

ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/deploy-showroom.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/prepare-variables.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/applicationset.yaml.j2
- fix doubleunderbar
- back to booleans
=> judd doubleunderbar

ansible/roles/showroom/templates/index.html.j2
Modify showroom role to allow full browser lab iframe - ie no tabs, simply `showroom_tab_services: []`
roles/showroom
=> Allow full screen lab iframe

ansible/roles/ocp4-workload-quarkus-workshop/files/rhbk-postgres-ss.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/rhbk-postgres-svc.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhbk.yaml
Split Postgres resource to statefulset and service in Quarkus workshop
```paste below
```
=> Split Postgres resource to statefulset and service in Quarkus workshop

ansible/roles/ocp4-workload-quarkus-workshop/files/rhbk-postgres-svc.yaml
Add a namespace in Quarkus workshop
```paste below
```
=> Add a namespace in Quarkus workshop

ansible/configs/ansible-lightspeed/default_vars_openshift_cnv.yml
Increase cores and memory
Config ansible-lightspeed
=> [ansible-lightspeed] Increase VM resources

ansible/roles-infra/infra-vmc-resources/tasks/delete_segment.yaml
delete vmc segments before deleting the segment
roles-infra/infra-vmc-resources
```paste below
```
=> add deletion of segment ports

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhbk.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/verify-workload.yaml
Fix the var issue and remove unncessary verifications in quarkus workshop
```paste below
```
=> Fix the var issue and remove unncessary verifications in quarkus workshop

ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
Update email body in quarkus workshop
```paste below
```
=> Update email body in quarkus workshop

ansible/configs/sandbox/post_software_vmc.yml
Improve the message for OCP 4.14
Config sandbox
=> [sandbox] Update post_software_vmc.yml

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml
Fixes an issue where a var name was not updated
```paste below
```
=> Adds the proper var name

ansible/roles/host-ocp4-assisted-installer/tasks/print_cluster_info.yml
Add retries to oc commands
Host-ocp4-assisted-installer role
=> [host-ocp4-asssisted-installer] Update print_cluster_info.yml

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml
Fixes automation controller configuration from an aap2 ee
```paste below
```
=> Fix aap2 controller config

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml
Fixes a hardcoded value.
```paste below
```
=> Fixed hardcoded url

ansible/roles/showroom/templates/index.html.j2
Showroom "tabless" ie no tabs didn't scroll - fixed.
-
roles/showroom
=> Fixed no scroll bug in showroom for full screen lab ie tabless

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml
Fixes a missing var
```paste below
```
=> Fixes a missing var

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/pre_workload.yml
Helm was always checked / installed even if the deployment type is set to ArgoCD.
=> Only install helm when requested

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/workload.yml
Update checks for LVM cluster equinix
ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/workload.yml
=> Update checks for LVM cluster equinix

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml
Fix the email body in MAD DEV
```paste below
```
=> Fix the email body in MAD DEV

ansible/roles-infra/infra-vmc-resources/tasks/create_public_ip_and_nat.yaml, ansible/roles-infra/infra-vmc-resources/tasks/delete_public_ip_and_nat.yaml
NSX-T requires this new parameter when updating a group
Role infra-vmc-resources
=> [infra-vmc-resources] Add group_type parameter to NSXT call

ansible/roles/ansible_bu_setup_workshop/tasks/common/cockpit.yml, ansible/roles/ansible_bu_setup_workshop/templates/hosts/ripu.j2, ansible/roles/ansible_bu_setup_workshop/templates/student-99-webui.json.j2
Rectification after review
Role: ansible_bu_setup_workshop
=> Ansible BU workshop RIPU

ansible/configs/open-environment-azure-subscription/destroy_env.yml, ansible/configs/open-environment-azure-subscription/post_software.yml, ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml
- fix username value
- put the showroom delete after azure cleanup
=> judd fix az showroom delete

ansible/configs/rosa-consolidated/uninstall_rosa.yml
rosa uninstall has a new flag --best-effort. Add a second task to retry the uninstall using that flat if the original uninstall fails.
=> Add rosa uninstall with best effort if regular uninstall failed.

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/remove_workload.yml
fix showroom delete
ocp4_workload_showroom 
```paste below
```
=> fix showroom delete

ansible/configs/sap-hana/software.yml
=> adding ansible 8.3 verison in exclude

ansible/roles_ocp_workloads/ocp4_workload_rocket_chat/tasks/workload.yml
Adding token and user id to userdata
Role: ocp4_workload_rocketchat
=> Event-driven Ansible and ChatOps

ansible/configs/podman-container-wksp/destroy_env.yml
=> remove bookbag in config

ansible/configs/podman-container-wksp/destroy_env.yml
=> Update destroy_env.yml in podman-container-wksp

ansible/configs/rhel9-workshop/default_vars.yml, ansible/configs/rhel9-workshop/pre_infra.yml, ansible/configs/rhel9-workshop/pre_software.yml
Moving to using the standard ssh key role
ansible/configs/rhel-9-workshop
=> rhel-9-workshop Use env_authorized_key_path_pub

ansible/configs/migrating-to-ocpvirt/post_software.yml
=> [migrating-to-ocpvirt] Disable deploy with images

ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/templates/redhat-datasciencecluster.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/templates/redhat-dsc_initialization.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/templates/redhat-ods-operator-group.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/templates/redhat-ods-operator.yaml.j2
OpenShift AI new role to setup operator and related configs.
OpenShift AI new role to setup operator and related configs.
```paste below
```
=> Openshift AI - New role

ansible/configs/migrating-to-ocpvirt/pre_software.yml
We require to download the Windows iso now as we are not using images
Config migrating-to-ocpvirt
=> [migrating-to-ocpvirt] Download windows image

ansible/configs/roadshow-ocpvirt/post_infra.yml
This debug is not needed, specially now moving to route53
Config roadshow-ocpvirt
=> [roadshow-ocpvirt] Remove not needed debug

ansible/configs/roadshow-ocpvirt/pre_software.yml
Task not needed
```paste below
```
=> Remove unneeded task

ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/templates/installplan.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/templates/redhat-ods-operator-subscription.yaml.j2
updated to setup auto update false logic
updated to setup auto update false logic
```paste below
```
=> (WIP) Openshift ai - logic to not do auto update of openshift ai operator

ansible/configs/ocp4-cluster/post_software.yml, ansible/roles/host-ocp4-assisted-destroy/tasks/main.yaml, ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml, ansible/roles/host-ocp4-assisted-installer/vars/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_le_certificates/tasks/workload.yml
This PR is to prepare agnosticD to use Route53 on OpenShift Virtualization
- ocp4-cluster config
- host-ocp4-assisted-destroy role
- host-ocp4-assisted-installer role
- ocp4_workload_le_certificates ocp role
=> OCPV: Move to Route53

ansible/configs/rosa-consolidated/destroy_env.yml
Building a Modern Application Platform
=> fix destroy rosa consolidated for book bag

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml
=> [host-ocp4-assisted-installer] Fix dns record for apps (route53)

ansible/configs/quay-rhel-poc/destroy_env.yml
=> Update destroy_env.yml for Deploy Red Hat Quay on RHEL

ansible/roles_ocp_workloads/ocp4_workload_external_odf/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_external_odf/templates/odf-sub.yaml.j2
To avoid issues specifying the startingCSV, removing this line will automatically set
ocp4_workload_external_odf Role
=> [ocp4_workload_external_odf] Remove StartingCSV to avoid future issues

ansible/configs/open-environment-azure-subscription/default_vars.yml, ansible/configs/open-environment-azure-subscription/destroy_env.yml, ansible/configs/open-environment-azure-subscription/infra.yml, ansible/configs/open-environment-azure-subscription/post_infra.yml, ansible/configs/open-environment-azure-subscription/post_software.yml, ansible/configs/open-environment-azure-subscription/pre_infra.yml, ansible/configs/open-environment-azure-subscription/pre_software.yml, ansible/configs/open-environment-azure-subscription/requirements.yml, ansible/configs/open-environment-azure-subscription/software.yml, ansible/configs/rosa-consolidated/post_software.yml
Add showroom to aro subscription env.
Fix ansible lint warnings.
Cleanup.
=> Add Showroom to ARO. Fix linter warnings

ansible/roles/host-ocp4-provisioner/tasks/gcp_prereqs.yml
Reverts redhat-cop/agnosticd#7527
=> Revert "Update gcp_prereqs.yml - fix up google ocp4"

ansible/configs/ocp4-cluster/files/requirements_openshift_cnv_el9.txt
Add requirements file for RHEL9 when we use openshift_cnv
ocp4-cluster Config
=> [ocp4-cluster] Support for RHEL9 on OCPV

ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml
Using local disk the live migration is not possible
=> [host-ocp4-assisted-installer] Remove evictionStrategy for control planes

ansible/roles/asset_injector/tasks/main.yml
Extend the asset injector to do removal as well as injector
=> Enhance asset injector dictionary to remove functionality

ansible/configs/base-infra/software.yml
Remove redundant, and breaking, code from base-infra
=> Remove redundant verification in software.yml, base-infra

ansible/configs/open-environment-azure-subscription/default_vars.yml, ansible/configs/open-environment-azure-subscription/install_helm.yml, ansible/configs/open-environment-azure-subscription/post_infra.yml, ansible/configs/open-environment-azure-subscription/post_software.yml, ansible/configs/open-environment-azure-subscription/pre_infra.yml, ansible/configs/open-environment-azure-subscription/pre_software.yml, ansible/configs/open-environment-azure-subscription/requirements.yml, ansible/configs/open-environment-azure-subscription/software.yml
Install Helm on bastion. Code cleanup (especially default vars).
Add support to remove insights motd and add custom motd to bastion.
=> Install more tools. Add motd capability

ansible/configs/open-environment-azure-subscription/pre_software.yml
Ran tasks to update the motd on the bastions as remote_user instead of root.
=> Fix permissions to update motd on bastions

ansible/roles_ocp_workloads/ocp4_workload_cockroach_dbaas_amq_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cockroach_dbaas_amq_lab/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cockroach_dbaas_amq_lab/tasks/remove_workload.yml
Update **Architecting event-driven apps with OpenShift CockroachDB Kafka** tear create and teardown cockroach serverless cluster
ocp4_workload_cockroach_dbaas_amq_lab
```
=> Update Architecting event-driven apps with OpenShift CockroachDB Kafka tear create and teardown cockroach serverless cluster

ansible/roles_ocp_workloads/ocp4_workload_retail_aiml_workshop/tasks/workload.yml
Added user data for sandbox id.
Added user data for sandbox id
```paste below
```
=> (WIP) Update workload.yml - Added user data for sandbox id

ansible/roles/host-ocp4-provisioner/tasks/gcp_prereqs.yml
Remove Google SDK install
```paste below
```
=> Remove Google SDK install

ansible/roles_ocp_workloads/ocp4_workload_cloud_architecture_workshop_summit2023/defaults/main.yml
Fix issue with quotes in the `ocp4_workload_cloud_architecture_workshop_summit2023` config.
ocp4_workload_cloud_architecture_workshop_summit2023
```paste below
```
=> Cloud architecture workshop: fix issue with quotes

ansible/roles/asset_injector/README.adoc, ansible/roles/asset_injector/tasks/main.yml
Extend asset injector to support more capabilities (file removal, blockinfile, service management)
=> Role asset injector 2024 01 04

ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/meta/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/tasks/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/tasks/post_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/tasks/pre_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/tasks/remove_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/tasks/workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_test_drive/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_test_drive/meta/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_test_drive/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_oai_test_drive/tasks/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_test_drive/tasks/post_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_test_drive/tasks/pre_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_test_drive/tasks/remove_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_test_drive/tasks/workload.yaml
=> Oai lab insurance claim

ansible/configs/sandbox/default_vars_vmc.yaml
Rename bastion to bastion-GUID
sandbox config
=> [sandbox] Update default_vars_vmc.yaml

ansible/configs/roadshow-ocpvirt/pre_software.yml
=> updating the intent for the retries

ansible/configs/hcp-ocpv/.yamllint, ansible/configs/hcp-ocpv/README.adoc, ansible/configs/hcp-ocpv/default_vars_equinix_metal.yml, ansible/configs/hcp-ocpv/destroy_env.yml, ansible/configs/hcp-ocpv/files/configure_operators.sh, ansible/configs/hcp-ocpv/files/htpasswd.yaml, ansible/configs/hcp-ocpv/files/replace_certs.sh, ansible/configs/hcp-ocpv/post_infra.yml, ansible/configs/hcp-ocpv/post_software.yml, ansible/configs/hcp-ocpv/pre_infra.yml, ansible/configs/hcp-ocpv/pre_software.yml, ansible/configs/hcp-ocpv/requirements.yml, ansible/configs/hcp-ocpv/sample_vars_equinix_metal.yml, ansible/configs/hcp-ocpv/software.yml
Add config for Hosted Control Planes on OpenShift Virtualization
hcp-ocpv config
=> Adding new hcp-ocpv config

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/rhdh/application_rhdh.yaml.j2
After improving the agnosticv var I'm updating agnosticd to match the new variable.
Variable will be used in M7- RHDH
```
=> update variable name to match new agnosticv var name

ansible/configs/ansible-automation-platform/env_vars.yml
Update ansible-automation-platform config to AAP 2.4 and RHEL 9.3 - just a refresh of the config.
related to PR agnosticv/pull/13377 resp. sandboxes-gpte/AUTOMATION_CONTROLLER_ADVANCED
=> Update ansible-automation-platform config to AAP 2.4 and RHEL 9.3

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhdh-main.yml
Added a secret for DevSpaces in the Mad Module using RHDH
=> Adding secret for DevSpaces - MAD

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhdh-main.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/gitlab/application.yaml.j2
Update branch path to use main instead of previous branch mad for gitlab setup- 
MAD workshopw. module rhdh
```
=> Update branch path

ansible/configs/open-environment-azure-subscription/pre_software.yml
=> adding retries

ansible/configs/hcp-ocpv/post_software.yml
TASK [Pre-install operators] *************************************************** FAILED - RETRYING: [bastion-vm]: Pre-install operators (10 retries left). FAILED - RETRYING: [bastion-vm]: Pre-install operators (9 retries left). FAILED - RETRYING: [bastion-vm]: Pre-install operators (8 retries left). FAILED - RETRYING: [bastion-vm]: Pre-install operators (7 retries left). FAILED - RETRYING: [bastion-vm]: Pre-install operators (6 retries left). FAILED - RETRYING: [bastion-vm]: Pre-install operators (5 retries left). FAILED - RETRYING: [bastion-vm]: Pre-install operators (4 retries left). FAILED - RETRYING: [bastion-vm]: Pre-install operators (3 retries left). FAILED - RETRYING: [bastion-vm]: Pre-install operators (2 retries left). FAILED - RETRYING: [bastion-vm]: Pre-install operators (1 …
=> Update post_software.yml - increase retires install operators hcp ocp

ansible/configs/roadshow-ocpvirt/vcenter-setup-user.yml
Remove assign permissions to the hosts
roadshow-ocpvirt config
=> [roadshow-ocpvirt] Update vcenter-setup-user.yml

ansible/setup_runtime.yml
Add support for `agnosticd_passthrough_user_data` mechanism to allow for a generic method to pass user data from extra vars.
AgnosticD core
=> Add support for agnosticd_passthrough_user_data

ansible/roles-infra/infra-dns/tasks/nested_loop.yml
Add retries to the rest of the route53 calls
infra-dns role
=> [infra-dns] Add retries to the rest of the route53 calls

ansible/configs/roadshow-ocpvirt/post_software.yml
=> Minor fix: console wording

ansible/configs/ocp4-cluster/post_software.yml, ansible/roles/ms_vscode_server/tasks/main.yml, ansible/roles/rhel-graphical/tasks/main.yml
Added student workload task in workload.yaml. The change is required to install certain packages to enable Desktop packages and install VScode on bastion
=> [WIP]Added Software workload for bastion

ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/fetch_and_apply_template.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/workload.yml
=> RHTAP: Include RH TPA in CI

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/workload.yml
As IPA server is not working, trying upgrade it to new one by `--set image=`
ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/workload.yml
=> Update workload.yml to upgrade IPA server

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/gitlab/application.yaml.j2
Add gitlab users count for MAD module 7 with RHDH.
=> add variable for gitlab user count

ansible/configs/ocp4-cluster/destroy_env_openshift_cnv.yml
Till now was not needed to remove workloads on openshift_cnv, but we have a use case for cockroach dbaas which is required
ocp4-cluster role
=> [ocp4-cluster] Add remove workload to openshift_cnv cloud provider

ansible/configs/zero-touch-base-rhel/pre_software.yml
Adds ssh configuration for the "rhel" user
This change was enabled to fix issues with showroom not being able to ssh as the rhel user
```paste below
```
=> zero-touch-base-rhel Update pre_software.yml to configure ssh for rhel user

ansible/configs/zero-touch-base-rhel/pre_software.yml
Update to include authorized_key file for the rhel user
zero-touch-rhel-base
```paste below
```
=> "zero-touch-rhel-base" Update to include authorized key file for the rhel user

ansible/configs/zero-touch-base-rhel/post_software.yml
Fixes an issue with a missing module parameter
```paste below
```
=> Zero touch rhel server hardening

ansible/configs/zero-touch-base-rhel/post_software.yml
Zero Touch RHEL hardening, adds parameters
```paste below
```
=> Zero Touch RHEL hardening, adds parameters

ansible/configs/zero-touch-base-rhel/lock_bastion_security_group.yml
=> Zero Touch RHEL update egress rules for testing

ansible/configs/zero-touch-base-rhel/default_vars_ec2.yml, ansible/configs/zero-touch-base-rhel/lock_bastion_security_group.yml
Zero Touch RHEL, update security groups and associated tasks
```paste below
```
=> Zero Touch RHEL, update security groups and associated tasks

ansible/configs/zero-touch-base-rhel/lock_bastion_security_group.yml
Removes old broken code
zero-touch-rhel-base
```paste below
```
=> zero touch rhel removing broken code

ansible/roles_ocp_workloads/ocp4_workload_oai_lab_gen_ai/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_gen_ai/meta/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_gen_ai/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_gen_ai/tasks/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_gen_ai/tasks/post_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_gen_ai/tasks/pre_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_gen_ai/tasks/remove_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_gen_ai/tasks/workload.yaml
New Role for Gen AI
Gen AI demo specific role.
```paste below
```
=> (WIP) Added new role for Gen AI

ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/README.md, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/files/acs-signature-policy.json, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/fetch_and_apply_template.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/setup_ec.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/setup_showroom_data.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/setup_stackrox.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/update_existing_policies.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_stackrox.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_tekton_chains.yml, test.yaml
=> RHTAP-wks: Initial upload of workshop roles

ansible/configs/tap-workshop-binder/README.adoc, ansible/configs/tap-workshop-binder/default_vars.yml, ansible/configs/tap-workshop-binder/default_vars_ec2.yml, ansible/configs/tap-workshop-binder/destroy_env.yml, ansible/configs/tap-workshop-binder/infra.yml, ansible/configs/tap-workshop-binder/post_infra.yml, ansible/configs/tap-workshop-binder/post_software.yml, ansible/configs/tap-workshop-binder/pre_infra.yml, ansible/configs/tap-workshop-binder/pre_software.yml, ansible/configs/tap-workshop-binder/requirements.yml, ansible/configs/tap-workshop-binder/sample_vars.yml, ansible/configs/tap-workshop-binder/software.yml, ansible/configs/tap-workshop-binder/stop.yml
New Binder config for Red Hat TPA Workshop
Config: tpa-workshop-binder
=> New Binder Config for TPA WORKSHOP 

ansible/configs/tap-workshop-binder/post_software.yml
=> RHTAP-wks: pull hostname from console url

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_tekton_chains.yml
=> RHTAP-wks: Bug fix to start in tmp directory

ansible/configs/tap-workshop-binder/post_software.yml
Adding Showroom to binder
config: tap-workshop-binder
=> Tap workshop binder

ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/openshift-oauth.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/openshift-openid-client-secret.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/rhsso-client-openshift.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/rhsso-instance.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/rhsso-realm-openshift.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_rhsso_authentication/templates/rhsso-user-openshift.yml.j2
SSO Auth Workload always required a catalog snapshot. Added a var to optionally turn that off.
Also went through the whole workload and fixed all ansible-lint errors.
ocp4_workload_rhsso_authentication
=> Add flag to turn off catalog snapshots. Fix all ansible-lint errors.

ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/templates/cluster_role_binding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/vars/main.yaml
Updated the workload to support ROSA HCP clusters.
Fixed a ton of yamllint warnings.
Added support for randomized user passwords.
ocp4_workload_authentication_rosa
=> Update Cognito Auth workload. Fix yamllint. Support HCP. Add randomized passwords.

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/tasks/rhdh-main.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/tasks/rhdh-setup-variables.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/templates/devspaces/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/templates/gitlab/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/templates/rhdh/application_configs.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/templates/rhdh/application_plugins.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/templates/rhdh/application_rhdh.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/templates/rhdh/rhsso-client-openshift.yml.j2
Add RDDH to MAD v2
```paste below
```
=> Add RDDH to MAD v2

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/templates/apps/application_rhdh.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/templates/apps/namespace_argo.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/templates/apps/user_roles_sso.yaml.j2
Fix RHDH error in MAD V2
```paste below
```
=> Fix RHDH error in MAD V2

ansible/configs/roadshow-ocpvirt/requirements.yml
Use rhpds instead my personal git repository
roadshow-ocpvirt config
=> [roadshow-ocpvirt] Update scm ref for requirements

ansible/roles_ocp_workloads/ocp4_workload_external_odf/templates/storageclass.yaml.j2
To move forward to have multiple CNV clusters, this need to be fixed
ocp4_workload_external_odf role
=> [ocp4_workload_external_odf] Parameterize pool for the storageclass

ansible/configs/sap-hana/default_vars_openshift_cnv.yaml, ansible/configs/sap-hana/post_software.yml, ansible/configs/sap-hana/pre_software.yml, ansible/configs/sap-hana/requirements.yml, ansible/configs/sap-hana/software.yml
Add configuration for SAP HANA to run on CNV
=> [sap-hana] Add support for CNV

ansible/roles/eda_controller_config/tasks/create/create_rulebook_activation.yml
Fixed token error of the role
Role: eda_controller_config
=> fixed the eda token error

ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/files/acs-signature-policy.json, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/deploy-insecured.sh.j2, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/deploy-secured.sh.j2, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/validate-insecured.sh.j2, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/validate-secured.sh.j2
=> Summit Lab 1090: Fix scripts
