redhat-cop/agnosticd

ansible/configs/ocp4-cluster/requirements.yml

The config ocp4-cluster had some rather old collections in its requirements file.
Updated to the current available ones.
Also added community.crypto because of changes to the authentication workload (which now uses the htpasswd module - which requires crypto).
These have been tested for quite a while in other existing configs (MAD Roadshow etc.) via overrides.
ocp4-cluster

Update default collections for ocp4-cluster

---

ansible/roles/install_operator/tasks/install.yml

When installing ElasticSearch operator, the namespace was not created because the condition matched, when it shouldn't.
```
- name: install elasticsearch operator
ansible.builtin.include_role:
name: install_operator
vars:
install_operator_name: elasticsearch-operator
install_operator_namespace: openshift-operators-redhat
...
```

Fix install_operator namespace creation

---

ansible/roles/aap_deploy/templates/automationcontroller_inventory.j2

1. If there is a PAH, controller should pull the EE images from it instead from redhat.io.
1. Enable the disabling of Insights in aap_deploy
aap_deploy (role)
Works now with AAP 2.3

Improve aap_deploy to be less dependent on Internet/Red Hat CDN

---

ansible/configs/rosa-manual/default_vars.yml
ansible/configs/rosa-manual/software.yml

Add a variable to rosa_manual config to suppress agnosticd_user_info messages. This is to beautify the workshop output when claiming an environment until workshop has the adoc template capability.
rosa_manual

Add flag to suppress agnosticd_user_info messages to rosa_manual

---

ansible/roles/open-env-azure-install-aro/tasks/main.yml

add retries to kubernetes operations
open-env-azure-aro
```paste below
```

add retries to kubernetes operations

---

ansible/configs/ocp4-cluster/post_software.yml

remove kubeadmin password msg for azure ocp4
ocp4-cluster
```paste below
```

remove kubeadmin password msg for azure ocp4

---

ansible/configs/ocp4-cluster/post_software.yml

fix bastion ssh hostname for azure ocp
ocp4-cluster
```paste below
```

fix bastion ssh hostname for azure ocp

---

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_devspaces.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_tekton.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/devspace_workspace.yml.j2

This change fixes an issue that was affecting the Tekton Operator install.
It also includes a set of tasks to augment the Openshift DevSpaces installation to warm-up the users' WorkSpaces.
N/A
```
ansible [core 2.14.3]
python version = 3.11.2 (main, Feb 16 2023, 03:15:23) [Clang 14.0.0 (clang-1400.0.29.202)] (/usr/local/Cellar/ansible/7.3.0/libexec/bin/python3.11)
jinja version = 3.1.2
libyaml = True
```
The new output for the Devspaces install phase
```
TASK [roles_ocp_workloads/ocp4_workload_performance_monitoring : Get DevWorkspace pods in users' namespaces] **************************************************************************
FAILED - RETRYING: [localhost]: Get DevWorkspace pods in users' namespaces (30 retries left). …
```

fixing lint issues

---

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/readme.adoc
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/admin_secret.j2
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/automationcontroller.j2
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/namespace.j2
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/operatorgroup.j2
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/subscription.j2

- Installs Ansible Automation Platform (Controller and Hub) on OpenShift (currently 2.3 on OCP 4.12)
- Optionally injects manifest
- Does **not**, by design, load any resources into Controller and Hub
```paste below
```

New ocp4_workload_ansible_automation_platform

---

ansible/roles-infra/infra-vmc-resources/tasks/create_public_ip_and_nat.yaml

TASK [infra-vmc-resources : Add public IP to VM guest attributes] **************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: }
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1681871891.8768113-1513-232574941244844/AnsiballZ_vmware_guest_custom_attributes.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1681871891.8768113-1513-232574941244844/AnsiballZ_vmware_guest_custom_attributes.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1681871891.8768113-1513-232574941244844/AnsiballZ_vmware_guest_cus …

[infra-vmc-resources] Update create_public_ip_and_nat.yaml to add retries

---

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/workload.yml

Need to be root to install binaries into /bin. Fixing.

Add missing become to hcp download

---

ansible/roles/bookbag/tasks/workload.yaml

When not running as cluster admin the check if a project exists will fail with a 403 error and the design of the `k8s_info` module does not allow differentiation based on the error code.
bookbag role

Disable retries on bookbag get project

---

ansible/configs/rosa-manual/software.yml

Update AWS CLI to v2 for ROSA Manual config.
rosa_manual

Update AWS CLI to v2 in ROSA Manual

---

ansible/roles/bookbag/tasks/workload.yaml

Fix bookbag build retries:
- Watch for errors in stderr of `oc start-build`
- Set GIT_REPO in BuildConfig
bookbag role

Fix bookbag build retry

---

ansible/roles/bookbag/tasks/workload.yaml

Retry build if `build error:` is in build stdout.
bookbag role

Retry bookbag build on build error

---

ansible/roles/bookbag/tasks/workload.yaml

bookbag can still fail on `Task Build bookbag image`
role bookbag

Bump up bookbag image rebuild tries - source of failure

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml

The role ocp4_workload_5gran_deployments_lab is failing cause centos stream images being used by our automation have been removed from the centos mirror. 
This PR points to a new commit for our automation plan that has these links fixed.
```paste below
```

Fixes centos8 streams url

---

ansible/roles/generate_ssh_keypair/README.adoc
ansible/roles/generate_ssh_keypair/defaults/main.yml
ansible/roles/generate_ssh_keypair/tasks/main.yml

For configs etc that need their own ssh keys for demos etc like AAP2 controllers making VMs

Role generate_ssh_keypair to generate an ssh keypair

---

ansible/roles/vscode-server/tasks/vscode-server.yml

Because the VScode terminal isn't a login session, it can be that podman complains about no systemd user session being available. loginctl enable-linger solves the issue
vscode_server
tested with advanced automation controller

Add loginctl command to vscode-server role to avoid podman moaning

---

ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/setup_htpasswd.yml

- The name "console_url" conflicts with a builtin variable for bookbag/openshift-homeroom.
- The name "openshift_console_url" is more descriptive.

Set openshift_console_url in ocp4_workload_authentication

---

ansible/roles/automation_platform_loader/README.adoc
ansible/roles/automation_platform_loader/defaults/main.yml
ansible/roles/automation_platform_loader/tasks/main.yml

role to populate Ansible Automation Controllers and Hub with resources (projects, creds, job_templates etc)
- generates, optionally, an ssh key for a default machine credential (useful in infra/cloud deploys
- wraps `infra.controller_configuration.dispatch` to populate AAP2
-

New automation_platform_loader role to populate AAP resources

---

ansible/roles/bookbag/tasks/wait-for-bookbag-deployment.yml

Need retries on `oc rollout` in bookbag deployment retry because the previous deployment attempt may not be marked as complete after it has failed.
bookbag role

Add retries to oc rollout in bookbag role

---

ansible/roles/agnosticd_restore_output_dir/tasks/fetch-from-s3-s3_object.yml

Newer versions of amazon.aws.s3_object module do not return a message indicating why the response code was forbidden. Need to handle 403 as a non-error.
Role agnosticd_restore_output_dir

Fix agnosticd_restore_output_dir to not consider 403 an error

---

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/workload.yml

Add facts to the ocp aap2 installer role for availability elsewhere eg the loader role
roles_ocp_workloads/ocp4_workload_ansible_automation_platform

Add facts to AAP2 OCP installer workload

---

ansible/configs/ocp-workloads/default_vars.yml
ansible/configs/ocp-workloads/post_infra.yml
ansible/configs/ocp-workloads/readme.adoc
ansible/configs/ocp-workloads/sample_vars/authentication-and-bookbag.yaml

Add ability to use `target_host: localhost` with ocp-workloads config.
Config ocp-workloads

Add localhost support for ocp-workloads

---

ansible/roles/automation_platform_loader/tasks/main.yml

- Added, off by default (in case not running on OCP, OCP bearer token generation for OCP AAP2 creds
- Refactored main.yml as it was getting long

Add ocp bearer token and refactor aap2 loader role

---

ansible/roles/automation_platform_loader/tasks/ocp_bearer_token.yml

- Bug fix, kubeadmin password was not available to role, user_data and not a fact)
- This retrieves it to allow token generation via oc login

Enhance ocp_bearer_token logic for aap loader role

---

ansible/roles/automation_platform_loader/tasks/ocp_bearer_token.yml

Simple fix - forgot to dereference register correctly
(r_kubeadmin_password.content | b64decode )

Fix bad register ref for ocp - try undecoding it next time

---

ansible/configs/ocp4-cluster/files/requirements_k8s.txt

ocp4_cluster breaking on venv deps
https://levelup.gitconnected.com/fix-attributeerror-module-lib-has-no-attribute-openssl-521a35d83769
pin pyopenssl to 23.1.1
Recent upgrade to more modern pip deps (#6388) introduced breaking changes to lets encrypt workload
ocp4_cluster

Upgrade ocp4 cluster pyOpenSSL to 23.1.0 LEcryprt dep issue

---

docs/Deploying_Using_Execution_Environments.adoc

Environments on Fedora Linux 37
Updating deploying execution environments document with instructions for Linux
A couple of fixes to the instructions for MAC commands that are using incorrect directory paths
Reformatted with ToC as the file is larger now, and changed heading levels to match with the new "Mac" and "Linux" headers
Deploying_Using_Execution_Environments.adoc
Instructions for Mac did not work for Linux (Fedora 37), so I have tested these and pulled them from my history and attempted to format as closely to the Mac setup as possible for parallelism.
I have swapped podman rootless for docker in the Linux config, as well, as this is what I tested.

Adding linux-based instructions for deploying with Ansible Execution

---

ansible/roles/ocp4-workload-dil-serverless/tasks/user_terminal.yaml

Update user_terminal.yaml
use 
ocp4_workload_authentication 
instead of dil authentication
https://github.com/rhpds/agnosticv/blob/master/azure_gpte/SUMMIT_2021_AZURE_MULTICLOUD_WKSP/dev.yaml 
TASK [ocp4-workload-dil-serverless : Log in OCP as user1] **********************
fatal: [bastion-7f2d2]: FAILED! => {"changed": false, "msg": "Authorization failed.", "req_method": "GET", "req_reason": "Unauthorized", "req_status_code": 401, "req_url": "https://oauth-********.apps.ocp4-7f2d2-ipi.azure.opentlc.com/oauth/authorize?response_type=code&client_id=********-challenging-client&state=1&code_challenge_method=S256"}

ocp4-workload-dil-servless- user-terminal - authentication change 

---

ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/templates/cert-utils-operarator.j2

ocp4_workload_cert_utils_operator failed because yaml lacked namespace - added
ocp4_workload_cert_utils_operator

Add namespace to cert_utils subscription

---

ansible/roles_ocp_workloads/ocp4_workload_cert_utils_operator/templates/cert-utils-operarator.j2

Forgot namespace in cert-utils OperatorGroup!
roles_ocp_workloads/ocp4_workload_cert_utils_operator

Add namespace to cert-utils OperatorGroup

---

ansible/roles/host-lets-encrypt-certs-certbot/files/requirements_certbot.txt
ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml
ansible/roles/host-lets-encrypt-certs-certbot/templates/run-certbot.j2
ansible/roles_ocp_workloads/ocp4_workload_le_certificates/tasks/workload.yml

Add LE/certbot support to OCP on GCP
ocp4_workload_le_certificates
```paste below
```

add LE/certbot to GCP deployments

---

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/workload.yml

OCP AAP2 installer roll now extends default ocp bearer token to 2 weeks for use as a cred in AAP
roles_ocp_workloads/ocp4_workload_ansible_automation_platform

Extend OCP bearer token lifecycle

---

ansible/roles/host-lets-encrypt-certs-certbot/files/requirements_certbot.txt

commenting line in latest commit to remove certbot-dns-google==1.17.0
```paste below
```

comment line in requirements_certbot.txt

---

ansible/roles/host-lets-encrypt-certs-certbot/files/requirements_certbot_gcp.txt
ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml

add new requirement_certbot_gcp for certbot role
```paste below
```

add new requirement_certbot_gcp for certbot role

---

ansible/roles_ocp_workloads/ocp4_workload_cloud_architecture_workshop_summit2023/tasks/bookbag.yml

ocp4_workload_cloud_architecture_workshop_summit2023
Use 'lab_ui_url' as variable for the url to bookbag.

use 'lab_ui_url' to set bookbag url

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml

When running our lab automation, we get random issues related to ssh connections:
~~~console
TASK [ocp4_workload_5gran_deployments_lab : Ensure trusted certs are updated] ***
fatal: [hypervisor]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to hypervisor.example.com closed.", "unreachable": true}
~~~
This change adds ssh connection retries.
```paste below
```

Adds ssh connection retries

---

ansible/configs/sap-hana/software.yml

as per the https://access.redhat.com/solutions/7007839 we need to move two files in /tmp directory in order to register the clients with red hat insight tool
```paste below
```

adding tasks to move newest.egg file

---

ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/tasks/workload.yml

rhjcd-patch-Update workload.yml add when bool for self-provisioner task
<when boolean needed for self-provisioner task as it is not necessary as default in a deploy>

Update workload.yml add when bool for self-provisioner task

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/workload.yml

Fix a typo in var name (double _url_url)
<

Fix showroom var typo (-url_url)

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml

When running our lab automation, we get random issues related to ssh connections:
~~~console
TASK [ocp4_workload_5gran_deployments_lab : Ensure trusted certs are updated] ***
fatal: [hypervisor]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to hypervisor.example.com closed.", "unreachable": true}
~~~
This change adds ssh connection retries.
```paste below
```

Fixes an issue with 5gran workload and tunes ssh

---

ansible/roles/ocp4-workload-workshop-admin-storage/defaults/main.yml
ansible/roles/ocp4-workload-workshop-admin-storage/tasks/post_workload.yml

Adding kubeadmin to user.indo
-->
Adding kubeadmin password to userdata, need to provide this in order to use them for the user-message-template when deploying. 
```paste below
```

Add to AgD user.info for ocp4-workload-workshop-admin-storage 

---

ansible/configs/ocp4-cluster/default_vars.yml

Adding common_packages_el9 to ocp4-cluster config
ocp4-cluster (where a RHEL9 bastion is used)
Due to recent changes in the default playbooks, this is now required when using a RHEL9 bastion.  Since this is undefined in the ocp4-config, it causes the deploy to fail when it should not.
```
TASK [common : install common packages for RHEL 9] *****************************
fatal: [ocp4-cluster.domain.local]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'common_packages_el9' is undefined. 'common_packages_el9' is undefined\n\nThe error appears to be in '/home/jappleii/development/agnosticd/ansible/roles/common/tasks/packages_el9.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax …
```

Adding common_packages_el9 to the ocp4-cluster config for RHEL9 bastion builds

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml

Makes the role use a specific version of the tooling that deploys the cluster to avoid issues when this tool gets updated without being tested in our environment.
```paste below
```

Uses a specific version for the automation tool

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml

Disables the gpg check when installing rpm locally.
```paste below
```

Disabled gpg check for kcli tooling

---

ansible/roles_ocp_workloads/ocp4_workload_dbaas_operator/tasks/workload.yml

Fix ocp4_workload_dbaas_operator CSV install check to not depend on a specific version.
Role ocp4_workload_dbaas_operator

Fix ocp4_workload_dbaas_operator CSV install check

---

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/devspace_cluster.yml.j2
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/devspace_workspace.yml.j2
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/prometheus_pod_monitor.yml.j2

* This PR adjusts DevSpaces CRs to v3.6 (just released this morning breaking our automation)
* It also adds ServiceMonitors for knative-serving services
N/A

ocp4_workload_performance_monitoring: Fix DevSpaces 3.6 CR issue

---

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_devspaces.yml

This PR fix another issue related to the DevSpaces upgrade (v3.6), which now requires a new `scc`.
N/A

ocp4_workload_performance_monitoring: wait for DevSpaces container-build scc

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml

Sometimes some K8s tasks fail because some component is not ready, this PR adds retries to such tasks.
```paste below
```

Adds retries to kubernetes tasks

---

ansible/configs/rosa-manual/software.yml

rosa_manual config had the aws region in ~/.aws/config. But for the AWS CLI to pick up that as the default that does not seem to be enough. Also adding the region to ~/.aws/credentials.
@rut31337 FYI
rosa-manual

Add default AWS region to AWS Credentials for ROSA

---

ansible/configs/sap-hana/software.yml

TASK [Ensure additional packages are installed] ******************************** fatal: [tower-bdwfw]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occured: \n Problem: cannot install the best candidate for the job\n  - nothing provides /usr/bin/python3.11 needed by ansible-7.2.0-1.el8.noarch\n  - nothing provides python(abi) = 3.11 needed by ansible-7.2.0-1.el8.noarch\n  - nothing provides python3.11dist(ansible-core) >= 2.14.2 needed by ansible-7.2.0-1.el8.noarch", "rc": 1, "results": []}
```paste below
```

Excluding the package ansible-7.2.0-1.el8.noarch

---

ansible/roles/showroom/tasks/30-showroom-clone-and-inject.yml
ansible/roles/showroom/tasks/40-showroom-render.yml
ansible/roles/showroom/tasks/main.yml

Added rendering, via podman and antora, to showroom role
Any AgnosticD userdata var, for example `foo` can be automagically referenced via `{foo}` in adoc
roles/showroom

Added and verified showroom rendering

---

ansible/roles/set-repositories/defaults/main.yaml

Make provisions default for set-repositories
```paste below
```

Make provisions default for set-repositories

---

ansible/configs/ocp4-cluster/default_vars.yml
ansible/roles/common/defaults/main.yml

Removed the common el9 package variable from ocp4-cluster. Common packages should not be changed. 
Added hint to ocp4-cluster to use extra packages variable to add packages to the config.
Added `jq` to the default list of packages for RHEL8.
ocp4-cluster
common (role)

Remove common packages from ocp4-cluster, add jq to common on RHEL8

---

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/workload.yml

RHACM 2.8 fixed the hypershift CLI package (it's no longer 5 directories deep). This PR adds a check to unzip it properly for 2.8 and newer as well as for 2.7 and earlier.

Add logic to download hypershift CLI for RHACM 2.8

---

ansible/roles/open-env-azure-create-open-env/tasks/main.yml

add missing "api://" to aro service principal

fix aro service principal name

---

ansible/configs/ansible-automation-platform/env_vars.yml

t3a is slightly cheaper than t2, and some of the helper VMs were rather too big, compensated by the controller/DB being now bigger (to overcome potential performance issues).
ansible-automation-platform (config)
Related to #10250 on AgnosticV

Rebalance sizing of advanced controller and standardize on t3a

---

ansible/roles/showroom/templates/container-compose.yml.j2
ansible/roles/showroom/templates/index.html.j2

Enhancement to the web based ttys in showroom role
- moved from butterfly based to WeTTY
- Automated ssh in tty's i.e. they automatically pre-ssh into the VM (e.g. bastion etc)
- Tweaked tab order with ttys default (then VSCode, external site)
role/showroom

Showroom role, add WeTTY logic replacing butterfly tty in showroom/bookbag 2 UI

---

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/pre_workload.yml

Fixes an issue where pyOpenSSL doesn't exist on the hypervisor and fails the provisioning.
```paste below
```

Adds pyopenssl

---

ansible/configs/ocp4-upi-vmc/templates/install-config.yaml.j2
ansible/configs/ocp4-upi-vmc/templates/power-on.sh.j2

The VMware UPI was never completing successfully.  Demonstrators could not go off script and demonstrate adding a vmware cluster to RHACM.  Now they can.

OHC: Fix VMware cluster UPI

---

ansible/configs/ansible-rhel-workshop/default_vars.yml

Fixed typo in automation controller credential variable

Fixed typo in credentials name

---

ansible/roles/ocp4-workload-dil-streaming/tasks/provision_devspaces.yaml

Updating reties for TASK [ocp4-workload-dil-streaming : Evaluate OpenShift Dev Spaces Cluster] as until logic is already in place.
Role: ocp4-workload-dil-streaming, TASK [ocp4-workload-dil-streaming : Evaluate OpenShift Dev Spaces Cluster]

Update retries as sometimes it is taking much more time than expected

---

ansible/roles/ocp4-workload-ccnrd-stable/files/devspaces_cr.yaml

This PR adds a workaround to configure Dev Spaces to use the online VisualStudio Code extension registry open-vsx.org (thousands of extensions) instead of the embedded one (~50 extensions). 
More details about the problem are available in the upstream issue https://github.com/eclipse/che/issues/22322.
OpenShift Dev Spaces CR file for ocp4-workload-ccnrd-stable 
Before this change some extensions like `redhat.windup-vscode-extension` could not be installed.

Fix role ocp4-workload-ccnrd-stable

---

ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/templates/certmanager/policy.yaml.j2

cert-manager policy was missing the `spec:` line. Added.
Also removed debug information.

fix cert-manager policy, remove debug stuff

---

ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/workload.yml

Starting RHACS 4.1, you can't use the KernelModule anymore, you must use EBPF
It's removed as per the release notes https://docs.openshift.com/acs/4.1/release_notes/41-release-notes.html#kernel-module-collection-method_release-notes-41
ansible/roles_ocp_workloads/ocp4_workload_hands_on_rhacs

Change workload ocp4_workload_rhacs to EPBF collection 

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml

Small changes to adapt to the new version of the lab targeting OCP 4.13. Basically:
- Update to OCP 4.13 release
- Add the change to specify a different Git repo and branch. Notice that this is set in the defaults. That will help us to test the playbook against our forked repo.
cc/ @mvazquezc

Update 5G RAN Lab to latest OCP release 4.13

---

ansible/configs/rosa/default_vars.yml
ansible/configs/rosa/destroy_env.yml
ansible/configs/rosa/files/cloud_providers/ec2_cloud_template.j2
ansible/configs/rosa/pre_software.yml

Fix the rosa config to use the correct SSH keys and not the old deprecated variables.
This change fixes the following  error that occurs on Controller when using EE:
```
TASK [infra-ec2-wait_for_linux_hosts : wait for linux host to be available (retry)] ***12:30:41
640
fatal: [bastion.rhz6l.internal]: FAILED! => {"changed": false, "elapsed": 260, "msg": "timed out waiting for ping module test: Failed to connect to the host via ssh: no such identity: /home/runner/.ssh/opentlc_admin_backdoor.pem: No such file or directory\r\nec2-user@ec2-3-23-174-219.us-east-2.compute.amazonaws.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)."}
```

rosa: remove deprecated SSH variables and role (For EE / Controller)

---

ansible/roles-infra/infra-vmc-resources/tasks/create_instance.yaml

In some situations the IP is not obtained properly and then the NAT creation fails

[VMC SANDBOX] Ensure the IP is gathered

---

ansible/roles/install_operator/tasks/install.yml
ansible/roles/install_operator/tasks/remove.yml
ansible/roles/ocp-workload-aiedge-computing-blueprint/tasks/approve_installplan.yml
ansible/roles/ocp4-workload-dil-serverless/tasks/approves_installplan.yaml
ansible/roles/ocp4-workload-pipelines/tasks/remove_workload.yml
ansible/roles/ocp4-workload-serverless/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_argocd_operator/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_image_puller_operator/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_jenkins_operator/tasks/deploy_jenkins.yml
ansible/roles_ocp_workloads/ocp4_workload_jenkins_operator/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_logging/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_migration_training/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_migration_training/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_ml_workflows_user/tasks/open_data_hub.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_container_storage/tasks/install_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_plus/tasks/workload_argocd.yml
ansible/roles_ocp_workloads/ocp4_workload_rhtr_xraylab/tasks/amq-streams-operator.yaml
ansible/roles_ocp_workloads/ocp4_workload_rhtr_xraylab/tasks/odh-operator.yaml
ansible/roles_ocp_workloads/ocp4_workload_rhtr_xraylab/tasks/storage.yaml
ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/install_amqstreams_operator.yaml
ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/install_crw_operator.yaml
ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/install_ocs_operator.yaml
ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/install_serverless_operator.yaml
ansible/roles_ocp_workloads/ocp4_workload_servicemesh/tasks/install_jaeger_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_servicemesh/tasks/install_kiali_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_servicemesh/tasks/install_servicemesh_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_snyk/tasks/workload.yml

This is a retried task, so the error is non-fatal, but it is still confusing.
Add a default([])
```
FAILED - RETRYING: [bastion.bdhcw.internal]: openshift-pipelines-operator - Wait until InstallPlan is created (9 retries left).
fatal: [bastion.bdhcw.internal]: FAILED! => {"msg": "The conditional check 'r_install_plans.resources | length > 0' failed. The error was: error while evaluating conditional (r_install_plans.resources | length > 0): 'dict object' has no attribute 'resources'. 'dict object' has no attribute 'resources'"}
```
```paste below
```

OCP4 install plans: Fix confusing error message

---

ansible/roles-infra/infra-vmc-resources/tasks/create_instance.yaml

It doesnt require _index the registered variable

[infra-vmc-resources] fix typo

---

ansible/roles/ocp4-workload-pipelines/tasks/workload.yml

Allow more attempts with a delay  of 10 between each retry. Also adding 50 retires from 30

Update workload.yml - improve Install Plan retires

---

ansible/roles_ocp_workloads/ocp4_workload_gitops_bootstrap/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_gitops_bootstrap/templates/application.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/templates/openshift-gitops.yaml.j2

This will allow the usage of environment vars in kustomize manifests, so it is possible for gitops deployments to have access to information such as the cluster subdomain.

Add kustomize-envvar plugin to openshift-gitops

---

ansible/roles/install_operator/tasks/install.yml

TASK [install_operator : openshift-pipelines-operator - Wait until InstallPlan is created]
FAILED - RETRYING: [bastion.qlhsr.internal]: openshift-pipelines-operator - Wait until InstallPlan is created (2 retries left).
FAILED - RETRYING: [bastion.qlhsr.internal]: openshift-pipelines-operator - Wait until InstallPlan is created (1 retries left).
fatal: [bastion.qlhsr.internal]: FAILED! => {"api_found": true, "attempts": 30, "changed": false, "resources":
```paste below
```

adding delay to the task

---

ansible/roles/ocp4-workload-camel3-workshop/tasks/provision_streams.yaml

shell command using tabs instead of spaces causing failure. Now fixed.

---

ansible/cloud_providers/azure_destroy_env.yml

Fix azure destroy to only run subscription based destroy functions when running the subscription based env type.
The destroy functions for subscription based destroy are not compatible with resource group based env types.
./cloud_providers/azure_destroy_env.yml
```paste below
```

Fix azure destroy

---

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/subscription.j2

AAP has been updated to stable-2.4 and the channel needs updating, this change should not affect any other labs, as channel is now made a parameter with default set to stable-2.3
ocp4_workload_ansible_automation_platform
```paste below
```

Parametrize aap subscription channel

---

ansible/roles/showroom/templates/main_compose_template.j2

Fussy jinja macro broke some indenting in a compose file
roles/showroom

Fix macro indentation issue showroom compose template showroom

---

ansible/roles_ocp_workloads/ocp4_workload_acc_new_app_dev/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_aiml_edge_workshop/tasks/setup-gitops.yml
ansible/roles_ocp_workloads/ocp4_workload_ama_demo/tasks/setup-gitops.yml
ansible/roles_ocp_workloads/ocp4_workload_ama_demo_shared/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/tasks/remove_workload_gitea.yml
ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/tasks/workload_gitea.yml
ansible/roles_ocp_workloads/ocp4_workload_amq_streams_dev_exp/templates/gitea-server.j2
ansible/roles_ocp_workloads/ocp4_workload_big_demo/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_blackhat_secured_container_pipelines/tasks/setup_infrastructure_prerequisites.yml
ansible/roles_ocp_workloads/ocp4_workload_coolstore_apac_summit/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_coolstore_backoffice_demo_ohc/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_infrastructure_prerequisites.yml
ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/readme.adoc
ansible/roles_ocp_workloads/ocp4_workload_gitops_amqstreams/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_gitops_hashicorp_vault/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_data_foundation/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_gitops/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_gitops_quay_registry/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_gitops_rhacs_secured_cluster/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_gitops_sonarqube/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_managed_cluster_workload/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_ohc/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_object_detection_ai_ml_setup/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_retail_aiml_workshop/tasks/setup-gitops.yml
ansible/roles_ocp_workloads/ocp4_workload_retail_store_workshop/tasks/setup-gitops.yml

apiVersion of the Gitea CR changed for V2.
Updating all workloads that used the old version to retrieve a running Gitea instance. This should prevent breakage when tagging code with newer tags - or deploying in DEV.
many

Update gitea api versions for workloads retrieving a Gitea instance.

---

ansible/roles/open-env-azure-add-user-to-subscription/defaults/main.yml
ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml

Use custom owner role for subscriptions so that users cannot delete the subscription.
roles/open-env-azure-add-user-to-subscription
```paste below
```

Azure owner change for subs

---

ansible/roles_ocp_workloads/ocp4_workload_gitops_cluster_mgmt_workshop/tasks/post_workload.yml

Add the lab instructions URL to the output from `post_workload`.
`roles_ocp_workloads/ocp4_workload_gitops_cluster_mgmt_workshop` - AKA the "Using GitOps to control and customise" lab.

chore: add instructions to lab output for using gitops lab

---

ansible/configs/hybrid-cloud-binder/requirements.yml

- name: kubernetes.core
version: 2.4.0
Bug fix PR

OHC Binder - set K8s auth to 2.4.0

---

ansible/configs/rosa-manual/software.yml

rosa-manual config was downloading helm as /usr/bin/helm-linux-amd64. Fixing by making a symlink to /usr/bin/helm.
Adding missing bash completion for oc and helm.
Adding fully qualified module names for software.yml
Remove unnecessary 'become: true' lines.
rosa-manual

Fix downloaded helm, add completion, use FQ Modules

---

ansible/roles_ocp_workloads/ocp4_workload_opentour_dach_2022/tasks/argocd_info.yml

Updating k8s_info in argocd_info.yml to fix the OpenShift GitOps server info error.
```paste below
```

Update argocd_info.yml - fix k8s facts to info

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml

adds async to a tasks that takes around 35m, there is another task that checks for completion.
```paste below
```

Adds async to deploy cluster task

---

tools/execution_environments/ee-multicloud-public/Containerfile
tools/execution_environments/ee-multicloud-public/ee-report.sh
tools/execution_environments/ee-multicloud-public/entrypoint.sh

Instead of entrypoint, move the mkdir to containerfile as it shouldn't require to be dynamic
Also add `find /runner -ls` to ee-report

ee: Move mkdir to containerfile

---

tools/execution_environments/ee-multicloud-public/Containerfile

Update the base image of the Execution Environment to latest UBI 8.
This fixes all the security vulnerabilities reported by Quay.

ee: Update UBI base image to latest 8 version

---

ansible/roles/open-env-azure-install-aro/tasks/main.yml

Workshop adoc authors want to detect this to switch on/off AAD instructions.

In ARO role, emit the preconfigure_aad var to user_data for bookbag customization

---

ansible/roles/install_operator/tasks/install.yml

More robust operator installation, fixes #6473 OpenShift operator install only queries first item in list of clusterServiceVersionNames 
Role install_operator
Role still works as expected, no breaking 'api' changes.

Fix Issue redhat-cop/agnosticd#6473

---

ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/tasks/workload.yml

The "Wait until postgres cache db is up" workload task is currently failing as r_service_db_pod.resources is empty. Local testing on an OCP 4.13 cluster does not reproduce this error. This PR adds a debug task to investigate the status of r_service_db_pod variable in the dev deployment.

Change ocp4_workload_fraud_detection_usecase - Debug r_service_db_pod variable state

---

ansible/roles/bookbag/tasks/workload.yaml

This issue is caused by https://github.com/ansible-collections/kubernetes.core/issues/623
Workaround is to not fail on this task when it is reported that projectrequest already exists.
bookbag role

Fix bookbag namespace creation issue

---

ansible/roles_ocp_workloads/ocp4_workload_fraud_detection_usecase/tasks/workload.yml

This PR fixes the issue of the playbook continuing before the postgres pods are ready and leaving the postgres pod data variable undefined. It adds a retry loop to ensure the pod is running before proceeding.

Change ocp4_workload_fraud_detection_usecase - add retry loop when getting postgres db data

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml

Removes the kubeadmin user from OCP. There is no need to use kubeadmin since we already created a admin user which is provided to the student.
A new task is added to remove the kubeadmin secrets once the cluster is deployed.

Removes kubeadmin user since it is not needed

---

ansible/configs/ocp4-on-rosa-with-rhods/default_vars.yml
ansible/configs/ocp4-on-rosa-with-rhods/destroy_env.yml
ansible/configs/ocp4-on-rosa-with-rhods/files/cloud_providers/ec2_cloud_template.j2
ansible/configs/ocp4-on-rosa-with-rhods/pre_software.yml
ansible/configs/rosa-manual/default_vars.yml
ansible/configs/rosa-manual/files/cloud_providers/ec2_cloud_template.j2
ansible/configs/rosa-manual/pre_software.yml

Fix the rosa config to use the correct SSH keys and not the old deprecated variables.
This change fixes the following error that occurs on Controller when using EE:
```
TASK [infra-ec2-wait_for_linux_hosts : wait for linux host to be available (retry)] ***
fatal: [bastion.7zl6w.internal]: FAILED! => {"changed": false, "elapsed": 261, "msg": "timed out waiting for ping module test: Failed to connect to the host via ssh: no such identity: /home/runner/.ssh/opentlc_admin_backdoor.pem: No such file or directory\r\nec2-user@ec2-18-223-8-42.us-east-2.compute.amazonaws.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)."}
```
configs > rosa-manual
configs > ocp4-on-rosa-with-rhods

Remove deprecated SSH variables and role (For EE / Controller)

---

.gitlab-ci.yaml
sonar-project.properties

Adding Requirements for Sonarqube static testing 
AgnosticD Static testing for (required for ESSv9 compliance for demo platform)
Required by RH Infosec for any executable code used in the demo platform.
These have already been verified as working via the babylon repo in redhat-cop and the configuration works correctly.

Adding requirements for ESSv9 for static code testing for executable code

---

tools/execution_environments/ee-multicloud-public/readme.adoc

`ee-multicloud:v0.1.0-alpha` is out, this PR to be merged after the period of test of the pre-release is done.

ee: add v0.1.0 release and update changelog

---

ansible/roles-infra/infra-vmc-resources/tasks/delete_public_ip_and_nat.yaml

After VMC was updated to a new version, they return 404 instead 500

[infra-vmc-resources] Update delete_public_ip_and_nat.yaml

---

ansible/configs/ocp4-cluster/requirements.yml

update openstack cloud requirement
ocp4-cluster
```paste below
```

update openstack cloud requirement

---

.github/workflows/build-ee-pr.yml

When creating a PR to update the EE image, there is a workflow to automatically build a temporary image based on the branch of the PR.
The expiration is currently set to 1 day. That is a bit low. Increase this to 7 days.

ee: increase expiration of image for PR to 7 days

---

ansible/roles-infra/infra-dns/tasks/nested_loop.yml
ansible/roles-infra/infra-osp-project-create/tasks/main.yml

remove unnecessary ansible_facts
infra-dns
infra-osp-project-create
```paste below
```

remove unnecessary ansible_facts

---

ansible/configs/ocp4-cluster/requirements.yml
ansible/roles/ocp4-workload-dil-serverless/tasks/user_terminal.yaml

add  community.okd instead of k8's auth
version: 2.3.0

Update to OCP Auth - dil serverless

---

ansible/roles-infra/infra-osp-resources-destroy/tasks/keypairs.yml

fix typo in rhods destroy
roles-infra/infra-osp-resources-destroy
```paste below
```

fix typo in rhods destroy

---

ansible/configs/ocp4-equinix-aio/requirements.yml

To don't use libvirt collection

[ocp4-equinix-aio] Update version of ocp4_aio_deploy_ocp

---

ansible/roles/showroom/tasks/60-showroom-verify.yml

showroom URL format messed up by unnecessary chomp operator, now removed
roles/showroom

Minor tidy up of showroom url output

---

ansible/configs/osp-migration/pre_infra.yml

try to make osp_migration use vaulted SSH key
osp-migration
```paste below
```

try to make osp_migration use vaulted SSH key

---

ansible/configs/osp-migration/pre_infra.yml

move osp-migration to env on migration server
osp-migration
```paste below
```

move to venv

---

ansible/configs/osp-migration/dns_loop.yml
ansible/roles-infra/infra-osp-create-inventory/tasks/main.yml
ansible/roles-infra/infra-osp-dns/tasks/nested_loop.yml

fix bug in DNS lookup of FQDNs using dig
roles-infra/infra-osp-create-inventory
roles-infra/infra-osp-dns
```paste below
```

fix dns lookups

---

ansible/roles/ocp4-workload-ccnrd-stable/files/devspaces_cr.yaml

Update ocp4-workload-ccnrd-stable for the ImagePuller 3.7 version
```paste below
```

Update ocp4-workload-ccnrd-stable for the ImagePuller 3.7 version

---

ansible/roles-infra/infra-common-ssh-config-generate/tasks/main.yml

toughen up check for environments that might not have a bastion
roles-infra/infra-common-ssh-config-generate
```paste below
```

toughen up check for environments that might not have a bastion

---

ansible/roles-infra/infra-common-ssh-config-generate/tasks/main.yml

fix env with no bastion
roles-infra/infra-common-ssh-config-generate
```paste below
```

fix env with no bastion

---

ansible/roles-infra/infra-common-ssh-config-generate/tasks/main.yml

fix typo in bastion search
roles-infra/infra-common-ssh-config-generate
```paste below
```

fix typo in bastion search

---

ansible/configs/rosa/destroy_env.yml

fix missing ssh key on destroy
rosa
```paste below
```

fix missing ssh key on destroy

---

tools/execution_environments/ee-multicloud-public/requirements.txt

Newer version doesn't allow to filter by metadata keys which doesn't exist (i.e. *guid*)
```paste below
```

[ee-multicloud-public] Fix openstacksdk python library

---

ansible/configs/ocp-workshop/post_software.yml

Updating to ec2_instance_info from ec2_instance_facts to resolve below fatal error. ERROR! couldn't resolve module/action 'ec2_instance_facts'. This often indicates a misspelling, missing collection, or incorrect module path.
```paste below
```

Updating to ec2_instance_info from ec2_instance_facts

---

ansible/roles/set-repositories/tasks/file-repos.yml

Removing warn: false to fix following fatal error. 
TASK [set-repositories : file | clean repositories] ****************************fatal: [master1.9nn4m.internal]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."}
```paste below
```

Removing warn: false to fix ansible.legacy.command error

---

ansible/configs/ocp4-cluster/destroy_env_ec2.yml

check if binary exists in venv before setting python interpreter to use it
ocp4-cluster
```paste below
```

check if binary exists in venv before setting python interpreter to use it

---

ansible/roles/showroom/tasks/50-showroom-service.yml

become machienctl was hacky (needed so showroom could see dbus for podman.socket)
- removed the task giving a root password
- enhanced ansible_user to have membership of `wheel` && a password
Works on ec2  ec2-user. 
May want to revisit
roles/showroom

Fixes to showroom re simplified machinectl become excalation

---

ansible/roles/showroom/defaults/main.yml
ansible/roles/showroom/tasks/50-showroom-service.yml

- Showroom needs `python-devel` so ensure it is installed
- machinectl should have been a FQCN. FIXED
roles/showroom

Minor cleaup of showroon, ensure pip, FQCN fix

---

.github/workflows/build-ee-pr.yml
tools/execution_environments/ee-multicloud-public/release_cycle.adoc
tools/execution_environments/readme.adoc

Pull Requests to update the ee-multicloud execution environment automatically triggers  A GitHub Action that builds a temporary image in the form `pr-1234`.
This change adds the `temporary-` as a prefix to be clear those images are for testing and are moving targets and not use for other purposes. Mostly because:
* they expire after 7 days
* PRs can be updated so does the image tag
before: `pr-1234`, after: `temporary-pr-1234`
see https://github.com/redhat-cop/agnosticd/blob/development/tools/execution_environments/ee-multicloud-public/release_cycle.adoc
* Github action `build-ee-pr.yml`

Explicitly prefix EEs for PRs 'temporary-pr-...'

---

ansible/configs/rosa-consolidated/install_rosa.yml

Bugfix: for default ROSA version had wrong logic to calculate the matching oc cli version.

Fix default oc cli version for rosa

---

ansible/roles/deploy_automationcontroller/tasks/main.yml

Change to correctly use dictionary key access (['content']) instead of attempting to access the content attribute directly

Update ATE main.yml - fix automation controller task

---

ansible/roles/showroom/tasks/20-showroom-user-setup.yml

Eliminate complex and fragile `become_method: machinectl`
roles/showroom
```paste below
```

Simplify showroom podman socket code - drop machinectl

---

ansible/roles/showroom/tasks/20-showroom-user-setup.yml

Recent changes to resolve an ocp4-cluster issue with showroom broke that role
- revert changes to how showroom creates the podman.socket for treafik
roles/showroom

Revert breaking machinectl changes for showroom

---

ansible/roles_ocp_workloads/ocp4_workload_quay_operator/defaults/main.yml

Reverts redhat-cop/agnosticd#7088
Reverting that as we should put default Quay to higher version.

Revert "Update ocp4_workload_quay_operator_channel stable-3.9"

---

ansible/roles/host-ocp4-provisioner/tasks/ec2_prereqs.yml

- The `length` filter applied to a vaulted value produces an error "object of type 'AnsibleVaultEncryptedUnicode' has no len()"
- Use equivalent test for empty string.
Role host-ocp4-provisioner

Work around ansible bug on length of vaulted string

---

ansible/configs/base-infra/lifecycle_hook_post_start.yml
ansible/configs/base-infra/lifecycle_hook_post_stop.yml
ansible/configs/base-infra/start.yml
ansible/configs/base-infra/stop.yml

- Zero CIs failed to start after stop
- added base-infra ec2 start/stop code
- provided hooks for future deeper validation (ie did all my endpoints come up)

Add config based start/stop functionality to base-infra for ec2

---

ansible/configs/base-infra/Makefile
ansible/configs/base-infra/default_vars_ec2.yml

Minor - allow bastion name to be set as a var e.g. for RHEL Zero

Make base-infra bastion name a var for RHEL Zero

---

ansible/configs/roadshow-ocpvirt/vcenter-remove-webapp-vms.yml
tests/static/test-requirements.txt

Power down VMC VMs before deleting.  Sometimes delete fails because the VM is in a running state.
roadshow-ocpvirt
```paste below
```

Power down VMC VMs before deleting

---

ansible/roles/ocp4-workload-dil-streaming/tasks/provision_userprojects.yaml

https://aap2-prod-us-east-2.aap.infra.demo.redhat.com/#/jobs/playbook/15687/output 
Fix for
TASK [ocp-workload-terminal : Create Project terminal] *************************
FAILED - RETRYING: [bastion.f94rs.internal]: Create Project terminal (5 retries left).
FAILED - RETRYING: [bastion.f94rs.internal]: Create Project terminal (4 retries left).
FAILED - RETRYING: [bastion.f94rs.internal]: Create Project terminal (3 retries left).
FAILED - RETRYING: [bastion.f94rs.internal]: Create Project terminal (2 retries left).
FAILED - RETRYING: [bastion.f94rs.internal]: Create Project terminal (1 retries left).
failed: [bastion.f94rs.internal] (item=./templates/project.j2) => {"ansible_loop_var": "item", "attempts": 5, "changed": false, "item": "./templates/project.j2", "msg": "Failed to find exact …

DIL Streaming - add line 17 `when item = 1" bug fix

---

ansible/roles/bastion-student-user/tasks/main.yml
ansible/roles/set_env_authorized_key/tasks/main.yml

Avoiding the usage of `locate_env_authorized_key` role, using `set_env_authorized_key` fails because some variables are not set.
This PR is to use the ssh_provision_* variables

Use ssh_provision_* variables by default

---

ansible/roles-infra/infra-common-ssh-config-generate/defaults/main.yml
ansible/roles-infra/infra-common-ssh-config-generate/tasks/main.yml

For CNV we are using a random port instead 22

[infra-common-ssh-config-generate] Add port to the bastion config + add openshift_cnv default user

---

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/install_odf_operator.yaml

The check for ODF intermittently fails depending on which CVS is first in the list.  Instead change the check to look for something that is consistent across all CVS.

OpenShift Serverless ML Ops - Fix ODF Installation Check

---

ansible/configs/rosa-consolidated/files/cloud_providers/ec2_cloud_template.j2

The fields `owner` and `email` are not set in a Zero environment. Setting defaults.

email is not set in a Zero environment

---

ansible/configs/rosa-consolidated/software.yml

Added rosa_deploy_hcp to the agnosticd_user_data. This way showroom can present different lab instructions based on HCP status.

Add rosa_deploy_hcp to agnosticd vars

---

ansible/cloud_providers/osp_destroy_env.yml

add missing env of osp cloud provider
cloud_providers/osp_destroy_env
```paste below
```

add missing env of osp cloud provider

---

ansible/configs/rosa-consolidated/install_ocp_cli.yml

Needed a failsafe for the case where ROSA is not installed yet the ocp cli version was not set otherwise. Set to latest in that case.

Add failsafe for CLI version

---

ansible/roles/showroom/tasks/20-showroom-user-setup.yml

Simplify a showroom task name, for when var not set
roles/showroom
```paste below
```

Simple fix to podman network task name

---

ansible/configs/rosa-consolidated/default_vars.yml

Even though the default to deploy showroom was false the other default vars were set causing havoc when they weren't overridden by a config.

Fix wrong showroom default vars

---

ansible/roles/bookbag/tasks/workload.yaml

Ansible attempts to patch the ProjectRequest after it is created and gets a 403 error. The namespace was already created by project request so this error can be safely ignored.
bookbag role

Fix bookbag create project bug

---

ansible/configs/ocp4-cluster/lifecycle_hook_post_start.yml
ansible/roles-infra/infra-openshift-cnv-create-inventory/tasks/create_inventory.yaml

If the cluster was stopped after created and started after 24 hours, then the cluster was not starting properly because the CSR was not approved

[ocp4-cluster] [cnv-resources] Improve inventory role and fix starting OCP4 on CNV

---

ansible/roles/ocp4-workload-ccnrd-stable/tasks/install-opentelemetry.yaml

Update ocp4-workload-ccn-stable to add Otel task
```paste below
```

Update ocp4-workload-ccn-stable to add Otel task

---

ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/tasks/workload.yml

Fixes bad paths in argo rollouts workshop
Removes the leading `files/` that was inherited from my standalone playbook since agnosticD resolves to files without it.
ocp4_workloads_rollouts_workshop
Discussed with Josh

Fix bad paths to files in argo rollouts workshop

---

ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/tasks/workload.yml

Added smarter code to wait for GitOps Operator to be up and running instead of dumb sleep for X
ocp4_workload_rollouts_workshop
Discussed with Josh

Use smarter code to wait for GitOps Operator to be ready

---

ansible/configs/ocp4-cluster/files/requirements_k8s_el9.txt

ocp4-cluster has a new requirements file for the k8s virtualenv on RHEL 9.
It was missing `passlib` - which means that the authentication workload failed.
Re-adding library.
ocp4-cluster

Add missing passlib library to requirements

---

ansible/configs/ocp4-cluster/post_software.yml
ansible/configs/open-environment-gcp/post_software.yml
ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml
ansible/roles/open-env-gcp-user-info/tasks/main.yml

add user info to gcp ocp4 when open env is enabled
```paste below
```

add user info to gcp ocp4 for open env

---

ansible/roles-infra/infra-gcp-lifecycle/tasks/initialize.yml

now that all ocp environments are in their own project, remove guid search for instances in gcp lifecycle when running lifecycle tasks
roles-infra/infra-gcp-lifecycle
```paste below
```

remove guid search for instances in gcp lifecycle

---

ansible/configs/rosa-consolidated/default_vars.yml
ansible/configs/rosa-consolidated/post_software.yml

Currently showroom uses the `common_password` variable to designate the password for the showroom user. Until @ankay fixes that and provides a dedicated variable generate a random password for just the showroom user to avoid reusing the rosa user's password.

Generate a random password for showroom user

---

ansible/roles-infra/infra-osp-template-generate/defaults/main.yaml

remove opentlc admin backdoor and use generated infra key
this should fix a lot of ssh problems we are having with OSP based CIs
roles-infra/infra-osp-template-generate
```paste below
```

remove opentlc admin backdoor and use generated infra key

---

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml

Version 4.14 disables ip_forward by default, this adds manifests to enable on workers and control planes
It removes variable ocp4_installer_url what is not in use

[OCP 4.14] Fix ip_forward

---

.github/workflows/build-ee-pr.yml
tools/execution_environments/ee-multicloud-public/readme.adoc

Release new version of ee-multicloud v0.1.1.
This PR should be merged after the testing phase of is done.
* alpha release: `quay.io/agnosticd/ee-multicloud:v0.1.1-alpha`
* 2nd alpha release: `quay.io/agnosticd/ee-multicloud:v0.1.1-alpha.2`
ee-multicloud Execution Environment

ee-multicloud: release v0.1.1 version

---

ansible/configs/rosa-consolidated/default_vars.yml
ansible/configs/rosa-consolidated/destroy_env.yml
ansible/configs/rosa-consolidated/files/requirements_k8s.txt
ansible/configs/rosa-consolidated/install_rosa_hcp.yml
ansible/configs/rosa-consolidated/lock_bastion_security_group.yml
ansible/configs/rosa-consolidated/post_software.yml
ansible/configs/rosa-consolidated/uninstall_rosa.yml

Fix showroom calls and switch to ssh key instead of password.
Add capability to lock down bastion VM with security group
Change destroy to run in EE rather than on (now unreachable) bastion VM.

Updated to change destroy and lock bastion

---

ansible/roles/showroom/defaults/main.yml
ansible/roles/showroom/tasks/20-showroom-user-setup.yml
ansible/roles/showroom/tasks/22-showroom-users-security.yml
ansible/roles/showroom/templates/service_single_terminal/service_single_terminal.j2

Adds cleaner support for sshkeys in showroom
- enables both passwords and sshkeys as tty auth
- cleans up setting passwords (depreciates common_+password etc)
roles/showroom

Fixes, tweaks, enhancements to how showroom handles ssh for lab users

---

ansible/roles/ocp4-workload-camel3-workshop/tasks/pre_workload.yml
ansible/roles/ocp4-workload-ccnrd-cuttingedge/tasks/pre_workload.yml
ansible/roles/ocp4-workload-ccnrd-stable/tasks/pre_workload.yml
ansible/roles/ocp4-workload-chaos-engineering-workshop/tasks/pre_workload.yml
ansible/roles/ocp4-workload-debugging-workshop/tasks/pre_workload.yml
ansible/roles/ocp4-workload-dil-streaming/tasks/pre_workload.yml
ansible/roles/ocp4-workload-jdg-workshop/tasks/pre_workload.yml
ansible/roles/ocp4-workload-quarkus-workshop/tasks/pre_workload.yml
ansible/roles/ocp4-workload-sso-workshop/tasks/pre_workload.yml

Many OCP workloads are checking if the aws_region is defined, this is against of the idea of agnostic (to be able to deploy in multiple clouds) and it looks it was defined in one role and copied to others without the need.
ocp4-workload-camel3-workshop
ocp4-workload-ccnrd-cuttingedge
ocp4-workload-ccnrd-stable
ocp4-workload-chaos-engineering-workshop
ocp4-workload-debezium-demo
ocp4-workload-debugging-workshop
ocp4-workload-dil-streaming
ocp4-workload-jdg-workshop
ocp4-workload-quarkus-workshop
ocp4-workload-sso-workshop
Needed in the migration of CI to OpenShift Virtualization

Remove "Ensuring AWS region is defined" task from OCP workload roles

---

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/workload.yml

Increasing retry more as task already have a valid until and it is failing sometimes: https://tower.dark-tower-prod.infra.open.redhat.com/#/jobs/1613431/
ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/workload.yml

Increasing retry more as task already have a valid until

---

ansible/roles/ocp4-workload-chaos-engineering-workshop/tasks/pre_workload.yml
ansible/roles/ocp4-workload-debezium-demo/tasks/pre_workload.yml
ansible/roles/ocp4-workload-debugging-workshop/tasks/pre_workload.yml
ansible/roles/ocp4-workload-dil-streaming/tasks/pre_workload.yml
ansible/roles/ocp4-workload-workshop-admin-storage/tasks/pre_workload.yml
ansible/roles/ocp4-workload-workshop-dashboard-cluster-admin-student/tasks/pre_workload.yml

Variable bastion_fqdn was set on several OCP workloads and it is not used anywhere. Furthermore, it was using the "subdomain_base" variable which is not always set and the bastion format is not always bastion.domain
roles/ocp4-workload-chaos-engineering-workshop
roles/ocp4-workload-debezium-demo
roles/ocp4-workload-debugging-workshop
roles/ocp4-workload-dil-streaming
roles/ocp4-workload-workshop-admin-storage
roles/ocp4-workload-workshop-dashboard-cluster-admin-student

[OCP workloads] Remove bastion_fqdn variable and fix indents

---

ansible/configs/ansible-windows-workshop/default_vars.yml

TASK [create_ssh_provision_key : Ensure key_name is not defined] ***************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "WARNING: key_name is DEPRECATED and should not be defined when using new create_ssh_provision_key role."}
...ignoring

Remove key_name  - Ansible Windows Workshop

---

ansible/configs/rosa-consolidated/install_rosa_cluster_login.yml

Double wait time for ROSA cluster login to succeed. Adjustment based on failure/success history.
rosa-consolidated config

Increase wait for rosa cluster login

---

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml

Doing a deployment of a old version of OCP, it was detected by default the infrastructure call is using a newer image instead the specific version. This solves that bug
roles/host-ocp4-assisted-installer
https://issues.redhat.com/browse/MGMT-16180

[host-ocp4-assisted-installer] Specify version on the infrastructure too

---

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml

Allow to specify version x.y instead only allow x.y.z
Remove condition _ocp4_installer_use_dev_preview_ because is not used
roles/host-ocp4-assisted-installer

[host-ocp4-assisted-installer] Improve setting variable ocp4_client_url

---

ansible/configs/rosa-consolidated/default_vars.yml
ansible/configs/rosa-consolidated/install_rosa_cli.yml
ansible/configs/rosa-consolidated/install_rosa_common_pre.yml
ansible/configs/rosa-consolidated/install_rosa_hcp.yml
ansible/configs/rosa-consolidated/requirements.yml
ansible/configs/rosa-consolidated/software.yml
ansible/configs/rosa-consolidated/uninstall_rosa.yml

Added capability to install the latest upgradable version for any given major version.
Also added logic to save terraform-vpc directory to output-dir and restore it into the EE - however destroy doesn't work... no biggie right now since sandbox-nuke should take care of terraform resources.

Add latest-upgrade, add terraform cleanup

---

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/install_odf_operator.yaml

The last deployment took ~22 minutes to fully install ODF.

Increase the wait time for ODF to install

---

ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/post_workload.yml

TASK [ocp4-workload-homeroomlab-starter-guides : Running Post Workload Tasks] ***
ERROR! conflicting action statements: agnosticd_user_info, data
The error appears to be in '/runner/project/ansible/roles/ocp4-workload-homeroomlab-starter-guides/tasks/post_workload.yml': line 9, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

[ocp4-workload-homeroomlab-starter-guides] Fix agnosticd_user_info

---

ansible/roles_ocp_workloads/ocp4_workload_rosa_policies/tasks/workload.yml

Add retries to k8s_info task to get cluster authentication in ocp4_workload_rosa_policies
Role ocp4_workload_rosa_policies

Add retries to ocp4_workload_rosa_policies

---

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/files/storage-cluster.yml
ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/tasks/workload.yml

I had the wrong `apiVersion` when creating the `StorageCluster`.

ML Serverless - Change StorageCluster ApiVersion

---

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/kubevirt/legacy-postgresql-application.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/kubevirt/legacy-tomcat-application.yaml.j2

Reorder to create the Postgres and Tomcat VM in sequence in MAD Dev
```paste below
```

Reorder to create the Postgres and Tomcat VM in sequence in MAD Dev

---

ansible/configs/sap-hana/requirements.yml

The storage role used in this config has been changed and it now uses the module ansible.utils.update_fact
```paste below
```

Added ansible.utils for sap-hana config

---

ansible/roles/rhel-graphical/tasks/main.yml

RHEL8 doesnt create a group with the same username name
role [rhel-graphical]

[rhel-graphical] Use group "users" if is RHEL8

---

ansible/configs/rosa-consolidated/default_vars.yml
ansible/configs/rosa-consolidated/install_rosa_common_pre.yml

- `rosa_version` default is specified with "default" rather than empty string to be compatible with parameters.
- Get available versions uses `--hosted-cp` flag when `rosa_deploy_hcp` is set to true.
- `rosa_version: latest` respects the value of `rosa_version_base`
- `rosa_version: latest-upgrade` falls back to latest if no upgrade is available
Config rosa-consolidated

Fix rosa-consolidated version logic

---

ansible/roles-infra/infra-osp-template-generate/defaults/main.yaml

fix concatenation for ssh key path 
roles-infra/infra-osp-template-generate
```paste below
```

fix concatenation for ssh key path 

---

ansible/roles/automation_platform_loader/tasks/ocp_bearer_token.yml

Currently this login is overriding the .kube/config on the ec2-user (or login user)
Role automation_platform_loader

[automation_platform_loader] Run oc command on the EE (or localhost)

---

ansible/configs/ocp4-cluster/destroy_env_gcp.yml
ansible/configs/ocp4-cluster/gcp_fw_destroy.yml

For some reason OCP creates firewall rules in GCP that the OCP installer cannot destroy causing the destroy to fail.  This will fix that problem.
ocp4-cluster
```paste below
```

remove firewall rules before running ocp uninstall

---

ansible/configs/rhel-custom-security-content/requirements.yml
ansible/roles/rhel-graphical/tasks/main.yml

Config rhel-custom-security-content misses kubernetes.core to deploy bookbag in shared cluster
Role rhel-graphical was created for a specific RHEL 9.X version, show the ignore welcome dialog task can be ignored for other versions
config rhel-custom-security-content
role rhel-graphical

[rhel-custom-security-content] Add kubernetes.core [rhel-graphical] Add ignore_errors

---

ansible/roles/ocp4-workload-eap8-workshop/tasks/install-sso.yaml

TASK [ocp4-workload-eap8-workshop : Wait for keycloak CRD to be ready] *********
fatal: [bastion.54fxw.internal]: FAILED! => {"msg": "The conditional check 'r_keycloak_crd.resources | list | length == 1' failed. The error was: error while evaluating conditional (r_keycloak_crd.resources | list | length == 1): 'dict object' has no attribute 'resources'. 'dict object' has no attribute 'resources'"}

Update install-sso.yaml - double delay time

---

ansible/roles/showroom/defaults/main.yml
ansible/roles/showroom/templates/ansible_runner_api_service/ansible_runner_api_service.j2
ansible/roles/showroom/templates/compose_default_template.j2

Showroom role, starting with Zero Touch, will support the use of an extensible API to run playbooks and scripts:
- setup (before modules and/or labs)
- validators/graders
- teardown etc
roles/showroom
```paste below
```

Added prelim support for ansible-runner-api orchestration to showroom

---

tools/execution_environments/ee-multicloud-public/requirements.yml

More and more CI are moving to CNV, so we need kubevirt.core for the stopping the VMs
EE ee-multicloud-public

[ee-multicloud-public] Adding kubevirt.core

---

ansible/roles/showroom/templates/tabs.css

Fix CSS for showroom role to prevent the terminal tab from scrolling.
Role showroom

Fix showroom terminal scroll

---

ansible/roles/showroom/templates/split.css

Remove top margin from showroom content to prevent scrolling.
Role showroom

Remove top margin from showroom to prevent scroll

---

ansible/configs/sandbox/post_software_vmc.yml

Version 4.14 works different compared to older versions connecting to the hosts. So to perform an installation is required to use the internal DNS instead the public one
sandbox (vmc)

[sandbox] Update post_software_vmc.yml

---

ansible/roles/agnosticd_restore_output_dir/tasks/fetch-from-s3-aws_s3.yml
ansible/roles/agnosticd_restore_output_dir/tasks/fetch-from-s3-s3_object.yml

Add retries for fetching output_dir archive from S3. Sometimes, albeit rarely, Amazon S3 cannot be reached and causes a failure that can be addressed with a simple retry.
Role `agnosticd_restore_output_dir`

Add retries for fetching output dir from S3

---

ansible/roles/ocp4-workload-ccnrd-stable/tasks/create_project.yaml

Workload are executed during OCP installation, sometimes the cluster is updating some components such as the apiserver, so it is possible it be unavailable for some seconds
Role ocp4-workload-ccnrd-stable

[ocp4-workload-ccnrd-stable] Add retries to the oc command

---

ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/meta/main.yml
ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/setup_htpasswd_authentication.yml
ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/setup_oauth_certificate.yml
ansible/roles_ocp_workloads/ocp4_workload_deploy_hosted_cluster/tasks/workload.yml

RHACM 2.9 has a lot of changes. Updated workload to deploy a hosted cluster to a shared hosting cluster to support (and require) RHACM 2.9. Cleaned up a few things as well.
This workload is only used in one catalog item (Workshop Hypershift) which will be updated next.

Update Deploy Hosted Cluster for OCP 4 and RHACM 2.9

---

ansible/cloud_providers/azure_infrastructure_deployment.yml
ansible/configs/open-environment-azure-subscription/README.adoc
ansible/configs/open-environment-azure-subscription/default_vars.yml
ansible/configs/open-environment-azure-subscription/post_software.yml
ansible/roles_ocp_workloads/ocp4_workload_showroom/README.adoc
ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml
ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/pre_workload.yml

- make bastion autologin false by default
- add bastion user_data to match ocp4_workload_showroom
- launch showroom on the shared cluster
- move run showroom stanza to localhost
- fix names of showroom_openshift_api_ vars
- start readme
- add more human readable value for rhel_sku, azure_bastion_rhel_sku
- azure subs readme improvments
- First proper showroom readme

Azure support for Showroom OCP, and shared cluster support:wq

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml

Fixes some tasks that were still being delegated to localhost.
```paste below
```

Fixes some tasks not moved to remote for 5gran

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml

Adds the changes required to make aap2 ee be able to reach our controller using a DNS entry in /etc/hosts
```paste below
```

Adds some changes to try get aap2 config working from aap2 ee

---

ansible/roles/host-ocp4-provisioner/tasks/ec2_prereqs.yml

Use the new V2 bundle instead of pip to install AWS
Fix the issue:
```
TASK [host-ocp4-provisioner : Install awscli] **********************************
fatal: [shared-414bastion.shared-414.internal]: FAILED! => {"changed": true, "cmd": ["/tmp/awscli-bundle/install", "-i", "/usr/local/aws", "-b", "/bin/aws"], "delta": "0:00:05.002540", "end": "2023-11-24 12:52:29.732703", "msg": "non-zero return code", "rc": 1, "start": "2023-11-24 12:52:24.730163", "stderr": "Traceback (most recent call last):\n  File \"/tmp/awscli-bundle/install\", line 257, in <module>\n    main()\n  File \"/tmp/awscli-bundle/install\", line 237, in main\n    pip_install_packages(opts.install_dir)\n  File \"/tmp/awscli-bundle/install\", line 147, in pip_install_packages\n    _install_setup_deps(python, '.')\n  File …
```

host-ocp4-provisioner: Install AWS v2

---

ansible/cloud_providers/equinix_metal_infrastructure_deployment.yml
ansible/cloud_providers/openshift_cnv_infrastructure_deployment.yml
ansible/configs/migrating-to-ocpvirt/post_infra.yml
ansible/configs/migrating-to-ocpvirt/pre_software.yml
ansible/configs/roadshow-ocpvirt/post_infra.yml
ansible/configs/roadshow-ocpvirt/pre_software.yml
ansible/configs/roadshow-ocpvirt/templates/httpd/ssl.conf
ansible/roles-infra/infra-dns/tasks/nested_loop.yml
ansible/roles-infra/infra-dns/tasks/pre_checks.yml
ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml

Currently we are using nsupdate/ddns for the labs running on baremetal, this PR configures configures the role infra-dns and the configs: migrating-to-ocpvirt and ocpvirtroadshow
- Enhance Pull Request
- Cloud providers: Equinix and OpenShift CNV
- Role infra-dns
- Config migrating-to-ocpvirt 
- Config roadshow-ocpvirt

Add Route53 support for Equinix/OpenShift Virtualization

---

ansible/roles/showroom/templates/index.html.j2

Last showroom PR broke the css includes in index.html breaking tab rendering
roles/showroom
```paste below
```

Put missing CC back in showroom index.html

---

ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml

Currently is searching for /home/user/credential instead the HOMEUSER/credential, for example for /root/
Role host-lets-encrypt-certs-certbot

[host-lets-encrypt-certs-certbot] Improve path for credentials file

---

ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml

This PR allows to have a created account hosted in a URL (protected with username/password) to use to request domains, that will reduce the errors on OpenShift Virtualization (where the egress IP is always the same for the worker)
You can create a maximum of 10 [Accounts per IP Address](https://letsencrypt.org/docs/too-many-registrations-for-this-ip/) per 3 hours. You can create a maximum of 500 Accounts per IP Range within an IPv6 /48 per 3 hours. Hitting either account rate limit is very rare, and we recommend that large integrators prefer a design [using one account for many customers](https://letsencrypt.org/docs/integration-guide/). Exceeding these limits is reported with the error message too many registrations for this IP or too many registrations for this IP range.
- Feature Pull …

[host-lets-encrypt-certs-certbot] Allow specify account URL for certbot

---

ansible/roles/host-ocp4-assisted-installer/vars/main.yaml

Increasing default values to 16 cores and 64GB RAM for workers

[host-ocp4-assisted-installer] Increase default cores/memory values for workers

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/README.adoc
ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml
ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/application.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/applicationset.yaml.j2

Updated README
Turns out the Argo deployment never used the chart version. Also it deployed from source code.
Changed ArgoCD deployment to also deploy the chart with a specified version.

Updates to only use packaged chart version and to specify proper chart version.

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/README.adoc
ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml
ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/workload.yml

Check if ArgoCD was present only worked for OpenShift GitOps 1.10. Adding check for older versions as well to support older OpenShift versions that can't run 1.10.

Add_check_for_old_argocd

---

ansible/roles-infra/infra-vmc-resources/tasks/create_public_ip_and_nat.yaml

I put incorrectly the parameter, it should be inside the body
infra-vmc-resources Role

[infra-vmc-resources] Move parameter to proper place

---

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/files/knative_serving.yaml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/files/serverless_subscription.yaml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/deploy_projects.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_amqstreams_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_grafana.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_jaeger_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_opentelemetry_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_prometheus.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_serverless.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/verify_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/workload.yml

Some enhancements to the `OCP4_QUARKUS_SUPERHEROES_DEMO` role:
- Installation of the OpenShift Serverless Operator & Knative serving capabilities
- Additional installation of the knative versions of the applications
I tested this by pointing DEV to my local fork (see https://github.com/rhpds/agnosticv/pull/12892) and then ordering the DEV catalog item.
OCP4_QUARKUS_SUPERHEROES_DEMO
```
╰─ ansible --version
ansible [core 2.15.5]
config file = /Users/edeandre/workspaces/ansible/agnosticd/ansible/ansible.cfg
configured module search path = ['/Users/edeandre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /opt/homebrew/Cellar/ansible/8.5.0/libexec/lib/python3.11/site-packages/ansible
ansible collection location = …
```

Change role OCP4_QUARKUS_SUPERHEROES_DEMO add serverless capabilities

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/report-variables.yaml

ocp_workload_showroom role fails on ec2 as some vars were Azure-specific
Changes add support for ec2 and safe defaults for a cloud_provider not using the desired vars
roles/ocp_workload_showroom

Make the var report more robust for cross cloud use

---

ansible/roles_ocp_workloads/ocp4_workload_rosa_policies/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_rosa_policies/tasks/workload.yml

Need to run a few of the rosa policies shell scripts as root. Adding that capability.
BREAKING CHANGE:
The list of policies to apply changed from a simple YAML list to a dictionary...
ocp4_workload_rosa_policies

Add support to deploy a policy shell script as root

---

ansible/configs/rosa-consolidated/default_vars.yml
ansible/configs/rosa-consolidated/pre_software.yml

On a default RHEL installation a prompt is shown upon login to register with insights.
Add two vars:
- bastion_remove_insights_motd: false
- bastion_custom_motd: Welcome to the Red Hat OpenShift Service on AWS Hands On Experience!
to customize the text.

Add vars to remove insights motd - and add custom motd - on bastion

---

ansible/roles/showroom/defaults/main.yml

Change default for `showroom_enable_root_ssh` to false. Having the default as true made specifying users obsolete.
showroom

Change enable root user to false. True caused unintended consequences.

---

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/files/amqstreams_instance.yaml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/deploy_projects.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_kafka.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_serverless.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/remove_workload.yml

Some enhancements and fixes:
- Waiting for the `KnativeServing` installation to finish before proceeding
- In each namespace, wait for the `Kafka` installation to finish, along with some failure handling in the case it doesn't provision correctly
- Nicer formatting in provision email
I tested this by pointing DEV to my local fork (see https://github.com/rhpds/agnosticv/pull/12928) and then ordering the DEV catalog item. I did this quite a few times before creating this PR.
OCP4_QUARKUS_SUPERHEROES_DEMO
```
╰─ ansible --version                                                             
ansible [core 2.16.0]
config file = /Users/edeandre/workspaces/ansible/agnosticd/ansible.cfg
configured module search path = ['/Users/edeandre/.ansible/plugins/modules', …
```

Change role OCP4_QUARKUS_SUPERHEROES_DEMO fix serverless & kafka errors

---

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml

Creating repositories with the Gitea operator timed out when it was more than 40 users. Doubled the timeout (and did a few minor cosmetic changes).

Increase retries for Gitea repository creation

---

ansible/configs/rosa-consolidated/default_vars.yml
ansible/configs/rosa-consolidated/pre_software.yml

This file gets created by RHEL 9.3 apparently and prevents login with a password. Removing if it's there.

Remove 50-cloud-init.conf file

---

ansible/roles_ocp_workloads/ocp4_workload_serverless/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_serverless/files/knative_eventing.yaml
ansible/roles_ocp_workloads/ocp4_workload_serverless/files/knative_serving.yaml
ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_serverless/templates/knative_eventing.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_serverless/templates/knative_serving.yaml.j2

workload was failing to deploy because of API version changes in recent serverless releases.
Added logic to retrieve the apiVersion from the CRDs.
Also modernized the code by FQDN modules etc.

Update Serverless Workload for latest versions

---

ansible/roles/host-ocp4-assisted-installer/vars/main.yaml

As default, the variable ai_cluster_version was set to 4.13. To be more consistent, default now is  ocp4_installer_version 
Role host-ocp4-assisted-installer

[host-ocp4-assisted-installer] Use ocp4_installer_version variable for ai_cluster_version

---

ansible/roles_ocp_workloads/ocp4_workload_serverless_ml_workshop/files/kafka-cluster.yml

Relax ssl to allow zookeeper to be able to connect as per https://github.com/strimzi/strimzi-kafka-operator/issues/3692

OpenShift Serverless ML Ops - Fix Zookeeper Timeout Error

---

ansible/configs/rosa-consolidated/pre_software.yml
ansible/roles/bastion-student-user/tasks/main.yml

When using the bastion-student role, we want to enable password authentication.
Remove the configuration that forbids PasswordAuthentication in Cloud
init ssh file:
```
[root@bastion sshd_config.d]# cat /etc/ssh/sshd_config.d/50-cloud-init.conf
PasswordAuthentication no
```
Patch the rosa config: Don't delete the file but use lineinfile module to remove only that line, as that file may be used for other puprose later.
```paste below
```

Fix SSH config from cloud-init: rm line about PasswordAuthentication

---

ansible/roles/host-ocp4-assisted-installer/tasks/print_cluster_info.yml

To keep compability with the host-ocp4-installer, it is needed to save this password to the user_data
host-ocp4-assisted-installer config

[host-ocp4-assisted-installer] Add kubeadmin password to the user_info

---

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml

The installer and revision-pruner pods are one-shot pods. The Cluster Operator will perform retries when needed. The Completed and Error status pods can be deleted if there is no error reported in the corresponding Cluster Operator.
Check: https://access.redhat.com/solutions/6488041
host-ocp4-assisted-installer config

[host-ocp4-assisted-installer] Delete failed installer pods 

---

ansible/roles_ocp_workloads/ocp4_workload_serverless/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml

Added var to set or not set KNative serving. Similar to what was already setup for KNative Eventing.
```paste below
```

(WIP) Added boolean for KNative Serving, similar to KNative eventing

---

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/workload.yml

Removes the kubeadmin webui user once cluster has been  deployed
```paste below
```

Removes kubeadmin user once cluster has been deployed

---

ansible/configs/roadshow-ocpvirt/default_vars_equinix_metal.yml

To reduce the number of permissions, group permissions are set in the vsphere cluster
Feature
roadshow-ocpvirt config

[Roadshow] Remove Datacenter and ClusterComputeResource permissions

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/report-variables.yaml

Fix ocp4_workload_showroom to set `user` and `lab_ui_url`
Role ocp4_workload_showroom

Fix agnosticd_user_info data for multiuser case in ocp4_workload_showroom

---

ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2

usertags doesnt work well in gcp
```paste below
```

usertags doesnt work well in gcp

---

tools/execution_environments/ee-ansible-workshop/requirements.yml

Adding version for ansible.workshop collection-
Reason: By default ansible.workshop collection picks old version (1.0.11) and CI needs latest version (1.0.18).
Execution Environment- ee-ansible-workshop

ee-ansible-workshop

---

ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/files/gitops-operator/subscription.yaml

Update the GitOps Operator to 1.11
OpenShift Rollouts Workshop
The update to 1.11 is necessary to get Rollouts 1.6 which enables the usage of the Prometheus metric instead of the hacky way we were doing it with the Web metric previously.

Update GitOps subscription to 1.11 for Rollouts Workshop

---

ansible/roles/showroom/defaults/main.yml
ansible/roles/showroom/templates/ansible_runner_api_service/ansible_runner_api_service.j2

Updated the `ansible-runtime-api` to use new image and fixed paths for mounted volumes

Change showroom role for new version of ansible-runtime-api

---

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml

Some deployments are failing with the following error: botocore.exceptions.ClientError: An error occurred (Throttling) when calling the ListResourceRecordSets operation (reached max retries: 4): Rate exceeded
This PR is to add a somes retries with 30 seconds delay

[host-ocp4-assisted-installer] Adding a retry for Route53 calls

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml
ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/deploy-showroom-helm.yaml
ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/application.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/applicationset.yaml.j2

Some lab environments need more CPU or Memory than the default in the Showroom Helm Chart. This PR adds the capability to specify resources for the terminal container.

Add vars to showroom workload to set resources for terminal containers

---

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml

New API doesnt include api_vip and ingress_vip

[host-ocp4-assisted-installer] remove api_vip and ingress_vip

---

ansible/roles/showroom/defaults/main.yml
ansible/roles/showroom/templates/ansible_runner_api_service/ansible_runner_api_service.j2

This change adds traefic configuration for `ansible-runner-api`. Default path will be `https://<showroom URL>/runner/docs` but can be configured with the `showroom_ansible_runner_path` variable.
Showroom/ansible_runner_api_service

Adding traefik configuration to ansible-runtime-api

---

ansible/roles-infra/infra-vmc-sandbox/tasks/create_access.yml

infra-vmc-sandbox role
```paste below
Instead of assigning permissions by host do it for a group
```

[infra-vmc-sandbox] Remove assign individual permissions to hosts

---

ansible/roles/showroom/templates/ansible_runner_api_service/ansible_runner_api_service.j2

There is a bug introduced by the https://github.com/redhat-cop/agnosticd/pull/7585 which prevents `Traefik` to route traffic correctly to the `ansible-runner-api`. This PR should fix it. 
Showroom/ansible-runner-api

Fixing traefik configuration for ansible-runner-api

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml
ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/deploy-showroom-helm.yaml
ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/application.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_showroom/templates/applicationset.yaml.j2

Helm chart has the capability to specify which Antora playbook to use from a content repo. Adding the variable ocp4_workload_showroom_content_antora_playbook to allow different playbooks for different showroom instances.

Add antora_playbook variable to ocp4_workload_showroom

---

tools/get-output-dir.py

first version: script to download tarball of output dir using the s3 bucket.

get-output-dir.py  script to get outputdir tarball

---

ansible/configs/open-environment-azure-subscription/post_software.yml

Azure bastions require a "generated_password".
But when there's no bastion in the env_type, then there's no generated password, and a failure.

remove emitting generated_password when there's no azure bastion

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/deploy-showroom-helm.yaml

This has been failing for me on the controllers.
We can now deploy showroom to the shared cluster without a bastion.

in helm_template kubeconfig use environment not parameter

---

ansible/configs/migrating-to-ocpvirt/post_software.yml

-->
Add more vars into user.info.data for use with info-message and service-ready-message templates in AgV
migrating-to-ocpvirt/post_software.yaml
Adding to allow config to be compatible with community content CI, that needs extra vars exposed within the user.info.data
```

migrating-to-ocpvirt/post_software.yaml add user.info.data vars

---

ansible/roles_ocp_workloads/ocp4_workload_external_odf/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_external_odf/templates/pvc-imageregistry.yaml

Registry on OCP on oVirt had a hardcoded pvc size of 20Gi. Made a variable and bumped default to 100Gi.
ocp4_workload_external_odf

Added var to customize registry storage on oVirt

---

ansible/roles-infra/infra-dns/tasks/nested_loop.yml

Migrating most of the labs to use Route53 instead to use nsupdate, is causing to reach some limits
This PR adds a retry
infra-dns Role

[infra-dns] Add retries to route53 call

---

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhdh-setup-variables.yml

There is a network latency that makes the cluster failed after not finding the secret. Adding a retry and delayed to resolve the issue. I can see the secret created in the cluster 20 seconds after the request is done.
Adding a retry for requesting the argocd secret associated to the ARGOCD instance for RHDH.
Module 7.
There is a network latency that makes the cluster failed after not finding the secret. Adding a retry and delayed to resolve the issue. I can see the secret created in the cluster 20 seconds after the request is done.
TASK [ocp4_workload_mad_roadshow : Retrieve ArgoCD credentials] ****************
FAILED - RETRYING: [bastion.m2f29.internal]: Retrieve ArgoCD credentials (3 retries left).
FAILED - RETRYING: …

adding retries for argocd secret associated with argocd instance for RHDH

---

ansible/roles/showroom/templates/ansible_runner_api_service/ansible_runner_api_service.j2

Fixing certificate configuration to support SSL (HTTPS) Traefik proxy forwarding to the `ansible-runner-api` service
Showroom

Fixing certificate configuration for Traefik proxy

---

ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/workload.yml

This change, in combination with [this](https://github.com/blues-man/vote-app-gitops/commit/3ad185c7f7ee55ee22936a359fd2a02f227f2109), will fix a bug we have where all devworkspaces are not up and running and admins need to be restart the cluster (or just sync devspaces argo apps).
This code will check if DevWorkspace Operator is successfully installed and if CRDs are available  
Add DevWorkspace installation checks
role ocp4_workload_voteapp

Add checks for DevWorkspace subs and crds 

---

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/workload.yml

IPA readiness check was finishing but IPA is still preparing. There is workshop in 2 hours we need to support.
ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/workload.yml

Update workload.yml to double the time to check IPA ready

---

ansible/roles_ocp_workloads/ocp4_workload_cockroach_dbaas_amq_lab/tasks/pre_workload.yml

On OpenShift Virtualization connection is using cloud-user, so fix permission for lab-user it is not possible
ocp4_workload_cockroach_dbaas_amq_lab role

[ocp4_workload_cockroach_dbaas_amq_lab] Using become to set permissions for lab-user

---

ansible/roles_ocp_workloads/ocp4_workload_cockroach_dbaas_amq_lab/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_cockroach_dbaas_amq_lab/tasks/remove_workload.yml

To be able to delete the cluster, we need to cluster ID. This PR stores the cluster_id inside the output_dir, which is restored for the destroy process
role ocp4_workload_cockroach_dbaas_amq_lab

[ocp4_workload_cockroach_dbaas_amq_lab] Using output_dir to store cluster ID 

---

ansible/configs/zero-touch-base-rhel/default_vars_ec2.yml
ansible/configs/zero-touch-base-rhel/lock_bastion_security_group.yml

Adds a task to the network hardening playbook that disables DNS on the VPC
zero-touch-rhel-base
```paste below
```

Zero touch RHEL add DNS enable/disable task

---

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/workload.yml

Reverts redhat-cop/agnosticd#7631
As actual code updated on helm-charts: https://github.com/redhat-cop/helm-charts/pull/463, we don't need this one.

Revert "Update workload.yml to upgrade IPA server"

---

ansible/configs/rosa-consolidated/default_vars.yml
ansible/configs/rosa-consolidated/post_software.yml
ansible/configs/rosa-consolidated/software.yml
ansible/roles_ocp_workloads/ocp4_workload_serverless/tasks/workload.yml

Add option to delete the temporary admin user from the ROSA cluster. This is useful if other authentication has been configured in a workload.
Add check to not download kn tool when KN Serving has not been configured for serverless.

Add support to delete temporary admin user. Add check to not download kn when serving is not installed

---

ansible/roles-infra/infra-ec2-template-generate/templates/cloud_template.j2

- Default owner tag to requester_email or requester_username
- Default owner to "unknownuser" if value is empty string
Role infra-ec2-template-generate

Fix error with empty owner tag for ec2

---

ansible/roles/ansible_bu_setup_workshop/tasks/ripu.yml

Updates Config as Code job templates that are executed towards the end of the workshop deploy automation for Ansible RIPU workshop.
ansible/roles/ansible_bu_setup_workshop role
The initial Config as Code job template "Z / CaC / Controller" is configured in AgnosticV [here](https://github.com/rhpds/agnosticv/blob/cb64480cd8c2c2a9f9eb0e363a12eba96547e578/sandboxes-gpte/ANS_BU_WKSP_RIPU/common.yaml#L443-L452).

Mods to reflect updated Config as Code workshop deploy strategy for Ansible RIPU workshop.

---

ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_rosa/vars/main.yaml

The logic to determine Console and API URL in the workload was not correct - and partially hardcoded.
Fixing to use the rosa cluster properties instead.
Also remove base domain variable that is never used.
ocp4_workload_authentication_rosa

Fix logic to get correct API and Console URLs

---

ansible/roles/bastion/tasks/prepuser.yml

hostvars.localhost.ssh_provision_key_path it is the recommended variable, if doesnt exist it will use hostvars.localhost.env_authorized_key_path
prepuser role

[prepuser] Use new hostvars.localhost.ssh_provision_key_path

---

ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_services.yaml

- With this PR the networkdata for the VMs will be working as expected, as before it was complex to define properly the definition
- VMs with not network definition will be mapped automatically to default network
- dataVolumeTemplates will work for VMs with count different to 1
- connection between VMs will not be limited now to port 22 using service
infra-openshift-cnv-resources Role

[infra-openshift-cnv-resources]  enhance CNV cloud provider

---

ansible/configs/archive/ocs4-external-implementation/default_vars.yml
ansible/configs/ocp4-cluster/default_vars.yml
ansible/configs/ocp4-workshop/files/install-config.yaml.j2
ansible/configs/sap-integration/default_vars.yml
ansible/roles/host-ocp4-installer/create-manifests.yml
ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2

As of OpenShift 4.15 OpenShiftSDN is no longer a supported networking type and installations fail. Instead of mandating all configs to set the networking to OVNKubernetes change the defaults where applicable.
ocp4-cluster
ocp4-workshop
ocs-external-implementation (archived)

Switch default OCP Networking Type to OVNKubernetes

---

ansible/roles-infra/infra-openshift-cnv-create-inventory/tasks/create_inventory.yaml
ansible/roles-infra/infra-openshift-cnv-create-inventory/tasks/main.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/main.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/start_instances.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/stop_instances.yaml
ansible/roles/host-ocp4-assisted-destroy/tasks/main.yaml
ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml
ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_workers.yaml
ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml

Currently we are using openshift_cnv_username and openshift_cnv_password for authentication to obtain the token (key)
This PR allows to have a variable openshift_cnv_sa_token with the authentication token instead
infra-openshift-cnv-create-inventory and infra-openshift-cnv-resources roles

[CNV] Allow authentication with token (from SA)

---

ansible/roles_ocp_workloads/ocp4_workload_quay_operator/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_quay_operator/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/config_bundle_secret.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/quay-admin-token-secret.yml.j2
ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/quay_namespace.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_quay_operator/templates/quay_registry.yaml.j2

Recent releases of Quay (e.g. 3.10) don't have a config editor anymore - which made this workload fail.
Adding condition to only get config editor credentials if it was created.
Fix Ansible lint errors/warnings
Streamline code.

Add support for newer Quay releases. Streamlining. Fix Ansible lint warnings.

---

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_external_secrets.yml
ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_janus_argocd.yml
ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_quay.yml
ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_vault.yml
ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/workload.yml

When deploying Quay 3.10 the database config fails. This PR adds logic to fix that while remaining compatible with the old Quay 3.6.
Also fixing a bunch of Ansible Lint warnings.
ocp4_workload_redhat_developer_hub_bootstrap

Add extra checks to Quay install. Fix a bunch of Ansible-lint warnings.

---

ansible/roles_ocp_workloads/ocp4_workload_voteapp/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_voteapp/tasks/workload.yml

voteapp workload had hardcoded subscription names. This fails when using default catalog sources.
Adding vars to make the setting customizable.
ocp4_workload_voteapp

Make subscription names customizable

---

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_quay.yml

Annoyingly on controler deploy still failed with a pod not found - even on the shell task. Adding a few retries to get the correct pod name.
ocp4_workload_redhat_developer_hub_bootstrap

Add a few retries to extend the Quay token

---

ansible/roles/showroom/templates/ssh_config.j2

This update is to remove starting line warning errors for the zero touch rhel showroom terminal.
ansible/roles/showroom/
```paste below
```

Update Showroom role ssh_config.j2 template for loglevel error

---

ansible/configs/base-infra/default_vars.yml
ansible/configs/base-infra/post_software.yml

Adds bool role to post_software to reset the rhsm.conf file after deployment. This is needed for a Red Hat Insights summit lab.
```paste below
```

Config base-infra Add role to reset system repositories after deployment

---

ansible/configs/rosa-consolidated/install_rosa_common_pre.yml

when requesting the default version of the hosted control plane ROSA, the jmespath query did not match the output of `rosa list versions --output json --hosted-cp`
This new code accounts for HCP and non-HCP ROSA versions in the output of `rosa list versions` with or without `--hosted-cp`

account for hosted_control_plane_default

---

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml

Add logic to install the argocd CLI on the bastion if the OpenShift Gitops operator is being installed. Works all the way back to ArgoCD 2.6.

Add argocd CLI download

---

ansible/configs/just-a-bunch-of-nodes/software.yml
ansible/configs/just-a-bunch-of-nodes/templates/novnc.service

- Extend software.yml in just-a-bunch-of-nodes to support `software_workloads_for_bastion`
- Add noVNC service template to ansible config
- 
Allows roles to be listed and configured in AgV
configs/just-a-bunch-of-nodes

Extend just a bunch config and add noVNC service template

---

tools/execution_environments/ee-multicloud-public/release_cycle.adoc

For clarity rename Alpha releases to Candidate Releases. It's also shorter.

EE doc: rename `alpha` to `rc` (Release Candidate)

---

ansible/configs/base-infra/pre_software.yml

Updates host identifier for pre_software to be windows enabled.
base-infra
```paste below
```

base-infra config, update pre_software to be windows enabled

---

ansible/configs/ansible-automation-platform/env_vars.yml
ansible/configs/ansible-automation-platform/post_software.yml
ansible/roles/vscode-server/README.adoc
ansible/roles/vscode-server/defaults/main.yml
ansible/roles/vscode-server/tasks/nginx-server.yml
ansible/roles/vscode-server/templates/nginx.conf.j2

Make the vscode-server able to have a different HTTPS port Open the ports 8443 (and 3443 as preparation for Gitea)
LB1750

Move VScode server to port 8443

---

ansible/configs/ansible-lightspeed/default_vars_openshift_cnv.yml
ansible/configs/base-infra/default_vars_openshift_cnv.yaml
ansible/configs/ocp4-cluster/default_vars_openshift_cnv.yml
ansible/configs/zero-touch-base-rhel/default_vars_openshift_cnv.yaml
ansible/roles-infra/infra-openshift-cnv-create-inventory/defaults/main.yaml
ansible/roles-infra/infra-openshift-cnv-create-inventory/tasks/create_inventory.yaml
ansible/roles-infra/infra-openshift-cnv-resources/defaults/main.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/check_network.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_network.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_project.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_routes.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_service.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_services.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/delete_networks.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/delete_project.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/main.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/start_instances.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/status_instances.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/stop_instances.yaml
ansible/roles-infra/infra-vmc-resources/tasks/status_instances.yaml
ansible/roles-infra/infra_vmware_ibm_resources/tasks/status_instances.yaml
ansible/roles/host-ocp4-assisted-destroy/vars/main.yaml
ansible/roles/host-ocp4-assisted-installer/vars/main.yaml

This is another PR for the preparation of using sandbox for OpenShift Virtualization
If the variable **sandbox_openshift_namespace** is defined, then is used as namespace for openshift_cnv
As well, if the variable **sandbox_openshift_namespace** is defined, the project and the rolebinding are not created or deleted, as sandbox will be the responsible for it.
This PR removes as well the variable openshift_cnv_project_name from default_vars.yaml
openshit_cnv cloud provider

Rename openshift_cnv_project_name to openshift_cnv_namespace and use as default sandbox_openshift_namespace

---

ansible/configs/rhel-security/crypto.yml

Deployments failing due to the crypto system not having httpd available.
rhel-security
```paste below
```

rhel-security config bug-fix update to install httpd

---

tools/execution_environments/ee-multicloud-public/requirements.txt

This python library is required for the community. general.random_pet lookup plugin for unique hostnames.
We have a request to use pet names for a Red Hat Insights lab for Summit. The lab owner will be using an internal account to showcase insights which if each system was named [node1.example.com](http://node1.example.com/) will cause the user to experience grief attempting to identify which system of the ~30 is their actual system in the insights console.
tools/execution_environments/ee-multicloud-public/requirements.txt
```paste below
```

Update Public EE for python petname library

---

ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml

Increasing the retries to 120 to fix the following fatal error.
TASK [host-ocp4-assisted-installer : Wait till VM is running] ******************
FAILED - RETRYING: [bastion]: Wait till VM is running (60 retries left).

host-ocp4-assisted-installer : Wait till VM is running retries

---

ansible/roles/windows-ami-finder/defaults/main.yml

Changing variable names after re-naming role
windows-ami-finder
```paste below
```

windows-ami-finder defaults/main.yml update

---

ansible/configs/ansible-automation-platform/destroy_env.yml
ansible/configs/ansible-automation-platform/post_software.yml

Use showroom on OCP Shared v locally on VM
Simplifies and avoids LE Cert clash with Nginx, VSCode wanting the same port, and a host of other stuff.
configs/ansible-automation-platform
Local showroom had never deployed successfully here and needed excessive work due to a non standard AgD config

Move showroom to OCP shared, including destroy for cleanup

---

ansible/configs/rhel-security/crypto.yml

This setup script is broken for RHEL 9. Adding conditional until fixed so summit developers can test.
rhel-security
```paste below
```

rhel-security add conditional to stop setup script

---

ansible/configs/rhel-security/post_software.yml

Added this boolean to control if we validate the setup. This is so the lab owners can fully deploy the CI and test through ordering a completed item.
rhel-security
```paste below
```

rhel-security Add bool to govern validation

---

ansible/configs/ansible-lightspeed/destroy_env.yml
ansible/configs/ansible-lightspeed/post_software.yml

Added the when: protected option to use Shared Showroom OCP in config ansible-lightspeed
- Allows it to be used with Showroom while simplifying port issues around CNV
configs/ansible-lightspeed

Add showroom destroy and deploy tasks to ansible

---

ansible/roles/pet_name_generator/README.md
ansible/roles/pet_name_generator/defaults/main.yml
ansible/roles/pet_name_generator/tasks/main.yml

This role creates unique hostnames for systems. It uses set_fact to create or override hostname variables and assigns them to a new value using the Python petname generator.
This is useful for deployments of systems mimicking a real-world environment or for Red Hat Insights labs making the systems easier to locate in the web console.
pet_name_generator
```paste below
```

New Role pet_name_generator

---

ansible/configs/base-infra/pre_infra.yml

Add pet_name_generator to base-infra with conditional
base-infra
```paste below
```

base-infra integrate system pet name trigger

---

ansible/configs/aap2-ansible-workshops/post_software.yml
ansible/configs/rhel-security/post_software.yml

Adding in showroom roles for summit
rhel-security aap2-ansible-workshops
```paste below
```

Add Showroom roles to aap2-ansible-workshops and rhel-security

---

ansible/configs/ansible-lightspeed/software.yml

Config fails if `git push --set-upstream origin ansible-lightspeed-fix-conditional-01` not set
Defaults it to false to allow block not to be executed
- Bug Fix
configs/ansible-lightspeed

Fix lightspeed conditional so it defaults to false

---

ansible/roles/reset-repositories/tasks/main.yml

The rhsm.conf file was not being regenerated. Changing this to restore the original from the backup created.
reset-repositories
```paste below
```

Update reset-repositories role to properly reset rhsm.conf

---

ansible/roles-infra/infra-equinix-metal-resources/tasks/create_instances.yaml

"msg": "failed to set device state present, error: Error 422: The 'facility' parameter is not supported for organization 367d5f94-cc39-4623-966a-fce18b63e2b2. For more details, see https://feedback.equinixmetal.com/changelog/bye-facilities-hello-again-metros",
```paste below
```

disabling facility parameter

---

ansible/configs/ansible-automation-platform/post_software.yml

As the title says, simply removing outdated links and variables replaced by Showroom.
LB1750

Remove outdated lab URL replaced by Showroom

---

ansible/configs/aap2-ansible-workshops/pre_infra.yml

Adds pet_name_generator role to pre_infra.yml with default false bool
```paste below
```

aap2-ansible-workshops include pet-name option

---

ansible/configs/ansible-bu-workshop/pre_infra.yml

Add pet_name_generator role for summit with bool.
```paste below
```

ansible-bu-workshop add pet_name_generator_role

---

ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml

cannot delete tags now, need to reinit instead
```paste below
```

cannot delete tags now, need to reinit instead

---

ansible/roles/ansible_bu_setup_workshop/tasks/ripu.yml

The template within this role needs access to the localhost registered variable "r_instances_info"
ansible_bu_setup_workshop
```paste below
```

ansible_bu_setup_workshop include registered var into another task list

---

ansible/configs/ocp4-cluster/destroy_env.yml
ansible/configs/ocp4-cluster/post_software.yml

Adds the capability to `ocp4-cluster` to deploy shared showroom at end of post_software
i.e. use only has to supply vars and it will deploy **after** all user-data is set

Add Showroom setup to post_software.yml in ocp4-cluster

---

ansible/configs/ansible-bu-workshop/destroy_env.yml
ansible/configs/ansible-bu-workshop/post_software.yml

The showroom needs to run on the ocp cluster instead of bastion. The bastion system is also an AAP2 Controller and takes 443.
ansible-bu-workshops
```paste below
```

ansible-bu-workshops move showroom to OCP cluster

---

ansible/roles_ocp_workloads/ocp4_workload_rhacs/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_rhacs/templates/central.yaml.j2

RHACS Certral custom resource task converted to template
Reason: In RHACS 4.4 there is new feature  scannerV4 is available and it is disabled by default. So to enable it we have to add option with condition which doesn't effect existing or old CIs.
Role: ocp4_workload_rhacs

[WIP] object convert to template

---

ansible/roles/install_operator/tasks/install.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/meta/main.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/readme.adoc
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/cert_manager_ec2.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/api-server.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/certificate-api.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/certificate-ingress.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/certmanager.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/clusterissuer.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/default-ingress-controller.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/secret-aws-credentials.yaml.j2

Add a workload to use the Red Hat cert manager operator to request and install Let's Encrypt certificates for OCP 4 clusters.
Initial support for AWS EC2.

Add workload to install and use cert manager operator

---

ansible/roles/ansible_bu_setup_workshop/templates/student-99-webui.json.j2

The old template was not populating the servers based on the jquery. I removed that and simplified the template.
ansible_bu_setup_workshop
```paste below
```

ansible_bu_setup_workshop template update

---

ansible/configs/rhel-security/gpg.yml
ansible/roles/rhel-security-verification/tasks/gpg-verify.yml

in RHEL-security workshop we migrated RHEL-8 systems to RHEL-9, gpg lab is not working because of this change and missing pinentry-tty package. 
Fixes the RHEL-security workshop and it's simple fix just to add more packages and verify it's present on the lab. 
```paste below
```

[RHEL-security] Add dependency packages for gpg lab

---

ansible/roles/rhel-security-verification/tasks/audit-verify.yml

Easy fix to ensure the verification test for audit lab the directory exists, however in RHEL-9 we changed the path for directory in audit package. 
```paste below
```

[RHEL-security] Fix new path for audit sample rules

---

ansible/configs/base-infra/post_software.yml

Adding trigger for ansible_idm_setup_lab role in base-infra config
base-infra
```paste below
```

base-infra add post_software workload

---

ansible/configs/ansible-automation-platform/env_vars.yml
ansible/configs/ansible-automation-platform/post_software.yml
ansible/roles/aap_controller_cert_issue/tasks/main.yml
ansible/roles/aap_controller_manifest_load/tasks/manifest.yml
ansible/roles/aap_devel_tools/templates/ansible-navigator.yml.j2

- Fix wrong port of gitea_web_ui_url
- Remove superfluous indentation from ansible-navigator.yml
- Add https://gitlab.com/ansible-labs-crew/playbooks-dev.git and https://gitlab.com/ansible-labs-crew/playbooks-ops.git to Gitea
- Remove warnings about use of awx.awx.tower_license/settings
- 
LB1750

Miscellaneous fixes of ansible-automation-platform

---

ansible/roles/ansible_idm_setup_lab/tasks/ansible-setup.yml

Role needed to update injected file permissions for lab-user.
ansible_idm_setup_lab
```paste below
```

ansible_idm_setup_lab fix file permissions at end

---

ansible/roles/ansible_idm_setup_lab/tasks/ansible-setup.yml

Fix installation location of custom roles
ansible_idm_setup_lab
```paste below
```

ansible_idm_setup_lab fix role installation paths

---

ansible/roles/pet_name_generator/tasks/main.yml

Exposing extended loop info (see Ansible docs [here](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html#extended-loop-variables)) will enable users of the role to make sequentially numbered names and do other clever things. For example, if you wanted two pet hosts using "7" separator and two with "8" separator, that's now possible like this: 
```yaml
pet_name_generator_separator: "{{ '7788'[ansible_loop.index0] }}"
pet_name_generator_lookup: "{{ lookup('community.general.random_pet', separator=pet_name_generator_separator) }}"
pet_name_generator_enable: true
pet_name_generator_instances:
- node1_instance_name
- node2_instance_name
- node3_instance_name
- node4_instance_name
```
role: pet_name_generator
@wilson-walrus, as discussed.

expose extended loop info

---

ansible/roles/ansible_idm_setup_lab/defaults/main.yml
ansible/roles/ansible_idm_setup_lab/tasks/ansible-setup.yml

Removing cruft from custom role installation. Can install roles from remote source with ansible_galaxy_install module.
```paste below
```

ansible_idm_setup_lab update to remove un-needed tasks

---

ansible/configs/migrating-to-ocpvirt/requirements.yml

Didn't have a version for  
- name: ocp4_aio_deploy_bastion
src: https://github.com/rhpds/ocp4_aio_infra_role_deploy_bastion.git
scm: git
so I set it to development

migrating2ocpvirt - set version: on requirements.yml where missing

---

ansible/configs/experience-ocpvirt/pre_software.yml
ansible/configs/experience-ocpvirt/requirements.yml

certbot is in epel - therefore change order of tasks to install epel first.
Cleanup requirements (latest collections, unified structure)

Fix order of installs to make sure epel is there before certbot. Update and cleanup requirements.

---

ansible/roles/set-repositories/tasks/satellite-repos.yml

equinix_metal systems were failing registrations due to hardware UUIDs being reported multiple times to the satellite.
This change will generate a random UUID to use in place of the default grabbed from /var/lib/rhsm/facts/
```paste below
```

set-repositories generate unique dmi.system.uuid rhsm facts for bare metal

---

ansible/roles/ansible_bu_setup_workshop/tasks/auto_satellite.yml

Add post workshop deploy automation job template and workflow template execution tasks.
`ansible/roles/ansible_bu_setup_workshop/tasks/auto_satellite.yml`
Same method as how [post workshop configuration is performed via ansible/workshops automation code](https://github.com/ansible/workshops/blob/5ffa2037ee0d2898b29c9797e99bbde3e096eeba/provisioner/workshop_specific/auto_satellite.yml#L348-L403) as well as in `ansible/roles/ansible_bu_setup_workshop/tasks/ripu.yml`

Add post workshop deploy automation from workshop controller.

---

ansible/roles/rhel-security-verification/tasks/openscap-verify.yml

Since switch from `ansible` to `ansible-core` we need additional modules for our playbooks to execute properly.

Add `rhc-worker-playbook` to enable Ansible

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml

- Added basic changes to deploy OCP 4.15 and the latest version of operators
- Added firewall configuration since now we are moving from RHEL8 to RHEL9 base hypervisor
- Added SR-IOV support for virtual machines via QEMU-KVM
- Role: ocp4_workload_5gran_deployments_lab
The change is basically to update the 5G RAN Lab to run on the latest 4.15 bits and the latest telco configurations and operators. 
cc/ @mvazquezc

Update 5G RAN Lab to OCP 4.15

---

ansible/configs/experience-ocpvirt/files/configure_operators.sh

Set maximum parallel migrations to 1 for MTV to reduce load.

Set max migrations to 1

---

ansible/roles/reset-repositories/tasks/main.yml

Enable rhsm to manage repos after resetting satellite configuration. 
This change is for Summit lab LB1222. This is an insights lab that needs to be reset to system defaults after our satellite configuration.
reset-repositories
```paste below
```

reset-repositories Enable RHSM repos after reset

---

ansible/configs/rosa-consolidated/post_software.yml

Remove check if Rosa has been deployed before running workloads - this enables the showroom workload on a shared cluster.

Remove gate for workloads to enable showroom workload on shared clusters

---

ansible/configs/ansible-lightspeed/software.yml

Add, boolean protected, asset-injector to the ansible-lightspeed config for additional customization
configs/ansible-lightspeed

Add asset injection to ansible-lightspeed config

---

ansible/roles/asset_injector/README.adoc
ansible/roles/asset_injector/tasks/main.yml

Enable "{{ _asset.disable_gpg_check | default(false) }}" in asset-injector
Add support to easily allow over-rise for example when pulling from an S3 bucket

Asset injector dnf 02

---

ansible/roles/asset_injector/tasks/main.yml

Fix simple type on asset_injector, used `user` instead of `name`

Update user attribute in asset_injector task

---

ansible/configs/roadshow-ocpvirt/templates/configureMTV.sh.j2

Error from server (NotFound): error when creating "STDIN": namespaces "openshift-mtv" not found error: resource mapping not found for name: "vmware" namespace: "openshift-mtv" from "STDIN": no matches for kind "Provider" in version "forklift.konveyor.io/v1beta1" ensure CRDs are installed first
```paste below
```

adding openshift-mtv namespace in configureMTV.sh.j2

---

ansible/configs/ocp-workloads/post_software.yml
ansible/roles/host-ocp4-set-facts/.yamllint
ansible/roles/host-ocp4-set-facts/README.adoc
ansible/roles/host-ocp4-set-facts/defaults/main.yml
ansible/roles/host-ocp4-set-facts/tasks/main.yml

Add role to set common OpenShift facts and call from ocp-workloads config.
- `openshift_api_url`
- `openshift_console_url`
- `openshift_cluster_ingress_domain`
New role: host-ocp4-set-facts
Config update: ocp-workloads

Host ocp4 set facts

---

ansible/roles/host-ocp4-installer/tasks/print_cluster_info.yml
ansible/roles/host-ocp4-set-facts/README.adoc
ansible/roles/host-ocp4-set-facts/tasks/main.yml

Add `openshift_route_default_domain` fact set by `host-ocp4-installer` and `host-ocp4-set-facts` roles. This supplements the `openshift_cluster_ingress_domain` and `openshift_cluster_ingress_apps_domain` variables which related the cluster ingress domains `spec.domain` and `spec.appsDomain`. The variable `openshift_route_default_domain` is the domain used by routes with dynamic `spec.host` and is either equal to `openshift_cluster_ingress_domain` or `openshift_cluster_ingress_apps_domain` depending on which is set.
Roles `host-ocp4-installer` and `host-ocp4-set-facts`.

Add openshift_route_default_domain

---

ansible/roles-infra/infra-windows-connection-facts/defaults/main.yml

infra-windows-connection-facts fails, due to a typo of extra dashes. Removing the resolve.
infra-windows-connection-facts
```paste below
```

infra-windows-connection-facts remove extra dashes at top of yaml

---

ansible/configs/ansible-bu-workshop/files/cloud_providers/ec2_cloud_template.j2

While Throughput is a valid config option via the EC2 EBS API, CloudFormation AWS::EC2::Instance Ebs does not currently handle this config option: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/824
ansible/configs/ansible-bu-workshop

Remove EBS Throughput config from ansible/configs/ansible-bu-workshop.

---

ansible/configs/ansible-bu-workshop/default_vars_ec2.yml
ansible/filter_plugins/core.py

Enable on-demand capacity reservations for ansible-bu-workshop config.
The flag `agnosticd_aws_capacity_reservations_enable` is false by default, so it'll have to be explicitely enabled in agnosticV.
This change also introduce a new jinja2 filter to facilitate the creation of the reservation by using what's defined in the `instances` variable.

ansible-bu-workshop: use on-demand capacity reservations

---

ansible/configs/rhel-security/software.yml
ansible/roles/rhel-security-verification/tasks/main.yml

Summit lab owners are removing systems that are not needed to remove ~600 VMs from the cost of deployment at summit.
rhel-security config and verification
```paste below
```

rhel-security update for removing extra systems for cost saving

---

ansible/roles/ansible-eda-config/README.adoc
ansible/roles/ansible-eda-config/defaults/main.yml
ansible/roles/ansible-eda-config/tasks/main.yml

Wraps the Ansible EDA infra.eda_configuration collection
Allows it to be called as an infra_worklaod
roles/ansible-eda-config

New wrapper role for EDA Config collection

---

ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/workload.yml

add timeouts for osd deployment
ocp4_workload_openshift_data_foundation
```paste below
```

add timeouts for osd deployment

---

ansible/configs/experience-ocpvirt/templates/configureMTV.sh.j2

portal.vc.opentlc.com was hardcoded. Changing to a variable coming from a secret - to be able to change without code changes.

Change VCenter Portal Address to be configurable

---

ansible/configs/test-empty-config/default_vars.yml
ansible/configs/test-empty-config/infra.yml
ansible/configs/test-empty-config/lifecycle.yml
ansible/configs/test-empty-config/post_infra.yml
ansible/configs/test-empty-config/post_software.yml
ansible/configs/test-empty-config/pre_infra.yml
ansible/configs/test-empty-config/pre_software.yml
ansible/configs/test-empty-config/software.yml
ansible/configs/test-empty-config/update.yml

- Add fail_on_start and fail_on_stop to test-empty-config
- Move defaults for fail_* variables to default_vars.yml

Add fail_on_start and fail_on_start to test-empty-config

---

ansible/roles/ai_setup_ilab/tasks/main.yml

Fix: RHEL 9 wants alternatives to set python3 and not pythons

Update default Python version mapping python3 to 3.11 in ai_setup_ilab role

---

ansible/roles/ai_setup_ilab/tasks/main.yml

RHEL has compilation issues building llama-cpp with CUDA support, which Fedora does not
Versions?
This brings it more in line with how to build for CUDA

Fix CUDA compile time issues for llama-cpp

---

ansible/configs/ibm-rhoic/default_vars.yml
ansible/configs/ibm-rhoic/infra.yml
ansible/configs/ibm-rhoic/software.yml

Add variable `terraform_version` and set default to `terraform-v1.4` for ibm-rhoic config.
The old hard-coded version `terraform-v0.14` is no longer available.
https://cloud.ibm.com/docs/schematics?topic=schematics-migrating-terraform-version
Config ibm-rhoic

Bump terraform to v1.4 for ibm-rhoic

---

ansible/configs/ocp4-cluster/files/requirements_k8s_el9.txt

For CNV environments the DNS entries are created in Route53.
Requirements were there for RHEL 8 but not for RHEL 9.
ocp4-cluster

Add AWS requirements to RHEL 9 k8s environment

---

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_crunchy_postgres.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_devspaces.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_grafana.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_hyperfoil.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_image_puller.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_logging_loki.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_noobaa.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_serverless.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_sonatype_nexus.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_tekton.yml
ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/workload.yml

Fixes CatalogSource namespace issue when installing Workload Operators.
Workload Role `ocp4_workload_performance_monitoring`
```bash
ansible [core 2.16.5]
config file = /Users/rsoares/dev/github/redhat-na-ssa/agnosticd/ansible.cfg
configured module search path = ['/Users/rsoares/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /opt/homebrew/Cellar/ansible/9.4.0/libexec/lib/python3.12/site-packages/ansible
ansible collection location = /Users/rsoares/.ansible/collections:/usr/share/ansible/collections
executable location = /opt/homebrew/bin/ansible
python version = 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/9.4.0/libexec/bin/python)
jinja version = 3.1.3
libyaml …
```

fixing catalogsource namespace issue for ocp4_workload_performance_monitoring

---

ansible/configs/experience-ocpvirt/post_software.yml

Moved infra_workloads task from line no 145 to line no 188.
Reason: Workloads requires public console link which get sets later so I moved workloads task afterwards.   
Config: experience-ocpvirt

shifting infra workload include task

---

ansible/configs/experience-ocpvirt/post_software.yml
ansible/configs/experience-ocpvirt/templates/exposeVMs.sh.j2
ansible/configs/experience-ocpvirt/templates/importVMs.sh.j2

This updates the experience-ocpvirt config to support exposing the imported VMs application.
. adds labels to the VM resources
. creates Services and Routes to expose the applicaiton
. creates a switch to turn the feature on, it's off by default.
.. ocp4_aio_expose_vms: true
```paste below
```

improve experience-ocpvirt to expose routes

---

ansible/roles_ocp_workloads/ocp4_workload_devops_roadshow/tasks/workload.yml

Fixes problems in this workshop with using query and fileglob in AgnosticD by replacing them with a hard coded list of files. Less maintainable but at least it works.
ocp4_workload_devops_roadshow
None

Replace query and fileglob with hard coded list of files in DevOps Roadshow workshop

---

ansible/roles_ocp_workloads/ocp4_workload_devops_roadshow/templates/user-appset.yaml.j2

We renamed the userX-tools namespace to userX-cicd and I forgot to change it in the user generating appset which results in a redundant namespace being created. I also removed the createNamespace flag from the Argo CD application since the users helm chart will do this anyway.
ocp4_workload_devops_roadshow

Rename tools to cicd ns in DevOps Roadshow

---

ansible/configs/experience-ocpvirt/templates/importVMs.sh.j2

small change to the shell script to parameterize starting newly imported VMs during deployment

experience-ocpvirt: starting VMs during deployment

---

ansible/roles_ocp_workloads/ocp4_workload_minio/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/meta/main.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/readme.adoc
ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/templates/deployment.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_minio/templates/namespace.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_minio/templates/persistentvolumeclaim.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_minio/templates/route_console.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_minio/templates/route_minio.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_minio/templates/secret.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_minio/templates/service.yaml.j2

Minio Workload hasn't been touched since 2020. Updated to support 2024 Minio deployments (while hopefully not breaking existing users).
Add capability to create a bucket.
Add capability to create buckets for each user
Add capability to not create routes.
ocp4_workload_minio

Updated Minio Workload to support modern (2024) Minio. Added bucket creation and multi-user deploy

---

ansible/roles_ocp_workloads/ocp4_workload_oadp/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp/files/objectbucketclaim.yaml
ansible/roles_ocp_workloads/ocp4_workload_oadp/meta/main.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp/readme.adoc
ansible/roles_ocp_workloads/ocp4_workload_oadp/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp/tasks/oadp_multi_user_install.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp/tasks/oadp_single_user_install.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp/templates/dataprotectionapplication.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_oadp/templates/dataprotectionapplication_multi_user.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_oadp/templates/rolebinding.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_oadp/templates/secret_cloud_credentials.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_oadp/templates/secret_cloud_credentials_multi_user.yaml.j2

Add workload to deploy the OADP Operator.
Optionally configure a DataProtectionApplication.
Single-user is the default (install for admins only).
Multi-user is available to deploy (and configure) one copy of the operator until the operator supports multi-tenancy (1.5+).
ocp4_workload_oadp

Add OADP Operator (both single and multi-user)

---

ansible/roles/ocp4_machineset_config/README.adoc
ansible/roles/ocp4_machineset_config/tasks/machineset-group-aws.yml
ansible/roles/ocp4_machineset_config/templates/machineset-aws.j2
ansible/roles_ocp_workloads/ocp4_workload_machinesets/defaults/main.yml

Enable the ansible roles ocp4_machineset_config & ocp4_workload_machinesets to create a machineset with a different architecure. 
Example for a multi-arch cluster:
```yaml
ocp4_installer_version: 4.15.14
ocp4_installer_url: https://mirror.openshift.com/pub/openshift-v4/multi/clients/ocp/4.15.14/amd64/openshift-install-linux.tar.gz
ocp4_client_url: https://mirror.openshift.com/pub/openshift-v4/multi/clients/ocp/4.15.14/amd64/openshift-client-linux.tar.gz
ocp4_network_type: OVNKubernetes
infra_workloads:
- ocp4_workload_machinesets
ocp4_workload_machinesets_machineset_groups:
- name: arm 
role: arm
instance_type: m7g.2xlarge 
instance_ami_architecture: aarch64
autoscale: false 
total_replicas: "{{ [(num_users | int / 5) | round(0, 'ceil') | int, 3] | max }}" 
total_replicas_min: "{{ …
```

Add support to overwrite ami architecture (role: ocp4_machineset_config & ocp4_workload_machinesets )

---

ansible/configs/ocp4-cluster/files/requirements_k8s.txt
ansible/configs/ocp4-cluster/files/requirements_k8s_el9.txt

In order to run workload ocp4_workload_virt_roadshow_vmware the k8s virtualenv needs two additional python modules installed.
ocp4-cluster

Updated k8s requirements to allow vCenter tasks to run

---

ansible/configs/experience-ocpvirt/vcenter-remove-access.yml
ansible/configs/osp-on-ocp/vcenter-remove-access.yml

fix deletions in VMW if folder is not created
configs/experience-ocpvirt/vcenter-remove-access.yml
configs/osp-on-ocp/vcenter-remove-access.yml
```paste below
```

fix deletions in VMW if folder is not created

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_remove_user.yml

Oddly deleting the user in vCenter failed with an error that the playbook couldn't be found. Re-arranging the command a bit.

Re-arrange delete of user to fix (?) error?

---

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/workload.yml

Adds timeouts for OSD deployment
RHTAP timeout patch
Why trying to deploy CI Red Hat Trusted Application Pipeline, you may encounter this error:
TASK [ocp4_workload_openshift_data_foundation : Wait for ODF Storage Cluster to finish deploying] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.kubernetes.core.plugins.module_utils.k8s.exceptions.CoreException: Failed to gather information about StorageCluster(s) even after waiting for 600 seconds
fatal: [bastion.tf2q9.internal]: FAILED! => {"changed": false, "msg": "Failed to gather information about StorageCluster(s) even after waiting for 600 seconds"}
Error looks similar to errors fixed by:
https://github.com/rhpds/agnosticv/pull/14743/files …

RHTAP timeout patch

---

ansible/roles/ansible_bu_satellite/tasks/main.yml

Earlier this year, Let’s Encrypt generated new intermediate keys and certificates. On Thursday, June 6th, 2024, Let's Encrypt switched issuance to use the new intermediate certificates. As a result, the CA bundle built for the Satellite was incorrect and any certificate validation would fail.
This PR switches from the old R3 intermediate cert to the new R11 cert.
ansible/roles/ansible_bu_satellite

Switch to new LetsEncrypt R11 intermediate cert.

---

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/cert_manager_ec2.yml

For CNV Clusters (which use Route53) allow passing of the HostedZoneID via variable instead of trying to determine it. This way certs can be requested for CNV clusters.

Allow passing of the hostedzoneid (for CNV clusters) instead of determining it

---

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_rhsso.yml

sometimes Retrieve backstage realm client credentials is taking time
ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_rhsso.yml

Update setup_rhsso.yml as sometimes Retrieve backstage realm client credentials is taking time

---

ansible/configs/ocp4-cluster/default_vars_openshift_cnv.yml
ansible/roles/host-ocp4-assisted-destroy/templates/cleanup-ceph.yaml.j2

This PR adds a variable to customize the cleanup job image (default now 4.15 instead of the outdated 4.13) enabling easier updates to future releases.
ocp4-cluster
host-ocp4-assisted-destroy

Fix ceph cleanup on CNV in Sandboxes. Make cleanup image configurable

---

ansible/configs/zero-touch-base-rhel/lock_bastion_security_group.yml

Zero Touch RHEL, This PR is to allow outbound traffic to the satellite. This is required by multiple labs to install packages.

ZT RHEL update to allow outbound with var

---

ansible/roles_ocp_workloads/ocp4_workload_summit_2024_cloud_native_camel/tasks/install_devspaces.yml

…spaces operator
Ansible task (Check DevSpaces plugin-registry devfile endpoint readiness)  was failing for checking plugin registry endpoint uri, Updated plugin registry URI to match the latest version of dev spaces
Install_devspaces.yaml , Task : Check DevSpaces plugin-registry devfile endpoint readiness
```paste below
```

Fix workload ocp4_workload_summit_2024_cloud_native_camel devspaces bug.

---

ansible/configs/rosa-consolidated/requirements.yml

Updated kubernetes.core ansible module version. Old version doesn't work with Ansible automation platform role. 
This is the same version used in ocp4-cluster config.
Config: rosa-consolidated

update kubernetes.core module version

---

ansible/configs/ocp4-cluster/destroy_env_openshift_cnv.yml

connection:local prevents dynamic additions of hosts. So some destroy tasks fail.
ocp4_cluster

Remove local connection from destroy

---

ansible/roles_ocp_workloads/ocp4_workload_cloud_architecture_workshop_summit2023/templates/devspaces-checluster.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_cloud_architecture_workshop_summit2023/templates/rhbk-application.yaml.j2

ansible/roles_ocp_workloads/ocp4_workload_cloud_architecture_workshop_summit2023
AgnosticV catalog item: sandboxes-gpte/CLOUD_ARCHITECTURE_WORKSHOP
Fixes:
* Dev Workspaces: fix for https://issues.redhat.com/browse/CRW-6048
* RHBK ArgoCD application: ignore differences in generated id's

Cloud native architecture workshop: bug fixes

---

ansible/configs/zero-touch-base-rhel/default_vars_ec2.yml

Adding default var for AWS egress rules.
```paste below
```

zero-touch-base-rhel default egress to []

---

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/workload.yml

Fix cert manager API name
```paste below
```

Fix cert manager API name

---

ansible/roles/asset_injector/tasks/main.yml

This update adds variables to control the file mode and owner for injecting assets with blockinfile.
```paste below
```

asset-injector role, update blockinfile vars

---

ansible/configs/roadshow-ocpvirt/pre_software.yml

Pull files from S3 instead of legacy WWW host.
roadshow-ocpvirt
```paste below
```

pull files from S3 not www

---

ansible/roles_ocp_workloads/ocp4_workload_sonarqube/templates/cicd/sonarqube-persistent-deploy.yaml.j2

The previous configuration of this template in `ansible/roles_ocp_workloads/ocp4_workload_sonarqube/templates/cicd/sonarqube-persistent-deploy.yaml.j2` was using a Sonarqube container image hosted on Docker Hub.  This has been moved to the Quay mirror.
In addition, the previous Sonarqube image was over 4 years old, 3 major releases behind, and also ranked with a startling 10.0 CVE score due to dozens of legacy issues and vulnerabilities, one of which was the Log4j exploit - somewhat of a bad look in the context of the RHTAP demo/workshop.  The image has been updated to SonarQube v10 and tied to a specific tag that's more up to date.
In newer versions of Sonarqube the JDBC_URL was changed to use the SONAR_JDBC_URL which is also reflected in the changed Deployment template.
The LDAP …

SonarQube patch for critical CVE

---

ansible/roles/ansible_bu_setup_workshop/tasks/auto_satellite.yml

Include deploy logic for `el_rebuild_distribution` var choice of centos vs oracle.
ansible/roles/ansible_bu_setup_workshop

ansible_bu_setup_workshop role - auto_satellite deploy logic, centos or oracle

---

ansible/roles/ansible_bu_setup_workshop/tasks/auto_satellite.yml

Raise oracle scenario deploy timeout to 5 hours. ~ 4 hours is required to sync Oracle repos on Satellite.
ansible_bu_setup_workshop role

ansible_bu_setup_workshop role - raise oracle scenario deploy timeout to 5 hours.

---

ansible/roles/host-ocp4-installer/tasks/install_installer.yml

This change try to fix:
```
TASK [host-ocp4-installer : Create OpenShift Bash completion file] *************
Wednesday 03 July 2024  11:30:55 +0000 (0:00:00.542)       1:01:05.004 ********
fatal: [bastion.n5s6l.internal]: FAILED! => {"changed": true, "cmd": "oc completion bash >/etc/bash_completion.d/openshift", "delta": "0:00:00.005362", "end": "2024-07-03 11:30:55.557546", "msg": "non-zero return code", "rc": 1, "start": "2024-07-03 11:30:55.552184", "stderr": "oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)\noc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by oc)\noc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by oc)", "stderr_lines": ["oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)", "oc: /lib64/libc.so.6: …
```

Fix oc client version

---

ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/workload.yml

For running ODF on ROSA. We need to skip labeling infra nodes. 
ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/workload.yml

Skip infra nodes

---

ansible/configs/rhel8-base/post_infra.yml

deploys are failing with this log https://aap2-prod-us-east-2.aap.infra.demo.redhat.com/#/jobs/playbook/638173/output
-->
the RHEL9 base CI using the RHEL8 base config is failing with syntax error like in this job: https://aap2-prod-us-east-2.aap.infra.demo.redhat.com/#/jobs/playbook/638173/output
RHEL8 config post_infra task

Update post_infra.yml rhel8 base indentation fix

---

ansible/configs/zero-touch-base-rhel/post_infra.yml
ansible/configs/zero-touch-base-rhel/post_software.yml

This adds the ec2_add_subnet_and_nic role with conditionals required for "Networking Basics (Admin 101)" to function.
```paste below
```

zero-touch-base-rhel, update config including network config

---

ansible/configs/zero-touch-base-rhel/post_infra.yml

Fixes incorrect formatting for include_role
```paste below
```

zero-touch-base-rhel, correct name for include_role

---

ansible/roles/ec2_add_subnet_and_nic/defaults/main.yaml

ec2_add_subnet_and_nic
```paste below
```

ec2_add_subnet_and_nic, comment out non role vars in default

---

ansible/configs/rosa-consolidated/default_vars.yml
ansible/configs/rosa-consolidated/install_rosa_common_post.yml
ansible/configs/rosa-consolidated/pre_software.yml
ansible/configs/rosa-consolidated/software.yml

Variables in the agnosticd_user_info data impacted:
- **rosa_sandbox_account_id**: deleted as it can be retrieved by `aws_web_console_url`
- **rosa_console_user_name**: deleted as it can be retrieved by `aws_web_console_user_name`
- **rosa_console_password**: deleted as it can be retrieved by `aws_web_console_password`
- **rosa_console_url**: renamed to `rosa_openshift_console_url`
- **rosa_api_url**: renamed to `rosa_openshift_api_url`
- **rosa_bastion_user_name**: deleted as it can be retrieved by `ssh_username`
- **rosa_user_password**: deleted, use `ssh_password`
- **rosa_ocp_cli_version**: deleted
- **rosa_admin_user**: renamed to `rosa_openshift_admin_user`
- **rosa_admin_password**: renamed to `rosa_openshift_admin_password`
AgnosticV changes to be done after this:
- …

Fix rosa-consolidated user data

---

ansible/roles_ocp_workloads/ocp4_workload_tl500/tasks/workload.yml

TL500 DevOps Culture and Practice
I'll mark the PR ready when I get okay from @eformat :) so I am tagging him here to check ❤️
Also, is it possible to mark existing prod TL500 catalog item on RHPDS as maintenance or something like that? There are a couple of PRs in different repositories that we need to align to make this change..which might affect the existing TL500 item.
And, since [AgnosticV repository](https://github.com/rhpds/agnosticv/blob/master/sandboxes-gpte/OCP4_WORKSHOP_DEVOPS_TL500/dev.yaml#L7) is already updated by @bbethell-1 with OCP v4.15 (thanks again!✨), there is nothing to do on that side. 
When we are moving these changes to prod, we need to do an update [here](https://github.com/rhpds/agnosticv/blob/master/sandboxes-gpte/OCP4_WORKSHOP_DEVOPS_T …

🎈pointing to uptaded content for v4.15🎈

---

ansible/roles_ocp_workloads/ocp4_workload_devops_roadshow/files/appprojects/users.yaml
ansible/roles_ocp_workloads/ocp4_workload_devops_roadshow/templates/user-appset.yaml.j2

This PR changes the users applicationset to use the users appproject as was originally intended. it also updates the permissions on the users appproject so that users can see the user facing applications with limited permissions (get and sync only)
DEVOPS_ROADSHOW

Update users appproject and permissions in DevOps Roadshow

---

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/workload.yml

The cert manager workload would fail if there was an error requesting certificates. In some cases it can be useful to not fail but print an error and continue provisioning - e.g. for DEV CIs.
Add variable ocp4_workload_cert_manager_ignore_errors to configure this behaviour.

Add graceful ignore of certificate failures

---

ansible/roles/agnosticd_save_output_dir/tasks/create-output-dir-archive.yml
ansible/roles/agnosticd_save_output_dir/tasks/main.yml
ansible/roles/agnosticd_save_output_dir/tasks/save-output-dir.yml
ansible/roles/agnosticd_save_output_dir/tasks/upload-archive-s3.yml

At least one CI was failing due to this role invoking `ansible.legacy.command`. This PR explicitly makes the role use FQCNs and does some minor cleanup (add a name: use top when consistently)
roles/agnosticd_save_output_dir

Add FQCN to agnosticd_save_output_dir role and minor cleanup

---

ansible/roles_ocp_workloads/ocp4_workload_devops_roadshow/files/appprojects/users.yaml
ansible/roles_ocp_workloads/ocp4_workload_devops_roadshow/tasks/workload.yml

The workshop fails every so often with cert issues when attempting to use the `oc` command in some of the plays. This PR adds a task to test and retry oc until it works for up to 10 minutes.
DEVOPS_ROADSHOW

DevOps Roadshow: Add test/retry for oc in case API endpoint is still working on cert

---

ansible/roles/showroom/templates/base_service_traefik_httpd/base_service_traefik_httpd.j2

Orchestration template for showroom's traefik reverse proxy had a port typo in it
roles/showroom

Fix showroom_primary_port typo in showroom traefik orchestration

---

ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/workload.yml

Once in a while creating the minio buckets fails with a connection error. Adding a few retries to catch those.
ocp4_workload_minio

Add retries to Minio Setup to catch instabilities

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/templates/secret_vmware_credentials.yaml.j2

For multi-user CNV Roadshow the secret to connect MTV to vCenter was using the wrong user base variable.

Wrong user base variable used. Fixed

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow/tasks/workload.yml

Fixing a duplicate `.yaml` in two templates that resulted in failures.
ocp4_workload_virt_roadshow

Fix typos in filenames

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow/templates/configmap-ui-settings.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow/templates/configmap-user-settings.yaml.j2

OCP Virt requires an Admin to log into the console and go to all pages for settings config maps to be written.
Attempt to pre-create config maps with settings.
ocp4_workload_virt_roadshow

Add configmaps to cluster

---

ansible/roles-infra/infra_vmware_ibm_resources/tasks/create_instance.yaml

add folder to add vm to network on ocp4 upi
roles-infra/infra_vmware_ibm_resources
```paste below
```

add folder to add vm to network on ocp4 upi

---

ansible/configs/ocp4-upi-vmc/vmware_ibm_destroy_env.yml

fix destroy ocp4 on cnv upi destroy
ocp4-upi-vmc/vmware_ibm_destroy_env
```paste below
```

fix destroy ocp4 on cnv upi destroy

---

ansible/roles/openshift_cluster_admin_service_account/tasks/main.yml

OpenShift service account token handling changed with 4.16 such that it no longer automatically generates a service account access token.
This fixes the role by adding a call to create an access token as well as getting the API CA cert a different way.
Role openshift_cluster_admin_service_account

Fix openshift_cluster_admin_service_account for OpenShift 4.16

---

ansible/roles_ocp_workloads/ocp4_workload_rhods_self_managed/tasks/workload.yml

Sometimes RHODS dashboard route is taking more time to get ready to serve.
Controller Job No: 688862, 691261
ansible/roles_ocp_workloads/ocp4_workload_rhods_self_managed/tasks/workload.yml

Update workload.yml to increase retry for getting ready RHODS dashboard route

---

ansible/configs/ocp4-cluster/default_vars_openshift_cnv.yml
ansible/configs/ocp4-cluster/destroy_env_openshift_cnv.yml
ansible/roles_ocp_workloads/ocp4_workload_kubevirt/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_kubevirt/templates/hyperconverged.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_kubevirt/vars/main.yml

To fix the issue with dangling VolumeSnapshots:
- Add logic to ocp4_workload_kubevirt to use pvcs instead of snapshots for OS Disk Images
- Add support to ocp4-cluster for CNV to pre-delete all VMs on the cluster to also clean up snapshots that may have been created by users.
ocp4-cluster

Add logic to use pvcs instead of snapshots for os images, add support to pre-delete VMs on CNV to ocp4-cluster

---

ansible/roles/asset_injector/README.adoc
ansible/roles/asset_injector/tasks/main.yml

Adds cmd function to asset-injector role
asset-injector
```paste below
```

asset-injector add cmd functionality

---

ansible/roles/asset_injector/README.adoc
ansible/roles/asset_injector/tasks/main.yml

Adds ansible.builtin.group module to asset-injector
asset-injector
```paste below
```

asset-injector, add ansible.builtin.group module

---

ansible/configs/ocp4-cluster/files/requirements_k8s.txt
ansible/configs/ocp4-cluster/files/requirements_k8s_el9.txt

New vCenter logic needs the aiohttp module in the k8s virtualenv.
Added.
ocp4-cluster

Add aio_http module to k8s virtualenv

---

ansible/roles-infra/infra-gcp-credentials-file/tasks/main.yml
ansible/roles/gcp-get-token/tasks/main.yml
ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/secret-gcp-credentials.yaml.j2

When the `gcp_credentials` value is supplied as a vaulted string then Ansible automatically handles the json string by loading it as a dictionary. This PR includes fixes to handle this format.
GCP cloud provider

Fix handling of gcp_credentials if value is mapping

---

ansible/configs/ocp4-cluster/files/requirements_k8s_el9.txt
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_prerequisites.yml

New vmware logic needs the vSphere Automation SDK installed in the k8s virtualenv.
Installing the SDK only for the workload.
Update ocp4-cluster k8s requirements to eliminate a version mismatch.
ocp4-cluster

Install vSphere Automation SDK in k8s virtualenv

---

ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/workload.yml

Make bucket creation not fail if bucket already exists.

OCP4_workload_minio: don't fail on existing minio buckets during install

---

ansible/roles/ansible_bu_satellite/tasks/main.yml

For Satellite 6.15, the katello-agent has been deprecated, requiring the utilization of the Satellite API and curl-bash method for registration of Content Hosts. Utilization of this registration method requires that the Registration and Template modules be enabled on any Satellite/Capsule systems utilized for Content Host registration.
roles/ansible_bu_satellite

Enable registration and template modules for foreman-proxy.

---

ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml
ansible/roles/open-env-gcp-remove-project/tasks/main.yml

go back to string for gcp credentials
open-env-gcp
```paste below
```

go back to string for gcp credentials

---

ansible/configs/ocp4-cluster/pre_software.yml

Correct logic error introduced during reformatting which causes RHEL8 hosts to skip virtualenv setup.

Fix ocp4-cluster k8s venv setup for RHEL 8

---

ansible/configs/experience-ocpvirt/default_vars_ec2.yml
ansible/configs/experience-ocpvirt/default_vars_equinix_metal.yml
ansible/configs/roadshow-ocpvirt/default_vars_ec2.yml
ansible/configs/roadshow-ocpvirt/default_vars_equinix_metal.yml
ansible/roles-infra/infra-vmc-sandbox/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/defaults/main.yml

remove unnecessary role permissions in vmware
ansible/configs/experience-ocpvirt/default_vars_ec2.yml
ansible/configs/experience-ocpvirt/default_vars_equinix_metal.yml
ansible/configs/roadshow-ocpvirt/default_vars_ec2.yml
ansible/configs/roadshow-ocpvirt/default_vars_equinix_metal.yml
ansible/roles-infra/infra-vmc-sandbox/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/defaults/main.yml
```paste below
```

remove unnecessary role permissions in vmware

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/multi_user/vm_database.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/multi_user/vm_winweb01.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/multi_user/vm_winweb02.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/single_user/vm_database.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/single_user/vm_winweb01.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/single_user/vm_winweb02.yaml.j2

As per this thread:
https://redhat-internal.slack.com/archives/C06A9FZL9N1/p1723670395722869
and this thread:
https://redhat-internal.slack.com/archives/C06A9FZL9N1/p1723819765836269?thread_ts=1723670395.722869&cid=C06A9FZL9N1
Change the values for CPUs for the pre-imported VMs to enable CPU hotplug scenarios.
ocp4_workload_virt_roadshow_vms

Adjust cpu settings for pre-imported VMs to enable CPU hotplug

---

ansible/roles/showroom/templates/ansible_runner_api_service/ansible_runner_api_service.j2

Add dns_search Parameter in Ansible Runner API Showroom Service Template.
Problem:
In RHEL 9, pods are unable to connect using short names due to the missing search entry in the /etc/resolv.conf file.
Solution:
To address this issue and ensure compatibility across both RHEL 8 and RHEL 9, the dns_search parameter in the container compose file within the Ansible Runner API showroom service template.
This adjustment will allow pods to resolve short names correctly by specifying the appropriate search domains in the DNS resolution process.
Role: showroom

adding dns_search 

---

ansible/roles/ansible_bu_setup_workshop/tasks/ripu.yml

For RIPU workshop deploy, increase timeout for final workshop deployment workflow template from 900 seconds to 1300 seconds.
roles/ansible_bu_setup_workshop

RIPU workshop - Increase timeout for final workshop deployment workflow template.

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_create_folder_and_vms.yml

Under load, the VMware cluster sometimes fails, so add retriesZZ
```
"default_message": "The maximum attempts to find unique directory name limit has been reached.",
"id": "com.vmware.vim.vm.error.AttemptToFindUniqueDirectoryNameLimitReached"
```
```paste below
```

ocp4_workload_virt_roadshow_vmware: retries for Create VM

---

ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/templates/application.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/templates/applicationset.yaml.j2

Enable the OADP Gitops workload to deploy with ODF as storage instead of Minio. Test single and multi-user on GCP.
ocp4_workload_oadp_gitops

Enable oadp gitops workload for odf

---

ansible/configs/ocp-workloads/default_vars.yml

Fix `cluster_workloads` to be default to `ocp_workloads`, which defaults to `infra_workloads` for compatibility.
Config ocp-workloads

Fix ocp workload defaults

---

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/templates/openshift-gitops.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/vars/main.yml

Starting with Gitops 1.13 the default Route is created using proper TLS encryption on the default ArgoCD instance.
Turning off setting the TLS route resulted in the route not being created at all.
Fix: New variable (set to true by default) to control creating the route. Only update TLS settings when requested.
Also fixed: API version of the ArgoCD instance changed to v1beta1 from v1alpha1. Added code to use the correct API version.

Fix route creation

---

ansible/configs/zero-touch-base-rhel/pre_software.yml

This update adds code to configure a second system for the showroom to ssh into. This is due to labs running RHEL 7 that also cannot use OCP4 showroom.
```paste below
```

zero-touch-base-rhel add functionality for rhel 7 systems

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_create_folder_and_vms.yml

ocp4_workload_..vmware: retry get folder ID in vmware workload

---

ansible/roles/host-ocp4-installer/tasks/create-manifests.yml
ansible/roles/host-ocp4-installer/tasks/install_installer.yml
ansible/roles/host-ocp4-installer/tasks/main.yml
ansible/roles/host-ocp4-installer/tasks/setup-fips-host.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/setup_htpasswd.yml
ansible/roles_ocp_workloads/ocp4_workload_le_certificates/tasks/workload.yml

Installing a FIPS cluster changed in 4.16. It now needs a FIPS enabled RHEL to run the installer. The installer has a different name as well. And finally the way that we created passwords in the authentication workload using `htpasswd` was not FIPS compliant either.
Fixed all of that.
Tested on 4.16, 4.15 and 4.14.

Update installer logic

---

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/cert_manager_api_cert_check.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/cert_manager_ingress_cert_check.yml
ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/workload.yml

add retries for certmanager cert checks
```paste below
```

add retries for certmanager cert checks

---

ansible/roles/bastion-base/defaults/main.yml
ansible/roles/bastion-base/tasks/main.yml

Allows bastion-base role to NOT install packages if set
- Packages will install by default, unless `bastion_install_basic_packages: true`
Motivated by immutable OS images like RHEL AI, however, a useful feature independent of motivation
roles/bastion-base

Allow bastion dnf package install to be turned off, on by default

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml

Lower CPU requests in ocp4_workload_showroom. Showroom pods mostly sit idle and reserving half a CPU for exclusive use by containers that are mostly idle wastes a lot of resources and drives up cost.
Role ocp4_workload_showroom

Lower cpu requests in ocp4_workload_showroom

---

ansible/roles-infra/infra-vmc-resources/tasks/start_instances.yaml
ansible/roles-infra/infra-vmc-resources/tasks/stop_instances.yaml

fix typo in start/stop for vmware
infra-vmc-resources
```paste below
```

fix typo in start/stop for vmware

---

ansible/configs/virt-roadshow-binder/post_software.yml
ansible/roles_ocp_workloads/ocp4_workload_external_odf/tasks/workload.yml

* Update the config/virt-roadshow-binder to handle differences in calling the vmware role
* remove environment setup because `cluster_name` is not available when workload is not called from config/ocp4-cluster

virt binder fixups to enable workloads and remove kubeconfig+cluster_name reference

---

ansible/roles/common/tasks/main.yml

This role was using "ansible.builtin.dnf" to update all packages on systems. This module will not work for RHEL 7 systems.
The "ansible.bultin.package" module will allow us to run this role on legacy systems as it acts as a proxy to the underlying package manager module. While all arguments will be passed to the underlying module.
Role: common
```paste below
```

Role common , Update dnf module to use package

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/multi_user/service_database.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/multi_user/vm_winweb01.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/multi_user/vm_winweb02.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/single_user/service_database.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/single_user/vm_winweb01.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/single_user/vm_winweb02.yaml.j2

The VMs that are pre-populated for the roadshow were fully functioning. The roadshow instructions however expect the students to fix the labels on the VMs and create the service for the database.
A new flag ocp4_workload_virt_roadshow_vms_roadshow_setup has been created (defaults to true) that will make the VMs "roadshow ready".
ocp4_workload_virt_roadshow_vms

Pre-deployed VMs were working before. Fix for roadshow

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_create_folder_and_vms.yml

Task contains retries and delay but until parameter was missing
Role ocp4_workload_virt_roadshow_vmware

[ocp4_workload_virt_roadshow_vmware] Add missing until on vcenter_setup_create_folder_and_vms.yml

---

ansible/roles/showroom/tasks/22-showroom-users-security.yml
ansible/roles/showroom/templates/tmux.conf.j2

Enhances showrooms `tmux` option by allowing seamless copy and paste across major OS client platforms:
- Linux
- MacOS
- Windows
Disables tmux right-click menu (was clashing with OS based right click menus)
Avoids truncation of pasted commands which occurred on windows and linux
roles/showroom

Add enhanced tmux.conf with cross-platform copy and paste to showroom

---

ansible/roles/deploy_automationcontroller/tasks/main.yml

Ansible Automation Platform installer failing due to improper version of python3-cryptography RPM package being installed during AAP install automation. An additional task is included to modify init.yml in certificate_authority role within Ansible Automation Platform installer code to use dnf module and specific versioning of python3-cryptography. This additional task is included _prior_ to the installer setup.sh being instantiated.
ansible/roles/deploy_automationcontroller

deploy_automationcontroller role - Modify init.yml in certificate_authority role

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_create_folder_and_vms.yml

We are hitting the following bug:
https://github.com/ansible-collections/vmware.vmware_rest/issues/324
This is a workaround till new version of the vmware.vmware_rest will be released
ocp4_workload_virt_roadshow_vmware role

[ocp4_workload_virt_roadshow_vmware] Using vcenter_folder_info instead folder_moid

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_create_folder_and_vms.yml

The workaround https://github.com/redhat-cop/agnosticd/pull/8551 was missing the environment variables
ocp4_workload_virt_roadshow_vmware role

[ocp4_workload_virt_roadshow_vmware] Adding missing environment variables

---

ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml

For sandbox quotas, we require specify the limits for the VM
We set the limit to the request values.
Role infra-openshift-cnv-resources

[infra-openshift-cnv-resources] Add limits to VM

---

ansible/roles/showroom/defaults/main.yml
ansible/roles/showroom/tasks/22-showroom-users-security.yml

This conditional is to avoid larger changes to the showroom role. For zero-touch items we have the need to run the showroom on a separate server with ssh connection to another box. The changed task was failing due to the showroom role attempting to place the file in the improper directory on the wrong system.
role: showroom
```paste below
```

Showroom role, add conditional to disable tmux scrolling

---

ansible/configs/experience-ocpvirt/vcenter-setup-webapp-vms.yml

VMware directory services do not handle multiple identical VM names at all well.
This adds GUIDs to the vmnames.

Equinix Legacy patch: ROADSHOW and BOOTCAMP: add GUID to vmname

---

ansible/configs/ocp4-cluster/destroy_env_openshift_cnv.yml
ansible/configs/osp-on-ocp/pre_software.yml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/start_instances.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/stop_instances.yaml
ansible/roles/host-ocp4-hcp-cnv-destroy/tasks/main.yaml
ansible/roles/host-ocp4-hcp-cnv-destroy/vars/main.yaml
ansible/roles/host-ocp4-hcp-cnv-install/defaults/main.yaml
ansible/roles/host-ocp4-hcp-cnv-install/tasks/main.yaml
ansible/roles/host-ocp4-hcp-cnv-install/tasks/print_cluster_info.yml
ansible/roles/host-ocp4-hcp-cnv-install/tasks/setup_htpasswd_authentication.yml
ansible/roles/host-ocp4-hcp-cnv-install/templates/certificate.yaml
ansible/roles/host-ocp4-hcp-cnv-install/templates/clusterrolebinding.yaml
ansible/roles/host-ocp4-hcp-cnv-install/templates/hostedcluster.yaml
ansible/roles/host-ocp4-hcp-cnv-install/templates/kubeconfig.yaml
ansible/roles/host-ocp4-hcp-cnv-install/templates/kubeconfigsecret.yaml
ansible/roles/host-ocp4-hcp-cnv-install/templates/nodepool.yaml
ansible/roles/host-ocp4-hcp-cnv-install/templates/pullsecret.yaml
ansible/roles/host-ocp4-hcp-cnv-install/templates/secret-htpasswd.yaml
ansible/roles/host-ocp4-hcp-cnv-install/templates/workers_svc.yaml
ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_create_folder_and_vms.yml
ansible/software_playbooks/openshift4_hcp_cnv.yml

This PR includes the following roles:
**host-ocp4-hcp-cnv-install**: Installs OCP using HostedCluster and NodePool resources. It registers in the DNS, order a Certificate and configure authentication if needed.
**host-ocp4-hcp-cnv-destroy**: Removes the HostedCluster to release resources and be able to remove the namespace.
It improves the stop and the start of the VMs on OpenShift Virtualization. VMs can be started in two ways (**running**: true or **runningStrategy**: Always) and the same stopping it. HCP uses **runningStrategy** instead **running**, the only way we had in our code.
As well for the storageclass on the guest OCP cluster, the **claimPropertySets** properties is configured on the StorageProfile object, to define the accessModes and the volumeMode

Adding new roles to install OCP4 cluster on a HCP with OCPVirt

---

ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/files/gitops-operator/subscription.yaml
ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/templates/pipelines-operator.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/templates/rollouts-manager.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/templates/user-appset.yaml.j2

- Adds a new variable from agnosticv called `git_revision` that is used to pin apps in rollouts repo to better support environments and staged promotions
- Bumps the OpenShift GitOps version to 1.13 
ocp4_workload_rollouts_workshop
Part of updating workshop to use Showroom for improved user experience

Update to use git_revision variable to commit pin in rollouts repo

---

ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml

Control plane VMs are using local disk, so LiveMigration (default) it is not possible

[host-ocp4-assisted-installer] Specify evictionStrategy shutdown for control plane

---

ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml

**SUMMARY**
Control plane VMs are using local disk, so LiveMigration (default) it is not possible
**ISSUE TYPE**
**COMPONENT NAME**

[host-ocp4-assisted-installer] Specify evictionStrategy to none for ctl planes

---

ansible/roles_ocp_workloads/ocp4_workload_minio/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/meta/main.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/workload.yml

The MinIO Workload used the wrong variable name (ocp4_workload_minio_bucket_base instead of ocp4_workload_minio_bucket_name) for the single user deployment.
Also updated to latest coding guidelines.
ocp4_workload_minio

Fix single user bucket name for MinIO workload

---

ansible/roles/host-ocp4-assisted-destroy/templates/cleanup-ceph.yaml.j2

Using sandbox the name of the namespace is not the same as the volumePrefixName we use on external ODF:
https://github.com/redhat-cop/agnosticd/blob/5e9712854f03f64a618774d66abaa473a8a30d23/ansible/roles_ocp_workloads/ocp4_workload_external_odf/templates/storageclass.yaml.j2#L21
host-ocp4-assisted-destroy role

[host-ocp4-assisted-destroy] Fixing LAB variable

---

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml

Kasten URL needs a trailing / to work.
Adding to the agd user info data.

Add missing / to the end of the kasten URL

---

ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/workload.yml

During functional tests of OcpVirt Roadshow, we detected default snapshot is not working
ocp4_workload_kubevirt role

[ocp4_workload_kubevirt] Add cloneStrategy and fix volumeMode

---

ansible/roles/ocp4_machineset_config/tasks/machineset-group-aws.yml

Added missing type cast
Based on https://redhat-internal.slack.com/archives/C04MLMA15MX/p1726674780813579
ansible/roles/ocp4_machineset_config/tasks/machineset-group-aws.yml
```paste below
TASK [ocp4_machineset_config : Define worker-gpu machineautoscalers] ***********
Wednesday 18 September 2024  15:30:17 +0000 (0:00:03.210)       0:51:44.465 *** 
fatal: [bastion.zqkhr.internal]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ (\\n   (machineset_group.total_replicas_min|default(0) + loop_index) /\\n   aws_worker_availability_zones | count\\n) | int }}'. Error was a <class …
```

Added missing type cast

---

ansible/configs/ocp4-cluster/files/requirements_k8s.txt

Specify a different version for aiohttp
In RHEL86 throws this error:
ERROR: Could not find a version that satisfies the requirement aiohttp==3.10.2
ocp4-cluster Role

[ocp4-cluster] Update requirements_k8s.txt to specify another version of aiohttp

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml

Adds extra check if the RHCOS images are not downloaded. The async job fails often.
- Role: ocp4_workload_5gran_deployments_lab
```paste below
```

Adds extra checks when OCP images task fails

---

ansible/configs/zero-touch-base-rhel/pre_software.yml

Add satellite configuration for satellite basics zero touch lab.
```paste below
```

zero-touch-base-rhel satellite configuration

---

ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml
ansible/roles/host-lets-encrypt-certs-certbot/templates/run-certbot.j2

add dns back into certbot role for zerossl
```paste below
```

add dns back into certbot role for zerossl

---

ansible/roles/showroom/tasks/22-showroom-users-security.yml
ansible/roles/showroom/templates/service_tty1/service_tty1.j2
ansible/roles/showroom/templates/service_tty2/service_tty2.j2
ansible/roles/showroom/templates/ssh_config_multi.j2

Modify the showroom role to allow multiple ssh destinations.
Role: showroom
```paste below
```

Role showroom, add option for multiple ssh destinations

---

ansible/roles-infra/infra-openshift-cnv-create-inventory/tasks/create_inventory.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/start_instances.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/status_instances.yaml
ansible/roles-infra/infra-openshift-cnv-resources/tasks/stop_instances.yaml
ansible/roles-infra/infra-vmc-resources/tasks/status_instances.yaml
ansible/roles-infra/infra_vmware_ibm_resources/tasks/status_instances.yaml
ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml
ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_workers.yaml

New OCP versions requires to specify kubevirt.io/v1 for the k8s and k8s_info  modules are throwing the following error: 
too many values to unpack (expected 2)
infra-openshift-cnv-resources  Role
infra-openshift-cnv-create-inventory Role

Add api_version to kubevirt.io/v1

---

ansible/roles/host-ocp4-hcp-cnv-install/tasks/setup_htpasswd_authentication.yml

Some showroom instructions uses openshift_console_url instead openshift_cluster_console_url variable, this will cover more use cases

[host-ocp4-hcp-cnv-install] Adding variable openshift_console_url to user data

---

ansible/roles/host-ocp4-hcp-cnv-install/tasks/print_cluster_info.yml

Current values were optimistic values. On overreload cluster will take more than 5 minutes.

[host-ocp4-hcp-cnv-install] Increase delays/retries

---

ansible/configs/base-infra/destroy_env.yml
ansible/configs/base-infra/post_software.yml

Allows config base-infra to used the shared OpenShift showroom role, and clean it up on destroy

Add shared ocp showroom to config base-infra

---

ansible/roles/asset_injector/tasks/main.yml

Missing quotes around var broke role - how did the linters not pick this up

Fix missing quotes in asset_injector role

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/multi_user/vm_database.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/single_user/vm_database.yaml.j2

Database VM for roadshow is a image not using EFI
ocp4_workload_virt_roadshow_vms role

[ocp4_workload_virt_roadshow_vms] Change database to use bios and not efi

---

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml

Resource is actually `kind: k10s`

ocp4_workload_kasten_k10: fix kasten kind: k10s, not k10

---

ansible/roles/s3_asset_injector/defaults/main.yml

Set safe, empty, defaults for AWS vars in s3_asset_injector role
It avoids unnecessary errors if vars are not set
roles/s3_asset_injector

Set defaults to null strings for AWS vars in s3_asset_injector

---

ansible/roles/host-ocp4-hcp-cnv-destroy/tasks/main.yaml

Increase the retries to destroy a HostedCluster, if it fails we ignore errors as we want to continue with the destroy process. HostedClusters will be monitored, and if stays for long time destroying a manual action is required.
host-ocp4-hcp-cnv-destroy Role

[host-ocp4-hcp-cnv-destroy] Increase times and tgnore errors to destroy HostedCluster

---

ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml

On new cluster it sets default UEFI (Secure) as default, trying UEFI as well is making the boot really slow.
This PR is to specify we want to boot with legacy bios.
infra-openshift-cnv-resources Role

[infra-openshift-cnv-resources] Default to BIOS instead UEFI

---

ansible/roles/host-ocp4-hcp-cnv-install/tasks/print_cluster_info.yml

Check every two minutes, 15 times, in total 30 minutes. Before we were just waiting 15 minutes, and in some overload clusters were not enough.

[host-ocp4-hcp-cnv-install] Wait more time for the cluster to be ready

---

ansible/roles/host-ocp4-hcp-cnv-install/defaults/main.yaml
ansible/roles/host-ocp4-hcp-cnv-install/templates/hostedcluster.yaml

External ODF has better performance / features than the kubevirt csi, this change allows to specify the variable **hcp_disable_storage_class** to true to disable configure it.

[host-ocp4-hcp-cnv-install] Enable the option to disable default kubervirt csi

---

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/defaults/main.yml

Adding the default **ocp4_workload_cert_manager_ec2_hostedzoneid** to point to the variable **route53_aws_zone_id**
Role ocp4_workload_cert_manager

[ocp4_workload_cert_manager] Add default ocp4_workload_cert_manager_ec2_hostedzoneid

---

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/files/cm-kustomize-envvar.yaml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/templates/openshift-gitops.yaml.j2
tools/runner/README.md

Since ArgoCD 2.8, configManagementPlugins no longer works, and the sidecar approach is now required.​

Fix openshift gitops kustomize plugin

---

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/defaults/main.yml

Currently only ec2 and gcp are supported.
Platforms we use (equinix, vmware, cnv) are using ec2, so setting as a default
ocp4_workload_cert_manager Role

[ocp4_workload_cert_manager] Defaults to ec2 as cloud_provider

---

.gitignore
ansible/collections/ansible_collections/agnosticd/ai/README.md
ansible/collections/ansible_collections/agnosticd/ai/galaxy.yml
ansible/collections/ansible_collections/agnosticd/ai/meta/runtime.yml
ansible/collections/ansible_collections/agnosticd/ai/plugins/README.md
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/README.adoc
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/defaults/main.yml
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/files/qna.yaml
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/tasks/10-nvidia-customizations.yml
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/tasks/20-developer-customizations.yml
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/tasks/30-instruct-repos.yml
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/tasks/40-instructlab-runtime-setup.yml
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/tasks/main.yml
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_nvidia_cuda/README.adoc
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_nvidia_cuda/defaults/main.yml
ansible/collections/ansible_collections/agnosticd/ai/roles/setup_nvidia_cuda/tasks/main.yml

Creates the skeleton with 2 active roles for the `agnosticd.ai` collection, which can potentially be broken out of the main repo at a later date. 
Gives superior structure and encapsulation than simple roles and allows the addition of role-based collection playbooks e.g
`ansible-playbook agnosticd.ai.setup_ai_stack.yml`, for example
Tested with multiple AI-centric CIs
Modifies .gitignore to allow `agnosticd` collections but no others
ansible/collections/ansible_collections/agnosticd/ai

Create basic agnosticd.ai collection for AI, InstructLab

---

ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml
ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_workers.yaml

With quota enabled by default in the clusters, it is required to specify the limit as well

[host-ocp4-assisted-installer] Add limits to the VMs

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_pool_user.yml

In case to dont be in the same datacenter, some calls can be slow and we need to retry more times
In case to dont be in the same datacenter, some calls can be slow and we need to retry more times
Role ocp4_workload_virt_roadshow_vmware

[ocp4_workload_virt_roadshow_vmware] Increase retries

---

ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_network.yaml

OCP 4.16 requires to be strict with the apiVersion
infra-openshift-cnv-resources role

[infra-openshift-cnv-resources] Add proper apiVersion to NaD

---

ansible/roles/ocp4_machineset_config/tasks/machineset-group-aws.yml

We can define the machineset dynamically, sometimes to disable a machineset we set the maxreplicas to 0
This PR skips the task if the max replicas is 0
AgnosticV reference: https://github.com/rhpds/agnosticv/blob/4168516a7c805fa4eab6f67fac1e44a50f9b4117/sandboxes-gpte/CLOUD_NATIVE_ROBOT/common.yaml#L267
Parameter: https://github.com/rhpds/agnosticv/blob/4168516a7c805fa4eab6f67fac1e44a50f9b4117/sandboxes-gpte/CLOUD_NATIVE_ROBOT/common.yaml#L375
ocp4_machineset_config role

[ocp4_machineset_config] Update machineset-group-aws.yml

---

ansible/configs/osp-on-ocp/post_software.yml
ansible/configs/osp-on-ocp/templates/httpd/ssl.conf

Adds a httpd virtualhost enabling the Nova-NoVNC console to work from within the Openstack deployment. 
This requires a websocket upgrade that isn't in the existing wildcard virtual host.

Adding NovaNoVNC config

---

ansible/roles/aap_pah_cert_issue/defaults/main.yml
ansible/roles/aap_pah_cert_issue/tasks/main.yml

Add zerossl support to pah role
aap_pah_cert_issue
```paste below
```

Add zerossl to PAH

---

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/readme.adoc
ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/templates/clusterrolebinding.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/templates/k10.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/templates/namespace.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/templates/objectbucketclaim.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/templates/rolebinding.yaml.j2

- Fix variable naming (proper workload prefix)
- Add support to set up a demo environment for single-user (cluster-admin) and multi-user

Add support to kasten-k10 workload to set up a demo environment for single (cluster-admin) and multi-user clusters.

---

ansible/roles/host-ocp4-set-facts/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/meta/main.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/readme.adoc
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/tasks/add_user_to_htpasswd_secret.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/tasks/remove_user_from_htpasswd_secret.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/tasks/setup_htpasswd.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/tasks/setup_ldap.yml
ansible/roles_ocp_workloads/ocp4_workload_authentication_htpasswd_user/tasks/workload.yml

Add `ocp4_workload_authentication_htpasswd_user` workload for adding users to a cluster's htpasswd authentication configuration.
Workload role `ocp4_workload_authentication_htpasswd_user`

Add ocp4_workload_authentication_htpasswd_user workload

---

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/workload.yml

I hit this error: https://cert-manager-webhook.cert-manager.svc:443/validate?timeout=30s\\\\\\\\\\": tls: failed to verify certificate: x509: certificate signed by unknown authorit
And it happened in the past, this PR adds a retry
ocp4_workload_cert_manager role

[ocp4_workload_cert_manager] Add retries / delay to Set Up ClusterIssuer task

---

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/pre_workload.yml

Issue with ksushy:
```
TASK [ocp4_workload_telco_hypershift_lab : Ensure ksushy is listening for redfish connections] ***
Tuesday 05 November 2024  05:50:58 +0000 (0:00:02.266)       0:08:42.630 ****** 
fatal: [hypervisor]: FAILED! => {"changed": false, "connection": "close", "content_length": "772", "content_type": "text/html; charset=UTF-8", "date": "Tue, 05 Nov 2024 05:50:59 GMT", "elapsed": 0, "msg": "Status code was 401 and not [200]: HTTP Error 401: Unauthorized", "redirected": false, "server": "Cheroot/10.0.1", "status": 401, "url": "https://xxxx.yyy.vv/vvv/YYYYY-worker0", "www_authenticate": "Basic realm=\"private\""}
```
ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/pre_workload.yml

HCP Telco Lab Fixes required auth for ksushy

---

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml

Increase retry because it failing a lot during summit connect deployment
```
TASK [ocp4_workload_gitea_operator : Create Gitea instance] ********************
fatal: [bastion.h4rl5.internal]: FAILED! => {"changed": false, "msg": "HTTPSConnectionPool(host='api.cluster-XXXX.XXX', port=YYYY): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xYYYYYYYFDc0>: Failed to establish a new connection: [Errno 111] Connection refused'))"}
```
ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
TASK [ocp4_workload_gitea_operator : Create Gitea instance]

Increase retry because it failing a lot during summit connect deployment

---

ansible/roles/install_operator/tasks/install.yml

Installing an operator usually replaces the CSV till get the latest version, this is a race condition situation causing issues.
This PR adds a waiting of 5 minutes in case of failure, and it retries.
install_operator Role

[GPTEINFRA-12416] [install_operator] Retry checking CSV

---

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml

The task "Wait until openshift-gitops ArgoCD instance has been created" has defined an until but not a retries/delay
ocp4_workload_openshift_gitops Role

[GPTEINFRA-12416][ocp4_workload_openshift_gitops] Add missing retries/delay

---

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml

Adding more retries/delay as in some busy environments ArgoCD takes more time
ocp4_workload_openshift_gitops Role

[ocp4_workload_openshift_gitops] Add retries waiting for ArgoCD

---

.gitignore
ansible/action_plugins/agnosticd_odcr.py
ansible/action_plugins/agnosticd_user_info.py
ansible/cloud_providers/ec2_infrastructure_deployment.yml
ansible/completion_callback.yml
ansible/configs/base-infra/default_vars.yml
ansible/configs/base-infra/default_vars_ec2.yml
ansible/configs/base-infra/post_software.yml
ansible/configs/base-infra/pre_software.yml
ansible/configs/base-infra/sample_files/multiple_regions_fallback_with_odcr.yaml
ansible/configs/just-a-bunch-of-nodes/default_vars.yml
ansible/configs/just-a-bunch-of-nodes/default_vars_ec2.yml
ansible/configs/just-a-bunch-of-nodes/sample_vars_multiple_region_retry.yaml
ansible/destroy.yml
ansible/lifecycle.yml
ansible/lifecycle_ec2.yml
ansible/lookup_plugins/agnosticd_user_data.py
ansible/main.yml
ansible/roles-infra/infra-aws-capacity-reservation/tasks/create.yaml
ansible/roles-infra/infra-aws-capacity-reservation/tasks/destroy.yaml
ansible/roles-infra/infra-ec2-template-create/tasks/main.yml
ansible/roles-infra/infra-images/tasks/ec2.yaml
ansible/setup_output_dir.yml
ansible/setup_runtime.yml
ansible/update.yml
docs/User_Info.adoc
training/03_Infrastructure/02_Advanced/03_Understanding_Main_File.adoc

- Add action name prefix to `user-data.yaml`, `user-info.yaml`, `user-body.yaml`.
- Default `agnosticd_user_info` lookup to look in `provision-user-data.yaml`
That allows agnosticd to use user-data from provision, duing destroy or stop/start when:
- developping locally
- agnosticd_restore/save_output_dir  role is used in production

Preserve user-data across run

---

ansible/roles-infra/infra-ec2-template-create/tasks/main.yml

Setting stack_deployed to true, it skips the tasks after the set_fact
infra-ec2-template-create role

[infra-ec2-template-create] Set stack_deployed at the end of the block

---

ansible/roles/host-ocp4-assisted-destroy/tasks/main.yaml

If the service account is not valid, destroying the environment fails here. This can happen if the cluster is reinstalled or other situations where the SA doesnt  xist anymore.
host-ocp4-assisted-destroy role

[host-ocp4-assisted-destroy] Ignore errors for cleanup ceph

---

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/templates/rolebinding-namespace.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/templates/rolebinding.yaml.j2

Users didn't have permissions for their backuptarget namespaces. Adding admin role.
\

Add missing permission on backuptarget namespaces

---

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml

After the cluster is installed, in some strange cases, this task fails (DNS or API not accessible). Adding some retries to fix the problem.

[host-ocp4-assisted-installer] Add retries to find failed installer pods

---

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml

AgnosticV is sending worker_instance_count as string when is a parameter

[host-ocp4-assisted-installer] For worker_instance_count to be an int

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml

Avoid async call and run on background the cluster install
```paste below
```

Avoid async call and run on background

---

ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml

New versions of Execution Environment gets stuck on the wait_for_connection for the VM. This PR adds a task to wait for the VM to be running. This doesn't solve the problem but mitigates it.
infra-openshift-cnv-resources Role

[infra-openshift-cnv-resources] Wait till the VM is running

---

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml

Syntax to annotate the storage class was wrong. Fixed.

Fix annotation for storageclass

---

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml

Fixes cluster deployment task being killed when running in background.
```paste below
```

Fixes 5gran hub cluster deployment

---

ansible/roles/common/tasks/main.yml

update reboot wait time in common, some instances take longer to restart as much as 5 mins
common
```paste below
```

update reboot wait time in common

---

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/create_hypershift_cluster.yml
ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/prep_aws_roles.yaml
ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/awspolicy-hcp-cli-role.json.j2
ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/secret-aws-credentials.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/templates/trust-relationship.json.j2

Added features to enable `hcp` from OCP 4.17, which uses new AWS Roles to control HCP deployments. 
ALSO tested against sandboxes-gpte/hol-ocp-plus development catalog item.  That prod tag can move without calamity.

ocp4_workload_rhacm_hypershift:  Support OCP 4.17 AWS authn

---

ansible/roles_ocp_workloads/ocp4_workload_rhacm_hypershift/tasks/create_hypershift_cluster.yml

ocp4_workload_rhacm_hypershift: use multi-arch release, not x86

---

ansible/roles/ansible_bu_setup_workshop/defaults/main.yml
ansible/roles/ansible_bu_setup_workshop/tasks/common/ansible-navigator.yml
ansible/roles/automation_platform_loader/defaults/main.yml
ansible/roles/automation_platform_loader/tasks/main.yml

1- Added condition to create token to support Ansible Automation Platform 2.5 
Cause: awx.awx.token module doesn't work with AAP2.5 at the moment
2- Updated ansible-bu-setup-workshop role to be compatible with AAP2.5
role: 
- automation_platform_loader 
- ansible_bu_setup_workshop

adding task and condition for aap2.5

---

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml

Supporting multiple cloud providers (CNV/GCP) requires slightly different storage classes.
Adding a data point to AgD user info to provide the actual storage class to showroom.

Add AgD kasten_storageclass variable

---

ansible/roles/ansible_bu_setup_workshop/defaults/main.yml
ansible/roles/ansible_bu_setup_workshop/tasks/common/clone-workshop-content.yml
ansible/roles/ansible_bu_setup_workshop/tasks/rhel.yml

Included task file to for workshop content clone 
Role: ansible-bu-setup-workshop

includ task file

---

ansible/configs/zero-touch-ansible-bu/workloads.yml

Enhanced workloads.yml by adding controllers and capsules group.
config: zero-touch-ansible-bu

Enhanced workloads 

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml

Example on how to auto log into the wetty terminal used the old variable. Fixed.

fix_comment_showroom

---

ansible/roles/install_operator/defaults/main.yml
ansible/roles/install_operator/tasks/install.yml

In some cases we want to still an operator inside a namespace where OperatorGroup exists, this PR is to avoid create the OperatorGroup as if it has different name causes issues.
install_operator role

[install_operator] Add option install_operator_skip_operatorgroup to skip create operatorgroup

---

ansible/roles_ocp_workloads/ocp4_workload_metallb/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_metallb/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_metallb/templates/ipaddresspool.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_metallb/templates/l2advertisement.yaml.j2

Current ocp4 workload just install operator and creates MetalLB object, this PR adds the functionality to add IPAddressPool and L2Advertisement records
ocp4_workload_metallb role

[ocp4_workload_metallb] Add IPAddressPool and L2Advertisement

---

ansible/roles_ocp_workloads/ocp4_workload_hcp_kubevirt/defaults/main.yaml
ansible/roles_ocp_workloads/ocp4_workload_hcp_kubevirt/readme.adoc
ansible/roles_ocp_workloads/ocp4_workload_hcp_kubevirt/tasks/main.yml
ansible/roles_ocp_workloads/ocp4_workload_hcp_kubevirt/tasks/post_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_hcp_kubevirt/tasks/pre_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_hcp_kubevirt/tasks/remove_workload.yml
ansible/roles_ocp_workloads/ocp4_workload_hcp_kubevirt/tasks/workload.yml

This role patches IngressController to accept Wildcard domains
ocp4_workload_hcp_kubevirt role

Add simple ocp4 workload named ocp4_workload_hcp_kubevirt

---

ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml
ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_workers.yaml
ansible/roles/host-ocp4-assisted-installer/vars/main.yaml

Two new variables are added:
ai_masters_extra_disks: []
ai_workers_extra_disks: []
INSTANCENAME text will be replaced with the name of the instance, to avoid duplicate names
Example:
```
ai_workers_extra_disks:
- metadata:
name: "extradiskINSTANCENAME"
spec:
source:
blank: {}
pvc:
accessModes:
- ReadWriteMany
volumeMode: Block
resources:
requests:
storage: "20Gi"
```

[host-ocp4-assisted-installer] Add the option to add extra disks to masters and/or workers

---

ansible/roles/host-ocp4-assisted-installer/files/etcd_disk.yaml

Remove this option, is not needed and causing issues on compact installer

[host-ocp4-assisted-installer] Remove mountOptions

---

ansible/roles/showroom/templates/service_double_tty/tablink_double_tty.j2
ansible/roles/showroom/templates/service_web1/tablink_web1.j2

Clean up tab handling in showroom fixing clash between web_1 and doube_tty (which doesn't need it)
roles/showroom

Clean up tab handling in showroom for codeserver

---

ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_gitops/tasks/workload.yml

Currently is difficult to specify directly the api_version, as you need to specify the internal variable (_ocp4_workload_openshift_gitops_api_version). This PR is to add a new variable called ocp4_workload_openshift_gitops_api_version and if doesnt exist it is using _ocp4_workload_openshift_gitops_api_version
ocp4_workload_openshift_gitops role

[ocp4_workload_openshift_gitops] Add new variable ocp4_workload_openshift_gitops_api_version

---

ansible/roles_ocp_workloads/ocp4_workload_rhacm_cloud_credentials/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_rhacm_cloud_credentials/readme.adoc
ansible/roles_ocp_workloads/ocp4_workload_rhacm_cloud_credentials/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_rhacm_cloud_credentials/templates/kubevirt_ns_and_secret.yaml.j2

ocp4_workload_rhacm_cloud_credentials: add kubevirt support

---

ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml
ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_workers.yaml
ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml
ansible/roles/host-ocp4-assisted-installer/templates/static_network_config_full.j2
ansible/roles/host-ocp4-assisted-installer/vars/main.yaml

This PR allows to use the variables ai_attach_masters_networks and ai_attach_workers_networks to attach the nodes to an existing network

[host-ocp4-assisted-installer] Add functionality to add extra networks

---

ansible/roles-infra/infra-images/defaults/main.yaml

Extend AgnosticD to support RHEL 95 and RHEL AI 1.2 AMIs
roles-infra/infra-images

Add support for RHEL95 and RHELAI 1.2 AMIs

---

ansible/roles_ocp_workloads/ocp4_workload_rhacm_cloud_credentials/templates/kubevirt_ns_and_secret.yaml.j2

Pull secrets in OpenShift secrets when used to deploy HCP clusters are strict about their json formatting.
This fixes the json formatting.

RH1 LAB01 (and ocp4_workload_rhacm_cloud_credentials) - fix pull secret in openshift secret

---

ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/tasks/nfd_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/templates/nodefeature_discovery_cr.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_oai_parasol_insurance/tasks/workload.yaml

Two changes.
1) In the `ocp4_workload_nvidia_gpu_setup`, modify NFD deployment. The operand image version becomes a variable, with the default set at `registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9:v4.17`
2) Parasol deployment workload modified to add an ArgoCD wait/check at the end. That way, the deployment is not finished until everything is properly deployed (no more sync wait time after you receive the go from the demo system).

Parasol: NFD workload fixes + Deployment end check

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/prepare-variables.yaml

We never actually gave lab instructions authors simply the integer of the user in a multi-user environment.
This adds that.
Gerald Nunn wanted it.

ocp4_workload_showroom: add usernum to user_data.user dict

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/prepare-variables.yaml

dedicated cluster orders were failing

set a default num_users for ocp4_workload_showroom

---

ansible/roles_ocp_workloads/ocp4_workload_portworx/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_portworx/tasks/workload.yml

For RH1 Labs add a flag to the portworx workload to not pre-install the operator - yet still create the AWS policy.
ocp4_workload_portworx

Add a flag to portworx workload to not install the operator if so desired

---

ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/tasks/40-instructlab-runtime-setup.yml

This change creates a variable to specify the path of CUDACXX rather than hard coded.
setup_instructlab
```paste below
```

setup_instructlab update CUDACXX location to variable

---

ansible/configs/ocp4-cluster/post_infra.yml

For RH1 with two clouds for each catalog item it may be necessary to adapt the showroom instructions based on the cloud provider selected.
This PR adds the `cloud_provider` variable to the AgnosticD user data so that in showroom some ifdef's can be written depending on which cloud the catalog item was deployed.
ocp4-cluster

Add cloud_provider to AgnosticD User Info for ocp4-cluster

---

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/files/clusterrole-list-nodenetworkconfigurationresources.yaml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/files/clusterrole-list-nodenetworkstates.yaml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/files/clusterrole-network-attachment-admin.yaml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/files/clusterrolebiding-network-attachment-admin.yaml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/files/clusterrolebinding-list-nodenetworkconfigurationresources.yaml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/files/clusterrolebinding-list-nodenetworkstates.yaml
ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/tasks/workload.yml

Allow authenticated users to list network details from the cluster (such as interfaces, bridges, bonds), the NNCP configs and allow users to create NaD (network attach definition)
ocp4_workload_virt_roadshow_multi_user role

[ocp4_workload_virt_roadshow_multi_user] Add the option to allow users to see cluster network configuration and create NaD

---

ansible/configs/ocp4-cluster/default_vars_gcp.yml
ansible/configs/ocp4-cluster/files/cloud_providers/gcp_cloud_template.j2

Make bastion machine type for ocp4-cluster bastion variable and update to n2-standard-2
ocp4-cluster
```paste below
```

Make bastion machine type for ocp4-cluster bastion variable and update to n2-standard-2

---

ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/templates/redhat-datasciencecluster.yaml.j2

The new release of OpenShift AI (stable) introduced new components that can be activated: Kueue and Model Registry.
This PR adds them to the available parameter of `ocp4_workload_openshift_ai`.
Defaults are set to "Removed" so that they are not installed by default in other pre-existing deployments.
`ocp4_workload_openshift_ai`

add kueue and modelregistry configuration to DSC template

---

ansible/roles/showroom/templates/showroom.service.j2

…wroom.service
showroom
```paste below
```

Showroom role, allow user to specify where ansible is executed by the service

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/deploy-showroom-helm.yaml

Currently all the showroom for users using wetty connect to the bastion with the default user (lab-user)
ocp4_workload_showroom role

[ocp4_workload_showroom] Allow SSH with different users (userX) to the bastion

---

ansible/roles_ocp_workloads/ocp4_workload_ols/tasks/remove_workload.yml

Added removal of the app and sp on azure.
```paste below
```

Added removal for Azure App and SP

---

ansible/roles_ocp_workloads/ocp4_workload_metallb/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_metallb/templates/l2advertisement.yaml.j2

Add a new variable called **ocp4_workload_metallb_node_selector** to specify where the metallb should advertise, for example:
```
ocp4_workload_metallb_node_selector: 
- matchLabels:
node-role.kubernetes.io/worker: "" 
```
ocp4_workload_metallb

[ocp4_workload_metallb] RFE to add nodeselectors option to L2Advertisement

---

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/prepare-variables.yaml

It was creating unwanted user_data.users.userX dictionaries

remove generic usernum from showroom

---

ansible/roles_ocp_workloads/ocp4_workload_devops_roadshow/tasks/workload.yml

This adds the subdomain of the cluster to the showroom variables to support substituting it in when creating a pipelinerun in the workshop instead of it being hard coded and requiring the instructor to manually update it.
DEVOPS_ROADSHOW

[DEVOPS_ROADSHOW] Add subdomain var to userdata

---

ansible/roles_ocp_workloads/ocp4_workload_gitops_bootstrap/tasks/workload.yml

If there were no configmaps, it was failing.

ocp_workload_gitops_boostrap: conditionalize cm processing

---

ansible/roles/rad_setup_instructlab/files/antora.yml
ansible/roles/rad_setup_instructlab/files/firefox-rad.desktop
ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml

Fix the git clone issue and add a new shortcut

---

ansible/roles_ocp_workloads/ocp4_workload_platform_engineering_workshop/tasks/openshift_gitops.yml

This step fails occasionally. Adding retries to reduce deployment failures.
ocp4_workload_platform_engineering_workshop
The error that occurs is below. Perhaps Argo CD is not ready in time for the request? 
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'urllib3.exceptions.NewConnectionError'>, <urllib3.connection.HTTPSConnection object at 0x7f97948ab1f0>: Failed to establish a new connection: [Errno 111] Connection refused
```

fix: add retries to pe workshop argocd patch

---

ansible/roles/user-create-ansible-service-account/templates/ssh_config.j2

RHEL AI now has the correct ec2-user (it was cloud-user)
roles/user-create-ansible-service-account

Remove obsolete support for older rhelai

---

ansible/cloud_providers/multi_destroy_env.yml
ansible/configs/minimal/default_vars.yml
ansible/configs/minimal/destroy_env.yml
ansible/configs/minimal/infra.yml
ansible/configs/minimal/noop.yml
ansible/configs/minimal/post_infra.yml
ansible/configs/minimal/post_software.yml
ansible/configs/minimal/pre_infra.yml
ansible/configs/minimal/pre_software.yml
ansible/configs/minimal/software.yml
ansible/configs/minimal/start.yml
ansible/configs/minimal/stop.yml
ansible/roles/host_workloads/README.adoc
ansible/roles/host_workloads/defaults/main.yml
ansible/roles/host_workloads/tasks/main.yml
ansible/roles/host_workloads/tasks/run_workload.yml

Add `host_workloads` role and call from minimal config to allow more powerful configuration of roles and targeting of hosts.
Maintain compatibility with existing configs.
Role host_workloads
Config minimal

Add role host_workloads for minimal config

---

ansible/roles_ocp_workloads/ocp4_workload_habana_gaudi_gpu_setup/tasks/habana_gaudi_operator.yml

Add/Fix retries in ocp4_workload_habana_gaudi_gpu_setup
Workload role ocp4_workload_habana_gaudi_gpu_setup

Add retries for ocp4_workload_habana_gaudi_gpu_setup

---

ansible/roles_ocp_workloads/ocp4_workload_habana_gaudi_gpu_setup/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_habana_gaudi_gpu_setup/tasks/habana_gaudi_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_habana_gaudi_gpu_setup/tasks/kmm_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_habana_gaudi_gpu_setup/tasks/nfd_operator.yml
ansible/roles_ocp_workloads/ocp4_workload_habana_gaudi_gpu_setup/templates/habana-gaudi/habana_gpu_clusterpolicy.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_habana_gaudi_gpu_setup/templates/nfd/nodefeature_discovery_cr.yaml.j2

updated habana role for OCP 4.17 and RHOAI 2.16 and above
```paste below
```

Habana v2 - updated habana role for OCP 4.17 and RHOAI 2.16 and above

---

ansible/roles_ocp_workloads/ocp4_workload_platform_engineering_workshop/tasks/openshift_gitops.yml

Currently, the playbook can proceed even if this Secret check fails, due to it referencing the previously successful step's variable instead of the current `r_secret` variable.
`ocp4_workload_platform_engineering_workshop`
N/A

fix: use correct variable in argocd secret check

---

.github/workflows/build-ee.yml
tools/execution_environments/ee-multicloud-public/install_binaries.sh

- Updated `install_binaries.sh` to dynamically detect system architecture (`ARCH`)
- Modified OpenShift CLI (`oc`) installation to use RHEL 8 version with architecture-specific tarballs.
- Adjusted AWS CLI download URL to include architecture detection.
- Added placeholder for Bitwarden CLI installation, as it does not support ARM64 yet.
ee-multicloud-public

Add multi-platform support for execution environment

---

ansible/roles/open-env-azure-add-user-to-subscription/defaults/main.yml
ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml
ansible/roles/open-env-azure-remove-user-from-subscription/defaults/main.yml
ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml

Add/remove user from azure group that allows management of application developer role
open-env-azure-add-user-from-subscription
```paste below
```

add azure group

---

ansible/configs/test-empty-config/default_vars.yml
ansible/configs/test-empty-config/post_software.yml

- Disable random_string when test_empty_config_passthrough_user_data is provided.
- Add test_empty_config_passthrough_per_user_data to allow setting user data for a range of simulated users.

Improvements to test-empty-config user data vars

---

ansible/roles_ocp_workloads/ocp4_workload_virt_network_config/defaults/main.yml
ansible/roles_ocp_workloads/ocp4_workload_virt_network_config/tasks/workload.yml
ansible/roles_ocp_workloads/ocp4_workload_virt_network_config/templates/nodenetworkconfigurationpolicy-linux-bridge.yaml.j2
ansible/roles_ocp_workloads/ocp4_workload_virt_network_config/templates/nodenetworkconfigurationpolicy-ovs-bridge.yaml.j2

Change virt network workload to allow either linux-bridge or ovs-bridge. Make parameters to each bridge customizable.
ocp4_workload_virt_network_config

Add support for ovs-bridge

---

ansible/roles_ocp_workloads/ocp4_workload_virt_network_config/files/clusterrole-list-nodenetworkconfigurationresources.yaml

Now is only allowing users to list but dont get the information
ocp4_workload_virt_network_config role

[ocp4_workload_virt_network_config] Add "get" to verbs for clusterrole-list-nodenetworkconfigurationresources.yaml

---

ansible/roles/rhel-graphical/tasks/main.yml

TASK [rhel-graphical : Install VNC packages on RHEL 8] *************************
Monday 10 February 2025  06:55:07 +0000 (0:04:58.181)       0:13:32.887 ******* 
fatal: [bastion.xlfrz.internal]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occurred: \n Problem: conflicting requests\n  - nothing provides x2goserver >= 4.1.0.4 needed by xorg-x11-server-x2gokdrive-0.0.0.2-2.el8.x86_64", "rc": 1, "results": []}
```paste below
```

removing xorg package as dependeny not available

---

ansible/roles/set-repositories/tasks/satellite-repos.yml

Remove need for 8443 on satellite HA
```paste below
```

Remove need for 8443 on satellite HA

---

ansible/roles/host-ocp4-assisted-installer/files/network_config.yaml

For advanced networking on OCP on OCP (cnv) we require to enable ipFowarding to Global mode[1]
https://docs.openshift.com/container-platform/4.17/networking/networking_operators/cluster-network-operator.html#nw-cno-enable-ip-forwarding_cluster-network-operator

[host-ocp4-assisted-installer] Enable ipFowarding Global

---

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml
ansible/roles/host-ocp4-assisted-installer/vars/main.yaml

In some cases we would like to install OCP using AI in a existing network. Use case: we want to connect bastion to the same network as the OCP cluster (machine)

[host-ocp4-assisted-installer] Allow the option to install OCP in a existing network

---

ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_network.yaml

Currently default value is 9000. Changed to 1500. This PR allows to specify another value for the mtu too
infra-openshift-cnv-resources role

[infra-openshift-cnv-resources] Change default mtu to 1500 for secondary networks

---

ansible/roles/showroom/tasks/40-showroom-render.yml

This change is to fix the issue with podman-5.2.2 where the default rootless network definition changed.
Role: showroom
```paste below
```

Role: Showroom, add new network definition for ZT items

---

ansible/configs/ocp4-cluster/default_vars_openshift_cnv.yml

For CNV (OpenShift virtualization) we use a layer2 network for the OCP. For advanced networking we require to use the bastion as a gateway. this PR is to allow configure the userdata (i.e. enable ip_forward and masquerade) and the networkdata (to set a static ip) with the variables bastion_userdata and bastion_metadata
ocp4-cluster config

[ocp4-cluster] Allow the option to speciy userdata and networkdata to the bastion (cnv)

---

ansible/collections/ansible_collections/agnosticd/ibm/plugins/action/agnosticd_user_info.py
ansible/collections/ansible_collections/agnosticd/ibm/plugins/module/agnosticd_user_info.py
ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/tasks/main.yml
ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/vars/main.yml

Provides a default "unprovided" value for the `ibmcloud_instructlab_authorization_link` variable that is registered with `agnosticd_user_info` as `display_link` in order to enable the template for agnosticv to show the link only after completing tasks.
ibm_instructlab_service
First of several changes, probably.
No change to Ansible or Python packages. Changes will need to be tested on integration to confirm agnosticd/agnosticv communication functions as desired.

Fix role in ibm_instructlab_service to provide link at the end of the task list
