redhat-cop/agnosticd

docs/Operator_Catalog_Snapshots.adoc
* find the versions of the operators in the catalog snapshots
=> add docs on dumping the catalog snapshot

ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/files/acs-signature-policy.json, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/deploy-insecured.sh.j2, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/deploy-secured.sh.j2
=> Rhtap summit lab 1090: Change deploy script to work on build step

ansible/roles_ocp_workloads/ocp4_workload_camelk/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_camelk/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_camelk/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_camelk/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_camelk/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_camelk/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_camelk/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_camelk/tasks/workload.yml
This role install Red Hat integration Camel K operator
Role: ocp4_workload_camelk
=> New role ocp4_workload_camelk

ansible/roles_ocp_workloads/ocp4_workload_camelk/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_camelk/tasks/workload.yml
Adding default channel 
Role: ocp4_workload_camelk
=> added default channel 

ansible/roles/reset-repositories/README.md, ansible/roles/reset-repositories/tasks/main.yml
This role resets the system repository configuration to the original state a system is installed with.
reset-repositories
```paste below
```
=> New Role to Reset System Repository Configuration

ansible/roles_ocp_workloads/ocp4_workload_external_odf/tasks/workload.yml
Requested by one user I think is a good feature
ocp4_workload_external_odf role
=> [ocp4_workload_external_odf] Enable UI plugin

ansible/cloud_providers/openshift_cnv_infrastructure_deployment.yml, ansible/configs/ansible-lightspeed/default_vars_openshift_cnv.yml, ansible/configs/base-infra/default_vars_openshift_cnv.yaml, ansible/configs/sap-hana/default_vars_openshift_cnv.yaml, ansible/configs/sap-hana/post_software.yml, ansible/configs/sap-hana/software.yml, ansible/configs/zero-touch-base-rhel/default_vars_openshift_cnv.yaml, ansible/roles-infra/infra-openshift-cnv-create-inventory/tasks/authentication.yaml, ansible/roles-infra/infra-openshift-cnv-create-inventory/tasks/create_inventory.yaml, ansible/roles-infra/infra-openshift-cnv-create-inventory/tasks/main.yaml, ansible/roles-infra/infra-openshift-cnv-resources/tasks/authentication.yaml, ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_routes.yaml, ansible/roles-infra/infra-openshift-cnv-resources/tasks/main.yaml, ansible/roles-infra/infra-openshift-cnv-resources/tasks/start_instances.yaml, ansible/roles-infra/infra-openshift-cnv-resources/tasks/stop_instances.yaml, ansible/roles/host-ocp4-assisted-destroy/tasks/main.yaml, ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml, ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_workers.yaml, ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml
To prepare openshift_cnv cloud provider for the new sandbox, we have decided to refactor some of the variables
openshift_cnv cloud_provider and derivated configs and roles
=> Refactoring OCP authentication variables

ansible/configs/rhel-security/default_vars.yml
Add missing required fields to security groups definitions 
rhel-security
=> Fix RHEL Security config by defining required fiels in security groups.

ansible/configs/just-a-bunch-of-nodes/post_software.yml
Added a `when` protected showroom play to post-software just-a-bunch-of-nodes
Summit 2024 and beyond feature
config/just-a-bunch-of-nodes
=> Add Showroom setup task to post_software.yml

ansible/configs/roadshow-ocpvirt/requirements.yml
this is not a role and shouldn't be in this location.
```paste below
```
=> removing  ocp4_aio_workload_cnvlab

ansible/roles/rhel-graphical/tasks/main.yml
=> fixing ansible_dist to 9

ansible/configs/rhel-security/idm.yml, ansible/configs/rhel-security/openscap.yml
=> removing gnome initial setup

ansible/configs/rosa-consolidated/install_additional_tools.yml
ArgoCd CLI tool was missing executable flag.
rosa-consolidate
=> Fix file permissions (missing executable flag) for argocd

ansible/configs/hcp-ocpv/post_software.yml
Updating retries for pre-install operator
ansible/configs/hcp-ocpv/post_software.yml
=> Updating retries for pre-install operator

ansible/roles/windows-ami-finder/README.md, ansible/roles/windows-ami-finder/defaults/main.yml, ansible/roles/windows-ami-finder/tasks/main.yml
New role to find the latest version and AMI ID for windows servers.
windows-ami-finder
```paste below
```
=> New Role To Find Latest Windows AMI

ansible/configs/base-infra/pre_infra.yml, ansible/configs/base-infra/pre_software.yml
Adding code for base-infra to be Windows-ready should it be required. 
It is required already from summit lab LB1401.
base-infra
```paste below
```
=> base-infra Code to enable windows systems if included in instances list

ansible/configs/base-infra/pre_software.yml
typo in FQCN of task
```paste below
```
=> base-infra fix typo

ansible/roles_ocp_workloads/ocp4_workload_pipelines/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_pipelines/tasks/workload.yml
Didn't check if resources was defined before checking its length. Added sanity checks.
Also modernized the code.
=> Add extra checks for pipeline deployment. Modernize code

ansible/configs/rhel-security/selinux1.yml
Updating ansible package name for RHEL9
rhel-security
```paste below
```
=> rhel-security Update ansible package name in setup script

tools/execution_environments/ee-multicloud-public/requirements.yml
Adding the ansible.windows collection to the ee
ee-multicloud-public
```paste below
```
=> Add ansible.windows to ee-multicloud-public reqs.yml

ansible/configs/rhel-security/destroy_env.yml, ansible/configs/rhel-security/post_software.yml
Moving showroom to deploy to ocp cluster as this config creates issues with built-in server hardening.
rhel-security
```paste below
```
=> rhel-security move showroom to ocp deployment

ansible/roles-infra/infra-equinix-metal-resources/tasks/create_instances.yaml
This reverts commit ff555cf081a25da4574bb736068487bd26a0c8e6.
```paste below
```
=> Revert "disabling facility parameter (#7759)"

ansible/configs/roadshow-ocpvirt/requirements.yml, ansible/roles-infra/infra-equinix-metal-resources/meta/main.yaml, ansible/roles-infra/infra-equinix-metal-resources/tasks/create_instances.yaml
Equinix Metal had updated their package to equinix.cloud and old package equinix.metal is depreciated.
ansible/roles-infra/infra-equinix-metal-resources/tasks/create_instances.yaml
ansible/configs/roadshow-ocpvirt/requirements.yml
=> Adding new collection equinix.cloud

ansible/roles-infra/infra-equinix-metal-resources/tasks/create_instances.yaml
"msg": "Unsupported parameters for (equinix.metal.device) module: metro. Update equinix.metal.device to equinix.cloud.metal_device
ansible/roles-infra/infra-equinix-metal-resources/tasks/create_instances.yaml
=> Update equinix.metal.device to equinix.cloud.metal_device

ansible/roles/windows-common/tasks/main.yml, ansible/roles/windows-common/tasks/sshd.yml
windows-common
```paste below
```
=> Update windows-common role for FQCN

ansible/configs/rhel-security/post_software.yml
Update agnosticd_user_info for hosted ocp showroom deploy.
rhel-security
```paste below
```
=> rhel-security update agnosticd_user_info

ansible/roles-infra/infra-dns/tasks/main.yml, ansible/roles-infra/infra-dns/tasks/nested_loop.yml, ansible/roles-infra/infra-equinix-metal-create-inventory/tasks/main.yaml, ansible/roles-infra/infra-equinix-metal-dry-run/tasks/main.yaml, ansible/roles-infra/infra-equinix-metal-resources/tasks/create_instances.yaml, ansible/roles-infra/infra-equinix-metal-resources/tasks/create_project.yaml, ansible/roles-infra/infra-equinix-metal-resources/tasks/delete_instances.yaml, ansible/roles-infra/infra-equinix-metal-resources/tasks/delete_project.yaml, tools/execution_environments/ee-multicloud-public/requirements.txt, tools/execution_environments/ee-multicloud-public/requirements.yml
Equinix Metal package update to EE
EE Update.
tools/execution_environments/ee-multicloud-public/requirements.yml
tools/execution_environments/ee-multicloud-public/requirements.txt
=> Equinix cloud package update from Equinix Metal

ansible/configs/ansible-bu-workshop/post_software.yml
Update the ansible-bu-workshop config with showroom enablement.
```paste below
```
=> ansible-bu-workshop ad showroom

ansible/roles-infra/infra-equinix-metal-resources/tasks/delete_instances.yaml
loop: r_equinix_metal_devices.json.devices | default([])
to
loop: "{{ r_equinix_metal_devices.json.devices | default([]) }}"
https://redhat-internal.slack.com/archives/D06D2LWLN4S/p1712078863411379
https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles-infra/infra-equinix-metal-resources/tasks/delete_instances.yaml#L20
=> Update delete_instances.yaml - JK fix for deletes

ansible/configs/sap-hana/software.yml
fatal: [hana-8jcqv1]: FAILED! => {"changed": true, "cmd": ["mv", "/var/lib/insights/newest.egg", "/tmp"], "delta": "0:00:00.005855", "end": "2024-04-02 16:10:52.561117", "msg": "non-zero return code", "rc": 1, "start": "2024-04-02 16:10:52.555262", "stderr": "mv: cannot stat '/var/lib/insights/newest.egg': No such file or directory", "stderr_lines": ["mv: cannot stat '/var/lib/insights/newest.egg': No such file or directory"], "stdout": "", "stdout_lines": []}
```paste below
```
=> adding ignore_errors: true

ansible/configs/ansible-bu-workshop/default_vars.yml, ansible/roles/ansible_bu_setup_workshop/templates/hosts/ripu.j2, ansible/roles/ansible_bu_setup_workshop/templates/student-99-webui.json.j2
Update jinja templates for petnames and splunk credential_type
```paste below
```
=> ansible-bu-workshop petname templates and splunk additions

ansible/roles/ansible_bu_setup_workshop/templates/student-99-webui.json.j2
ansible_bu_workshop
```paste below
```
=> ansible_bu_workshop role Update variable definitions

ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/meta/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/tasks/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/tasks/post_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/tasks/pre_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/tasks/remove_workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/tasks/workload.yaml
Create new role to deploy single application set bootstrap using ArgoCD
Create new role to deploy single application set bootstrap using ArgoCD
```paste below
```
=> Added Role to deploy applicationset using ArgoCd

ansible/configs/base-infra/files/hosts_template.j2
=> base-infra config update hosts if windows in inventory_groups

ansible/roles/ansible_bu_setup_workshop/tasks/ripu.yml
ansible_bu_setup_workshop 
```paste below
```
=> ansible_bu_setup_workshop role fix var indentation

ansible/configs/ansible-bu-workshop/post_software.yml
=> ansible-bu-workshop fix showroom to deploy on bastion

ansible/roles/ansible_bu_setup_workshop/tasks/common/fetch_instances_info.yml, ansible/roles/ansible_bu_setup_workshop/tasks/ripu.yml
=> ansible_bu_setup_workshop add set_fact

ansible/configs/odf-dr-binder/post_software.yml
Replaced bookbag with showroom 
config: odf-dr-binder
=> added showroom

ansible/roles/ansible_bu_setup_workshop/templates/hosts/ripu.j2
Template had type for variable
```paste below
```
=> Typo in template

ansible/roles_ocp_workloads/ocp4_workload_rhdh/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhdh/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_rhdh/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhdh/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhdh/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhdh/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhdh/tasks/workload.yml
RHDH role to install RHDH via operator hub 
=> RHDH Operator role creation

ansible/configs/ocp4-cluster/destroy_env.yml, ansible/configs/ocp4-cluster/post_software.yml
Remove - consensus seems to be that this should run as infra_workload
=> Remove Showroom setup from ocp4-cluster config

ansible/roles_ocp_workloads/ocp4_workload_rhacs/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs/templates/central.yaml.j2
Change variable to enable v4 scanner in RHACS to be a bool instead of a string.
Fix ansible-lint errors/warnings where quickly possible.
ocp4_workload_rhacs
=> Make v4 scanner var bool. Fix ansible-lint errors and warnings where possible.

ansible/configs/ansible-bu-workshop/post_software.yml
ansible-bu-workshops
```paste below
```
=> ansible-bu-workshops fix user data in post_software.yml

ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/tasks/workload.yaml
Adding loop to the task to use multiple bootstrapping repositories.
Role: ocp4_workload_argocd_bootsrap
=> Argocd bootstrap 

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_quay.yml
Added until loop to put some delay
Role: ocp4_workload_redhat_developer_hub_bootstrap
=> add until loop for retry

ansible/roles/ansible_bu_setup_workshop/templates/student-99-webui.json.j2
ansible_bu_setup_workshop
```paste below
```
=> ansible_bu_setup_workshop update cockpit template

ansible/configs/test-empty-config/destroy_env.yml, ansible/configs/test-empty-config/post_software.yml, ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/deploy-showroom-helm.yaml
=> Enable NoVNC client on OCP Showroom

ansible/roles/automation_platform_loader/tasks/main.yml
Adding until and retries to awx.awx.token task
role: automation_platform_loader
=> adding retries to the token task

ansible/roles/ansible_bu_setup_workshop/templates/student-99-webui.json.j2
ansible_bu_setup_workshop
```paste below
```
=> ansible-bu-setup-workshop Update template to use r_instances_info

ansible/configs/ansible-bu-workshop/post_software.yml, ansible/configs/ansible-bu-workshop/pre_infra.yml
=> ansible-bu-workshop move roles to workload role definitons

ansible/roles/common/tasks/main.yml
update the common role for updating specific package functionality.
ansible/roles/common
```paste below
```
=> common role, update to add specific package updates

ansible/roles/common/tasks/main.yml
roles/common
```paste below
```
=> common role bugfix for defaulted variable

ansible/configs/multi-cloud-odf-binder/files/cloud_providers/ec2_cloud_template.j2
SUMMARY
Fix EIP issues on Configs with Custom CloudFormation templates due to AWS change overnight.
ISSUE TYPE
=> Ipdating custom CF files CI's with EIP setup per PM

ansible/configs/rhel9-workshop/post_software.yml
=> updating ssh_password to bastion_ssh_password

ansible/roles/automation_platform_loader/tasks/main.yml
Fix regression introduced by d76bbc219f. 
Create a new AAP2 Auth token using controller username/password
It's a boolean, not a string. :wink:
=> change string to boolean

ansible/roles/asset_injector/README.adoc, ansible/roles/asset_injector/tasks/main.yml
Enhance asset-injector to do capabilities.
(Equinix needs to add capability: cap_setuid+ep  capability: cap_setgid+ep for example)
role/asset_injector
=> Asset injector capabilities 01

ansible/roles/asset_injector/defaults/main.yml
set asset_injector_assets: [] as default - safe exit if called whilst unset
=> Add safe default to asset_injector role

ansible/configs/experience-ocpvirt/requirements.yml
The experience-ocpvirt used the wrong equinix collection.
=> Change equinix collection from equinix.metal to equinix.cloud

ansible/configs/rhel9-workshop/post_software.yml
Reverts redhat-cop/agnosticd#7836
=> Revert "updating ssh_password to bastion_ssh_password"

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_gitlab.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_gitlab.yml
=> RHDH: Set max number of users on get

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_gitlab.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_gitlab.yml
=> Summit lab-1990: check for gitlab job completion

ansible/roles/agnosticv-userdata-import/README.md, ansible/roles/agnosticv-userdata-import/defaults/main.yml
agnosticv-userdata-import
```paste below
```
=> agnosticv-userdata-import fix role to use yaml instead of JSON. Update readme to reflect changes.

CODEOWNERS
Add most important configs to require core approval:
- ocp4-cluster
- rosa-consolidated
CODEOWNERS
=> Added ocp4-cluster and rosa-consolidated to core approvals

ansible/configs/acs-wksp-binder/README.adoc, ansible/configs/acs-wksp-binder/default_vars.yml, ansible/configs/acs-wksp-binder/default_vars_ec2.yml, ansible/configs/acs-wksp-binder/destroy_env.yml, ansible/configs/acs-wksp-binder/infra.yml, ansible/configs/acs-wksp-binder/post_infra.yml, ansible/configs/acs-wksp-binder/post_software.yml, ansible/configs/acs-wksp-binder/pre_infra.yml, ansible/configs/acs-wksp-binder/pre_software.yml, ansible/configs/acs-wksp-binder/requirements.yml, ansible/configs/acs-wksp-binder/sample_vars.yml, ansible/configs/acs-wksp-binder/software.yml, ansible/configs/acs-wksp-binder/stop.yml
=> [WIP: DO not Merge] LB1208 Binder config

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/create_devspace_user_namespaces.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/fetch_and_apply_template.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_backstage_repo.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_devspaces.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_gitlab.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_gitlab_runner.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_rhsso.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_stackrox.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_templates.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/application-backstage-gitops.yml.j2
=> RHDH-TAP: update tap role to vault pull secret

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_gitlab.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/workload.yml
=> RHDH-TAP: Undo copy paste error

ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
fix blank azure cost center on delete
```paste below
```
=> fix blank azure cost center

ansible/configs/experience-ocpvirt/default_vars_equinix_metal.yml, ansible/configs/experience-ocpvirt/post_software.yml, ansible/configs/experience-ocpvirt/templates/configureMTV.sh.j2, ansible/configs/experience-ocpvirt/vcenter-remove-vm.yml, ansible/configs/experience-ocpvirt/vcenter-remove-webapp-vms.yml, ansible/configs/experience-ocpvirt/vcenter-remove_access.yml, ansible/configs/experience-ocpvirt/vcenter-setup-user.yml, ansible/configs/experience-ocpvirt/vcenter-setup-webapp-vms.yml
There was a mismatch of system and student user for LB2096. Hopefully this cleans that up.
experience_ocpvirt
=> Fix wrong user creation for vmware

ansible/configs/experience-ocpvirt/default_vars_equinix_metal.yml, ansible/configs/experience-ocpvirt/vcenter-setup-user.yml
Somehow username was not picked up from defaults file. Setting in logic.
=> Set username in logic

ansible/configs/experience-ocpvirt/templates/configureMTV.sh.j2, ansible/configs/experience-ocpvirt/vcenter-remove_access.yml, ansible/configs/experience-ocpvirt/vcenter-setup-user.yml
Hopefully this fixes the vmware user creation for real.
=> Hopefully fix vmware user for real

ansible/configs/experience-ocpvirt/post_software.yml, ansible/configs/experience-ocpvirt/software.yml
Update AgnosticD output for VMware user.
Remove commented out code.
=> Proper output for VMware user

ansible/configs/experience-ocpvirt/vcenter-remove_access.yml, ansible/configs/experience-ocpvirt/vcenter-setup-user.yml
=> Set student user for destroy

ansible/configs/experience-ocpvirt/templates/configureMTV.sh.j2
=> Fix variable

ansible/roles/ansible_bu_setup_workshop/tasks/auto_satellite.yml
Include `extra_vars: refresh_satellite_manifest: true`
ansible/roles/ansible_bu_setup_workshop/tasks/auto_satellite.yml
=> Include extra_vars: refresh_satellite_manifest: true

ansible/configs/experience-ocpvirt/default_vars_equinix_metal.yml, ansible/configs/experience-ocpvirt/vcenter-remove-vm.yml, ansible/configs/experience-ocpvirt/vcenter-remove-webapp-vms.yml, ansible/configs/experience-ocpvirt/vcenter-remove_access.yml, ansible/configs/experience-ocpvirt/vcenter-setup-user.yml, ansible/configs/experience-ocpvirt/vcenter-setup-webapp-vms.yml
Somehow VCenter user didn't have access to the folder. Using a shorter folder name seems to work better.
=> Change VCenter folder.

ansible/configs/rhel-security/openscap.yml
New package required when updating to RHEL 9
rhel-security
```paste below
```
=> rhel-security update openscap packages list

ansible/roles/ocp4-workload-workshop-admin-storage/files/workshop-settings.j2, ansible/roles/ocp4-workload-workshop-admin-storage/tasks/pre_workload.yml
https://github.com/redhat-cop/agnosticd/pull/7314/files
```paste below
```
=> reverting the code change for bastion_fqdn

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
Missing firewall Python library
```paste below
```
=> Adds firewall python library

ansible/configs/base-infra/workloads.yml
Update workloads.yml to include all:!localhost option
base-infra
```paste below
```
=> base-infra update workloads.yml definitions

ansible/roles/ansible_idm_setup_lab/tasks/host-definition.yml, ansible/roles/ansible_idm_setup_lab/templates/ansible_hosts.j2, ansible/roles/ansible_idm_setup_lab/templates/etc_hosts.j2
ansible_idm_setup_lab
```paste below
```
=> ansible_idm_setup_lab fix for variable pulls and new hostnames

ansible/roles/ansible_idm_setup_lab/tasks/host-definition.yml
ansible_idm_setup_lab
```paste below
```
=> ansible_idm_setup_lab update variables for set_facts

ansible/roles/ansible_idm_setup_lab/tasks/host-definition.yml, ansible/roles/ansible_idm_setup_lab/templates/etc_hosts.j2
The template had a messy output, vars contained extra spaces.
```paste below
```
=> ansible_idm_setup_lab improve templates and remove spaces from vars

ansible/roles_ocp_workloads/ocp4_workload_smartvillage/tasks/workload.yml
=> SUMMIT lb2480  Update workload.yml

ansible/roles_ocp_workloads/ocp4_workload_smartvillage/tasks/workload.yml
switching to kubernetes.core.k8s
=> Update workload.yml - summit smartvillage

ansible/configs/rosa-consolidated/post_software.yml
Workloads still don't deploy. Reverting until thinking of a better solution.
=> Revert adding check to workloads

ansible/configs/ocp4-disconnected/post_infra.yml
Adding some quality of life improvements to ocp4-disconnected around easy ssh access between nodes
ocp4-disconnected
=> ocp4-disconnected: adding /etc/hosts and ssh key configuration

ansible/configs/equinix-baremetal-node/post_software.yml
Allow config to use showroom-shared
configs/equinix-baremetal-node
=> Add shared showroom capability to equinix-baremetal-node

ansible/configs/just-a-bunch-of-nodes/post_software.yml
Add shared ocp showroom to just-a-bunch-of-nodes
configs/just-a-bunch-of-nodes
=> Add Showroom deployment in post software tasks

ansible/roles/asset_injector/README.adoc, ansible/roles/asset_injector/tasks/main.yml
Extend asset-injector role to do users (simple use cases ideally)
=> Add user management in asset injector role

ansible/configs/ocp4-cluster/default_vars_vmware_ibm.yml, ansible/configs/ocp4-cluster/destroy_env_vmware_ibm.yml, ansible/configs/ocp4-cluster/vmware_ibm_instances_start.yaml, ansible/configs/three-tier-app/default_vars_vmware_ibm.yml
three-tier-app and ocp4-cluster
while the provider for vmware_ibm was created, no updates were done to allow those roles to function in the intended configs.  This commit will provide a set of default vars for testing to make sure the vmware_ibm role works as-expected.
=> Create vmware_ibm default vars for ocp4-cluster and three-tier-app

ansible/configs/base-infra/files/hosts_template.j2
=> base-infra update windows vars in hosts_template

ansible/configs/roadshow-ocpvirt/templates/configureMTV.sh.j2
=> adding forklift-controller

ansible/configs/roadshow-ocpvirt/post_software.yml
when: preinstall_operators | default(False)
```paste below
```
=> adding when command in Execut Import.sh.j2

ansible/configs/tap-workshop-binder/requirements.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/workload.yml
=> ADDED FQCN

ansible/configs/tap-workshop-binder/requirements.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/validate-insecured.sh.j2, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/validate-secured.sh.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_rekor.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_artifact_signer/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_artifact_signer/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_artifact_signer/templates/tas-secure-sign.yml.j2
=> RHTAS: move operator to v1.0.0

ansible/configs/rhel-security/sessionrecording.yml, ansible/roles/rhel-security-verification/tasks/sessionrecording-verify.yml
Fixes missing package requirement in RHEL Security / Session Recording lab
=> Required explicit sssd-proxy installation

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_backstage.yml
As per request from developer advocates, a new rhdh console link will be available on the openshift console
RHDH
=> RHDH: Include rhdh link to openshift console

ansible/roles-infra/infra-windows-connection-facts/defaults/main.yml, ansible/roles-infra/infra-windows-connection-facts/tasks/main.yml
Some variables had typos in the initial commit. This PR resolves those issues.
infra-windows-connection-facts
```paste below
```
=> infra-windows-connection-facts correct var typos

ansible/configs/ocp4-cluster/default_vars_vmware_ibm.yml, ansible/configs/ocp4-cluster/destroy_env_vmware_ibm.yml, ansible/configs/ocp4-cluster/vmware_ibm_instances_start.yaml, ansible/configs/ocp4-upi-vmc/default_vars_vmware_ibm.yaml, ansible/configs/ocp4-upi-vmc/post_infra_vmware_ibm.yml, ansible/configs/ocp4-upi-vmc/post_software_vmware_ibm.yml, ansible/configs/ocp4-upi-vmc/software_vmware_ibm.yml, ansible/configs/ocp4-upi-vmc/vmware_ibm_destroy_env.yml, ansible/configs/three-tier-app/default_vars_vmware_ibm.yml
add more vmware_ibm variables
ocp-upi-vmc
instances variable with cloud_provider vmware_ibm fails due to undefined variable "instances"
=> Create vmware_ibm default vars for ocp4-upi-vmc

ansible/roles-infra/infra-windows-connection-facts/tasks/main.yml
…lues from defaults
infra-windows-connection-facts
```paste below
```
=> infra-windows-connection-facts update main.yml to properly pull vars

ansible/configs/ansible-bu-workshop/files/cloud_providers/ec2_cloud_template.j2
`ansible/roles-infra/infra-ec2-template-generate/templates/cloud_template.j2` used as the initial source for `ansible/configs/ansible-bu-workshop/files/cloud_providers/ec2_cloud_template.j2` with additional if section added for EBS Iops and Throughput tuning parameters when defined and instance name is "satellite".
ansible/configs/ansible-bu-workshop
=> Initial revision for ec2_cloud_template.j2 under ansible/configs/ansible-bu-workshop

ansible/configs/base-infra/pre_software.yml, ansible/roles-infra/infra-windows-connection-facts/defaults/main.yml, ansible/roles/ansible_idm_setup_lab/templates/ansible_hosts.j2
=> Update for roles concerning LB1401

ansible/configs/sandbox/post_software_vmc.yml, ansible/configs/sandbox/post_software_vmware_ibm.yml
Set vcenter proxy for vmc on aws
sandbox
```paste below
```
=> Set vcenter proxy

ansible/roles-infra/infra-vmc-resources/tasks/create_additional_public_ips.yaml, ansible/roles-infra/infra-vmc-resources/tasks/create_segment.yaml, ansible/roles-infra/infra-vmc-resources/tasks/delete_additional_public_ips.yaml
fix ipaddr in vmware sandbox
sandbox
```paste below
```
=> fix ipaddr in vmware sandbox

ansible/roles_ocp_workloads/ocp4_workload_trusted_artifact_signer/files/keycloak-client.yml
=> RHTAS: gitsign compatibilty with keycloak

ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/deploy-insecured.sh.j2
=> SMTLB 1090: Fix logging message

ansible/configs/ansible-bu-workshop/files/cloud_providers/ec2_cloud_template.j2
Ensure that EbsOptimized is enabled for Satellite instances with ansible-bu-workshop deployments.
ansible/configs/ansible-bu-workshop
=> ansible/configs/ansible-bu-workshop ec2_cloud_template.j2 include EbsOptimized: true

ansible/roles_ocp_workloads/ocp4_workload_summit_2024_cloud_native_camel/README.md, ansible/roles_ocp_workloads/ocp4_workload_summit_2024_cloud_native_camel/templates/kafka-console-template.yaml.j2
Fixing AMQ Streams Console version
ocp4_workload_summit_2024_cloud_native_camel
=> fixing AMQ Streams Console version

ansible/configs/ocp4-disconnected/.yamllint, ansible/configs/ocp4-disconnected/post_infra.yml
Fixes for ocp4-disconnected in multiple regions as well as some quality of life fixes
- Fix assumptions around region deployments, allow for us-west-2
- Reordering node configuration to first do bastion to fix a race conditional failure
- support for configuring the highside host
ocp4-disconnected
=> ocp4-disconnected: bugfixes and QOL

ansible/configs/ocp4-disconnected/post_infra.yml
bugfix for s3 bucket retry
ocp4-disconnected
=> ocp4-disconnected: add support for retry when creating s3 bucket

ansible/configs/ocp4-disconnected/post_infra.yml
bugfix for s3 bucket retry
ocp4-disconnected
=> Revert to ansible retry

ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/tasks/workload.yml
Adds retries to check deployment tasks to help with Summit load testing for workshop
Argo Rollouts Workshop
=> Argo Rollouts Workshop: Add retries to check tasks

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/rhdh/application_rhdh_deploy.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/templates/rhdh/application_rhdh_deploy.yaml.j2
=> Fix the RHDH pull secret in LB1223

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/rhdh/application_rhdh_deploy.yaml.j2
=> revert the secret in rhdh

ansible/configs/ansible-bu-workshop/files/cloud_providers/ec2_cloud_template.j2, ansible/roles-infra/infra-ec2-template-generate/tasks/main.yml
ansible/configs/ansible-bu-workshop
The CloudFormation object AWS::EC2::Instance object has a bug where the Throughput setting for EBS volumes can not be set, however, the AWS::EC2::LaunchTemplate object does. So a AWS::EC2::LaunchTemplate object is introduced for the Satellite instances for workshop deployments, along with a matching AWS::EC2::Instance object to launch Satellite instances with the proper EBS settings for IOPS and Throughput.
=> Ansible workshop CloudFormation template modifications for Red Hat Satellite

ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/validate-insecured.sh.j2, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/validate-secured.sh.j2
=> RHTAS: Use forked version of default policy

ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/setup_ec.yml
=> RHTAS: Use CLI image for EC as public CLI is unstable

ansible/roles/ai_setup_nvidia_cuda/README.adoc, ansible/roles/ai_setup_nvidia_cuda/defaults/main.yml, ansible/roles/ai_setup_nvidia_cuda/tasks/main.yml
Installs Nvdia GPU drivers and CUDA from their official repos on:
- RHEL 9
- Fedora
Also ensures popular AI tooling is installed.
roles/ai_setup_nvidia_cuda
=> Create a role to install nvidia/cuda stack on RHEL and Fedora

ansible/roles/install_operator/tasks/install.yml
=> adding until task from old working tag

ansible/roles_ocp_workloads/ocp4_workload_openshift_container_storage/tasks/install_operator.yml
Reverts redhat-cop/agnosticd#7987
=> Revert "Update install_operator.yml"

ansible/roles/install_operator/tasks/install.yml
Reverts redhat-cop/agnosticd#7988
=> Revert "adding until task from old working tag"

ansible/configs/convert-to-rhel-azure-arc/files/convert_to_rhel.yaml, ansible/configs/convert-to-rhel-azure-arc/post_software.yml, ansible/configs/convert-to-rhel-azure-arc/templates/deploy_arc.yaml.j2
This summit lab 2005 is more fun when there's ansible playbooks to do the remote convert2rhel
this implements that
```paste below
```
=> Judd lb2005 add arc playbook

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/tasks/workload.yml
=> remove gitea and postgres VMs in LB1223

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/tasks/workload.yml
=> fix the gitea issue in lb1223

ansible/roles/ai_setup_ilab/README.adoc, ansible/roles/ai_setup_ilab/defaults/main.yml, ansible/roles/ai_setup_ilab/tasks/main.yml
Sets up Instruct Lab (ilab) on a VM - assumes Nvidia CUDA (see associated ai_setup_nvidia_cuda role)
=> Base ai_setup_ilab role

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/tasks/workload.yml
=> Fix gitea cicd in lb1223

ansible/roles/ai_setup_ilab/tasks/main.yml
Role originally written for Fedora - this makes it RHEL agnostic
=> Fixes removing fedora user fro ai_setup_ilab

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/defaults/main.yaml
=> revert the gitea repo var

ansible/roles/asset_injector/tasks/main.yml
New requirement implemented - option to allow groups to be added to user
=> Add groups to asset injector user capability

ansible/roles/ai_setup_ilab/tasks/main.yml
Optimizations for setting up InstructLab 
=> Ai setup ilab and venv config

ansible/roles/ai_setup_ilab/tasks/main.yml
shell executes command in place generating correctly positioned config.yaml
=> Move ilab cmds to single shell v multiple commands

ansible/roles/ai_setup_ilab/tasks/main.yml
Fix: simple name of merlinite LLM 
=> Rename LLM to include -lab-

tools/execution_environments/ee-multicloud-public/requirements.yml
Update requirements.yml to add infra.eda_configuration
tools/execution_environments/ee-multicloud-public/requirements.yml
=> Update requirements.yml to add infra.eda_configuration

ansible/roles/asset_injector/tasks/main.yml
Extend copy functionality of asset-injector to remote_src
=> Extend asset-injector copy to allow remote_src

ansible/roles/ai_setup_ilab/defaults/main.yml, ansible/roles/ai_setup_ilab/tasks/main.yml
Conditional logic to allow
- Pulling the LLMs in
- Pulling various images in
=> Enhance ai_setup_ilab with developer preview options for fine tuning

ansible/configs/experience-ocpvirt/files/configure_operators.sh
This shell script really needs to be rewritten to do all this in ansible so we can do normal retry logic.
Right now this is just a quick fix to allow apis to come up for webhooks to give us a better chance of success.
Config experience-ocpvirt
=> Add sleep to experience-ocpvirt shell script

ansible/roles/ocp4-workload-quarkus-workshop/files/community-operators-index.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/devspaces_cr.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/redhat-operators-index.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/stack.Dockerfile, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/workload.yml
Upgrade RHBQ 3.8, OpenShift 4.15, Dev Spaces 3.13 in Quarkus Workshop
```paste below
```
=> Upgrade RHBQ 3.8, OpenShift 4.15, Dev Spaces 3.13 in Quarkus Workshop

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/defaults/main.yml
=> update Hosted Control Plane lab to 4.15

ansible/configs/ibm-rhoic/README.adoc, ansible/configs/ibm-rhoic/auth_sandbox.yml, ansible/configs/ibm-rhoic/default_vars.yml, ansible/configs/ibm-rhoic/destroy_env.yml, ansible/configs/ibm-rhoic/infra.yml, ansible/configs/ibm-rhoic/post_infra.yml, ansible/configs/ibm-rhoic/post_software.yml, ansible/configs/ibm-rhoic/pre_infra.yml, ansible/configs/ibm-rhoic/pre_software.yml, ansible/configs/ibm-rhoic/software.yml, ansible/roles-infra/sandbox-ibm/tasks/create_access.yml, ansible/roles-infra/sandbox-ibm/tasks/create_rhoic_access_groups.yml, ansible/roles-infra/sandbox-ibm/tasks/create_rhoic_policies.yml, ansible/roles-infra/sandbox-ibm/tasks/create_rhoic_ui_access.yml, ansible/roles-infra/sandbox-ibm/tasks/main.yml, ansible/roles-infra/sandbox-ibm/tasks/remove_access.yml, ansible/roles-infra/sandbox-ibm/tasks/remove_rhoic_access.yml, ansible/roles-infra/sandbox-ibm/tasks/remove_rhoic_access_groups.yml, ansible/roles-infra/sandbox-ibm/tasks/remove_rhoic_ui_access_groups.yml
I updated A LOT of fqcn.  And fixed up the config so it actually works.
=> ibm_rhoic: refresh round 2

ansible/roles_ocp_workloads/ocp4_workload_blackhat_secured_container_pipelines/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_blackhat_secured_container_pipelines/tasks/setup_cosign.yml
=> Blackhat RSA2024: Create new cosign download link

ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/files/grafana_dashboard_jvm.yml.json, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/files/grafana_dashboard_performance.yml.json, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/files/grafana_dashboard_workload.yml.json, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_crunchy_postgres.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_devspaces.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_grafana.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_hyperfoil.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_image_puller.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_logging_loki.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_noobaa.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_serverless.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_sonatype_nexus.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/tasks/install_tekton.yml, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/devspace_cluster.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/grafana_binding.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/grafana_datasource.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_performance_monitoring/templates/grafana_instance.yml.j2
Upgrade Operators to the latest version using CatalogSource snapshots.
Role `ocp4_workload_performance_monitoring`
This PR upgrades some operators' versions to make this workload work on newer versions of Openshift. It also makes use of snapshot CatalogSources to avoid issues during cluster upgrades.
```bash
ansible [core 2.16.5]
config file = /Users/rsoares/dev/github/redhat-na-ssa/agnosticd/ansible.cfg
configured module search path = ['/Users/rsoares/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /opt/homebrew/Cellar/ansible/9.4.0/libexec/lib/python3.12/site-packages/ansible
ansible collection location = /Users/rsoares/.ansible/collections:/usr/share/ansible/collections
executable location = …
```
=> Mod cn 2024 upgrade

ansible/configs/ocp4-getting-started-rosa/workloads.yml
=> comment out Check if demo failed installation

ansible/configs/ocp4-getting-started-rosa/destroy_env.yml
=> adding amazon.aws.cloudformation

ansible/configs/ocp4-getting-started-rosa/destroy_env.yml
=> fixing destroy_env in ocp4_getting_started_wksp_rosa

tools/execution_environments/ee-multicloud-public/requirements.yml
see #7894
PR to cut a new release candidate **v0.1.2-rc.2**  
bugfix: Incorporate the hotfix for equinix-metal and update collections and modules. see https://github.com/redhat-cop/agnosticd/pull/7894
- EE Pull request
ee-multicloud  public  EE
=> EE v0.1.2-rc.2 Add equinix.metal new collection

ansible/roles_ocp_workloads/ocp4_workload_cockroach_dbaas_amq_lab/tasks/remove_workload.yml
Fix destroy for cockroach lab
ocp4_workload_cockroach_dbaas_amq_lab
```paste below
```
=> Fix destroy for cockroach lab

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-guides.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml
=> Fix the redis in Quarkus workshop

ansible/roles/ai_setup_ilab/tasks/main.yml
Optionally turns off some the `ai_setup_ilab` role features
=> Tweak role ai_setup_ilab to do optional summit2024 configuration

ansible/configs/ocp4-getting-started-aro/workloads.yml
=> reverting workload changes

ansible/roles/ai_setup_ilab/tasks/main.yml
Make the role more conditional so that it can be used to deploy different scenarios
=> Enhance ialb role for Summit2024 usecase

ansible/roles/ai_setup_ilab/files/qna.yaml, ansible/roles/ai_setup_ilab/tasks/main.yml
More tweaks to the ai_setup_ilab role, making it summit 2024 lab-friendly
=> More summit 2024 additions for ai_setup_ilab

ansible/roles/ai_setup_ilab/tasks/main.yml
=> MInor fix - ai_setup_ilab role

Makefile, ansible/roles/ai_setup_ilab/tasks/main.yml
Improve the paths, dir structure and model location
=> Optimizations for instructlab and model location

ansible/roles/ai_setup_ilab/tasks/main.yml
ai_setup_lab - ensure instruct user owns all assets and LLMs
=> Ensure instruct user owns all assets

ansible/roles/ai_setup_ilab/tasks/main.yml
Move the role to use the Granite model from instructlab
=> Swap models for ai_setup_ilab

ansible/roles_ocp_workloads/ocp4_workload_trusted_artifact_signer/tasks/workload.yml
=> RHTAS Operator: Disable auto approve

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-rhsso-backstage.yml.j2
=> RHDH: pin rhsso version

ansible/roles_ocp_workloads/ocp4_workload_aws_efs_operator/README.md, ansible/roles_ocp_workloads/ocp4_workload_aws_efs_operator/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_aws_efs_operator/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_aws_efs_operator/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_aws_efs_operator/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_aws_efs_operator/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_aws_efs_operator/tasks/workload.yml
=> AWS EFS: Initial commit

ansible/roles_ocp_workloads/ocp4_workload_aws_efs_operator/tasks/workload.yml
=> storage class wait

ansible/roles_ocp_workloads/ocp4_workload_aws_efs_operator/tasks/workload.yml
=> EFS: Add wait for storage class initialization

ansible/roles_ocp_workloads/ocp4_workload_aws_efs_operator/tasks/workload.yml
=> Ocp virt efs operator 3

ansible/roles/ai_setup_ilab/defaults/main.yml, ansible/roles/ai_setup_ilab/tasks/main.yml
Python and LLM runtime is highly changeable, which makes it more flexible and easier to revise.
=> Make the llama LLM runtime version a var for ease of revision

ansible/roles_ocp_workloads/ocp4_workload_metallb/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_metallb/files/metallb.yaml, ansible/roles_ocp_workloads/ocp4_workload_metallb/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_metallb/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_metallb/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_metallb/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_metallb/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_metallb/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_metallb/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_nmstate/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_nmstate/files/nmstate.yaml, ansible/roles_ocp_workloads/ocp4_workload_nmstate/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_nmstate/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_nmstate/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_nmstate/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_nmstate/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_nmstate/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_nmstate/tasks/workload.yml
Add two new workloads to use with the OCP Virt Roadshow on CNV.
- MetalLB Operator
- NMState Operator
- ocp4_workload_metallb
- ocp4_workload_nmstate
=> Add two new workloads for Virt Roadshow on CNV

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/pre_workload.yml
removed b64decode removed from value
role: ocp4_workload_ansible_automation_platform
=> remove decode from value

ansible/configs/experience-ocpvirt/vcenter-remove-access.yml, ansible/configs/experience-ocpvirt/vcenter-remove-vm.yml, ansible/configs/experience-ocpvirt/vcenter-remove-webapp-vms.yml, ansible/configs/experience-ocpvirt/vcenter-setup-user.yml, ansible/configs/experience-ocpvirt/vcenter-setup-webapp-vms.yml
Dont verify vcenter SSL certs as we now talk direct to vcenter which has self signed cert
```paste below
```
=> dont verify vcenter cert since we are talking direct to vc

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhbk.yaml
=> Fix RHBK operator in Quarkus workshop

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhbk.yaml
=> Add install_operator_starting_csv in Quarkus workshop

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhbk.yaml
…watch all namespaces
```paste below
```
=> fix AllNamespaces InstallModeType not supported in Quarkus workshop

ansible/configs/sap-hana/software.yml
=> adding ansible exclude

ansible/configs/osp-on-ocp/README.adoc, ansible/configs/osp-on-ocp/default_vars_ec2.yml, ansible/configs/osp-on-ocp/default_vars_equinix_metal.yml, ansible/configs/osp-on-ocp/destroy_env.yml, ansible/configs/osp-on-ocp/files/configure_backup_operator.sh, ansible/configs/osp-on-ocp/files/configure_nodenetworkconfigurationpolicy.sh, ansible/configs/osp-on-ocp/files/configure_operators.sh, ansible/configs/osp-on-ocp/files/configure_vddk.sh, ansible/configs/osp-on-ocp/files/htpasswd.yaml, ansible/configs/osp-on-ocp/post_infra.yml, ansible/configs/osp-on-ocp/post_software.yml, ansible/configs/osp-on-ocp/pre_infra.yml, ansible/configs/osp-on-ocp/pre_software.yml, ansible/configs/osp-on-ocp/requirements.yml, ansible/configs/osp-on-ocp/sample_vars_equinix_metal.yml, ansible/configs/osp-on-ocp/software.yml, ansible/configs/osp-on-ocp/templates/configureMTV.sh.j2, ansible/configs/osp-on-ocp/templates/exposeVMs.sh.j2, ansible/configs/osp-on-ocp/templates/httpd/ocp.conf, ansible/configs/osp-on-ocp/templates/httpd/ssl.conf, ansible/configs/osp-on-ocp/templates/importVMs.sh.j2, ansible/configs/osp-on-ocp/vcenter-remove-access.yml, ansible/configs/osp-on-ocp/vcenter-remove-vm.yml, ansible/configs/osp-on-ocp/vcenter-remove-webapp-vms.yml, ansible/configs/osp-on-ocp/vcenter-setup-user.yml, ansible/configs/osp-on-ocp/vcenter-setup-webapp-vms.yml
-->
Onboarding config, it will require changes to the base config it was developed using in order to be promoted to the next iteration.  New config will require pre-built hosts and network configuration that varies from the base. 
osp-on-ocp config to demo the osp on ocp services.
=> Onboard osp-on-ocp Config

ansible/configs/osp-on-ocp/rhev-remove-webrhv-vm.yml
fix destroy for osp on ocp
osp on ocp
```paste below
```
=> fix destroy for osp on ocp

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/defaults/main.yml
Adding oldest vars in workloads...
=> Missed the super old default vars

ansible/roles/ocp4-workload-quarkus-workshop/files/rhbk_operatorgroup.yaml, ansible/roles/ocp4-workload-quarkus-workshop/files/rhbk_subscription.yaml, ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhbk.yaml
=> Update RHBK installer in Quarkus workshop

ansible/configs/ocp4-equinix-aio/requirements.yml
Fixes issue with missing flat subnet in virsh 
config ocp4-equinix-aio
=> Update requirements to use standard branch

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/files/vddk_buildconfig.yaml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/files/vddk_imagestream.yaml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_mtv_provider.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_vddk.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/templates/forklift_provider_host.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/templates/forklift_provider_vmware.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/templates/namespace_mtv_provider.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/templates/secret_vmware_credentials.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/vars/main.yml
Add Support to create VDDK Image and configure vCenter Forklift Provider.
This completes the single-user usecase.
=> Add support to configure VDDK Image and MTV Providers

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_remove_user.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_remove_vm.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_remove_vms.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_prerequisites.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_user.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_vddk.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_vms.yml
Add flag to turn cert validation off for vCenter. 
=> Add flag to turn off cert validation on vCenter

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhbk.yaml
=> Fix rhbk issue in Quarkus workshop

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-rhbk.yaml, ansible/roles/ocp4-workload-quarkus-workshop/templates/rhbk_operatorgroup.yaml.j2, ansible/roles/ocp4-workload-quarkus-workshop/templates/rhbk_subscription.yaml.j2
=> Improve RHBK installer in Quarkus workshop

ansible/roles_ocp_workloads/ocp4_workload_rosa_fsx/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_rosa_fsx/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_fsx/tasks/files/FSxONTAP.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_fsx/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_fsx/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_fsx/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_fsx/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rosa_fsx/tasks/workload.yml
New role for the ROSA FSx Workshop
Ansible Role ocp4_workload_rosa_fsx
=> Add new role  ocp4_workload_rosa_fsx

ansible/roles/ocp4-workload-quarkus-workshop/tasks/verify-workload.yaml
=> Fix the guide verification in Quarkus workshop

ansible/roles/ocp4-workload-quarkus-workshop/tasks/install-username-distribution.yaml
=> Fix Redis issue in Quarkus workshop

ansible/roles_ocp_workloads/ocp4_workload_mta7/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta7/templates/applicationset.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta7/templates/tackle.yaml.j2
MTA7 Workload was created but not updated completely to deploy MTA 7.
Fixed.
ocp4_workload_mta7
=> Fix MTA 7 Workload

ansible/roles_ocp_workloads/ocp4_workload_mta7/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_mta7/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7/tasks/workload.yml
Make ansible-lint warnings/errors disappear.
ocp4_workload_mta7
=> Modernize MTA7 workload code

ansible/roles/install_operator/tasks/install.yml
Update install.yml to increase installplan setup duration
ansible/roles/install_operator/tasks/install.yml
=> Update install.yml to increase installplan setup duration

ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/workload.yml
=> RHTPA: Install latest trustification instance

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_tpa_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/workload.yml
=> RHTPA: Add secrets for TPA configuration

ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/workload.yml
=> TPA: add custom password for admin console

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_tpa_secrets.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/workload.yml
=> RHTPA: Small fixes to get TPA template working

ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/templates/deployment_database.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/templates/namespace.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/templates/pvc_database.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/templates/rolebinding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/templates/secret_database.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/templates/service_database.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mta7_workshop/templates/serviceaccount_database.yaml.j2
MTA 7 Workshop needs a PostgreSQL database preconfigured. This workload sets that up.
ocp4_workload_mta7_workshop
=> Add database for MTA 7 Workshop

ansible/configs/ocp4-upi-vmc/software_vmc.yml
=> Update software_vmc.yml - fix up vmware user data

ansible/configs/rosa-consolidated/destroy_env.yml
Adding remove_workloads task in destroy_env.yml 
Config: rosa-consolidated
=> adding remove workload task

ansible/configs/rosa-consolidated/files/requirements_k8s.txt
Adding pyvmomi and pyvim python library to support ocp4_workload_virt_roadshow_vmware role
config: rosa-consolidated
=> adding pyvmomi python lib

ansible/roles/host-ocp4-assisted-destroy/defaults/main.yml, ansible/roles/host-ocp4-assisted-destroy/templates/cleanup-ceph.yaml.j2
CNV Cleanup Job template was malformed. Fixed.
List new variable to pick ceph image in role defaults.
host-ocp4-assisted-destroy
=> Fix CNV cleanup job. Add default to role.

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/pre_workload.yml
Fixed download of oc tooling.
```paste below
```
=> Fixes oc tooling download

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_remove_user.yml
fix roadshow delete
```paste below
```
=> fix roadshow delete

ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/rhoai/odh-cluster.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/templates/rhoai/odh-dashboard-config.yaml.j2
=> Fix RHOAI issue in MAD

ansible/configs/experience-ocpvirt/templates/importVMs.sh.j2
Update importVMs.sh.j2 for experience ocpvirt
```paste below
```
=> Update importVMs.sh.j2 for experience ocpvirt

ansible/configs/test-empty-config/default_vars.yml, ansible/configs/test-empty-config/infra.yml
Add `fail_infra_percentage` feature to test-empty-config
=> Add test-empty-config fail_infra_percentage

ansible/configs/zero-touch-base-rhel/pre_software.yml
This update to zero-touch-base-rhel will allow us to inject assets that each individual lab requires
```paste below
```
=> zero-touch-base-rhel update to add asset-injector role

ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/files/container_security_subscription.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/files/jaeger_subscription.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/files/opentelemetry_subscription.yaml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_jaeger_operator.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/install_opentelemetry_operator.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_quarkus_super_heroes_demo/templates/opentelemetry_collector_instance.yaml.j2
Update the `OCP4_QUARKUS_SUPERHEROES_DEMO` role.
I tested this by pointing DEV to my local fork. See 
- https://github.com/rhpds/agnosticv/pull/15514
- https://github.com/rhpds/agnosticv/pull/15528
- https://github.com/rhpds/agnosticv/pull/15529
- https://github.com/rhpds/agnosticv/pull/15563
I then ordered the DEV catalog item
=> Change role OCP4_QUARKUS_SUPERHEROES_DEMO update to RHBQ 3.8

ansible/configs/test-empty-config/post_infra.yml, ansible/configs/test-empty-config/sandbox_openshift.yml
Add data from the sandbox API to user_info
- Test pull request
```paste below
```
=> empty-config: add data for OcpSandbox

ansible/configs/test-empty-config/infra.yml
=> empty-config: Fix fail_infra_percentage

ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/workload.yml
=> RHTPA: Increase minio storage

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/remove_workload.yml
Forgot to remove the task that calls the tasks file that got removed.
=> Oops. Removed the tasks file but not the task.

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/files/vddk_buildconfig.yaml
Remove extra space to make test pass.
=> Remove extra space

ansible/configs/ocp4-rhods-aro-config/README.adoc, ansible/configs/ocp4-rhods-aro-config/default_vars.yml, ansible/configs/ocp4-rhods-aro-config/destroy_env.yml, ansible/configs/ocp4-rhods-aro-config/files/cloud_providers/azure_cloud_template.j2, ansible/configs/ocp4-rhods-aro-config/infra.yml, ansible/configs/ocp4-rhods-aro-config/post_infra.yml, ansible/configs/ocp4-rhods-aro-config/post_software.yml, ansible/configs/ocp4-rhods-aro-config/pre_infra.yml, ansible/configs/ocp4-rhods-aro-config/pre_software.yml, ansible/configs/ocp4-rhods-aro-config/requirements.yml, ansible/configs/ocp4-rhods-aro-config/software.yml, ansible/configs/ocp4-rhods-aro-config/templates/agnosticd_user_info_upload.yaml.j2, ansible/configs/ocp4-rhods-aro-config/templates/demo-operator-catalog-source.yaml, ansible/configs/ocp4-rhods-aro-config/templates/demo-operator-namespace.yaml, ansible/configs/ocp4-rhods-aro-config/templates/demo-operator-operator-group.yaml, ansible/configs/ocp4-rhods-aro-config/templates/demo-operator-subscription.yaml, ansible/configs/ocp4-rhods-aro-config/templates/demo-workshop-install.yaml.j2, ansible/configs/ocp4-rhods-aro-config/workloads.yml
Restore ocp4-rhods-aro-config
ocp4-rhods-aro-config
=> klewis928 restore ocp4-rhods-aro-config

ansible/configs/zero-touch-base-rhel/pre_software.yml
Update when statement to include correct variable.
```paste below
```
=> zero-touch-base-rhel asset-injector typo fix

ansible/roles_ocp_workloads/ocp4_workload_cloud_native_workload_identity/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cloud_native_workload_identity/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cloud_native_workload_identity/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_cloud_native_workload_identity/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cloud_native_workload_identity/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cloud_native_workload_identity/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cloud_native_workload_identity/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cloud_native_workload_identity/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cloud_native_workload_identity/templates/devworkspace.yaml.j2
Added new ocp4_workload_cloud_native_workload_identity role
=> Added ocp4_workload_cloud_native_workload_identity role

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/multi_user/vm_database.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/multi_user/vm_winweb01.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/multi_user/vm_winweb02.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/single_user/vm_database.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/single_user/vm_winweb01.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vms/templates/single_user/vm_winweb02.yaml.j2
Make the type of machine used for the VMs in the Virt Roadshow configurable.
ocp4_workload_virt_roadshow_vms
=> Make VM machine type configurable

ansible/roles_ocp_workloads/ocp4_workload_gitops_aap/tasks/argocd_info.yml
=> AAP: add retry for route

ansible/roles/asset_injector/README.adoc
Update README of asset_injector role
asset_injector
```paste below
```
=> asset_injector Update README for new functionality

ansible/roles_ocp_workloads/ocp4_workload_rhdh/tasks/workload.yml
add in section to install backstage
=> Update workload.yml - rhdh

ansible/roles_ocp_workloads/ocp4_workload_cloud_native_workload_identity/tasks/workload.yml
Manages failure conditions for Cloud Native Workload Identity role
* ocp4_workload_cloud_native_workload_identity
=> Handling failures for Cloud Native Workload Identity role

ansible/roles_ocp_workloads/ocp4_workload_rhdh _plugins/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhdh _plugins/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_rhdh _plugins/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhdh _plugins/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhdh _plugins/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhdh _plugins/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhdh _plugins/tasks/workload.yml
* Update workload.yml
* Update workload.yml
* Update workload.yml
* Update workload.yml
* Update workload.yml
* Update workload.yml
* Update workload.yml
* Update workload.yml
```paste below
```
=> Update workload.yml - rhdh (#8205)

ansible/roles/vscode-server/defaults/main.yml, ansible/roles/vscode-server/templates/config.yaml.j2, ansible/roles/vscode-server/templates/nginx.conf.j2
1: Adding variable to select auth types between password and none.
2: Remove samepage option from nginx header to serve vscode in iframs.
=> adding auth type

ansible/roles/ocp4-workload-workshop-admin-storage/defaults/main.yml
Having issues with MAD: OPS on 4.15. We are increasing instance size to see if that fixes issues. May need to be increased again.
Increasing aws instance size to see if that fixes issues with MAD: OPS on 4.15
=> Change test MAD: OPS (increase AWS instance size)

tools/execution_environments/ee-multicloud-public/Containerfile, tools/execution_environments/ee-multicloud-public/readme.adoc
new release of ee-multicloud based on `v0.1.2-rc2`
- New ee-multicloud Pull Request
=> ee-multicloud v0.1.2

ansible/roles/ocp4-workload-workshop-admin-storage/defaults/main.yml
<Reverse> Having issues with MAD: OPS on 4.15. We are increasing instance size to see if that fixes issues. May need to be increased again.
<Reverse> Increasing aws instance size to see if that fixes issues with MAD: OPS on 4.15
=> reverse changes - MAD: OPS

ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/workload.yml
=> RHTPA: Use latest version of MINIO

ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/workload.yml
=> RHTPA: Bug fix with Minio size

ansible/roles_ocp_workloads/ocp4_workload_ai_llm_rag_demo/tasks/workload.yml
Update variable to correct value
workload_ai_llm_rag_demo
=> update to correct var value

ansible/roles_ocp_workloads/ocp4_workload_ai_llm_rag_demo/tasks/workload.yml
Of course I missed one... Last var update fingers crossed
ocp4_workload_ai_llm_rag_demo_branch
=> one more var update

ansible/configs/rosa-consolidated/workloads.yml
As FTL requires root privileges to install, I've added this to the rosa-consolidated config during the bastion install play.
Rosa-Consolidated
```paste below
```
=> Add ftl to rosa consolidated

ansible/configs/base-infra/post_infra.yml
Modify and restart sshd for CVE CVE-2024-6387 aka regreSSHion
In post_infra.yml:
- changes an sshd config var
- restarts sshd
(This pattern will be repeated on 8 other impacted configs)
config/base-infra
=> Fix for base_infra regrsshion CVE

ansible/configs/base-infra/post_infra.yml
Extend regreSSHion fix to only apply to RHEL 9 VMs for config base-infra
config/base-infra
=> Make regreSSHion fix conditional on being RHEL 9

ansible/configs/ocp4-cluster/post_infra.yml
Fix CVE regreSSHion in ocp4-cluster
```paste below
```
=> Make regreSSHion fix conditional on being RHEL 9 in ocp4-cluster

ansible/configs/ansible-lightspeed/post_infra.yml
Fix in post_infra for CVE regeSSHion
configs/ansible-lightspeed
=> Fixes for regreSSHion CVE - config ansible-lightspeed

ansible/configs/rosa-manual/post_infra.yml
SUMMARY
Fix CVE regreSSHion in ocp4-cluster
ISSUE TYPE
COMPONENT NAME
configs/rosa-consolidated
ADDITIONAL INFORMATION
=> Update post_infra.yml to Fix CVE regreSSHion in ocp4-cluster

ansible/configs/just-bastion/post_infra.yml
* Fix CVE regreSSHion in ansible-bu-wprkshop
* Update post_infra.yml
config: just-bastion
=> Fix CVE regreSSHion just-bastion

ansible/configs/rhel-security/post_infra.yml
Fix CVE regreSSHion in rhel-security
configs/rhel-security
=> Fix CVE regreSSHion in rhel-security

ansible/configs/rhel-container-security/post_infra.yml
Fix CVE regreSSHion in rhel-container-security
configs/rhel-container-security
=> Fix CVE regreSSHion in rhel-container-security

ansible/configs/rosa-manual/post_infra.yml
* Fix CVE regreSSHion in ansible-bu-wprkshop
* Update post_infra.yml
config: rosa-manual
=> Fix CVE regreSSHion rosa-manual

ansible/configs/rhel8-base/post_infra.yml
Fix CVE regreSSHion in rhel8-base
configs/rhel8-base
=> Fix CVE regreSSHion in rhel8-base

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
Increase delay by 10 and retires by 10
Due to failing on rock, paper scissors - > https://aap2-prod-us-east-2.aap.infra.demo.redhat.com/#/jobs/playbook/567034/output
=> Update workload.yml - increase wait for Gitea users setup

ansible/configs/rhel9-workshop/post_infra.yml
Fix CVE regreSSHion in rhel9-workshop
configs/rhel9-workshop
=> Fix CVE regreSSHion in rhel9-workshop

ansible/roles/vscode-server/defaults/main.yml, ansible/roles/vscode-server/templates/settings.json
Adding jinja2 condition in template to add additional settings parameter in settings.json
=> adding additonal settings

ansible/configs/ansible-automation-platform/post_infra.yml
* Fix CVE regreSSHion in ansible-bu-wprkshop
* Update post_infra.yml
config: ansible-automation-platform
=> Fix CVE regreSSHion ansible-automation-platform

ansible/roles/vscode-server/templates/settings.json
=> fixed the condition

ansible/roles/ansible_bu_setup_workshop/templates/hosts/auto_satellite.j2
Include additional if sections for centos and oracle instances based on el_rebuild_distribution var.
ansible/roles/ansible_bu_setup_workshop
=> ansible_bu_setup_workshop role - auto_satellite inventory jinja template mod

ansible/configs/convert-to-rhel/pre_software.yml
Gather facts so role conditional is found.
```paste below
```
=> convert-to-rhel gather facts = true for conditional

ansible/roles/ansible_bu_setup_workshop/templates/hosts/auto_satellite.j2
Adjust for loops to be contained within separate if/endif sections for auto_satellite inventory jinja template
ansible/roles/ansible_bu_setup_workshop
=> ansible_bu_setup_workshop role -  auto_satellite inventory jinja template mod

ansible/configs/just-a-bunch-of-nodes/destroy_env.yml
config/just-a-bunch-of-nodes needed a shared showroom destroy
config/just-a-bunch-of-nodes
=> Add shared cluster showroom destroy to just-a

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/acm/acm-placement.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_amqstreams/templates/acm-placement.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_gitlab/templates/placement.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_hashicorp_vault/templates/acm-placement.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_data_foundation/templates/acm-placement.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_openshift_gitops/templates/acm-placement.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_quay_registry/templates/acm-placement.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_rhacs_secured_cluster/templates/acm-placement.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_gitops_sonarqube/templates/acm-placement.yml.j2
=> API version upgrade

ansible/roles_ocp_workloads/ocp4_workload_gitops_sonarqube/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_sonarqube/templates/acm-application-set.yml.j2
=> pass imnage name

ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_tekton_chains.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/templates/tekton-config.yml.j2
=> Install new tekton chains version

ansible/configs/osp-on-ocp/pre_software.yml
Updating to rhel-9.4-x86_64-kvm.qcow2
ansible/configs/osp-on-ocp
=> Update qcow Image

ansible/roles/showroom/defaults/main.yml, ansible/roles/showroom/tasks/22-showroom-users-security.yml, ansible/roles/showroom/tasks/40-showroom-render.yml, ansible/roles/showroom/templates/ansible_runner_api_service/ansible_runner_api_service.j2, ansible/roles/showroom/templates/base_service_traefik_httpd/base_service_traefik_httpd.j2, ansible/roles/showroom/templates/compose_nginx_template.j2, ansible/roles/showroom/templates/service_codeserver/service_codeserver.j2, ansible/roles/showroom/templates/service_double_tty/service_double_tty.j2, ansible/roles/showroom/templates/service_second_terminal/service_second_terminal.j2, ansible/roles/showroom/templates/service_single_terminal/service_single_terminal.j2, ansible/roles/showroom/templates/service_tty1/service_tty1.j2, ansible/roles/showroom/templates/service_tty2/service_tty2.j2
1- Replace docker image with quay.io images
2- Added tasks in block to use environment ssh provision keypair
3- Variablised images path
role: showroom
=> [WIP] showroom 

ansible/configs/convert-to-rhel/post_software.yml
Update showroom ssh user
```paste below
```
=> convert-to-rhel update ssh user var showroom

ansible/configs/convert-to-rhel/post_software.yml
Resolve showroom ssh errors with correct password var
```paste below
```
=> Convert to RHEL, update showroom ssh pass var

ansible/roles/open-env-azure-install-aro/defaults/main.yml, ansible/roles/open-env-azure-install-aro/tasks/install-aro-azcollection.yml
set variables for hard coded vm size and the counts
role: open-env-azure-install-aro
=> [WIP] variablized hardcode counts and vm size

ansible/roles/open-env-azure-install-aro/tasks/install-aro-azcollection.yml
Adding missing argument 
role: open-env-azure-install-aro
=> [WIP] open-env-azure-install-aro

ansible/roles/deploy-eks-cluster/defaults/main.yaml, ansible/roles/deploy-eks-cluster/tasks/create_resources.yaml, ansible/roles/deploy-eks-cluster/tasks/destroy_resources.yaml, ansible/roles/deploy-eks-cluster/tasks/extract_kubeconfig.yaml, ansible/roles/deploy-eks-cluster/tasks/main.yaml, ansible/roles/deploy-eks-cluster/tasks/print_user_info.yaml, ansible/roles/deploy-eks-cluster/templates/eks-cluster-env.yaml.j2
1: Added kubeconfig extract tasks
2: Variablized template
3: Used variable name convention 
role: deploy-eks-cluster
=> [WIP] Deploy eks cluster

ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_masters_etcd.yaml, ansible/roles/host-ocp4-assisted-installer/tasks/kubevirt/create_workers.yaml, ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml, ansible/roles/host-ocp4-assisted-installer/templates/static_network_config_full.j2
=> CNV: Provide mac address for enp1s0 too

ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_project.yaml
=> CNV: enable kubemacpool (it's the default)

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml
=> CNV: smaller prefix for MAC to reduce collisions

ansible/roles/host-ocp4-assisted-installer/vars/main.yaml
=> CNV: add missing vars

ansible/roles/deploy-eks-cluster/tasks/extract_kubeconfig.yaml
Added task to copy .aws/creds to student user
role: deploy-eks-cluster
=> adding task to copy credentials

ansible/roles/deploy-eks-cluster/tasks/extract_kubeconfig.yaml
Replace copy src with content
role: deploy-eks-cluster
=> replace src with content

ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/tasks/workload.yml
=> RHTAP: Remove inline dependency build

ansible/roles_ocp_workloads/ocp4_workload_ansible_plugin_registry/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_plugin_registry/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_plugin_registry/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_plugin_registry/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_plugin_registry/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_plugin_registry/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_plugin_registry/templates/deployment-ansible-plugin-registry.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_plugin_registry/templates/namespace-ansible-plugin-registry.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_backstage_repo.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/application-backstage-gitops.yml.j2
=> Ansible RHDH: Add ansible plugin registry

ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/files/nodefeature_discovery_cr.yaml, ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/tasks/nfd_operator.yml, ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/tasks/nvidia_gpu_operator.yml
Updated with timeouts and change to nfd cr image.
```paste below
```
=> Updated timeouts for deployment and changed nfd cr image

ansible/configs/containerize-app-demo/post_software.yml, ansible/configs/rhel-container-security/post_software.yml, ansible/configs/rhel9-workshop/post_software.yml
showroomize three configs
. containerize-app-demo
. rhel-container-security
. rhel9-workshop
```paste below
```
=> showroomize three configs

ansible/roles/host-ocp4-installer/tasks/install_installer.yml
=> Fix download URL of the OC client for <=4.14

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/workload.yml
=> Update workload.yml -add retires

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/remove_workload.yml
ignore errors on showroom project deletion
```paste below
```
=> ignore errors on showroom deletion

ansible/roles_ocp_workloads/ocp4_workload_rhacs/templates/central.yaml.j2
=> Increase matcher memory

ansible/roles/ec2_add_subnet_and_nic/tasks/main.yaml
Update role vars for general aws_secret variable naming.
ec2_add_subnet_and_nic
```paste below
```
=> ec2_add_subnet_and_nic, update to correct aws secret vars

ansible/configs/zero-touch-base-rhel/post_software.yml
Fix conn_name var to disconnect created nic
zero_touch_base_rhel
```paste below
```
=> ZT base RHEL, update connection name

ansible/roles_ocp_workloads/ocp4_workload_acm_multicluster_observability/tasks/workload.yml
=> [WIP]Added Until condition

ansible/roles_ocp_workloads/ocp4_workload_showroom/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/deploy-showroom-helm.yaml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/setup-namespace.yaml
stacked and tabbed terminals working with showroom terminal and wetty
=> ocp showroom: implementation of stacked/tabbed terminals

ansible/roles/podman_desktop/defaults/main.yml, ansible/roles/podman_desktop/tasks/main.yml
Clean up the user vars in podman_desktop vars and support usecase where student_group != student_name
roles/podman_desktop
=> Clean up role podman_desktop's user vars

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/secret-default-sa-token.yml.j2
=> RHDH-RAD: Added 4.16 backwards compatibility for SA token

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_rhsso.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/secret-default-sa-token.yml.j2
=> Rhdh rad fix 1.0

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/files/secret-default-sa-token.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/files/secret-default-sa-token.yml
added namespace
```paste below
```
=> Update secret-default-sa-token.yml - added namespace

ansible/role_runner.yml, ansible/roles/test_empty_role/README.adoc, ansible/roles/test_empty_role/tasks/main.yml
Simple wrapper for running an AgD role against an existing host, group, inventory
Simple test_role for verification
ansible/role_runner.yml
ansible/roles/test_empty_role
=> Simple role_ruuner playbook and test role

ansible/roles/vscode-server/README.adoc, ansible/roles/vscode-server/defaults/main.yml, ansible/roles/vscode-server/tasks/main.yml, ansible/roles/vscode-server/tasks/nginx-server.yml, ansible/roles/vscode-server/tasks/nginx/RedHat7.yml, ansible/roles/vscode-server/tasks/nginx/RedHat8.yml, ansible/roles/vscode-server/tasks/vscode-server.yml, ansible/roles/vscode-server/templates/coder.json.j2, ansible/roles/vscode-server/templates/config.yaml.j2, ansible/roles/vscode-server/vars/main.yml
Make vscode _server_port listening port configurable.
Major refactor of vars for consistency.
roles/vscode-server
=> Refactor vscode-server vars for consistency, extend port capability

ansible/roles/vscode-server/defaults/main.yml
added colon in variable
role: vscode_server
=> vscode_server

ansible/roles/host-ocp4-assisted-destroy/templates/cleanup-ceph.yaml.j2
```
\\\\\"cleanup\\\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"cleanup-ceph-sandbox-qnl5t-1-ocp4-cluster\",\"group\":\"batch\",\"kind\":\"jobs\"},\"code\":403}\\n'", "reason": "Forbidden"}
```
```paste below
```
=> CNV: Use a unique name for the cleanup job

ansible/roles/vscode-server/README.adoc, ansible/roles/vscode-server/defaults/main.yml, ansible/roles/vscode-server/tasks/main.yml, ansible/roles/vscode-server/tasks/nginx-server.yml, ansible/roles/vscode-server/tasks/nginx/RedHat7.yml, ansible/roles/vscode-server/tasks/nginx/RedHat8.yml, ansible/roles/vscode-server/tasks/vscode-server.yml, ansible/roles/vscode-server/templates/coder.json.j2, ansible/roles/vscode-server/templates/config.yaml.j2, ansible/roles/vscode-server/vars/main.yml
Reverts my PR which broke the vscode-server role
Will test more extensively before resubmitting future changes
roles/vscode-server
```paste below
```
=> Revert toks vscode changes 01

ansible/roles_ocp_workloads/ocp4_workload_summit_2024_cloud_native_camel/files/grafana-dashboard.yml
Updating the Graphana dashboard. Some panels are now deprecated and need this update. 
ocp4_workload_summit_2024_cloud_native_camel
=> updating grafana dashboard

ansible/roles_ocp_workloads/ocp4_workload_summit_2024_cloud_native_camel/templates/devspace_cluster.yml.j2
fixing error message in devspaces dashboard .
ocp4_workload_summit_2024_cloud_native_camel
=> fixing CHE default editor

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_rhsso.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/keycloak-client-openshift.yml.j2
=> Fix bug with username

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow/templates/rolebinding-kubevirt-ui-features-reader-binding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow/templates/rolebinding-kubevirt-user-settings-reader-binding.yaml.j2
Forgot a few things.
ocp4_workload_virt_roadshow
=> Add missing roles and rolebindings to kubevirt

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow/tasks/workload.yml
Missing loop_control var caused an error.
ocp4_workload_virt_roadshow
=> Adding missing loop_control

ansible/roles_ocp_workloads/ocp4_workload_kubevirt/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/templates/hyperconverged.yaml.j2
Add feature gate to (not) import boot sources upon CNV deployment.
Modernize Ansible, fix all Ansible-lint errors/warnings.
=> Add feature gate to import boot sources (or not). Modernize Ansible

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_janus_argocd.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_quay.yml
=> RHDH: Remove dependency of common password

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/inform_only_policy_tasks.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_stackrox.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/workload.yml
=> Remove dependency on common password

ansible/configs/ocp4-equinix-aio/requirements.yml
https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_base_virt/tree/v0.1.7
=> Update requirements.yml - set branch back to tag version 

ansible/configs/sap-hana/default_vars_openshift_cnv.yaml
Requested in RITM1852455
```paste below
```
=> Increase CPUs for HANA DB

ansible/roles/asset_injector/README.adoc
asset-injector
```paste below
```
=> asset-injector update README

ansible/configs/ocp4-equinix-aio/requirements.yml
implement odf fix to aio
to fix https://aap2-prod-us-east-2.aap.infra.demo.redhat.com/#/jobs/playbook/702376/output 
fix is here: 
https://github.com/RHFieldProductManagement/ocp4_aio_role_ocs/blob/v0.0.9/files/odf-operator.yaml
=> Update requirements.yml - upgrade aio tag to v0.0.9

ansible/roles/ansible_bu_setup_workshop/tasks/rh_isam.yml, ansible/roles/ansible_bu_setup_workshop/templates/hosts/rh_isam.j2
Initial rh_isam deploy configs.
Initial deploy config for rh_isam workshop deploy, new deploy for `ansible_bu_setup_workshop` role.
=> Initial rh_isam deploy configs.

ansible/roles/ai_setup_ilab/defaults/main.yml, ansible/roles/ai_setup_ilab/tasks/main.yml
Fix: missing when boolean var was breaking role
=> Role ai_setup_ilab Missing when var was breaking ai_setup_lab

ansible/roles/ansible_bu_setup_workshop/templates/etchosts/rh_isam.j2
Initial revision for etchosts/rh_isam.j2 template
- New config Pull Request - rh_isam workshop deployment
roles/ansible_bu_setup_workshop
=> rh_isam workeshop templates/etchosts/rh_isam.j2 - Initial revision.

ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/tasks/workload.yml
=> Enable NVIDIA GPU Dashboard

ansible/include_vars.yml, ansible/setup_runtime.yml
- Remove unnecessary stat for include_vars checks
- Fix to allow passtrough user data in include_vars
Core
=> Simplify include-vars logic

ansible/configs/ocp4-cluster/files/requirements_ec2_el9.txt, ansible/configs/ocp4-cluster/files/requirements_k8s.txt, ansible/configs/ocp4-cluster/files/requirements_k8s_el9.txt, ansible/configs/ocp4-cluster/files/requirements_openshift_cnv.txt, ansible/configs/ocp4-cluster/files/requirements_openshift_cnv_el9.txt, ansible/configs/ocp4-cluster/requirements.yml
Updating the collections in the latest EE also requires updating python modules.
This PR updates the relevant modules.
Tested on AWS and CNV.
ocp4-cluster
=> Update ocp4 cluster python dependencies

ansible/roles/host-ocp4-installer/create-manifests.yml, ansible/roles/host-ocp4-installer/defaults/main.yml, ansible/roles/host-ocp4-installer/files/cluster-network-03-config.yml, ansible/roles/host-ocp4-installer/tasks/configure-osp-external-network-for-install.yml, ansible/roles/host-ocp4-installer/tasks/generate_install_config.yml, ansible/roles/host-ocp4-installer/tasks/install_installer.yml, ansible/roles/host-ocp4-installer/tasks/main.yml, ansible/roles/host-ocp4-installer/tasks/osp_post.yml, ansible/roles/host-ocp4-installer/tasks/osp_pre.yml, ansible/roles/host-ocp4-installer/tasks/print_cluster_info.yml, ansible/roles/host-ocp4-installer/templates/install-config.yaml.j2
Fix the deprecation warning about the nthhost filter.
Also while at it address ansible-lint warnings/errors where possible.
=> Fix nthhost deprecation warning. Address ansible-lint warnings where possible

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ai_llm_rag_demo/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_aquasec/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_blackhat_secured_container_pipelines/tasks/fetch_and_apply_template.yml, ansible/roles_ocp_workloads/ocp4_workload_devops_roadshow/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/fetch_and_apply_template.yml, ansible/roles_ocp_workloads/ocp4_workload_devsecops_validated_pattern/tasks/setup_tekton_chains.yml, ansible/roles_ocp_workloads/ocp4_workload_gitops_amqstreams/tasks/fetch_and_apply_template.yml, ansible/roles_ocp_workloads/ocp4_workload_hashicorp/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow/tasks/rhdh-setup-variables.yml, ansible/roles_ocp_workloads/ocp4_workload_mad_roadshow_v2/tasks/rhdh-setup-variables.yml, ansible/roles_ocp_workloads/ocp4_workload_pntae_single_node/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_project_dance/tasks/setup_tekton_chains.yml, ansible/roles_ocp_workloads/ocp4_workload_rollouts_workshop/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_stssc_on_ocp_wks/tasks/fetch_and_apply_template.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_tekton_chains.yml
When merging an AgD PR even if the checks on the changed code succeeded a subsequent check always failed.
Example: https://github.com/redhat-cop/agnosticd/actions/runs/10301887749/job/28514394407
This PR addresses all the issues that ansible-lint found that caused it to spit out warnings and fail.
multiple workloads
=> Fix warnings and errors like in https://github.com/redhat-cop/agnosticd/actions/runs/10301887749/job/28514394407

ansible/roles_ocp_workloads/ocp4_workload_minio/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_minio/templates/deployment.yaml.j2
Minio Pod did not set requests for cpu and memory.
Adding vars to set.
ocp4_workload_minio
=> Add requests to Minio pod

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_create_folder.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_create_vms.yml
=> vmware rest createvms in ocp4_workload_virt_roadshow_vmware

tools/execution_environments/ee-multicloud-public/requirements.yml
Add vmware.vmware_rest collection to Multicloud-Public EE.
ee-multicloud-public
=> Add vmware.vmware_rest to EE

ansible/library/vcenter_manage_subfolder.py, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_create_folder.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_prerequisites.yml
jumphost_ad.pem to output dir
replace folder creation code with new module
=> ocp4_workload_virt_roadshow_vmware: new folder module

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/keycloak-dev-user-openshift.yml.j2
=> Create separate variable for dev user password

ansible/configs/ocp4-cluster/files/requirements_k8s_el9.txt
Adding a few modules to hopefully satisfy the new vmware code.
ocp4-cluster
=> Update requirements to add vmware modules

ansible/configs/experience-ocpvirt/files/configure_backup_operator.sh
Bump OADP Operator to stable-1.4 for Exp Virt Roadshow on Equinix.
=> Update OADP operator to 1.4

ansible/roles-infra/infra-images/defaults/main.yaml
set up multiple defaults for arch type
```paste below
```
=> set up multiple defaults for arch type

ansible/roles/open-env-gcp-add-user-to-project/defaults/main.yml, ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml, ansible/roles/open-env-gcp-remove-project/tasks/main.yml
Update the google roles to pass ansible lint tests. One more debug output line.
open-env-gcp-add-user-to-project
open-env-gcp-remove-project
=> Update gcp provision

ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml
remove debug
open-env-gcp
```paste below
```
=> remove debug

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_stackrox.yml
=> RHTAP: Switch from docker integrationt to quay

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_stackrox.yml
=> RHTAP: Remove Quay Scanning

ansible/configs/convert-to-rhel/lock_bastion_security_group.yml, ansible/configs/convert-to-rhel/post_software.yml, ansible/configs/convert-to-rhel/requirements.yml
Update convert-to-rhel for zero touch deployments.
```paste below
```
=> Convert-to-rhel Updates for zero-touch

ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/templates/application.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_oadp_gitops/templates/applicationset.yaml.j2
Convert OADP Workload to deploy using Gitops.
NOTE:
- ONLY implemented for Minio storage
- ONLY tested for multi-user
ocp4_workload_oadp_gitops
=> Add OADP Gitops Workload

ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/files/nodefeature_discovery_cr.yaml
since NFD worker pods were failing during deployment but manually it works, so updating with the working one.
```paste below
```
=> Update nodefeature_discovery_cr.yaml - updated NFD

ansible/configs/open-environment-azure-subscription/post_software.yml
Config: pen-environment-azure-subscription
=> Moving Kubeconfig task earlier

ansible/configs/convert-to-rhel/pre_software.yml
add asset_injector role
```paste below
```
=> convert-to-rhel add asset_injector role

ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/templates/tvk-minio-s3-login-secret.yaml.j2
=> Minio Bug: Fix bug in Minio workload

ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/templates/tvk-triliovault-admin-role-binding.yaml.j2
=> Create tilio vault admin

ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/tasks/setup_oauth.yml, ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/tasks/workload.yml
=> Trilio: Add user data

ansible/configs/open-environment-azure-subscription/post_software.yml
=> (WIP) Update post_software.yml - reverted movement of kubeconfig

ansible/roles/showroom/tasks/10-showroom-dependencies.yml
ROLE: showroom
```paste below
```
=> showroom role, change dnf module to package

ansible/configs/zero-touch-base-rhel/default_vars_ec2.yml
=> Update ansible/configs/zero-touch-base-rhel/default_vars_ec2.yml default_vars_ec2.yml

ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/templates/tvk-triliovault-demo-platform-user-role-binding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/templates/tvk-triliovault-demo-platform-user-role.yaml.j2
=> Trilio: Create new trilio role excluding license

ansible/configs/zero-touch-base-rhel/default_vars_ec2.yml
Reverts redhat-cop/agnosticd#8467
=> Revert "Update ansible/configs/zero-touch-base-rhel/default_vars_ec2.yml default_vars_ec2.yml"

ansible/configs/zero-touch-base-rhel/post_software.yml
=> zero-touch-base-rhel add option for cockpit install

ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/templates/tvk-triliovault-demo-platform-user-role.yaml.j2
=> Trilio: Update api group

ansible/configs/zero-touch-base-rhel/pre_software.yml
=> zero-touch-base-rhel remove bad conditional

ansible/configs/open-environment-azure-subscription/default_vars.yml, ansible/configs/open-environment-azure-subscription/post_software.yml, ansible/configs/open-environment-azure-subscription/software.yml, ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/setup_htpasswd.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_data_foundation/tasks/workload.yml
=> (WIP) Update post_software.yml - moved workloads after kubeconfig creation

ansible/configs/experience-ocpvirt/files/configure_operators.sh
script is absolutely terrible at handling error conditions.
=> equinix virt roadshow - make wait for DevWorkspace resources more robust

ansible/configs/zero-touch-base-rhel/pre_software.yml
=> zero-touch-base-rhel update play to exclude centos

ansible/configs/zero-touch-base-rhel/post_software.yml, ansible/configs/zero-touch-base-rhel/pre_software.yml
zero-touch-base-rhel fix conditonal bugs
```paste below
```
=> zero-touch-base-rhel fix conditonal bugs

ansible/roles/showroom/templates/ssh_config.j2
role: showroom
```paste below
```
=> showroom role, add ssh option for alternate host

ansible/roles/showroom/templates/ssh_config.j2
=> showroom role, ssh host bug fix

ansible/roles_ocp_workloads/ocp4_workload_argocd_bootstrap/tasks/workload.yaml
=> Update workload.yaml - removed pause

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/cert_manager_ec2.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/certificate-api.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/certificate-ingress.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/clusterissuer.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/secret-zerossl-credentials.yaml.j2
Add ZeroSSL support to cert manager role
```paste below
```
=> add zerossl support to cert manager

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/cert_manager_ec2.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/workload.yml
fix zerossl to run on any cloud
```paste below
```
=> fix zerossl to run on any cloud

ansible/roles_ocp_workloads/ocp4_workload_mtv/defaults/main.yml
=> MTV performance: use tag to indicate replacement container image

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/cert_manager_api_cert_check.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/cert_manager_ingress_cert_check.yml
remove ignore errors in cert-manager
```paste below
```
=> remove ignore errors

ansible/roles_ocp_workloads/ocp4_workload_ai_llm_rag_demo/tasks/workload.yml
I need to remove our install to test if it is issue with CI or install itself
=> remove validated install for testing

ansible/configs/zero-touch-base-rhel/pre_software.yml
zero-touch-base-rhel 
```paste below
```
=> zero-touch-base-rhel install tmux, add tmux config to centos

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/cronjob-vault-es-fix.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/cronjob-vault-es-fix.yml.j2
=> Vault: Add job to fix vault issues on startup

ansible/roles_ocp_workloads/ocp4_workload_mtv/tasks/workload.yml
- 
fixed my bug in identifying proper mtv-operator csv
=> mtv container replacement

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/cronjob-vault-es-fix.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/cronjob-vault-es-fix.yml.j2
=> Vault: Update vault polling command

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_create_folder_and_vms.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_vmware/tasks/vcenter_setup_vms.yml
=> virt vmware - guid in vm name

ansible/roles_ocp_workloads/ocp4_workload_external_odf/tasks/workload.yml
This will hopefully fix the registry bug
=> virt - set image registry to Managed

ansible/roles/common/tasks/main.yml
role: common
```paste below
```
=> Role 'common' , add when conditionals for ansible version

ansible/roles_ocp_workloads/ocp4_workload_ai_llm_rag_demo/tasks/workload.yml
Add install back for rag llm as fix is applied
=> add install back for rag llm

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/cronjob-vault-es-fix.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/cronjob-vault-es-fix.yml.j2
=> Fix Cronjob

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/cronjob-vault-es-fix.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/cronjob-vault-es-fix.yml.j2
=> Bug: Set backoff limit in correct location

ansible/roles_ocp_workloads/ocp4_workload_summit_2024_cloud_native_camel/tasks/install_devspaces.yml
Devspaces operator is broken and this is a workaround
ocp4_workload_summit_2024_cloud_native_camel
=> [ocp4_workload_summit_2024_cloud_native_camel] Workaroud devspaces problems

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/deployment-post-startup-fixes.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_backstage.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/deployment-post-startup-fixes.yml.j2
=> RHDH Demos: Post start up fix

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/deployment-post-startup-fixes.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/deployment-post-startup-fixes.yml.j2
=> RHDH: Remove restart policy

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/deployment-post-startup-fixes.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/deployment-post-startup-fixes.yml.j2
=> RHDH: Cleanup script

ansible/roles_ocp_workloads/ocp4_workload_ai_llm_rag_demo/tasks/create-gpu-machine-set.yaml, ansible/roles_ocp_workloads/ocp4_workload_ai_llm_rag_demo/templates/gpu-machine-sets.j2
We need to update our machine set provision. Adjusted Ansible logic and template for this
=> update machine set provision

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/deployment-post-startup-fixes.yml.j2
=> RHDH: Check for central with status code

ansible/configs/rosa-consolidated/files/requirements_k8s.txt
=> VMWare: new collection

ansible/roles_ocp_workloads/ocp4_workload_summit_2024_cloud_native_camel/tasks/install_devspaces.yml, ansible/roles_ocp_workloads/ocp4_workload_summit_2024_cloud_native_camel/templates/devspace_cluster.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_summit_2024_cloud_native_camel/templates/devspace_workspace.yml.j2
Fixing DevSpaces installation issue
- 
OCP4_WORKLOAD_SUMMIT_2024_CLOUD_NATIVE_CAMEL
=> updating devspaces

ansible/roles_ocp_workloads/ocp4_workload_summit_2024_cloud_native_camel/tasks/install_devspaces.yml
Versions were removed from channel breaking the item deployment
OCP4_WORKLOAD_SUMMIT_2024_CLOUD_NATIVE_CAMEL
=> removing devspaces versions

.github/workflows/build-ee-dispatch.yml
Fix GitHub username for "jkupferer" in build-ee-dispatch.yml
EE Build automation
=> Fix GitHub username for build-ee-dispatch.yml

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
Fixes playbook error when downloading binary oc and kubectl executables
=> [5G LAB] Fixes kubectl/oc versioning when downloading

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
Adds new config to firewalld by adding dhcp to the allow protocols.
- Role: ocp4_workload_5gran_deployments_lab
=> [5G lab] Allows dhcp in firewalld

ansible/cloud_providers/multi_infrastructure_deployment.yml, ansible/cloud_providers/shared_openshift_infrastructure_deployment.yml, ansible/setup_runtime.yml
Adding multi cloud_provider for multi component
Adding shared_openshift cloud_provider
- multi cloud_provider
- shared_openshift cloud_provider
=> Adding multi and shared_openshift cloud providers

ansible/roles-infra/infra-openshift-cnv-resources/tasks/start_instances.yaml, ansible/roles-infra/infra-openshift-cnv-resources/tasks/stop_instances.yaml
This PR fix when the VM is stopped or started with the running parameter
=> [infra-openshift-cnv-resources] Fix start stop conditions

ansible/configs/rhel9-workshop/post_software.yml
=> rhel9-workshop - Add showroom vars

ansible/configs/rhel9-workshop/post_software.yml
=> rhel9-workshop - move vars to correct location

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/pre_workload.yml
Enables and installs firewalld which is not even installed in equinix baremetal
- Role: ocp4_workload_5gran_deployments_lab
=> [Telco 5G Lab] Enables firewalld

ansible/configs/zero-touch-base-rhel/lock_bastion_security_group.yml
=> zero-touch-base-rhel add local security group def

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/files/description.html, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/templates/k10.yaml.j2
New version of the Kasten K10 workload.
Uses a pre-configured Minio (using the workload ocp4_workload_minio)
Uses install_operator
Updated to latest coding standards.
=> Add Kasten K10 Workload (using modern Ansible)

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/templates/k10.yaml.j2
Changed k10 deployment to use built-in OpenShift authentication.
Added step to validate the k10 deployed successfully.
=> Change to OpenShift Auth, wait for K10 deployment

ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/defaults/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/tasks/workload.yaml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/templates/redhat-datasciencecluster.yaml.j2
=> Changes requested from Christopher Nuland

ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/files/aws-efs-storage-class.yaml, ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/tasks/workload.yaml
=> ETX-Demo: Create storage class

ansible/roles_ocp_workloads/ocp4_workload_mtv/defaults/main.yml
new patch tag for forklift-controller image from engineering: fix-npe
=> MTV: change patch image tag to fix-npe

ansible/roles_ocp_workloads/ocp4_workload_oai_lab_insurance_claim/tasks/workload.yaml
=> ETX: Enable Tech Preview

ansible/configs/zero-touch-base-rhel/default_vars_ec2.yml
=> updating bastion name to rhel

ansible/configs/zero-touch-base-rhel/pre_software.yml
Typo in module name
```paste below
```
=> zero-touch-base-rhel module typo

ansible/roles/host-lets-encrypt-certs-certbot/defaults/main.yml, ansible/roles/host-lets-encrypt-certs-certbot/tasks/main.yml, ansible/roles/host-lets-encrypt-certs-certbot/templates/run-certbot.j2
Add zero ssl certbot
```paste below
```
=> Add zero ssl certbot

ansible/configs/zero-touch-base-rhel/pre_software.yml
add option to inject assets to all systems in pre-software.yml
```paste below
```
=> zero-touch-base-rhel add role conditional

ansible/configs/zero-touch-base-rhel/pre_software.yml
Conditional in wrong place, I was tired
```paste below
```
=> zero-touch-base-rhel conditional typo

ansible/configs/zero-touch-base-rhel/pre_software.yml
=> zero-touch-base-rhel elevate play permissions

ansible/roles_ocp_workloads/ocp4_workload_devops_roadshow/files/appprojects/cluster-config.yaml, ansible/roles_ocp_workloads/ocp4_workload_devops_roadshow/files/gitops-operator/subscription.yaml
This adds a new repo to the GitOps AppProject to support RHTPA installation, it also adds a wildcard to the repo list for more flexibility as this workshop is developed. It also upgrades the GitOps operator to 1.13.
DevOps Roadshow
=> [DevOps Roadshow] Add new repo and upgrade gitops operator

ansible/roles-infra/infra-equinix-metal-resources/tasks/create_instances.yaml
This PR adds facility, metro and plan to the provision data, to be used for reporting
infra-equinix-metal-resources infra role
=> [infra-equinix-metal-resources] Adding useful provisioning data

ansible/configs/zero-touch-base-rhel/pre_software.yml
Modify satellite configuration to bypass letsencrypt
```paste below
```
=> zero-touch-base-rhel satellite configuration

ansible/roles_ocp_workloads/ocp4_workload_ols/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ols/templates/deploy_faulty_pod.yml.j2
=> Ols update - added broken pod scenario to the role

ansible/configs/zero-touch-base-rhel/pre_software.yml
=> zero-touch-base-rhel update satellite configuration

ansible/roles_ocp_workloads/ocp4_workload_gitops_gitlab/defaults/main.yml
=> RHDH: Set default gitlab installed version

ansible/roles/open-env-gcp-user-info/tasks/main.yml
Attempt to fix GCP email output by using better ADOC formatting.
open-env-gcp-user-info
```paste below
```
=> Attempt to fix GCP email output

ansible/configs/zero-touch-base-rhel/pre_software.yml
=> zero-touch-base-rhel enable satellite installer to auto accept

ansible/configs/zero-touch-base-rhel/pre_software.yml
=> zero-touch-base-rhel, satellite configuration, foreman-maintain -y

ansible/roles/host-ocp4-hcp-cnv-install/templates/nodepool.yaml
We dont need to guarantee the cores
=> [host-ocp4-hcp-cnv-install] Remove QoS: Update nodepool.yaml

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_janus_argocd.yml
=> RHDH: Add retry for failure scenario

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_janus_argocd.yml
=> RHDH: Revert to argo 1.12 as 1.14 is unstable

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_janus_argocd.yml
=> RHDH: Attempt fix for argocd 1.14

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_janus_argocd.yml
=> RHDH: Remove duplicate password update

ansible/roles/open-env-gcp-add-user-to-project/defaults/main.yml, ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml
Add cost center to GCP projects
```paste below
```
=> Add cost center to GCP projects

ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml
update gcp project create to API v3
```paste below
```
=> update gcp project create to API v3

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern/templates/values-global.yaml.j2
Currently ocp4_workload_validated_pattern deploys are failing due to a change in the pattern repo that was not implemented in the ocp4_role.
The PR adds the required configuration in the values-global.yaml file (template task)
Fixes issue deploying, error:
```
You must set \".main.multiSourceConfig.enabled: true\" in your 'values-global.yaml' file
```
ocp4_workload_validated_pattern
Template function has been tested locally, the pattern deploys successfully with the generated template.
=> Fix role ocp4_workload_validated_pattern template file

ansible/roles/asset_injector/README.adoc, ansible/roles/asset_injector/tasks/main.yml
asset_injector needs unarchive capability eg, for unarchiving in tarballs of llms
=> Add tar unarchive capability to asset_injector role

ansible/configs/rhel9-workshop/post_software.yml
Reverts redhat-cop/agnosticd#8635
=> Revert "Update post_software.yml -rhel9"

ansible/configs/rhel9-workshop/pre_software.yml
=>  Remove setup strong passwords- Update pre_software.yml

ansible/configs/rhel9-workshop/post_software.yml
variables are set on bastion host and not localhost
rhel9-workshop Config
=> [rhel9-workshop] Update post_software.yml

ansible/configs/zero-touch-base-rhel/pre_software.yml
Speed up provision, remove outdated tasks.
```paste below
```
=> zero-touch-base-rhel remove cruft from sat setup

ansible/configs/rhel9-workshop/post_software.yml
There was an issue showing the information for the student user, this PR removes the variable bastion_public_hostname and uses the bastion to show the information, where the student_password is set
rhel9-workshop config
=> [rhel9-workshop] Fix user login information

ansible/roles/deploy-eks-cluster/tasks/extract_kubeconfig.yaml
=> EKS: Create aws file if not found

ansible/roles_ocp_workloads/ocp4_workload_trusted_artifact_signer/tasks/workload.yml
=> RHTAS: Remove check for deleted file

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/defaults/main.yml
update cert manager defaults
cert_manager
```paste below
```
=> update cert manager defaults

ansible/roles_ocp_workloads/ocp4_workload_minio/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_minio/tasks/workload.yml
=> RHDH: Change minio bucket to list

ansible/roles/host-ocp4-hcp-cnv-install/defaults/main.yaml, ansible/roles/host-ocp4-hcp-cnv-install/templates/hostedcluster.yaml
Allows to indicate a specific storageclass for etcd
Role host-ocp4-hcp-cnv-install
=> [host-ocp4-hcp-cnv-install] Allow specify etcd storageclass

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_quay.yml
=> OSR: create storage name switch

ansible/roles-infra/infra-aws-open-environment/tasks/print_user_info.yaml
Add variable aws_sandbox_account_id to be used on components
infra-aws-open-environment Role
=> Add aws sandbox id to provision data

ansible/roles/deploy-eks-cluster/defaults/main.yaml, ansible/roles/deploy-eks-cluster/tasks/extract_kubeconfig.yaml
=> OSR: Fix missing aws cli

ansible/roles/deploy-eks-cluster/tasks/extract_kubeconfig.yaml
=> Use fully qualified names

ansible/roles/deploy-eks-cluster/tasks/main.yaml, ansible/roles_ocp_workloads/ocp4_workload_external_odf/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_external_odf/tasks/workload.yml
=> RHDH-CNV: Fixes for CI to work on CNV

ansible/roles_ocp_workloads/ocp4_workload_external_odf/tasks/workload.yml
=> Swith to FQCN

ansible/roles/ai_setup_ilab/defaults/main.yml, ansible/roles/ai_setup_ilab/tasks/main.yml
=> adding ilab_version var

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/README.md, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/templates/values-secret-multicloud-gitops.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/templates/values-secret-retail.yaml.j2
The new role will be able to deploy the available patterns in the
ocp4_workload_validated_pattern_deploy_available_patterns. The input
variable is ocp4_workload_validated_pattern_deploy_display_name, will
come from RHDPS.
This role will eventually obsolete the old role ocp4_workload_validated_pattern
Tested with dev catalog item on RHDPS.
=> Add role ocp4_workload_validated_pattern_deploy

ansible/roles/ai_setup_ilab_rad/README.adoc, ansible/roles/ai_setup_ilab_rad/defaults/main.yml, ansible/roles/ai_setup_ilab_rad/files/qna.yaml, ansible/roles/ai_setup_ilab_rad/files/settings.json, ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Create a custom ilab setup role for RAD

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix the ilab commands

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix the ilab role

ansible/roles/ai_setup_ilab_rad/defaults/main.yml, ansible/roles/ai_setup_ilab_rad/tasks/main.yml
Fix to install tools
```paste below
```
=> Fix to install tools

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix an issue for Run sdkman installer

ansible/roles/ai_setup_ilab_rad/defaults/main.yml, ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix VSCode installation

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix the sdkman

ansible/roles/ai_setup_ilab_rad/files/sdkman-installer.sh, ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Add logs for sdkman issue

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Update skdman install

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Add group and owner to geturl

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix group and user for vscode installation

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix the sdkman path

ansible/roles_ocp_workloads/ocp4_workload_external_odf/tasks/workload.yml
=> ODF: Refactor to use k8s instead of shell

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Update path to install Java

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Add admin perm

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Change the permission

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix the Java installation

ansible/roles_ocp_workloads/ocp4_workload_external_odf/tasks/workload.yml
=> ODF: Increase retry count

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Add x permission to sdk file

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Make a new dir and set the perm for dirs

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Update Git clone module

ansible/roles/showroom/defaults/main.yml
=> package renamed in upstream

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Add logs to check the cloned project

ansible/roles/showroom/defaults/main.yml
Reverts redhat-cop/agnosticd#8717
=> Revert "package renamed in upstream"

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Update the project path

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix the perm for app dir

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Add new perm

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix mvn package error

ansible/roles/ai_setup_ilab_rad/tasks/main.yml
=> Fix the path of mvn

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_orchestrator.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/namespace-sonataflow.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/network-policy-sonataflow.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/orchestrator-rhdh.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/templates/secret-sonataflow-pgsql.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/defaults/main.yml
=> RHDH: Enable Orchestrator

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_orchestrator.yml
=> RHDH: Retry workflow install

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml
=> RHDH-Orchestrator: Specify starting csv as workaround for bug fix

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/tasks/setup_orchestrator.yml
=> RHDH-Orch: Wait for deployment before installing workflow

ansible/configs/osp-on-ocp/templates/httpd/ssl.conf
Adding block to restore NoVNC connection
osp-on-ocp
=> Add upgrade rule

ansible/roles/containerlab/files/bash_profile
=> Update bash_profile - fix labdir

ansible/roles/showroom/tasks/10-showroom-dependencies.yml
Remove loops from package install for faster deployments.
role, showroom
```paste below
```
=> Role: showroom, update install code for speed

ansible/roles/aap_controller_cert_issue/defaults/main.yml, ansible/roles/aap_controller_cert_issue/tasks/main.yml
Add zerossl to AAP2 CI
aap_controller_cert_issue
```paste below
```
=> add more zerossl vars

ansible/configs/ansible-automation-platform/env_vars.yml, ansible/roles/aap_deploy/templates/automationcontroller_inventory.j2, ansible/roles/aap_pah_cert_issue/tasks/main.yml
Bump RHEL Golden Image to RHEL 9.4 for ansible-automation-platform
Used by the service:
```paste below
sandboxes-gpte/automation-controller-adv-v2/dev.yaml
```
=> Bump RHEL Golden Image to RHEL 9.4 for ansible-automation-platform

ansible/configs/hcp-ocpv/post_software.yml, ansible/configs/hcp-ocpv/requirements.yml
=> [GPTEINFRA-12220] Fix requirements to newest versions

ansible/roles/install_operator/tasks/install.yml
Increase retries for CSV installation
ansible/roles/install_operator/tasks/install.yml
=> Increase retries for CSV installation

ansible/configs/base-infra/workloads.yml
Added capsule server in the workloads
config: base-infa
=> adding satellite capsule in workloads

ansible/configs/base-infra/workloads.yml
fixed task name
config: base-infa
=> fixed task name

ansible/configs/osp-on-ocp/templates/httpd/ssl.conf
An extra line was added by mistake to ssl.conf
osp-on-ocp config
=> [osp-on-ocp] Fix ssl.conf

ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/post_workload.yml
=> support multi-user data in rhacs workload

ansible/roles/rad_setup_instructlab/files/config.yaml, ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Update tools in RAD VM

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Set the Granite model to PD AI Lab in advance for RAD RHEL VM

ansible/configs/ansible-bu-workshop/workloads.yml
Enhanced workload.yml by adding controller and cleanup
config: ansible-bu-workshop
=> Workload enhancement 

ansible/roles/nginx_with_cert/README.adoc, ansible/roles/nginx_with_cert/defaults/main.yml, ansible/roles/nginx_with_cert/meta/main.yml, ansible/roles/nginx_with_cert/tasks/main.yml, ansible/roles/nginx_with_cert/tasks/nginx/RedHat7.yml, ansible/roles/nginx_with_cert/tasks/nginx/RedHat8.yml, ansible/roles/nginx_with_cert/tasks/nginx/RedHat9.yml, ansible/roles/nginx_with_cert/templates/nginx.conf.j2
Nginx with letsencrypt cert which is by default for AAP2.5
role: nginx_with_cert
=> Nginx with cert 

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/pre_workload.yml
Updates the HCP Baremetal Lab automation to OCP release 4.17
```paste below
```
=> Updates hcp baremetal lab to 4.17

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/pre_workload.yml
=> disable gpg check for localrpm

ansible/roles/nginx_with_cert/defaults/main.yml
adding missing var value
role: nginx-with-cert
=> adding variable

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/pre_workload.yml
ocp4_workload_telco_hypershift_lab 
```paste below
```
=> Added new rpms for rhel9 in hcp lab

ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_telco_hypershift_lab/tasks/pre_workload.yml
=> Added epel repo for rhel9

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Fix the copy module for RAD VM

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Fix the copy module in RAD VM

ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/post_workload.yml
Reverts redhat-cop/agnosticd#8761
Had a bug
=> Revert "support multi-user data in rhacs workload"

ansible/roles_ocp_workloads/ocp4_workload_gitea_operator/tasks/workload.yml
During a workshop with many instances, we had several random issues.
This PR adds retries, delay and condition to retry the gitea creation
ocp4_workload_gitea_operator Role
=> [GPTEINFRA-12416] [ocp4_workload_gitea_operator] Add retries configuring Gitea

ansible/roles/install_operator/tasks/install.yml
Reduce to 5 min maximum 
Install_operator role
```paste below
```
=> [install_operator] adjust retries and delay for csv check

ansible/roles_ocp_workloads/ocp4_workload_trusted_artifact_signer/templates/tas-secure-sign.yml.j2
=> RHTAS: Enable Rekor search UI

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Comment out the config file creation for iLab for RAD VM

ansible/configs/hcp-ocpv/requirements.yml
Restore original requirements and add fixes for the disk
hcp-ocpv config
=> [hcp-ocpv] Fix requirements

ansible/roles-infra/infra-openshift-cnv-resources/tasks/delete_networks.yaml
Temporary PR
infra-openshift-cnv-resources role
=> [infra-openshift-cnv-resources] Temporary ignore errors to cleanup CIs

ansible/roles/nginx_with_cert/tasks/main.yml
Adding user info and data.
role: nginx_with_cert
=> adding userinfo

ansible/configs/base-infra/post_software.yml
- There is a typo in this command. Should be ssh not sh
-
-
=> Fix post_software.yml -> ssh_command

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml
Add logic to optionally annotate VolumeSnapshotClasses as backup targets for Kasten K10.
=> Add logic to annotate volumesnapshotclasses if so desired

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml
Multi-user Kasten demo needs another annotation - this time on the storage class.
=> Add support to label a storage class. Simply demo logic conditions

ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_5gran_deployments_lab/tasks/workload.yml
Updates 5G RAN Lab to OCP release 4.17
```paste below
```
=> Updates 5gran to OCP 4.17

ansible/roles_ocp_workloads/ocp4_workload_external_odf/tasks/workload.yml
Improves the until condition adding a default([])
ocp4_workload_external_odf role
=> [ocp4_workload_external_odf] Fix until condition

ansible/configs/ansible-bu-workshop/post_software.yml
```paste below
```
Ansible BU Workshop - targethost variable added to post_software.yaml
=> Ansible BU Workshop - targethost variable added to post_software.yaml

ansible/roles_ocp_workloads/ocp4_workload_shared_cluster_access/tasks/setup_users.yml
Fix variable `ocp4_workload_shared_cluster_quota` in `ocp4_workload_shared_cluster_access` role.
Role `ocp4_workload_shared_cluster_access`
=> Fix condition in ocp4_workload_shared_cluster_access

ansible/configs/sap-hana-rhel9/default_vars.yml, ansible/configs/sap-hana-rhel9/post_software.yml, ansible/configs/sap-hana-rhel9/software.yml
Fix bug, that deployment of AAP breaks, when waiting on finishing it
sap-hana-rhel9
```paste below
```
=> Bug Fix: Wait for AAP deployment to finish

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/defaults/main.yml
Fix variable name, syntax of >- usage/typo in role default
=> Fix role ocp4_workload_validated_pattern_deploy

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/templates/values-secret-medical-diagnosis.yaml.j2
=> Merging new changes to AgnosticD

ansible/configs/odf-dr-binder/post_software.yml
showroom is unable to run and need a fix from @miteshget
```paste below
```
=> re-enabling bookbag

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/tasks/workload.yml
Also add the Kasten Storage Class to the multi-user output.
=> Also add kasten storageclass to multi-user output

ansible/roles/ai_setup_nvidia_cuda/defaults/main.yml, ansible/roles/ai_setup_nvidia_cuda/tasks/main.yml
Abandon the old < v0.18 code as everyone is on v0.19 and beyond
Upgrades the role for a better nvidia and CUDA stack
roles/ai_setup_nvidia_cuda
=> Update ai_setup_nvidia_cuda for ilab > v0.17

ansible/roles/ai_setup_instructlab/README.adoc, ansible/roles/ai_setup_instructlab/defaults/main.yml, ansible/roles/ai_setup_instructlab/files/qna.yaml, ansible/roles/ai_setup_instructlab/tasks/10-nvidia-customizations.yml, ansible/roles/ai_setup_instructlab/tasks/20-developer-customizations.yml, ansible/roles/ai_setup_instructlab/tasks/30-instruct-repos.yml, ansible/roles/ai_setup_instructlab/tasks/40-instructlab-runtime-setup.yml, ansible/roles/ai_setup_instructlab/tasks/main.yml
Take Summit Connect v0.19.3 (and anything > v0.17) to production
roles/ai_setup_instructlab
=> Modernize instructlab deploys to v0.18 and beyond

ansible/roles/automation_platform_loader/defaults/main.yml, ansible/roles/automation_platform_loader/tasks/aap/aap-2.5.yml, ansible/roles/automation_platform_loader/tasks/aap/aap-2.x.yml, ansible/roles/automation_platform_loader/tasks/main.yml
Split the tasks into tasks file.
role: ansible-platform-loader
=> spliting tasks into tasks file

ansible/roles/automation_platform_loader/defaults/main.yml
Rename automation_platform_loader_create_token with automation_platform_loader_aap_version
automation_platform_loader role
=> [automation_platform_loader] Fix variable name

ansible/roles/automation_platform_loader/defaults/main.yml, ansible/roles/automation_platform_loader/tasks/aap/aap-2.5.yml, ansible/roles/automation_platform_loader/tasks/aap/aap-legacy.yml
Fixed name and variable
Role: ansible_platform_loader
=> Fixed name and variable

ansible/roles/ansible_bu_setup_workshop/files/settings.json, ansible/roles/ansible_bu_setup_workshop/tasks/rhel.yml, ansible/roles/ansible_bu_setup_workshop/tasks/ripu.yml, ansible/roles/ansible_bu_setup_workshop/templates/coder.json.j2
Adding code-server additional settings condition
role: ansible-bu-setup-workshop
=> adding code-server settings

ansible/roles/install_operator/defaults/main.yml, ansible/roles/install_operator/meta/main.yml, ansible/roles/install_operator/tasks/install.yml, ansible/roles/install_operator/tasks/main.yml, ansible/roles/install_operator/tasks/remove.yml, ansible/roles/install_operator/templates/catalogsource.yaml.j2, ansible/roles/install_operator/templates/installplan.yaml.j2, ansible/roles/install_operator/templates/operatorgroup.yaml.j2, ansible/roles/install_operator/templates/subscription.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/vars/main.yml
install_operator: Added documentation on the extra subscription config capability. Reformatted a few things.
ocp4_workload_kubevirt: modernize workload and add support for nested KVM virtualization.
=> Add_extra_config_option_to_kubevirt

ansible/roles_ocp_workloads/ocp4_workload_rhacm/tasks/workload.yml
=> Wildcard routes for hcp hosted clusters

ansible/roles/showroom/templates/service_web1/tab_web1.j2, ansible/roles/showroom/templates/service_web2/tab_web2.j2
Enhance showroom's web tabs to play better with code-server (and others)
roles/showroom
=> Extend web tabs to support more iframe options

ansible/configs/zero-touch-ansible-bu/default_vars_ec2.yml
update internal aws zone
config: zero-touch-ansible-bu
=> Update internal zone

ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/files/nodefeature_discovery_sub.yaml
=> RAD: Make auto approve configurable

ansible/roles/showroom/templates/service_triple_tty/service_triple_tty.j2, ansible/roles/showroom/templates/service_triple_tty/tab_triple_tty.j2, ansible/roles/showroom/templates/service_triple_tty/tablink_triple_tty.j2
Add triple ttys to showroom eg allowing this:
1. ilab serve..
2. ilab chat
3. nvtop
roles/showroom
=> Add support for triple ttys in showroom

ansible/roles/showroom/templates/service_web1/tab_web1.j2, ansible/roles/showroom/templates/service_web2/tab_web2.j2
Extend showroom functionality for framing via its web tabs
Better iframe support for code server etc
roles/showroom
```paste below
```
=> Showroom open up iframe options to play well with code-server reloads

ansible/roles/showroom/templates/service_web1/tab_web1.j2, ansible/roles/showroom/templates/service_web2/tab_web2.j2
Fix iframe reload issue in showroom web tabs
- codeserver needed manual frame reload, this automates
roles/showroom
=> Add frame reloading code to web tabs for code-server etc

ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/files/nodefeature_discovery_cr.yaml
=> Update NFD CR

ansible/roles_ocp_workloads/ocp4_workload_cert_manager/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/cert_manager_azure.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/clusterissuer.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_cert_manager/templates/secret-azure-credentials.yaml.j2
This PR allows to configure cert manager for Azure cloud provider
ocp4_workload_cert_manager role
=> [ocp4_workload_cert_manager] Add Azure support

ansible/roles_ocp_workloads/ocp4_workload_lvms/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lvms/files/lvmcluster.yaml, ansible/roles_ocp_workloads/ocp4_workload_lvms/meta/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lvms/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_lvms/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_lvms/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lvms/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lvms/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lvms/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_lvms/templates/lvmcluster.yaml
Add  ocp4_workload_lvms - Deploy Logical Volume Manager Storage Operator to an OpenShift Cluster
- 
ocp4_workload_lvms ocp4 workload role
=> Add  ocp4_workload_lvms - Deploy Logical Volume Manager Storage Operator to an OpenShift Cluster

ansible/roles_ocp_workloads/ocp4_workload_metallb/templates/ipaddresspool.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_metallb/templates/l2advertisement.yaml.j2
Fix templates
ocp4_workload_metallb Role
=> [ocp4_workload_metallb] Fix template

ansible/roles_ocp_workloads/ocp4_workload_lvms/tasks/workload.yml
=> [ocp4_workload_lvms] fix template name

ansible/roles_ocp_workloads/ocp4_workload_nvidia_gpu_setup/tasks/nfd_operator.yml
=> RAD: Use General operator install

ansible/roles_ocp_workloads/ocp4_workload_lvms/templates/lvmcluster.yaml
Remove quotes and add to_yaml to ensure it parses properly the variable
ocp4_workload_lvms role
=> [ocp4_workload_lvms] Fix template

ansible/roles_ocp_workloads/ocp4_workload_lvms/tasks/workload.yml
Add correct version, as the previous one was incorrect
ocp4_workload_lvms role
=> [ocp4_workload_lvms] Update workload.yml

ansible/roles_ocp_workloads/ocp4_workload_cloud_architecture_workshop_summit2023/tasks/devspaces.yml, ansible/roles_ocp_workloads/ocp4_workload_cloud_architecture_workshop_summit2023/tasks/workload.yml
Devspaces installation check to look for  /dashboard endpoint instead of /devfile which is non-existent
ocp4_workload_cloud_architecture_workshop_summit2023
=> CNA Workshop - move from Registry to Dashboard

ansible/roles_ocp_workloads/ocp4_workload_cloud_architecture_workshop_summit2023/tasks/devspaces.yml, ansible/roles_ocp_workloads/ocp4_workload_cloud_architecture_workshop_summit2023/tasks/workload.yml
Devspaces failure
rh-cloud-architecture-workshop
=> [WIP] Devspaces failure

ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/templates/tvk-list-secrets-role-binding.yaml.j2, ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/templates/tvk-list-secrets-role.yaml.j2
=> Trilio: Fix for UI issue

ansible/roles-infra/infra-images/defaults/main.yaml
=> renaming RHEL95 image name

ansible/roles_ocp_workloads/ocp4_workload_trilio_backup_restore_vms/templates/tvk-list-secrets-role.yaml.j2
=> Trilio: Reduce role permission

ansible/roles_ocp_workloads/ocp4_workload_rhacm_cloud_credentials/tasks/install_hcp_cli.yaml, ansible/roles_ocp_workloads/ocp4_workload_rhacm_cloud_credentials/tasks/workload.yml
=> RH1 LAB1 and ocp4_workload_rhacm_cloud_credentials: Add hcp cli to workload

ansible/roles_ocp_workloads/ocp4_workload_authorino/README.md, ansible/roles_ocp_workloads/ocp4_workload_authorino/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_authorino/tasks/authorino_operator.yml, ansible/roles_ocp_workloads/ocp4_workload_authorino/tasks/main.yml, ansible/roles_ocp_workloads/ocp4_workload_authorino/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_authorino/tasks/pre_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_authorino/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_authorino/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_ols/templates/install_rhoai_vllm.olsconfig.j2
New Role to deploy Authorino Operator on OpenShift
New role to deploy authorino operator
```paste below
```
=> Added a new role for Authorino Operator Deployment

ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml
=> [infra-openshift-cnv-resources] Remove resources section

ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_profile_analyzer/templates/values-rhtpa.yml.j2
=> RHTPA: Fix bug in install where default storage is too low

ansible/configs/zero-touch-base-rhel/post_software.yml, ansible/configs/zero-touch-base-rhel/pre_infra.yml, ansible/configs/zero-touch-base-rhel/pre_software.yml, ansible/configs/zero-touch-base-rhel/software.yml, ansible/configs/zero-touch-base-rhel/workloads.yml
Adding workload.yml to expand including roles.
```paste below
```
=> zero-touch-base-rhel, add workloads for expansion

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/workload.yml
=> RHTAP: Make Jenkins disabled as default

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/tasks/setup_jenkins.yml, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/deployment-nginx.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/nginx-webhook-proxy-pass.conf.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/pvc-nginx.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/service-nginx.yml.j2
Added Nginx for reverse proxy to api server (Header rewrite required)
```paste below
```
=> RHTAP: Use Nginx for proxy pass and header rewrite

ansible/roles/ansible_automation_platform_configuration/README.adoc, ansible/roles/ansible_automation_platform_configuration/defaults/main.yml, ansible/roles/ansible_automation_platform_configuration/meta/main.yml, ansible/roles/ansible_automation_platform_configuration/tasks/aap-configuration.yml, ansible/roles/ansible_automation_platform_configuration/tasks/main.yml, ansible/roles/ansible_automation_platform_configuration/tasks/ocp_token.yml, ansible/roles/ansible_automation_platform_configuration/tasks/ssh_keypair.yml, ansible/roles/ansible_automation_platform_configuration/vars/main.yml
Ansible Automation platform Configuration role is created for AAP 2.5.
This role can configure all AAP 2.5 unified web ui components i.e. controller, eda, hub and gateway. 
role: ansible_automation_platform_configuration
=> New role for AAP 2.5

ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/tasks/20-developer-customizations.yml
Remove unnecessary loop for package installation task.
setup_instructlab
```paste below
```
=> Update setup_instructlab role to remove package installation loop

ansible/roles_ocp_workloads/ocp4_workload_showroom/tasks/prepare-variables.yaml
fix errant creation on multi-user showroom.
=> ocp4_workload_showroom: move and update usernum creation to safer spot

ansible/collections/ansible_collections/agnosticd/ai/roles/setup_instructlab/tasks/40-instructlab-runtime-setup.yml
Previous PR had a quotation error. This PR fixes that.
setup_instructlab
```paste below
```
=> setup_instuctlab role bug, resolves quotation error

ansible/roles_ocp_workloads/ocp4_workload_jenkins/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_jenkins/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_jenkins/templates/deployment.yaml.j2
ocp4_workload_jenkins
```paste below
```
=> Jenkins: add capability to set jenkins password

ansible/roles_ocp_workloads/ocp4_workload_kubevirt/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_kubevirt/tasks/workload.yml
The Portworx Lab needs students to install Hyperconverged.
Make installing it optional (default remaining true).
=> Make installing Hyperconverged optional

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/aap-2.5.j2, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/admin_secret.j2
Adding more options to support various component of AAP2.5. Added variables for good user experience.
role: ocp4-workload-ansible-automation-platform
=> Extended the support of AAP2.5

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/templates/values-secret-medical-diagnosis.yaml.j2
Add medical diagnosis to available patterns 
=> Change role ocp4_workload_validated_pattern_deploy 

ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/tasks/aap/aap-2.5.yml, ansible/roles_ocp_workloads/ocp4_workload_ansible_automation_platform/templates/eda_cluster_rolebinding.j2
Added task to create cluster role binding for EDA service account for AAP2.5.
role: ocp4_workload_ansible_automation_platform
=> Adding EDA RoleBinding

ansible/roles/vscode-server/defaults/main.yml, ansible/roles/vscode-server/tasks/clone-workspace-repos.yml, ansible/roles/vscode-server/tasks/main.yml
Added clone-workshpace-repos tasks to clone repositories in user's workshpace/home. 
=> added workshpace repos

ansible/roles_ocp_workloads/ocp4_workload_authentication/tasks/setup_htpasswd.yml
Improve ocp4_workload_authentication adding some retries/delays
ocp4_workload_authentication role
=> [ocp4_workload_authentication] Add retries/delay to k8s tasks

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub/templates/cronjob-vault-es-fix.yml.j2, ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/templates/cronjob-vault-es-fix.yml.j2
=> RHDH: Fix post start script

ansible/roles/control-user/tasks/copy-contents.yml, ansible/roles/control-user/tasks/copy-files.yml, ansible/roles/control-user/tasks/copy-templates.yml, ansible/roles/control-user/tasks/create-directory.yml, ansible/roles/control-user/tasks/create-user.yml, ansible/roles/control-user/tasks/main.yml, ansible/roles/control-user/tasks/ssh-config.yml
Fixed yamllint error and added to task to enable password authentication in RHEL9
role: control-user
=> fixed yaml lint

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml
=> Fix orchestrator-helm-chart repo

ansible/roles_ocp_workloads/ocp4_workload_redhat_developer_hub_bootstrap/defaults/main.yml
=> Orchestrator: use migrated repository

ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_validated_pattern_deploy/templates/values-secret-industrial-edge.yaml.j2
SUMMARY
Add Industrial Edge to available patterns
ISSUE TYPE
=> Change role ocp4_workload_validated_pattern_deploy

ansible/roles/nginx_with_cert/defaults/main.yml
Reverts redhat-cop/agnosticd#8931
=> Revert "NGNINX WITH CERT- SET TO USE ZEROSSL BY DEFAULT IN FUTURE"

ansible/roles/ocp4-workload-debezium-demo/defaults/main.yaml, ansible/roles/ocp4-workload-debezium-demo/templates/postgresql.yaml.j2
=> ocp4-workload-debezium-demo -> Fix and parametize storageclass reference.

ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_openshift_ai/templates/redhat-datasciencecluster.yaml.j2
Add modelregistries parameter to OpenShift AI workload.
`ocp4_workload_openshift_ai`
=> add modelregistries namespace

ansible/configs/base-infra/default_vars_ec2.yml, ansible/configs/base-infra/files/ssh_config.j2, ansible/configs/base-infra/post_software.yml, ansible/configs/base-infra/pre_software.yml, ansible/roles/showroom/tasks/20-showroom-user-setup.yml, ansible/roles/showroom/templates/service_double_tty/tab_double_tty.j2, ansible/roles/showroom/templates/service_web1/tab_web1.j2, ansible/roles/showroom/templates/service_web2/tab_web2.j2, ansible/roles/user-create-ansible-service-account/templates/ssh_config.j2
AgnosticD config base-infra does not play well with two different ansible_user settings on the same cloud ie one for VM 1, 1 for VM 2.
This resolves that and enhances the showroom role used by base-infra
config/base-infra
roles/showroom
=> Base infra aws user fixes 01

tools/runner/README.md
Small PR - fixes the `roles_ocp_workloads` reference in `tools/runner/README.md`.
```paste below
```
=> Update `roles_ocp_workloads` reference

htpasswd
=> Remove htpasswd

ansible/roles_ocp_workloads/ocp4_workload_gitops_bootstrap/README.md, ansible/roles_ocp_workloads/ocp4_workload_gitops_bootstrap/tasks/workload.yml
=> workload_gitops_boostrap: read multi-user configmaps

ansible/roles/open-env-gcp-add-user-to-project/tasks/main.yml
=> yaml indent error

ansible/roles_ocp_workloads/ocp4_workload_nginxplus/templates/nginx-ingress-controller.j2
updated ingress-controller j2 for new nginx ingress controller image
ocp4_workload_nginxplus
=> updated ingress-controller j2 for new nginx ingress controller image

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Set a local guides for VM for RAD

ansible/roles_ocp_workloads/ocp4_workload_gitops_bootstrap/tasks/workload.yml
=> workload_gitops_bootstrap allow suspended

ansible/roles_ocp_workloads/ocp4_workload_nginxplus/tasks/workload.yml, ansible/roles_ocp_workloads/ocp4_workload_nginxplus/templates/nginx-ingress-controller.j2, ansible/roles_ocp_workloads/ocp4_workload_nginxplus/templates/nginx-license-secret.j2
update ocp4_workload_nginxplus with license secret
ocp4_workload_nginxplus 
```
=> update ocp4_workload_nginxplus with license secret

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Update the copy permission for RAD VM

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Fix ssh connection after reboot

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Update reboot command

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Update reboot module

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Fix the delay syntax error

ansible/configs/ocp4-cluster/requirements.yml
Trying new version of the collection, which retries the installation in case of is back to "ready"
ocp4-cluster config
=> [ocp4-cluster] Update rhpds.assisted_installer version

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Add async to igore an interactive auth

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Fix the sync syntax

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Add privilege to the reboot module

ansible/cloud_providers/none_destroy_env.yml, ansible/collections/ansible_collections/agnosticd/ibm/README.md, ansible/collections/ansible_collections/agnosticd/ibm/galaxy.yml, ansible/collections/ansible_collections/agnosticd/ibm/meta/runtime.yml, ansible/collections/ansible_collections/agnosticd/ibm/playbooks/ibm_role_runner.yml, ansible/collections/ansible_collections/agnosticd/ibm/plugins/README.md, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/README.md, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/defaults/main.yml, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/handlers/main.yml, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/meta/main.yml, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/tasks/main.yml, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/tasks/scenarios/ibm_instructlab_service_delete.yml, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/tasks/scenarios/ibm_instructlab_service_destroy.yml, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/tasks/scenarios/ibm_instructlab_service_provision.yml, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/templates/instructlab-as-a-service.j2, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/tests/inventory, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/tests/test.yml, ansible/collections/ansible_collections/agnosticd/ibm/roles/ibm_instructlab_service/vars/main.yml
Adds the ability to create dedicated Trusted profiles for IBM InstructLab as a Service
Makes very minor mods to `config/minimal` (currently the only CI using it)
agnosticd.ibm.ibm_instructlab_service
=> Ibm instructlab 01

ansible/roles/rad_setup_instructlab/files/rad.desktop, ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Reorder the desktop icon task

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Add granite-3.1-8b-instruct-Q4_K_M.gguf for RAD Desktop

ansible/roles/novnc/tasks/main.yml
=> Set a lab-ui-url for RHEL VM

ansible/roles/novnc/tasks/main.yml
=> Fix the quote error

ansible/roles/novnc/tasks/main.yml
=> Update the Lab UI URL

ansible/roles/novnc/tasks/main.yml
=> Update Lab URL for RHEL VM

ansible/roles_ocp_workloads/ocp4_workload_rhacs/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs/readme.adoc, ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/workload.yml
=> ocp4_workload_rhacs: fix route to central

ansible/roles_ocp_workloads/ocp4_workload_trusted_application_pipeline/files/jenkins-global-config.xml
=> Jenkins: Fix predicate script

ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/post_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/remove_workload.yml, ansible/roles_ocp_workloads/ocp4_workload_rhacs/tasks/workload.yml
Add retries in ocp4_workload_rhacs
Workload ocp4_workload_rhacs
=> Add retries in ocp4_workload_rhacs

tools/execution_environments/ee-multicloud-public/requirements.yml
Add ibm.cloudcollection collection for IBM Resource Group 
ee-multicloud-public  image
=> [ee-multicloud-public] Update requirements.yml to add ibm.cloudcollection

ansible/roles/showroom/templates/service_double_tty/tablink_double_tty.j2
=> Showroom: Revert removal of terminal tab id

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> enable GPU on RHEL9 VM for RAD and RH1 Lab24

ansible/roles/rad_setup_instructlab/tasks/50-dev-tools-setup.yml
=> Fix timeout in RAD VM

ansible/configs/zero-touch-base-rhel/instructlab_setup.yml
zero-touch-base-rhel, fix instructlab setup script bug
removes mutually exclusive parameters.
```paste below
```
=> zero-touch-base-rhel, fix instructlab setup script bug

ansible/configs/zero-touch-base-rhel/instructlab_setup.yml
Add token ref for hugging face downloads.
```paste below
```
=> zero-touch-base-rhel, add token for instructlab hugging face login

ansible/roles_ocp_workloads/ocp4_workload_kasten_k10/templates/objectbucketclaim.yaml.j2
Fix for K10 Objectbucketclaims in multi-user
=> Fix bucket name for multi-user K10

.github/workflows/build-ee.yml, tools/execution_environments/ee-multicloud-public/install_binaries.sh
build is failing, see https://github.com/redhat-cop/agnosticd/actions/runs/13292743508
=> Revert "Add multi-platform support for execution environment (#8951)"

.github/workflows/build-ee.yml, tools/execution_environments/ee-multicloud-public/install_binaries.sh
* feat(ee-multicloud-public): add multi-platform support for execution environments
- Updated `install_binaries.sh` to dynamically detect system architecture (`ARCH`)
- Modified OpenShift CLI (`oc`) installation to use RHEL 8 version with architecture-specific tarballs.
- Adjusted AWS CLI download URL to include architecture detection.
- Added placeholder for Bitwarden CLI installation, as it does not support ARM64 yet.
* Update build-ee workflow adding support for multi arch
* Add QEMU setup for multi-platform builds in build-ee.yml
- Added QEMU setup using `docker/setup-qemu-action@v2` to enable emulation for multiple architectures.
- Installed `qemu` and `binfmt-support` as dependencies to ensure proper handling of multi-platform builds.
* fix(workflow): adjust QEMU setup order for …
=> Add multi-platform support for execution environment (#8951)

ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/files/nodenetworkconfigurationpolicy.yaml, ansible/roles_ocp_workloads/ocp4_workload_virt_roadshow_multi_user/tasks/workload.yml
ocp4_workload_virt_roadshow_multi_user config
=> [ocp4_workload_virt_roadshow_multi_user] Adding flatnetwork functionality for OCP Virtualization Roadshow

ansible/roles_ocp_workloads/ocp4_workload_external_odf/tasks/workload.yml
Missed a filename change in the logic when updating the workload.\
ocp4_workload_external_odf
=> Fixed the filename but not the code using it. :-(

ansible/configs/zero-touch-base-rhel/instructlab_setup.yml
Update the setup tasks for instructlab to correct venv path.
```paste below
```
=> zero-touch-base-rhel update instructlab setup python/venv path

ansible/configs/zero-touch-base-rhel/instructlab_setup.yml
Modifies instructlab setup tasks adding "--non-interactive" option avoid hangs
```paste below
```
=> zero-touch-base-rhel instructlab setup, run in non-interactive mode

ansible/configs/zero-touch-base-rhel/post_software.yml
Run setup tasks as the instruct user
```paste below
```
=> zero-touch-base-rhel, instructlab setup, become_user: instruct

ansible/roles_ocp_workloads/ocp4_workload_ols/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_ols/tasks/install_ols_operator.yml
Disable catalog snapshot and enable namespace watch instead all namespaces
ocp4_workload_ols role
=> [ocp4_workload_ols] Update install_ols_operator.yml

ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
-->
Adding new parameter for play, currently failing without parameter set. 
ansible/roles/open-env-azure-add-user-to-subscription
```
=> Add Tenant ID

ansible/roles/open-env-azure-add-user-to-subscription/tasks/main.yml, ansible/roles/open-env-azure-remove-user-from-subscription/tasks/main.yml
update object ID for azure subscription
azure subscription roles
```paste below
```
=> update object ID for azure subscription

ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/defaults/main.yml, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/tasks/setup_ec.yml
EC image moved from quay.io.  Require new image.
=> RHTAS: Use updated image for ec cli

ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/defaults/main.yml
=> Enhancing Dev: Use quay image

ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/validate-insecured.sh.j2, ansible/roles_ocp_workloads/ocp4_workload_tap_wks_sno_setup/templates/validate-secured.sh.j2
=> Enhancing: Force json response

ansible/roles_ocp_workloads/ocp4_workload_platform_engineering_workshop/tasks/orchestrator.yml, ansible/roles_ocp_workloads/ocp4_workload_platform_engineering_workshop/templates/orchestrator/orchestrator-application.yaml.j2
Extract gitlab token from secret and add as variable for rhdh orchestrator
Platform Engineering Workshop: roles_ocp_workloads/ocp4_workload_platform_engineering_workshop
```paste below
```
=> Added gitlab token for orchestrator

ansible/roles_ocp_workloads/ocp4_workload_jenkins_tap_wks_setup/tasks/setup_lab_scripts.yml
=> LB1696: Remove templating for deleted files

ansible/roles_ocp_workloads/ocp4_workload_jenkins_tap_wks_setup/templates/deploy-app.sh.j2, ansible/roles_ocp_workloads/ocp4_workload_jenkins_tap_wks_setup/templates/validate-image.sh.j2
=> lb1696: fix script

ansible/configs/ocp4-cluster/default_vars_openshift_cnv.yml
It seems omit doesnt work as expected here
ocp4-config
=> [ocp4-cluster/cnv] Fix userdata/metadata default values

ansible/roles_ocp_workloads/ocp4_workload_jenkins_tap_wks_setup/templates/acs-signature-policy.json
=> LB1696: Rename acs policy

ansible/roles/host-ocp4-assisted-installer/tasks/main.yaml, ansible/roles/host-ocp4-assisted-installer/vars/main.yaml
>
Bad logic was introduced in previous PR
=> [host-ocp4-assisted-installer] fix network name variable

ansible/roles_ocp_workloads/ocp4_workload_jenkins_tap_wks_setup/defaults/main.yml
=> LB1696: Change default config

ansible/configs/lb1942-binder/README.adoc, ansible/configs/lb1942-binder/default_vars.yml, ansible/configs/lb1942-binder/default_vars_ec2.yml, ansible/configs/lb1942-binder/destroy_env.yml, ansible/configs/lb1942-binder/infra.yml, ansible/configs/lb1942-binder/post_infra.yml, ansible/configs/lb1942-binder/post_software.yml, ansible/configs/lb1942-binder/pre_infra.yml, ansible/configs/lb1942-binder/pre_software.yml, ansible/configs/lb1942-binder/requirements.yml, ansible/configs/lb1942-binder/sample_vars.yml, ansible/configs/lb1942-binder/software.yml, ansible/configs/lb1942-binder/stop.yml
=> LB1942: Binder

ansible/roles_ocp_workloads/ocp4_workload_ols/tasks/workload.yml
=> (WIP) Updated to create default namespace before the workload
